#!/bin/sh

#--------- Configuration: ------

# Directories containing source files:
SRC="${BETALIB}/persistentstore"

# Files to include in interface. The order given here will
# be the order they appear in in the generated interface.
FILES="\
persistentstore.bet \
clientinterface.bet \
serverinterface.bet \
transaction.bet \
notification.bet \
lockmanager.bet \
lockmanagerinterface.bet \
notificationmanager.bet \
sharedpersistentstore.bet \
sharedpsnotifications.bet \
perslib.bet \
samefile.bet \
"

MAKEINT=../../bin/beta2int.perl
#MAKEHTML=../../bin/int2html.perl
MAKEHTML=../../bin/int2frames.perl

. ../../bin/makeHTML.sh
