#!/bin/sh

#--------- Configuration: ------

# Directories containing source files:
SRC="${BETALIB}/persistentstore"

# Files to include in interface. The order given here will
# be the order they appear in in the generated interface.
FILES="\
persistentstore.bet \
shared/clientinterface.bet \
shared/serverinterface.bet \
shared/transaction.bet \
shared/notification.bet \
shared/lockmanager.bet \
shared/lockmanagerinterface.bet \
shared/notificationmanager.bet \
shared/sharedpersistentstore.bet \
shared/sharedpsnotifications.bet \
shared/perslib.bet \
shared/samefile.bet \
"

MAKEINT=../../bin/beta2int.perl
#MAKEHTML=../../bin/int2html.perl
MAKEHTML=../../bin/int2frames.perl

. ../../bin/makeHTML.sh
