#!/bin/csh

rm -f lidskjalv.int lidskjalv.rtf

echo ">>>>>>>>>>>>>>>>> INTERFACE GENERATION"
foreach file (	\
		guienv.bet \
		stddialogs.bet \
		controls.bet \
		fields.bet \
		figureitems.bet \
		scrolllists.bet \
		graphmath.bet \
		graphics.bet \
		styledtext.bet \
		guienvactions.bet \
		controlsactions.bet \
		fieldsactions.bet \
		guienvall.bet \
 		guienvsystemenv.bet \
	     )
	if (-e $file) then
		echo $file
		cat $file:r.bet | ~beta/doc/miadoc/bin/interfaces.perl >> lidskjalv.int
	else
		echo ../sources/$file NOT FOUND 
		exit(0)
	endif
end #foreach

echo ">>>>>>>>>>>>>>>>> Creating RTF file"
cat ~beta/doc/miadoc/inputs/RTF/RTF.7.0.header                >  lidskjalv.rtf
(expand lidskjalv.int | ~beta/doc/miadoc/bin/RTF.7.0.perl -s) >> lidskjalv.rtf
cat ~beta/doc/miadoc/inputs/RTF/RTF.7.0.trailer               >> lidskjalv.rtf
#rm lidskjalv.int
echo ">>>>>>>>>>>>>>>>> DONE"
