BETA = beta+

all:
	$(BETA) guienvall guienvsystemenv;\
        $(BETA) -d guienvall guienvsystemenv

tags:
	etags *.bet private/*.bet private/X11/*.bet private/macintosh/*.bet demo/*.bet demo/ReferenceDemos/*.bet demo/TutorialDemos/*.bet private/X11/external/makefile
