BETA = beta

all:
	$(BETA) guienvall guienvsystemenv;\
        $(BETA) -d guienvall guienvsystemenv

tags:
	etags *.bet private/*.bet private/X11/*.bet private/macintosh/*.bet private/winnt/*.bet utils/*.bet utils/private/*.bet utils/private/X11/*.bet utils/private/winnt/*.bet utils/private/macintosh/*.bet demo/ReferenceDemos/*.bet demo/TutorialDemos/*.bet private/X11/external/makefile
