BETA = beta+

all:
	$(BETA) --quiet guienvall guienvsystemenv;\
        $(BETA) --quiet -g guienvall guienvsystemenv

tags:
	etags *.bet private/*.bet private/X11/*.bet private/macintosh/*.bet demo/*.bet demo/ReferenceDemos/*.bet demo/TutorialDemos/*.bet private/X11/external/makefile
