#!/bin/csh

rm -f interfaces.all interfaces.RTF

echo ">>>>>>>>>>>>>>>>> INTERFACE GENERATION"
foreach file (	UIenv.bet \
		controls.bet \
		fields.bet \
		scrollingLists.bet \
		figureItems.bet \
		stdDialogs.bet \
		graphics.bet \
		raster.bet \
		styledText.bet \
		UIenvAll.bet \
		graphMath.bet \
		layout.bet)
	if (-e $file) then
		echo $file
		cat $file:r.bet | ~beta/miadoc/bin/interfaces.perl >> interfaces.all
	else
		echo $file NOT FOUND 
		exit(0)
	endif
end #foreach

echo ">>>>>>>>>>>>>>>>> Creating RTF file"
cat ~beta/miadoc/inputs/RTF/RTF.header            >  interfaces.RTF
(expand interfaces.all | ~beta/miadoc/bin/RTF.perl) >> interfaces.RTF
rm interfaces.all
cat ~beta/miadoc/inputs/RTF/RTF.trailer           >> interfaces.RTF
echo ">>>>>>>>>>>>>>>>> DONE"
