#!/bin/sh

#--------- Configuration: ------

# Directories containing source files:
SRC="${BETALIB}/Xt"

# Files to include in interface. The order given here will
# be the order they appear in in the generated interface.
FILES="\
motif/basics.bet \
motif/callbackstruct.bet \
motif/primitive.bet \
motif/arrowbutton.bet \
motif/separator.bet \
motif/scrollbar.bet \
motif/label.bet \
motif/cascadebutton.bet \
motif/drawnbutton.bet \
motif/pushbutton.bet \
motif/togglebutton.bet \
motif/lists.bet \
motif/texts.bet \
motif/manager.bet \
motif/bulletinboard.bet \
motif/form.bet \
motif/drawingarea.bet \
motif/frame.bet \
motif/rowcolumn.bet \
motif/scrolledwindow.bet \
motif/mainwindow.bet \
motif/scale.bet \
motif/panedwindow.bet \
motif/selectionbox.bet \
motif/fileselectionbox.bet \
motif/command.bet \
motif/messagebox.bet \
motif/menushell.bet \
motif/dialogshell.bet \
motif/vendorshell.bet \
motif/gadget.bet \
motif/labelgadget.bet \
motif/cascadebuttongadget.bet \
motif/pushbuttongadget.bet \
motif/togglebuttongadget.bet \
motif/arrowbuttongadget.bet \
motif/separatorgadget.bet \
motifenv.bet \
allmotif.bet \
"

MAKEINT=../../../bin/beta2int.perl
#MAKEHTML=../../../bin/int2html.perl
MAKEHTML=../../../bin/int2frames.perl
OPTIONS="-x"

. ../../../bin/makeHTML.sh
