#!/usr/local/bin/perl -s


local ($cmd);
local ($verbose) = ($v);
local ($BETALIB) = $ENV{'BETALIB'};

$cmd = "catman -n -M $BETALIB/man 1";
print STDERR "$cmd\n" if ($verbose);
print STDERR `$cmd`;

$cmd = "catman -w -M $BETALIB/man 1";
print STDERR "$cmd\n" if ($verbose);
print STDERR `$cmd`;

1;
