default:
	@echo You must specify a target.

tags:
	etags tar/*.dotar dat/*.dodat tape/*.dotape tar/*.sh dat/*.sh tape/*.sh files/*.files update/*.update misc/*.sh

clean:
	/bin/rm -f *~ tar/*~ tape/*~ dat/*~ files/*~ update/*~
