#!/bin/sh
echo %%%%%%%%%% CountChar
cp CountChar.bet data1
CountChar
echo %%%%%%%%%% CountChar1 CountChar1.bet
CountChar1 CountChar1.bet
echo %%%%%%%%%% CountChar2 CountChar2.bet
CountChar2 CountChar2.bet
echo %%%%%%%%%% DirTable .
DirTable .
echo %%%%%%%%%% ExploreTypes
ExploreTypes
echo %%%%%%%%%% FileCount: type lines
FileCount FileCount.bet
echo %%%%%%%%%% HelloWorld
HelloWorld
echo %%%%%%%%%% ListDir .
ListDir .
echo %%%%%%%%%% MultipleAssignment
MultipleAssignment
echo %%%%%%%%%% Multiplication1
Multiplication1
echo %%%%%%%%%% Multiplication2
Multiplication2
echo %%%%%%%%%% Multiplication3
Multiplication3
echo %%%%%%%%%% MultiplicationTable: type 3 5
MultiplicationTable
echo %%%%%%%%%% Person
Person
echo %%%%%%%%%% QuickSort type: 3 55 77 3 444 664 3454 2 7 4 
QuickSort
echo %%%%%%%%%% SaveListDir .
SaveListDir .
echo %%%%%%%%%% SaveListDir2 .
SaveListDir2 .
echo %%%%%%%%%% SaveListDir3 .
rm -r fileStore
SaveListDir3 .
echo %%%%%%%%%% GetListDir
GetListDir
echo %%%%%%%%%% SimpleTypes
SimpleTypes
echo %%%%%%%%%% SquareRoot
SquareRoot
echo %%%%%%%%%% StaticAndDynamic
StaticAndDynamic
echo %%%%%%%%%% StaticAndDynamic2
StaticAndDynamic2

echo Remember to run the following programs manually:

echo Clock
echo ClockTexteditor
echo Hello
echo Scale
echo Seconds
echo TextEditor

