#!/bin/sh 

#--------- Configuration: ------

SRC=${BETALIB}/bifrost

FILES="\
Bifrost.bet \
EPSfile.bet \
ColorNames.bet \
Palette.bet \
PredefinedGO.bet \
RasterGrays.bet \
SelectionPicture.bet \
"

MAKEINT=../../bin/beta2int.perl
# A speciality for Bifrost:
INTPOST=./headers.perl
#MAKEHTML=../../bin/int2html.perl
MAKEHTML=../../bin/int2frames.perl

. ../../bin/makeHTML.sh
