#!/bin/sh 

#--------- Configuration: ------

SRC=${BETALIB}/bifrost

FILES="\
Bifrost.bet \
EPSfile.bet \
ColorNames.bet \
Palette.bet \
PredefinedGO.bet \
RasterGrays.bet \
SelectionPicture.bet \
"

MAKEINT=../../bin/beta2int.perl
MAKEHTML=../../bin/int2html.perl

# A speciality for Bifrost:
HEADERS=./headers.perl

#----- Don't change below ! -----

/bin/rm -f *.int
echo Making interface descriptions for $SRC.
echo ""
for file in $FILES
do
    INT=`basename $SRC/$file .bet`.int
    echo Making $INT from $SRC/$file ...
    expand $SRC/$file | $MAKEINT | $HEADERS > $INT
done

echo Creating HTML:
$MAKEHTML -v *.int
echo done.
