#!/bin/sh

#--------- Configuration: ------

SRC=${BETALIB}/bifrost
DST=.

FILES1="\
Bifrost.bet \
EPSfile.bet \
"

FILES2="\
Palette.bet \
PredefinedGO.bet \
RasterGrays.bet \
SelectionPicture.bet \
"

# ColorNames is handled specially, see below.

INT=interface.int
HTML=../interface.html

MAKEINT=../../bin/beta2int.perl
MAKEHTML=../../bin/int2html.perl
HEADERS=./headers.perl

#----- Don't change below ! -----

/bin/rm -f $DST/$INT $DST/$HTML

echo Making interface descriptions for $SRC.
echo ""
echo Making $DST/$INT...
touch $DST/$INT
for file in $FILES1
do
	echo $SRC/$file
	expand $SRC/$file | $MAKEINT | $HEADERS >> $DST/$INT
done

echo "$SRC/ColorNames.bet (special)"
expand $SRC/ColorNames.bet | head -18 | $MAKEINT | $HEADERS >> $DST/$INT
echo '...'                                                  >> $DST/$INT
expand $SRC/ColorNames.bet | tail -3                        >> $DST/$INT

for file in $FILES2
do
	echo $SRC/$file
	expand $SRC/$file | $MAKEINT | $HEADERS >> $DST/$INT
done

echo Creating $HTML...
$MAKEHTML < $DST/$INT   > $DST/$HTML
echo done.
