// Deep_Thought.idl : IDL source for Deep_Thought.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (Deep_Thought.tlb) and marshalling code.
//
// File created by Kristian Lippert, DTI, 980205
// for Phase 7, COT Case 3: Pilot Application
// This is the shared version that contains the Hello.world interface method
// The GUIDS for the interfaces as in phase 2, 3, and 4:
// ICalc :  6FB6D32F-9E06-11D1-AE78-0020AF72F3D6
// ICalc2:  08407980-9e15-11d1-ae78-0020af72f3d6
// IHello:  a3985ef0-b4e6-11d1-aabb-006097636471
// IConv :  ed297100-9e0b-11d1-ae78-0020af72f3d6
//
// The components should be registered under the ProgId's or ClassID:

//        Version independant V. dependant		   GUID/UUID 
// Calc:  Deep_Thought.Calc   Deep_Thought.Calc.5 88bc6440-ab04-11d1-b55a-00600889e712 
// Conv:  Deep_Thought.Conv   Deep_Thought.Conv.5 bd4067e0-ab04-11d1-b55a-00600889e712  
// The client should try to resolve in the above order
// The client should notify which resolvement method it chooses (i.e. using a message box)

import "oaidl.idl";
import "ocidl.idl";

	[
		uuid(6FB6D32F-9E06-11D1-AE78-0020AF72F3D6),
		dual,
		helpstring("ICalc Interface"),
		pointer_default(unique)
	]
	interface ICalc : IDispatch
	{
		[helpstring("method Add")] HRESULT Add([in] long v1, [in] long v2, [out, retval] long* res);
		[helpstring("method Subtract")] HRESULT Subtract([in] long v1, [in] long v2, [out, retval] long* res);
		[helpstring("method Multiply")] HRESULT Multiply([in] long v1, [in] long v2, [out, retval] long* res);
		[helpstring("method Divide")] HRESULT Divide([in] long v1, [in] long v2, [out, retval] long* res);
		[helpstring("method Modulus")] HRESULT Modulus([in] long v1, [in] long v2, [out, retval] long* res);
	};
	[
		uuid(08407980-9e15-11d1-ae78-0020af72f3d6),
		dual,
		helpstring("ICalc2 Interface"),
		pointer_default(unique)
	]
	interface ICalc2 : IDispatch
	{
		[helpstring("method Power")] HRESULT Power([in] long v, [out, retval] long* res);
	};

	[
		uuid(a3985ef0-b4e6-11d1-aabb-006097636471),
		dual,
		helpstring("IHello Interface"),
		pointer_default(unique)
	]
	interface IHello : IDispatch
	{
		[helpstring("method World")] HRESULT World([out, retval] BSTR* res);
	};

	[
		uuid(ed297100-9e0b-11d1-ae78-0020af72f3d6),
		dual,
		helpstring("IConv Interface"),
		pointer_default(unique)
	]
	interface IConv : IDispatch
	{
		[helpstring("method Hex2Dec")] HRESULT Hex2Dec([in] BSTR v, [out,retval] long *res);
		[helpstring("method Dec2Hex")] HRESULT Dec2Hex([in] long v, [out,retval] BSTR *res);
	};


[
	uuid(6FB6D322-9E06-11D1-AE78-0020AF72F3D6),
	version(1.0),
	helpstring("Deep_Thought 1.0 Type Library")
]
library DEEP_THOUGHTLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[
		uuid(88bc6440-ab04-11d1-b55a-00600889e712),
		helpstring("Calc Class")
	]
	coclass Calc
	{
		[default] interface ICalc;
		interface ICalc2;
		interface IHello;
	};
	[
		uuid(bd4067e0-ab04-11d1-b55a-00600889e712),
		helpstring("Conv Class")
	]
	coclass Conv
	{
		[default] interface IConv;
	};
};
