/*****************************************************************
 IDL Specification for ICalc Interface.  24/11-97 Peter P. & Kåre

 DESCRIPTION:
 This IDL file is included by the ICalcTLB.IDL file.

 GUIDS:
 Do not tamper with the GUID, it must be the same across applications
******************************************************************/
[
    uuid(2F9FBD42-64AE-11D1-B039-0020AF3BC782),
    version(1.0),
    helpstring("IUnknown interface for ICalc"),
    hidden
]
interface ICalc : IUnknown {
    import "unknwn.idl";
    HRESULT _stdcall add([in] int n1, [in] int n2, [out, retval] int *res);
    HRESULT _stdcall sub([in] int n1, [in] int n2, [out, retval] int *res);
    HRESULT _stdcall mul([in] int n1, [in] int n2, [out, retval] int *res);
    HRESULT _stdcall div([in] int n1, [in] int n2, [out, retval] int *res);
};


