/*****************************************************************
 IDL Specification for ICalc Typelibrary.  24/11-97 Peter P. & Kåre

 DESCRIPTION:
 This IDL file will generate a type library, proxy and stub source
 when compiled with MIDL.

 GUIDS:
 To use this IDL file, you must replace the GUID for the CoClass
 (2F9FBD43-64AE-11D1-B039-0020AF3BC782), since this will be unique
 for your implementation. The GUID for the type library might need
 to be replaced, but the GUID for the interface ICalc _must_ remain
 the same.
******************************************************************/
interface ICalc;

[
  uuid(2F9FBD41-64AE-11D1-B039-0020AF3BC782),
  version(1.0),
  helpstring("Type library for ICalc interface")
]
library libCalc
{
    import "ICalc.IDL";

    [
      uuid(ed99fb8a-9d68-11d1-a2e2-00c04fb954fb),
      version(1.0),
      helpstring("CoClass for ICalc interface")
    ]
    coclass Calc {
        [default] interface ICalc;
    };
};
