/*****************************************************************
 IDL Specification for IConv Interface.  24/11-97 Peter P. & Kåre

 DESCRIPTION:
 This IDL file is included by the IConvTLB.IDL file.

 GUIDS:
 Do not tamper with the GUID, it must be the same across applications
******************************************************************/
typedef int dec;
typedef char* hex;

[
    uuid(2F9FBD45-64AE-11D1-B039-0020AF3BC782),
    version(1.0),
    helpstring("IUnknown interface for IConv"),
    hidden
]
interface IConv : IUnknown {
    import "unknwn.idl";
    HRESULT _stdcall dec2hex([in] dec n, [out, retval, string] hex *res);
    HRESULT _stdcall hex2dec([in, string] hex n, [out, retval] dec *res);
};



