typedef struct tagPoint3d
{
	double x ;
	double y ;
	double z ;
} Point3d;

typedef           int     int_alias;
typedef           Point3d Point3d_alias1;


// typedef struct tagPoint3d Point3d_alias2; /* OK */
// typedef Point3d_pointer  *Point3d_pointer_pointer;
