typedef struct {
        DECIMAL decVal1;
    } __VARIANT_NAME_2;

struct tagVARIANT2 {
    struct {
        DECIMAL decVal1;
        DECIMAL decVal2;
    } __VARIANT_NAME_1;
};

#if 1
typedef union {
        DECIMAL decVal1;
    } __VARIANT_NAME_1;

struct tagVARIANT1 {
    union {
        DECIMAL decVal1;
        DECIMAL decVal2;
    } __VARIANT_NAME_1;
};
#endif