// simple cases

typedef struct 
{
	double x ;
} Point1D;

typedef struct tagPoint2d
{
	double x ;
	double y ;
} *Point2D_Pointer;

typedef struct tagPoint3d
{
	double x ;
	double y ;
	double z ;
} Point3d, *Point3D_Pointer;
