// full struct

typedef struct tagPoint2d Point2d; // tag not yet defined

struct tagPoint2d
{
	double x ;
	double y ;
}; // no name

typedef struct tagPoint3d Point3d_alias; // tag not yet defined

typedef struct tagPoint3d
{
	double x ;
	double y ;
	double z ;
} Point3d, *Point3d_pointer, Point3d_alias0;

typedef Point3d_pointer  *Point3d_pointer_pointer;
typedef           Point3d Point3d_alias1;
typedef struct tagPoint3d Point3d_alias2;
