#!/bin/sh
##############################################################################
# installation site specific:
TO=olm
CC=`whoami`
BETALIB=${BETALIB-/usr/local/lib/beta}
. $BETALIB/configuration/r4.0/env.sh

# end installation site specific
##############################################################################
# application specific:

APPLICATION=beta
LOCATION="$BETALIB"/system/v5.2
# try binary first
EXECNAME="$MACHINETYPE"Bbeta
if [ ! -f "$LOCATION/$EXECNAME" ]
then
  # fall back on non-binary
  EXECNAME="$MACHINETYPE"beta
fi

# what about $BETAOPTS $betaopt

BETASTAT=${BETASTAT-yes}
STATFILE="$BETALIB"/statistics/beta/betastat

BETAREPORT=${BETAREPORT-yes}

# end application specific
##############################################################################
#     PLEASE DO NOT CHANGE BELOW THIS LINE
##############################################################################

export BETALIB

. $BETALIB/bin/exectool

