#!/bin/sh

BETALIB=${BETALIB-/usr/local/lib/beta}
export BETALIB   # needed if pathhandler is used
. $BETALIB/configuration/env.sh

LD_LIBRARY_PATH=${BETALIB}/system/v5.1.1/${objdir}:${LD_LIBRARY_PATH}
export LD_LIBRARY_PATH

# try binary first
compiler="$BETALIB"/system/v5.1.1/"$MACHINETYPE"Bbeta
if [ ! -f $compiler ]
then
  # fall back on non-binary
  compiler="$BETALIB"/system/v5.1.1/"$MACHINETYPE"beta
fi

exec $compiler $BETAOPTS $betaopt "$@"

