#!/bin/sh
##############################################################################
# installation site specific:
TO=olm
CC=`whoami`
BETALIB=${BETALIB-/usr/local/lib/beta}
. $BETALIB/configuration/env.sh

# end installation site specific
##############################################################################
# application specific:

APPLICATION=beta
LOCATION="$BETALIB"/system/v5.2
# try binary first
EXECNAME="$MACHINETYPE"Bbeta
if [ ! -f "$LOCATION/$EXECNAME" ]
then
  # fall back on non-binary
  EXECNAME="$MACHINETYPE"beta
fi

# what about $BETAOPTS $betaopt ??

BETASTAT=${BETASTAT-no}
STATLOCATION="$BETALIB"/statistics/"$APPLICATION"
STATFILE="$STATLOCATION"/"$APPLICATION"stat

BETAREPORT=${BETAREPORT-no}
BETAREPORT_EMAIL=${BETAREPORT_EMAIL-yes}
BETAREPORT_WWW=${BETAREPORT_WWW-yes}
REPORTDIR="$STATLOCATION"/reports 
TOOLCOUNTER="$REPORTDIR"/"$APPLICATION".counter
TOOLINDEX="$REPORTDIR"/index.html

# REPORTDIR must be writeable by all
# STATFILE and TOOLINDEX must exist and be writeable by all
# TOOLCOUNTER must exist and be writeable by all AND intialized with 1
# e.g. by: cat >sif.counter and enter 1 <CR> ctrl-d
# all this is done by the script 'prepareReportDir' in bin/admin
# usage: pwd $STATLOCATION; prepareReportDir $APPLICATION

# end application specific
##############################################################################
#     PLEASE DO NOT CHANGE BELOW THIS LINE
##############################################################################

export BETALIB

. $BETALIB/bin/exectool

