#!/bin/sh

BETALIB=${BETALIB-/usr/local/lib/beta}
. $BETALIB/configuration/env.sh

if [ "$1" = "" ]
then
   echo "Usage: $0 <grammar-name>"
   exit 1
fi

if [ "$MACHINETYPE" = "SGI" ]
then
  LD_LIBRARY_PATH="$BETALIB"/bobsgen/v1.5/${objdir}:${LD_LIBRARY_PATH}
  export LD_LIBRARY_PATH
fi

echo bobsit $1-parser.bobs

"$BETALIB"/bobsgen/v1.5/"$MACHINETYPE"exbobs < $1-parser.bobs 
mv -f bobslist  $1-parser.lst


echo "End-of-BOBS"

if [ ! -s tables ] 
then
  echo ERRORS IN GRAMMAR
  echo Look at $1-parser.lst
  exit 1
elif egrep "ERROR IN.*TO SMALL" $1-parser.lst \
 || egrep "END OF FILE ENTCOUNTERED" $1-parser.lst \
 || egrep "EOF ENCOUNTERED IN READING THE GRAMMAR" $1-parser.lst \
 || egrep "The grammar is NOT LALR\(1\)" $1-parser.lst \
 || egrep "ERROR\(S\) IN INPUT" $1-parser.lst \
 || egrep "ERROR\(S\) IN GRAMMAR" $1-parser.lst
then
  echo ERRORS IN GRAMMAR
  echo Look at $1-parser.lst
fi

if [ -s tables ] 
then
  echo Creating tables
  eval ${BETALIB}/bobsgen/v1.5/${MACHINETYPE}tabc tables $1-parser
else
  exit 1
fi