#!/bin/sh

BETALIB=${BETALIB-/usr/local/lib/beta}
. $BETALIB/configuration/env.sh

if [ "'$1" = "'-b" ]
then
    boot="/boot"
    shift
else
    boot=""
fi

if [ "$1" = "" ]
then
   echo "Usage: $0 <grammar-name>"
   exit 1
fi

if [ "$MACHINETYPE" = "SGI" ]
then
  LD_LIBRARY_PATH="$BETALIB"/bin/${objdir}:${LD_LIBRARY_PATH}
  export LD_LIBRARY_PATH
fi

grammarname=$1;

# We don't need or understand the -metagram option, so skip it.
# (except the tabc command, which needs it.)
if [ "$1" = "-metagram" ]
then
    option1=$1;
    option2=$2;
    grammarname=$3;
fi

echo bobsit $grammarname-parser.bobs

"$BETALIB"$boot/bin/${objdir}/exbobs < $grammarname-parser.bobs 
mv -f bobslist  $grammarname-parser.lst


echo "End-of-BOBS"

if [ ! -s tables ] 
then
  echo ERRORS IN GRAMMAR
  echo Look at $grammarname-parser.lst
  exit 1
elif egrep "ERROR IN.*TO SMALL" $grammarname-parser.lst \
 || egrep "END OF FILE ENTCOUNTERED" $grammarname-parser.lst \
 || egrep "EOF ENCOUNTERED IN READING THE GRAMMAR" $grammarname-parser.lst \
 || egrep "The grammar is NOT LALR\(1\)" $grammarname-parser.lst \
 || egrep "ERROR\(S\) IN INPUT" $grammarname-parser.lst \
 || egrep "ERROR\(S\) IN GRAMMAR" $grammarname-parser.lst
then
  echo ERRORS IN GRAMMAR
  echo Look at $grammarname-parser.lst
fi

if [ -s tables ] 
then
  echo Creating tables
  ${BETALIB}$boot/bin/${objdir}/tabc $option1 $option2 tables $grammarname-parser $grammarname
else
  exit 1
fi
