#!/bin/sh -f

# Used to boot all grammars by invoking the 
# bootdogram tool of the previous release.

if [ -d $BETALIB/bin_unix/ ]
then
    cd $BETALIB/grammars/metagram/current
    $BETALIB/bin_unix/bootdogram metagrammar

    cd $BETALIB/grammars/beta/current
    $BETALIB/bin_unix/bootdogram beta

    cd $BETALIB/grammars/pretty/current
    $BETALIB/bin_unix/bootdogram prettyprint

    cd $BETALIB/grammars/property/current
    $BETALIB/bin_unix/bootdogram property

    cd $BETALIB/grammars/mylang/current
    $BETALIB/bin_unix/bootdogram mylang
else
    cd $BETALIB/grammars/metagram/current
    $BETALIB/bin/bootdogram metagrammar

    cd $BETALIB/grammars/beta/current
    $BETALIB/bin/bootdogram beta

    cd $BETALIB/grammars/pretty/current
    $BETALIB/bin/bootdogram prettyprint

    cd $BETALIB/grammars/property/current
    $BETALIB/bin/bootdogram property

    cd $BETALIB/grammars/mylang/current
    $BETALIB/bin/bootdogram mylang
fi
