#!/bin/sh

# used to boot beta compiler.
# this one is tricky, since we cannot just set BETALIB
# to the old value and invoke bin/beta in the old location: 
# BETALIB *must* point to the stuff we are about to compile. 
# So we introduce a variable OLD_BETALIB to point to the old 
# location and duplicate the beta script.

#--- configuration---
OLD_BETALIB=${OLD_BETALIB-/users/beta/r5.1.boot}
. $BETALIB/configuration/env.sh
OLD_BETARUN="$OLD_BETALIB/betarun/$objdir/betarun.o"

#--- don't change below ---

if [ "$BETALIB" = "" ]
then
    echo "$0: BETALIB must be set to NEW location"
    exit 1
fi

. $BETALIB/configuration/env.sh

if [ "$MACHINETYPE" = "SGI" ]
then
  LD_LIBRARY_PATH=${OLD_BETALIB}/bin/${objdir}:${OLD_BETALIB}/lib/sgi:${LD_LIBRARY_PATH}
  export LD_LIBRARY_PATH
fi

compiler=${OLD_BETALIB}/bin/${objdir}/beta

exec $compiler --betarun $OLD_BETARUN $BETAOPTS $betaopt "$@"
