#!/bin/sh -f
echo "bootdogram in r5.0"
# Used to boot grammars by invoking the 
# grammar tools of the previous release.
# MUST contain the inlined scripts, since we
# must have BETALIB set to the new value when executing.

#--- configuration---
OLD_BETALIB=${OLD_BETALIB-/users/beta/r5.0.boot}

#--- don't change below ---

. $BETALIB/configuration/env.sh

if [ "$1" = "" ]
then
   echo "Usage: $0 <grammar-name>"
   exit 1
fi

echo generator
${OLD_BETALIB}/bin/$objdir/gen $*

########################

echo bobsit $1-parser.bobs

${OLD_BETALIB}/bin/$objdir/exbobs < $1-parser.bobs 
mv -f bobslist  $1-parser.lst

echo "End-of-BOBS"

if [ ! -s tables ] 
then
  echo ERRORS IN GRAMMAR
  echo Look at $1-parser.lst
  exit 1
elif egrep "ERROR IN.*TO SMALL" $1-parser.lst \
 || egrep "END OF FILE ENTCOUNTERED" $1-parser.lst \
 || egrep "EOF ENCOUNTERED IN READING THE GRAMMAR" $1-parser.lst \
 || egrep "The grammar is NOT LALR\(1\)" $1-parser.lst \
 || egrep "ERROR\(S\) IN INPUT" $1-parser.lst \
 || egrep "ERROR\(S\) IN GRAMMAR" $1-parser.lst
then
  echo ERRORS IN GRAMMAR
  echo Look at $1-parser.lst
fi

if [ -s tables ] 
then
  echo Creating tables
  eval ${OLD_BETALIB}/bin/$objdir/tabc tables $1-parser $1
else
  exit 1
fi

################

echo makepretty
"$OLD_BETALIB"/bin/$objdir/makepretty $*

################

echo morepretty

"$OLD_BETALIB"/bin/$objdir/morepretty $*
