#!/bin/sh -f
echo "bootdogram in r4.1"
# Used to boot grammars by invoking the 
# grammar tools of the previous release.
# MUST contain the inlined scripts, since we
# must have BETALIB set to the new value when executing.

#--- configuration---
OLD_BETALIB="/users/beta/r4.1.boot"
META_VERSION=v5.2
BOBSGEN_VERSION=v1.6
PRETTYGEN_VERSION=v5.2

#--- don't change below ---

. $BETALIB/configuration/env.sh

if [ "$1" = "" ]
then
   echo "Usage: $0 <grammar-name>"
   exit 1
fi

echo generator version ${META_VERSION}
${OLD_BETALIB}/meta/${META_VERSION}/${MACHINETYPE}gen $*

########################

echo bobsit $1-parser.bobs

${OLD_BETALIB}/bobsgen/${BOBSGEN_VERSION}/"$MACHINETYPE"exbobs < $1-parser.bobs 
mv -f bobslist  $1-parser.lst

echo "End-of-BOBS"

if [ ! -s tables ] 
then
  echo ERRORS IN GRAMMAR
  echo Look at $1-parser.lst
  exit 1
elif egrep "ERROR IN.*TO SMALL" $1-parser.lst \
 || egrep "END OF FILE ENTCOUNTERED" $1-parser.lst \
 || egrep "EOF ENCOUNTERED IN READING THE GRAMMAR" $1-parser.lst \
 || egrep "The grammar is NOT LALR\(1\)" $1-parser.lst \
 || egrep "ERROR\(S\) IN INPUT" $1-parser.lst \
 || egrep "ERROR\(S\) IN GRAMMAR" $1-parser.lst
then
  echo ERRORS IN GRAMMAR
  echo Look at $1-parser.lst
fi

if [ -s tables ] 
then
  echo Creating tables
  eval ${OLD_BETALIB}/bobsgen/${BOBSGEN_VERSION}/${MACHINETYPE}tabc tables $1-parser
else
  exit 1
fi

################

echo makepretty version ${PRETTYGEN_VERSION} 

"$OLD_BETALIB"/prettygen/${PRETTYGEN_VERSION}/"$MACHINETYPE"makepretty $*

################

echo morepretty version ${PRETTYGEN_VERSION}

"$OLD_BETALIB"/prettygen/${PRETTYGEN_VERSION}/"$MACHINETYPE"morepretty $*
