#!/bin/sh

BETALIB=${BETALIB-/usr/local/lib/beta}
export BETALIB   # needed if pathhandler is used
. $BETALIB/configuration/env.sh
LOCATION=$BETALIB/boot/bin/$objdir/

if [ "$MACHINETYPE" = "SGI" ]
then
  LD_LIBRARY_PATH=${LOCATION}:${LD_LIBRARY_PATH}
  export LD_LIBRARY_PATH
fi

if [ -f $LOCATION/betarun.a ]
then
   betarun=$LOCATION/betarun.a
else
   betarun=$LOCATION/betarun.o
fi

$LOCATION/beta --betarun $betarun "$@"
