#!/bin/sh -f

# Used to boot all grammars by invoking the 
# bootdogram tool of the previous release.

cd $BETALIB/grammars/metagram/v4.5
$BETALIB/bin/bootdogram metagrammar

cd $BETALIB/grammars/beta/v2.6
$BETALIB/bin/bootdogram beta

cd $BETALIB/grammars/pretty/v2.4
$BETALIB/bin/bootdogram prettyprint

cd $BETALIB/grammars/property/v1.3
$BETALIB/bin/bootdogram property

cd $BETALIB/grammars/mylang/v1.3
$BETALIB/bin/bootdogram mylang
