#!/bin/sh -f

# Used to boot grammars by invoking the 
# grammar tools of the previous release.

#--- configuration---
OLD_BETALIB="/users/beta/r4.0.3"

#--- don't change below ---

if [ "$1" = "" ]
then
   echo "Usage: $0 <grammar-name>"
   exit 1
fi

# set BETALIB to refer old release, and invoke the scripts
# from there.
BETALIB=${OLD_BETALIB}
export BETALIB
${OLD_BETALIB}/bin/generator $* && \
${OLD_BETALIB}/bin/bobsit $* && \
${OLD_BETALIB}/bin/makepretty $* && \
${OLD_BETALIB}/bin/morepretty $*
