#!/bin/sh

# used to boot beta compiler.
# this one is tricky, since we cannot just set BETALIB
# to the old value and invoke bin/beta in the old location: 
# BETALIB *must* point to the stuff we are about to compile. 
# So we introduce a variable OLD_BETALIB to point to the old 
# location and duplicate the beta script.

#--- configuration---
OLD_BETALIB=${OLD_BETALIB-/users/beta/r5.0.boot}
# linux betarun has to be a separate instance in r5.0.boot, since
# it uses a BETA program (gen) to generate the runtime system.
# For the other platforms betarun is generated without the use
# of BETA, and thus the betarun i r5.0.boot may be soft links to
# r5.0.boot.
OLD_BETARUN=$OLD_BETALIB/betarun

#--- don't change below ---

if [ "$BETALIB" = "" ]
then
    echo "$0: BETALIB must be set to NEW location"
    exit 1
fi

. $BETALIB/configuration/env.sh

if [ "$MACHINETYPE" = "SGI" ]
then
  LD_LIBRARY_PATH=${OLD_BETALIB}/compiler/${objdir}:${OLD_BETALIB}/lib/sgi:${LD_LIBRARY_PATH}
  export LD_LIBRARY_PATH
fi

compiler=${OLD_BETALIB}/compiler/${objdir}/beta

exec $compiler $BETAOPTS $betaopt "$@"
