#!/bin/sh -f

grammarname=$1

if [ "'$1" = "'-b" ]
then
    boot=1
    grammarname=$2
else
    boot=0
fi

if [ "$grammarname" = "" ]
then
   echo "Usage: $0 [-b] <grammar-name>"
   exit 1
fi

if [ "$boot" = "1" ]
then
    generator -b $grammarname && bobsit -b $grammarname
else
    generator $grammarname && bobsit $grammarname && makepretty $grammarname && morepretty $grammarname
fi
