#!/bin/sh

##############################################################################
#     PLEASE DO NOT CHANGE BELOW THIS LINE
##############################################################################

MAIL="/usr/lib/sendmail -t"
TMPFILE=/tmp/$APPLICATION.$$
ERRFILE=/tmp/$APPLICATION.ERR.$$

#TODAY="`date +%y%m%d`"
TODAY="`date`"
if [ "$MACHINETYPE" = "SGI" ]
then
  LD_LIBRARY_PATH=${LOCATION}:${LD_LIBRARY_PATH}
  LD_LIBRARY_PATH=${LOCATION}/${objdir}:${LD_LIBRARY_PATH}
# the latter is necessary if LOCATION is different from objdir
  export LD_LIBRARY_PATH
fi

if [ ! -f "$LOCATION/$EXECNAME" ]
then
	echo "$APPLICATION" is currently not available on $MACHINETYPE
	exit 0
fi

# remove dump file if possible.
if [ -f "$EXECNAME".dump ]
then
        /bin/rm -f "$EXECNAME".dump
fi
if [ -f "$EXECNAME".dump ]
then
        # rm failed
#        /bin/mv -f "$EXECNAME".dump /tmp
    echo "old dumpfile: $EXECNAME.dump could not be removed"
fi

if [  "$BETASTAT" = "yes" -a -w $STATFILE ] 
then
echo 'start:' `whoami` '|' $MACHINETYPE '|' `hostname` '|' `date` '|' $$ '|' $* >> $STATFILE
fi

# execute

# trap user interrupt - exit 1 in this case:
# in case this script was invoked from a make file or perl
# this will stop make/perl too.

trap "echo ''; echo 'User Interrupt'; \
if [  '$BETASTAT' = 'yes' -a -w $STATFILE ]; \
then \
echo 'interrupt:  ' `whoami` '|' $MACHINETYPE '|' `hostname` '|' `date` '|' $$ '|' $* code\(130\) \
>> $STATFILE; \
fi; \
exit 1\
" 2

touch $ERRFILE
if [ -w $ERRFILE ] 
then
	$LOCATION/$EXECNAME $DEFAULTOPTIONS $*  2>$ERRFILE
else
	$LOCATION/$EXECNAME $DEFAULTOPTIONS $* 
fi


# check status

NUMSTAT=$?

case $NUMSTAT in
0)	STATUS="NORMAL"
	;;

# kill -2, kill -INT
130)	STATUS="INTERRUPT"
	;;

# kill -9, kill -KILL
137)	STATUS="INTERRUPT"
	;;

# others
*)	STATUS="ERROR"
esac

case $STATUS in

NORMAL)
        # normal exit
        if [ "$BETASTAT" = "yes" -a -w $STATFILE ]
        then
        	echo 'end:  ' `whoami` '|' $MACHINETYPE '|' `hostname` '|' `date` '|' $$ '|' $* >> $STATFILE
        fi
	if [ -w $ERRFILE ] 
	then 
		cat $ERRFILE
		rm -f $ERRFILE
	fi
        ;;

INTERRUPT)
	#interupted
        if [  "$BETASTAT" = "yes" -a -w "$STATFILE" ]
        then
        	echo 'interrupt:' `whoami` '|' $MACHINETYPE '|' `hostname` '|' `date` '|' $$  '|' code\($NUMSTAT\) >> "$STATFILE"
        fi
	if [ -w $ERRFILE ] 
	then 
		cat $ERRFILE
		rm -f $ERRFILE
	fi
        ;;

*)

if [ "$BETAREPORT" = "yes" ]
then
    if  [ "$BETAREPORT_WWW" = "yes" ]
    then
	if [ -w $TOOLCOUNTER ]
	then
	    read REPORTNO < $TOOLCOUNTER
	    if [ "$REPORTNO" = "" ]; then REPORTNO="0"; fi
	    REPORTNO=`expr $REPORTNO + 1`
	    PREV=`expr $REPORTNO - 1`
	    NEXT=`expr $REPORTNO + 1`
	    cat > $TOOLCOUNTER <<EOF
$REPORTNO
EOF
	fi
    fi
fi

if [ "$BETASTAT" = "yes" ]
then
    # error!
    if [ "$BETAREPORT_WWW" = "yes" ]
    then
	magic="`whoami` | $MACHINETYPE | `hostname` | `date` | $$ | $* $REPORTNO"
    else
	magic="`whoami` | $MACHINETYPE | `hostname` | `date` | $$ | $*"
    fi
    if [ -w $STATFILE ]
    then
	echo 'fatal:' $magic >> $STATFILE
    fi
fi

trap "" 2

if [ -w $ERRFILE ] 
then 
	cat $ERRFILE
fi
 
if [ "$BETAREPORT" = "yes" ]
then
        echo BETALIB="$BETALIB" > $TMPFILE
        echo LOCATION=$LOCATION >> $TMPFILE
        echo EXECNAME=$EXECNAME >> $TMPFILE
        echo "$magic" >> $TMPFILE
        echo Description:  >> $TMPFILE
        echo "----------"  >> $TMPFILE

        echo ""
        echo "****** ${EXECNAME} has exited with fatal error ******"
	echo We are sorry about that and will try to correct the error as soon 
	echo as possible. In order to find the cause of the error we need your help. 
	echo Please enter a short description of the situation leading to the crash.
	echo "That description will be mailed to the developer(s) of ${EXECNAME}"
	echo The dump file will automatically be included in the mail, but any
	echo further information e.g. consol output is appreciated.
	echo If you do not have the time to the explain the error or if you already
	echo "have described it previously, then just type ^D"
	echo ""
        echo "Stop by typing ^D:"
	cat		   >> $TMPFILE
	echo "Thank you!"

        echo "----------"  >> $TMPFILE
        echo ""            >> $TMPFILE
        echo Dumpfile:     >> $TMPFILE
        echo "----------"  >> $TMPFILE
        if [ -f "$EXECNAME".dump ]
        then
	    dump="`pwd`/$EXECNAME".dump

	    if  [ "$BETAREPORT_WWW" = "yes" ]
	    then
		if [ -w $TOOLINDEX ]
		then
		    LINE1=`head -1 "$EXECNAME".dump  | sed -e 's/</\&lt;/g' -e 's/>/\&gt;/g'`
		    LINE5=`head -5 "$EXECNAME".dump | tail -1 | sed -e 's/</\&lt;/g' -e 's/>/\&gt;/g' `
		    LINE6=`head -6 "$EXECNAME".dump | tail -1 | sed -e 's/</\&lt;/g' -e 's/>/\&gt;/g' `
		    echo '<pre><a href="http:'$REPORTNO'.html">'$REPORTNO'</a>' `whoami` $TODAY '<br>' $LINE1 '<br>' $LINE5 '<br>' $LINE6 '<br></pre>' >>$TOOLINDEX
		fi
	    fi

	    ls -l $dump                      >> $TMPFILE
	    echo ""                          >> $TMPFILE
	    cat "$EXECNAME".dump | head -500    >> $TMPFILE
        else

	    if  [ "$BETAREPORT_WWW" = "yes" ]
	    then
		if [ -w $TOOLINDEX ]
		then
		    echo '<pre><a href="http:'$REPORTNO'.html">'$REPORTNO'</a>' `whoami` $TODAY '<br>' No dumpfile '<br>' Probably: Cannot open display '<br></pre>'  >>$TOOLINDEX
		fi
	    fi

	    echo "(no dumpfile)"             >> $TMPFILE
	    if [ -w $ERRFILE ] 
	    then 
		cat $ERRFILE  | head -500 >> $TMPFILE
	    fi
        fi
        echo "----------"                  >> $TMPFILE

	if  [ "$BETAREPORT_EMAIL" = "yes" ]
	then
	    echo Sending error report to $TO with Cc to $CC
        (echo To: ${TO}; echo Cc: ${CC}; echo Subject: Automatic "$APPLICATION" error report; \
         echo "";                                                    \
         cat $TMPFILE;                                  \
         ) | ${MAIL}
	fi

	if  [ "$BETAREPORT_WWW" = "yes" ]
	then
	    if  [ -w  $REPORTDIR ] 
	    then
		REPORTFILE="$REPORTDIR"/"$REPORTNO".html
		touch $REPORTFILE
		chmod a+r $REPORTFILE
		chmod a+w $REPORTFILE

		echo '<title>' $REPORTNO '</title>' '<br><a href="http:'$PREV.html'"> 'Previous'</a>' '<a href="http:'$NEXT.html'"> 'Next'</a>' '<a href="http:index.html">Overview</a><pre>' > $REPORTFILE 

		cat $TMPFILE | sed -e 's/</\&lt;/g' -e 's/>/\&gt;/g'  >> $REPORTFILE 
		# to substitute < and > with &lt; and &gt; resp.
	    fi
	fi
        rm -f $TMPFILE
fi

rm -f $ERRFILE

esac

# give an appropriate exit code - see trap for user interrupt above
# for motivation for this.
case $STATUS in
NORMAL)
    exit 0;;
INTERRUPT)
    exit 1;;
*)
    exit 1;;
esac