#!/bin/sh

echo -n "Enter name of PostScript file (without .ps): "
read fileName
fileName=${fileName}".ps"
mv $1 $fileName

if [ -f $BETALIB/bin-unix/freja2eps ]
then
    "$BETALIB"/bin-unix/freja2eps $fileName
else
    "$BETALIB"/bin/freja2eps $fileName
fi

