#!/bin/sh
##############################################################################
# installation site specific:
TO=toby,ess
CC=`whoami`
BETALIB=${BETALIB-/usr/local/lib/beta}
. $BETALIB/configuration/env.sh

# end installation site specific
##############################################################################
# application specific:

APPLICATION=freja
LOCATION="$BETALIB"/freja/v3.0/"$objdir"
EXECNAME="$MACHINETYPE"freja

DesignPrintCommand=${DesignPrintCommand-"$BETALIB"/bin/frejaprinter}
export DesignPrintCommand
DesignResourceDir=${DesignResourceDir-"$BETALIB"/designOA/v1.0/src/resources}
export DesignResourceDir
if [ "$MACHINETYPE" = "SUN4" ]
then
  XAPPLRESDIR="$BETALIB"/freja/v3.0/XRESOURCES/sun4
else
  XAPPLRESDIR="$BETALIB"/freja/v3.0/XRESOURCES/
fi
export XAPPLRESDIR

BETASTAT=${BETASTAT-yes}
STATFILE="$BETALIB"/statistics/freja/frejastat

BETAREPORT=${BETAREPORT-yes}

# end application specific
##############################################################################
#     PLEASE DO NOT CHANGE BELOW THIS LINE
##############################################################################


export BETALIB

. $BETALIB/bin/exectool

