#!/bin/sh

BETALIB=${BETALIB-/usr/local/lib/beta}
EPSDIR=${EPSDIR-"$BETALIB"/freja/EPS}; export EPSDIR
BBPSDIR=${BBPSDIR-$EPSDIR}; export BBPSDIR

case $# in
   1) ps=$1 ;;
   *) echo "Usage: $0 <ps-file>"; exit ;;
esac

if [ ! -f $ps ]
then
    echo "No ps file called $ps";
    exit;
fi

if grep "^%%BoundingBox" $ps
then
    echo "$ps already contains a BoundingBox";
    exit;
fi

base=`basename $ps .ps`
eps="$base.eps"
epsi="$base.epsi"

echo "%!PS-Adobe-2.0 EPSF-2.0" >$eps
$EPSDIR/bbfig -gs $ps >> /tmp/$$
perl -ane 'print $F[0]," ",$F[1]-1," ",$F[2]," ",$F[3]," ",$F[4],"\n"' < /tmp/$$ >>$eps
echo "%%Creator: Freja" >>$eps
echo "%%Title: $base" >>$eps
date=`date`
echo "%%CreationDate: $date" >>$eps
cat $ps >>$eps

echo "$ps --> $eps"

#$EPSDIR/eps2epsi $eps > $epsi
#
#echo "$eps --> $epsi"
