#!/bin/sh
##############################################################################
# installation site specific:
TO=toby,ess
CC=`whoami`
BETALIB=${BETALIB-/usr/local/lib/beta}
. $BETALIB/configuration/env.sh

# end installation site specific
##############################################################################
# application specific:

APPLICATION=freja
LOCATION="$BETALIB"/freja/v3.0/"$objdir"
EXECNAME="$MACHINETYPE"freja
DEFAULTOPTIONS=""

DesignPrintCommand=${DesignPrintCommand-"$BETALIB"/bin/frejaprinter}
export DesignPrintCommand
DesignResourceDir=${DesignResourceDir-"$BETALIB"/designOA/v1.0/src/resources}
export DesignResourceDir
if [ "$MACHINETYPE" = "SUN4" ]
then
  XAPPLRESDIR="$BETALIB"/freja/v3.0/XRESOURCES/sun4
else
  XAPPLRESDIR="$BETALIB"/freja/v3.0/XRESOURCES/
fi
export XAPPLRESDIR

BETASTAT=${BETASTAT-no}
STATLOCATION="$BETALIB"/statistics/"$APPLICATION"
STATFILE="$STATLOCATION"/"$APPLICATION"stat

BETAREPORT=${BETAREPORT-no}
BETAREPORT_EMAIL=${BETAREPORT_EMAIL-yes}
BETAREPORT_WWW=${BETAREPORT_WWW-yes}
REPORTDIR="$STATLOCATION"/reports 
TOOLCOUNTER="$REPORTDIR"/"$APPLICATION".counter
TOOLINDEX="$REPORTDIR"/index.html

# REPORTDIR must be writeable by all
# STATFILE and TOOLINDEX must exist and be writeable by all
# TOOLCOUNTER must exist and be writeable by all AND intialized with 1
# e.g. by: cat >sif.counter and enter 1 <CR> ctrl-d
# all this is done by the script 'prepareReportDir' in bin/admin
# usage: pwd $STATLOCATION; prepareReportDir $APPLICATION

# end application specific
##############################################################################
#     PLEASE DO NOT CHANGE BELOW THIS LINE
##############################################################################


export BETALIB

. $BETALIB/bin/exectool

