#!/bin/sh
##############################################################################
# installation site specific:
TO=henryml
CC=`whoami`
BETALIB=${BETALIB-/usr/local/lib/beta}
. $BETALIB/configuration/env.sh

# end installation site specific
##############################################################################
# application specific:

APPLICATION=frigg
LOCATION="$BETALIB"/interfacebuilder/v1.5
EXECNAME="$MACHINETYPE"frigg

BETASTAT=${BETASTAT-yes}
STATFILE="$BETALIB"/statistics/frigg/friggstat

BETAREPORT=${BETAREPORT-yes}

# end application specific
##############################################################################
#     PLEASE DO NOT CHANGE BELOW THIS LINE
##############################################################################

export BETALIB

. $BETALIB/bin/exectool

