#!/bin/sh

BETALIB=${BETALIB-/users/beta/r4.0.1}
. $BETALIB/configuration/r4.0/env.sh

echo "gdb /users/beta/r4.0.1/editor/v5.1/"$objdir"/"$MACHINETYPE"gdbsif"
gdb /users/beta/r4.0.1/editor/v5.1/"$objdir"/"$MACHINETYPE"gdbsif <<EOT
run
EOT
