#!/bin/sh -f

BETALIB=${BETALIB-/usr/local/lib/beta}
. $BETALIB/configuration/env.sh

if [ "'$1" = "'-b" ]
then
    boot="/boot"
    shift
else
    boot=""
fi

if [ "$1" = "" ]
then
   echo "Usage: $0 <grammar-name>"
   exit 1
fi

if [ "$MACHINETYPE" = "SGI" ]
then
  LD_LIBRARY_PATH="$BETALIB"/meta/${objdir}:${LD_LIBRARY_PATH}
  export LD_LIBRARY_PATH
fi

echo generator version 5.2

exec "$BETALIB"$boot/bin/${objdir}/gen $*
