#!/bin/sh

RELEASE=4.1

echonl(){
case "`uname -m`" in
  sun*)
    case "`uname -r`" in
      4.*)
        /bin/echo -n "$1"
        ;;
      5.*)
        /bin/echo "$1\c"
        ;;
      *)
        echo "Unsupported SunOS"
	exit 1
        ;;
    esac
    ;;
  9000/[347]??)
    echo "$1\c"
    ;;
  i?86)
    echo -n "$1"
    ;;
  IP22)
    echo -n "$1"
    ;;
  *)
    echo "$0: Unsupported OS"
    exit 1
    ;;
esac
}

make_link()
{
	if [ -d $BETALIB/$1 ]
	then
	  echo "$1/current -> $2"
	  cd $BETALIB/$1
	  rm -f current
	  ln -s $2 current
	fi
}

if [ "$BETALIB" = "" ]
then
	echo The BETALIB environment variable must be set
	echo before running this script.
	echo Please set BETALIB and restart this script.
	exit 1
fi

if [ ! -d $BETALIB ]
then
	echo The BETALIB environment variable must be set
	echo to the name of an existing directory.
	echo Current value is: \"$BETALIB\"
	exit 1
fi

echo   "This script will remove old current links and install new links"
echo   "in release $RELEASE of the Mjolner BETA System (using ln)."
echo   "The directory affected is BETALIB: $BETALIB."
echonl "Is this what you want to do? [ny] "
read answer
case "$answer" in
"y")	echo ""
	;;
*)	exit 0
	;;
esac

make_link Xt v1.9
make_link basiclib v1.5
make_link betaast v5.1
make_link utils/betawc v1.1
make_link utils/betatar v1.1
make_link utils/betafs v1.1
make_link betarun v2.9
make_link bifrost v2.1
make_link bobs v6.10
make_link bobsgen v1.5
make_link containers v1.5
make_link debugger v2.2
make_link dependency v1.2
make_link distribution v1.2
make_link editor v5.1
make_link emacs v1.6
make_link grammars/beta v2.5
make_link grammars/metagram v4.4
make_link grammars/pretty v2.3
make_link grammars/property v1.2
make_link guienv v1.4
make_link man v1.3
make_link meta v5.1
make_link mps v5.1
make_link objectbrowser v2.1
make_link sourcebrowser v1.1
make_link objectserver v2.4
make_link persistentstore v1.5
make_link pretty v5.1
make_link prettygen v5.1
make_link process v1.5
make_link system v5.2
make_link sysutils v1.5
make_link unixlib v1.5
make_link interfacebuilder v1.5
make_link freja v3.0
