#!/bin/sh

RELEASE=4.1

echonl(){
case "`uname -m`" in
  sun*)
    case "`uname -r`" in
      4.*)
        /bin/echo -n "$1"
        ;;
      5.*)
        /bin/echo "$1\c"
        ;;
      *)
        echo "Unsupported SunOS"
	exit 1
        ;;
    esac
    ;;
  9000/[347]??)
    echo "$1\c"
    ;;
  i?86)
    echo -n "$1"
    ;;
  IP22)
    echo -n "$1"
    ;;
  *)
    echo "$0: Unsupported OS"
    exit 1
    ;;
esac
}

make_link()
{
	if [ -d $BETALIB/$1 ]
	then
	  cd $BETALIB/$1
	  echo "$1/current -> $2"
	  if [ -d $2 ]
	  then
	    rm -f current
	    ln -s $2 current
	  else
	    echo "  Directory $BETALIB/$1/$2 does not exist."
	    echo "  No current link created."
	  fi
	fi
}

if [ "$BETALIB" = "" ]
then
	echo The BETALIB environment variable must be set
	echo before running this script.
	echo Please set BETALIB and restart this script.
	exit 1
fi

if [ ! -d $BETALIB ]
then
	echo The BETALIB environment variable must be set
	echo to the name of an existing directory.
	echo Current value is: \"$BETALIB\"
	exit 1
fi

echo   "This script will remove old current links and install new links"
echo   "in release $RELEASE of the Mjolner BETA System (using ln)."
echo   "The directory affected is BETALIB: $BETALIB."
echonl "Is this what you want to do? [ny] "
read answer
case "$answer" in
"y")	echo ""
	;;
*)	exit 0
	;;
esac

make_link Xt v1.10
make_link basiclib v1.6
make_link betaast v5.2
make_link betarun v3.0
make_link bifrost v2.2
make_link bobs v6.11
make_link bobsgen v1.6
make_link containers v1.6
make_link debugger v2.3
make_link dependency v1.3
make_link designenv v3.1
make_link designlib v2.3
make_link distribution v1.6
make_link editor v5.2
make_link emacs v1.7
make_link freja v3.1
make_link gpp v3.1
make_link grammars/beta v2.6
make_link grammars/document v1.2
make_link grammars/ecool v1.3
make_link grammars/gdmo v1.2
make_link grammars/metagram v4.4
make_link grammars/mylang v1.2
make_link grammars/osdl v1.1
make_link grammars/pascal v1.3
make_link grammars/pretty v2.3
make_link grammars/property v1.2
make_link guienv v1.6
make_link interfacebuilder v1.6
make_link man v1.4
make_link meta v5.2
make_link mps v5.2
make_link objectbrowser v2.2
make_link objectserver v2.5
make_link oodb v2.3
make_link persistentstore v1.6
make_link pretty v5.2
make_link prettygen v5.2
make_link process v1.6
make_link sourcebrowser v1.2
make_link sysutils v1.6
make_link toollibs/preferences v1.1
make_link toollibs/report v1.0
make_link unixlib v1.6
make_link utils/betawc v1.2
make_link utils/betatar v1.2
make_link utils/betafs v1.2
