#!/bin/sh -f

BETALIB=${BETALIB-/usr/local/lib/beta}
. $BETALIB/configuration/env.sh

grammarname=$1

if [ "'$1" = "'-b" ]
then
    boot="/boot"
    grammarname=$2
else
    boot=""
fi

if [ "$grammarname" = "" ]
then
   echo "Usage: $0 <grammar-name>"
   exit 1
fi

if [ "$MACHINETYPE" = "SGI" ]
then
  LD_LIBRARY_PATH="$BETALIB"/bin/${objdir}:${LD_LIBRARY_PATH}
  export LD_LIBRARY_PATH
fi

echo makepretty version v5.2 

exec "$BETALIB"$boot/bin/${objdir}/makepretty $grammarname
