#!/bin/sh -f

BETALIB=${BETALIB-/usr/local/lib/beta}
. $BETALIB/configuration/env.sh

if [ "$MACHINETYPE" = "SGI" ]
then
  LD_LIBRARY_PATH="$BETALIB"/bin/${objdir}:${LD_LIBRARY_PATH}
  export LD_LIBRARY_PATH
fi

exec "$BETALIB"/bin/${objdir}/parse $*
