#!/bin/sh -f

BETALIB=${BETALIB-/usr/local/lib/beta}
. $BETALIB/configuration/env.sh

if [ "$MACHINETYPE" = "SGI" ]
then
  LD_LIBRARY_PATH="$BETALIB"/pretty/v5.2/${objdir}:${LD_LIBRARY_PATH}
  export LD_LIBRARY_PATH
fi

#echo $0 version 5.2
exec "$BETALIB"/pretty/v5.2/${objdir}/pp $*
