#!/bin/sh -f

BETALIB=${BETALIB-/usr/local/lib/beta}
. $BETALIB/configuration/r4.0/env.sh

if [ "$MACHINETYPE" = "SGI" ]
then
  LD_LIBRARY_PATH="$BETALIB"/pretty/v5.1/${objdir}:${LD_LIBRARY_PATH}
  export LD_LIBRARY_PATH
fi

#echo $0 version 5.1
exec "$BETALIB"/pretty/v5.1/"$MACHINETYPE"pp $*
