#!/bin/sh

BETALIB=${BETALIB-/usr/local/lib/beta}
. $BETALIB/configuration/env.sh

if [ "$MACHINETYPE" = "SGI" ]
then
  LD_LIBRARY_PATH=${BETALIB}/objectbrowser/v2.1/psbrowser/${objdir}:${LD_LIBRARY_PATH}
  export LD_LIBRARY_PATH
fi

echo BETA object browser v2.1 for persistentstore/v1.5

exec ${BETALIB}/objectbrowser/v2.1/psbrowser/${MACHINETYPE}psbrowser