#!/bin/sh

BETALIB=${BETALIB-/usr/local/lib/beta}
. $BETALIB/configuration/env.sh

if [ "$MACHINETYPE" = "SGI" ]
then
  LD_LIBRARY_PATH=${BETALIB}/bin/${objdir}:${LD_LIBRARY_PATH}
  export LD_LIBRARY_PATH
fi

echo BETA object browser v2.2 for persistentstore/v1.6

exec ${BETALIB}/bin/${objdir}/psbrowser
