#!/bin/sh
#set -x
##############################################################################
# installation site specific:
MAILTO=bug-beta@mjolner.dk
MAILCC=`whoami`
BETALIB=${BETALIB-/usr/local/lib/beta}
. $BETALIB/configuration/env.sh

# end installation site specific
##############################################################################
# application specific:

APPLICATION=rungen
LOCATION="$BETALIB"/bin/"$objdir"
EXECNAME=rungen
DEFAULTOPTIONS="$BETAOPTS"

BETASTAT=${BETASTAT-no}
STATLOCATION="$BETALIB"/statistics/"$APPLICATION"
STATFILE="$STATLOCATION"/"$APPLICATION"stat

BETAREPORT=${BETAREPORT-no}
# The following two are only used if BETAREPORT=yes
BETAREPORT_EMAIL=${BETAREPORT_EMAIL-no}
BETAREPORT_WWW=${BETAREPORT_WWW-no}
REPORTDIR="$STATLOCATION"/reports 
TOOLCOUNTER="$REPORTDIR"/"$APPLICATION".counter
TOOLINDEX="$REPORTDIR"/index.html

# REPORTDIR must be writeable by all
# STATFILE and TOOLINDEX must exist and be writeable by all
# TOOLCOUNTER must exist and be writeable by all AND intialized with 1
# e.g. by: cat >sif.counter and enter 1 <CR> ctrl-d
# all this is done by the script 'prepareReportDir' in bin/admin
# usage: pwd $STATLOCATION; prepareReportDir $APPLICATION

# end application specific
##############################################################################
#     PLEASE DO NOT CHANGE BELOW THIS LINE
##############################################################################

export BETALIB

if [ -f $BETALIB/bin_unix/exectool ]
then
    . $BETALIB/bin_unix/exectool
else
    . $BETALIB/bin/exectool
fi

