#!/bin/sh
##############################################################################
# installation site specific:
TO=ess
CC=`whoami`
BETALIB=${BETALIB-/usr/local/lib/beta}
. $BETALIB/configuration/env.sh

# end installation site specific
##############################################################################
# application specific:

APPLICATION=sif
LOCATION="$BETALIB"/editor/v5.1/"$objdir"
EXECNAME="$MACHINETYPE"sif

BETASTAT=${BETASTAT-yes}
STATLOCATION="$BETALIB"/statistics/sif
STATFILE=$STATLOCATION/sifstat

# NOTICE is using exectool.new!!!!!!!!!

BETAREPORT=${BETAREPORT-yes}
REPORTDIR="$STATLOCATION"/reports 
TOOLCOUNTER="$REPORTDIR"/"$APPLICATION".counter
TOOLINDEX="$REPORTDIR"/index.html

# REPORTDIR must be writeable by all
# STATFILE and TOOLINDEX must exist and be writeable by all

# end application specific
##############################################################################
#     PLEASE DO NOT CHANGE BELOW THIS LINE
##############################################################################

export BETALIB

. $BETALIB/bin/exectool.new

