#!/bin/sh

BETALIB=${BETALIB-/usr/local/lib/beta}
. $BETALIB/configuration/env.sh

LOCATION=${BETALIB}/bin

if [ "$MACHINETYPE" = "SGI" ]
then
  LD_LIBRARY_PATH=${LOCATION}:${BETALIB}/lib/${objdir}:${LD_LIBRARY_PATH}
  LD_LIBRARY_PATH=${LOCATION}/${objdir}:${LD_LIBRARY_PATH}
# the latter is necessary if LOCATION is different from objdir
  export LD_LIBRARY_PATH
fi

echo Installing BETA ensemble daemon v1.6 for "$MACHINETYPE".
exec ${LOCATION}/${objdir}/ensembleDeamon

