#!/bin/sh

BETALIB=${BETALIB-/usr/local/lib/beta}
. $BETALIB/configuration/r4.0/env.sh

LOCATION=${BETALIB}/distribution/v1.2

if [ "$MACHINETYPE" = "SGI" ]
then
  LD_LIBRARY_PATH=${LOCATION}/${objdir}:${LD_LIBRARY_PATH}
  export LD_LIBRARY_PATH
fi

echo Installing BETA ensemble deamon v1.2 for "$MACHINETYPE".
exec ${LOCATION}/${MACHINETYPE}ensembleDeamon

