#!/bin/sh
##############################################################################
# installation site specific:
TO=jlk@mjolner.dk,datpete@mjolner.dk
CC=`whoami`
BETALIB=${BETALIB-/usr/local/lib/beta}
. $BETALIB/configuration/env.sh

# end installation site specific
##############################################################################
# application specific:

APPLICATION=valhalla
LOCATION="$BETALIB"/debugger/v2.2/"$objdir"
EXECNAME=valhalla

BETASTAT=${BETASTAT-yes}
STATFILE="$BETALIB"/statistics/valhalla/valhallastat

BETAREPORT=${BETAREPORT-yes}

echo BETA debugger v2.2 for ${MACHINETYPE} -- compiler v5.2 / betarun v2.9

# end application specific
##############################################################################
#     PLEASE DO NOT CHANGE BELOW THIS LINE
##############################################################################

export BETALIB

. $BETALIB/bin/exectool

