asm:
	- /home/amparo1/beta/betarun/v2.4/GEN/hp/gen -o MakeTextObj.s MakeTextObj

bytes:
	- /home/amparo1/beta/betarun/v2.4/GEN/hp/gen -o Bytes.s /home/amparo1/beta/betarun/v2.5/RUN/Bytes

bo:
	- as -o Bytes.o Bytes.s
