#!/bin/sh

if [ ! -f /usr/bin/sun ]
then
	echo ***WARNING: you may run into \"arg list too long\"
	echo ***WARNING: if you don\'t do this on a SUN\!
fi

cd ${BETALIB}/export/dotar

PACKLIDSKJALV=${PACKLIDSKJALV-"yes"}
export PACKLIDSKJALV

FILES=`ls -r *.dotar`

for f in $FILES
do
	echo "------------"
	echo Executing $f -0 ...
	$f -0
done