#!/bin/sh

if [ ! -f /usr/bin/sun ]
then
	echo ***WARNING: you may run into \"arg list too long\"
	echo ***WARNING: if you don\'t do this on a SUN\!
fi

cd /users/beta/export/distribution/r3.1/tar

PACKEDITOR=${PACKEDITOR-"yes"}
export PACKEDITOR

#FILES=`ls *.dotar | grep -v pe-`
#FILES="linux.dotar"
echo Only packing for sun4s...
FILES="sun4s.dotar"

for f in $FILES
do
	echo Executing $f -0 ...
	$f -0
done