#!/bin/sh

if [ ! -f /usr/bin/sun ]
then
	echo ***WARNING: you may run into \"arg list too long\"
	echo ***WARNING: if you don\'t do this on a SUN\!
fi

cd ${BETALIB}/export/dotar

FILES=`ls *.dotar | grep -v mac | grep -v demo | grep -v pe-`

for f in $FILES
do
	echo "---------------"
	echo Executing $f -F ...
	$f -F
done