#!/bin/sh

if [ ! -f /usr/bin/sun ]
then
	echo ***WARNING: you may run into \"arg list too long\"
	echo ***WARNING: if you don\'t do this on a SUN\!
fi


cd /users/beta/export/distribution/r4.0/tar

for f in *.dotar
do
	echo "--------------------"
	echo Executing $f -pe ...
	$f -pe
done