#!/bin/sh

if [ ! -f /usr/bin/sun ]
then
	echo ***WARNING: you may run into \"arg list too long\"
	echo ***WARNING: if you don\'t do this on a SUN\!
fi

cd /users/beta/export/distribution/r4.0/tar

PACKGDMO=${PACKGDMO-"yes"}
export PACKGDMO

#FILES=`ls *.dotar | grep -v pe- | grep -v demo`
echo Only packing for sun4s...
FILES="sun4.dotar"

for f in $FILES
do
	echo "---------------------"
	echo Executing $f -0 ...
	$f -0
done