#!/bin/sh

if [ ! -f /usr/bin/sun ]
then
	echo ***WARNING: you may run into \"arg list too long\"
	echo ***WARNING: if you don\'t do this on a SUN\!
fi

cd /users/beta/export/distribution/r3.1/tar

for f in *.dotar
do
	echo "----------------"
	echo Executing $f -F ...
	$f -F
done