#!/bin/sh

if [ ! -f /usr/bin/sun ]
then
	echo ***WARNING: you may run into \"arg list too long\"
	echo ***WARNING: if you don\'t do this on a SUN\!
fi

cd /users/beta/export/distribution/r3.1/tar

PACKBETACL=${PACKBETACL-"yes"}
export PACKBETACL

#FILES=`ls *.dotar | grep -v pe-`
echo BeTaCl only packed for sun4s - no machine specific files...
FILES="sun4s.dotar"

for f in $FILES
do
	echo "---------------------"
	echo Executing $f -0 ...
	$f -0
done