#!/usr/local/bin/perl -s

my @files;

use File::Find;

$betalib = $ENV{'BETALIB'};

sub check()
{
    $f = $File::Find::name;
    next unless $f =~ m%\.bet$%;
    $f =~ s%\.bet$%%; # strip suffix
    $f =~ s%^\./%%; # strip ./ prefix
    next if ($f =~ m%/_[^/]+$%); # skip wrapper classes
    next if ($f =~ m%beta_helpers$%); # skip helpers
    next if ($f =~ m%dotnet2beta/test%); # skip test programs
    push @files, $f;
}

$|= 1;
print "Searching for .bet files to rebuild ...";
find(\&check, ".");
print " done (found " . scalar(@files) . ")\n";

# First convert System.Windows.Forms.Control - triggers most others

print "************ System.Windows.Forms.Control ************\n";
system "dotnet2beta -F -w System.Windows.Forms.Control";

foreach $f (@files){
    print "************ $f ************\n";
    if (-M "$f.bet" <= 0){
	print "*** Skipped $f.bet: already modified by this rebuild\n";
    } else {
	system "dotnet2beta -F -w $f";
    }
}
