#!/bin/sh

#--------- Configuration: ------

# Directories containing source files:
SRC="${BETALIB}/basiclib"

# Files to include in interface. The order given here will
# be the order they appear in in the generated interface.
FILES="\
betaenv.bet \
math.bet \
numberio.bet \
formatio.bet \
random.bet \
regexp.bet \
file.bet \
directory.bet \
basicsystemenv.bet \
systemenv.bet \
timehandler.bet \
external.bet \
"

MAKEINT=../../bin/beta2int.perl
MAKEHTML=../../bin/int2html.perl

. ../../bin/makeHTML.sh
