#!/bin/sh

#--------- Configuration: ------

# FIXME: unixlib stuff should probably be left out
# (and taken out of the word doc too)
# There is now a separate unixlib dir.

# Directories containing source files:
SRC="${BETALIB}/basiclib ${BETALIB}/unixlib"

# Files to include in interface. The order given here will
# be the order they appear in in the generated interface.
FILES="\
betaenv.bet \
math.bet \
numberio.bet \
formatio.bet \
random.bet \
regexp.bet \
file.bet \
directory.bet \
unixfile.bet \
unixdirectory.bet \
basicsystemenv.bet \
systemenv.bet \
timehandler.bet \
external.bet \
"

MAKEINT=../../bin/beta2int.perl
MAKEHTML=../../bin/int2html.perl


#----- Don't change below ! -----

/bin/rm -f *.int
echo Making interface descriptions for $SRC.
echo ""
for srcdir in $SRC
do
    for file in $FILES
    do
	if [ ! -f $srcdir/$file ]; then continue; fi
	INT=`basename $srcdir/$file .bet`.int
	echo Making $INT from $srcdir/$file ...
	expand $srcdir/$file | $MAKEINT > $INT
	INTFILES="${INTFILES} $INT"
    done
done

echo Creating HTML:
$MAKEHTML -v *.int
/bin/rm -f $INTFILES
echo done.
