#!/bin/sh

#--------- Configuration: ------

# Directories containing source files:
SRC="${BETALIB}/basiclib"

# Files to include in interface. The order given here will
# be the order they appear in in the generated interface.
FILES="\
basicsystemenv.bet \
betaenv.bet \
binfile.bet \
directory.bet \
external.bet \
file.bet \
filerep.bet \
formatio.bet \
iget.bet \
math.bet \
mbs_version.bet \
numberio.bet \
random.bet \
regexp.bet \
substreams.bet \
systemenv.bet \
texthash.bet \
textUtils.bet \
timedate.bet \
timehandler.bet \
wtext.bet \
"

MAKEINT=../../bin/beta2int.perl
#MAKEHTML=../../bin/int2html.perl
MAKEHTML=../../bin/int2frames.perl

. ../../bin/makeHTML.sh
