#!/bin/sh

cd /users/beta

tar -cvf ./objectbrowser/v2.0/psbrowser/psbrowser.tar  \
./objectbrowser/v2.0/*.bet \
./objectbrowser/v2.0/private/*.bet \
./objectbrowser/v2.0/UI/*.bet \
./objectbrowser/v2.0/UI/private/*.bet \
./objectbrowser/v2.0/psbrowser/*.bet \
./objectbrowser/v2.0/psbrowser/private/*.bet
