#!/bin/sh

cd /users/beta

tar -cvf psbrowser_olm.tar \
./objectbrowser/v2.0/psbrowser/sun4s/psbrowser \
./objectbrowser/v2.0/psbrowser/README \
./objectbrowser/v2.0/psbrowser/*.bet \
./objectbrowser/v2.0/psbrowser/private/*.bet \
./bin/psbrowser \
./bitmap/*.xbm