#!/bin/sh

# Arm GNU toolchain location 
# TOOLCHAIN=/Applications/ArmGNUToolchain/12.2.rel1/arm-none-eabi
TOOLCHAIN="/cygdrive/c/Program Files/GNU ARM Embedded Toolchain/10 2021.07"



CC="$TOOLCHAIN/bin/arm-none-eabi-gcc"
OBJCOPY="$TOOLCHAIN/bin/arm-none-eabi-objcopy"

"$CC" -O0 -g -ffreestanding -nostartfiles --specs=nosys.specs -mcpu=cortex-a53 -mfloat-abi=soft slib.S clib.c main.c -o kernel7.elf
"$OBJCOPY" kernel7.elf -O binary kernel7.img

