#!/bin/sh

#--------- Configuration: ------

# Directories containing source files:
SRC="${BETALIB}/mps"

# Files to include in interface. The order given here will
# be the order they appear in in the generated interface.
FILES="\
astlevel.bet \
applgram.bet \
findgrammar.bet \
metagrammarcfl.bet \
metagramsematt.bet \
property.bet \
propertycfl.bet \
"

MAKEINT=../../bin/beta2int.perl
MAKEHTML=../../bin/int2html.perl

. ../../bin/makeHTML.sh
