#!/bin/sh

#--------- Configuration: ------

# Directories containing source files:
SRC="${BETALIB}/mps"

# Files to include in interface. The order given here will
# be the order they appear in in the generated interface.
FILES="\
astlevel.bet \
findgrammar.bet \
fragmentscanner.bet \
grammarinit.bet \
metagrammarcfl.bet \
metagramsematt.bet \
notifications.bet \
observer.bet \
property.bet \
propertycfl.bet \
propertyparser.bet \
"

MAKEINT=../../bin/beta2int.perl
#MAKEHTML=../../bin/int2html.perl
MAKEHTML=../../bin/int2frames.perl

. ../../bin/makeHTML.sh
