(defun insert-marker ()
  (interactive)
  (insert "<A NAME=MARKER-")
  (yank)
  (insert "></A>")
  (backward-word 4)
  (let ((beg (point)))
   (let ((case-fold-search nil)) (re-search-backward "[=MARKER]")
      (forward-char)
      (delete-region beg (point))))
  (let ((beg (point)))
   (let ((case-fold-search nil)) (re-search-forward "[>]")
      (backward-char)
      (copy-region-as-kill beg (point))))
  (other-window 1) 
)

(defun insert-href ()
  (interactive)
  (insert "  <A HREF=\"MARKER-")
  (yank)
  (insert "\">")
  (yank)
  (let ((beg (point)))
    (let ((case-fold-search nil)) (re-search-backward "[>]")))
  (forward-char)
  (let ((beg (point)))
    (let ((case-fold-search nil)) (re-search-forward "[-]")
       (delete-region beg (point))))
  (end-of-line)
  (insert "</A>")
)
