(defun miadoc-replace1 (basefilename)
  (interactive "sWebMaker base filename: " )
  (set-variable 'tags-file-name nil)

  (let ((case-replace t) (match (concat basefilename "-[12].html")) )
    (message "Replacing first and second file name with index.html")
    (tags-query-replace match "index.html" nil)
))

;(defun miadoc-replace2 (secondfilename)
;  (interactive "sSecond WebMaker generated file: " )
;  (set-variable 'tags-file-name nil);;;
;
;  (let ((case-replace t))
;    (message "Replacing %s name with contents.html" secondfilename)
;    (tags-query-replace secondfilename "contents.html" nil)
;))

(defun miadoc-replace3 (lastfilename)
  (interactive "sLast WebMaker generated file: " )
  (set-variable 'tags-file-name nil)

  (let ((case-replace t))
    (message "Replacing last file name with inx.html")
    (tags-query-replace lastfilename "inx.html" nil)
))

(defun miadoc-replace4 ()
  (interactive)
  (set-variable 'tags-file-name nil)

  (let ((case-replace t))
    (message "Removing WebMaker comment")
    (tags-query-replace "<!-- Generated by Harlequin Webmaker .* -->" "" nil)
))

(defun miadoc-replace5 ()
  (interactive)
  (set-variable 'tags-file-name nil)

  (let ((case-replace t))
    (message "Removing version numbers")
    (tags-query-replace "/v[0-9]+\\.[0-9]+\\.?[0-9]*" "" nil))
)

(defun miadoc-replace6 ()
  (interactive)
  (set-variable 'tags-file-name nil)

  (let ((case-replace t))
    (message "Adding anchors to index entries")
    (find-file "inx.html")
    (query-replace-regexp "<H2>\\([A-Z]\\)</H2>" "<H2><A NAME=_\\1>\\1</A></H2>" nil))
)

(defun miadoc-replace7 ()
  (interactive)
  (set-variable 'tags-file-name nil)

  (let ((case-replace t))
    (message "Adding Style sheet")
    (tags-query-replace "</TITLE>" "</TITLE>
<LINK REL=stylesheet HREF=../style/miadoc.css TYPE=text/css>" nil))
)

(defun miadoc-replace8 ()
  (interactive)
  (set-variable 'tags-file-name nil)

  (let ((case-replace t))
    (message "Fixing MIA references")
    (tags-query-replace "\\[MIA\\s-*\\(9[0-9]-[0-9]+\\)\\]" "<A HREF=\"../bibliography/index.html#mia\\1\">[MIA \\1]</A>" nil)))

(defun miadoc-replace9 ()
  (interactive)
  (set-variable 'tags-file-name nil)

  (let ((case-replace t))
    (message "Changing PRE to class BETA")
    (tags-query-replace "<PRE>" "<PRE CLASS=beta>" nil)))

(defun miadoc-replace10 ()
  (interactive)
  (set-variable 'tags-file-name nil)

  (let ((case-replace t))
    (message "Removing META")
    (tags-query-replace "<META.*>" "" nil)))

(defun miadoc-replace11 ()
  (interactive)
  (set-variable 'tags-file-name nil)

  (let ((case-replace t))
    (message "Removing &middot;")
    (tags-query-replace "<LI>&middot;" "<LI>" nil)))

(defun miadoc-replace12 ()
  (interactive)
  (set-variable 'tags-file-name nil)

  (let ((case-replace t))
    (message "Removing <DIV>")
    (tags-query-replace "</?DIV>" "" nil)))

(defun miadoc-replace13 ()
  (interactive)
  (set-variable 'tags-file-name nil)

  (let ((case-replace t))
    (message "Fixing Madsen 93 references")
    (tags-query-replace "\\[Madsen 93\\]" "<A HREF=\"../bibliography/index.html#mmn93\">[MMN 93]</A>" nil)))

(defun miadoc-replace14 ()
  (interactive)
  (set-variable 'tags-file-name nil)

  (let ((case-replace t))
    (message "Fixing Knudsen 94 references")
    (tags-query-replace "\\[Knudsen 94\\]" "<A HREF=\"../bibliography/index.html#knudsen94\">[Knudsen 94]</A>" nil)))

(defun miadoc-replace15 ()
  (interactive)
  (set-variable 'tags-file-name nil)

  (let ((case-replace t))
    (message "Removing FM pgf ignored")
    (tags-query-replace "<!-- FM pgf ignored -->" "" nil)))
