(defun miadoc-replace1 (firstfilename)
  (interactive "sFirst WebMaker generated file: " )
  (set-variable 'tags-file-name nil)

  (let ((case-replace t))
    (message "Replacing first file name with index.html")
    (tags-query-replace firstfilename "index.html" nil)
))

(defun miadoc-replace2 (secondfilename)
  (interactive "sSecond WebMaker generated file: " )
  (set-variable 'tags-file-name nil)

  (let ((case-replace t))
    (message "Replacing %s name with contents.html" secondfilename)
    (tags-query-replace secondfilename "contents.html" nil)
))

(defun miadoc-replace3 (lastfilename)
  (interactive "sLast WebMaker generated file: " )
  (set-variable 'tags-file-name nil)

  (let ((case-replace t))
    (message "Replacing last file name with inx.html")
    (tags-query-replace lastfilename "inx.html" nil)
))

(defun miadoc-replace4 ()
  (interactive)
  (set-variable 'tags-file-name nil)

  (let ((case-replace t))
    (message "Removing WebMaker comment")
    (tags-query-replace "<!-- Generated by Harlequin Webmaker .* -->" "" nil)
))

(defun miadoc-replace5 ()
  (interactive)
  (set-variable 'tags-file-name nil)

  (let ((case-replace t))
    (message "Removing version numbers")
    (tags-query-replace "/v[0-9]+\\.[0-9]+\\.?[0-9]*" "" nil))
)

(defun miadoc-replace6 ()
  (interactive)
  (set-variable 'tags-file-name nil)

  (let ((case-replace t))
    (message "Adding anchors to index entries")
    (find-file "inx.html")
    (query-replace-regexp "<H2>\\([A-Z]\\)</H2>" "<H2><A NAME=_\\1>\\1</A></H2>" nil))
)

(defun miadoc-replace7 ()
  (interactive)
  (set-variable 'tags-file-name nil)

  (let ((case-replace t))
    (message "Adding Style sheet")
    (tags-query-replace "</TITLE>" "</TITLE>
<LINK REL=stylesheet HREF=../style/miadoc.css TYPE=text/css>" nil))
)

;; Not needed in webmaker 3.
;; And wml file in webmaker 2.3 can be modified to produce the BORDER=0 and
;; Alt=... too (use literal HTML).
;; (defun miadoc-replace8 ()
;;   (interactive)
;;   (set-variable 'tags-file-name nil)
;; 
;;   (let ((case-replace t))
;;     (message "Removing borders from buttons")
;;     (tags-query-replace "<IMG\\s-+ALIGN\\s-*=\\s-*BOTTOM\\s-+SRC\\s-*=\\s-*\"\\.\\./images/\\(\\w+\\)\\.gif\">;; " "<IMG ALIGN=\"BOTTOM\" ALT=\"\\1\" BORDER=0 SRC=\"\\.\\./images/\\1.gif\">
;; " nil))
;; )

(defun miadoc-replace9 ()
  (interactive)
  (set-variable 'tags-file-name nil)

  (let ((case-replace t))
    (message "Changing PRE to class BETA")
    (tags-query-replace "<PRE>" "<PRE CLASS=beta>" nil))
)

(defun miadoc-replace10 ()
  (interactive)
  (set-variable 'tags-file-name nil)

  (let ((case-replace t))
    (message "Removing META")
    (tags-query-replace "<META.*>" "" nil))
)

(defun miadoc-replace11 ()
  (interactive)
  (set-variable 'tags-file-name nil)

  (let ((case-replace t))
    (message "Removing &middot;")
    (tags-query-replace "<LI>&middot;" "<LI>" nil))
)

