(defun miadoc-replace0 ()
  (interactive)
  (set-variable 'tags-file-name nil)

  (let ((case-replace t))
    (message "Fixing newlines")
    (tags-query-replace "" "
" nil)))

(defun miadoc-replace1 (basefilename)
  (interactive "sWebMaker base filename: " )
  (set-variable 'tags-file-name nil)

  (let ((case-replace t) (match (concat basefilename "-[12].html")) )
    (message "Replacing first and second file name with index.html")
    (tags-query-replace match "index.html" nil)
))

(defun miadoc-replace1t (basefilename)
  (interactive "sWebMaker base filename: " )
  (set-variable 'tags-file-name nil)

  (let ((case-replace t) (match (concat basefilename "-[12].html")) )
    (message "Replacing first and second file name with ../mjolner-tut/index.html")
    (tags-query-replace match "../mjolner-tut/index.html" nil)
))
(defun miadoc-replace1r (basefilename)
  (interactive "sWebMaker base filename: " )
  (set-variable 'tags-file-name nil)

  (let ((case-replace t) (match (concat basefilename "-[12].html")) )
    (message "Replacing first and second file name with ../mjolner/index.html")
    (tags-query-replace match "../mjolner/index.html" nil)
))

(defun miadoc-replace2 ()
  (interactive)
  (set-variable 'tags-file-name nil);;;

  (let ((case-replace t))
    (message "Replacing contents.html with index.html")
    (tags-query-replace "contents.html" "index.html" nil)
))
(defun miadoc-replace2-2 ()
  (interactive)
  (set-variable 'tags-file-name nil);;;

  (let ((case-replace t))
    (message "Removing Up buttons")
    (tags-query-replace "<A HREF=index.html><IMG ALIGN=BOTTOM SRC=\"../images/up.gif\" ALT=Up BORDER=0></A>" "" nil)
))
(defun miadoc-replace2-3 ()
  (interactive)
  (set-variable 'tags-file-name nil);;;

  (let ((case-replace t))
    (message "Fixing Top buttons")
    (tags-query-replace "<A HREF=index.html><IMG ALIGN=BOTTOM SRC=\"../images/top.gif\" ALT=Top BORDER=0></A>" "<A HREF=../index.html><IMG ALIGN=BOTTOM SRC=\"../images/top.gif\" ALT=Top BORDER=0></A>" nil)
))



(defun miadoc-replace3 (lastfilename)
  (interactive "sLast WebMaker generated file: " )
  (set-variable 'tags-file-name nil)

  (let ((case-replace t))
    (message "Replacing last file name with inx.html")
    (tags-query-replace lastfilename "inx.html" nil)
))

(defun miadoc-replace4 ()
  (interactive)
  (set-variable 'tags-file-name nil)

  (let ((case-replace t))
    (message "Removing WebMaker comment")
    (tags-query-replace "<!-- Generated by Harlequin Webmaker .* -->" "" nil)
))

(defun miadoc-replace5 ()
  (interactive)
  (set-variable 'tags-file-name nil)

  (let ((case-replace t))
    (message "Removing version numbers")
    (tags-query-replace "/v[0-9]+\\.[0-9]+\\.?[0-9]*" "" nil))
)

(defun miadoc-replace6 ()
  (interactive)
  (set-variable 'tags-file-name nil)

  (let ((case-replace t))
    (message "Adding anchors to index entries")
    (find-file "inx.html")
    (query-replace-regexp "<H2>\\([A-Z]\\)</H2>" "<H2><A NAME=_\\1>\\1</A></H2>" nil))
)

(defun miadoc-replace7 ()
  (interactive)
  (set-variable 'tags-file-name nil)

  (let ((case-replace t))
    (message "Adding Style sheet")
    (tags-query-replace "</TITLE>" "</TITLE>
<LINK REL=stylesheet HREF=../style/miadoc.css TYPE=text/css>" nil))
)

(defun miadoc-replace8 ()
  (interactive)
  (set-variable 'tags-file-name nil)

  (let ((case-replace t))
    (message "Fixing MIA references")
    (tags-query-replace "\\[MIA\\s-*\\(9[0-9]-[0-9]+\\)\\]" "<A HREF=\"../bibliography/index.html#mia\\1\">[MIA \\1]</A>" nil)))

(defun miadoc-replace9 ()
  (interactive)
  (set-variable 'tags-file-name nil)

  (let ((case-replace t))
    (message "Changing PRE to class BETA")
    (tags-query-replace "<PRE>" "<PRE CLASS=beta>" nil)))

(defun miadoc-replace10 ()
  (interactive)
  (set-variable 'tags-file-name nil)

  (let ((case-replace t))
    (message "Removing META")
    (tags-query-replace "<META.*>" "" nil)))

(defun miadoc-replace11 ()
  (interactive)
  (set-variable 'tags-file-name nil)

  (let ((case-replace t))
    (message "Removing &middot;")
    (tags-query-replace "<LI>&middot;" "<LI>" nil)))

(defun miadoc-replace12 ()
  (interactive)
  (set-variable 'tags-file-name nil)

  (let ((case-replace t))
    (message "Removing <DIV>")
    (tags-query-replace "</?DIV>" "" nil)))

(defun miadoc-replace13 ()
  (interactive)
  (set-variable 'tags-file-name nil)

  (let ((case-replace t))
    (message "Fixing Madsen 93 references")
    (tags-query-replace "\\[Madsen 93\\]" "<A HREF=\"../bibliography/index.html#mmn93\">[MMN 93]</A>" nil)))

(defun miadoc-replace14 ()
  (interactive)
  (set-variable 'tags-file-name nil)

  (let ((case-replace t))
    (message "Fixing Knudsen 94 references")
    (tags-query-replace "\\[Knudsen 94\\]" "<A HREF=\"../bibliography/index.html#knudsen94\">[Knudsen 94]</A>" nil)))

(defun miadoc-replace15 ()
  (interactive)
  (set-variable 'tags-file-name nil)

  (let ((case-replace t))
    (message "Removing FM pgf ignored")
    (tags-query-replace "<!-- FM pgf ignored -->" "" nil)))

(defun miadoc-replace16 ()
  (interactive)
  (set-variable 'tags-file-name nil)

  (let ((case-replace t))
    (message "Removing empty lines in PRE")
    (tags-query-replace "<PRE CLASS=beta>

" "<PRE CLASS=beta>
" nil)))

(defun miadoc-replace17 ()
  (interactive)
  (set-variable 'tags-file-name nil)

  (let ((case-replace t))
    (message "Replacing &iquest;")
    (tags-query-replace "&iquest;" "&oslash;" nil)))

(defun miadoc-replace18 (manualname)
  (interactive "sManual name: ")
  (set-variable 'tags-file-name nil);;;

  (let ((case-replace t))
    (message "Replacing Contents headers with %s" manualname)
    (tags-query-replace "<P> Contents</P>" (format "<P>%s</P>" manualname) nil)
))

(defun miadoc-replace19 ()
  (interactive)
  (set-variable 'tags-file-name nil)

  (let ((case-replace t))
    (message "Removing up buttons")
    (tags-query-replace "<LINK REL=UP HREF=index.html>" "" nil)))

(defun miadoc-replace20 ()
  (interactive)
  (set-variable 'tags-file-name nil)

  (let ((case-replace t))
    (message "Removing up buttons")
    (tags-query-replace "<A HREF=index.html><IMG ALIGN=BOTTOM SRC=\"../images/up.gif\" ALT=Up BORDER=0></A>" "" nil)))

(defun miadoc-replace21 ()
  (interactive)
  (set-variable 'tags-file-name nil)

  (let ((case-replace t))
    (message "Removing empty lines in PRE")
    (tags-query-replace "
+
</PRE>" "
</PRE>" nil)))

(defun miadoc-replace22 ()
  (interactive)
  (set-variable 'tags-file-name nil)

  (let ((case-replace t))
    (message "Fixing quotes")
    (tags-query-replace "&ograve;" "'" nil)))

(defun miadoc-replace23 ()
  (interactive)
  (set-variable 'tags-file-name nil)

  (let ((case-replace t))
    (message "Removing REL LINKs")
    (tags-query-replace "<LINK REL=[A-Z]+ HREF=[^>]+.html>" "" nil)))

(defun miadoc-replace24 ()
  (interactive)
  (set-variable 'tags-file-name nil)

  (let ((case-replace t))
    (message "Removing /current")
    (tags-query-replace "/current" "" nil)))

(defun miadoc-replace25 ()
  (interactive)
  (set-variable 'tags-file-name nil)

  (let ((case-replace t))
    (message "Removing &yen;")
    (tags-query-replace "<LI>&yen;" "<LI>" nil)))
 
(defun miadoc-replace26 ()
  (interactive)
  (set-variable 'tags-file-name nil)

  (let ((case-replace t))
    (message "Fixing quotes")
    (tags-query-replace "&otilde;" "'" nil)))

(defun miadoc-replace27 ()
  (interactive)
  (set-variable 'tags-file-name nil)

  (let ((case-replace t))
    (message "Removing empty PRE's")
    (tags-query-replace "<PRE CLASS=beta>
</PRE>" "" nil)))

(defun miadoc-replace28 ()
  (interactive)
  (set-variable 'tags-file-name nil)

  (let ((case-replace t))
    (message "Appending beta captions")
    (tags-query-replace "<P> \\([a-zA-Z0-9_]+\\.bet\\)</P>" "<A NAME=\\1><H4 CLASS=betacaption>\\1</H4></A>" nil)))

(defun miadoc-replace28-H2 ()
  (interactive)
  (set-variable 'tags-file-name nil)

  (let ((case-replace t))
    (message "Appending beta captions")
    (tags-query-replace "<H2> \\([a-zA-Z0-9_]+\\.bet\\)</H2>" "<A NAME=\\1><H4 CLASS=betacaption>\\1</H4></A>" nil)))

(defun miadoc-replace28-1 ()
  (interactive)
  (set-variable 'tags-file-name nil)

  (let ((case-replace t))
    (message "Appending NAME to old beta captions")
    (tags-query-replace "<H4 CLASS=betacaption>\\([a-zA-Z0-9_]+\\.bet\\)</H4>" "<A NAME=\\1><H4 CLASS=betacaption>\\1</H4></A>" nil)))

(defun miadoc-replace28-2 ()
  (interactive)
  (set-variable 'tags-file-name nil)

  (let ((case-replace t))
    (message "Appending NAME to old beta captions")
    (tags-query-replace "<H4 NAME=\\([a-zA-Z0-9_]+\\.bet\\) CLASS=betacaption>\\1</H4>" "<A NAME=\\1><H4 CLASS=betacaption>\\1</H4></A>" nil)))

(defun miadoc-replace29 ()
  (interactive)
  (set-variable 'tags-file-name nil)

  (let ((case-replace t))
    (message "Fixing dots")
    (tags-query-replace "&Eacute;" "..." nil)))

(defun miadoc-replace30 ()
  (interactive)
  (set-variable 'tags-file-name nil)

  (let ((case-replace t))
    (message "Fixing spaces")
    (tags-query-replace "&Ecirc;" " " nil)))

(defun miadoc-replace31 ()
  (interactive)
  (set-variable 'tags-file-name nil)

  (let ((case-replace t))
    (message "Fixing IMG tags")
    (tags-query-replace "<P> <IMG ALIGN=TOP SRC=xwindows-[0-9]+-image-[0-9]+.gif></P>" "<BLOCKQUOTE><IMG ALIGN=TOP SRC=images//.gif></BLOCKQUOTE>" nil)))


(defun miadoc-replace32 ()
  (interactive)
  (set-variable 'tags-file-name nil)

  (let ((case-replace t))
    (message "Fixing quotes")
    (tags-query-replace "&ocirc;" "'" nil)))


(defun miadoc-replace33 ()
  (interactive)
  (set-variable 'tags-file-name nil)

  (let ((case-replace t))
    (message "Fixing quotes")
    (tags-query-replace "&oacute;" "'" nil)))

(defun miadoc-replace34 ()
  (interactive)
  (set-variable 'tags-file-name nil)

  (let ((case-replace t))
    (message "Fixing dash")
    (tags-query-replace "&Ntilde;" " - " nil)))


(defun miadoc-replace35 ()
  (interactive)
  (set-variable 'tags-file-name nil)

  (let ((case-replace t)(case-fold-search t))
    (message "Fixing footer")
    (tags-query-replace "<TD width=\"33%\" align=\"left\">\\s-*<ADDRESS>\\(.*\\)</ADDRESS>\\s-*</TD>\\s-*<TD width=\"34%\" align=\"center\"><FONT size=-1>&COPY; <A HREF=\"http://www.mjolner.com\">Mj&oslash;lner Informatics</A></FONT></TD>\\s-*<TD width=\"33%\" align=\"right\"><FONT size=-1><SCRIPT LANGUAGE=JavaScript SRC=\"\\(\\.?\\.?/?\\.?\\.?/?\\)javascript/lastmod.js\"></SCRIPT></FONT></TD>" 
"<TD width=\"40%\" align=\"left\">
<ADDRESS>\\1</ADDRESS>
</TD>
<TD width=\"20%\" align=\"center\"><FONT size=-1>&COPY; <A HREF=\"http://www.mjolner.com\">Mj&oslash;lner Informatics</A></FONT></TD>
<TD width=\"40%\" align=\"right\"><SCRIPT LANGUAGE=JavaScript SRC=\"\\2javascript/lastmod.js\"></SCRIPT></TD>" nil)))

(defun miadoc-replace36 ()
  (interactive)
  (set-variable 'tags-file-name nil)

  (let ((case-replace t)(case-fold-search t))
    (message "Fixing footer")
    (tags-query-replace "<TD width=\"33%\" align=\"left\">\\s-*<ADDRESS>\\(.*\\)</ADDRESS>\\s-*</TD>\\s-*<TD width=\"34%\" align=\"center\">&nbsp;?</TD>\\s-*<TD width=\"33%\" align=\"right\"><FONT size=-1><SCRIPT LANGUAGE=JavaScript SRC=\"\\(\\.?\\.?/?\\.?\\.?/?\\)javascript/lastmod.js\"></SCRIPT></FONT></TD>" 
"<TD width=\"50%\" align=\"left\">
<ADDRESS>\\1</ADDRESS>
</TD>
<TD width=\"50%\" align=\"right\"><SCRIPT LANGUAGE=JavaScript SRC=\"\\2javascript/lastmod.js\"></SCRIPT></TD>" nil)))

(defun miadoc-replace37 ()
  (interactive)
  (set-variable 'tags-file-name nil)

  (let ((case-replace t))
    (message "Fixing quotes")
    (tags-query-replace "&otilde;" "'" nil)))

