#!/bin/sh

#--------- Configuration: ------

# Directories containing source files:
SRC="${BETALIB}/comlib"

# Files to include in interface. The order given here will
# be the order they appear in in the generated interface.
FILES="\
holders.bet \
unicodetext.bet \
comtypes.bet \
wTypes.bet \
Unknwn.bet \
ObjIdl.bet \
comlib.bet \
"

MAKEINT=../../bin/beta2int.perl
#MAKEHTML=../../bin/int2html.perl
MAKEHTML=../../bin/int2frames.perl

. ../../bin/makeHTML.sh
