#!/bin/sh
#
#
# recompile on other supported platforms than SUN4S


sun4=jaguar
sun4s=fraxinus
hpux9mc=louise
hpux9pa=ronchamp
linux=ceres
sgi=lithium

platforms="$sun4 $hpux9pa $hpux9mc $linux $sgi"


beta="/users/beta/bin/beta -w "

echo "--- Code-generating (in batch) on all platforms: $platforms"
echo "--- Must have been checked on sun4s!!"

sleep 5


for p in $platforms
do
case $p in
	$sun4) TARGET=SUN4
		;;
	$sun4s)
		TARGET=SUN4S
		;;
	$hpux9mc)
		TARGET=HPUX9MC
		;;
	$hpux9pa)
		TARGET=HPUX9PA
		;;
	$linux)
		TARGET=LINUX
		;;
	$sgi)
		TARGET=SGI
		;;
esac
echo "	rsh $p ($beta  -o "$TARGET"makepretty morepretty; $beta  -o "$TARGET"morepretty morepretty  > recomp.$p.lst)"
(rsh $p "(cd prettygen/v5.1;   setenv BETALIB /users/beta; \
          $beta  -o "$TARGET"makepretty makepretty; \
          strip "$TARGET"makepretty; \
 	  $beta  -o "$TARGET"morepretty morepretty; \
          strip "$TARGET"morepretty;)"> recomp.$p.lst 2>&1; ) &

done

echo "--- Consult the files: recomp.*.lst for the results"
