#!/bin/sh
#
#
# 


sun4=jaguar
sun4s=fraxinus
hpux9mc=louise
hpux9pa=ronchamp
linux=ceres
sgi=lithium

platforms="$sun4 $hpux9pa $hpux9mc $linux $sgi"

clear;
for p in $platforms
do

echo "*****" $p "*************************************************************************"
tail recomp.$p.lst
echo "  "
	
done

