#!/bin/sh
#
#
# recompile on all supported platforms

VERSION=v1.8

sun4s=quercus
sun4=tatra
hpux8=louise
hpux9pa=angers
linux=ceres

#platforms="$sun4s $sun4 $snake $hpux9pa $hpux8 $linux"
platforms="$sun4s"

beta="/users/beta/bin/beta+"

echo "--- Checking on $sun4s:"

if [ "`hostname`" = "$sun4s" ]
then
	echo "$beta --nocode -q xawbdraw | tee recomp.check.lst"
	$beta --nocode -q xawbdraw | tee recomp.check.lst
	echo "$beta --nocode -q xmbdraw | tee recomp.xm.check.lst"
	$beta --nocode -q xmbdraw | tee recomp.xm.check.lst
else
	echo "rsh $sun4s $beta --nocode -q xawbdraw | tee recomp.check.lst"
	rsh $sun4s "$beta --nocode -q xawbdraw | tee recomp.check.lst"
	echo "rsh $sun4s $beta --nocode -q xmbdraw | tee recomp.xm.check.lst"
	rsh $sun4s "$beta --nocode -q xmbdraw | tee recomp.xm.check.lst"
fi

echo "--- Code-generating (in batch) on all platforms: $platforms"

for p in $platforms
do
case $p in
	$sun4s)
		TARGET=SUN4S
		;;
	$sun4)
		TARGET=SUN4
		;;
	$hpux8)
		TARGET=HPUX8
		;;
	$snake)
		TARGET=SNAKE
		;;
	$hpux9pa)
		TARGET=HPUX9PA
		;;
	$linux)
		TARGET=LINUX
		;;
esac

if [ "`hostname`" = "$p" ]
then
	echo "\"$beta --static -q -o ${TARGET}bdraw xawbdraw; $beta -q -o ${TARGET}xmbdraw xmbdraw\""
        (  sh -c "BETALIB=/users/beta; export BETALIB;          \
                  cd /users/beta/bifrost/$VERSION/bdraw;        \
                  $beta --static -q -o ${TARGET}bdraw xawbdraw; \
                  /users/beta/bin/Strip ${TARGET}bdraw;         \
                  $beta -q -o ${TARGET}xmbdraw xmbdraw;         \
                  /users/beta/bin/Strip ${TARGET}xmbdraw"       \
                  2>&1) >recomp.$p.lst &
else
	echo "rsh $p \"$beta --static -q -o ${TARGET}bdraw xawbdraw; $beta -q -o ${TARGET}xmbdraw xmbdraw\""
	( rsh $p "sh -c \
                  \"BETALIB=/users/beta; export BETALIB;        \
                  cd /users/beta/bifrost/$VERSION/bdraw;        \
                  $beta --static -q -o ${TARGET}bdraw xawbdraw; \
                  /users/beta/bin/Strip ${TARGET}bdraw;         \
                  $beta -q -o ${TARGET}xmbdraw xmbdraw;         \
                  /users/beta/bin/Strip ${TARGET}xmbdraw\""     \
                  2>&1) >recomp.$p.lst &
fi
done

echo "--- Consult the files: recomp.*.lst for the results"
