.TH betatar 1 "June-27-1997" "MBS r4.1" "Mjolner Informatics" 
.\"  Copyright (c) 1996-97 Mjolner Informatics
.de BP
.sp
.ti \-.2i
\(**
..

.SH NAME
betatar \- BETA archiving program
.SH SYNOPSIS
.hy 0
.na
.B betatar
.RB "[\|" \-\-help | \-h "\|]"
.RB "[\|" \-\-extent | \-e "\|]"
.RB "[\|" \-\-domain | \-d "\|]"
.RB "[\|" \-\-full | \-f "\|]"
.RB "[\|" \-\-ast | \-a "\|]"
.RB "[\|" \-\-asm  | \-s"\|]"
.RB "[\|" \-\-code | \-c "\|]"
.RB "[\|" \-\-debug | \-b "\|]"
.RB "[\|" \-\-job | \-j "\|]"
.RB "[\|" \-\-dump | \-u "\|]"
.RB "[\|" \-\-total | \-t "\|]"
.RB "[\|" \-\-ignore | \-x 
.I rexps
]
.RB "[\|" \-\-include | \-i 
.I rexps
]
.RB "[\|" \-\-verbose | \-v "\|]"
.RB "[\|" \-\-compress | \-m "\|]"
.RB "[\|" \-\-gzip | \-g "\|]"
.RB "[\|" \-\-zip | \-z "\|]"
.RB "[\|" \-\-list | \-l "\|]"
.IR file ...
.ad b
.hy 1
.PP
.SH AVAILABILITY
The Mjolner System betatar(1) utility is available as part of the Mjolner
BETA System from Mjolner Informatics.
.PP
.SH DESCRIPTION
.I betatar
is an archiving program.  
betatar(1) makes use different external programs, such as
.B tar(1)
or
.B zip(1)
and for compressing the files, betatar(1) makes use of
.B compress(1)
or
.B gzip(1)
Which is actually used depends on the options (see later).

.I betatar
is used to create an archive of all files related to a BETA
fragment file (BETA source files, etc.)  
.I betatar
is intended to be used for packaging the entire set of files,
contributing to a given BETA program in order to move this program to
another installation for further work (debugging or further
development).  Typical usages include moving a program between, say, a
PC at home and the UNIX workstation at work, or between different
development teams.

.I betatar
offers many different options for controlling which files are
packaged into the archive file.  The most important aspect of 
.I betatar
is that it ensures that all necessary files are collected into the archive
file (except if certain options are used - see later), such that, when
unpacked, all needed files will be in place for continued work.

.I betatar
works by traversing the dependency graph of the fragment graph,
following ORIGIN, INCLUDE, BODY and MDBODY fragment links, starting
at the fragment specified in the file given as argument to 
.I betatar.
During this traversal (identical to the dependency analysis conducted
by the BETA compiler), 
.I betatar
selects the fragments to be included in the archive file, depending on the
different options specified to
.I betatar.
.PP
.SH OPTIONS

.PD 0
.TP
.B \ \-h 
.TP
.B \-\-help
Print this help info
.PD 0
.TP
.B \ \-e 
.TP
.B \-\-extent
Traverse the entire dependency graph, including BODY and MDBODY fragments.
.PD 0
.TP
.B \ \-d 
.TP
.B \-\-domain 	
Traverse the dependency graph, ignoring BODY and MDBODY fragments.
.PD 0
.TP
.B \ \-f 
.TP
.B \-\-full
Choose all fragments found during the traversal of the dependency
graph.  This includes standard libraries from the Mjolner BETA
System.  If 
.I --full
is not specified, all fragments located in $BETALIB/ are ignored
(i.e. standard files are not packed into the archive file).
.PD 0
.TP
.B \ \-a 
.TP
.B \-\-ast
Include .ast/.astL files in the archive file (if the corresponding .bet
file are selected).
.PD 0
.TP
.B \ \-s 
.TP
.B \-\-asm
Include ..s assembler files (if present) in the archive file (if the
corresponding .bet file are selected).
.PD 0
.TP
.B \ \-c 
.TP
.B \-\-code
Include .o code files (if present) in the archive file (if the
corresponding .bet file are selected).
.PD 0
.TP
.B \ \-b 
.TP
.B \-\-debug
Include ..db debug files (if present) in the archive file (if the
corresponding .bet file are selected).
.PD 0
.TP
.B \ \-j 
.TP
.B \-\-job
Include the .job file (if present)
.PD 0
.TP
.B \ \-u 
.TP
.B \-\-dump
Include the .dump file (if present)
.PD 0
.TP
.B \ \-t 
.TP
.B \-\-total
Include all file types (equiv. to "--ast --asm --code --debup --job --dump")
.PD 0
.TP
.B \ \-x 
.TP
.BI "\-\-ignore " string
Ignore fragments found in the traversal if they contain 
.I rexps
in their filename (e.g. 
.I \-\-ignore "basiclib"
will result in all fragments containing 'basiclib' will be ignored.
Note: 
.I rexps
may be any 
.B regexp
pattern.
.br
This option may have more than one "rexp" in the command line, with
different regexps.  The effect will be, that all these fragments are
ignored.
"--ignore rexp" has precedence over all above options.
.PD 0
.TP
.B \ \-i 
.TP
.BI "\-\-include " string
Include fragments found in the traversal if they contain 
.I rexps
in their filename (e.g. 
.I \-\-include "basiclib"
will result in all fragments containing 'basiclib' will be included.
Note: 
.I rexps
may be any 
.B regexp
pattern.
.br
This option may have more than one "rexp" in the command line, with
different regexps.  The effect will be, that all these fragments are
included.
"--include rexp" has precedence over all above options.
.PD 0
.TP
.B \ \-v 
.TP
.B \-\-verbose
print what is saved onto the archive file
.PD 0
.TP
.B \ \-m 
.TP
.B \-\-compress
compress the archive file
.PD 0
.TP
.B \ \-g 
.TP
.B \-\-gzip
use 
.B gzip(1)
instead of 
.B compress(1)
to compress the archive file.
.PD 0
.TP
.B \ \-z 
.TP
.B \-\-zip
use 
.B zip(1)
instead of 
.B tar(1)
to pack the files.
.PD 0
.TP
.B \ \-l 
.TP
.B \-\-list
list the files to be packed. Do not actually pack the files.
.PP
.SH ENVIRONMENT
.I betatar
recognizes the environment variable $BETALIB. Please note
that this variable is given default value in the Bourne Shell
script 
.I $BETALIB/configuration/r4.1/env.sh
.TP
.B BETALIB
Specifies where 
.I ~beta
is located.  If not set,
.I beta
is assumed to be a username, and 
.I ~beta
being the home directory of that user.  Is used by many tools in the Mjolner
BETA System.

.PP
.SH SEE ALSO
.I beta(1)
- BETA Compiler
.br
.sp
.I valhalla(1)
- BETA Source-Level Debugger
.br
.sp
.I betawc(1)
- BETA fragment analyser
.br
.sp
.I betafs(1)
- Mjolner BETA Fragment Structure Lister
.br
.sp
.I sif(1)
- Hyper-Structure Editor
.PP
.SH BUGS
Currently, 
.I betatar
packs the files with full file path specifications, making it
difficult to unpack the files at another location.
.PP
.SH AUTHORS
The betatar(1) utility is developed by Mjolner Informatics as part of
the Mjolner BETA System.

Questions, bug-reports, etc. may be directed to support@mjolner.com if the
local support organization cannot find solutions to the problems.

For more information of the Mjolner BETA System, please contact
Mjolner Informatics, Science Park Aarhus, Gustav Wieds Vej 10, DK-8000 Aarhus C,
Denmark, phone: +45 86 20 20 00, fax: +45 86 20 12 22, e-mail:
info@mjolner.com.
