#!/bin/sh

#--------- Configuration: ------

# Directories containing source files:
SRC="${BETALIB}/guienv"

# Files to include in interface. The order given here will
# be the order they appear in in the generated interface.
FILES="\
utils/buttonadds.bet \
utils/colorConverter.bet \
utils/colorDialog.bet \
utils/colorTable.bet \
utils/cursorTable.bet \
utils/decorator.bet \
utils/defaultstyle.bet \
utils/designsupport.bet \
utils/dialogfield.bet \
utils/graphicsadds.bet \
utils/group.bet \
utils/guienvadds.bet \
utils/guienvstuff.bet \
utils/heapview.bet \
utils/iconname.bet \
utils/interfaceObjectAdds.bet \
utils/labelled.bet \
utils/listview.bet \
utils/navigationkeys.bet \
utils/obguienvadds.bet \
utils/pane.bet \
utils/promptForArgs.bet \
utils/prompts.bet \
utils/rasteradds.bet \
utils/scrolleradds.bet \
utils/simplemenu.bet \
utils/streamwindow.bet \
utils/tabControl.bet \
utils/tableview.bet \
utils/textfieldadds.bet \
utils/tooltip.bet \
utils/walkingants.bet \
"

MAKEINT=../../bin/beta2int.perl
MAKEHTML=../../bin/int2html.perl

. ../../bin/makeHTML.sh
