// Generated .IDL file (by the OLE/COM Object Viewer)
// 
// typelib filename: MSCAL.OCX

[
  uuid(8E27C92E-1264-101C-8A2F-040224009C02),
  version(7.0),
  helpstring("Microsoft Calendar Control 8.0"),
  helpfile("mscal.hlp"),
  helpcontext(0x0000347e)
]
library MSACAL
{
    // TLib :     // TLib : OLE Automation : {00020430-0000-0000-C000-000000000046}
    importlib("STDOLE2.TLB");

    // Forward declare all types defined in this typelib
    interface ICalendar;
    dispinterface DCalendarEvents;

    [
      odl,
      uuid(8E27C92C-1264-101C-8A2F-040224009C02),
      helpstring("Calendar Control"),
      hidden,
      dual,
      oleautomation
    ]
    interface ICalendar : IDispatch {
        [id(0xfffffe0b), propget, bindable, requestedit, helpcontext(0x00003483)]
        HRESULT BackColor([out, retval] OLE_COLOR* pclrBackColor);
        [id(0xfffffe0b), propput, bindable, requestedit, helpcontext(0x00003483)]
        HRESULT BackColor([in] OLE_COLOR pclrBackColor);
        [id(0x00000011), propget, bindable, helpcontext(0x00003484)]
        HRESULT Day([out, retval] short* pnDay);
        [id(0x00000011), propput, bindable, helpcontext(0x00003484)]
        HRESULT Day([in] short pnDay);
        [id(0x00000001), propget, helpcontext(0x00003485)]
        HRESULT DayFont([out, retval] IFontDisp** ppfontDayFont);
        [id(0x00000001), propput, helpcontext(0x00003485)]
        HRESULT DayFont([in] IFontDisp* ppfontDayFont);
        [id(0x00000002), propget, helpcontext(0x00003486)]
        HRESULT DayFontColor([out, retval] OLE_COLOR* pclrDayFontColor);
        [id(0x00000002), propput, helpcontext(0x00003486)]
        HRESULT DayFontColor([in] OLE_COLOR pclrDayFontColor);
        [id(0x00000012), propget, helpcontext(0x00003487)]
        HRESULT DayLength([out, retval] short* pnDayLength);
        [id(0x00000012), propput, helpcontext(0x00003487)]
        HRESULT DayLength([in] short pnDayLength);
        [id(0x00000013), propget, helpcontext(0x00003489)]
        HRESULT FirstDay([out, retval] short* pnFirstDay);
        [id(0x00000013), propput, helpcontext(0x00003489)]
        HRESULT FirstDay([in] short pnFirstDay);
        [id(0x00000014), propget, helpcontext(0x000036e0)]
        HRESULT GridCellEffect([out, retval] long* plGridCellEffect);
        [id(0x00000014), propput, helpcontext(0x000036e0)]
        HRESULT GridCellEffect([in] long plGridCellEffect);
        [id(0x00000003), propget, helpcontext(0x0000348b)]
        HRESULT GridFont([out, retval] IFontDisp** ppfontGridFont);
        [id(0x00000003), propput, helpcontext(0x0000348b)]
        HRESULT GridFont([in] IFontDisp* ppfontGridFont);
        [id(0x00000004), propget, helpcontext(0x0000348c)]
        HRESULT GridFontColor([out, retval] OLE_COLOR* pclrGridFontColor);
        [id(0x00000004), propput, helpcontext(0x0000348c)]
        HRESULT GridFontColor([in] OLE_COLOR pclrGridFontColor);
        [id(0x0000000d), propget, helpcontext(0x0000348d)]
        HRESULT GridLinesColor([out, retval] OLE_COLOR* pclrGridLinesColor);
        [id(0x0000000d), propput, helpcontext(0x0000348d)]
        HRESULT GridLinesColor([in] OLE_COLOR pclrGridLinesColor);
        [id(0x00000010), propget, bindable, helpcontext(0x0000348f)]
        HRESULT Month([out, retval] short* pnMonth);
        [id(0x00000010), propput, bindable, helpcontext(0x0000348f)]
        HRESULT Month([in] short pnMonth);
        [id(0x00000015), propget, helpcontext(0x00003490)]
        HRESULT MonthLength([out, retval] short* pnMonthLength);
        [id(0x00000015), propput, helpcontext(0x00003490)]
        HRESULT MonthLength([in] short pnMonthLength);
        [id(0x00000005), propget, helpcontext(0x00003491)]
        HRESULT ShowDateSelectors([out, retval] VARIANT_BOOL* pfShowDateSelectors);
        [id(0x00000005), propput, helpcontext(0x00003491)]
        HRESULT ShowDateSelectors([in] VARIANT_BOOL pfShowDateSelectors);
        [id(0x00000006), propget, helpcontext(0x00003492)]
        HRESULT ShowDays([out, retval] VARIANT_BOOL* pfShowDays);
        [id(0x00000006), propput, helpcontext(0x00003492)]
        HRESULT ShowDays([in] VARIANT_BOOL pfShowDays);
        [id(0x00000007), propget, helpcontext(0x00003493)]
        HRESULT ShowHorizontalGrid([out, retval] VARIANT_BOOL* pfShowHorizontalGrid);
        [id(0x00000007), propput, helpcontext(0x00003493)]
        HRESULT ShowHorizontalGrid([in] VARIANT_BOOL pfShowHorizontalGrid);
        [id(0x00000008), propget, helpcontext(0x00003494)]
        HRESULT ShowTitle([out, retval] VARIANT_BOOL* pfShowTitle);
        [id(0x00000008), propput, helpcontext(0x00003494)]
        HRESULT ShowTitle([in] VARIANT_BOOL pfShowTitle);
        [id(0x00000009), propget, helpcontext(0x00003495)]
        HRESULT ShowVerticalGrid([out, retval] VARIANT_BOOL* pfShowVerticalGrid);
        [id(0x00000009), propput, helpcontext(0x00003495)]
        HRESULT ShowVerticalGrid([in] VARIANT_BOOL pfShowVerticalGrid);
        [id(0x0000000a), propget, helpcontext(0x00003496)]
        HRESULT TitleFont([out, retval] IFontDisp** ppfontTitleFont);
        [id(0x0000000a), propput, helpcontext(0x00003496)]
        HRESULT TitleFont([in] IFontDisp* ppfontTitleFont);
        [id(0x0000000b), propget, helpcontext(0x00003497)]
        HRESULT TitleFontColor([out, retval] OLE_COLOR* pclrTitleFontColor);
        [id(0x0000000b), propput, helpcontext(0x00003497)]
        HRESULT TitleFontColor([in] OLE_COLOR pclrTitleFontColor);
        [id(0x0000000c), propget, bindable, requestedit, displaybind, defaultbind, helpcontext(0x00003498)]
        HRESULT Value([out, retval] VARIANT* pvarValue);
        [id(0x0000000c), propput, bindable, requestedit, displaybind, defaultbind, helpcontext(0x00003498)]
        HRESULT Value([in] VARIANT pvarValue);
        [id(00000000), propget, hidden]
        HRESULT _Value([out, retval] VARIANT* pvarValue);
        [id(00000000), propput, hidden]
        HRESULT _Value([in] VARIANT pvarValue);
        [id(0x0000000e), propget, helpcontext(0x00003499)]
        HRESULT ValueIsNull([out, retval] VARIANT_BOOL* pfValueIsNull);
        [id(0x0000000e), propput, helpcontext(0x00003499)]
        HRESULT ValueIsNull([in] VARIANT_BOOL pfValueIsNull);
        [id(0x0000000f), propget, bindable, helpcontext(0x0000349a)]
        HRESULT Year([out, retval] short* pnYear);
        [id(0x0000000f), propput, bindable, helpcontext(0x0000349a)]
        HRESULT Year([in] short pnYear);
        [id(0x00000016), helpcontext(0x0000349c)]
        HRESULT NextDay();
        [id(0x00000017), helpcontext(0x0000349e)]
        HRESULT NextMonth();
        [id(0x00000018), helpcontext(0x000034a0)]
        HRESULT NextWeek();
        [id(0x00000019), helpcontext(0x000034a2)]
        HRESULT NextYear();
        [id(0x0000001a), helpcontext(0x000034a4)]
        HRESULT PreviousDay();
        [id(0x0000001b), helpcontext(0x000034a6)]
        HRESULT PreviousMonth();
        [id(0x0000001c), helpcontext(0x000034a8)]
        HRESULT PreviousWeek();
        [id(0x0000001d), helpcontext(0x000034aa)]
        HRESULT PreviousYear();
        [id(0xfffffdda), helpcontext(0x000034ac)]
        HRESULT Refresh();
        [id(0x0000001e), helpcontext(0x000034ae)]
        HRESULT Today();
        [id(0xfffffdd8), helpcontext(0x0000349b)]
        HRESULT AboutBox();
    };

    [
      uuid(8E27C92D-1264-101C-8A2F-040224009C02),
      helpstring("Event interface for Calendar control"),
      hidden
    ]
    dispinterface DCalendarEvents {
        properties:
        methods:
            [id(0xfffffda8), helpcontext(0x000034b1)]
            void Click();
            [id(0xfffffda7), helpcontext(0x000034b2)]
            void DblClick();
            [id(0xfffffda6), helpcontext(0x000034b4)]
            void KeyDown(
                            short* KeyCode, 
                            short Shift);
            [id(0xfffffda5), helpcontext(0x000034b5)]
            void KeyPress(short* KeyAscii);
            [id(0xfffffda4), helpcontext(0x000034b4)]
            void KeyUp(
                            short* KeyCode, 
                            short Shift);
            [id(0x00000002), helpcontext(0x000034b0)]
            void BeforeUpdate(short* Cancel);
            [id(0x00000001), helpcontext(0x000034af)]
            void AfterUpdate();
            [id(0x00000003), helpcontext(0x000034b6)]
            void NewMonth();
            [id(0x00000004), helpcontext(0x000034b7)]
            void NewYear();
    };

    [
      uuid(8E27C92B-1264-101C-8A2F-040224009C02),
      helpstring("Calendar control"),
      helpcontext(0x0000347e),
      control
    ]
    coclass Calendar {
        [default] interface ICalendar;
        [default, source] dispinterface DCalendarEvents;
    };
};
