import "MSO9701.Idl";


    [
      odl,
      uuid(000C0322-0000-0000-C000-000000000046),
      helpcontext(0x00030d40),
      dual,
      nonextensible,
      oleautomation
    ]
    interface Assistant : _IMsoDispObj {
        [id(0x60030000), propget, helpcontext(0x00030d41)]
        HRESULT Parent([out, retval] IDispatch** ppidisp);
        [id(0x60030001), helpcontext(0x00030d42)]
        HRESULT Move(
                        [in] int xLeft, 
                        [in] int yTop);
        [id(0x60030002), propput, helpcontext(0x00030d43)]
        HRESULT Top([in] int pyTop);
        [id(0x60030002), propget, helpcontext(0x00030d43)]
        HRESULT Top([out, retval] int* pyTop);
        [id(0x60030004), propput, helpcontext(0x00030d44)]
        HRESULT Left([in] int pxLeft);
        [id(0x60030004), propget, helpcontext(0x00030d44)]
        HRESULT Left([out, retval] int* pxLeft);
        [id(0x60030006), helpcontext(0x00030d45)]
        HRESULT Help();
        [id(0x60030007), helpcontext(0x00030d46)]
        HRESULT StartWizard(
                        [in] VARIANT_BOOL On, 
                        [in] BSTR Callback, 
                        [in] long PrivateX, 
                        [in, optional] VARIANT Animation, 
                        [in, optional] VARIANT CustomTeaser, 
                        [in, optional] VARIANT Top, 
                        [in, optional] VARIANT Left, 
                        [in, optional] VARIANT Bottom, 
                        [in, optional] VARIANT Right, 
                        [out, retval] long* plWizID);
        [id(0x60030008), helpcontext(0x00030d47)]
        HRESULT EndWizard(
                        [in] long WizardID, 
                        [in] VARIANT_BOOL varfSuccess, 
                        [in, optional] VARIANT Animation);
        [id(0x60030009), helpcontext(0x00030d48)]
        HRESULT ActivateWizard(
                        [in] long WizardID, 
                        [in] MsoWizardActType act, 
                        [in, optional] VARIANT Animation);
        [id(0x6003000a), helpcontext(0x00030d49)]
        HRESULT ResetTips();
        [id(0x6003000b), propget, helpcontext(0x00030d4a)]
        HRESULT NewBalloon([out, retval] IDispatch** ppidisp);
        [id(0x6003000c), propget, helpcontext(0x00030d4b)]
        HRESULT BalloonError([out, retval] MsoBalloonErrorType* pbne);
        [id(0x6003000d), propget, helpcontext(0x00030d4c)]
        HRESULT Visible([out, retval] VARIANT_BOOL* pvarfVisible);
        [id(0x6003000d), propput, helpcontext(0x00030d4c)]
        HRESULT Visible([in] VARIANT_BOOL pvarfVisible);
        [id(0x6003000f), propget, helpcontext(0x00030d4d)]
        HRESULT Animation([out, retval] MsoAnimationType* pfca);
        [id(0x6003000f), propput, helpcontext(0x00030d4d)]
        HRESULT Animation([in] MsoAnimationType pfca);
        [id(0x60030011), propget, helpcontext(0x00030d4e)]
        HRESULT Reduced([out, retval] VARIANT_BOOL* pvarfReduced);
        [id(0x60030011), propput, helpcontext(0x00030d4e)]
        HRESULT Reduced([in] VARIANT_BOOL pvarfReduced);
        [id(0x60030013), propput, helpcontext(0x00030d4f)]
        HRESULT AssistWithHelp([in] VARIANT_BOOL pvarfAssistWithHelp);
        [id(0x60030013), propget, helpcontext(0x00030d4f)]
        HRESULT AssistWithHelp([out, retval] VARIANT_BOOL* pvarfAssistWithHelp);
        [id(0x60030015), propput, helpcontext(0x00030d50)]
        HRESULT AssistWithWizards([in] VARIANT_BOOL pvarfAssistWithWizards);
        [id(0x60030015), propget, helpcontext(0x00030d50)]
        HRESULT AssistWithWizards([out, retval] VARIANT_BOOL* pvarfAssistWithWizards);
        [id(0x60030017), propput, helpcontext(0x00030d51)]
        HRESULT AssistWithAlerts([in] VARIANT_BOOL pvarfAssistWithAlerts);
        [id(0x60030017), propget, helpcontext(0x00030d51)]
        HRESULT AssistWithAlerts([out, retval] VARIANT_BOOL* pvarfAssistWithAlerts);
        [id(0x60030019), propput, helpcontext(0x00030d52)]
        HRESULT MoveWhenInTheWay([in] VARIANT_BOOL pvarfMove);
        [id(0x60030019), propget, helpcontext(0x00030d52)]
        HRESULT MoveWhenInTheWay([out, retval] VARIANT_BOOL* pvarfMove);
        [id(0x6003001b), propput, helpcontext(0x00030d53)]
        HRESULT Sounds([in] VARIANT_BOOL pvarfSounds);
        [id(0x6003001b), propget, helpcontext(0x00030d53)]
        HRESULT Sounds([out, retval] VARIANT_BOOL* pvarfSounds);
        [id(0x6003001d), propput, helpcontext(0x00030d54)]
        HRESULT FeatureTips([in] VARIANT_BOOL pvarfFeatures);
        [id(0x6003001d), propget, helpcontext(0x00030d54)]
        HRESULT FeatureTips([out, retval] VARIANT_BOOL* pvarfFeatures);
        [id(0x6003001f), propput, helpcontext(0x00030d55)]
        HRESULT MouseTips([in] VARIANT_BOOL pvarfMouse);
        [id(0x6003001f), propget, helpcontext(0x00030d55)]
        HRESULT MouseTips([out, retval] VARIANT_BOOL* pvarfMouse);
        [id(0x60030021), propput, helpcontext(0x00030d56)]
        HRESULT KeyboardShortcutTips([in] VARIANT_BOOL pvarfKeyboardShortcuts);
        [id(0x60030021), propget, helpcontext(0x00030d56)]
        HRESULT KeyboardShortcutTips([out, retval] VARIANT_BOOL* pvarfKeyboardShortcuts);
        [id(0x60030023), propput, helpcontext(0x00030d57)]
        HRESULT HighPriorityTips([in] VARIANT_BOOL pvarfHighPriorityTips);
        [id(0x60030023), propget, helpcontext(0x00030d57)]
        HRESULT HighPriorityTips([out, retval] VARIANT_BOOL* pvarfHighPriorityTips);
        [id(0x60030025), propput, helpcontext(0x00030d58)]
        HRESULT TipOfDay([in] VARIANT_BOOL pvarfTipOfDay);
        [id(0x60030025), propget, helpcontext(0x00030d58)]
        HRESULT TipOfDay([out, retval] VARIANT_BOOL* pvarfTipOfDay);
        [id(0x60030027), propput, helpcontext(0x00030d59)]
        HRESULT GuessHelp([in] VARIANT_BOOL pvarfGuessHelp);
        [id(0x60030027), propget, helpcontext(0x00030d59)]
        HRESULT GuessHelp([out, retval] VARIANT_BOOL* pvarfGuessHelp);
        [id(0x60030029), propput, helpcontext(0x00030d5a)]
        HRESULT SearchWhenProgramming([in] VARIANT_BOOL pvarfSearchInProgram);
        [id(0x60030029), propget, helpcontext(0x00030d5a)]
        HRESULT SearchWhenProgramming([out, retval] VARIANT_BOOL* pvarfSearchInProgram);
        [id(00000000), propget, helpcontext(0x00030d5b)]
        HRESULT Item([out, retval] BSTR* pbstrName);
        [id(0x6003002c), propget, helpcontext(0x00030d5c)]
        HRESULT FileName([out, retval] BSTR* pbstr);
        [id(0x6003002c), propput, helpcontext(0x00030d5c)]
        HRESULT FileName([in] BSTR pbstr);
        [id(0x6003002e), propget, helpcontext(0x00030d5d)]
        HRESULT Name([out, retval] BSTR* pbstrName);
    };

    [
      odl,
      uuid(000C0324-0000-0000-C000-000000000046),
      helpcontext(0x00031128),
      dual,
      nonextensible,
      oleautomation
    ]
    interface Balloon : _IMsoDispObj {
        [id(0x60030000), propget, helpcontext(0x00031129)]
        HRESULT Parent([out, retval] IDispatch** ppidisp);
        [id(0x60030001), propget, helpcontext(0x0003112a)]
        HRESULT Checkboxes([out, retval] IDispatch** ppidisp);
        [id(0x60030002), propget, helpcontext(0x0003112b)]
        HRESULT Labels([out, retval] IDispatch** ppidisp);
        [id(0x60030003), propput, helpcontext(0x0003112c)]
        HRESULT BalloonType([in] MsoBalloonType pbty);
        [id(0x60030003), propget, helpcontext(0x0003112c)]
        HRESULT BalloonType([out, retval] MsoBalloonType* pbty);
        [id(0x60030005), propput, helpcontext(0x0003112d)]
        HRESULT Icon([in] MsoIconType picn);
        [id(0x60030005), propget, helpcontext(0x0003112d)]
        HRESULT Icon([out, retval] MsoIconType* picn);
        [id(0x60030007), propput, helpcontext(0x0003112e)]
        HRESULT Heading([in] BSTR pbstr);
        [id(0x60030007), propget, helpcontext(0x0003112e)]
        HRESULT Heading([out, retval] BSTR* pbstr);
        [id(0x60030009), propput, helpcontext(0x0003112f)]
        HRESULT Text([in] BSTR pbstr);
        [id(0x60030009), propget, helpcontext(0x0003112f)]
        HRESULT Text([out, retval] BSTR* pbstr);
        [id(0x6003000b), propput, helpcontext(0x00031130)]
        HRESULT Mode([in] MsoModeType pmd);
        [id(0x6003000b), propget, helpcontext(0x00031130)]
        HRESULT Mode([out, retval] MsoModeType* pmd);
        [id(0x6003000d), propput, helpcontext(0x00031131)]
        HRESULT Animation([in] MsoAnimationType pfca);
        [id(0x6003000d), propget, helpcontext(0x00031131)]
        HRESULT Animation([out, retval] MsoAnimationType* pfca);
        [id(0x6003000f), propput, helpcontext(0x00031132)]
        HRESULT Button([in] MsoButtonSetType psbs);
        [id(0x6003000f), propget, helpcontext(0x00031132)]
        HRESULT Button([out, retval] MsoButtonSetType* psbs);
        [id(0x60030011), propput, helpcontext(0x00031133)]
        HRESULT Callback([in] BSTR pbstr);
        [id(0x60030011), propget, helpcontext(0x00031133)]
        HRESULT Callback([out, retval] BSTR* pbstr);
        [id(0x60030013), propput, helpcontext(0x00031134)]
        HRESULT Private([in] long plPrivate);
        [id(0x60030013), propget, helpcontext(0x00031134)]
        HRESULT Private([out, retval] long* plPrivate);
        [id(0x60030015), helpcontext(0x00031135)]
        HRESULT SetAvoidRectangle(
                        [in] int Left, 
                        [in] int Top, 
                        [in] int Right, 
                        [in] int Bottom);
        [id(0x60030016), propget, helpcontext(0x00031136)]
        HRESULT Name([out, retval] BSTR* pbstrName);
        [id(0x60030017), helpcontext(0x00031137)]
        HRESULT Show([out, retval] MsoBalloonButtonType* pibtn);
        [id(0x60030018), helpcontext(0x00031138)]
        HRESULT Close();
    };

    [
      odl,
      uuid(000C0326-0000-0000-C000-000000000046),
      helpcontext(0x00031510),
      dual,
      nonextensible,
      oleautomation
    ]
    interface BalloonCheckboxes : _IMsoDispObj {
        [id(0x60030000), propget, helpcontext(0x00031511)]
        HRESULT Name([out, retval] BSTR* pbstrName);
        [id(0x60030001), propget, helpcontext(0x00031512)]
        HRESULT Parent([out, retval] IDispatch** ppidisp);
        [id(00000000), propget, helpcontext(0x00031513)]
        HRESULT Item(
                        [in] int Index, 
                        [out, retval] IDispatch** ppidisp);
        [id(0x60030003), propget, helpcontext(0x00031514)]
        HRESULT Count([out, retval] int* pccbx);
        [id(0x60030003), propput, helpcontext(0x00031514)]
        HRESULT Count([in] int pccbx);
        [id(0xfffffffc), propget, helpcontext(0x00031515)]
        HRESULT _NewEnum([out, retval] IUnknown** ppienum);
    };

    [
      odl,
      uuid(000C0328-0000-0000-C000-000000000046),
      helpcontext(0x000318f8),
      dual,
      nonextensible,
      oleautomation
    ]
    interface BalloonCheckbox : _IMsoDispObj {
        [id(00000000), propget, helpcontext(0x000318f9)]
        HRESULT Item([out, retval] BSTR* pbstrName);
        [id(0x60030001), propget, helpcontext(0x000318fa)]
        HRESULT Name([out, retval] BSTR* pbstrName);
        [id(0x60030002), propget, helpcontext(0x000318fb)]
        HRESULT Parent([out, retval] IDispatch** ppidisp);
        [id(0x60030003), propput, helpcontext(0x000318fc)]
        HRESULT Checked([in] VARIANT_BOOL pvarfChecked);
        [id(0x60030003), propget, helpcontext(0x000318fc)]
        HRESULT Checked([out, retval] VARIANT_BOOL* pvarfChecked);
        [id(0x60030005), propput, helpcontext(0x000318fd)]
        HRESULT Text([in] BSTR pbstr);
        [id(0x60030005), propget, helpcontext(0x000318fd)]
        HRESULT Text([out, retval] BSTR* pbstr);
    };

    [
      odl,
      uuid(000C032E-0000-0000-C000-000000000046),
      helpcontext(0x00031ce0),
      dual,
      nonextensible,
      oleautomation
    ]
    interface BalloonLabels : _IMsoDispObj {
        [id(0x60030000), propget, helpcontext(0x00031ce1)]
        HRESULT Name([out, retval] BSTR* pbstrName);
        [id(0x60030001), propget, helpcontext(0x00031ce2)]
        HRESULT Parent([out, retval] IDispatch** ppidisp);
        [id(00000000), propget, helpcontext(0x00031ce3)]
        HRESULT Item(
                        [in] int Index, 
                        [out, retval] IDispatch** ppidisp);
        [id(0x60030003), propget, helpcontext(0x00031ce4)]
        HRESULT Count([out, retval] int* pcwz);
        [id(0x60030003), propput, helpcontext(0x00031ce4)]
        HRESULT Count([in] int pcwz);
        [id(0xfffffffc), propget, helpcontext(0x00031ce5)]
        HRESULT _NewEnum([out, retval] IUnknown** ppienum);
    };

    [
      odl,
      uuid(000C0330-0000-0000-C000-000000000046),
      helpcontext(0x000320c8),
      dual,
      nonextensible,
      oleautomation
    ]
    interface BalloonLabel : _IMsoDispObj {
        [id(00000000), propget, helpcontext(0x000320c9)]
        HRESULT Item([out, retval] BSTR* pbstrName);
        [id(0x60030001), propget, helpcontext(0x000320ca)]
        HRESULT Name([out, retval] BSTR* pbstrName);
        [id(0x60030002), propget, helpcontext(0x000320cb)]
        HRESULT Parent([out, retval] IDispatch** ppidisp);
        [id(0x60030003), propput, helpcontext(0x000320cc)]
        HRESULT Text([in] BSTR pbstr);
        [id(0x60030003), propget, helpcontext(0x000320cc)]
        HRESULT Text([out, retval] BSTR* pbstr);
    };

    [
      odl,
      uuid(2DF8D04E-5BFA-101B-BDE5-00AA0044DE52),
      helpcontext(0x0003d092)
    ]
    interface DocumentProperty : IDispatch {
        [propget, helpcontext(0x0003d093)]
        IDispatch* _stdcall Parent();
        [helpcontext(0x0003d094)]
        HRESULT _stdcall Delete();
        [propget, helpcontext(0x0003d095)]
        HRESULT _stdcall Name(
                        [in, lcid] long lcid, 
                        [out, retval] BSTR* pbstrRetVal);
        [propput, helpcontext(0x0003d095)]
        HRESULT _stdcall Name(
                        [in, lcid] long lcid, 
                        [in] BSTR pbstrRetVal);
        [propget, helpcontext(0x0003d096)]
        HRESULT _stdcall Value(
                        [in, lcid] long lcid, 
                        [out, retval] VARIANT* pvargRetVal);
        [propput, helpcontext(0x0003d096)]
        HRESULT _stdcall Value(
                        [in, lcid] long lcid, 
                        [in] VARIANT pvargRetVal);
        [propget, helpcontext(0x0003d097)]
        HRESULT _stdcall Type(
                        [in, lcid] long lcid, 
                        [out, retval] MsoDocProperties* ptypeRetVal);
        [propput, helpcontext(0x0003d097)]
        HRESULT _stdcall Type(
                        [in, lcid] long lcid, 
                        [in] MsoDocProperties ptypeRetVal);
        [propget, helpcontext(0x0003d098)]
        HRESULT _stdcall LinkToContent([out, retval] VARIANT_BOOL* pfLinkRetVal);
        [propput, helpcontext(0x0003d098)]
        HRESULT _stdcall LinkToContent([in] VARIANT_BOOL pfLinkRetVal);
        [propget, helpcontext(0x0003d099)]
        HRESULT _stdcall LinkSource([out, retval] BSTR* pbstrSourceRetVal);
        [propput, helpcontext(0x0003d099)]
        HRESULT _stdcall LinkSource([in] BSTR pbstrSourceRetVal);
        [propget, helpcontext(0x0003d09f)]
        HRESULT _stdcall Application([out, retval] IDispatch** ppidisp);
        [propget, helpcontext(0x0003d0a0)]
        HRESULT _stdcall Creator([out, retval] long* plCreator);
    };

    [
      odl,
      uuid(2DF8D04D-5BFA-101B-BDE5-00AA0044DE52),
      helpcontext(0x0003d09a)
    ]
    interface DocumentProperties : IDispatch {
        [propget, helpcontext(0x0003d09b)]
        IDispatch* _stdcall Parent();
        [propget, helpcontext(0x0003d09c)]
        HRESULT _stdcall Item(
                        [in] VARIANT Index, 
                        [in, lcid] long lcid, 
                        [out, retval] DocumentProperty** ppIDocProp);
        [propget, helpcontext(0x0003d09d)]
        HRESULT _stdcall Count([out, retval] long* pc);
        [helpcontext(0x0003d09e)]
        HRESULT _stdcall Add(
                        [in] BSTR Name, 
                        [in] VARIANT_BOOL LinkToContent, 
                        [in, optional] VARIANT Type, 
                        [in, optional] VARIANT Value, 
                        [in, optional] VARIANT LinkSource, 
                        [in, lcid] long lcid, 
                        [out, retval] DocumentProperty** ppIDocProp);
        [propget]
        HRESULT _stdcall _NewEnum([out, retval] IUnknown** ppunkEnum);
        [propget, helpcontext(0x0003d0a1)]
        HRESULT _stdcall Application([out, retval] IDispatch** ppidisp);
        [propget, helpcontext(0x0003d0a2)]
        HRESULT _stdcall Creator([out, retval] long* plCreator);
    };

    typedef enum {
        msoOptionsNew = 1,
        msoOptionsAdd = 2,
        msoOptionsWithin = 3
    } MsoFileFindOptions;

    typedef enum {
        msoViewFileInfo = 1,
        msoViewPreview = 2,
        msoViewSummaryInfo = 3
    } MsoFileFindView;

    typedef enum {
        msoFileFindSortbyAuthor = 1,
        msoFileFindSortbyDateCreated = 2,
        msoFileFindSortbyLastSavedBy = 3,
        msoFileFindSortbyDateSaved = 4,
        msoFileFindSortbyFileName = 5,
        msoFileFindSortbySize = 6,
        msoFileFindSortbyTitle = 7
    } MsoFileFindSortBy;

    typedef enum {
        msoListbyName = 1,
        msoListbyTitle = 2
    } MsoFileFindListBy;

    [
      odl,
      uuid(000C0338-0000-0000-C000-000000000046),
      helpcontext(0x00033838),
      dual,
      nonextensible,
      oleautomation
    ]
    interface IFoundFiles : IDispatch {
        [id(00000000), propget, helpcontext(0x00033839)]
        HRESULT Item(
                        [in] int Index, 
                        [out, retval] BSTR* pbstr);
        [id(0x60020001), propget, helpcontext(0x0003383a)]
        HRESULT Count([out, retval] int* pCount);
        [id(0xfffffffc), propget, restricted]
        HRESULT _NewEnum([out, retval] IUnknown** ppunkEnum);
    };

    [
      odl,
      uuid(000C0337-0000-0000-C000-000000000046),
      helpcontext(0x00033c20),
      dual,
      nonextensible,
      oleautomation
    ]
    interface IFind : IDispatch {
        [id(00000000), propget, helpcontext(0x00033c21)]
        HRESULT SearchPath([out, retval] BSTR* pbstr);
        [id(0x60020001), propget, helpcontext(0x00033c22)]
        HRESULT Name([out, retval] BSTR* pbstr);
        [id(0x60020002), propget, helpcontext(0x00033c23)]
        HRESULT SubDir([out, retval] VARIANT_BOOL* retval);
        [id(0x60020003), propget, helpcontext(0x00033c24)]
        HRESULT Title([out, retval] BSTR* pbstr);
        [id(0x60020004), propget, helpcontext(0x00033c25)]
        HRESULT Author([out, retval] BSTR* pbstr);
        [id(0x60020005), propget, helpcontext(0x00033c26)]
        HRESULT Keywords([out, retval] BSTR* pbstr);
        [id(0x60020006), propget, helpcontext(0x00033c27)]
        HRESULT Subject([out, retval] BSTR* pbstr);
        [id(0x60020007), propget, helpcontext(0x00033c28)]
        HRESULT Options([out, retval] MsoFileFindOptions* penmOptions);
        [id(0x60020008), propget, helpcontext(0x00033c29)]
        HRESULT MatchCase([out, retval] VARIANT_BOOL* retval);
        [id(0x60020009), propget, helpcontext(0x00033c2a)]
        HRESULT Text([out, retval] BSTR* pbstr);
        [id(0x6002000a), propget, helpcontext(0x00033c2b)]
        HRESULT PatternMatch([out, retval] VARIANT_BOOL* retval);
        [id(0x6002000b), propget, helpcontext(0x00033c2c)]
        HRESULT DateSavedFrom([out, retval] VARIANT* pdatSavedFrom);
        [id(0x6002000c), propget, helpcontext(0x00033c2d)]
        HRESULT DateSavedTo([out, retval] VARIANT* pdatSavedTo);
        [id(0x6002000d), propget, helpcontext(0x00033c2e)]
        HRESULT SavedBy([out, retval] BSTR* pbstr);
        [id(0x6002000e), propget, helpcontext(0x00033c2f)]
        HRESULT DateCreatedFrom([out, retval] VARIANT* pdatCreatedFrom);
        [id(0x6002000f), propget, helpcontext(0x00033c30)]
        HRESULT DateCreatedTo([out, retval] VARIANT* pdatCreatedTo);
        [id(0x60020010), propget, helpcontext(0x00033c31)]
        HRESULT View([out, retval] MsoFileFindView* penmView);
        [id(0x60020011), propget, helpcontext(0x00033c32)]
        HRESULT SortBy([out, retval] MsoFileFindSortBy* penmSortBy);
        [id(0x60020012), propget, helpcontext(0x00033c33)]
        HRESULT ListBy([out, retval] MsoFileFindListBy* penmListBy);
        [id(0x60020013), propget, helpcontext(0x00033c34)]
        HRESULT SelectedFile([out, retval] int* pintSelectedFile);
        [id(0x60020014), propget, helpcontext(0x00033c35)]
        HRESULT Results([out, retval] IFoundFiles** pdisp);
        [id(0x60020015), helpcontext(0x00033c36)]
        HRESULT Show([out, retval] int* pRows);
        [id(00000000), propput, helpcontext(0x00033c21)]
        HRESULT SearchPath([in] BSTR pbstr);
        [id(0x60020001), propput, helpcontext(0x00033c22)]
        HRESULT Name([in] BSTR pbstr);
        [id(0x60020002), propput, helpcontext(0x00033c23)]
        HRESULT SubDir([in] VARIANT_BOOL retval);
        [id(0x60020003), propput, helpcontext(0x00033c24)]
        HRESULT Title([in] BSTR pbstr);
        [id(0x60020004), propput, helpcontext(0x00033c25)]
        HRESULT Author([in] BSTR pbstr);
        [id(0x60020005), propput, helpcontext(0x00033c26)]
        HRESULT Keywords([in] BSTR pbstr);
        [id(0x60020006), propput, helpcontext(0x00033c27)]
        HRESULT Subject([in] BSTR pbstr);
        [id(0x60020007), propput, helpcontext(0x00033c28)]
        HRESULT Options([in] MsoFileFindOptions penmOptions);
        [id(0x60020008), propput, helpcontext(0x00033c29)]
        HRESULT MatchCase([in] VARIANT_BOOL retval);
        [id(0x60020009), propput, helpcontext(0x00033c2a)]
        HRESULT Text([in] BSTR pbstr);
        [id(0x6002000a), propput, helpcontext(0x00033c2b)]
        HRESULT PatternMatch([in] VARIANT_BOOL retval);
        [id(0x6002000b), propput, helpcontext(0x00033c2c)]
        HRESULT DateSavedFrom([in] VARIANT pdatSavedFrom);
        [id(0x6002000c), propput, helpcontext(0x00033c2d)]
        HRESULT DateSavedTo([in] VARIANT pdatSavedTo);
        [id(0x6002000d), propput, helpcontext(0x00033c2e)]
        HRESULT SavedBy([in] BSTR pbstr);
        [id(0x6002000e), propput, helpcontext(0x00033c2f)]
        HRESULT DateCreatedFrom([in] VARIANT pdatCreatedFrom);
        [id(0x6002000f), propput, helpcontext(0x00033c30)]
        HRESULT DateCreatedTo([in] VARIANT pdatCreatedTo);
        [id(0x60020010), propput, helpcontext(0x00033c31)]
        HRESULT View([in] MsoFileFindView penmView);
        [id(0x60020011), propput, helpcontext(0x00033c32)]
        HRESULT SortBy([in] MsoFileFindSortBy penmSortBy);
        [id(0x60020012), propput, helpcontext(0x00033c33)]
        HRESULT ListBy([in] MsoFileFindListBy penmListBy);
        [id(0x60020013), propput, helpcontext(0x00033c34)]
        HRESULT SelectedFile([in] int pintSelectedFile);
        [id(0x6002002a), helpcontext(0x00033c37)]
        HRESULT Execute();
        [id(0x6002002b), helpcontext(0x00033c38)]
        HRESULT Load([in] BSTR bstrQueryName);
        [id(0x6002002c), helpcontext(0x00033c39)]
        HRESULT Save([in] BSTR bstrQueryName);
        [id(0x6002002d), helpcontext(0x00033c3a)]
        HRESULT Delete([in] BSTR bstrQueryName);
        [id(0x6002002e), propget, helpcontext(0x00033c3b)]
        HRESULT FileType([out, retval] long* plFileType);
        [id(0x6002002e), propput, helpcontext(0x00033c3b)]
        HRESULT FileType([in] long plFileType);
    };

    typedef enum {
        msoLastModifiedYesterday = 1,
        msoLastModifiedToday = 2,
        msoLastModifiedLastWeek = 3,
        msoLastModifiedThisWeek = 4,
        msoLastModifiedLastMonth = 5,
        msoLastModifiedThisMonth = 6,
        msoLastModifiedAnyTime = 7
    } MsoLastModified;

    typedef enum {
        msoSortByFileName = 1,
        msoSortBySize = 2,
        msoSortByFileType = 3,
        msoSortByLastModified = 4
    } MsoSortBy;

    typedef enum {
        msoSortOrderAscending = 1,
        msoSortOrderDescending = 2
    } MsoSortOrder;

    typedef enum {
        msoConnectorAnd = 1,
        msoConnectorOr = 2
    } MsoConnector;

    typedef enum {
        msoConditionFileTypeAllFiles = 1,
        msoConditionFileTypeOfficeFiles = 2,
        msoConditionFileTypeWordDocuments = 3,
        msoConditionFileTypeExcelWorkbooks = 4,
        msoConditionFileTypePowerPointPresentations = 5,
        msoConditionFileTypeBinders = 6,
        msoConditionFileTypeDatabases = 7,
        msoConditionFileTypeTemplates = 8,
        msoConditionIncludes = 9,
        msoConditionIncludesPhrase = 10,
        msoConditionBeginsWith = 11,
        msoConditionEndsWith = 12,
        msoConditionIncludesNearEachOther = 13,
        msoConditionIsExactly = 14,
        msoConditionIsNot = 15,
        msoConditionYesterday = 16,
        msoConditionToday = 17,
        msoConditionTomorrow = 18,
        msoConditionLastWeek = 19,
        msoConditionThisWeek = 20,
        msoConditionNextWeek = 21,
        msoConditionLastMonth = 22,
        msoConditionThisMonth = 23,
        msoConditionNextMonth = 24,
        msoConditionAnytime = 25,
        msoConditionAnytimeBetween = 26,
        msoConditionOn = 27,
        msoConditionOnOrAfter = 28,
        msoConditionOnOrBefore = 29,
        msoConditionInTheNext = 30,
        msoConditionInTheLast = 31,
        msoConditionEquals = 32,
        msoConditionDoesNotEqual = 33,
        msoConditionAnyNumberBetween = 34,
        msoConditionAtMost = 35,
        msoConditionAtLeast = 36,
        msoConditionMoreThan = 37,
        msoConditionLessThan = 38,
        msoConditionIsYes = 39,
        msoConditionIsNo = 40
    } MsoCondition;

    typedef enum {
        msoFileTypeAllFiles = 1,
        msoFileTypeOfficeFiles = 2,
        msoFileTypeWordDocuments = 3,
        msoFileTypeExcelWorkbooks = 4,
        msoFileTypePowerPointPresentations = 5,
        msoFileTypeBinders = 6,
        msoFileTypeDatabases = 7,
        msoFileTypeTemplates = 8
    } MsoFileType;

    [
      odl,
      uuid(000C0331-0000-0000-C000-000000000046),
      helpcontext(0x00034008),
      dual,
      oleautomation
    ]
    interface FoundFiles : _IMsoDispObj {
        [id(00000000), propget, helpcontext(0x00034009)]
        HRESULT Item(
                        [in] int Index, 
                        [in, lcid] long lcid, 
                        [out, retval] BSTR* pbstrFile);
        [id(0x00000004), propget, helpcontext(0x0003400a)]
        HRESULT Count([out, retval] long* pc);
        [id(0xfffffffc), propget]
        HRESULT _NewEnum([out, retval] IUnknown** ppunkEnum);
    };

    [
      odl,
      uuid(000C0333-0000-0000-C000-000000000046),
      helpcontext(0x000343f0),
      dual,
      nonextensible,
      oleautomation
    ]
    interface PropertyTest : _IMsoDispObj {
        [id(00000000), propget, helpcontext(0x000343f1)]
        HRESULT Name([out, retval] BSTR* pbstrRetVal);
        [id(0x00000002), propget, helpcontext(0x000343f2)]
        HRESULT Condition([out, retval] MsoCondition* pConditionRetVal);
        [id(0x00000003), propget, helpcontext(0x000343f3)]
        HRESULT Value([out, retval] VARIANT* pvargRetVal);
        [id(0x00000004), propget, helpcontext(0x000343f4)]
        HRESULT SecondValue([out, retval] VARIANT* pvargRetVal2);
        [id(0x00000005), propget, helpcontext(0x000343f5)]
        HRESULT Connector([out, retval] MsoConnector* pConnector);
    };

    [
      odl,
      uuid(000C0334-0000-0000-C000-000000000046),
      helpcontext(0x000347d8),
      dual,
      oleautomation
    ]
    interface PropertyTests : _IMsoDispObj {
        [id(00000000), propget, helpcontext(0x000347d9)]
        HRESULT Item(
                        [in] int Index, 
                        [in, lcid] long lcid, 
                        [out, retval] PropertyTest** ppIDocProp);
        [id(0x00000004), propget, helpcontext(0x000347da)]
        HRESULT Count([out, retval] long* pc);
        [id(0x00000005), helpcontext(0x000347db)]
        HRESULT Add(
                        [in] BSTR Name, 
                        [in] MsoCondition Condition, 
                        [in, optional] VARIANT Value, 
                        [in, optional] VARIANT SecondValue, 
                        [in, optional, defaultvalue(1)] MsoConnector Connector);
        [id(0x00000006), helpcontext(0x000347dc)]
        HRESULT Remove([in] int Index);
        [id(0xfffffffc), propget]
        HRESULT _NewEnum([out, retval] IUnknown** ppunkEnum);
    };

    [
      odl,
      uuid(000C0332-0000-0000-C000-000000000046),
      helpcontext(0x00034bc0),
      dual,
      oleautomation
    ]
    interface FileSearch : _IMsoDispObj {
        [id(0x00000001), propget, helpcontext(0x00034bc1)]
        HRESULT SearchSubFolders([out, retval] VARIANT_BOOL* SearchSubFoldersRetVal);
        [id(0x00000001), propput, helpcontext(0x00034bc1)]
        HRESULT SearchSubFolders([in] VARIANT_BOOL SearchSubFoldersRetVal);
        [id(0x00000002), propget, helpcontext(0x00034bc2)]
        HRESULT MatchTextExactly([out, retval] VARIANT_BOOL* MatchTextRetVal);
        [id(0x00000002), propput, helpcontext(0x00034bc2)]
        HRESULT MatchTextExactly([in] VARIANT_BOOL MatchTextRetVal);
        [id(0x00000003), propget, helpcontext(0x00034bc3)]
        HRESULT MatchAllWordForms([out, retval] VARIANT_BOOL* MatchAllWordFormsRetVal);
        [id(0x00000003), propput, helpcontext(0x00034bc3)]
        HRESULT MatchAllWordForms([in] VARIANT_BOOL MatchAllWordFormsRetVal);
        [id(0x00000004), propget, helpcontext(0x00034bc4)]
        HRESULT FileName([out, retval] BSTR* FileNameRetVal);
        [id(0x00000004), propput, helpcontext(0x00034bc4)]
        HRESULT FileName([in] BSTR FileNameRetVal);
        [id(0x00000005), propget, helpcontext(0x00034bc5)]
        HRESULT FileType([out, retval] MsoFileType* FileTypeRetVal);
        [id(0x00000005), propput, helpcontext(0x00034bc5)]
        HRESULT FileType([in] MsoFileType FileTypeRetVal);
        [id(0x00000006), propget, helpcontext(0x00034bc6)]
        HRESULT LastModified([out, retval] MsoLastModified* LastModifiedRetVal);
        [id(0x00000006), propput, helpcontext(0x00034bc6)]
        HRESULT LastModified([in] MsoLastModified LastModifiedRetVal);
        [id(0x00000007), propget, helpcontext(0x00034bc7)]
        HRESULT TextOrProperty([out, retval] BSTR* TextOrProperty);
        [id(0x00000007), propput, helpcontext(0x00034bc7)]
        HRESULT TextOrProperty([in] BSTR TextOrProperty);
        [id(0x00000008), propget, helpcontext(0x00034bc8)]
        HRESULT LookIn([out, retval] BSTR* LookInRetVal);
        [id(0x00000008), propput, helpcontext(0x00034bc8)]
        HRESULT LookIn([in] BSTR LookInRetVal);
        [id(0x00000009), helpcontext(0x00034bc9)]
        HRESULT Execute(
                        [in, optional, defaultvalue(1)] MsoSortBy SortBy, 
                        [in, optional, defaultvalue(1)] MsoSortOrder SortOrder, 
                        [in, optional, defaultvalue(-1)] VARIANT_BOOL AlwaysAccurate, 
                        [out, retval] int* pRet);
        [id(0x0000000a), helpcontext(0x00034bca)]
        HRESULT NewSearch();
        [id(0x0000000b), propget, helpcontext(0x00034bcb)]
        HRESULT FoundFiles([out, retval] FoundFiles** FoundFilesRet);
        [id(0x0000000c), propget, helpcontext(0x00034bcc)]
        HRESULT PropertyTests([out, retval] PropertyTests** PropTestsRet);
    };
