
Print of foo: bar(1 2 text"Hello" ^ 0)

Found using the prototype of foo:
	Pattern name:     bar
	GC table:         312120
	Origin Offset:    4
	Generation Part:  155016
	Size (longs):     14
	Prefix labId:     integerValue#
	Located in file:  ~beta/sysutils/demo/objinterface/objint
	LabId:            bar#

	Static reference at offset  24
	Dynamic reference at offset 8
	Dynamic reference at offset 16
	Dynamic reference at offset 48
