
BetaConverter.class:
	mkdir -p classes/beta/converter
	javac -sourcepath sources -d classes -classpath classes sources/beta/converter/BetaConverter.java

clean:
	/bin/rm -f *~ *.class *.ast *.astL *.a2s \#*
	/bin/rm -rf classes


