#!/bin/sh

#--------- Configuration: ------

# Directories containing source files:
SRC="${BETALIB}/Xt"

# Files to include in interface. The order given here will
# be the order they appear in in the generated interface.
FILES="\
xtenv.bet \
events.bet \
xsystemenv.bet \
"

MAKEINT=../../../bin/beta2int.perl
#MAKEHTML=../../../bin/int2html.perl
MAKEHTML=../../../bin/int2frames.perl
OPTIONS="-v -x"

. ../../../bin/makeHTML.sh
