#!/bin/sh

case "`uname -m`" in
        sun4*)
                case "`uname -r`" in
                4.1*)
			echo SunOS: Only doing \"make asm\"
			make asm
			;;
		*)
			echo $0: only on SunOS 4.1 or Linux
			;;
		esac
		;;
	i?86)
		case "$1" in
		"debug")
			echo Linux: not doing \"make asm\"
			make debug
			;;
		*)
			echo Linux: not doing \"make asm\"
			make
			;;
		esac
		;;
	*)
		echo $0: only on SunOS 4.1 or Linux
		;;
esac
