intMultiSet1.elements: 1,2,3,4,
intMultiSet2.elements: 4,5,6,7,
intMultiSet2->intMultiSet3: 4,5,6,7,
"7"->intMultiSet3.delete: 4,5,6,
"4"->intMultiSet3.delete: 6,5,
intMultiSet1[]->intMultiSet2.union: 4,5,6,7,1,2,3,4,
intMultiSet1[]->intMultiSet2.diff: 7,5,6,
intMultiSet1[]->intMultiSet2.sect: 4,
intMultiSet1[]->intMultiSet2.symDiff: 4,5,6,7,1,2,3,
intMultiSet3.find(# predicate ::< (# "elm=4" #) #): 4
4->intMultiSet3.has: yes
10->intMultiSet3.has: no
