#ifndef _PROFILE_H_
#define _PROFILE_H_

/* CONSTANTS */
/* #define PROFILE_PERSISTENCE */

enum {
  UNKNOWN,
  LOOKUPREFERENCEENTRY,
  CREATECROSSSTORETABLE,
  SAVECURRENTCROSSSTORETABLE,
  SETCURRENTCROSSSTORETABLE,
  NEWSTOREPROXY,
  LOOKUPSTOREPROXY,
  CREATEOBJECTSTORE,
  SAVECURRENTOBJECTSTORE,
  SETCURRENTOBJECTSTORE,
  NEWSTOREOBJECT,
  LOOKUPSTOREOBJECT,
  SETSTOREOBJECT,
  LOADOBJECT,
  MAXTICKS
};

/* MACROES */
#ifdef PROFILE_PERSISTENCE
#define SETSIM(code) (isSim = code)
#else
#define SETSIM(code)
#endif /* PROFILE_PERSISTENCE */

/* TYPES */

/* VARIABLES */
extern u_long isSim;

/* FUNCTIONS */

void start_vtimer(void);
void show_vtimer(void);

#endif /* _PROFILE_H_ */
