#!/bin/sh

echo Hammer icons

cat folderclosed.xpm | sed 's/none/#ffffff/i' | xpmtoppm | pnmscale 12 > prjclosed.ppm
cat prjopen.xpm | sed 's/none/#ffffff/i' | xpmtoppm | pnmscale 12 > prjopen.ppm
cat fg.xpm | sed 's/none/#ffffff/i' | xpmtoppm | pnmscale 12 > fg.ppm

xpmtoppm folderopenmask.xpm | pnmscale 12 | ppmtopgm | pgmtopbm -thresh | tee folderopenmask.pbm | pnminvert > folderopeninversemask.pbm

    djpeg M_icon.jpg | pnmpad -white -l47 -t86 > M_icon.ppm
    ppmtorgb3 M_icon.ppm
    pnmarith -sub M_icon.blu M_icon.red | ppmquant 2 | ppmtopgm | pgmtopbm -thresh -value 0.3 | pbmmask > M_icon.pbm
    pnminvert M_icon.pbm | pnmarith -mult - M_icon.ppm > M_icononly.ppm

pnmarith -mult prjclosed.ppm M_icon.pbm | pnmarith -add - M_icononly.ppm | tee prjclosedhammer.ppm | pnmscale  0.0416666666666666666 | tee tv-prjclosed-noquant.ppm | ppmquant -map map.ppm | ppmtoxpm > tv-prjclosed.xpm

    djpeg M_icon.jpg | pnmpad -white -r73 -t86 | pnmcut 26 0 408 432 > M_icon.ppm
    ppmtorgb3 M_icon.ppm
    pnmarith -sub M_icon.blu M_icon.red | ppmquant 2 | ppmtopgm | pgmtopbm -thresh -value 0.3 | pbmmask > M_icon.pbm
    pnminvert M_icon.pbm | pnmarith -mult - M_icon.ppm > M_icononly.ppm

pnmarith -mult fg.ppm M_icon.pbm | pnmarith -add - M_icononly.ppm | tee fghammer.ppm | pnmscale  0.0416666666666666666 | tee tv-fg-noquant.ppm | ppmquant -map map.ppm | ppmtoxpm | sed 's/#ffffff/none/i' > tv-fg.xpm

    djpeg M_icon.jpg | pnmpad -white -l47 -t86 > M_icon.ppm
    ppmtorgb3 M_icon.ppm
    pnmarith -sub M_icon.blu M_icon.red | ppmquant 2 | ppmtopgm | pgmtopbm -thresh -value 0.3 | pbmmask > M_icon.pbm
    pnminvert M_icon.pbm | pnmarith -mult - M_icon.ppm > M_icononly.ppm

pnmarith -mult prjopen.ppm folderopeninversemask.pbm > prjopenonly.ppm
pnmarith -mult prjopen.ppm M_icon.pbm | pnmarith -add - M_icononly.ppm | pnmarith -mult - folderopenmask.pbm | pnmarith -add - prjopenonly.ppm | tee prjopenhammer.ppm | pnmscale  0.0416666666666666666 | tee tv-prjopen-noquant.ppm | ppmquant -map map.ppm | ppmtoxpm > tv-prjopen.xpm

echo End Hammer icons
