#!/bin/sh

# Script to make icons from basic files.  Start with name-pic.xpm and
# name-text.xpm and make name.xpm, name-shadow.xpm, name-small.xpm and
# name-small-shadow.xpm.  Also all the png files.
# To run this you need the pbm tools and ImageMagic (for convert).  Try
# a Linux machine if they are not available.
#
#
# The text is made with the font you get with
# xfontsel -pattern '-*-interface system-medium-r-*-*-12-*-*-*-*-*-iso8859-*'

sed 's/none/#dddddd/i' blank-48-27.xpm | xpmtoppm > blank-48-27.ppm
cp blank-48-27.ppm allcolors.ppm
sed 's/none/#dddddd/i' blank-48-39.xpm | xpmtoppm > blank-48-39.ppm
sed 's/none/#dddddd/i' blank-32-18.xpm | xpmtoppm > blank-32-18.ppm

for name in backbtn frwbtn compbtn chkbtn downbtn upbtn dbgbtn
do
cat $name-pic.xpm | sed 's/none/#dddddd/i' | xpmtoppm | pnmscale 0.666666666666666666666666666666 | pnmcat -lr - allcolors.ppm > allcolorsnew.ppm
mv allcolorsnew.ppm allcolors.ppm
cat $name-pic.xpm | sed 's/none/#dddddd/i' | xpmtoppm | pnmcat -lr - allcolors.ppm > allcolorsnew.ppm
mv allcolorsnew.ppm allcolors.ppm
cat $name-pic.xpm | sed 's/none/#dddddd/i' | xpmtoppm | pnmscale 0.666666666666666666666666666666 | ppmmix 0.7 - blank-32-18.ppm | pnmcat -lr - allcolors.ppm > allcolorsnew.ppm
mv allcolorsnew.ppm allcolors.ppm
done

ppmquant 25 allcolors.ppm > map.ppm

# Shrink images:

for name in backbtn frwbtn compbtn chkbtn downbtn upbtn dbgbtn
do
echo $name
cat $name-text.xpm | sed 's/none/#dddddd/i' | xpmtoppm > $name-text.ppm
cat $name-pic.xpm | sed 's/none/#dddddd/i' | xpmtoppm | pnmcat -tb - $name-text.ppm | ppmquant -map map.ppm | ppmtoxpm | sed 's/#dddddd/none/i' > $name.xpm
cat $name-pic.xpm | sed 's/none/#dddddd/i' | xpmtoppm | pnmscale 0.666666666666666666666666666666 | ppmquant -map map.ppm | ppmtoxpm | sed 's/#dddddd/none/i' > $name-small.xpm
cat $name-pic.xpm | sed 's/none/#dddddd/i' | xpmtoppm | pnmcat -tb - $name-text.ppm | ppmmix 0.7 - blank-48-39.ppm | ppmquant -map map.ppm | ppmtoxpm | sed 's/#dddddd/none/i' > $name-shadow.xpm
cat $name-pic.xpm | sed 's/none/#dddddd/i' | xpmtoppm | pnmscale 0.666666666666666666666666666666 | ppmmix 0.7 - blank-32-18.ppm | ppmquant -map map.ppm | ppmtoxpm | sed 's/#dddddd/none/i' > $name-small-shadow.xpm

convert $name.xpm $name.png
convert $name-shadow.xpm $name-shadow.png
convert $name-small.xpm $name-small.png
convert $name-small-shadow.xpm $name-small-shadow.png
convert $name.xpm $name.bmp
convert $name-shadow.xpm $name-shadow.bmp
convert $name-small.xpm $name-small.bmp
convert $name-small-shadow.xpm $name-small-shadow.bmp
done

