#!/bin/sh

# Script to make icons from basic files.  Start with name-pic.xpm and
# name-text.xpm and make name.xpm, name-shadow.xpm, name-small.xpm and
# name-small-shadow.xpm.  Also all the png files.
# To run this you need the pbm tools and ImageMagic (for convert).  Try
# a Linux machine if they are not available.
#
#
# The text is made with the font you get with
# xfontsel -pattern '-*-interface system-medium-r-*-*-12-*-*-*-*-*-iso8859-*'

mvifchng () {
  if cmp -s $1 $2
  then
    echo $2 not changed, leaving alone
    rm $1
  else
    echo $2 changed
    mv $1 $2
  fi
}
    

# Make blank ppm files from xpm sources
sed 's/none/#dddddd/i' blank-48-27.xpm | xpmtoppm > blank-48-27.ppm
sed 's/none/#dddddd/i' blank-48-39.xpm | xpmtoppm > blank-48-39.ppm
sed 's/none/#dddddd/i' blank-32-18.xpm | xpmtoppm > blank-32-18.ppm

# Make scaled version of bricks for BUILD directive in treeview
cat compbtn-pic.xpm | sed 's/none/#ffffff/i' |  sed 's/#bbbbbb/#ffffff/i' | xpmtoppm | pnmcrop | pnmscale -xsize 22 -ysize 11 | pnmpad -white -t7 > doc.ppm

cat cat.xpm | sed 's/none/#dddddd/' | xpmtoppm | pnmscale 0.5 | ppmtoxpm | sed 's/#dddddd/none/' > runbtn-pic.xpm

# Make initial allcolors file
pnmcat -tb doc.ppm blank-48-27.ppm > allcolors.ppm

for name in backbtn frwbtn compbtn chkbtn downbtn upbtn dbgbtn umlbtn guibtn runbtn
do
cat $name-pic.xpm | sed 's/none/#dddddd/i' | xpmtoppm | pnmscale 0.666666666666666666666666666666 | pnmcat -tb - allcolors.ppm > allcolorsnew.ppm
mv allcolorsnew.ppm allcolors.ppm
cat $name-pic.xpm | sed 's/none/#dddddd/i' | xpmtoppm | pnmscale 0.666666666666666666666666666666 | ppmmix 0.7 - blank-32-18.ppm | pnmcat -tb - allcolors.ppm > allcolorsnew.ppm
mv allcolorsnew.ppm allcolors.ppm
done

for name in folderclosed folderopen ff ffsel origin include body link
do
  cat $name.xpm | sed 's/none/#ffffff/i' | xpmtoppm | pnmscale 0.5 | pnmcat -tb - allcolors.ppm > allcolorsnew.ppm
  mv allcolorsnew.ppm allcolors.ppm
done


# We have to have a map.ppm so that hammericons can run, but it doesn't
# matter what is in it this time.
if [ ! -f map.ppm ]
then
  cp allcolors.ppm map.ppm
fi

./hammericons no

# Now we ran hammericons we have some unquantised icons to add to the
# gallery
pnmcat -tb tv-prjclosed-noquant.ppm tv-prjopen-noquant.ppm tv-fg-noquant.ppm allcolors.ppm > allcolorsnew.ppm
mv allcolorsnew.ppm allcolors.ppm


# Now pick 64 colours to cover the entire palette
ppmquant 64 allcolors.ppm | tee quantedicons.ppm | ppmtomap > map.ppm

# Now we have the 64 colour we can redo the hammer icons with the right colours
./hammericons yes

# Shrink images:

for name in backbtn frwbtn compbtn chkbtn downbtn upbtn dbgbtn umlbtn guibtn runbtn
do
  echo $name
  cat $name-text.xpm | sed 's/none/#dddddd/i' | xpmtoppm > $name-text.ppm
  cat $name-pic.xpm | sed 's/none/#dddddd/i' | xpmtoppm | pnmcat -tb - $name-text.ppm | ppmtoxpm | sed 's/#dddddd/none/i' > tmp.xpm
  mvifchng tmp.xpm $name.xpm
  cat $name-pic.xpm | sed 's/none/#dddddd/i' | xpmtoppm | pnmscale 0.666666666666666666666666666666 | ppmquant -map map.ppm | ppmtoxpm | sed 's/#dddddd/none/i' > tmp.xpm
  mvifchng tmp.xpm $name-small.xpm
  cat $name-pic.xpm | sed 's/none/#dddddd/i' | xpmtoppm | pnmcat -tb - $name-text.ppm | ppmmix 0.7 - blank-48-39.ppm | ppmtoxpm | sed 's/#dddddd/none/i' > tmp.xpm
  mvifchng tmp.xpm $name-shadow.xpm
  cat $name-pic.xpm | sed 's/none/#dddddd/i' | xpmtoppm | pnmscale 0.666666666666666666666666666666 | ppmmix 0.7 - blank-32-18.ppm | ppmquant -map map.ppm | ppmtoxpm | sed 's/#dddddd/none/i' > tmp.xpm
  mvifchng tmp.xpm $name-small-shadow.xpm
  
  convert $name.xpm tmp.png
  mvifchng tmp.png $name.png
  convert $name-shadow.xpm tmp.png
  mvifchng tmp.png $name-shadow.png
  convert $name-small.xpm tmp.png
  mvifchng tmp.png $name-small.png
  convert $name-small-shadow.xpm tmp.png
  mvifchng tmp.png $name-small-shadow.png
done

# The xxx.xpm files are source.  The tv-* files are produced here.
# Lines nodes and links are the exception to this

ppmquant -map map.ppm doc.ppm | ppmtoxpm | sed 's/#ffffff/none/i' > tv-doc.xpm

for name in folderclosed folderopen ff ffsel origin include body link
do
  cat $name.xpm | sed 's/none/#ffffff/i' | xpmtoppm | pnmscale 0.5 | ppmquant -map map.ppm | ppmtoxpm | sed 's/#ffffff/none/i' > tmp.xpm
  mvifchng tmp.xpm tv-$name.xpm
  convert tv-$name.xpm tmp.png
  mvifchng tmp.png tv-$name.png
done

for name in prjopen prjclosed fg
do
  convert tv-$name.xpm tmp.png
  mvifchng tmp.png tv-$name.png
done

for name in blank doc lastnode mlastnode mnode mrootnode node plastnode pnode prootnode vertline
do
  convert tv-$name.xpm tmp.png
  mvifchng tmp.png tv-$name.png
done

mv map.ppm map.saved
mv quantedicons.ppm quantedicons.saved
rm *.p?m
mv map.saved map.ppm
mv quantedicons.saved quantedicons.ppm
