#!/bin/sh

# Script to make icons from basic files.  Start with name-pic.xpm and
# name-text.xpm and make name.xpm, name-shadow.xpm, name-small.xpm and
# name-small-shadow.xpm.  Also all the png files.
# To run this you need the pbm tools and ImageMagic (for convert).  Try
# a Linux machine if they are not available.
#
#
# The text is made with the font you get with
# xfontsel -pattern '-*-interface system-medium-r-*-*-12-*-*-*-*-*-iso8859-*'

# Make blank ppm files from xpm sources
sed 's/none/#dddddd/i' blank-48-27.xpm | xpmtoppm > blank-48-27.ppm
sed 's/none/#dddddd/i' blank-48-39.xpm | xpmtoppm > blank-48-39.ppm
sed 's/none/#dddddd/i' blank-32-18.xpm | xpmtoppm > blank-32-18.ppm

# Make scaled version of bricks for BUILD directive in treeview
cat compbtn-pic.xpm | sed 's/none/#ffffff/i' |  sed 's/#bbbbbb/#ffffff/i' | xpmtoppm | pnmcrop | pnmscale -xsize 22 -ysize 11 | pnmpad -white -t7 > doc.ppm

# Make initial allcolors file
pnmcat -lr doc.ppm blank-48-27.ppm > allcolors.ppm

for name in backbtn frwbtn compbtn chkbtn downbtn upbtn dbgbtn umlbtn guibtn
do
cat $name-pic.xpm | sed 's/none/#dddddd/i' | xpmtoppm | pnmscale 0.666666666666666666666666666666 | pnmcat -lr - allcolors.ppm > allcolorsnew.ppm
mv allcolorsnew.ppm allcolors.ppm
cat $name-pic.xpm | sed 's/none/#dddddd/i' | xpmtoppm | pnmscale 0.666666666666666666666666666666 | ppmmix 0.7 - blank-32-18.ppm | pnmcat -lr - allcolors.ppm > allcolorsnew.ppm
mv allcolorsnew.ppm allcolors.ppm
done

ppmquant 32 allcolors.ppm > map.ppm

# Shrink images:

for name in backbtn frwbtn compbtn chkbtn downbtn upbtn dbgbtn umlbtn guibtn
do
  echo $name
  cat $name-text.xpm | sed 's/none/#dddddd/i' | xpmtoppm > $name-text.ppm
  cat $name-pic.xpm | sed 's/none/#dddddd/i' | xpmtoppm | pnmcat -tb - $name-text.ppm | ppmtoxpm | sed 's/#dddddd/none/i' > $name.xpm
  cat $name-pic.xpm | sed 's/none/#dddddd/i' | xpmtoppm | pnmscale 0.666666666666666666666666666666 | ppmquant -map map.ppm | ppmtoxpm | sed 's/#dddddd/none/i' > $name-small.xpm
  cat $name-pic.xpm | sed 's/none/#dddddd/i' | xpmtoppm | pnmcat -tb - $name-text.ppm | ppmmix 0.7 - blank-48-39.ppm | ppmtoxpm | sed 's/#dddddd/none/i' > $name-shadow.xpm
  cat $name-pic.xpm | sed 's/none/#dddddd/i' | xpmtoppm | pnmscale 0.666666666666666666666666666666 | ppmmix 0.7 - blank-32-18.ppm | ppmquant -map map.ppm | ppmtoxpm | sed 's/#dddddd/none/i' > $name-small-shadow.xpm
  
  convert $name.xpm $name.png
  convert $name-shadow.xpm $name-shadow.png
  convert $name-small.xpm $name-small.png
  convert $name-small-shadow.xpm $name-small-shadow.png
done

# The xxx.xpm files are source.  The tv-* files are produced here.
# Lines nodes and links are the exception to this

ppmquant -map map.ppm doc.ppm | ppmtoxpm | sed 's/#ffffff/none/i' > tv-doc.xpm

for name in folderopen folderclosed prjclosed prjopen fg ff origin include body
do
  cat $name.xpm | sed 's/none/#ffffff/i' | xpmtoppm | pnmscale 0.5 | ppmtoxpm | sed 's/#ffffff/none/i' > tv-$name.xpm
  convert tv-$name.xpm tv-$name.png
done

# What about link

for name in blank doc lastnode mlastnode mnode mrootnode node plastnode pnode prootnode vertline
do
  convert tv-$name.xpm tv-$name.png
done
