#!/bin/sh
#
#
# 


sun4=ferrari
sun4s=fraxinus
hpux9mc=louise
hpux9pa=ronchamp
linux=faxe
sgi=lithium

platforms="$sun4 $hpux9pa $linux $sgi"


for p in $platforms
do

echo "*****" $p "*************************************************************************"
more recomp/recomp.$p.lst
echo "  "

done

