#!/bin/sh
#
#
# 


sun4s=ariel
hpux9pa=ronchamp
linux=delirium
sgi=arsenic

platforms="$hpux9pa $linux $sgi"


for p in $platforms
do

echo "*****" $p "*************************************************************************"
more recomp/recomp.$p.lst
echo "  "

done

