#!/bin/sh
#
#
# recompile on other supported platforms than SUN4S


sun4sp=ariel
hpux9pap=ronchamp
linuxp=delirium
sgip=arsenic

platforms="$linuxp $hpux9pap $sgip"

betalocation=/users/beta/r4.2

beta="$betalocation/bin/beta -w"

echo "--- Code-generating (in batch) on all platforms: $platforms"
echo "--- Must have been checked on sun4s!!"

sleep 5


for p in $platforms
do
case $p in
	$sun4sp)
		codedir=sun4s
		;;
	$hpux9pap)
		codedir=hpux9pa
		;;
	$linuxp)
		codedir=linux
		;;
	$sgip)
		codedir=sgi
		;;
esac

	echo "	rsh $p ($beta  -o $codedir/sif sif > recomp/recomp.$p.lst)"
	(rsh $p "(cd $betalocation/editor;   setenv BETALIB $betalocation; \
                  $beta  -o  "$codedir/sif" sif; \
                  )"> recomp/recomp.$p.lst 2>&1) &

done

echo "--- Consult the files: recomp/recomp.*.lst for the results"
