#!/bin/sh
#
#
# recompile on other supported platforms than SUN4S


sun4=ferrari
sun4s=fraxinus
hpux9mc=louise
hpux9pa=ronchamp
linux=heineken
sgi=lithium

platforms="$sun4 $hpux9pa $sgi"


beta="/users/beta/bin/beta -w"

echo "--- Code-generating (in batch) on all platforms: $platforms"
echo "--- Must have been checked on sun4s!!"

sleep 5


for p in $platforms
do
case $p in
	$sun4) TARGET=SUN4
		;;
	$sun4s)
		TARGET=SUN4S
		;;
	$hpux9mc)
		TARGET=HPUX9MC
		;;
	$hpux9pa)
		TARGET=HPUX9PA
		;;
	$linux)
		TARGET=LINUX
		;;
	$sgi)
		TARGET=SGI
		;;
esac

if [ "$TARGET" = "SUN4" ] 
then
	echo "	rsh $p ($beta --static -o "$TARGET"sif sif > recomp/recomp.$p.lst)"
	(rsh $p "(cd editor/v5.1;  setenv TMPDIR .; setenv BETALIB /users/beta; \
                  $beta  --static -o "$TARGET"sif sif; \
                  )" > recomp/recomp.$p.lst 2>&1) &
else
	echo "	rsh $p ($beta  -o "$TARGET"sif sif > recomp/recomp.$p.lst)"
	(rsh $p "(cd editor/v5.1;   setenv BETALIB /users/beta; \
                  $beta  -o "$TARGET"sif sif; \
                  )"> recomp/recomp.$p.lst 2>&1) &
fi

done

echo "--- Consult the files: recomp/recomp.*.lst for the results"
