#!/bin/sh
#
#
# 


sun4=ferrari
sun4s=fraxinus
hpux9mc=louise
hpux9pa=ronchamp
linux=faxe
sgi=lithium

platforms="$sun4 $hpux9pa  $sgi $linux"

clear;
for p in $platforms
do

echo "*****" $p "*************************************************************************"
tail recomp/recomp.$p.lst
echo "  "
	
done

