#!/bin/sh
#
#
# 


sun4s=ariel
hpux9pa=ronchamp
linux=delirium
sgi=arsenic

platforms="$hpux9pa  $sgi $linux"

clear;
for p in $platforms
do

echo "*****" $p "*************************************************************************"
tail recomp/recomp.$p.lst
echo "  "
	
done

