#!/bin/sh

#--------- Configuration: ------

# Directories containing source files:
SRC="${BETALIB}/guienv"

# Files to include in interface. The order given here will
# be the order they appear in in the generated interface.
FILES="\
guienv.bet \
stddialogs.bet \
controls.bet \
fields.bet \
figureitems.bet \
scrolllists.bet \
graphmath.bet \
graphics.bet \
raster.bet \
styledtext.bet \
guienvactions.bet \
controlsactions.bet \
fieldsactions.bet \
guienvall.bet \
guienvsystemenv.bet \
"

MAKEINT=../../bin/beta2int.perl
MAKEHTML=../../bin/int2html.perl


#----- Don't change below ! -----

/bin/rm -f *.int
echo Making interface descriptions for $SRC.
echo ""
for srcdir in $SRC
do
    for file in $FILES
    do
	if [ ! -f $srcdir/$file ]; then continue; fi
	INT=`basename $srcdir/$file .bet`.int
	echo Making $INT from $srcdir/$file ...
	expand $srcdir/$file | $MAKEINT > $INT
	INTFILES="${INTFILES} $INT"
    done
done

echo Creating HTML:
$MAKEHTML -v $INTFILES
/bin/rm -f *.int
echo done.
