#!/bin/sh

#--------- Configuration: ------

# Directories containing source files:
SRC="${BETALIB}/guienv"

# Files to include in interface. The order given here will
# be the order they appear in in the generated interface.
FILES="\
controls.bet \
controlsactions.bet \
fields.bet \
fieldsactions.bet \
figureitems.bet \
graphics.bet \
graphmath.bet \
guienv.bet \
guienvactions.bet \
guienvall.bet \
guienvsystemenv.bet \
scrolllists.bet \
stddialogs.bet \
styledtext.bet \
"

MAKEINT=../../bin/beta2int.perl
#MAKEHTML=../../bin/int2html.perl
MAKEHTML=../../bin/int2frames.perl

. ../../bin/makeHTML.sh
