#!/bin/sh

#--------- Configuration: ------

# Directories containing source files:
SRC="${BETALIB}/containers"

# Files to include in interface. The order given here will
# be the order they appear in in the generated interface.
FILES="\
container.bet \
collection.bet \
sets.bet \
classification.bet \
hashTable.bet \
dictionary.bet \
arrayContainer.bet \
list.bet \
recList.bet \
seqContainers.bet \
"

MAKEINT=../../bin/beta2int.perl
#MAKEHTML=../../bin/int2html.perl
MAKEHTML=../../bin/int2frames.perl
OPTIONS=-w

. ../../bin/makeHTML.sh
