
1:pushthis 

2:invoke 1 0 1 BETAworld:1002:descInx:1 
thisObj = BETAworld[main,main][]  thisStack = main[main][]
1:rstore 1 main->BETAworld[1]
3:allocEventQ 1 
5:pushthis 
6:saveBETAworld 
7:mvStack 
thisObj = BETAworld[main,main][]  thisStack = BETAworld[main,main][]
8:pushthis 

9:invoke 3 2 1 (0)BETA:1003:descInx:3 
thisObj = (0)BETA[BETAworld,BETAworld][]  thisStack = BETAworld[main,main,BETAworld][]
1:rstore 1 BETAworld->(0)BETA[1]
3:allocEventQ 1 
5:mvStack 
thisObj = (0)BETA[BETAworld,BETAworld][]  thisStack = (0)BETA[BETAworld,BETAworld][]
6:rtnEventQ 0 
8:mvStack 
thisObj = (0)BETA[BETAworld,BETAworld][]  thisStack = (0)BETA[BETAworld,BETAworld][]
9:rtnEventQ 0 
11:setThisStack 
thisObj = (0)BETA[BETAworld,BETAworld][]  thisStack = BETAworld[main,main][]
12:pushthis 

13:rtn D (0)BETA:1003:descInx:3  to: BETAworld:1002:descInx:1 
thisObj = BETAworld[main,main,(0)BETA][]  thisStack = BETAworld[main,main,(0)BETA][]
15:rpop 
16:pushthis 

17:invoke 71 3 1 (0)LIB:1004:descInx:71 
thisObj = (0)LIB[BETAworld,BETAworld][]  thisStack = BETAworld[main,main,BETAworld][]
1:rstore 1 BETAworld->(0)LIB[1]
3:allocEventQ 1 
5:mvStack 
thisObj = (0)LIB[BETAworld,BETAworld][]  thisStack = (0)LIB[BETAworld,BETAworld][]
6:pushthis 

7:invoke 72 2 1 (0)BasicSystem:1005:descInx:72 
thisObj = (0)BasicSystem[(0)LIB,(0)LIB][]  thisStack = (0)LIB[BETAworld,BETAworld,(0)LIB][]
1:rstore 1 (0)LIB->(0)BasicSystem[1]
3:allocEventQ 1 
5:mvStack 
thisObj = (0)BasicSystem[(0)LIB,(0)LIB][]  thisStack = (0)BasicSystem[(0)LIB,(0)LIB][]
6:rtnEventQ 0 
8:mvStack 
thisObj = (0)BasicSystem[(0)LIB,(0)LIB][]  thisStack = (0)BasicSystem[(0)LIB,(0)LIB][]
9:rtnEventQ 0 
11:setThisStack 
thisObj = (0)BasicSystem[(0)LIB,(0)LIB][]  thisStack = (0)LIB[BETAworld,BETAworld][]
12:pushthis 

13:rtn D (0)BasicSystem:1005:descInx:72  to: (0)LIB:1004:descInx:71 
thisObj = (0)LIB[BETAworld,BETAworld,(0)BasicSystem][]  thisStack = (0)LIB[BETAworld,BETAworld,(0)BasicSystem][]
13:rpop 
14:pushthis 

15:invoke 160 3 1 (0)Complex:1006:descInx:160 
thisObj = (0)Complex[(0)LIB,(0)LIB][]  thisStack = (0)LIB[BETAworld,BETAworld,(0)LIB][]
1:rstore 1 (0)LIB->(0)Complex[1]
3:allocEventQ 1 
5:mvStack 
thisObj = (0)Complex[(0)LIB,(0)LIB][]  thisStack = (0)Complex[(0)LIB,(0)LIB][]
6:rtnEventQ 0 
8:mvStack 
thisObj = (0)Complex[(0)LIB,(0)LIB][]  thisStack = (0)Complex[(0)LIB,(0)LIB][]
9:rtnEventQ 0 
11:setThisStack 
thisObj = (0)Complex[(0)LIB,(0)LIB][]  thisStack = (0)LIB[BETAworld,BETAworld][]
12:pushthis 

13:rtn D (0)Complex:1006:descInx:160  to: (0)LIB:1004:descInx:71 
thisObj = (0)LIB[BETAworld,BETAworld,(0)Complex][]  thisStack = (0)LIB[BETAworld,BETAworld,(0)Complex][]
21:rpop 
22:pushthis 

23:invoke 73 4 1 (0)Containers:1007:descInx:73 
thisObj = (0)Containers[(0)LIB,(0)LIB][]  thisStack = (0)LIB[BETAworld,BETAworld,(0)LIB][]
1:rstore 1 (0)LIB->(0)Containers[1]
3:allocEventQ 1 
5:mvStack 
thisObj = (0)Containers[(0)LIB,(0)LIB][]  thisStack = (0)Containers[(0)LIB,(0)LIB][]
6:pushthis 

7:invoke 74 2 1 (0)mQueue:1008:descInx:74 
thisObj = (0)mQueue[(0)Containers,(0)Containers][]  thisStack = (0)Containers[(0)LIB,(0)LIB,(0)Containers][]
1:rstore 1 (0)Containers->(0)mQueue[1]
3:allocEventQ 1 
5:mvStack 
thisObj = (0)mQueue[(0)Containers,(0)Containers][]  thisStack = (0)mQueue[(0)Containers,(0)Containers][]
6:rtnEventQ 0 
8:mvStack 
thisObj = (0)mQueue[(0)Containers,(0)Containers][]  thisStack = (0)mQueue[(0)Containers,(0)Containers][]
9:rtnEventQ 0 
11:setThisStack 
thisObj = (0)mQueue[(0)Containers,(0)Containers][]  thisStack = (0)Containers[(0)LIB,(0)LIB][]
12:pushthis 

13:rtn D (0)mQueue:1008:descInx:74  to: (0)Containers:1007:descInx:73 
thisObj = (0)Containers[(0)LIB,(0)LIB,(0)mQueue][]  thisStack = (0)Containers[(0)LIB,(0)LIB,(0)mQueue][]
13:rpop 
14:rtnEventQ 0 
16:mvStack 
thisObj = (0)Containers[(0)LIB,(0)LIB][]  thisStack = (0)Containers[(0)LIB,(0)LIB][]
17:rtnEventQ 0 
19:setThisStack 
thisObj = (0)Containers[(0)LIB,(0)LIB][]  thisStack = (0)LIB[BETAworld,BETAworld][]
20:pushthis 

21:rtn D (0)Containers:1007:descInx:73  to: (0)LIB:1004:descInx:71 
thisObj = (0)LIB[BETAworld,BETAworld,(0)Containers][]  thisStack = (0)LIB[BETAworld,BETAworld,(0)Containers][]
29:rpop 
30:pushthis 

31:invoke 165 5 1 (0)EMC2array:1009:descInx:165 
thisObj = (0)EMC2array[(0)LIB,(0)LIB][]  thisStack = (0)LIB[BETAworld,BETAworld,(0)LIB][]
1:rstore 1 (0)LIB->(0)EMC2array[1]
3:allocEventQ 1 
5:mvStack 
thisObj = (0)EMC2array[(0)LIB,(0)LIB][]  thisStack = (0)EMC2array[(0)LIB,(0)LIB][]
6:rtnEventQ 0 
8:mvStack 
thisObj = (0)EMC2array[(0)LIB,(0)LIB][]  thisStack = (0)EMC2array[(0)LIB,(0)LIB][]
9:rtnEventQ 0 
11:setThisStack 
thisObj = (0)EMC2array[(0)LIB,(0)LIB][]  thisStack = (0)LIB[BETAworld,BETAworld][]
12:pushthis 

13:rtn D (0)EMC2array:1009:descInx:165  to: (0)LIB:1004:descInx:71 
thisObj = (0)LIB[BETAworld,BETAworld,(0)EMC2array][]  thisStack = (0)LIB[BETAworld,BETAworld,(0)EMC2array][]
37:rpop 
38:pushthis 

39:invoke 190 6 1 (0)ForkJoinSystem:1010:descInx:190 
thisObj = (0)ForkJoinSystem[(0)LIB,(0)LIB][]  thisStack = (0)LIB[BETAworld,BETAworld,(0)LIB][]
1:rstore 1 (0)LIB->(0)ForkJoinSystem[1]
3:allocEventQ 1 
5:mvStack 
thisObj = (0)ForkJoinSystem[(0)LIB,(0)LIB][]  thisStack = (0)ForkJoinSystem[(0)LIB,(0)LIB][]
6:rtnEventQ 0 
8:mvStack 
thisObj = (0)ForkJoinSystem[(0)LIB,(0)LIB][]  thisStack = (0)ForkJoinSystem[(0)LIB,(0)LIB][]
9:rtnEventQ 0 
11:setThisStack 
thisObj = (0)ForkJoinSystem[(0)LIB,(0)LIB][]  thisStack = (0)LIB[BETAworld,BETAworld][]
12:pushthis 

13:rtn D (0)ForkJoinSystem:1010:descInx:190  to: (0)LIB:1004:descInx:71 
thisObj = (0)LIB[BETAworld,BETAworld,(0)ForkJoinSystem][]  thisStack = (0)LIB[BETAworld,BETAworld,(0)ForkJoinSystem][]
45:rpop 
46:pushthis 

47:invoke 197 7 1 (0)MonitorSystem:1011:descInx:197 
thisObj = (0)MonitorSystem[(0)LIB,(0)LIB][]  thisStack = (0)LIB[BETAworld,BETAworld,(0)LIB][]
1:rstore 1 (0)LIB->(0)MonitorSystem[1]
3:allocEventQ 1 
5:mvStack 
thisObj = (0)MonitorSystem[(0)LIB,(0)LIB][]  thisStack = (0)MonitorSystem[(0)LIB,(0)LIB][]
6:rtnEventQ 0 
8:mvStack 
thisObj = (0)MonitorSystem[(0)LIB,(0)LIB][]  thisStack = (0)MonitorSystem[(0)LIB,(0)LIB][]
9:rtnEventQ 0 
11:setThisStack 
thisObj = (0)MonitorSystem[(0)LIB,(0)LIB][]  thisStack = (0)LIB[BETAworld,BETAworld][]
12:pushthis 

13:rtn D (0)MonitorSystem:1011:descInx:197  to: (0)LIB:1004:descInx:71 
thisObj = (0)LIB[BETAworld,BETAworld,(0)MonitorSystem][]  thisStack = (0)LIB[BETAworld,BETAworld,(0)MonitorSystem][]
53:rpop 
54:pushthis 

55:invoke 89 9 1 (0)String:1012:descInx:89 
thisObj = (0)String[(0)LIB,(0)LIB][]  thisStack = (0)LIB[BETAworld,BETAworld,(0)LIB][]
1:rstore 1 (0)LIB->(0)String[1]
3:allocEventQ 1 
5:mvStack 
thisObj = (0)String[(0)LIB,(0)LIB][]  thisStack = (0)String[(0)LIB,(0)LIB][]
6:rtnEventQ 0 
8:mvStack 
thisObj = (0)String[(0)LIB,(0)LIB][]  thisStack = (0)String[(0)LIB,(0)LIB][]
9:rtnEventQ 0 
11:setThisStack 
thisObj = (0)String[(0)LIB,(0)LIB][]  thisStack = (0)LIB[BETAworld,BETAworld][]
12:pushthis 

13:rtn D (0)String:1012:descInx:89  to: (0)LIB:1004:descInx:71 
thisObj = (0)LIB[BETAworld,BETAworld,(0)String][]  thisStack = (0)LIB[BETAworld,BETAworld,(0)String][]
61:rpop 
62:rtnEventQ 0 
64:mvStack 
thisObj = (0)LIB[BETAworld,BETAworld][]  thisStack = (0)LIB[BETAworld,BETAworld][]
65:rtnEventQ 0 
67:setThisStack 
thisObj = (0)LIB[BETAworld,BETAworld][]  thisStack = BETAworld[main,main][]
68:pushthis 

69:rtn D (0)LIB:1004:descInx:71  to: BETAworld:1002:descInx:1 
thisObj = BETAworld[main,main,(0)LIB][]  thisStack = BETAworld[main,main,(0)LIB][]
23:rpop 
24:pushthis 

25:invoke 222 4 1 (0)workspace:1013:descInx:222 
thisObj = (0)workspace[BETAworld,BETAworld][]  thisStack = BETAworld[main,main,BETAworld][]
1:rstore 1 BETAworld->(0)workspace[1]
3:allocEventQ 1 
5:mvStack 
thisObj = (0)workspace[BETAworld,BETAworld][]  thisStack = (0)workspace[BETAworld,BETAworld][]
6:pushthis 

7:invoke 422 4 1 (0)demo:1014:descInx:422 
thisObj = (0)demo[(0)workspace,(0)workspace][]  thisStack = (0)workspace[BETAworld,BETAworld,(0)workspace][]
1:rstore 1 (0)workspace->(0)demo[1]
3:allocEventQ 1 
5:mvStack 
thisObj = (0)demo[(0)workspace,(0)workspace][]  thisStack = (0)demo[(0)workspace,(0)workspace][]
6:pushthis 

7:invoke 423 2 1 (0)ArrayDemos:1015:descInx:423 
thisObj = (0)ArrayDemos[(0)demo,(0)demo][]  thisStack = (0)demo[(0)workspace,(0)workspace,(0)demo][]
1:rstore 1 (0)demo->(0)ArrayDemos[1]
3:allocEventQ 1 
5:mvStack 
thisObj = (0)ArrayDemos[(0)demo,(0)demo][]  thisStack = (0)ArrayDemos[(0)demo,(0)demo][]
6:pushthis 

7:invoke 434 4 1 (0)List:1016:descInx:434 
thisObj = (0)List[(0)ArrayDemos,(0)ArrayDemos][]  thisStack = (0)ArrayDemos[(0)demo,(0)demo,(0)ArrayDemos][]
1:rstore 1 (0)ArrayDemos->(0)List[1]
3:allocEventQ 0 
5:mvStack 
thisObj = (0)List[(0)ArrayDemos,(0)ArrayDemos][]  thisStack = (0)List[(0)ArrayDemos,(0)ArrayDemos][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = (0)List[(0)ArrayDemos,(0)ArrayDemos][]  thisStack = (0)List[(0)ArrayDemos,(0)ArrayDemos][]
10:pushText 1 
XmkTextObject
Object: String:1017 lsc: 0
VFields: 18 105 110 116 101 103 101 114 65 114 114 97 121 83 116 97 114 116 49 0 
Rfields: (0)LIB:1004 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
VStack: 
RStack: 
VdtTable: 0 0 0 0 
lscStack: 
--------------


12:invoke 100 0 0 print:1018:descInx:100 
thisObj = print[(0)List,(0)List][]  thisStack = (0)List[(0)ArrayDemos,(0)ArrayDemos,String][]
1:rstore 1 String->print[1]
3:allocEventQ 0 
5:mvStack 
thisObj = print[(0)List,(0)List][]  thisStack = print[(0)List,(0)List][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = print[(0)List,(0)List][]  thisStack = print[(0)List,(0)List][]
10:pushthis 

11:invoke 101 0 1 %for%to%%do%#S#101:1019:descInx:101 
thisObj = %for%to%%do%#S#101[print,print][]  thisStack = print[(0)List,(0)List,print][]
1:rstore 2 print->%for%to%%do%#S#101[2]
3:allocEventQ 1 
5:pushthis 
6:rpushg 2 %for%to%%do%#S#101[2]=print
8:rpushg 1 print[1]=String
10:rpushg 1 String[1]=(0)LIB
12:rpushg 1 (0)LIB[1]=BETAworld
14:pushc 1 
16:pushthis 
17:rpushg 2 %for%to%%do%#S#101[2]=print
19:rpushg 1 print[1]=String

21:invoke 91 0 0 length:1020:descInx:91 
thisObj = length[%for%to%%do%#S#101,print][]  thisStack = print[(0)List,(0)List,BETAworld,String][1]
1:rstore 1 String->length[1]
3:allocEventQ 0 
5:mvStack 
thisObj = length[%for%to%%do%#S#101,print][]  thisStack = length[%for%to%%do%#S#101,print][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = length[%for%to%%do%#S#101,print][]  thisStack = length[%for%to%%do%#S#101,print][]
10:pushthis 
11:pushthis 
12:rpushg 1 length[1]=String
14:pushc 0 
16:xpushg 1 String[1]=18
xpushg:
Object: String:1017 lsc: 0
VFields: 18 105 110 116 101 103 101 114 65 114 114 97 121 83 116 97 114 116 49 0 
Rfields: (0)LIB:1004 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
VStack: 
RStack: 
VdtTable: 0 0 0 0 
lscStack: 
--------------

18:storeg 1 length[1]=18
20:rtnEventQ 0 
22:setThisStack 
thisObj = length[%for%to%%do%#S#101,print][]  thisStack = print[(0)List,(0)List,BETAworld][1]
23:pushthis 
24:pushg 1 length[1]=18

26:rtn D length:1020:descInx:91  to: %for%to%%do%#S#101:1019:descInx:101 
thisObj = %for%to%%do%#S#101[print,print][]  thisStack = print[(0)List,(0)List,BETAworld][1,18]
27:toSuper 63 63 glsc: 1
1:pushthis 
2:storeg 2 %for%to%%do%#S#101[2]=18
4:pushthis 
5:storeg 1 %for%to%%do%#S#101[1]=1
7:rstore 1 BETAworld->%for%to%%do%#S#101[1]
9:allocEventQ 0 
11:mvStack 
thisObj = %for%to%%do%#S#101[print,print][]  thisStack = %for%to%%do%#S#101[print,print][]
12:rtnEventQ 1 
14:doEventQ 
15:mvStack 
thisObj = %for%to%%do%#S#101[print,print][]  thisStack = %for%to%%do%#S#101[print,print][]
16:pushthis 
17:pushthis 
18:pushg 1 %for%to%%do%#S#101[1]=1
20:storeg 3 %for%to%%do%#S#101[3]=1
22:pushthis 

23:invoke 64 0 1 do:1021:descInx:64 
thisObj = do[%for%to%%do%#S#101,%for%to%%do%#S#101][]  thisStack = %for%to%%do%#S#101[print,print,%for%to%%do%#S#101][]
1:rstore 1 %for%to%%do%#S#101->do[1]
3:allocEventQ 1 
5:mvStack 
thisObj = do[%for%to%%do%#S#101,%for%to%%do%#S#101][]  thisStack = do[%for%to%%do%#S#101,%for%to%%do%#S#101][]
6:pushthis 

7:invoke 65 2 1 loop:1022:descInx:65 
thisObj = loop[do,do][]  thisStack = do[%for%to%%do%#S#101,%for%to%%do%#S#101,do][]
1:rstore 1 do->loop[1]
3:allocEventQ 0 
5:mvStack 
thisObj = loop[do,do][]  thisStack = loop[do,do][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = loop[do,do][]  thisStack = loop[do,do][]
10:pushthis 
11:rpushg 1 loop[1]=do
13:rpushg 1 do[1]=%for%to%%do%#S#101
15:pushg 3 %for%to%%do%#S#101[3]=1
17:pushthis 
18:rpushg 1 loop[1]=do
20:rpushg 1 do[1]=%for%to%%do%#S#101
22:pushg 2 %for%to%%do%#S#101[2]=18
24:<= 
25:jmpFalse (1)36 
28:pushthis 

29:invoke 525 0 1 #S#525:1023:descInx:525 
thisObj = #S#525[loop,loop][]  thisStack = loop[do,do,loop][]
1:rstore 1 loop->#S#525[1]
3:allocEventQ 0 
5:mvStack 
thisObj = #S#525[loop,loop][]  thisStack = #S#525[loop,loop][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = #S#525[loop,loop][]  thisStack = #S#525[loop,loop][]
10:pushthis 
11:rpushg 1 #S#525[1]=loop
13:rpushg 1 loop[1]=do
15:rpushg 1 do[1]=%for%to%%do%#S#101
thisObj = #S#525[loop,loop,%for%to%%do%#S#101][]  thisStack = #S#525[loop,loop,%for%to%%do%#S#101][]

17:sendv  1 body#SB#539:1024:descInx:539 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = #S#525[loop,loop,%for%to%%do%#S#101][]
1:rstore 2 %for%to%%do%#S#101->body#SB#539[2]
3:allocEventQ 0 
5:mvStack 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = body#SB#539[#S#525,#S#525][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = body#SB#539[#S#525,#S#525][]
10:pushthis 
11:rpushg 2 body#SB#539[2]=%for%to%%do%#S#101
13:rpushg 2 %for%to%%do%#S#101[2]=print
15:rpushg 1 print[1]=String
17:pushthis 
18:rpushg 2 body#SB#539[2]=%for%to%%do%#S#101
20:pushg 3 %for%to%%do%#S#101[3]=1
22:xpushg 1 String[2]=105
xpushg:
Object: String:1017 lsc: 0
VFields: 18 105 110 116 101 103 101 114 65 114 114 97 121 83 116 97 114 116 49 0 
Rfields: (0)LIB:1004 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
VStack: 
RStack: 
VdtTable: 0 0 0 0 
lscStack: 
--------------

24:%prim 2 105 i
26:rtnEventQ 0 
28:setThisStack 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = #S#525[loop,loop][]
29:pushthis 

30:rtn D body#SB#539:1024:descInx:539  to: #S#525:1023:descInx:525 
thisObj = #S#525[loop,loop,body#SB#539][]  thisStack = #S#525[loop,loop,body#SB#539][]
19:rpop 
20:pushthis 
21:rpushg 1 #S#525[1]=loop
23:rpushg 1 loop[1]=do
25:rpushg 1 do[1]=%for%to%%do%#S#101
27:pushthis 
28:rpushg 1 #S#525[1]=loop
30:rpushg 1 loop[1]=do
32:rpushg 1 do[1]=%for%to%%do%#S#101
34:pushg 3 %for%to%%do%#S#101[3]=1
36:pushc 1 
38:+ 1 1
39:storeg 3 %for%to%%do%#S#101[3]=2
41:break 1 81 
10:pushthis 
11:rpushg 1 loop[1]=do
13:rpushg 1 do[1]=%for%to%%do%#S#101
15:pushg 3 %for%to%%do%#S#101[3]=2
17:pushthis 
18:rpushg 1 loop[1]=do
20:rpushg 1 do[1]=%for%to%%do%#S#101
22:pushg 2 %for%to%%do%#S#101[2]=18
24:<= 
25:jmpFalse (1)36 
28:pushthis 

29:invoke 525 0 1 #S#525:1025:descInx:525 
thisObj = #S#525[loop,loop][]  thisStack = loop[do,do,loop][]
1:rstore 1 loop->#S#525[1]
3:allocEventQ 0 
5:mvStack 
thisObj = #S#525[loop,loop][]  thisStack = #S#525[loop,loop][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = #S#525[loop,loop][]  thisStack = #S#525[loop,loop][]
10:pushthis 
11:rpushg 1 #S#525[1]=loop
13:rpushg 1 loop[1]=do
15:rpushg 1 do[1]=%for%to%%do%#S#101
thisObj = #S#525[loop,loop,%for%to%%do%#S#101][]  thisStack = #S#525[loop,loop,%for%to%%do%#S#101][]

17:sendv  1 body#SB#539:1026:descInx:539 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = #S#525[loop,loop,%for%to%%do%#S#101][]
1:rstore 2 %for%to%%do%#S#101->body#SB#539[2]
3:allocEventQ 0 
5:mvStack 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = body#SB#539[#S#525,#S#525][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = body#SB#539[#S#525,#S#525][]
10:pushthis 
11:rpushg 2 body#SB#539[2]=%for%to%%do%#S#101
13:rpushg 2 %for%to%%do%#S#101[2]=print
15:rpushg 1 print[1]=String
17:pushthis 
18:rpushg 2 body#SB#539[2]=%for%to%%do%#S#101
20:pushg 3 %for%to%%do%#S#101[3]=2
22:xpushg 1 String[3]=110
xpushg:
Object: String:1017 lsc: 0
VFields: 18 105 110 116 101 103 101 114 65 114 114 97 121 83 116 97 114 116 49 0 
Rfields: (0)LIB:1004 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
VStack: 
RStack: 
VdtTable: 0 0 0 0 
lscStack: 
--------------

24:%prim 2 110 n
26:rtnEventQ 0 
28:setThisStack 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = #S#525[loop,loop][]
29:pushthis 

30:rtn D body#SB#539:1026:descInx:539  to: #S#525:1025:descInx:525 
thisObj = #S#525[loop,loop,body#SB#539][]  thisStack = #S#525[loop,loop,body#SB#539][]
19:rpop 
20:pushthis 
21:rpushg 1 #S#525[1]=loop
23:rpushg 1 loop[1]=do
25:rpushg 1 do[1]=%for%to%%do%#S#101
27:pushthis 
28:rpushg 1 #S#525[1]=loop
30:rpushg 1 loop[1]=do
32:rpushg 1 do[1]=%for%to%%do%#S#101
34:pushg 3 %for%to%%do%#S#101[3]=2
36:pushc 1 
38:+ 2 1
39:storeg 3 %for%to%%do%#S#101[3]=3
41:break 1 81 
10:pushthis 
11:rpushg 1 loop[1]=do
13:rpushg 1 do[1]=%for%to%%do%#S#101
15:pushg 3 %for%to%%do%#S#101[3]=3
17:pushthis 
18:rpushg 1 loop[1]=do
20:rpushg 1 do[1]=%for%to%%do%#S#101
22:pushg 2 %for%to%%do%#S#101[2]=18
24:<= 
25:jmpFalse (1)36 
28:pushthis 

29:invoke 525 0 1 #S#525:1027:descInx:525 
thisObj = #S#525[loop,loop][]  thisStack = loop[do,do,loop][]
1:rstore 1 loop->#S#525[1]
3:allocEventQ 0 
5:mvStack 
thisObj = #S#525[loop,loop][]  thisStack = #S#525[loop,loop][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = #S#525[loop,loop][]  thisStack = #S#525[loop,loop][]
10:pushthis 
11:rpushg 1 #S#525[1]=loop
13:rpushg 1 loop[1]=do
15:rpushg 1 do[1]=%for%to%%do%#S#101
thisObj = #S#525[loop,loop,%for%to%%do%#S#101][]  thisStack = #S#525[loop,loop,%for%to%%do%#S#101][]

17:sendv  1 body#SB#539:1028:descInx:539 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = #S#525[loop,loop,%for%to%%do%#S#101][]
1:rstore 2 %for%to%%do%#S#101->body#SB#539[2]
3:allocEventQ 0 
5:mvStack 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = body#SB#539[#S#525,#S#525][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = body#SB#539[#S#525,#S#525][]
10:pushthis 
11:rpushg 2 body#SB#539[2]=%for%to%%do%#S#101
13:rpushg 2 %for%to%%do%#S#101[2]=print
15:rpushg 1 print[1]=String
17:pushthis 
18:rpushg 2 body#SB#539[2]=%for%to%%do%#S#101
20:pushg 3 %for%to%%do%#S#101[3]=3
22:xpushg 1 String[4]=116
xpushg:
Object: String:1017 lsc: 0
VFields: 18 105 110 116 101 103 101 114 65 114 114 97 121 83 116 97 114 116 49 0 
Rfields: (0)LIB:1004 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
VStack: 
RStack: 
VdtTable: 0 0 0 0 
lscStack: 
--------------

24:%prim 2 116 t
26:rtnEventQ 0 
28:setThisStack 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = #S#525[loop,loop][]
29:pushthis 

30:rtn D body#SB#539:1028:descInx:539  to: #S#525:1027:descInx:525 
thisObj = #S#525[loop,loop,body#SB#539][]  thisStack = #S#525[loop,loop,body#SB#539][]
19:rpop 
20:pushthis 
21:rpushg 1 #S#525[1]=loop
23:rpushg 1 loop[1]=do
25:rpushg 1 do[1]=%for%to%%do%#S#101
27:pushthis 
28:rpushg 1 #S#525[1]=loop
30:rpushg 1 loop[1]=do
32:rpushg 1 do[1]=%for%to%%do%#S#101
34:pushg 3 %for%to%%do%#S#101[3]=3
36:pushc 1 
38:+ 3 1
39:storeg 3 %for%to%%do%#S#101[3]=4
41:break 1 81 
10:pushthis 
11:rpushg 1 loop[1]=do
13:rpushg 1 do[1]=%for%to%%do%#S#101
15:pushg 3 %for%to%%do%#S#101[3]=4
17:pushthis 
18:rpushg 1 loop[1]=do
20:rpushg 1 do[1]=%for%to%%do%#S#101
22:pushg 2 %for%to%%do%#S#101[2]=18
24:<= 
25:jmpFalse (1)36 
28:pushthis 

29:invoke 525 0 1 #S#525:1029:descInx:525 
thisObj = #S#525[loop,loop][]  thisStack = loop[do,do,loop][]
1:rstore 1 loop->#S#525[1]
3:allocEventQ 0 
5:mvStack 
thisObj = #S#525[loop,loop][]  thisStack = #S#525[loop,loop][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = #S#525[loop,loop][]  thisStack = #S#525[loop,loop][]
10:pushthis 
11:rpushg 1 #S#525[1]=loop
13:rpushg 1 loop[1]=do
15:rpushg 1 do[1]=%for%to%%do%#S#101
thisObj = #S#525[loop,loop,%for%to%%do%#S#101][]  thisStack = #S#525[loop,loop,%for%to%%do%#S#101][]

17:sendv  1 body#SB#539:1030:descInx:539 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = #S#525[loop,loop,%for%to%%do%#S#101][]
1:rstore 2 %for%to%%do%#S#101->body#SB#539[2]
3:allocEventQ 0 
5:mvStack 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = body#SB#539[#S#525,#S#525][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = body#SB#539[#S#525,#S#525][]
10:pushthis 
11:rpushg 2 body#SB#539[2]=%for%to%%do%#S#101
13:rpushg 2 %for%to%%do%#S#101[2]=print
15:rpushg 1 print[1]=String
17:pushthis 
18:rpushg 2 body#SB#539[2]=%for%to%%do%#S#101
20:pushg 3 %for%to%%do%#S#101[3]=4
22:xpushg 1 String[5]=101
xpushg:
Object: String:1017 lsc: 0
VFields: 18 105 110 116 101 103 101 114 65 114 114 97 121 83 116 97 114 116 49 0 
Rfields: (0)LIB:1004 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
VStack: 
RStack: 
VdtTable: 0 0 0 0 
lscStack: 
--------------

24:%prim 2 101 e
26:rtnEventQ 0 
28:setThisStack 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = #S#525[loop,loop][]
29:pushthis 

30:rtn D body#SB#539:1030:descInx:539  to: #S#525:1029:descInx:525 
thisObj = #S#525[loop,loop,body#SB#539][]  thisStack = #S#525[loop,loop,body#SB#539][]
19:rpop 
20:pushthis 
21:rpushg 1 #S#525[1]=loop
23:rpushg 1 loop[1]=do
25:rpushg 1 do[1]=%for%to%%do%#S#101
27:pushthis 
28:rpushg 1 #S#525[1]=loop
30:rpushg 1 loop[1]=do
32:rpushg 1 do[1]=%for%to%%do%#S#101
34:pushg 3 %for%to%%do%#S#101[3]=4
36:pushc 1 
38:+ 4 1
39:storeg 3 %for%to%%do%#S#101[3]=5
41:break 1 81 
10:pushthis 
11:rpushg 1 loop[1]=do
13:rpushg 1 do[1]=%for%to%%do%#S#101
15:pushg 3 %for%to%%do%#S#101[3]=5
17:pushthis 
18:rpushg 1 loop[1]=do
20:rpushg 1 do[1]=%for%to%%do%#S#101
22:pushg 2 %for%to%%do%#S#101[2]=18
24:<= 
25:jmpFalse (1)36 
28:pushthis 

29:invoke 525 0 1 #S#525:1031:descInx:525 
thisObj = #S#525[loop,loop][]  thisStack = loop[do,do,loop][]
1:rstore 1 loop->#S#525[1]
3:allocEventQ 0 
5:mvStack 
thisObj = #S#525[loop,loop][]  thisStack = #S#525[loop,loop][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = #S#525[loop,loop][]  thisStack = #S#525[loop,loop][]
10:pushthis 
11:rpushg 1 #S#525[1]=loop
13:rpushg 1 loop[1]=do
15:rpushg 1 do[1]=%for%to%%do%#S#101
thisObj = #S#525[loop,loop,%for%to%%do%#S#101][]  thisStack = #S#525[loop,loop,%for%to%%do%#S#101][]

17:sendv  1 body#SB#539:1032:descInx:539 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = #S#525[loop,loop,%for%to%%do%#S#101][]
1:rstore 2 %for%to%%do%#S#101->body#SB#539[2]
3:allocEventQ 0 
5:mvStack 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = body#SB#539[#S#525,#S#525][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = body#SB#539[#S#525,#S#525][]
10:pushthis 
11:rpushg 2 body#SB#539[2]=%for%to%%do%#S#101
13:rpushg 2 %for%to%%do%#S#101[2]=print
15:rpushg 1 print[1]=String
17:pushthis 
18:rpushg 2 body#SB#539[2]=%for%to%%do%#S#101
20:pushg 3 %for%to%%do%#S#101[3]=5
22:xpushg 1 String[6]=103
xpushg:
Object: String:1017 lsc: 0
VFields: 18 105 110 116 101 103 101 114 65 114 114 97 121 83 116 97 114 116 49 0 
Rfields: (0)LIB:1004 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
VStack: 
RStack: 
VdtTable: 0 0 0 0 
lscStack: 
--------------

24:%prim 2 103 g
26:rtnEventQ 0 
28:setThisStack 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = #S#525[loop,loop][]
29:pushthis 

30:rtn D body#SB#539:1032:descInx:539  to: #S#525:1031:descInx:525 
thisObj = #S#525[loop,loop,body#SB#539][]  thisStack = #S#525[loop,loop,body#SB#539][]
19:rpop 
20:pushthis 
21:rpushg 1 #S#525[1]=loop
23:rpushg 1 loop[1]=do
25:rpushg 1 do[1]=%for%to%%do%#S#101
27:pushthis 
28:rpushg 1 #S#525[1]=loop
30:rpushg 1 loop[1]=do
32:rpushg 1 do[1]=%for%to%%do%#S#101
34:pushg 3 %for%to%%do%#S#101[3]=5
36:pushc 1 
38:+ 5 1
39:storeg 3 %for%to%%do%#S#101[3]=6
41:break 1 81 
10:pushthis 
11:rpushg 1 loop[1]=do
13:rpushg 1 do[1]=%for%to%%do%#S#101
15:pushg 3 %for%to%%do%#S#101[3]=6
17:pushthis 
18:rpushg 1 loop[1]=do
20:rpushg 1 do[1]=%for%to%%do%#S#101
22:pushg 2 %for%to%%do%#S#101[2]=18
24:<= 
25:jmpFalse (1)36 
28:pushthis 

29:invoke 525 0 1 #S#525:1033:descInx:525 
thisObj = #S#525[loop,loop][]  thisStack = loop[do,do,loop][]
1:rstore 1 loop->#S#525[1]
3:allocEventQ 0 
5:mvStack 
thisObj = #S#525[loop,loop][]  thisStack = #S#525[loop,loop][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = #S#525[loop,loop][]  thisStack = #S#525[loop,loop][]
10:pushthis 
11:rpushg 1 #S#525[1]=loop
13:rpushg 1 loop[1]=do
15:rpushg 1 do[1]=%for%to%%do%#S#101
thisObj = #S#525[loop,loop,%for%to%%do%#S#101][]  thisStack = #S#525[loop,loop,%for%to%%do%#S#101][]

17:sendv  1 body#SB#539:1034:descInx:539 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = #S#525[loop,loop,%for%to%%do%#S#101][]
1:rstore 2 %for%to%%do%#S#101->body#SB#539[2]
3:allocEventQ 0 
5:mvStack 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = body#SB#539[#S#525,#S#525][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = body#SB#539[#S#525,#S#525][]
10:pushthis 
11:rpushg 2 body#SB#539[2]=%for%to%%do%#S#101
13:rpushg 2 %for%to%%do%#S#101[2]=print
15:rpushg 1 print[1]=String
17:pushthis 
18:rpushg 2 body#SB#539[2]=%for%to%%do%#S#101
20:pushg 3 %for%to%%do%#S#101[3]=6
22:xpushg 1 String[7]=101
xpushg:
Object: String:1017 lsc: 0
VFields: 18 105 110 116 101 103 101 114 65 114 114 97 121 83 116 97 114 116 49 0 
Rfields: (0)LIB:1004 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
VStack: 
RStack: 
VdtTable: 0 0 0 0 
lscStack: 
--------------

24:%prim 2 101 e
26:rtnEventQ 0 
28:setThisStack 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = #S#525[loop,loop][]
29:pushthis 

30:rtn D body#SB#539:1034:descInx:539  to: #S#525:1033:descInx:525 
thisObj = #S#525[loop,loop,body#SB#539][]  thisStack = #S#525[loop,loop,body#SB#539][]
19:rpop 
20:pushthis 
21:rpushg 1 #S#525[1]=loop
23:rpushg 1 loop[1]=do
25:rpushg 1 do[1]=%for%to%%do%#S#101
27:pushthis 
28:rpushg 1 #S#525[1]=loop
30:rpushg 1 loop[1]=do
32:rpushg 1 do[1]=%for%to%%do%#S#101
34:pushg 3 %for%to%%do%#S#101[3]=6
36:pushc 1 
38:+ 6 1
39:storeg 3 %for%to%%do%#S#101[3]=7
41:break 1 81 
10:pushthis 
11:rpushg 1 loop[1]=do
13:rpushg 1 do[1]=%for%to%%do%#S#101
15:pushg 3 %for%to%%do%#S#101[3]=7
17:pushthis 
18:rpushg 1 loop[1]=do
20:rpushg 1 do[1]=%for%to%%do%#S#101
22:pushg 2 %for%to%%do%#S#101[2]=18
24:<= 
25:jmpFalse (1)36 
28:pushthis 

29:invoke 525 0 1 #S#525:1035:descInx:525 
thisObj = #S#525[loop,loop][]  thisStack = loop[do,do,loop][]
1:rstore 1 loop->#S#525[1]
3:allocEventQ 0 
5:mvStack 
thisObj = #S#525[loop,loop][]  thisStack = #S#525[loop,loop][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = #S#525[loop,loop][]  thisStack = #S#525[loop,loop][]
10:pushthis 
11:rpushg 1 #S#525[1]=loop
13:rpushg 1 loop[1]=do
15:rpushg 1 do[1]=%for%to%%do%#S#101
thisObj = #S#525[loop,loop,%for%to%%do%#S#101][]  thisStack = #S#525[loop,loop,%for%to%%do%#S#101][]

17:sendv  1 body#SB#539:1036:descInx:539 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = #S#525[loop,loop,%for%to%%do%#S#101][]
1:rstore 2 %for%to%%do%#S#101->body#SB#539[2]
3:allocEventQ 0 
5:mvStack 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = body#SB#539[#S#525,#S#525][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = body#SB#539[#S#525,#S#525][]
10:pushthis 
11:rpushg 2 body#SB#539[2]=%for%to%%do%#S#101
13:rpushg 2 %for%to%%do%#S#101[2]=print
15:rpushg 1 print[1]=String
17:pushthis 
18:rpushg 2 body#SB#539[2]=%for%to%%do%#S#101
20:pushg 3 %for%to%%do%#S#101[3]=7
22:xpushg 1 String[8]=114
xpushg:
Object: String:1017 lsc: 0
VFields: 18 105 110 116 101 103 101 114 65 114 114 97 121 83 116 97 114 116 49 0 
Rfields: (0)LIB:1004 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
VStack: 
RStack: 
VdtTable: 0 0 0 0 
lscStack: 
--------------

24:%prim 2 114 r
26:rtnEventQ 0 
28:setThisStack 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = #S#525[loop,loop][]
29:pushthis 

30:rtn D body#SB#539:1036:descInx:539  to: #S#525:1035:descInx:525 
thisObj = #S#525[loop,loop,body#SB#539][]  thisStack = #S#525[loop,loop,body#SB#539][]
19:rpop 
20:pushthis 
21:rpushg 1 #S#525[1]=loop
23:rpushg 1 loop[1]=do
25:rpushg 1 do[1]=%for%to%%do%#S#101
27:pushthis 
28:rpushg 1 #S#525[1]=loop
30:rpushg 1 loop[1]=do
32:rpushg 1 do[1]=%for%to%%do%#S#101
34:pushg 3 %for%to%%do%#S#101[3]=7
36:pushc 1 
38:+ 7 1
39:storeg 3 %for%to%%do%#S#101[3]=8
41:break 1 81 
10:pushthis 
11:rpushg 1 loop[1]=do
13:rpushg 1 do[1]=%for%to%%do%#S#101
15:pushg 3 %for%to%%do%#S#101[3]=8
17:pushthis 
18:rpushg 1 loop[1]=do
20:rpushg 1 do[1]=%for%to%%do%#S#101
22:pushg 2 %for%to%%do%#S#101[2]=18
24:<= 
25:jmpFalse (1)36 
28:pushthis 

29:invoke 525 0 1 #S#525:1037:descInx:525 
thisObj = #S#525[loop,loop][]  thisStack = loop[do,do,loop][]
1:rstore 1 loop->#S#525[1]
3:allocEventQ 0 
5:mvStack 
thisObj = #S#525[loop,loop][]  thisStack = #S#525[loop,loop][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = #S#525[loop,loop][]  thisStack = #S#525[loop,loop][]
10:pushthis 
11:rpushg 1 #S#525[1]=loop
13:rpushg 1 loop[1]=do
15:rpushg 1 do[1]=%for%to%%do%#S#101
thisObj = #S#525[loop,loop,%for%to%%do%#S#101][]  thisStack = #S#525[loop,loop,%for%to%%do%#S#101][]

17:sendv  1 body#SB#539:1038:descInx:539 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = #S#525[loop,loop,%for%to%%do%#S#101][]
1:rstore 2 %for%to%%do%#S#101->body#SB#539[2]
3:allocEventQ 0 
5:mvStack 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = body#SB#539[#S#525,#S#525][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = body#SB#539[#S#525,#S#525][]
10:pushthis 
11:rpushg 2 body#SB#539[2]=%for%to%%do%#S#101
13:rpushg 2 %for%to%%do%#S#101[2]=print
15:rpushg 1 print[1]=String
17:pushthis 
18:rpushg 2 body#SB#539[2]=%for%to%%do%#S#101
20:pushg 3 %for%to%%do%#S#101[3]=8
22:xpushg 1 String[9]=65
xpushg:
Object: String:1017 lsc: 0
VFields: 18 105 110 116 101 103 101 114 65 114 114 97 121 83 116 97 114 116 49 0 
Rfields: (0)LIB:1004 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
VStack: 
RStack: 
VdtTable: 0 0 0 0 
lscStack: 
--------------

24:%prim 2 65 A
26:rtnEventQ 0 
28:setThisStack 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = #S#525[loop,loop][]
29:pushthis 

30:rtn D body#SB#539:1038:descInx:539  to: #S#525:1037:descInx:525 
thisObj = #S#525[loop,loop,body#SB#539][]  thisStack = #S#525[loop,loop,body#SB#539][]
19:rpop 
20:pushthis 
21:rpushg 1 #S#525[1]=loop
23:rpushg 1 loop[1]=do
25:rpushg 1 do[1]=%for%to%%do%#S#101
27:pushthis 
28:rpushg 1 #S#525[1]=loop
30:rpushg 1 loop[1]=do
32:rpushg 1 do[1]=%for%to%%do%#S#101
34:pushg 3 %for%to%%do%#S#101[3]=8
36:pushc 1 
38:+ 8 1
39:storeg 3 %for%to%%do%#S#101[3]=9
41:break 1 81 
10:pushthis 
11:rpushg 1 loop[1]=do
13:rpushg 1 do[1]=%for%to%%do%#S#101
15:pushg 3 %for%to%%do%#S#101[3]=9
17:pushthis 
18:rpushg 1 loop[1]=do
20:rpushg 1 do[1]=%for%to%%do%#S#101
22:pushg 2 %for%to%%do%#S#101[2]=18
24:<= 
25:jmpFalse (1)36 
28:pushthis 

29:invoke 525 0 1 #S#525:1039:descInx:525 
thisObj = #S#525[loop,loop][]  thisStack = loop[do,do,loop][]
1:rstore 1 loop->#S#525[1]
3:allocEventQ 0 
5:mvStack 
thisObj = #S#525[loop,loop][]  thisStack = #S#525[loop,loop][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = #S#525[loop,loop][]  thisStack = #S#525[loop,loop][]
10:pushthis 
11:rpushg 1 #S#525[1]=loop
13:rpushg 1 loop[1]=do
15:rpushg 1 do[1]=%for%to%%do%#S#101
thisObj = #S#525[loop,loop,%for%to%%do%#S#101][]  thisStack = #S#525[loop,loop,%for%to%%do%#S#101][]

17:sendv  1 body#SB#539:1040:descInx:539 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = #S#525[loop,loop,%for%to%%do%#S#101][]
1:rstore 2 %for%to%%do%#S#101->body#SB#539[2]
3:allocEventQ 0 
5:mvStack 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = body#SB#539[#S#525,#S#525][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = body#SB#539[#S#525,#S#525][]
10:pushthis 
11:rpushg 2 body#SB#539[2]=%for%to%%do%#S#101
13:rpushg 2 %for%to%%do%#S#101[2]=print
15:rpushg 1 print[1]=String
17:pushthis 
18:rpushg 2 body#SB#539[2]=%for%to%%do%#S#101
20:pushg 3 %for%to%%do%#S#101[3]=9
22:xpushg 1 String[10]=114
xpushg:
Object: String:1017 lsc: 0
VFields: 18 105 110 116 101 103 101 114 65 114 114 97 121 83 116 97 114 116 49 0 
Rfields: (0)LIB:1004 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
VStack: 
RStack: 
VdtTable: 0 0 0 0 
lscStack: 
--------------

24:%prim 2 114 r
26:rtnEventQ 0 
28:setThisStack 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = #S#525[loop,loop][]
29:pushthis 

30:rtn D body#SB#539:1040:descInx:539  to: #S#525:1039:descInx:525 
thisObj = #S#525[loop,loop,body#SB#539][]  thisStack = #S#525[loop,loop,body#SB#539][]
19:rpop 
20:pushthis 
21:rpushg 1 #S#525[1]=loop
23:rpushg 1 loop[1]=do
25:rpushg 1 do[1]=%for%to%%do%#S#101
27:pushthis 
28:rpushg 1 #S#525[1]=loop
30:rpushg 1 loop[1]=do
32:rpushg 1 do[1]=%for%to%%do%#S#101
34:pushg 3 %for%to%%do%#S#101[3]=9
36:pushc 1 
38:+ 9 1
39:storeg 3 %for%to%%do%#S#101[3]=10
41:break 1 81 
10:pushthis 
11:rpushg 1 loop[1]=do
13:rpushg 1 do[1]=%for%to%%do%#S#101
15:pushg 3 %for%to%%do%#S#101[3]=10
17:pushthis 
18:rpushg 1 loop[1]=do
20:rpushg 1 do[1]=%for%to%%do%#S#101
22:pushg 2 %for%to%%do%#S#101[2]=18
24:<= 
25:jmpFalse (1)36 
28:pushthis 

29:invoke 525 0 1 #S#525:1041:descInx:525 
thisObj = #S#525[loop,loop][]  thisStack = loop[do,do,loop][]
1:rstore 1 loop->#S#525[1]
3:allocEventQ 0 
5:mvStack 
thisObj = #S#525[loop,loop][]  thisStack = #S#525[loop,loop][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = #S#525[loop,loop][]  thisStack = #S#525[loop,loop][]
10:pushthis 
11:rpushg 1 #S#525[1]=loop
13:rpushg 1 loop[1]=do
15:rpushg 1 do[1]=%for%to%%do%#S#101
thisObj = #S#525[loop,loop,%for%to%%do%#S#101][]  thisStack = #S#525[loop,loop,%for%to%%do%#S#101][]

17:sendv  1 body#SB#539:1042:descInx:539 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = #S#525[loop,loop,%for%to%%do%#S#101][]
1:rstore 2 %for%to%%do%#S#101->body#SB#539[2]
3:allocEventQ 0 
5:mvStack 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = body#SB#539[#S#525,#S#525][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = body#SB#539[#S#525,#S#525][]
10:pushthis 
11:rpushg 2 body#SB#539[2]=%for%to%%do%#S#101
13:rpushg 2 %for%to%%do%#S#101[2]=print
15:rpushg 1 print[1]=String
17:pushthis 
18:rpushg 2 body#SB#539[2]=%for%to%%do%#S#101
20:pushg 3 %for%to%%do%#S#101[3]=10
22:xpushg 1 String[11]=114
xpushg:
Object: String:1017 lsc: 0
VFields: 18 105 110 116 101 103 101 114 65 114 114 97 121 83 116 97 114 116 49 0 
Rfields: (0)LIB:1004 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
VStack: 
RStack: 
VdtTable: 0 0 0 0 
lscStack: 
--------------

24:%prim 2 114 r
26:rtnEventQ 0 
28:setThisStack 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = #S#525[loop,loop][]
29:pushthis 

30:rtn D body#SB#539:1042:descInx:539  to: #S#525:1041:descInx:525 
thisObj = #S#525[loop,loop,body#SB#539][]  thisStack = #S#525[loop,loop,body#SB#539][]
19:rpop 
20:pushthis 
21:rpushg 1 #S#525[1]=loop
23:rpushg 1 loop[1]=do
25:rpushg 1 do[1]=%for%to%%do%#S#101
27:pushthis 
28:rpushg 1 #S#525[1]=loop
30:rpushg 1 loop[1]=do
32:rpushg 1 do[1]=%for%to%%do%#S#101
34:pushg 3 %for%to%%do%#S#101[3]=10
36:pushc 1 
38:+ 10 1
39:storeg 3 %for%to%%do%#S#101[3]=11
41:break 1 81 
10:pushthis 
11:rpushg 1 loop[1]=do
13:rpushg 1 do[1]=%for%to%%do%#S#101
15:pushg 3 %for%to%%do%#S#101[3]=11
17:pushthis 
18:rpushg 1 loop[1]=do
20:rpushg 1 do[1]=%for%to%%do%#S#101
22:pushg 2 %for%to%%do%#S#101[2]=18
24:<= 
25:jmpFalse (1)36 
28:pushthis 

29:invoke 525 0 1 #S#525:1043:descInx:525 
thisObj = #S#525[loop,loop][]  thisStack = loop[do,do,loop][]
1:rstore 1 loop->#S#525[1]
3:allocEventQ 0 
5:mvStack 
thisObj = #S#525[loop,loop][]  thisStack = #S#525[loop,loop][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = #S#525[loop,loop][]  thisStack = #S#525[loop,loop][]
10:pushthis 
11:rpushg 1 #S#525[1]=loop
13:rpushg 1 loop[1]=do
15:rpushg 1 do[1]=%for%to%%do%#S#101
thisObj = #S#525[loop,loop,%for%to%%do%#S#101][]  thisStack = #S#525[loop,loop,%for%to%%do%#S#101][]

17:sendv  1 body#SB#539:1044:descInx:539 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = #S#525[loop,loop,%for%to%%do%#S#101][]
1:rstore 2 %for%to%%do%#S#101->body#SB#539[2]
3:allocEventQ 0 
5:mvStack 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = body#SB#539[#S#525,#S#525][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = body#SB#539[#S#525,#S#525][]
10:pushthis 
11:rpushg 2 body#SB#539[2]=%for%to%%do%#S#101
13:rpushg 2 %for%to%%do%#S#101[2]=print
15:rpushg 1 print[1]=String
17:pushthis 
18:rpushg 2 body#SB#539[2]=%for%to%%do%#S#101
20:pushg 3 %for%to%%do%#S#101[3]=11
22:xpushg 1 String[12]=97
xpushg:
Object: String:1017 lsc: 0
VFields: 18 105 110 116 101 103 101 114 65 114 114 97 121 83 116 97 114 116 49 0 
Rfields: (0)LIB:1004 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
VStack: 
RStack: 
VdtTable: 0 0 0 0 
lscStack: 
--------------

24:%prim 2 97 a
26:rtnEventQ 0 
28:setThisStack 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = #S#525[loop,loop][]
29:pushthis 

30:rtn D body#SB#539:1044:descInx:539  to: #S#525:1043:descInx:525 
thisObj = #S#525[loop,loop,body#SB#539][]  thisStack = #S#525[loop,loop,body#SB#539][]
19:rpop 
20:pushthis 
21:rpushg 1 #S#525[1]=loop
23:rpushg 1 loop[1]=do
25:rpushg 1 do[1]=%for%to%%do%#S#101
27:pushthis 
28:rpushg 1 #S#525[1]=loop
30:rpushg 1 loop[1]=do
32:rpushg 1 do[1]=%for%to%%do%#S#101
34:pushg 3 %for%to%%do%#S#101[3]=11
36:pushc 1 
38:+ 11 1
39:storeg 3 %for%to%%do%#S#101[3]=12
41:break 1 81 
10:pushthis 
11:rpushg 1 loop[1]=do
13:rpushg 1 do[1]=%for%to%%do%#S#101
15:pushg 3 %for%to%%do%#S#101[3]=12
17:pushthis 
18:rpushg 1 loop[1]=do
20:rpushg 1 do[1]=%for%to%%do%#S#101
22:pushg 2 %for%to%%do%#S#101[2]=18
24:<= 
25:jmpFalse (1)36 
28:pushthis 

29:invoke 525 0 1 #S#525:1045:descInx:525 
thisObj = #S#525[loop,loop][]  thisStack = loop[do,do,loop][]
1:rstore 1 loop->#S#525[1]
3:allocEventQ 0 
5:mvStack 
thisObj = #S#525[loop,loop][]  thisStack = #S#525[loop,loop][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = #S#525[loop,loop][]  thisStack = #S#525[loop,loop][]
10:pushthis 
11:rpushg 1 #S#525[1]=loop
13:rpushg 1 loop[1]=do
15:rpushg 1 do[1]=%for%to%%do%#S#101
thisObj = #S#525[loop,loop,%for%to%%do%#S#101][]  thisStack = #S#525[loop,loop,%for%to%%do%#S#101][]

17:sendv  1 body#SB#539:1046:descInx:539 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = #S#525[loop,loop,%for%to%%do%#S#101][]
1:rstore 2 %for%to%%do%#S#101->body#SB#539[2]
3:allocEventQ 0 
5:mvStack 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = body#SB#539[#S#525,#S#525][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = body#SB#539[#S#525,#S#525][]
10:pushthis 
11:rpushg 2 body#SB#539[2]=%for%to%%do%#S#101
13:rpushg 2 %for%to%%do%#S#101[2]=print
15:rpushg 1 print[1]=String
17:pushthis 
18:rpushg 2 body#SB#539[2]=%for%to%%do%#S#101
20:pushg 3 %for%to%%do%#S#101[3]=12
22:xpushg 1 String[13]=121
xpushg:
Object: String:1017 lsc: 0
VFields: 18 105 110 116 101 103 101 114 65 114 114 97 121 83 116 97 114 116 49 0 
Rfields: (0)LIB:1004 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
VStack: 
RStack: 
VdtTable: 0 0 0 0 
lscStack: 
--------------

24:%prim 2 121 y
26:rtnEventQ 0 
28:setThisStack 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = #S#525[loop,loop][]
29:pushthis 

30:rtn D body#SB#539:1046:descInx:539  to: #S#525:1045:descInx:525 
thisObj = #S#525[loop,loop,body#SB#539][]  thisStack = #S#525[loop,loop,body#SB#539][]
19:rpop 
20:pushthis 
21:rpushg 1 #S#525[1]=loop
23:rpushg 1 loop[1]=do
25:rpushg 1 do[1]=%for%to%%do%#S#101
27:pushthis 
28:rpushg 1 #S#525[1]=loop
30:rpushg 1 loop[1]=do
32:rpushg 1 do[1]=%for%to%%do%#S#101
34:pushg 3 %for%to%%do%#S#101[3]=12
36:pushc 1 
38:+ 12 1
39:storeg 3 %for%to%%do%#S#101[3]=13
41:break 1 81 
10:pushthis 
11:rpushg 1 loop[1]=do
13:rpushg 1 do[1]=%for%to%%do%#S#101
15:pushg 3 %for%to%%do%#S#101[3]=13
17:pushthis 
18:rpushg 1 loop[1]=do
20:rpushg 1 do[1]=%for%to%%do%#S#101
22:pushg 2 %for%to%%do%#S#101[2]=18
24:<= 
25:jmpFalse (1)36 
28:pushthis 

29:invoke 525 0 1 #S#525:1047:descInx:525 
thisObj = #S#525[loop,loop][]  thisStack = loop[do,do,loop][]
1:rstore 1 loop->#S#525[1]
3:allocEventQ 0 
5:mvStack 
thisObj = #S#525[loop,loop][]  thisStack = #S#525[loop,loop][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = #S#525[loop,loop][]  thisStack = #S#525[loop,loop][]
10:pushthis 
11:rpushg 1 #S#525[1]=loop
13:rpushg 1 loop[1]=do
15:rpushg 1 do[1]=%for%to%%do%#S#101
thisObj = #S#525[loop,loop,%for%to%%do%#S#101][]  thisStack = #S#525[loop,loop,%for%to%%do%#S#101][]

17:sendv  1 body#SB#539:1048:descInx:539 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = #S#525[loop,loop,%for%to%%do%#S#101][]
1:rstore 2 %for%to%%do%#S#101->body#SB#539[2]
3:allocEventQ 0 
5:mvStack 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = body#SB#539[#S#525,#S#525][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = body#SB#539[#S#525,#S#525][]
10:pushthis 
11:rpushg 2 body#SB#539[2]=%for%to%%do%#S#101
13:rpushg 2 %for%to%%do%#S#101[2]=print
15:rpushg 1 print[1]=String
17:pushthis 
18:rpushg 2 body#SB#539[2]=%for%to%%do%#S#101
20:pushg 3 %for%to%%do%#S#101[3]=13
22:xpushg 1 String[14]=83
xpushg:
Object: String:1017 lsc: 0
VFields: 18 105 110 116 101 103 101 114 65 114 114 97 121 83 116 97 114 116 49 0 
Rfields: (0)LIB:1004 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
VStack: 
RStack: 
VdtTable: 0 0 0 0 
lscStack: 
--------------

24:%prim 2 83 S
26:rtnEventQ 0 
28:setThisStack 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = #S#525[loop,loop][]
29:pushthis 

30:rtn D body#SB#539:1048:descInx:539  to: #S#525:1047:descInx:525 
thisObj = #S#525[loop,loop,body#SB#539][]  thisStack = #S#525[loop,loop,body#SB#539][]
19:rpop 
20:pushthis 
21:rpushg 1 #S#525[1]=loop
23:rpushg 1 loop[1]=do
25:rpushg 1 do[1]=%for%to%%do%#S#101
27:pushthis 
28:rpushg 1 #S#525[1]=loop
30:rpushg 1 loop[1]=do
32:rpushg 1 do[1]=%for%to%%do%#S#101
34:pushg 3 %for%to%%do%#S#101[3]=13
36:pushc 1 
38:+ 13 1
39:storeg 3 %for%to%%do%#S#101[3]=14
41:break 1 81 
10:pushthis 
11:rpushg 1 loop[1]=do
13:rpushg 1 do[1]=%for%to%%do%#S#101
15:pushg 3 %for%to%%do%#S#101[3]=14
17:pushthis 
18:rpushg 1 loop[1]=do
20:rpushg 1 do[1]=%for%to%%do%#S#101
22:pushg 2 %for%to%%do%#S#101[2]=18
24:<= 
25:jmpFalse (1)36 
28:pushthis 

29:invoke 525 0 1 #S#525:1049:descInx:525 
thisObj = #S#525[loop,loop][]  thisStack = loop[do,do,loop][]
1:rstore 1 loop->#S#525[1]
3:allocEventQ 0 
5:mvStack 
thisObj = #S#525[loop,loop][]  thisStack = #S#525[loop,loop][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = #S#525[loop,loop][]  thisStack = #S#525[loop,loop][]
10:pushthis 
11:rpushg 1 #S#525[1]=loop
13:rpushg 1 loop[1]=do
15:rpushg 1 do[1]=%for%to%%do%#S#101
thisObj = #S#525[loop,loop,%for%to%%do%#S#101][]  thisStack = #S#525[loop,loop,%for%to%%do%#S#101][]

17:sendv  1 body#SB#539:1050:descInx:539 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = #S#525[loop,loop,%for%to%%do%#S#101][]
1:rstore 2 %for%to%%do%#S#101->body#SB#539[2]
3:allocEventQ 0 
5:mvStack 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = body#SB#539[#S#525,#S#525][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = body#SB#539[#S#525,#S#525][]
10:pushthis 
11:rpushg 2 body#SB#539[2]=%for%to%%do%#S#101
13:rpushg 2 %for%to%%do%#S#101[2]=print
15:rpushg 1 print[1]=String
17:pushthis 
18:rpushg 2 body#SB#539[2]=%for%to%%do%#S#101
20:pushg 3 %for%to%%do%#S#101[3]=14
22:xpushg 1 String[15]=116
xpushg:
Object: String:1017 lsc: 0
VFields: 18 105 110 116 101 103 101 114 65 114 114 97 121 83 116 97 114 116 49 0 
Rfields: (0)LIB:1004 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
VStack: 
RStack: 
VdtTable: 0 0 0 0 
lscStack: 
--------------

24:%prim 2 116 t
26:rtnEventQ 0 
28:setThisStack 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = #S#525[loop,loop][]
29:pushthis 

30:rtn D body#SB#539:1050:descInx:539  to: #S#525:1049:descInx:525 
thisObj = #S#525[loop,loop,body#SB#539][]  thisStack = #S#525[loop,loop,body#SB#539][]
19:rpop 
20:pushthis 
21:rpushg 1 #S#525[1]=loop
23:rpushg 1 loop[1]=do
25:rpushg 1 do[1]=%for%to%%do%#S#101
27:pushthis 
28:rpushg 1 #S#525[1]=loop
30:rpushg 1 loop[1]=do
32:rpushg 1 do[1]=%for%to%%do%#S#101
34:pushg 3 %for%to%%do%#S#101[3]=14
36:pushc 1 
38:+ 14 1
39:storeg 3 %for%to%%do%#S#101[3]=15
41:break 1 81 
10:pushthis 
11:rpushg 1 loop[1]=do
13:rpushg 1 do[1]=%for%to%%do%#S#101
15:pushg 3 %for%to%%do%#S#101[3]=15
17:pushthis 
18:rpushg 1 loop[1]=do
20:rpushg 1 do[1]=%for%to%%do%#S#101
22:pushg 2 %for%to%%do%#S#101[2]=18
24:<= 
25:jmpFalse (1)36 
28:pushthis 

29:invoke 525 0 1 #S#525:1051:descInx:525 
thisObj = #S#525[loop,loop][]  thisStack = loop[do,do,loop][]
1:rstore 1 loop->#S#525[1]
3:allocEventQ 0 
5:mvStack 
thisObj = #S#525[loop,loop][]  thisStack = #S#525[loop,loop][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = #S#525[loop,loop][]  thisStack = #S#525[loop,loop][]
10:pushthis 
11:rpushg 1 #S#525[1]=loop
13:rpushg 1 loop[1]=do
15:rpushg 1 do[1]=%for%to%%do%#S#101
thisObj = #S#525[loop,loop,%for%to%%do%#S#101][]  thisStack = #S#525[loop,loop,%for%to%%do%#S#101][]

17:sendv  1 body#SB#539:1052:descInx:539 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = #S#525[loop,loop,%for%to%%do%#S#101][]
1:rstore 2 %for%to%%do%#S#101->body#SB#539[2]
3:allocEventQ 0 
5:mvStack 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = body#SB#539[#S#525,#S#525][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = body#SB#539[#S#525,#S#525][]
10:pushthis 
11:rpushg 2 body#SB#539[2]=%for%to%%do%#S#101
13:rpushg 2 %for%to%%do%#S#101[2]=print
15:rpushg 1 print[1]=String
17:pushthis 
18:rpushg 2 body#SB#539[2]=%for%to%%do%#S#101
20:pushg 3 %for%to%%do%#S#101[3]=15
22:xpushg 1 String[16]=97
xpushg:
Object: String:1017 lsc: 0
VFields: 18 105 110 116 101 103 101 114 65 114 114 97 121 83 116 97 114 116 49 0 
Rfields: (0)LIB:1004 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
VStack: 
RStack: 
VdtTable: 0 0 0 0 
lscStack: 
--------------

24:%prim 2 97 a
26:rtnEventQ 0 
28:setThisStack 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = #S#525[loop,loop][]
29:pushthis 

30:rtn D body#SB#539:1052:descInx:539  to: #S#525:1051:descInx:525 
thisObj = #S#525[loop,loop,body#SB#539][]  thisStack = #S#525[loop,loop,body#SB#539][]
19:rpop 
20:pushthis 
21:rpushg 1 #S#525[1]=loop
23:rpushg 1 loop[1]=do
25:rpushg 1 do[1]=%for%to%%do%#S#101
27:pushthis 
28:rpushg 1 #S#525[1]=loop
30:rpushg 1 loop[1]=do
32:rpushg 1 do[1]=%for%to%%do%#S#101
34:pushg 3 %for%to%%do%#S#101[3]=15
36:pushc 1 
38:+ 15 1
39:storeg 3 %for%to%%do%#S#101[3]=16
41:break 1 81 
10:pushthis 
11:rpushg 1 loop[1]=do
13:rpushg 1 do[1]=%for%to%%do%#S#101
15:pushg 3 %for%to%%do%#S#101[3]=16
17:pushthis 
18:rpushg 1 loop[1]=do
20:rpushg 1 do[1]=%for%to%%do%#S#101
22:pushg 2 %for%to%%do%#S#101[2]=18
24:<= 
25:jmpFalse (1)36 
28:pushthis 

29:invoke 525 0 1 #S#525:1053:descInx:525 
thisObj = #S#525[loop,loop][]  thisStack = loop[do,do,loop][]
1:rstore 1 loop->#S#525[1]
3:allocEventQ 0 
5:mvStack 
thisObj = #S#525[loop,loop][]  thisStack = #S#525[loop,loop][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = #S#525[loop,loop][]  thisStack = #S#525[loop,loop][]
10:pushthis 
11:rpushg 1 #S#525[1]=loop
13:rpushg 1 loop[1]=do
15:rpushg 1 do[1]=%for%to%%do%#S#101
thisObj = #S#525[loop,loop,%for%to%%do%#S#101][]  thisStack = #S#525[loop,loop,%for%to%%do%#S#101][]

17:sendv  1 body#SB#539:1054:descInx:539 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = #S#525[loop,loop,%for%to%%do%#S#101][]
1:rstore 2 %for%to%%do%#S#101->body#SB#539[2]
3:allocEventQ 0 
5:mvStack 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = body#SB#539[#S#525,#S#525][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = body#SB#539[#S#525,#S#525][]
10:pushthis 
11:rpushg 2 body#SB#539[2]=%for%to%%do%#S#101
13:rpushg 2 %for%to%%do%#S#101[2]=print
15:rpushg 1 print[1]=String
17:pushthis 
18:rpushg 2 body#SB#539[2]=%for%to%%do%#S#101
20:pushg 3 %for%to%%do%#S#101[3]=16
22:xpushg 1 String[17]=114
xpushg:
Object: String:1017 lsc: 0
VFields: 18 105 110 116 101 103 101 114 65 114 114 97 121 83 116 97 114 116 49 0 
Rfields: (0)LIB:1004 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
VStack: 
RStack: 
VdtTable: 0 0 0 0 
lscStack: 
--------------

24:%prim 2 114 r
26:rtnEventQ 0 
28:setThisStack 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = #S#525[loop,loop][]
29:pushthis 

30:rtn D body#SB#539:1054:descInx:539  to: #S#525:1053:descInx:525 
thisObj = #S#525[loop,loop,body#SB#539][]  thisStack = #S#525[loop,loop,body#SB#539][]
19:rpop 
20:pushthis 
21:rpushg 1 #S#525[1]=loop
23:rpushg 1 loop[1]=do
25:rpushg 1 do[1]=%for%to%%do%#S#101
27:pushthis 
28:rpushg 1 #S#525[1]=loop
30:rpushg 1 loop[1]=do
32:rpushg 1 do[1]=%for%to%%do%#S#101
34:pushg 3 %for%to%%do%#S#101[3]=16
36:pushc 1 
38:+ 16 1
39:storeg 3 %for%to%%do%#S#101[3]=17
41:break 1 81 
10:pushthis 
11:rpushg 1 loop[1]=do
13:rpushg 1 do[1]=%for%to%%do%#S#101
15:pushg 3 %for%to%%do%#S#101[3]=17
17:pushthis 
18:rpushg 1 loop[1]=do
20:rpushg 1 do[1]=%for%to%%do%#S#101
22:pushg 2 %for%to%%do%#S#101[2]=18
24:<= 
25:jmpFalse (1)36 
28:pushthis 

29:invoke 525 0 1 #S#525:1055:descInx:525 
thisObj = #S#525[loop,loop][]  thisStack = loop[do,do,loop][]
1:rstore 1 loop->#S#525[1]
3:allocEventQ 0 
5:mvStack 
thisObj = #S#525[loop,loop][]  thisStack = #S#525[loop,loop][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = #S#525[loop,loop][]  thisStack = #S#525[loop,loop][]
10:pushthis 
11:rpushg 1 #S#525[1]=loop
13:rpushg 1 loop[1]=do
15:rpushg 1 do[1]=%for%to%%do%#S#101
thisObj = #S#525[loop,loop,%for%to%%do%#S#101][]  thisStack = #S#525[loop,loop,%for%to%%do%#S#101][]

17:sendv  1 body#SB#539:1056:descInx:539 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = #S#525[loop,loop,%for%to%%do%#S#101][]
1:rstore 2 %for%to%%do%#S#101->body#SB#539[2]
3:allocEventQ 0 
5:mvStack 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = body#SB#539[#S#525,#S#525][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = body#SB#539[#S#525,#S#525][]
10:pushthis 
11:rpushg 2 body#SB#539[2]=%for%to%%do%#S#101
13:rpushg 2 %for%to%%do%#S#101[2]=print
15:rpushg 1 print[1]=String
17:pushthis 
18:rpushg 2 body#SB#539[2]=%for%to%%do%#S#101
20:pushg 3 %for%to%%do%#S#101[3]=17
22:xpushg 1 String[18]=116
xpushg:
Object: String:1017 lsc: 0
VFields: 18 105 110 116 101 103 101 114 65 114 114 97 121 83 116 97 114 116 49 0 
Rfields: (0)LIB:1004 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
VStack: 
RStack: 
VdtTable: 0 0 0 0 
lscStack: 
--------------

24:%prim 2 116 t
26:rtnEventQ 0 
28:setThisStack 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = #S#525[loop,loop][]
29:pushthis 

30:rtn D body#SB#539:1056:descInx:539  to: #S#525:1055:descInx:525 
thisObj = #S#525[loop,loop,body#SB#539][]  thisStack = #S#525[loop,loop,body#SB#539][]
19:rpop 
20:pushthis 
21:rpushg 1 #S#525[1]=loop
23:rpushg 1 loop[1]=do
25:rpushg 1 do[1]=%for%to%%do%#S#101
27:pushthis 
28:rpushg 1 #S#525[1]=loop
30:rpushg 1 loop[1]=do
32:rpushg 1 do[1]=%for%to%%do%#S#101
34:pushg 3 %for%to%%do%#S#101[3]=17
36:pushc 1 
38:+ 17 1
39:storeg 3 %for%to%%do%#S#101[3]=18
41:break 1 81 
10:pushthis 
11:rpushg 1 loop[1]=do
13:rpushg 1 do[1]=%for%to%%do%#S#101
15:pushg 3 %for%to%%do%#S#101[3]=18
17:pushthis 
18:rpushg 1 loop[1]=do
20:rpushg 1 do[1]=%for%to%%do%#S#101
22:pushg 2 %for%to%%do%#S#101[2]=18
24:<= 
25:jmpFalse (1)36 
28:pushthis 

29:invoke 525 0 1 #S#525:1057:descInx:525 
thisObj = #S#525[loop,loop][]  thisStack = loop[do,do,loop][]
1:rstore 1 loop->#S#525[1]
3:allocEventQ 0 
5:mvStack 
thisObj = #S#525[loop,loop][]  thisStack = #S#525[loop,loop][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = #S#525[loop,loop][]  thisStack = #S#525[loop,loop][]
10:pushthis 
11:rpushg 1 #S#525[1]=loop
13:rpushg 1 loop[1]=do
15:rpushg 1 do[1]=%for%to%%do%#S#101
thisObj = #S#525[loop,loop,%for%to%%do%#S#101][]  thisStack = #S#525[loop,loop,%for%to%%do%#S#101][]

17:sendv  1 body#SB#539:1058:descInx:539 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = #S#525[loop,loop,%for%to%%do%#S#101][]
1:rstore 2 %for%to%%do%#S#101->body#SB#539[2]
3:allocEventQ 0 
5:mvStack 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = body#SB#539[#S#525,#S#525][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = body#SB#539[#S#525,#S#525][]
10:pushthis 
11:rpushg 2 body#SB#539[2]=%for%to%%do%#S#101
13:rpushg 2 %for%to%%do%#S#101[2]=print
15:rpushg 1 print[1]=String
17:pushthis 
18:rpushg 2 body#SB#539[2]=%for%to%%do%#S#101
20:pushg 3 %for%to%%do%#S#101[3]=18
22:xpushg 1 String[19]=49
xpushg:
Object: String:1017 lsc: 0
VFields: 18 105 110 116 101 103 101 114 65 114 114 97 121 83 116 97 114 116 49 0 
Rfields: (0)LIB:1004 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
VStack: 
RStack: 
VdtTable: 0 0 0 0 
lscStack: 
--------------

24:%prim 2 49 1
26:rtnEventQ 0 
28:setThisStack 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = #S#525[loop,loop][]
29:pushthis 

30:rtn D body#SB#539:1058:descInx:539  to: #S#525:1057:descInx:525 
thisObj = #S#525[loop,loop,body#SB#539][]  thisStack = #S#525[loop,loop,body#SB#539][]
19:rpop 
20:pushthis 
21:rpushg 1 #S#525[1]=loop
23:rpushg 1 loop[1]=do
25:rpushg 1 do[1]=%for%to%%do%#S#101
27:pushthis 
28:rpushg 1 #S#525[1]=loop
30:rpushg 1 loop[1]=do
32:rpushg 1 do[1]=%for%to%%do%#S#101
34:pushg 3 %for%to%%do%#S#101[3]=18
36:pushc 1 
38:+ 18 1
39:storeg 3 %for%to%%do%#S#101[3]=19
41:break 1 81 
10:pushthis 
11:rpushg 1 loop[1]=do
13:rpushg 1 do[1]=%for%to%%do%#S#101
15:pushg 3 %for%to%%do%#S#101[3]=19
17:pushthis 
18:rpushg 1 loop[1]=do
20:rpushg 1 do[1]=%for%to%%do%#S#101
22:pushg 2 %for%to%%do%#S#101[2]=18
24:<= 
25:jmpFalse (0)36 
36:rtnEventQ 0 
38:setThisStack 
thisObj = loop[do,do][]  thisStack = do[%for%to%%do%#S#101,%for%to%%do%#S#101][]
39:pushthis 

40:rtn D loop:1022:descInx:65  to: do:1021:descInx:64 
thisObj = do[%for%to%%do%#S#101,%for%to%%do%#S#101,loop][]  thisStack = do[%for%to%%do%#S#101,%for%to%%do%#S#101,loop][]
13:rpop 
14:rtnEventQ 0 
16:mvStack 
thisObj = do[%for%to%%do%#S#101,%for%to%%do%#S#101][]  thisStack = do[%for%to%%do%#S#101,%for%to%%do%#S#101][]
17:rtnEventQ 0 
19:setThisStack 
thisObj = do[%for%to%%do%#S#101,%for%to%%do%#S#101][]  thisStack = %for%to%%do%#S#101[print,print][]
20:pushthis 

21:rtn D do:1021:descInx:64  to: %for%to%%do%#S#101:1019:descInx:101 
thisObj = %for%to%%do%#S#101[print,print,do][]  thisStack = %for%to%%do%#S#101[print,print,do][]
29:rpop 
30:rtnEventQ 0 
32:setThisStack 
thisObj = %for%to%%do%#S#101[print,print][]  thisStack = print[(0)List,(0)List][]
33:pushthis 

34:rtn D %for%to%%do%#S#101:1019:descInx:101  to: print:1018:descInx:100 
thisObj = print[(0)List,(0)List,%for%to%%do%#S#101][]  thisStack = print[(0)List,(0)List,%for%to%%do%#S#101][]
17:rpop 
18:rtnEventQ 0 
20:setThisStack 
thisObj = print[(0)List,(0)List][]  thisStack = (0)List[(0)ArrayDemos,(0)ArrayDemos][]
21:pushthis 

22:rtn D print:1018:descInx:100  to: (0)List:1016:descInx:434 
thisObj = (0)List[(0)ArrayDemos,(0)ArrayDemos,print][]  thisStack = (0)List[(0)ArrayDemos,(0)ArrayDemos,print][]
18:rpop 
19:pushthis 
20:rpushg 1 (0)List[1]=(0)ArrayDemos
22:rpushg 1 (0)ArrayDemos[1]=(0)demo
24:rpushg 1 (0)demo[1]=(0)workspace

26:invoke 66 0 0 newline:1059:descInx:66 
thisObj = newline[(0)List,(0)List][]  thisStack = (0)List[(0)ArrayDemos,(0)ArrayDemos,(0)workspace][]
1:rstore 1 (0)workspace->newline[1]
3:allocEventQ 0 
5:mvStack 
thisObj = newline[(0)List,(0)List][]  thisStack = newline[(0)List,(0)List][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = newline[(0)List,(0)List][]  thisStack = newline[(0)List,(0)List][]
10:pushc 10 
12:%prim 2 10 

14:rtnEventQ 0 
16:setThisStack 
thisObj = newline[(0)List,(0)List][]  thisStack = (0)List[(0)ArrayDemos,(0)ArrayDemos][]
17:pushthis 

18:rtn D newline:1059:descInx:66  to: (0)List:1016:descInx:434 
thisObj = (0)List[(0)ArrayDemos,(0)ArrayDemos,newline][]  thisStack = (0)List[(0)ArrayDemos,(0)ArrayDemos,newline][]
32:rpop 
33:pushthis 
34:pushthis 

35:invoke 626 0 1 List#S#626:1060:descInx:626 
thisObj = List#S#626[(0)List,(0)List][]  thisStack = (0)List[(0)ArrayDemos,(0)ArrayDemos,(0)List,(0)List][]
1:rstore 1 (0)List->List#S#626[1]
3:allocEventQ 1 
5:pushthis 
6:rpushg 1 List#S#626[1]=(0)List
8:pushNone 
9:pushNone 
10:toSuper 436 436 glsc: 1
1:pushthis 
2:rstoreg 3 List#S#626[3]=none
4:pushthis 
5:rstoreg 2 List#S#626[2]=none
7:rstore 1 (0)List->List#S#626[1]
9:allocEventQ 1 
11:mvStack 
thisObj = List#S#626[(0)List,(0)List][]  thisStack = List#S#626[(0)List,(0)List][]
12:rtnEventQ 0 
14:mvStack 
thisObj = List#S#626[(0)List,(0)List][]  thisStack = List#S#626[(0)List,(0)List][]
15:rtnEventQ 0 
17:setThisStack 
thisObj = List#S#626[(0)List,(0)List][]  thisStack = (0)List[(0)ArrayDemos,(0)ArrayDemos,(0)List][]
18:pushthis 

19:rtn D List#S#626:1060:descInx:626  to: (0)List:1016:descInx:434 
thisObj = (0)List[(0)ArrayDemos,(0)ArrayDemos,(0)List,List#S#626][]  thisStack = (0)List[(0)ArrayDemos,(0)ArrayDemos,(0)List,List#S#626][]
41:rswap 
42:rstoreg 4 (0)List[4]=List#S#626
44:pushthis 
45:pushthis 
46:pushthis 
47:rpushg 1 (0)List[1]=(0)ArrayDemos
49:rpushg 1 (0)ArrayDemos[1]=(0)demo
51:rpushg 1 (0)demo[1]=(0)workspace
53:pushc 2 
55:pushc 0 
57:pushc 1 

59:allocIndexed 52 1 
AllocQ_indexed:
Object: Indexed:1061 lsc: 0
VFields: 2 0 0 
Rfields: * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
VStack: 
RStack: 
VdtTable: 0 0 0 0 
lscStack: 
--------------


63:invoke 440 0 0 Range:1062:descInx:440 
thisObj = Range[(0)List,(0)List][]  thisStack = (0)List[(0)ArrayDemos,(0)ArrayDemos,(0)List,(0)List,Indexed][]
1:pushthis 
2:rstoreg 2 Range[2]=Indexed
4:rstore 1 (0)List->Range[1]
6:allocEventQ 0 
8:mvStack 
thisObj = Range[(0)List,(0)List][]  thisStack = Range[(0)List,(0)List][]

9:innerA 1  exe: 0

11:rtnEventQ 1 
13:doEventQ 
14:mvStack 
thisObj = Range[(0)List,(0)List][]  thisStack = Range[(0)List,(0)List][]
15:pushthis 

16:inner P 1  exe: 0

18:rpopThisObj 
19:rtnEventQ 0 
21:setThisStack 
thisObj = Range[(0)List,(0)List][]  thisStack = (0)List[(0)ArrayDemos,(0)ArrayDemos,(0)List][]
22:pushthis 

23:rtn D Range:1062:descInx:440  to: (0)List:1016:descInx:434 
thisObj = (0)List[(0)ArrayDemos,(0)ArrayDemos,(0)List,Range][]  thisStack = (0)List[(0)ArrayDemos,(0)ArrayDemos,(0)List,Range][]
69:rswap 
70:rstoreg 6 (0)List[6]=Range
72:pushthis 
73:pushthis 
74:pushthis 
75:rpushg 1 (0)List[1]=(0)ArrayDemos
77:rpushg 1 (0)ArrayDemos[1]=(0)demo
79:rpushg 1 (0)demo[1]=(0)workspace
81:pushc 2 
83:pushc 0 
85:pushc 1 

87:allocIndexed 52 1 
AllocQ_indexed:
Object: Indexed:1063 lsc: 0
VFields: 2 0 0 
Rfields: * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
VStack: 
RStack: 
VdtTable: 0 0 0 0 
lscStack: 
--------------


91:invoke 440 0 0 Range:1064:descInx:440 
thisObj = Range[(0)List,(0)List][]  thisStack = (0)List[(0)ArrayDemos,(0)ArrayDemos,(0)List,(0)List,Indexed][]
1:pushthis 
2:rstoreg 2 Range[2]=Indexed
4:rstore 1 (0)List->Range[1]
6:allocEventQ 0 
8:mvStack 
thisObj = Range[(0)List,(0)List][]  thisStack = Range[(0)List,(0)List][]

9:innerA 1  exe: 0

11:rtnEventQ 1 
13:doEventQ 
14:mvStack 
thisObj = Range[(0)List,(0)List][]  thisStack = Range[(0)List,(0)List][]
15:pushthis 

16:inner P 1  exe: 0

18:rpopThisObj 
19:rtnEventQ 0 
21:setThisStack 
thisObj = Range[(0)List,(0)List][]  thisStack = (0)List[(0)ArrayDemos,(0)ArrayDemos,(0)List][]
22:pushthis 

23:rtn D Range:1064:descInx:440  to: (0)List:1016:descInx:434 
thisObj = (0)List[(0)ArrayDemos,(0)ArrayDemos,(0)List,Range][]  thisStack = (0)List[(0)ArrayDemos,(0)ArrayDemos,(0)List,Range][]
97:rswap 
98:rstoreg 7 (0)List[7]=Range
100:pushthis 
101:pushthis 
102:pushthis 
103:rpushg 6 (0)List[6]=Range
105:pushthis 
106:rpushg 4 (0)List[4]=List#S#626

108:invoke 438 0 0 RangeList:1065:descInx:438 
thisObj = RangeList[(0)List,(0)List][]  thisStack = (0)List[(0)ArrayDemos,(0)ArrayDemos,(0)List,(0)List,Range,List#S#626][]
1:rstore 1 List#S#626->RangeList[1]
3:allocEventQ 0 
5:pushthis 
6:rpushg 1 RangeList[1]=List#S#626
8:pushthis 
9:rpushg 1 RangeList[1]=List#S#626
11:rpushg 1 List#S#626[1]=(0)List

13:invoke 440 0 0 Range:1066:descInx:440 
thisObj = Range[RangeList,(0)List][]  thisStack = (0)List[(0)ArrayDemos,(0)ArrayDemos,(0)List,(0)List,Range,List#S#626,(0)List][]
1:pushthis 
2:rstoreg 2 Range[2]=(0)List
4:rstore 1 List#S#626->Range[1]
6:allocEventQ 0 
8:mvStack 
thisObj = Range[RangeList,(0)List][]  thisStack = Range[RangeList,(0)List][]

9:innerA 1  exe: 0

11:rtnEventQ 1 
13:doEventQ 
14:mvStack 
thisObj = Range[RangeList,(0)List][]  thisStack = Range[RangeList,(0)List][]
15:pushthis 

16:inner P 1  exe: 0

18:rpopThisObj 
19:rtnEventQ 0 
21:setThisStack 
thisObj = Range[RangeList,(0)List][]  thisStack = (0)List[(0)ArrayDemos,(0)ArrayDemos,(0)List,(0)List,Range][]
22:pushthis 

23:rtn D Range:1066:descInx:440  to: RangeList:1065:descInx:438 
thisObj = RangeList[(0)List,(0)List][]  thisStack = (0)List[(0)ArrayDemos,(0)ArrayDemos,(0)List,(0)List,Range,Range][]
19:toSuper 436 436 glsc: 1
1:pushthis 
2:rstoreg 3 RangeList[3]=Range
4:pushthis 
5:rstoreg 2 RangeList[2]=Range
7:rstore 1 (0)List->RangeList[1]
9:allocEventQ 1 
11:mvStack 
thisObj = RangeList[(0)List,(0)List][]  thisStack = RangeList[(0)List,(0)List][]
12:rtnEventQ 0 
14:mvStack 
thisObj = RangeList[(0)List,(0)List][]  thisStack = RangeList[(0)List,(0)List][]
15:rtnEventQ 0 
17:setThisStack 
thisObj = RangeList[(0)List,(0)List][]  thisStack = (0)List[(0)ArrayDemos,(0)ArrayDemos,(0)List][]
18:pushthis 

19:rtn D RangeList:1065:descInx:438  to: (0)List:1016:descInx:434 
thisObj = (0)List[(0)ArrayDemos,(0)ArrayDemos,(0)List,RangeList][]  thisStack = (0)List[(0)ArrayDemos,(0)ArrayDemos,(0)List,RangeList][]
114:rswap 
115:rstoreg 3 (0)List[3]=RangeList
117:pushText 20 
XmkTextObject
Object: String:1067 lsc: 0
VFields: 18 105 110 116 101 103 101 114 65 114 114 97 121 83 116 97 114 116 50 0 
Rfields: (0)LIB:1004 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
VStack: 
RStack: 
VdtTable: 0 0 0 0 
lscStack: 
--------------


119:invoke 100 0 0 print:1068:descInx:100 
thisObj = print[(0)List,(0)List][]  thisStack = (0)List[(0)ArrayDemos,(0)ArrayDemos,String][]
1:rstore 1 String->print[1]
3:allocEventQ 0 
5:mvStack 
thisObj = print[(0)List,(0)List][]  thisStack = print[(0)List,(0)List][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = print[(0)List,(0)List][]  thisStack = print[(0)List,(0)List][]
10:pushthis 

11:invoke 101 0 1 %for%to%%do%#S#101:1069:descInx:101 
thisObj = %for%to%%do%#S#101[print,print][]  thisStack = print[(0)List,(0)List,print][]
1:rstore 2 print->%for%to%%do%#S#101[2]
3:allocEventQ 1 
5:pushthis 
6:rpushg 2 %for%to%%do%#S#101[2]=print
8:rpushg 1 print[1]=String
10:rpushg 1 String[1]=(0)LIB
12:rpushg 1 (0)LIB[1]=BETAworld
14:pushc 1 
16:pushthis 
17:rpushg 2 %for%to%%do%#S#101[2]=print
19:rpushg 1 print[1]=String

21:invoke 91 0 0 length:1070:descInx:91 
thisObj = length[%for%to%%do%#S#101,print][]  thisStack = print[(0)List,(0)List,BETAworld,String][1]
1:rstore 1 String->length[1]
3:allocEventQ 0 
5:mvStack 
thisObj = length[%for%to%%do%#S#101,print][]  thisStack = length[%for%to%%do%#S#101,print][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = length[%for%to%%do%#S#101,print][]  thisStack = length[%for%to%%do%#S#101,print][]
10:pushthis 
11:pushthis 
12:rpushg 1 length[1]=String
14:pushc 0 
16:xpushg 1 String[1]=18
xpushg:
Object: String:1067 lsc: 0
VFields: 18 105 110 116 101 103 101 114 65 114 114 97 121 83 116 97 114 116 50 0 
Rfields: (0)LIB:1004 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
VStack: 
RStack: 
VdtTable: 0 0 0 0 
lscStack: 
--------------

18:storeg 1 length[1]=18
20:rtnEventQ 0 
22:setThisStack 
thisObj = length[%for%to%%do%#S#101,print][]  thisStack = print[(0)List,(0)List,BETAworld][1]
23:pushthis 
24:pushg 1 length[1]=18

26:rtn D length:1070:descInx:91  to: %for%to%%do%#S#101:1069:descInx:101 
thisObj = %for%to%%do%#S#101[print,print][]  thisStack = print[(0)List,(0)List,BETAworld][1,18]
27:toSuper 63 63 glsc: 1
1:pushthis 
2:storeg 2 %for%to%%do%#S#101[2]=18
4:pushthis 
5:storeg 1 %for%to%%do%#S#101[1]=1
7:rstore 1 BETAworld->%for%to%%do%#S#101[1]
9:allocEventQ 0 
11:mvStack 
thisObj = %for%to%%do%#S#101[print,print][]  thisStack = %for%to%%do%#S#101[print,print][]
12:rtnEventQ 1 
14:doEventQ 
15:mvStack 
thisObj = %for%to%%do%#S#101[print,print][]  thisStack = %for%to%%do%#S#101[print,print][]
16:pushthis 
17:pushthis 
18:pushg 1 %for%to%%do%#S#101[1]=1
20:storeg 3 %for%to%%do%#S#101[3]=1
22:pushthis 

23:invoke 64 0 1 do:1071:descInx:64 
thisObj = do[%for%to%%do%#S#101,%for%to%%do%#S#101][]  thisStack = %for%to%%do%#S#101[print,print,%for%to%%do%#S#101][]
1:rstore 1 %for%to%%do%#S#101->do[1]
3:allocEventQ 1 
5:mvStack 
thisObj = do[%for%to%%do%#S#101,%for%to%%do%#S#101][]  thisStack = do[%for%to%%do%#S#101,%for%to%%do%#S#101][]
6:pushthis 

7:invoke 65 2 1 loop:1072:descInx:65 
thisObj = loop[do,do][]  thisStack = do[%for%to%%do%#S#101,%for%to%%do%#S#101,do][]
1:rstore 1 do->loop[1]
3:allocEventQ 0 
5:mvStack 
thisObj = loop[do,do][]  thisStack = loop[do,do][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = loop[do,do][]  thisStack = loop[do,do][]
10:pushthis 
11:rpushg 1 loop[1]=do
13:rpushg 1 do[1]=%for%to%%do%#S#101
15:pushg 3 %for%to%%do%#S#101[3]=1
17:pushthis 
18:rpushg 1 loop[1]=do
20:rpushg 1 do[1]=%for%to%%do%#S#101
22:pushg 2 %for%to%%do%#S#101[2]=18
24:<= 
25:jmpFalse (1)36 
28:pushthis 

29:invoke 525 0 1 #S#525:1073:descInx:525 
thisObj = #S#525[loop,loop][]  thisStack = loop[do,do,loop][]
1:rstore 1 loop->#S#525[1]
3:allocEventQ 0 
5:mvStack 
thisObj = #S#525[loop,loop][]  thisStack = #S#525[loop,loop][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = #S#525[loop,loop][]  thisStack = #S#525[loop,loop][]
10:pushthis 
11:rpushg 1 #S#525[1]=loop
13:rpushg 1 loop[1]=do
15:rpushg 1 do[1]=%for%to%%do%#S#101
thisObj = #S#525[loop,loop,%for%to%%do%#S#101][]  thisStack = #S#525[loop,loop,%for%to%%do%#S#101][]

17:sendv  1 body#SB#539:1074:descInx:539 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = #S#525[loop,loop,%for%to%%do%#S#101][]
1:rstore 2 %for%to%%do%#S#101->body#SB#539[2]
3:allocEventQ 0 
5:mvStack 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = body#SB#539[#S#525,#S#525][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = body#SB#539[#S#525,#S#525][]
10:pushthis 
11:rpushg 2 body#SB#539[2]=%for%to%%do%#S#101
13:rpushg 2 %for%to%%do%#S#101[2]=print
15:rpushg 1 print[1]=String
17:pushthis 
18:rpushg 2 body#SB#539[2]=%for%to%%do%#S#101
20:pushg 3 %for%to%%do%#S#101[3]=1
22:xpushg 1 String[2]=105
xpushg:
Object: String:1067 lsc: 0
VFields: 18 105 110 116 101 103 101 114 65 114 114 97 121 83 116 97 114 116 50 0 
Rfields: (0)LIB:1004 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
VStack: 
RStack: 
VdtTable: 0 0 0 0 
lscStack: 
--------------

24:%prim 2 105 i
26:rtnEventQ 0 
28:setThisStack 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = #S#525[loop,loop][]
29:pushthis 

30:rtn D body#SB#539:1074:descInx:539  to: #S#525:1073:descInx:525 
thisObj = #S#525[loop,loop,body#SB#539][]  thisStack = #S#525[loop,loop,body#SB#539][]
19:rpop 
20:pushthis 
21:rpushg 1 #S#525[1]=loop
23:rpushg 1 loop[1]=do
25:rpushg 1 do[1]=%for%to%%do%#S#101
27:pushthis 
28:rpushg 1 #S#525[1]=loop
30:rpushg 1 loop[1]=do
32:rpushg 1 do[1]=%for%to%%do%#S#101
34:pushg 3 %for%to%%do%#S#101[3]=1
36:pushc 1 
38:+ 1 1
39:storeg 3 %for%to%%do%#S#101[3]=2
41:break 1 81 
10:pushthis 
11:rpushg 1 loop[1]=do
13:rpushg 1 do[1]=%for%to%%do%#S#101
15:pushg 3 %for%to%%do%#S#101[3]=2
17:pushthis 
18:rpushg 1 loop[1]=do
20:rpushg 1 do[1]=%for%to%%do%#S#101
22:pushg 2 %for%to%%do%#S#101[2]=18
24:<= 
25:jmpFalse (1)36 
28:pushthis 

29:invoke 525 0 1 #S#525:1075:descInx:525 
thisObj = #S#525[loop,loop][]  thisStack = loop[do,do,loop][]
1:rstore 1 loop->#S#525[1]
3:allocEventQ 0 
5:mvStack 
thisObj = #S#525[loop,loop][]  thisStack = #S#525[loop,loop][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = #S#525[loop,loop][]  thisStack = #S#525[loop,loop][]
10:pushthis 
11:rpushg 1 #S#525[1]=loop
13:rpushg 1 loop[1]=do
15:rpushg 1 do[1]=%for%to%%do%#S#101
thisObj = #S#525[loop,loop,%for%to%%do%#S#101][]  thisStack = #S#525[loop,loop,%for%to%%do%#S#101][]

17:sendv  1 body#SB#539:1076:descInx:539 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = #S#525[loop,loop,%for%to%%do%#S#101][]
1:rstore 2 %for%to%%do%#S#101->body#SB#539[2]
3:allocEventQ 0 
5:mvStack 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = body#SB#539[#S#525,#S#525][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = body#SB#539[#S#525,#S#525][]
10:pushthis 
11:rpushg 2 body#SB#539[2]=%for%to%%do%#S#101
13:rpushg 2 %for%to%%do%#S#101[2]=print
15:rpushg 1 print[1]=String
17:pushthis 
18:rpushg 2 body#SB#539[2]=%for%to%%do%#S#101
20:pushg 3 %for%to%%do%#S#101[3]=2
22:xpushg 1 String[3]=110
xpushg:
Object: String:1067 lsc: 0
VFields: 18 105 110 116 101 103 101 114 65 114 114 97 121 83 116 97 114 116 50 0 
Rfields: (0)LIB:1004 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
VStack: 
RStack: 
VdtTable: 0 0 0 0 
lscStack: 
--------------

24:%prim 2 110 n
26:rtnEventQ 0 
28:setThisStack 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = #S#525[loop,loop][]
29:pushthis 

30:rtn D body#SB#539:1076:descInx:539  to: #S#525:1075:descInx:525 
thisObj = #S#525[loop,loop,body#SB#539][]  thisStack = #S#525[loop,loop,body#SB#539][]
19:rpop 
20:pushthis 
21:rpushg 1 #S#525[1]=loop
23:rpushg 1 loop[1]=do
25:rpushg 1 do[1]=%for%to%%do%#S#101
27:pushthis 
28:rpushg 1 #S#525[1]=loop
30:rpushg 1 loop[1]=do
32:rpushg 1 do[1]=%for%to%%do%#S#101
34:pushg 3 %for%to%%do%#S#101[3]=2
36:pushc 1 
38:+ 2 1
39:storeg 3 %for%to%%do%#S#101[3]=3
41:break 1 81 
10:pushthis 
11:rpushg 1 loop[1]=do
13:rpushg 1 do[1]=%for%to%%do%#S#101
15:pushg 3 %for%to%%do%#S#101[3]=3
17:pushthis 
18:rpushg 1 loop[1]=do
20:rpushg 1 do[1]=%for%to%%do%#S#101
22:pushg 2 %for%to%%do%#S#101[2]=18
24:<= 
25:jmpFalse (1)36 
28:pushthis 

29:invoke 525 0 1 #S#525:1077:descInx:525 
thisObj = #S#525[loop,loop][]  thisStack = loop[do,do,loop][]
1:rstore 1 loop->#S#525[1]
3:allocEventQ 0 
5:mvStack 
thisObj = #S#525[loop,loop][]  thisStack = #S#525[loop,loop][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = #S#525[loop,loop][]  thisStack = #S#525[loop,loop][]
10:pushthis 
11:rpushg 1 #S#525[1]=loop
13:rpushg 1 loop[1]=do
15:rpushg 1 do[1]=%for%to%%do%#S#101
thisObj = #S#525[loop,loop,%for%to%%do%#S#101][]  thisStack = #S#525[loop,loop,%for%to%%do%#S#101][]

17:sendv  1 body#SB#539:1078:descInx:539 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = #S#525[loop,loop,%for%to%%do%#S#101][]
1:rstore 2 %for%to%%do%#S#101->body#SB#539[2]
3:allocEventQ 0 
5:mvStack 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = body#SB#539[#S#525,#S#525][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = body#SB#539[#S#525,#S#525][]
10:pushthis 
11:rpushg 2 body#SB#539[2]=%for%to%%do%#S#101
13:rpushg 2 %for%to%%do%#S#101[2]=print
15:rpushg 1 print[1]=String
17:pushthis 
18:rpushg 2 body#SB#539[2]=%for%to%%do%#S#101
20:pushg 3 %for%to%%do%#S#101[3]=3
22:xpushg 1 String[4]=116
xpushg:
Object: String:1067 lsc: 0
VFields: 18 105 110 116 101 103 101 114 65 114 114 97 121 83 116 97 114 116 50 0 
Rfields: (0)LIB:1004 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
VStack: 
RStack: 
VdtTable: 0 0 0 0 
lscStack: 
--------------

24:%prim 2 116 t
26:rtnEventQ 0 
28:setThisStack 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = #S#525[loop,loop][]
29:pushthis 

30:rtn D body#SB#539:1078:descInx:539  to: #S#525:1077:descInx:525 
thisObj = #S#525[loop,loop,body#SB#539][]  thisStack = #S#525[loop,loop,body#SB#539][]
19:rpop 
20:pushthis 
21:rpushg 1 #S#525[1]=loop
23:rpushg 1 loop[1]=do
25:rpushg 1 do[1]=%for%to%%do%#S#101
27:pushthis 
28:rpushg 1 #S#525[1]=loop
30:rpushg 1 loop[1]=do
32:rpushg 1 do[1]=%for%to%%do%#S#101
34:pushg 3 %for%to%%do%#S#101[3]=3
36:pushc 1 
38:+ 3 1
39:storeg 3 %for%to%%do%#S#101[3]=4
41:break 1 81 
10:pushthis 
11:rpushg 1 loop[1]=do
13:rpushg 1 do[1]=%for%to%%do%#S#101
15:pushg 3 %for%to%%do%#S#101[3]=4
17:pushthis 
18:rpushg 1 loop[1]=do
20:rpushg 1 do[1]=%for%to%%do%#S#101
22:pushg 2 %for%to%%do%#S#101[2]=18
24:<= 
25:jmpFalse (1)36 
28:pushthis 

29:invoke 525 0 1 #S#525:1079:descInx:525 
thisObj = #S#525[loop,loop][]  thisStack = loop[do,do,loop][]
1:rstore 1 loop->#S#525[1]
3:allocEventQ 0 
5:mvStack 
thisObj = #S#525[loop,loop][]  thisStack = #S#525[loop,loop][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = #S#525[loop,loop][]  thisStack = #S#525[loop,loop][]
10:pushthis 
11:rpushg 1 #S#525[1]=loop
13:rpushg 1 loop[1]=do
15:rpushg 1 do[1]=%for%to%%do%#S#101
thisObj = #S#525[loop,loop,%for%to%%do%#S#101][]  thisStack = #S#525[loop,loop,%for%to%%do%#S#101][]

17:sendv  1 body#SB#539:1080:descInx:539 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = #S#525[loop,loop,%for%to%%do%#S#101][]
1:rstore 2 %for%to%%do%#S#101->body#SB#539[2]
3:allocEventQ 0 
5:mvStack 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = body#SB#539[#S#525,#S#525][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = body#SB#539[#S#525,#S#525][]
10:pushthis 
11:rpushg 2 body#SB#539[2]=%for%to%%do%#S#101
13:rpushg 2 %for%to%%do%#S#101[2]=print
15:rpushg 1 print[1]=String
17:pushthis 
18:rpushg 2 body#SB#539[2]=%for%to%%do%#S#101
20:pushg 3 %for%to%%do%#S#101[3]=4
22:xpushg 1 String[5]=101
xpushg:
Object: String:1067 lsc: 0
VFields: 18 105 110 116 101 103 101 114 65 114 114 97 121 83 116 97 114 116 50 0 
Rfields: (0)LIB:1004 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
VStack: 
RStack: 
VdtTable: 0 0 0 0 
lscStack: 
--------------

24:%prim 2 101 e
26:rtnEventQ 0 
28:setThisStack 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = #S#525[loop,loop][]
29:pushthis 

30:rtn D body#SB#539:1080:descInx:539  to: #S#525:1079:descInx:525 
thisObj = #S#525[loop,loop,body#SB#539][]  thisStack = #S#525[loop,loop,body#SB#539][]
19:rpop 
20:pushthis 
21:rpushg 1 #S#525[1]=loop
23:rpushg 1 loop[1]=do
25:rpushg 1 do[1]=%for%to%%do%#S#101
27:pushthis 
28:rpushg 1 #S#525[1]=loop
30:rpushg 1 loop[1]=do
32:rpushg 1 do[1]=%for%to%%do%#S#101
34:pushg 3 %for%to%%do%#S#101[3]=4
36:pushc 1 
38:+ 4 1
39:storeg 3 %for%to%%do%#S#101[3]=5
41:break 1 81 
10:pushthis 
11:rpushg 1 loop[1]=do
13:rpushg 1 do[1]=%for%to%%do%#S#101
15:pushg 3 %for%to%%do%#S#101[3]=5
17:pushthis 
18:rpushg 1 loop[1]=do
20:rpushg 1 do[1]=%for%to%%do%#S#101
22:pushg 2 %for%to%%do%#S#101[2]=18
24:<= 
25:jmpFalse (1)36 
28:pushthis 

29:invoke 525 0 1 #S#525:1081:descInx:525 
thisObj = #S#525[loop,loop][]  thisStack = loop[do,do,loop][]
1:rstore 1 loop->#S#525[1]
3:allocEventQ 0 
5:mvStack 
thisObj = #S#525[loop,loop][]  thisStack = #S#525[loop,loop][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = #S#525[loop,loop][]  thisStack = #S#525[loop,loop][]
10:pushthis 
11:rpushg 1 #S#525[1]=loop
13:rpushg 1 loop[1]=do
15:rpushg 1 do[1]=%for%to%%do%#S#101
thisObj = #S#525[loop,loop,%for%to%%do%#S#101][]  thisStack = #S#525[loop,loop,%for%to%%do%#S#101][]

17:sendv  1 body#SB#539:1082:descInx:539 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = #S#525[loop,loop,%for%to%%do%#S#101][]
1:rstore 2 %for%to%%do%#S#101->body#SB#539[2]
3:allocEventQ 0 
5:mvStack 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = body#SB#539[#S#525,#S#525][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = body#SB#539[#S#525,#S#525][]
10:pushthis 
11:rpushg 2 body#SB#539[2]=%for%to%%do%#S#101
13:rpushg 2 %for%to%%do%#S#101[2]=print
15:rpushg 1 print[1]=String
17:pushthis 
18:rpushg 2 body#SB#539[2]=%for%to%%do%#S#101
20:pushg 3 %for%to%%do%#S#101[3]=5
22:xpushg 1 String[6]=103
xpushg:
Object: String:1067 lsc: 0
VFields: 18 105 110 116 101 103 101 114 65 114 114 97 121 83 116 97 114 116 50 0 
Rfields: (0)LIB:1004 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
VStack: 
RStack: 
VdtTable: 0 0 0 0 
lscStack: 
--------------

24:%prim 2 103 g
26:rtnEventQ 0 
28:setThisStack 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = #S#525[loop,loop][]
29:pushthis 

30:rtn D body#SB#539:1082:descInx:539  to: #S#525:1081:descInx:525 
thisObj = #S#525[loop,loop,body#SB#539][]  thisStack = #S#525[loop,loop,body#SB#539][]
19:rpop 
20:pushthis 
21:rpushg 1 #S#525[1]=loop
23:rpushg 1 loop[1]=do
25:rpushg 1 do[1]=%for%to%%do%#S#101
27:pushthis 
28:rpushg 1 #S#525[1]=loop
30:rpushg 1 loop[1]=do
32:rpushg 1 do[1]=%for%to%%do%#S#101
34:pushg 3 %for%to%%do%#S#101[3]=5
36:pushc 1 
38:+ 5 1
39:storeg 3 %for%to%%do%#S#101[3]=6
41:break 1 81 
10:pushthis 
11:rpushg 1 loop[1]=do
13:rpushg 1 do[1]=%for%to%%do%#S#101
15:pushg 3 %for%to%%do%#S#101[3]=6
17:pushthis 
18:rpushg 1 loop[1]=do
20:rpushg 1 do[1]=%for%to%%do%#S#101
22:pushg 2 %for%to%%do%#S#101[2]=18
24:<= 
25:jmpFalse (1)36 
28:pushthis 

29:invoke 525 0 1 #S#525:1083:descInx:525 
thisObj = #S#525[loop,loop][]  thisStack = loop[do,do,loop][]
1:rstore 1 loop->#S#525[1]
3:allocEventQ 0 
5:mvStack 
thisObj = #S#525[loop,loop][]  thisStack = #S#525[loop,loop][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = #S#525[loop,loop][]  thisStack = #S#525[loop,loop][]
10:pushthis 
11:rpushg 1 #S#525[1]=loop
13:rpushg 1 loop[1]=do
15:rpushg 1 do[1]=%for%to%%do%#S#101
thisObj = #S#525[loop,loop,%for%to%%do%#S#101][]  thisStack = #S#525[loop,loop,%for%to%%do%#S#101][]

17:sendv  1 body#SB#539:1084:descInx:539 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = #S#525[loop,loop,%for%to%%do%#S#101][]
1:rstore 2 %for%to%%do%#S#101->body#SB#539[2]
3:allocEventQ 0 
5:mvStack 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = body#SB#539[#S#525,#S#525][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = body#SB#539[#S#525,#S#525][]
10:pushthis 
11:rpushg 2 body#SB#539[2]=%for%to%%do%#S#101
13:rpushg 2 %for%to%%do%#S#101[2]=print
15:rpushg 1 print[1]=String
17:pushthis 
18:rpushg 2 body#SB#539[2]=%for%to%%do%#S#101
20:pushg 3 %for%to%%do%#S#101[3]=6
22:xpushg 1 String[7]=101
xpushg:
Object: String:1067 lsc: 0
VFields: 18 105 110 116 101 103 101 114 65 114 114 97 121 83 116 97 114 116 50 0 
Rfields: (0)LIB:1004 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
VStack: 
RStack: 
VdtTable: 0 0 0 0 
lscStack: 
--------------

24:%prim 2 101 e
26:rtnEventQ 0 
28:setThisStack 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = #S#525[loop,loop][]
29:pushthis 

30:rtn D body#SB#539:1084:descInx:539  to: #S#525:1083:descInx:525 
thisObj = #S#525[loop,loop,body#SB#539][]  thisStack = #S#525[loop,loop,body#SB#539][]
19:rpop 
20:pushthis 
21:rpushg 1 #S#525[1]=loop
23:rpushg 1 loop[1]=do
25:rpushg 1 do[1]=%for%to%%do%#S#101
27:pushthis 
28:rpushg 1 #S#525[1]=loop
30:rpushg 1 loop[1]=do
32:rpushg 1 do[1]=%for%to%%do%#S#101
34:pushg 3 %for%to%%do%#S#101[3]=6
36:pushc 1 
38:+ 6 1
39:storeg 3 %for%to%%do%#S#101[3]=7
41:break 1 81 
10:pushthis 
11:rpushg 1 loop[1]=do
13:rpushg 1 do[1]=%for%to%%do%#S#101
15:pushg 3 %for%to%%do%#S#101[3]=7
17:pushthis 
18:rpushg 1 loop[1]=do
20:rpushg 1 do[1]=%for%to%%do%#S#101
22:pushg 2 %for%to%%do%#S#101[2]=18
24:<= 
25:jmpFalse (1)36 
28:pushthis 

29:invoke 525 0 1 #S#525:1085:descInx:525 
thisObj = #S#525[loop,loop][]  thisStack = loop[do,do,loop][]
1:rstore 1 loop->#S#525[1]
3:allocEventQ 0 
5:mvStack 
thisObj = #S#525[loop,loop][]  thisStack = #S#525[loop,loop][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = #S#525[loop,loop][]  thisStack = #S#525[loop,loop][]
10:pushthis 
11:rpushg 1 #S#525[1]=loop
13:rpushg 1 loop[1]=do
15:rpushg 1 do[1]=%for%to%%do%#S#101
thisObj = #S#525[loop,loop,%for%to%%do%#S#101][]  thisStack = #S#525[loop,loop,%for%to%%do%#S#101][]

17:sendv  1 body#SB#539:1086:descInx:539 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = #S#525[loop,loop,%for%to%%do%#S#101][]
1:rstore 2 %for%to%%do%#S#101->body#SB#539[2]
3:allocEventQ 0 
5:mvStack 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = body#SB#539[#S#525,#S#525][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = body#SB#539[#S#525,#S#525][]
10:pushthis 
11:rpushg 2 body#SB#539[2]=%for%to%%do%#S#101
13:rpushg 2 %for%to%%do%#S#101[2]=print
15:rpushg 1 print[1]=String
17:pushthis 
18:rpushg 2 body#SB#539[2]=%for%to%%do%#S#101
20:pushg 3 %for%to%%do%#S#101[3]=7
22:xpushg 1 String[8]=114
xpushg:
Object: String:1067 lsc: 0
VFields: 18 105 110 116 101 103 101 114 65 114 114 97 121 83 116 97 114 116 50 0 
Rfields: (0)LIB:1004 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
VStack: 
RStack: 
VdtTable: 0 0 0 0 
lscStack: 
--------------

24:%prim 2 114 r
26:rtnEventQ 0 
28:setThisStack 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = #S#525[loop,loop][]
29:pushthis 

30:rtn D body#SB#539:1086:descInx:539  to: #S#525:1085:descInx:525 
thisObj = #S#525[loop,loop,body#SB#539][]  thisStack = #S#525[loop,loop,body#SB#539][]
19:rpop 
20:pushthis 
21:rpushg 1 #S#525[1]=loop
23:rpushg 1 loop[1]=do
25:rpushg 1 do[1]=%for%to%%do%#S#101
27:pushthis 
28:rpushg 1 #S#525[1]=loop
30:rpushg 1 loop[1]=do
32:rpushg 1 do[1]=%for%to%%do%#S#101
34:pushg 3 %for%to%%do%#S#101[3]=7
36:pushc 1 
38:+ 7 1
39:storeg 3 %for%to%%do%#S#101[3]=8
41:break 1 81 
10:pushthis 
11:rpushg 1 loop[1]=do
13:rpushg 1 do[1]=%for%to%%do%#S#101
15:pushg 3 %for%to%%do%#S#101[3]=8
17:pushthis 
18:rpushg 1 loop[1]=do
20:rpushg 1 do[1]=%for%to%%do%#S#101
22:pushg 2 %for%to%%do%#S#101[2]=18
24:<= 
25:jmpFalse (1)36 
28:pushthis 

29:invoke 525 0 1 #S#525:1087:descInx:525 
thisObj = #S#525[loop,loop][]  thisStack = loop[do,do,loop][]
1:rstore 1 loop->#S#525[1]
3:allocEventQ 0 
5:mvStack 
thisObj = #S#525[loop,loop][]  thisStack = #S#525[loop,loop][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = #S#525[loop,loop][]  thisStack = #S#525[loop,loop][]
10:pushthis 
11:rpushg 1 #S#525[1]=loop
13:rpushg 1 loop[1]=do
15:rpushg 1 do[1]=%for%to%%do%#S#101
thisObj = #S#525[loop,loop,%for%to%%do%#S#101][]  thisStack = #S#525[loop,loop,%for%to%%do%#S#101][]

17:sendv  1 body#SB#539:1088:descInx:539 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = #S#525[loop,loop,%for%to%%do%#S#101][]
1:rstore 2 %for%to%%do%#S#101->body#SB#539[2]
3:allocEventQ 0 
5:mvStack 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = body#SB#539[#S#525,#S#525][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = body#SB#539[#S#525,#S#525][]
10:pushthis 
11:rpushg 2 body#SB#539[2]=%for%to%%do%#S#101
13:rpushg 2 %for%to%%do%#S#101[2]=print
15:rpushg 1 print[1]=String
17:pushthis 
18:rpushg 2 body#SB#539[2]=%for%to%%do%#S#101
20:pushg 3 %for%to%%do%#S#101[3]=8
22:xpushg 1 String[9]=65
xpushg:
Object: String:1067 lsc: 0
VFields: 18 105 110 116 101 103 101 114 65 114 114 97 121 83 116 97 114 116 50 0 
Rfields: (0)LIB:1004 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
VStack: 
RStack: 
VdtTable: 0 0 0 0 
lscStack: 
--------------

24:%prim 2 65 A
26:rtnEventQ 0 
28:setThisStack 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = #S#525[loop,loop][]
29:pushthis 

30:rtn D body#SB#539:1088:descInx:539  to: #S#525:1087:descInx:525 
thisObj = #S#525[loop,loop,body#SB#539][]  thisStack = #S#525[loop,loop,body#SB#539][]
19:rpop 
20:pushthis 
21:rpushg 1 #S#525[1]=loop
23:rpushg 1 loop[1]=do
25:rpushg 1 do[1]=%for%to%%do%#S#101
27:pushthis 
28:rpushg 1 #S#525[1]=loop
30:rpushg 1 loop[1]=do
32:rpushg 1 do[1]=%for%to%%do%#S#101
34:pushg 3 %for%to%%do%#S#101[3]=8
36:pushc 1 
38:+ 8 1
39:storeg 3 %for%to%%do%#S#101[3]=9
41:break 1 81 
10:pushthis 
11:rpushg 1 loop[1]=do
13:rpushg 1 do[1]=%for%to%%do%#S#101
15:pushg 3 %for%to%%do%#S#101[3]=9
17:pushthis 
18:rpushg 1 loop[1]=do
20:rpushg 1 do[1]=%for%to%%do%#S#101
22:pushg 2 %for%to%%do%#S#101[2]=18
24:<= 
25:jmpFalse (1)36 
28:pushthis 

29:invoke 525 0 1 #S#525:1089:descInx:525 
thisObj = #S#525[loop,loop][]  thisStack = loop[do,do,loop][]
1:rstore 1 loop->#S#525[1]
3:allocEventQ 0 
5:mvStack 
thisObj = #S#525[loop,loop][]  thisStack = #S#525[loop,loop][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = #S#525[loop,loop][]  thisStack = #S#525[loop,loop][]
10:pushthis 
11:rpushg 1 #S#525[1]=loop
13:rpushg 1 loop[1]=do
15:rpushg 1 do[1]=%for%to%%do%#S#101
thisObj = #S#525[loop,loop,%for%to%%do%#S#101][]  thisStack = #S#525[loop,loop,%for%to%%do%#S#101][]

17:sendv  1 body#SB#539:1090:descInx:539 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = #S#525[loop,loop,%for%to%%do%#S#101][]
1:rstore 2 %for%to%%do%#S#101->body#SB#539[2]
3:allocEventQ 0 
5:mvStack 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = body#SB#539[#S#525,#S#525][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = body#SB#539[#S#525,#S#525][]
10:pushthis 
11:rpushg 2 body#SB#539[2]=%for%to%%do%#S#101
13:rpushg 2 %for%to%%do%#S#101[2]=print
15:rpushg 1 print[1]=String
17:pushthis 
18:rpushg 2 body#SB#539[2]=%for%to%%do%#S#101
20:pushg 3 %for%to%%do%#S#101[3]=9
22:xpushg 1 String[10]=114
xpushg:
Object: String:1067 lsc: 0
VFields: 18 105 110 116 101 103 101 114 65 114 114 97 121 83 116 97 114 116 50 0 
Rfields: (0)LIB:1004 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
VStack: 
RStack: 
VdtTable: 0 0 0 0 
lscStack: 
--------------

24:%prim 2 114 r
26:rtnEventQ 0 
28:setThisStack 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = #S#525[loop,loop][]
29:pushthis 

30:rtn D body#SB#539:1090:descInx:539  to: #S#525:1089:descInx:525 
thisObj = #S#525[loop,loop,body#SB#539][]  thisStack = #S#525[loop,loop,body#SB#539][]
19:rpop 
20:pushthis 
21:rpushg 1 #S#525[1]=loop
23:rpushg 1 loop[1]=do
25:rpushg 1 do[1]=%for%to%%do%#S#101
27:pushthis 
28:rpushg 1 #S#525[1]=loop
30:rpushg 1 loop[1]=do
32:rpushg 1 do[1]=%for%to%%do%#S#101
34:pushg 3 %for%to%%do%#S#101[3]=9
36:pushc 1 
38:+ 9 1
39:storeg 3 %for%to%%do%#S#101[3]=10
41:break 1 81 
10:pushthis 
11:rpushg 1 loop[1]=do
13:rpushg 1 do[1]=%for%to%%do%#S#101
15:pushg 3 %for%to%%do%#S#101[3]=10
17:pushthis 
18:rpushg 1 loop[1]=do
20:rpushg 1 do[1]=%for%to%%do%#S#101
22:pushg 2 %for%to%%do%#S#101[2]=18
24:<= 
25:jmpFalse (1)36 
28:pushthis 

29:invoke 525 0 1 #S#525:1091:descInx:525 
thisObj = #S#525[loop,loop][]  thisStack = loop[do,do,loop][]
1:rstore 1 loop->#S#525[1]
3:allocEventQ 0 
5:mvStack 
thisObj = #S#525[loop,loop][]  thisStack = #S#525[loop,loop][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = #S#525[loop,loop][]  thisStack = #S#525[loop,loop][]
10:pushthis 
11:rpushg 1 #S#525[1]=loop
13:rpushg 1 loop[1]=do
15:rpushg 1 do[1]=%for%to%%do%#S#101
thisObj = #S#525[loop,loop,%for%to%%do%#S#101][]  thisStack = #S#525[loop,loop,%for%to%%do%#S#101][]

17:sendv  1 body#SB#539:1092:descInx:539 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = #S#525[loop,loop,%for%to%%do%#S#101][]
1:rstore 2 %for%to%%do%#S#101->body#SB#539[2]
3:allocEventQ 0 
5:mvStack 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = body#SB#539[#S#525,#S#525][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = body#SB#539[#S#525,#S#525][]
10:pushthis 
11:rpushg 2 body#SB#539[2]=%for%to%%do%#S#101
13:rpushg 2 %for%to%%do%#S#101[2]=print
15:rpushg 1 print[1]=String
17:pushthis 
18:rpushg 2 body#SB#539[2]=%for%to%%do%#S#101
20:pushg 3 %for%to%%do%#S#101[3]=10
22:xpushg 1 String[11]=114
xpushg:
Object: String:1067 lsc: 0
VFields: 18 105 110 116 101 103 101 114 65 114 114 97 121 83 116 97 114 116 50 0 
Rfields: (0)LIB:1004 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
VStack: 
RStack: 
VdtTable: 0 0 0 0 
lscStack: 
--------------

24:%prim 2 114 r
26:rtnEventQ 0 
28:setThisStack 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = #S#525[loop,loop][]
29:pushthis 

30:rtn D body#SB#539:1092:descInx:539  to: #S#525:1091:descInx:525 
thisObj = #S#525[loop,loop,body#SB#539][]  thisStack = #S#525[loop,loop,body#SB#539][]
19:rpop 
20:pushthis 
21:rpushg 1 #S#525[1]=loop
23:rpushg 1 loop[1]=do
25:rpushg 1 do[1]=%for%to%%do%#S#101
27:pushthis 
28:rpushg 1 #S#525[1]=loop
30:rpushg 1 loop[1]=do
32:rpushg 1 do[1]=%for%to%%do%#S#101
34:pushg 3 %for%to%%do%#S#101[3]=10
36:pushc 1 
38:+ 10 1
39:storeg 3 %for%to%%do%#S#101[3]=11
41:break 1 81 
10:pushthis 
11:rpushg 1 loop[1]=do
13:rpushg 1 do[1]=%for%to%%do%#S#101
15:pushg 3 %for%to%%do%#S#101[3]=11
17:pushthis 
18:rpushg 1 loop[1]=do
20:rpushg 1 do[1]=%for%to%%do%#S#101
22:pushg 2 %for%to%%do%#S#101[2]=18
24:<= 
25:jmpFalse (1)36 
28:pushthis 

29:invoke 525 0 1 #S#525:1093:descInx:525 
thisObj = #S#525[loop,loop][]  thisStack = loop[do,do,loop][]
1:rstore 1 loop->#S#525[1]
3:allocEventQ 0 
5:mvStack 
thisObj = #S#525[loop,loop][]  thisStack = #S#525[loop,loop][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = #S#525[loop,loop][]  thisStack = #S#525[loop,loop][]
10:pushthis 
11:rpushg 1 #S#525[1]=loop
13:rpushg 1 loop[1]=do
15:rpushg 1 do[1]=%for%to%%do%#S#101
thisObj = #S#525[loop,loop,%for%to%%do%#S#101][]  thisStack = #S#525[loop,loop,%for%to%%do%#S#101][]

17:sendv  1 body#SB#539:1094:descInx:539 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = #S#525[loop,loop,%for%to%%do%#S#101][]
1:rstore 2 %for%to%%do%#S#101->body#SB#539[2]
3:allocEventQ 0 
5:mvStack 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = body#SB#539[#S#525,#S#525][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = body#SB#539[#S#525,#S#525][]
10:pushthis 
11:rpushg 2 body#SB#539[2]=%for%to%%do%#S#101
13:rpushg 2 %for%to%%do%#S#101[2]=print
15:rpushg 1 print[1]=String
17:pushthis 
18:rpushg 2 body#SB#539[2]=%for%to%%do%#S#101
20:pushg 3 %for%to%%do%#S#101[3]=11
22:xpushg 1 String[12]=97
xpushg:
Object: String:1067 lsc: 0
VFields: 18 105 110 116 101 103 101 114 65 114 114 97 121 83 116 97 114 116 50 0 
Rfields: (0)LIB:1004 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
VStack: 
RStack: 
VdtTable: 0 0 0 0 
lscStack: 
--------------

24:%prim 2 97 a
26:rtnEventQ 0 
28:setThisStack 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = #S#525[loop,loop][]
29:pushthis 

30:rtn D body#SB#539:1094:descInx:539  to: #S#525:1093:descInx:525 
thisObj = #S#525[loop,loop,body#SB#539][]  thisStack = #S#525[loop,loop,body#SB#539][]
19:rpop 
20:pushthis 
21:rpushg 1 #S#525[1]=loop
23:rpushg 1 loop[1]=do
25:rpushg 1 do[1]=%for%to%%do%#S#101
27:pushthis 
28:rpushg 1 #S#525[1]=loop
30:rpushg 1 loop[1]=do
32:rpushg 1 do[1]=%for%to%%do%#S#101
34:pushg 3 %for%to%%do%#S#101[3]=11
36:pushc 1 
38:+ 11 1
39:storeg 3 %for%to%%do%#S#101[3]=12
41:break 1 81 
10:pushthis 
11:rpushg 1 loop[1]=do
13:rpushg 1 do[1]=%for%to%%do%#S#101
15:pushg 3 %for%to%%do%#S#101[3]=12
17:pushthis 
18:rpushg 1 loop[1]=do
20:rpushg 1 do[1]=%for%to%%do%#S#101
22:pushg 2 %for%to%%do%#S#101[2]=18
24:<= 
25:jmpFalse (1)36 
28:pushthis 

29:invoke 525 0 1 #S#525:1095:descInx:525 
thisObj = #S#525[loop,loop][]  thisStack = loop[do,do,loop][]
1:rstore 1 loop->#S#525[1]
3:allocEventQ 0 
5:mvStack 
thisObj = #S#525[loop,loop][]  thisStack = #S#525[loop,loop][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = #S#525[loop,loop][]  thisStack = #S#525[loop,loop][]
10:pushthis 
11:rpushg 1 #S#525[1]=loop
13:rpushg 1 loop[1]=do
15:rpushg 1 do[1]=%for%to%%do%#S#101
thisObj = #S#525[loop,loop,%for%to%%do%#S#101][]  thisStack = #S#525[loop,loop,%for%to%%do%#S#101][]

17:sendv  1 body#SB#539:1096:descInx:539 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = #S#525[loop,loop,%for%to%%do%#S#101][]
1:rstore 2 %for%to%%do%#S#101->body#SB#539[2]
3:allocEventQ 0 
5:mvStack 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = body#SB#539[#S#525,#S#525][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = body#SB#539[#S#525,#S#525][]
10:pushthis 
11:rpushg 2 body#SB#539[2]=%for%to%%do%#S#101
13:rpushg 2 %for%to%%do%#S#101[2]=print
15:rpushg 1 print[1]=String
17:pushthis 
18:rpushg 2 body#SB#539[2]=%for%to%%do%#S#101
20:pushg 3 %for%to%%do%#S#101[3]=12
22:xpushg 1 String[13]=121
xpushg:
Object: String:1067 lsc: 0
VFields: 18 105 110 116 101 103 101 114 65 114 114 97 121 83 116 97 114 116 50 0 
Rfields: (0)LIB:1004 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
VStack: 
RStack: 
VdtTable: 0 0 0 0 
lscStack: 
--------------

24:%prim 2 121 y
26:rtnEventQ 0 
28:setThisStack 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = #S#525[loop,loop][]
29:pushthis 

30:rtn D body#SB#539:1096:descInx:539  to: #S#525:1095:descInx:525 
thisObj = #S#525[loop,loop,body#SB#539][]  thisStack = #S#525[loop,loop,body#SB#539][]
19:rpop 
20:pushthis 
21:rpushg 1 #S#525[1]=loop
23:rpushg 1 loop[1]=do
25:rpushg 1 do[1]=%for%to%%do%#S#101
27:pushthis 
28:rpushg 1 #S#525[1]=loop
30:rpushg 1 loop[1]=do
32:rpushg 1 do[1]=%for%to%%do%#S#101
34:pushg 3 %for%to%%do%#S#101[3]=12
36:pushc 1 
38:+ 12 1
39:storeg 3 %for%to%%do%#S#101[3]=13
41:break 1 81 
10:pushthis 
11:rpushg 1 loop[1]=do
13:rpushg 1 do[1]=%for%to%%do%#S#101
15:pushg 3 %for%to%%do%#S#101[3]=13
17:pushthis 
18:rpushg 1 loop[1]=do
20:rpushg 1 do[1]=%for%to%%do%#S#101
22:pushg 2 %for%to%%do%#S#101[2]=18
24:<= 
25:jmpFalse (1)36 
28:pushthis 

29:invoke 525 0 1 #S#525:1097:descInx:525 
thisObj = #S#525[loop,loop][]  thisStack = loop[do,do,loop][]
1:rstore 1 loop->#S#525[1]
3:allocEventQ 0 
5:mvStack 
thisObj = #S#525[loop,loop][]  thisStack = #S#525[loop,loop][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = #S#525[loop,loop][]  thisStack = #S#525[loop,loop][]
10:pushthis 
11:rpushg 1 #S#525[1]=loop
13:rpushg 1 loop[1]=do
15:rpushg 1 do[1]=%for%to%%do%#S#101
thisObj = #S#525[loop,loop,%for%to%%do%#S#101][]  thisStack = #S#525[loop,loop,%for%to%%do%#S#101][]

17:sendv  1 body#SB#539:1098:descInx:539 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = #S#525[loop,loop,%for%to%%do%#S#101][]
1:rstore 2 %for%to%%do%#S#101->body#SB#539[2]
3:allocEventQ 0 
5:mvStack 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = body#SB#539[#S#525,#S#525][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = body#SB#539[#S#525,#S#525][]
10:pushthis 
11:rpushg 2 body#SB#539[2]=%for%to%%do%#S#101
13:rpushg 2 %for%to%%do%#S#101[2]=print
15:rpushg 1 print[1]=String
17:pushthis 
18:rpushg 2 body#SB#539[2]=%for%to%%do%#S#101
20:pushg 3 %for%to%%do%#S#101[3]=13
22:xpushg 1 String[14]=83
xpushg:
Object: String:1067 lsc: 0
VFields: 18 105 110 116 101 103 101 114 65 114 114 97 121 83 116 97 114 116 50 0 
Rfields: (0)LIB:1004 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
VStack: 
RStack: 
VdtTable: 0 0 0 0 
lscStack: 
--------------

24:%prim 2 83 S
26:rtnEventQ 0 
28:setThisStack 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = #S#525[loop,loop][]
29:pushthis 

30:rtn D body#SB#539:1098:descInx:539  to: #S#525:1097:descInx:525 
thisObj = #S#525[loop,loop,body#SB#539][]  thisStack = #S#525[loop,loop,body#SB#539][]
19:rpop 
20:pushthis 
21:rpushg 1 #S#525[1]=loop
23:rpushg 1 loop[1]=do
25:rpushg 1 do[1]=%for%to%%do%#S#101
27:pushthis 
28:rpushg 1 #S#525[1]=loop
30:rpushg 1 loop[1]=do
32:rpushg 1 do[1]=%for%to%%do%#S#101
34:pushg 3 %for%to%%do%#S#101[3]=13
36:pushc 1 
38:+ 13 1
39:storeg 3 %for%to%%do%#S#101[3]=14
41:break 1 81 
10:pushthis 
11:rpushg 1 loop[1]=do
13:rpushg 1 do[1]=%for%to%%do%#S#101
15:pushg 3 %for%to%%do%#S#101[3]=14
17:pushthis 
18:rpushg 1 loop[1]=do
20:rpushg 1 do[1]=%for%to%%do%#S#101
22:pushg 2 %for%to%%do%#S#101[2]=18
24:<= 
25:jmpFalse (1)36 
28:pushthis 

29:invoke 525 0 1 #S#525:1099:descInx:525 
thisObj = #S#525[loop,loop][]  thisStack = loop[do,do,loop][]
1:rstore 1 loop->#S#525[1]
3:allocEventQ 0 
5:mvStack 
thisObj = #S#525[loop,loop][]  thisStack = #S#525[loop,loop][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = #S#525[loop,loop][]  thisStack = #S#525[loop,loop][]
10:pushthis 
11:rpushg 1 #S#525[1]=loop
13:rpushg 1 loop[1]=do
15:rpushg 1 do[1]=%for%to%%do%#S#101
thisObj = #S#525[loop,loop,%for%to%%do%#S#101][]  thisStack = #S#525[loop,loop,%for%to%%do%#S#101][]

17:sendv  1 body#SB#539:1100:descInx:539 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = #S#525[loop,loop,%for%to%%do%#S#101][]
1:rstore 2 %for%to%%do%#S#101->body#SB#539[2]
3:allocEventQ 0 
5:mvStack 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = body#SB#539[#S#525,#S#525][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = body#SB#539[#S#525,#S#525][]
10:pushthis 
11:rpushg 2 body#SB#539[2]=%for%to%%do%#S#101
13:rpushg 2 %for%to%%do%#S#101[2]=print
15:rpushg 1 print[1]=String
17:pushthis 
18:rpushg 2 body#SB#539[2]=%for%to%%do%#S#101
20:pushg 3 %for%to%%do%#S#101[3]=14
22:xpushg 1 String[15]=116
xpushg:
Object: String:1067 lsc: 0
VFields: 18 105 110 116 101 103 101 114 65 114 114 97 121 83 116 97 114 116 50 0 
Rfields: (0)LIB:1004 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
VStack: 
RStack: 
VdtTable: 0 0 0 0 
lscStack: 
--------------

24:%prim 2 116 t
26:rtnEventQ 0 
28:setThisStack 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = #S#525[loop,loop][]
29:pushthis 

30:rtn D body#SB#539:1100:descInx:539  to: #S#525:1099:descInx:525 
thisObj = #S#525[loop,loop,body#SB#539][]  thisStack = #S#525[loop,loop,body#SB#539][]
19:rpop 
20:pushthis 
21:rpushg 1 #S#525[1]=loop
23:rpushg 1 loop[1]=do
25:rpushg 1 do[1]=%for%to%%do%#S#101
27:pushthis 
28:rpushg 1 #S#525[1]=loop
30:rpushg 1 loop[1]=do
32:rpushg 1 do[1]=%for%to%%do%#S#101
34:pushg 3 %for%to%%do%#S#101[3]=14
36:pushc 1 
38:+ 14 1
39:storeg 3 %for%to%%do%#S#101[3]=15
41:break 1 81 
10:pushthis 
11:rpushg 1 loop[1]=do
13:rpushg 1 do[1]=%for%to%%do%#S#101
15:pushg 3 %for%to%%do%#S#101[3]=15
17:pushthis 
18:rpushg 1 loop[1]=do
20:rpushg 1 do[1]=%for%to%%do%#S#101
22:pushg 2 %for%to%%do%#S#101[2]=18
24:<= 
25:jmpFalse (1)36 
28:pushthis 

29:invoke 525 0 1 #S#525:1101:descInx:525 
thisObj = #S#525[loop,loop][]  thisStack = loop[do,do,loop][]
1:rstore 1 loop->#S#525[1]
3:allocEventQ 0 
5:mvStack 
thisObj = #S#525[loop,loop][]  thisStack = #S#525[loop,loop][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = #S#525[loop,loop][]  thisStack = #S#525[loop,loop][]
10:pushthis 
11:rpushg 1 #S#525[1]=loop
13:rpushg 1 loop[1]=do
15:rpushg 1 do[1]=%for%to%%do%#S#101
thisObj = #S#525[loop,loop,%for%to%%do%#S#101][]  thisStack = #S#525[loop,loop,%for%to%%do%#S#101][]

17:sendv  1 body#SB#539:1102:descInx:539 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = #S#525[loop,loop,%for%to%%do%#S#101][]
1:rstore 2 %for%to%%do%#S#101->body#SB#539[2]
3:allocEventQ 0 
5:mvStack 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = body#SB#539[#S#525,#S#525][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = body#SB#539[#S#525,#S#525][]
10:pushthis 
11:rpushg 2 body#SB#539[2]=%for%to%%do%#S#101
13:rpushg 2 %for%to%%do%#S#101[2]=print
15:rpushg 1 print[1]=String
17:pushthis 
18:rpushg 2 body#SB#539[2]=%for%to%%do%#S#101
20:pushg 3 %for%to%%do%#S#101[3]=15
22:xpushg 1 String[16]=97
xpushg:
Object: String:1067 lsc: 0
VFields: 18 105 110 116 101 103 101 114 65 114 114 97 121 83 116 97 114 116 50 0 
Rfields: (0)LIB:1004 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
VStack: 
RStack: 
VdtTable: 0 0 0 0 
lscStack: 
--------------

24:%prim 2 97 a
26:rtnEventQ 0 
28:setThisStack 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = #S#525[loop,loop][]
29:pushthis 

30:rtn D body#SB#539:1102:descInx:539  to: #S#525:1101:descInx:525 
thisObj = #S#525[loop,loop,body#SB#539][]  thisStack = #S#525[loop,loop,body#SB#539][]
19:rpop 
20:pushthis 
21:rpushg 1 #S#525[1]=loop
23:rpushg 1 loop[1]=do
25:rpushg 1 do[1]=%for%to%%do%#S#101
27:pushthis 
28:rpushg 1 #S#525[1]=loop
30:rpushg 1 loop[1]=do
32:rpushg 1 do[1]=%for%to%%do%#S#101
34:pushg 3 %for%to%%do%#S#101[3]=15
36:pushc 1 
38:+ 15 1
39:storeg 3 %for%to%%do%#S#101[3]=16
41:break 1 81 
10:pushthis 
11:rpushg 1 loop[1]=do
13:rpushg 1 do[1]=%for%to%%do%#S#101
15:pushg 3 %for%to%%do%#S#101[3]=16
17:pushthis 
18:rpushg 1 loop[1]=do
20:rpushg 1 do[1]=%for%to%%do%#S#101
22:pushg 2 %for%to%%do%#S#101[2]=18
24:<= 
25:jmpFalse (1)36 
28:pushthis 

29:invoke 525 0 1 #S#525:1103:descInx:525 
thisObj = #S#525[loop,loop][]  thisStack = loop[do,do,loop][]
1:rstore 1 loop->#S#525[1]
3:allocEventQ 0 
5:mvStack 
thisObj = #S#525[loop,loop][]  thisStack = #S#525[loop,loop][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = #S#525[loop,loop][]  thisStack = #S#525[loop,loop][]
10:pushthis 
11:rpushg 1 #S#525[1]=loop
13:rpushg 1 loop[1]=do
15:rpushg 1 do[1]=%for%to%%do%#S#101
thisObj = #S#525[loop,loop,%for%to%%do%#S#101][]  thisStack = #S#525[loop,loop,%for%to%%do%#S#101][]

17:sendv  1 body#SB#539:1104:descInx:539 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = #S#525[loop,loop,%for%to%%do%#S#101][]
1:rstore 2 %for%to%%do%#S#101->body#SB#539[2]
3:allocEventQ 0 
5:mvStack 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = body#SB#539[#S#525,#S#525][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = body#SB#539[#S#525,#S#525][]
10:pushthis 
11:rpushg 2 body#SB#539[2]=%for%to%%do%#S#101
13:rpushg 2 %for%to%%do%#S#101[2]=print
15:rpushg 1 print[1]=String
17:pushthis 
18:rpushg 2 body#SB#539[2]=%for%to%%do%#S#101
20:pushg 3 %for%to%%do%#S#101[3]=16
22:xpushg 1 String[17]=114
xpushg:
Object: String:1067 lsc: 0
VFields: 18 105 110 116 101 103 101 114 65 114 114 97 121 83 116 97 114 116 50 0 
Rfields: (0)LIB:1004 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
VStack: 
RStack: 
VdtTable: 0 0 0 0 
lscStack: 
--------------

24:%prim 2 114 r
26:rtnEventQ 0 
28:setThisStack 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = #S#525[loop,loop][]
29:pushthis 

30:rtn D body#SB#539:1104:descInx:539  to: #S#525:1103:descInx:525 
thisObj = #S#525[loop,loop,body#SB#539][]  thisStack = #S#525[loop,loop,body#SB#539][]
19:rpop 
20:pushthis 
21:rpushg 1 #S#525[1]=loop
23:rpushg 1 loop[1]=do
25:rpushg 1 do[1]=%for%to%%do%#S#101
27:pushthis 
28:rpushg 1 #S#525[1]=loop
30:rpushg 1 loop[1]=do
32:rpushg 1 do[1]=%for%to%%do%#S#101
34:pushg 3 %for%to%%do%#S#101[3]=16
36:pushc 1 
38:+ 16 1
39:storeg 3 %for%to%%do%#S#101[3]=17
41:break 1 81 
10:pushthis 
11:rpushg 1 loop[1]=do
13:rpushg 1 do[1]=%for%to%%do%#S#101
15:pushg 3 %for%to%%do%#S#101[3]=17
17:pushthis 
18:rpushg 1 loop[1]=do
20:rpushg 1 do[1]=%for%to%%do%#S#101
22:pushg 2 %for%to%%do%#S#101[2]=18
24:<= 
25:jmpFalse (1)36 
28:pushthis 

29:invoke 525 0 1 #S#525:1105:descInx:525 
thisObj = #S#525[loop,loop][]  thisStack = loop[do,do,loop][]
1:rstore 1 loop->#S#525[1]
3:allocEventQ 0 
5:mvStack 
thisObj = #S#525[loop,loop][]  thisStack = #S#525[loop,loop][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = #S#525[loop,loop][]  thisStack = #S#525[loop,loop][]
10:pushthis 
11:rpushg 1 #S#525[1]=loop
13:rpushg 1 loop[1]=do
15:rpushg 1 do[1]=%for%to%%do%#S#101
thisObj = #S#525[loop,loop,%for%to%%do%#S#101][]  thisStack = #S#525[loop,loop,%for%to%%do%#S#101][]

17:sendv  1 body#SB#539:1106:descInx:539 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = #S#525[loop,loop,%for%to%%do%#S#101][]
1:rstore 2 %for%to%%do%#S#101->body#SB#539[2]
3:allocEventQ 0 
5:mvStack 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = body#SB#539[#S#525,#S#525][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = body#SB#539[#S#525,#S#525][]
10:pushthis 
11:rpushg 2 body#SB#539[2]=%for%to%%do%#S#101
13:rpushg 2 %for%to%%do%#S#101[2]=print
15:rpushg 1 print[1]=String
17:pushthis 
18:rpushg 2 body#SB#539[2]=%for%to%%do%#S#101
20:pushg 3 %for%to%%do%#S#101[3]=17
22:xpushg 1 String[18]=116
xpushg:
Object: String:1067 lsc: 0
VFields: 18 105 110 116 101 103 101 114 65 114 114 97 121 83 116 97 114 116 50 0 
Rfields: (0)LIB:1004 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
VStack: 
RStack: 
VdtTable: 0 0 0 0 
lscStack: 
--------------

24:%prim 2 116 t
26:rtnEventQ 0 
28:setThisStack 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = #S#525[loop,loop][]
29:pushthis 

30:rtn D body#SB#539:1106:descInx:539  to: #S#525:1105:descInx:525 
thisObj = #S#525[loop,loop,body#SB#539][]  thisStack = #S#525[loop,loop,body#SB#539][]
19:rpop 
20:pushthis 
21:rpushg 1 #S#525[1]=loop
23:rpushg 1 loop[1]=do
25:rpushg 1 do[1]=%for%to%%do%#S#101
27:pushthis 
28:rpushg 1 #S#525[1]=loop
30:rpushg 1 loop[1]=do
32:rpushg 1 do[1]=%for%to%%do%#S#101
34:pushg 3 %for%to%%do%#S#101[3]=17
36:pushc 1 
38:+ 17 1
39:storeg 3 %for%to%%do%#S#101[3]=18
41:break 1 81 
10:pushthis 
11:rpushg 1 loop[1]=do
13:rpushg 1 do[1]=%for%to%%do%#S#101
15:pushg 3 %for%to%%do%#S#101[3]=18
17:pushthis 
18:rpushg 1 loop[1]=do
20:rpushg 1 do[1]=%for%to%%do%#S#101
22:pushg 2 %for%to%%do%#S#101[2]=18
24:<= 
25:jmpFalse (1)36 
28:pushthis 

29:invoke 525 0 1 #S#525:1107:descInx:525 
thisObj = #S#525[loop,loop][]  thisStack = loop[do,do,loop][]
1:rstore 1 loop->#S#525[1]
3:allocEventQ 0 
5:mvStack 
thisObj = #S#525[loop,loop][]  thisStack = #S#525[loop,loop][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = #S#525[loop,loop][]  thisStack = #S#525[loop,loop][]
10:pushthis 
11:rpushg 1 #S#525[1]=loop
13:rpushg 1 loop[1]=do
15:rpushg 1 do[1]=%for%to%%do%#S#101
thisObj = #S#525[loop,loop,%for%to%%do%#S#101][]  thisStack = #S#525[loop,loop,%for%to%%do%#S#101][]

17:sendv  1 body#SB#539:1108:descInx:539 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = #S#525[loop,loop,%for%to%%do%#S#101][]
1:rstore 2 %for%to%%do%#S#101->body#SB#539[2]
3:allocEventQ 0 
5:mvStack 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = body#SB#539[#S#525,#S#525][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = body#SB#539[#S#525,#S#525][]
10:pushthis 
11:rpushg 2 body#SB#539[2]=%for%to%%do%#S#101
13:rpushg 2 %for%to%%do%#S#101[2]=print
15:rpushg 1 print[1]=String
17:pushthis 
18:rpushg 2 body#SB#539[2]=%for%to%%do%#S#101
20:pushg 3 %for%to%%do%#S#101[3]=18
22:xpushg 1 String[19]=50
xpushg:
Object: String:1067 lsc: 0
VFields: 18 105 110 116 101 103 101 114 65 114 114 97 121 83 116 97 114 116 50 0 
Rfields: (0)LIB:1004 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
VStack: 
RStack: 
VdtTable: 0 0 0 0 
lscStack: 
--------------

24:%prim 2 50 2
26:rtnEventQ 0 
28:setThisStack 
thisObj = body#SB#539[#S#525,#S#525][]  thisStack = #S#525[loop,loop][]
29:pushthis 

30:rtn D body#SB#539:1108:descInx:539  to: #S#525:1107:descInx:525 
thisObj = #S#525[loop,loop,body#SB#539][]  thisStack = #S#525[loop,loop,body#SB#539][]
19:rpop 
20:pushthis 
21:rpushg 1 #S#525[1]=loop
23:rpushg 1 loop[1]=do
25:rpushg 1 do[1]=%for%to%%do%#S#101
27:pushthis 
28:rpushg 1 #S#525[1]=loop
30:rpushg 1 loop[1]=do
32:rpushg 1 do[1]=%for%to%%do%#S#101
34:pushg 3 %for%to%%do%#S#101[3]=18
36:pushc 1 
38:+ 18 1
39:storeg 3 %for%to%%do%#S#101[3]=19
41:break 1 81 
10:pushthis 
11:rpushg 1 loop[1]=do
13:rpushg 1 do[1]=%for%to%%do%#S#101
15:pushg 3 %for%to%%do%#S#101[3]=19
17:pushthis 
18:rpushg 1 loop[1]=do
20:rpushg 1 do[1]=%for%to%%do%#S#101
22:pushg 2 %for%to%%do%#S#101[2]=18
24:<= 
25:jmpFalse (0)36 
36:rtnEventQ 0 
38:setThisStack 
thisObj = loop[do,do][]  thisStack = do[%for%to%%do%#S#101,%for%to%%do%#S#101][]
39:pushthis 

40:rtn D loop:1072:descInx:65  to: do:1071:descInx:64 
thisObj = do[%for%to%%do%#S#101,%for%to%%do%#S#101,loop][]  thisStack = do[%for%to%%do%#S#101,%for%to%%do%#S#101,loop][]
13:rpop 
14:rtnEventQ 0 
16:mvStack 
thisObj = do[%for%to%%do%#S#101,%for%to%%do%#S#101][]  thisStack = do[%for%to%%do%#S#101,%for%to%%do%#S#101][]
17:rtnEventQ 0 
19:setThisStack 
thisObj = do[%for%to%%do%#S#101,%for%to%%do%#S#101][]  thisStack = %for%to%%do%#S#101[print,print][]
20:pushthis 

21:rtn D do:1071:descInx:64  to: %for%to%%do%#S#101:1069:descInx:101 
thisObj = %for%to%%do%#S#101[print,print,do][]  thisStack = %for%to%%do%#S#101[print,print,do][]
29:rpop 
30:rtnEventQ 0 
32:setThisStack 
thisObj = %for%to%%do%#S#101[print,print][]  thisStack = print[(0)List,(0)List][]
33:pushthis 

34:rtn D %for%to%%do%#S#101:1069:descInx:101  to: print:1068:descInx:100 
thisObj = print[(0)List,(0)List,%for%to%%do%#S#101][]  thisStack = print[(0)List,(0)List,%for%to%%do%#S#101][]
17:rpop 
18:rtnEventQ 0 
20:setThisStack 
thisObj = print[(0)List,(0)List][]  thisStack = (0)List[(0)ArrayDemos,(0)ArrayDemos][]
21:pushthis 

22:rtn D print:1068:descInx:100  to: (0)List:1016:descInx:434 
thisObj = (0)List[(0)ArrayDemos,(0)ArrayDemos,print][]  thisStack = (0)List[(0)ArrayDemos,(0)ArrayDemos,print][]
125:rpop 
126:pushthis 
127:rpushg 1 (0)List[1]=(0)ArrayDemos
129:rpushg 1 (0)ArrayDemos[1]=(0)demo
131:rpushg 1 (0)demo[1]=(0)workspace

133:invoke 66 0 0 newline:1109:descInx:66 
thisObj = newline[(0)List,(0)List][]  thisStack = (0)List[(0)ArrayDemos,(0)ArrayDemos,(0)workspace][]
1:rstore 1 (0)workspace->newline[1]
3:allocEventQ 0 
5:mvStack 
thisObj = newline[(0)List,(0)List][]  thisStack = newline[(0)List,(0)List][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = newline[(0)List,(0)List][]  thisStack = newline[(0)List,(0)List][]
10:pushc 10 
12:%prim 2 10 

14:rtnEventQ 0 
16:setThisStack 
thisObj = newline[(0)List,(0)List][]  thisStack = (0)List[(0)ArrayDemos,(0)ArrayDemos][]
17:pushthis 

18:rtn D newline:1109:descInx:66  to: (0)List:1016:descInx:434 
thisObj = (0)List[(0)ArrayDemos,(0)ArrayDemos,newline][]  thisStack = (0)List[(0)ArrayDemos,(0)ArrayDemos,newline][]
139:rpop 
140:pushthis 
141:rpushg 6 (0)List[6]=Range
143:rpushg 2 Range[2]=Indexed
145:pushc 2 
147:pushc 1 
149:xstoreg 1 Indexed[2]=2
xstoreg:
Object: Indexed:1061 lsc: 0
VFields: 2 2 0 
Rfields: * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
VStack: 
RStack: 
VdtTable: 0 0 0 0 
lscStack: 
--------------

151:pushthis 
152:rpushg 6 (0)List[6]=Range
154:rpushg 2 Range[2]=Indexed
156:pushc 3 
158:pushc 2 
160:xstoreg 1 Indexed[3]=3
xstoreg:
Object: Indexed:1061 lsc: 0
VFields: 2 2 3 
Rfields: * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
VStack: 
RStack: 
VdtTable: 0 0 0 0 
lscStack: 
--------------

162:pushthis 
163:rpushg 7 (0)List[7]=Range
165:rpushg 2 Range[2]=Indexed
167:pushc 4 
169:pushc 1 
171:xstoreg 1 Indexed[2]=4
xstoreg:
Object: Indexed:1063 lsc: 0
VFields: 2 4 0 
Rfields: * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
VStack: 
RStack: 
VdtTable: 0 0 0 0 
lscStack: 
--------------

173:pushthis 
174:rpushg 7 (0)List[7]=Range
176:rpushg 2 Range[2]=Indexed
178:pushc 5 
180:pushc 2 
182:xstoreg 1 Indexed[3]=5
xstoreg:
Object: Indexed:1063 lsc: 0
VFields: 2 4 5 
Rfields: * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
VStack: 
RStack: 
VdtTable: 0 0 0 0 
lscStack: 
--------------

184:pushthis 
185:rpushg 1 (0)List[1]=(0)ArrayDemos
187:rpushg 1 (0)ArrayDemos[1]=(0)demo
189:rpushg 1 (0)demo[1]=(0)workspace
191:pushthis 
192:rpushg 6 (0)List[6]=Range
194:rpushg 2 Range[2]=Indexed
196:pushc 1 
198:xpushg 1 Indexed[2]=2
xpushg:
Object: Indexed:1061 lsc: 0
VFields: 2 2 3 
Rfields: * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
VStack: 
RStack: 
VdtTable: 0 0 0 0 
lscStack: 
--------------


200:invoke 67 0 0 putint:1110:descInx:67 
thisObj = putint[(0)List,(0)List][]  thisStack = (0)List[(0)ArrayDemos,(0)ArrayDemos,(0)workspace][2]
1:pushthis 
2:storeg 1 putint[1]=2
4:rstore 1 (0)workspace->putint[1]
6:allocEventQ 0 
8:mvStack 
thisObj = putint[(0)List,(0)List][]  thisStack = putint[(0)List,(0)List][]
9:pushthis 
10:rpushg 1 putint[1]=(0)workspace
12:pushc 20 
14:pushc 0 
16:pushc 1 

18:allocIndexed 52 1 
AllocQ_indexed:
Object: Indexed:1111 lsc: 0
VFields: 20 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
Rfields: * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
VStack: 
RStack: 
VdtTable: 0 0 0 0 
lscStack: 
--------------

22:pushthis 
23:rstoreg 2 putint[2]=Indexed
25:rtnEventQ 1 
27:doEventQ 
28:mvStack 
thisObj = putint[(0)List,(0)List][]  thisStack = putint[(0)List,(0)List][]
29:pushthis 
30:pushthis 
31:pushg 1 putint[1]=2
33:pushc 0 
35:< 2<0
36:storeg 3 putint[3]=0
38:pushthis 
39:pushg 3 putint[3]=0
41:jmpFalse (0)53 
53:pushthis 

54:invoke 68 0 0 doit:1112:descInx:68 
thisObj = doit[putint,putint][]  thisStack = putint[(0)List,(0)List,putint][]
1:rstore 1 putint->doit[1]
3:allocEventQ 0 
5:mvStack 
thisObj = doit[putint,putint][]  thisStack = doit[putint,putint][]
6:pushthis 

7:invoke 69 2 1 loop:1113:descInx:69 
thisObj = loop[doit,doit][]  thisStack = doit[putint,putint,doit][]
1:rstore 1 doit->loop[1]
3:allocEventQ 0 
5:mvStack 
thisObj = loop[doit,doit][]  thisStack = loop[doit,doit][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = loop[doit,doit][]  thisStack = loop[doit,doit][]
10:pushthis 
11:rpushg 1 loop[1]=doit
13:rpushg 1 doit[1]=putint
15:pushthis 
16:rpushg 1 loop[1]=doit
18:rpushg 1 doit[1]=putint
20:pushg 2 putint[2]=0
22:pushc 1 
24:+ 0 1
25:storeg 2 putint[2]=1
27:pushthis 
28:rpushg 1 loop[1]=doit
30:rpushg 1 doit[1]=putint
32:rpushg 2 putint[2]=Indexed
34:pushthis 
35:rpushg 1 loop[1]=doit
37:rpushg 1 doit[1]=putint
39:pushg 1 putint[1]=2
41:pushc 10 
43:mod 
44:pushthis 
45:rpushg 1 loop[1]=doit
47:rpushg 1 doit[1]=putint
49:pushg 2 putint[2]=1
51:xstoreg 1 Indexed[2]=2
xstoreg:
Object: Indexed:1111 lsc: 0
VFields: 20 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
Rfields: * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
VStack: 
RStack: 
VdtTable: 0 0 0 0 
lscStack: 
--------------

53:pushthis 
54:rpushg 1 loop[1]=doit
56:rpushg 1 doit[1]=putint
58:pushthis 
59:rpushg 1 loop[1]=doit
61:rpushg 1 doit[1]=putint
63:pushg 1 putint[1]=2
65:pushc 10 
67:div 
68:storeg 1 putint[1]=0
70:pushthis 
71:rpushg 1 loop[1]=doit
73:rpushg 1 doit[1]=putint
75:pushg 1 putint[1]=0
77:pushc 0 
79:> 0>0
80:jmpFalse (0)91 
91:rtnEventQ 0 
93:setThisStack 
thisObj = loop[doit,doit][]  thisStack = doit[putint,putint][]
94:pushthis 

95:rtn D loop:1113:descInx:69  to: doit:1112:descInx:68 
thisObj = doit[putint,putint,loop][]  thisStack = doit[putint,putint,loop][]
13:rpop 
14:rtnEventQ 1 
16:doEventQ 
17:mvStack 
thisObj = doit[putint,putint][]  thisStack = doit[putint,putint][]
18:pushthis 
19:rpushg 1 doit[1]=putint
21:pushg 3 putint[3]=0
23:jmpFalse (0)30 
30:pushthis 

31:invoke 70 0 1 %for%to%%do%#S#70:1114:descInx:70 
thisObj = %for%to%%do%#S#70[doit,doit][]  thisStack = doit[putint,putint,doit][]
1:rstore 2 doit->%for%to%%do%#S#70[2]
3:allocEventQ 1 
5:pushthis 
6:rpushg 2 %for%to%%do%#S#70[2]=doit
8:rpushg 1 doit[1]=putint
10:rpushg 1 putint[1]=(0)workspace
12:pushc 1 
14:pushthis 
15:rpushg 2 %for%to%%do%#S#70[2]=doit
17:rpushg 1 doit[1]=putint
19:pushg 2 putint[2]=1
21:toSuper 63 63 glsc: 1
1:pushthis 
2:storeg 2 %for%to%%do%#S#70[2]=1
4:pushthis 
5:storeg 1 %for%to%%do%#S#70[1]=1
7:rstore 1 (0)workspace->%for%to%%do%#S#70[1]
9:allocEventQ 0 
11:mvStack 
thisObj = %for%to%%do%#S#70[doit,doit][]  thisStack = %for%to%%do%#S#70[doit,doit][]
12:rtnEventQ 1 
14:doEventQ 
15:mvStack 
thisObj = %for%to%%do%#S#70[doit,doit][]  thisStack = %for%to%%do%#S#70[doit,doit][]
16:pushthis 
17:pushthis 
18:pushg 1 %for%to%%do%#S#70[1]=1
20:storeg 3 %for%to%%do%#S#70[3]=1
22:pushthis 

23:invoke 64 0 1 do:1115:descInx:64 
thisObj = do[%for%to%%do%#S#70,%for%to%%do%#S#70][]  thisStack = %for%to%%do%#S#70[doit,doit,%for%to%%do%#S#70][]
1:rstore 1 %for%to%%do%#S#70->do[1]
3:allocEventQ 1 
5:mvStack 
thisObj = do[%for%to%%do%#S#70,%for%to%%do%#S#70][]  thisStack = do[%for%to%%do%#S#70,%for%to%%do%#S#70][]
6:pushthis 

7:invoke 65 2 1 loop:1116:descInx:65 
thisObj = loop[do,do][]  thisStack = do[%for%to%%do%#S#70,%for%to%%do%#S#70,do][]
1:rstore 1 do->loop[1]
3:allocEventQ 0 
5:mvStack 
thisObj = loop[do,do][]  thisStack = loop[do,do][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = loop[do,do][]  thisStack = loop[do,do][]
10:pushthis 
11:rpushg 1 loop[1]=do
13:rpushg 1 do[1]=%for%to%%do%#S#70
15:pushg 3 %for%to%%do%#S#70[3]=1
17:pushthis 
18:rpushg 1 loop[1]=do
20:rpushg 1 do[1]=%for%to%%do%#S#70
22:pushg 2 %for%to%%do%#S#70[2]=1
24:<= 
25:jmpFalse (1)36 
28:pushthis 

29:invoke 525 0 1 #S#525:1117:descInx:525 
thisObj = #S#525[loop,loop][]  thisStack = loop[do,do,loop][]
1:rstore 1 loop->#S#525[1]
3:allocEventQ 0 
5:mvStack 
thisObj = #S#525[loop,loop][]  thisStack = #S#525[loop,loop][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = #S#525[loop,loop][]  thisStack = #S#525[loop,loop][]
10:pushthis 
11:rpushg 1 #S#525[1]=loop
13:rpushg 1 loop[1]=do
15:rpushg 1 do[1]=%for%to%%do%#S#70
thisObj = #S#525[loop,loop,%for%to%%do%#S#70][]  thisStack = #S#525[loop,loop,%for%to%%do%#S#70][]

17:sendv  1 body#SB#527:1118:descInx:527 
thisObj = body#SB#527[#S#525,#S#525][]  thisStack = #S#525[loop,loop,%for%to%%do%#S#70][]
1:rstore 2 %for%to%%do%#S#70->body#SB#527[2]
3:allocEventQ 0 
5:mvStack 
thisObj = body#SB#527[#S#525,#S#525][]  thisStack = body#SB#527[#S#525,#S#525][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = body#SB#527[#S#525,#S#525][]  thisStack = body#SB#527[#S#525,#S#525][]
10:pushthis 
11:pushthis 
12:rpushg 2 body#SB#527[2]=%for%to%%do%#S#70
14:rpushg 2 %for%to%%do%#S#70[2]=doit
16:rpushg 1 doit[1]=putint
18:pushg 2 putint[2]=1
20:pushc 1 
22:pushthis 
23:rpushg 2 body#SB#527[2]=%for%to%%do%#S#70
25:pushg 3 %for%to%%do%#S#70[3]=1
27:- 1 1
28:+ 1 0
29:storeg 1 body#SB#527[1]=1
31:pushc 48 
33:pushthis 
34:rpushg 2 body#SB#527[2]=%for%to%%do%#S#70
36:rpushg 2 %for%to%%do%#S#70[2]=doit
38:rpushg 1 doit[1]=putint
40:rpushg 2 putint[2]=Indexed
42:pushthis 
43:pushg 1 body#SB#527[1]=1
45:xpushg 1 Indexed[2]=2
xpushg:
Object: Indexed:1111 lsc: 0
VFields: 20 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
Rfields: * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
VStack: 
RStack: 
VdtTable: 0 0 0 0 
lscStack: 
--------------

47:+ 48 2
48:%prim 2 50 2
50:rtnEventQ 0 
52:setThisStack 
thisObj = body#SB#527[#S#525,#S#525][]  thisStack = #S#525[loop,loop][]
53:pushthis 

54:rtn D body#SB#527:1118:descInx:527  to: #S#525:1117:descInx:525 
thisObj = #S#525[loop,loop,body#SB#527][]  thisStack = #S#525[loop,loop,body#SB#527][]
19:rpop 
20:pushthis 
21:rpushg 1 #S#525[1]=loop
23:rpushg 1 loop[1]=do
25:rpushg 1 do[1]=%for%to%%do%#S#70
27:pushthis 
28:rpushg 1 #S#525[1]=loop
30:rpushg 1 loop[1]=do
32:rpushg 1 do[1]=%for%to%%do%#S#70
34:pushg 3 %for%to%%do%#S#70[3]=1
36:pushc 1 
38:+ 1 1
39:storeg 3 %for%to%%do%#S#70[3]=2
41:break 1 81 
10:pushthis 
11:rpushg 1 loop[1]=do
13:rpushg 1 do[1]=%for%to%%do%#S#70
15:pushg 3 %for%to%%do%#S#70[3]=2
17:pushthis 
18:rpushg 1 loop[1]=do
20:rpushg 1 do[1]=%for%to%%do%#S#70
22:pushg 2 %for%to%%do%#S#70[2]=1
24:<= 
25:jmpFalse (0)36 
36:rtnEventQ 0 
38:setThisStack 
thisObj = loop[do,do][]  thisStack = do[%for%to%%do%#S#70,%for%to%%do%#S#70][]
39:pushthis 

40:rtn D loop:1116:descInx:65  to: do:1115:descInx:64 
thisObj = do[%for%to%%do%#S#70,%for%to%%do%#S#70,loop][]  thisStack = do[%for%to%%do%#S#70,%for%to%%do%#S#70,loop][]
13:rpop 
14:rtnEventQ 0 
16:mvStack 
thisObj = do[%for%to%%do%#S#70,%for%to%%do%#S#70][]  thisStack = do[%for%to%%do%#S#70,%for%to%%do%#S#70][]
17:rtnEventQ 0 
19:setThisStack 
thisObj = do[%for%to%%do%#S#70,%for%to%%do%#S#70][]  thisStack = %for%to%%do%#S#70[doit,doit][]
20:pushthis 

21:rtn D do:1115:descInx:64  to: %for%to%%do%#S#70:1114:descInx:70 
thisObj = %for%to%%do%#S#70[doit,doit,do][]  thisStack = %for%to%%do%#S#70[doit,doit,do][]
29:rpop 
30:rtnEventQ 0 
32:setThisStack 
thisObj = %for%to%%do%#S#70[doit,doit][]  thisStack = doit[putint,putint][]
33:pushthis 

34:rtn D %for%to%%do%#S#70:1114:descInx:70  to: doit:1112:descInx:68 
thisObj = doit[putint,putint,%for%to%%do%#S#70][]  thisStack = doit[putint,putint,%for%to%%do%#S#70][]
37:rpop 
38:rtnEventQ 0 
40:setThisStack 
thisObj = doit[putint,putint][]  thisStack = putint[(0)List,(0)List][]
41:pushthis 

42:rtn D doit:1112:descInx:68  to: putint:1110:descInx:67 
thisObj = putint[(0)List,(0)List,doit][]  thisStack = putint[(0)List,(0)List,doit][]
60:rpop 
61:rtnEventQ 0 
63:setThisStack 
thisObj = putint[(0)List,(0)List][]  thisStack = (0)List[(0)ArrayDemos,(0)ArrayDemos][]
64:pushthis 

65:rtn D putint:1110:descInx:67  to: (0)List:1016:descInx:434 
thisObj = (0)List[(0)ArrayDemos,(0)ArrayDemos,putint][]  thisStack = (0)List[(0)ArrayDemos,(0)ArrayDemos,putint][]
206:rpop 
207:pushthis 
208:rpushg 1 (0)List[1]=(0)ArrayDemos
210:rpushg 1 (0)ArrayDemos[1]=(0)demo
212:rpushg 1 (0)demo[1]=(0)workspace
214:pushthis 
215:rpushg 6 (0)List[6]=Range
217:rpushg 2 Range[2]=Indexed
219:pushc 2 
221:xpushg 1 Indexed[3]=3
xpushg:
Object: Indexed:1061 lsc: 0
VFields: 2 2 3 
Rfields: * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
VStack: 
RStack: 
VdtTable: 0 0 0 0 
lscStack: 
--------------


223:invoke 67 0 0 putint:1119:descInx:67 
thisObj = putint[(0)List,(0)List][]  thisStack = (0)List[(0)ArrayDemos,(0)ArrayDemos,(0)workspace][3]
1:pushthis 
2:storeg 1 putint[1]=3
4:rstore 1 (0)workspace->putint[1]
6:allocEventQ 0 
8:mvStack 
thisObj = putint[(0)List,(0)List][]  thisStack = putint[(0)List,(0)List][]
9:pushthis 
10:rpushg 1 putint[1]=(0)workspace
12:pushc 20 
14:pushc 0 
16:pushc 1 

18:allocIndexed 52 1 
AllocQ_indexed:
Object: Indexed:1120 lsc: 0
VFields: 20 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
Rfields: * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
VStack: 
RStack: 
VdtTable: 0 0 0 0 
lscStack: 
--------------

22:pushthis 
23:rstoreg 2 putint[2]=Indexed
25:rtnEventQ 1 
27:doEventQ 
28:mvStack 
thisObj = putint[(0)List,(0)List][]  thisStack = putint[(0)List,(0)List][]
29:pushthis 
30:pushthis 
31:pushg 1 putint[1]=3
33:pushc 0 
35:< 3<0
36:storeg 3 putint[3]=0
38:pushthis 
39:pushg 3 putint[3]=0
41:jmpFalse (0)53 
53:pushthis 

54:invoke 68 0 0 doit:1121:descInx:68 
thisObj = doit[putint,putint][]  thisStack = putint[(0)List,(0)List,putint][]
1:rstore 1 putint->doit[1]
3:allocEventQ 0 
5:mvStack 
thisObj = doit[putint,putint][]  thisStack = doit[putint,putint][]
6:pushthis 

7:invoke 69 2 1 loop:1122:descInx:69 
thisObj = loop[doit,doit][]  thisStack = doit[putint,putint,doit][]
1:rstore 1 doit->loop[1]
3:allocEventQ 0 
5:mvStack 
thisObj = loop[doit,doit][]  thisStack = loop[doit,doit][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = loop[doit,doit][]  thisStack = loop[doit,doit][]
10:pushthis 
11:rpushg 1 loop[1]=doit
13:rpushg 1 doit[1]=putint
15:pushthis 
16:rpushg 1 loop[1]=doit
18:rpushg 1 doit[1]=putint
20:pushg 2 putint[2]=0
22:pushc 1 
24:+ 0 1
25:storeg 2 putint[2]=1
27:pushthis 
28:rpushg 1 loop[1]=doit
30:rpushg 1 doit[1]=putint
32:rpushg 2 putint[2]=Indexed
34:pushthis 
35:rpushg 1 loop[1]=doit
37:rpushg 1 doit[1]=putint
39:pushg 1 putint[1]=3
41:pushc 10 
43:mod 
44:pushthis 
45:rpushg 1 loop[1]=doit
47:rpushg 1 doit[1]=putint
49:pushg 2 putint[2]=1
51:xstoreg 1 Indexed[2]=3
xstoreg:
Object: Indexed:1120 lsc: 0
VFields: 20 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
Rfields: * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
VStack: 
RStack: 
VdtTable: 0 0 0 0 
lscStack: 
--------------

53:pushthis 
54:rpushg 1 loop[1]=doit
56:rpushg 1 doit[1]=putint
58:pushthis 
59:rpushg 1 loop[1]=doit
61:rpushg 1 doit[1]=putint
63:pushg 1 putint[1]=3
65:pushc 10 
67:div 
68:storeg 1 putint[1]=0
70:pushthis 
71:rpushg 1 loop[1]=doit
73:rpushg 1 doit[1]=putint
75:pushg 1 putint[1]=0
77:pushc 0 
79:> 0>0
80:jmpFalse (0)91 
91:rtnEventQ 0 
93:setThisStack 
thisObj = loop[doit,doit][]  thisStack = doit[putint,putint][]
94:pushthis 

95:rtn D loop:1122:descInx:69  to: doit:1121:descInx:68 
thisObj = doit[putint,putint,loop][]  thisStack = doit[putint,putint,loop][]
13:rpop 
14:rtnEventQ 1 
16:doEventQ 
17:mvStack 
thisObj = doit[putint,putint][]  thisStack = doit[putint,putint][]
18:pushthis 
19:rpushg 1 doit[1]=putint
21:pushg 3 putint[3]=0
23:jmpFalse (0)30 
30:pushthis 

31:invoke 70 0 1 %for%to%%do%#S#70:1123:descInx:70 
thisObj = %for%to%%do%#S#70[doit,doit][]  thisStack = doit[putint,putint,doit][]
1:rstore 2 doit->%for%to%%do%#S#70[2]
3:allocEventQ 1 
5:pushthis 
6:rpushg 2 %for%to%%do%#S#70[2]=doit
8:rpushg 1 doit[1]=putint
10:rpushg 1 putint[1]=(0)workspace
12:pushc 1 
14:pushthis 
15:rpushg 2 %for%to%%do%#S#70[2]=doit
17:rpushg 1 doit[1]=putint
19:pushg 2 putint[2]=1
21:toSuper 63 63 glsc: 1
1:pushthis 
2:storeg 2 %for%to%%do%#S#70[2]=1
4:pushthis 
5:storeg 1 %for%to%%do%#S#70[1]=1
7:rstore 1 (0)workspace->%for%to%%do%#S#70[1]
9:allocEventQ 0 
11:mvStack 
thisObj = %for%to%%do%#S#70[doit,doit][]  thisStack = %for%to%%do%#S#70[doit,doit][]
12:rtnEventQ 1 
14:doEventQ 
15:mvStack 
thisObj = %for%to%%do%#S#70[doit,doit][]  thisStack = %for%to%%do%#S#70[doit,doit][]
16:pushthis 
17:pushthis 
18:pushg 1 %for%to%%do%#S#70[1]=1
20:storeg 3 %for%to%%do%#S#70[3]=1
22:pushthis 

23:invoke 64 0 1 do:1124:descInx:64 
thisObj = do[%for%to%%do%#S#70,%for%to%%do%#S#70][]  thisStack = %for%to%%do%#S#70[doit,doit,%for%to%%do%#S#70][]
1:rstore 1 %for%to%%do%#S#70->do[1]
3:allocEventQ 1 
5:mvStack 
thisObj = do[%for%to%%do%#S#70,%for%to%%do%#S#70][]  thisStack = do[%for%to%%do%#S#70,%for%to%%do%#S#70][]
6:pushthis 

7:invoke 65 2 1 loop:1125:descInx:65 
thisObj = loop[do,do][]  thisStack = do[%for%to%%do%#S#70,%for%to%%do%#S#70,do][]
1:rstore 1 do->loop[1]
3:allocEventQ 0 
5:mvStack 
thisObj = loop[do,do][]  thisStack = loop[do,do][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = loop[do,do][]  thisStack = loop[do,do][]
10:pushthis 
11:rpushg 1 loop[1]=do
13:rpushg 1 do[1]=%for%to%%do%#S#70
15:pushg 3 %for%to%%do%#S#70[3]=1
17:pushthis 
18:rpushg 1 loop[1]=do
20:rpushg 1 do[1]=%for%to%%do%#S#70
22:pushg 2 %for%to%%do%#S#70[2]=1
24:<= 
25:jmpFalse (1)36 
28:pushthis 

29:invoke 525 0 1 #S#525:1126:descInx:525 
thisObj = #S#525[loop,loop][]  thisStack = loop[do,do,loop][]
1:rstore 1 loop->#S#525[1]
3:allocEventQ 0 
5:mvStack 
thisObj = #S#525[loop,loop][]  thisStack = #S#525[loop,loop][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = #S#525[loop,loop][]  thisStack = #S#525[loop,loop][]
10:pushthis 
11:rpushg 1 #S#525[1]=loop
13:rpushg 1 loop[1]=do
15:rpushg 1 do[1]=%for%to%%do%#S#70
thisObj = #S#525[loop,loop,%for%to%%do%#S#70][]  thisStack = #S#525[loop,loop,%for%to%%do%#S#70][]

17:sendv  1 body#SB#527:1127:descInx:527 
thisObj = body#SB#527[#S#525,#S#525][]  thisStack = #S#525[loop,loop,%for%to%%do%#S#70][]
1:rstore 2 %for%to%%do%#S#70->body#SB#527[2]
3:allocEventQ 0 
5:mvStack 
thisObj = body#SB#527[#S#525,#S#525][]  thisStack = body#SB#527[#S#525,#S#525][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = body#SB#527[#S#525,#S#525][]  thisStack = body#SB#527[#S#525,#S#525][]
10:pushthis 
11:pushthis 
12:rpushg 2 body#SB#527[2]=%for%to%%do%#S#70
14:rpushg 2 %for%to%%do%#S#70[2]=doit
16:rpushg 1 doit[1]=putint
18:pushg 2 putint[2]=1
20:pushc 1 
22:pushthis 
23:rpushg 2 body#SB#527[2]=%for%to%%do%#S#70
25:pushg 3 %for%to%%do%#S#70[3]=1
27:- 1 1
28:+ 1 0
29:storeg 1 body#SB#527[1]=1
31:pushc 48 
33:pushthis 
34:rpushg 2 body#SB#527[2]=%for%to%%do%#S#70
36:rpushg 2 %for%to%%do%#S#70[2]=doit
38:rpushg 1 doit[1]=putint
40:rpushg 2 putint[2]=Indexed
42:pushthis 
43:pushg 1 body#SB#527[1]=1
45:xpushg 1 Indexed[2]=3
xpushg:
Object: Indexed:1120 lsc: 0
VFields: 20 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
Rfields: * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
VStack: 
RStack: 
VdtTable: 0 0 0 0 
lscStack: 
--------------

47:+ 48 3
48:%prim 2 51 3
50:rtnEventQ 0 
52:setThisStack 
thisObj = body#SB#527[#S#525,#S#525][]  thisStack = #S#525[loop,loop][]
53:pushthis 

54:rtn D body#SB#527:1127:descInx:527  to: #S#525:1126:descInx:525 
thisObj = #S#525[loop,loop,body#SB#527][]  thisStack = #S#525[loop,loop,body#SB#527][]
19:rpop 
20:pushthis 
21:rpushg 1 #S#525[1]=loop
23:rpushg 1 loop[1]=do
25:rpushg 1 do[1]=%for%to%%do%#S#70
27:pushthis 
28:rpushg 1 #S#525[1]=loop
30:rpushg 1 loop[1]=do
32:rpushg 1 do[1]=%for%to%%do%#S#70
34:pushg 3 %for%to%%do%#S#70[3]=1
36:pushc 1 
38:+ 1 1
39:storeg 3 %for%to%%do%#S#70[3]=2
41:break 1 81 
10:pushthis 
11:rpushg 1 loop[1]=do
13:rpushg 1 do[1]=%for%to%%do%#S#70
15:pushg 3 %for%to%%do%#S#70[3]=2
17:pushthis 
18:rpushg 1 loop[1]=do
20:rpushg 1 do[1]=%for%to%%do%#S#70
22:pushg 2 %for%to%%do%#S#70[2]=1
24:<= 
25:jmpFalse (0)36 
36:rtnEventQ 0 
38:setThisStack 
thisObj = loop[do,do][]  thisStack = do[%for%to%%do%#S#70,%for%to%%do%#S#70][]
39:pushthis 

40:rtn D loop:1125:descInx:65  to: do:1124:descInx:64 
thisObj = do[%for%to%%do%#S#70,%for%to%%do%#S#70,loop][]  thisStack = do[%for%to%%do%#S#70,%for%to%%do%#S#70,loop][]
13:rpop 
14:rtnEventQ 0 
16:mvStack 
thisObj = do[%for%to%%do%#S#70,%for%to%%do%#S#70][]  thisStack = do[%for%to%%do%#S#70,%for%to%%do%#S#70][]
17:rtnEventQ 0 
19:setThisStack 
thisObj = do[%for%to%%do%#S#70,%for%to%%do%#S#70][]  thisStack = %for%to%%do%#S#70[doit,doit][]
20:pushthis 

21:rtn D do:1124:descInx:64  to: %for%to%%do%#S#70:1123:descInx:70 
thisObj = %for%to%%do%#S#70[doit,doit,do][]  thisStack = %for%to%%do%#S#70[doit,doit,do][]
29:rpop 
30:rtnEventQ 0 
32:setThisStack 
thisObj = %for%to%%do%#S#70[doit,doit][]  thisStack = doit[putint,putint][]
33:pushthis 

34:rtn D %for%to%%do%#S#70:1123:descInx:70  to: doit:1121:descInx:68 
thisObj = doit[putint,putint,%for%to%%do%#S#70][]  thisStack = doit[putint,putint,%for%to%%do%#S#70][]
37:rpop 
38:rtnEventQ 0 
40:setThisStack 
thisObj = doit[putint,putint][]  thisStack = putint[(0)List,(0)List][]
41:pushthis 

42:rtn D doit:1121:descInx:68  to: putint:1119:descInx:67 
thisObj = putint[(0)List,(0)List,doit][]  thisStack = putint[(0)List,(0)List,doit][]
60:rpop 
61:rtnEventQ 0 
63:setThisStack 
thisObj = putint[(0)List,(0)List][]  thisStack = (0)List[(0)ArrayDemos,(0)ArrayDemos][]
64:pushthis 

65:rtn D putint:1119:descInx:67  to: (0)List:1016:descInx:434 
thisObj = (0)List[(0)ArrayDemos,(0)ArrayDemos,putint][]  thisStack = (0)List[(0)ArrayDemos,(0)ArrayDemos,putint][]
229:rpop 
230:pushthis 
231:rpushg 1 (0)List[1]=(0)ArrayDemos
233:rpushg 1 (0)ArrayDemos[1]=(0)demo
235:rpushg 1 (0)demo[1]=(0)workspace
237:pushthis 
238:rpushg 7 (0)List[7]=Range
240:rpushg 2 Range[2]=Indexed
242:pushc 1 
244:xpushg 1 Indexed[2]=4
xpushg:
Object: Indexed:1063 lsc: 0
VFields: 2 4 5 
Rfields: * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
VStack: 
RStack: 
VdtTable: 0 0 0 0 
lscStack: 
--------------


246:invoke 67 0 0 putint:1128:descInx:67 
thisObj = putint[(0)List,(0)List][]  thisStack = (0)List[(0)ArrayDemos,(0)ArrayDemos,(0)workspace][4]
1:pushthis 
2:storeg 1 putint[1]=4
4:rstore 1 (0)workspace->putint[1]
6:allocEventQ 0 
8:mvStack 
thisObj = putint[(0)List,(0)List][]  thisStack = putint[(0)List,(0)List][]
9:pushthis 
10:rpushg 1 putint[1]=(0)workspace
12:pushc 20 
14:pushc 0 
16:pushc 1 

18:allocIndexed 52 1 
AllocQ_indexed:
Object: Indexed:1129 lsc: 0
VFields: 20 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
Rfields: * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
VStack: 
RStack: 
VdtTable: 0 0 0 0 
lscStack: 
--------------

22:pushthis 
23:rstoreg 2 putint[2]=Indexed
25:rtnEventQ 1 
27:doEventQ 
28:mvStack 
thisObj = putint[(0)List,(0)List][]  thisStack = putint[(0)List,(0)List][]
29:pushthis 
30:pushthis 
31:pushg 1 putint[1]=4
33:pushc 0 
35:< 4<0
36:storeg 3 putint[3]=0
38:pushthis 
39:pushg 3 putint[3]=0
41:jmpFalse (0)53 
53:pushthis 

54:invoke 68 0 0 doit:1130:descInx:68 
thisObj = doit[putint,putint][]  thisStack = putint[(0)List,(0)List,putint][]
1:rstore 1 putint->doit[1]
3:allocEventQ 0 
5:mvStack 
thisObj = doit[putint,putint][]  thisStack = doit[putint,putint][]
6:pushthis 

7:invoke 69 2 1 loop:1131:descInx:69 
thisObj = loop[doit,doit][]  thisStack = doit[putint,putint,doit][]
1:rstore 1 doit->loop[1]
3:allocEventQ 0 
5:mvStack 
thisObj = loop[doit,doit][]  thisStack = loop[doit,doit][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = loop[doit,doit][]  thisStack = loop[doit,doit][]
10:pushthis 
11:rpushg 1 loop[1]=doit
13:rpushg 1 doit[1]=putint
15:pushthis 
16:rpushg 1 loop[1]=doit
18:rpushg 1 doit[1]=putint
20:pushg 2 putint[2]=0
22:pushc 1 
24:+ 0 1
25:storeg 2 putint[2]=1
27:pushthis 
28:rpushg 1 loop[1]=doit
30:rpushg 1 doit[1]=putint
32:rpushg 2 putint[2]=Indexed
34:pushthis 
35:rpushg 1 loop[1]=doit
37:rpushg 1 doit[1]=putint
39:pushg 1 putint[1]=4
41:pushc 10 
43:mod 
44:pushthis 
45:rpushg 1 loop[1]=doit
47:rpushg 1 doit[1]=putint
49:pushg 2 putint[2]=1
51:xstoreg 1 Indexed[2]=4
xstoreg:
Object: Indexed:1129 lsc: 0
VFields: 20 4 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
Rfields: * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
VStack: 
RStack: 
VdtTable: 0 0 0 0 
lscStack: 
--------------

53:pushthis 
54:rpushg 1 loop[1]=doit
56:rpushg 1 doit[1]=putint
58:pushthis 
59:rpushg 1 loop[1]=doit
61:rpushg 1 doit[1]=putint
63:pushg 1 putint[1]=4
65:pushc 10 
67:div 
68:storeg 1 putint[1]=0
70:pushthis 
71:rpushg 1 loop[1]=doit
73:rpushg 1 doit[1]=putint
75:pushg 1 putint[1]=0
77:pushc 0 
79:> 0>0
80:jmpFalse (0)91 
91:rtnEventQ 0 
93:setThisStack 
thisObj = loop[doit,doit][]  thisStack = doit[putint,putint][]
94:pushthis 

95:rtn D loop:1131:descInx:69  to: doit:1130:descInx:68 
thisObj = doit[putint,putint,loop][]  thisStack = doit[putint,putint,loop][]
13:rpop 
14:rtnEventQ 1 
16:doEventQ 
17:mvStack 
thisObj = doit[putint,putint][]  thisStack = doit[putint,putint][]
18:pushthis 
19:rpushg 1 doit[1]=putint
21:pushg 3 putint[3]=0
23:jmpFalse (0)30 
30:pushthis 

31:invoke 70 0 1 %for%to%%do%#S#70:1132:descInx:70 
thisObj = %for%to%%do%#S#70[doit,doit][]  thisStack = doit[putint,putint,doit][]
1:rstore 2 doit->%for%to%%do%#S#70[2]
3:allocEventQ 1 
5:pushthis 
6:rpushg 2 %for%to%%do%#S#70[2]=doit
8:rpushg 1 doit[1]=putint
10:rpushg 1 putint[1]=(0)workspace
12:pushc 1 
14:pushthis 
15:rpushg 2 %for%to%%do%#S#70[2]=doit
17:rpushg 1 doit[1]=putint
19:pushg 2 putint[2]=1
21:toSuper 63 63 glsc: 1
1:pushthis 
2:storeg 2 %for%to%%do%#S#70[2]=1
4:pushthis 
5:storeg 1 %for%to%%do%#S#70[1]=1
7:rstore 1 (0)workspace->%for%to%%do%#S#70[1]
9:allocEventQ 0 
11:mvStack 
thisObj = %for%to%%do%#S#70[doit,doit][]  thisStack = %for%to%%do%#S#70[doit,doit][]
12:rtnEventQ 1 
14:doEventQ 
15:mvStack 
thisObj = %for%to%%do%#S#70[doit,doit][]  thisStack = %for%to%%do%#S#70[doit,doit][]
16:pushthis 
17:pushthis 
18:pushg 1 %for%to%%do%#S#70[1]=1
20:storeg 3 %for%to%%do%#S#70[3]=1
22:pushthis 

23:invoke 64 0 1 do:1133:descInx:64 
thisObj = do[%for%to%%do%#S#70,%for%to%%do%#S#70][]  thisStack = %for%to%%do%#S#70[doit,doit,%for%to%%do%#S#70][]
1:rstore 1 %for%to%%do%#S#70->do[1]
3:allocEventQ 1 
5:mvStack 
thisObj = do[%for%to%%do%#S#70,%for%to%%do%#S#70][]  thisStack = do[%for%to%%do%#S#70,%for%to%%do%#S#70][]
6:pushthis 

7:invoke 65 2 1 loop:1134:descInx:65 
thisObj = loop[do,do][]  thisStack = do[%for%to%%do%#S#70,%for%to%%do%#S#70,do][]
1:rstore 1 do->loop[1]
3:allocEventQ 0 
5:mvStack 
thisObj = loop[do,do][]  thisStack = loop[do,do][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = loop[do,do][]  thisStack = loop[do,do][]
10:pushthis 
11:rpushg 1 loop[1]=do
13:rpushg 1 do[1]=%for%to%%do%#S#70
15:pushg 3 %for%to%%do%#S#70[3]=1
17:pushthis 
18:rpushg 1 loop[1]=do
20:rpushg 1 do[1]=%for%to%%do%#S#70
22:pushg 2 %for%to%%do%#S#70[2]=1
24:<= 
25:jmpFalse (1)36 
28:pushthis 

29:invoke 525 0 1 #S#525:1135:descInx:525 
thisObj = #S#525[loop,loop][]  thisStack = loop[do,do,loop][]
1:rstore 1 loop->#S#525[1]
3:allocEventQ 0 
5:mvStack 
thisObj = #S#525[loop,loop][]  thisStack = #S#525[loop,loop][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = #S#525[loop,loop][]  thisStack = #S#525[loop,loop][]
10:pushthis 
11:rpushg 1 #S#525[1]=loop
13:rpushg 1 loop[1]=do
15:rpushg 1 do[1]=%for%to%%do%#S#70
thisObj = #S#525[loop,loop,%for%to%%do%#S#70][]  thisStack = #S#525[loop,loop,%for%to%%do%#S#70][]

17:sendv  1 body#SB#527:1136:descInx:527 
thisObj = body#SB#527[#S#525,#S#525][]  thisStack = #S#525[loop,loop,%for%to%%do%#S#70][]
1:rstore 2 %for%to%%do%#S#70->body#SB#527[2]
3:allocEventQ 0 
5:mvStack 
thisObj = body#SB#527[#S#525,#S#525][]  thisStack = body#SB#527[#S#525,#S#525][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = body#SB#527[#S#525,#S#525][]  thisStack = body#SB#527[#S#525,#S#525][]
10:pushthis 
11:pushthis 
12:rpushg 2 body#SB#527[2]=%for%to%%do%#S#70
14:rpushg 2 %for%to%%do%#S#70[2]=doit
16:rpushg 1 doit[1]=putint
18:pushg 2 putint[2]=1
20:pushc 1 
22:pushthis 
23:rpushg 2 body#SB#527[2]=%for%to%%do%#S#70
25:pushg 3 %for%to%%do%#S#70[3]=1
27:- 1 1
28:+ 1 0
29:storeg 1 body#SB#527[1]=1
31:pushc 48 
33:pushthis 
34:rpushg 2 body#SB#527[2]=%for%to%%do%#S#70
36:rpushg 2 %for%to%%do%#S#70[2]=doit
38:rpushg 1 doit[1]=putint
40:rpushg 2 putint[2]=Indexed
42:pushthis 
43:pushg 1 body#SB#527[1]=1
45:xpushg 1 Indexed[2]=4
xpushg:
Object: Indexed:1129 lsc: 0
VFields: 20 4 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
Rfields: * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
VStack: 
RStack: 
VdtTable: 0 0 0 0 
lscStack: 
--------------

47:+ 48 4
48:%prim 2 52 4
50:rtnEventQ 0 
52:setThisStack 
thisObj = body#SB#527[#S#525,#S#525][]  thisStack = #S#525[loop,loop][]
53:pushthis 

54:rtn D body#SB#527:1136:descInx:527  to: #S#525:1135:descInx:525 
thisObj = #S#525[loop,loop,body#SB#527][]  thisStack = #S#525[loop,loop,body#SB#527][]
19:rpop 
20:pushthis 
21:rpushg 1 #S#525[1]=loop
23:rpushg 1 loop[1]=do
25:rpushg 1 do[1]=%for%to%%do%#S#70
27:pushthis 
28:rpushg 1 #S#525[1]=loop
30:rpushg 1 loop[1]=do
32:rpushg 1 do[1]=%for%to%%do%#S#70
34:pushg 3 %for%to%%do%#S#70[3]=1
36:pushc 1 
38:+ 1 1
39:storeg 3 %for%to%%do%#S#70[3]=2
41:break 1 81 
10:pushthis 
11:rpushg 1 loop[1]=do
13:rpushg 1 do[1]=%for%to%%do%#S#70
15:pushg 3 %for%to%%do%#S#70[3]=2
17:pushthis 
18:rpushg 1 loop[1]=do
20:rpushg 1 do[1]=%for%to%%do%#S#70
22:pushg 2 %for%to%%do%#S#70[2]=1
24:<= 
25:jmpFalse (0)36 
36:rtnEventQ 0 
38:setThisStack 
thisObj = loop[do,do][]  thisStack = do[%for%to%%do%#S#70,%for%to%%do%#S#70][]
39:pushthis 

40:rtn D loop:1134:descInx:65  to: do:1133:descInx:64 
thisObj = do[%for%to%%do%#S#70,%for%to%%do%#S#70,loop][]  thisStack = do[%for%to%%do%#S#70,%for%to%%do%#S#70,loop][]
13:rpop 
14:rtnEventQ 0 
16:mvStack 
thisObj = do[%for%to%%do%#S#70,%for%to%%do%#S#70][]  thisStack = do[%for%to%%do%#S#70,%for%to%%do%#S#70][]
17:rtnEventQ 0 
19:setThisStack 
thisObj = do[%for%to%%do%#S#70,%for%to%%do%#S#70][]  thisStack = %for%to%%do%#S#70[doit,doit][]
20:pushthis 

21:rtn D do:1133:descInx:64  to: %for%to%%do%#S#70:1132:descInx:70 
thisObj = %for%to%%do%#S#70[doit,doit,do][]  thisStack = %for%to%%do%#S#70[doit,doit,do][]
29:rpop 
30:rtnEventQ 0 
32:setThisStack 
thisObj = %for%to%%do%#S#70[doit,doit][]  thisStack = doit[putint,putint][]
33:pushthis 

34:rtn D %for%to%%do%#S#70:1132:descInx:70  to: doit:1130:descInx:68 
thisObj = doit[putint,putint,%for%to%%do%#S#70][]  thisStack = doit[putint,putint,%for%to%%do%#S#70][]
37:rpop 
38:rtnEventQ 0 
40:setThisStack 
thisObj = doit[putint,putint][]  thisStack = putint[(0)List,(0)List][]
41:pushthis 

42:rtn D doit:1130:descInx:68  to: putint:1128:descInx:67 
thisObj = putint[(0)List,(0)List,doit][]  thisStack = putint[(0)List,(0)List,doit][]
60:rpop 
61:rtnEventQ 0 
63:setThisStack 
thisObj = putint[(0)List,(0)List][]  thisStack = (0)List[(0)ArrayDemos,(0)ArrayDemos][]
64:pushthis 

65:rtn D putint:1128:descInx:67  to: (0)List:1016:descInx:434 
thisObj = (0)List[(0)ArrayDemos,(0)ArrayDemos,putint][]  thisStack = (0)List[(0)ArrayDemos,(0)ArrayDemos,putint][]
252:rpop 
253:pushthis 
254:rpushg 1 (0)List[1]=(0)ArrayDemos
256:rpushg 1 (0)ArrayDemos[1]=(0)demo
258:rpushg 1 (0)demo[1]=(0)workspace
260:pushthis 
261:rpushg 7 (0)List[7]=Range
263:rpushg 2 Range[2]=Indexed
265:pushc 2 
267:xpushg 1 Indexed[3]=5
xpushg:
Object: Indexed:1063 lsc: 0
VFields: 2 4 5 
Rfields: * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
VStack: 
RStack: 
VdtTable: 0 0 0 0 
lscStack: 
--------------


269:invoke 67 0 0 putint:1137:descInx:67 
thisObj = putint[(0)List,(0)List][]  thisStack = (0)List[(0)ArrayDemos,(0)ArrayDemos,(0)workspace][5]
1:pushthis 
2:storeg 1 putint[1]=5
4:rstore 1 (0)workspace->putint[1]
6:allocEventQ 0 
8:mvStack 
thisObj = putint[(0)List,(0)List][]  thisStack = putint[(0)List,(0)List][]
9:pushthis 
10:rpushg 1 putint[1]=(0)workspace
12:pushc 20 
14:pushc 0 
16:pushc 1 

18:allocIndexed 52 1 
AllocQ_indexed:
Object: Indexed:1138 lsc: 0
VFields: 20 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
Rfields: * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
VStack: 
RStack: 
VdtTable: 0 0 0 0 
lscStack: 
--------------

22:pushthis 
23:rstoreg 2 putint[2]=Indexed
25:rtnEventQ 1 
27:doEventQ 
28:mvStack 
thisObj = putint[(0)List,(0)List][]  thisStack = putint[(0)List,(0)List][]
29:pushthis 
30:pushthis 
31:pushg 1 putint[1]=5
33:pushc 0 
35:< 5<0
36:storeg 3 putint[3]=0
38:pushthis 
39:pushg 3 putint[3]=0
41:jmpFalse (0)53 
53:pushthis 

54:invoke 68 0 0 doit:1139:descInx:68 
thisObj = doit[putint,putint][]  thisStack = putint[(0)List,(0)List,putint][]
1:rstore 1 putint->doit[1]
3:allocEventQ 0 
5:mvStack 
thisObj = doit[putint,putint][]  thisStack = doit[putint,putint][]
6:pushthis 

7:invoke 69 2 1 loop:1140:descInx:69 
thisObj = loop[doit,doit][]  thisStack = doit[putint,putint,doit][]
1:rstore 1 doit->loop[1]
3:allocEventQ 0 
5:mvStack 
thisObj = loop[doit,doit][]  thisStack = loop[doit,doit][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = loop[doit,doit][]  thisStack = loop[doit,doit][]
10:pushthis 
11:rpushg 1 loop[1]=doit
13:rpushg 1 doit[1]=putint
15:pushthis 
16:rpushg 1 loop[1]=doit
18:rpushg 1 doit[1]=putint
20:pushg 2 putint[2]=0
22:pushc 1 
24:+ 0 1
25:storeg 2 putint[2]=1
27:pushthis 
28:rpushg 1 loop[1]=doit
30:rpushg 1 doit[1]=putint
32:rpushg 2 putint[2]=Indexed
34:pushthis 
35:rpushg 1 loop[1]=doit
37:rpushg 1 doit[1]=putint
39:pushg 1 putint[1]=5
41:pushc 10 
43:mod 
44:pushthis 
45:rpushg 1 loop[1]=doit
47:rpushg 1 doit[1]=putint
49:pushg 2 putint[2]=1
51:xstoreg 1 Indexed[2]=5
xstoreg:
Object: Indexed:1138 lsc: 0
VFields: 20 5 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
Rfields: * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
VStack: 
RStack: 
VdtTable: 0 0 0 0 
lscStack: 
--------------

53:pushthis 
54:rpushg 1 loop[1]=doit
56:rpushg 1 doit[1]=putint
58:pushthis 
59:rpushg 1 loop[1]=doit
61:rpushg 1 doit[1]=putint
63:pushg 1 putint[1]=5
65:pushc 10 
67:div 
68:storeg 1 putint[1]=0
70:pushthis 
71:rpushg 1 loop[1]=doit
73:rpushg 1 doit[1]=putint
75:pushg 1 putint[1]=0
77:pushc 0 
79:> 0>0
80:jmpFalse (0)91 
91:rtnEventQ 0 
93:setThisStack 
thisObj = loop[doit,doit][]  thisStack = doit[putint,putint][]
94:pushthis 

95:rtn D loop:1140:descInx:69  to: doit:1139:descInx:68 
thisObj = doit[putint,putint,loop][]  thisStack = doit[putint,putint,loop][]
13:rpop 
14:rtnEventQ 1 
16:doEventQ 
17:mvStack 
thisObj = doit[putint,putint][]  thisStack = doit[putint,putint][]
18:pushthis 
19:rpushg 1 doit[1]=putint
21:pushg 3 putint[3]=0
23:jmpFalse (0)30 
30:pushthis 

31:invoke 70 0 1 %for%to%%do%#S#70:1141:descInx:70 
thisObj = %for%to%%do%#S#70[doit,doit][]  thisStack = doit[putint,putint,doit][]
1:rstore 2 doit->%for%to%%do%#S#70[2]
3:allocEventQ 1 
5:pushthis 
6:rpushg 2 %for%to%%do%#S#70[2]=doit
8:rpushg 1 doit[1]=putint
10:rpushg 1 putint[1]=(0)workspace
12:pushc 1 
14:pushthis 
15:rpushg 2 %for%to%%do%#S#70[2]=doit
17:rpushg 1 doit[1]=putint
19:pushg 2 putint[2]=1
21:toSuper 63 63 glsc: 1
1:pushthis 
2:storeg 2 %for%to%%do%#S#70[2]=1
4:pushthis 
5:storeg 1 %for%to%%do%#S#70[1]=1
7:rstore 1 (0)workspace->%for%to%%do%#S#70[1]
9:allocEventQ 0 
11:mvStack 
thisObj = %for%to%%do%#S#70[doit,doit][]  thisStack = %for%to%%do%#S#70[doit,doit][]
12:rtnEventQ 1 
14:doEventQ 
15:mvStack 
thisObj = %for%to%%do%#S#70[doit,doit][]  thisStack = %for%to%%do%#S#70[doit,doit][]
16:pushthis 
17:pushthis 
18:pushg 1 %for%to%%do%#S#70[1]=1
20:storeg 3 %for%to%%do%#S#70[3]=1
22:pushthis 

23:invoke 64 0 1 do:1142:descInx:64 
thisObj = do[%for%to%%do%#S#70,%for%to%%do%#S#70][]  thisStack = %for%to%%do%#S#70[doit,doit,%for%to%%do%#S#70][]
1:rstore 1 %for%to%%do%#S#70->do[1]
3:allocEventQ 1 
5:mvStack 
thisObj = do[%for%to%%do%#S#70,%for%to%%do%#S#70][]  thisStack = do[%for%to%%do%#S#70,%for%to%%do%#S#70][]
6:pushthis 

7:invoke 65 2 1 loop:1143:descInx:65 
thisObj = loop[do,do][]  thisStack = do[%for%to%%do%#S#70,%for%to%%do%#S#70,do][]
1:rstore 1 do->loop[1]
3:allocEventQ 0 
5:mvStack 
thisObj = loop[do,do][]  thisStack = loop[do,do][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = loop[do,do][]  thisStack = loop[do,do][]
10:pushthis 
11:rpushg 1 loop[1]=do
13:rpushg 1 do[1]=%for%to%%do%#S#70
15:pushg 3 %for%to%%do%#S#70[3]=1
17:pushthis 
18:rpushg 1 loop[1]=do
20:rpushg 1 do[1]=%for%to%%do%#S#70
22:pushg 2 %for%to%%do%#S#70[2]=1
24:<= 
25:jmpFalse (1)36 
28:pushthis 

29:invoke 525 0 1 #S#525:1144:descInx:525 
thisObj = #S#525[loop,loop][]  thisStack = loop[do,do,loop][]
1:rstore 1 loop->#S#525[1]
3:allocEventQ 0 
5:mvStack 
thisObj = #S#525[loop,loop][]  thisStack = #S#525[loop,loop][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = #S#525[loop,loop][]  thisStack = #S#525[loop,loop][]
10:pushthis 
11:rpushg 1 #S#525[1]=loop
13:rpushg 1 loop[1]=do
15:rpushg 1 do[1]=%for%to%%do%#S#70
thisObj = #S#525[loop,loop,%for%to%%do%#S#70][]  thisStack = #S#525[loop,loop,%for%to%%do%#S#70][]

17:sendv  1 body#SB#527:1145:descInx:527 
thisObj = body#SB#527[#S#525,#S#525][]  thisStack = #S#525[loop,loop,%for%to%%do%#S#70][]
1:rstore 2 %for%to%%do%#S#70->body#SB#527[2]
3:allocEventQ 0 
5:mvStack 
thisObj = body#SB#527[#S#525,#S#525][]  thisStack = body#SB#527[#S#525,#S#525][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = body#SB#527[#S#525,#S#525][]  thisStack = body#SB#527[#S#525,#S#525][]
10:pushthis 
11:pushthis 
12:rpushg 2 body#SB#527[2]=%for%to%%do%#S#70
14:rpushg 2 %for%to%%do%#S#70[2]=doit
16:rpushg 1 doit[1]=putint
18:pushg 2 putint[2]=1
20:pushc 1 
22:pushthis 
23:rpushg 2 body#SB#527[2]=%for%to%%do%#S#70
25:pushg 3 %for%to%%do%#S#70[3]=1
27:- 1 1
28:+ 1 0
29:storeg 1 body#SB#527[1]=1
31:pushc 48 
33:pushthis 
34:rpushg 2 body#SB#527[2]=%for%to%%do%#S#70
36:rpushg 2 %for%to%%do%#S#70[2]=doit
38:rpushg 1 doit[1]=putint
40:rpushg 2 putint[2]=Indexed
42:pushthis 
43:pushg 1 body#SB#527[1]=1
45:xpushg 1 Indexed[2]=5
xpushg:
Object: Indexed:1138 lsc: 0
VFields: 20 5 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
Rfields: * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
VStack: 
RStack: 
VdtTable: 0 0 0 0 
lscStack: 
--------------

47:+ 48 5
48:%prim 2 53 5
50:rtnEventQ 0 
52:setThisStack 
thisObj = body#SB#527[#S#525,#S#525][]  thisStack = #S#525[loop,loop][]
53:pushthis 

54:rtn D body#SB#527:1145:descInx:527  to: #S#525:1144:descInx:525 
thisObj = #S#525[loop,loop,body#SB#527][]  thisStack = #S#525[loop,loop,body#SB#527][]
19:rpop 
20:pushthis 
21:rpushg 1 #S#525[1]=loop
23:rpushg 1 loop[1]=do
25:rpushg 1 do[1]=%for%to%%do%#S#70
27:pushthis 
28:rpushg 1 #S#525[1]=loop
30:rpushg 1 loop[1]=do
32:rpushg 1 do[1]=%for%to%%do%#S#70
34:pushg 3 %for%to%%do%#S#70[3]=1
36:pushc 1 
38:+ 1 1
39:storeg 3 %for%to%%do%#S#70[3]=2
41:break 1 81 
10:pushthis 
11:rpushg 1 loop[1]=do
13:rpushg 1 do[1]=%for%to%%do%#S#70
15:pushg 3 %for%to%%do%#S#70[3]=2
17:pushthis 
18:rpushg 1 loop[1]=do
20:rpushg 1 do[1]=%for%to%%do%#S#70
22:pushg 2 %for%to%%do%#S#70[2]=1
24:<= 
25:jmpFalse (0)36 
36:rtnEventQ 0 
38:setThisStack 
thisObj = loop[do,do][]  thisStack = do[%for%to%%do%#S#70,%for%to%%do%#S#70][]
39:pushthis 

40:rtn D loop:1143:descInx:65  to: do:1142:descInx:64 
thisObj = do[%for%to%%do%#S#70,%for%to%%do%#S#70,loop][]  thisStack = do[%for%to%%do%#S#70,%for%to%%do%#S#70,loop][]
13:rpop 
14:rtnEventQ 0 
16:mvStack 
thisObj = do[%for%to%%do%#S#70,%for%to%%do%#S#70][]  thisStack = do[%for%to%%do%#S#70,%for%to%%do%#S#70][]
17:rtnEventQ 0 
19:setThisStack 
thisObj = do[%for%to%%do%#S#70,%for%to%%do%#S#70][]  thisStack = %for%to%%do%#S#70[doit,doit][]
20:pushthis 

21:rtn D do:1142:descInx:64  to: %for%to%%do%#S#70:1141:descInx:70 
thisObj = %for%to%%do%#S#70[doit,doit,do][]  thisStack = %for%to%%do%#S#70[doit,doit,do][]
29:rpop 
30:rtnEventQ 0 
32:setThisStack 
thisObj = %for%to%%do%#S#70[doit,doit][]  thisStack = doit[putint,putint][]
33:pushthis 

34:rtn D %for%to%%do%#S#70:1141:descInx:70  to: doit:1139:descInx:68 
thisObj = doit[putint,putint,%for%to%%do%#S#70][]  thisStack = doit[putint,putint,%for%to%%do%#S#70][]
37:rpop 
38:rtnEventQ 0 
40:setThisStack 
thisObj = doit[putint,putint][]  thisStack = putint[(0)List,(0)List][]
41:pushthis 

42:rtn D doit:1139:descInx:68  to: putint:1137:descInx:67 
thisObj = putint[(0)List,(0)List,doit][]  thisStack = putint[(0)List,(0)List,doit][]
60:rpop 
61:rtnEventQ 0 
63:setThisStack 
thisObj = putint[(0)List,(0)List][]  thisStack = (0)List[(0)ArrayDemos,(0)ArrayDemos][]
64:pushthis 

65:rtn D putint:1137:descInx:67  to: (0)List:1016:descInx:434 
thisObj = (0)List[(0)ArrayDemos,(0)ArrayDemos,putint][]  thisStack = (0)List[(0)ArrayDemos,(0)ArrayDemos,putint][]
275:rpop 
276:pushthis 
277:pushthis 
278:pushthis 
279:rpushg 6 (0)List[6]=Range
281:pushthis 
282:pushthis 
283:rpushg 7 (0)List[7]=Range
285:pushNone 

286:invoke 438 0 0 RangeList:1146:descInx:438 
thisObj = RangeList[(0)List,(0)List][]  thisStack = (0)List[(0)ArrayDemos,(0)ArrayDemos,(0)List,(0)List,Range,(0)List,Range,none][]
1:rstore 1 none->RangeList[1]
3:allocEventQ 0 
5:pushthis 
6:rpushg 1 RangeList[1]=none
8:pushthis 
9:rpushg 1 RangeList[1]=none
11:rpushg 1 