
1:pushthis 

2:invoke 1 0 1 BETAworld:1002:descInx:1 
thisObj = BETAworld[main,main][]  thisStack = main[main][]
1:rstore 1 main->BETAworld[1]
3:allocEventQ 1 
5:pushthis 
6:saveBETAworld 
7:mvStack 
thisObj = BETAworld[main,main][]  thisStack = BETAworld[main,main][]
8:pushthis 

9:invoke 3 2 1 BETA:1003:descInx:3 
thisObj = BETA[BETAworld,BETAworld][]  thisStack = BETAworld[main,main,BETAworld][]
1:rstore 1 BETAworld->BETA[1]
3:allocEventQ 1 
5:mvStack 
thisObj = BETA[BETAworld,BETAworld][]  thisStack = BETA[BETAworld,BETAworld][]
6:rtnEventQ 0 
8:mvStack 
thisObj = BETA[BETAworld,BETAworld][]  thisStack = BETA[BETAworld,BETAworld][]
9:rtnEventQ 0 
11:setThisStack 
thisObj = BETA[BETAworld,BETAworld][]  thisStack = BETAworld[main,main][]
12:pushthis 

13:rtn D BETA:1003:descInx:3  to: BETAworld:1002:descInx:1 
thisObj = BETAworld[main,main,BETA][]  thisStack = BETAworld[main,main,BETA][]
15:rpop 
16:pushthis 

17:invoke 71 3 1 LIB:1004:descInx:71 
thisObj = LIB[BETAworld,BETAworld][]  thisStack = BETAworld[main,main,BETAworld][]
1:rstore 1 BETAworld->LIB[1]
3:allocEventQ 1 
5:mvStack 
thisObj = LIB[BETAworld,BETAworld][]  thisStack = LIB[BETAworld,BETAworld][]
6:pushthis 

7:invoke 72 2 1 BasicSystem:1005:descInx:72 
thisObj = BasicSystem[LIB,LIB][]  thisStack = LIB[BETAworld,BETAworld,LIB][]
1:rstore 1 LIB->BasicSystem[1]
3:allocEventQ 1 
5:mvStack 
thisObj = BasicSystem[LIB,LIB][]  thisStack = BasicSystem[LIB,LIB][]
6:rtnEventQ 0 
8:mvStack 
thisObj = BasicSystem[LIB,LIB][]  thisStack = BasicSystem[LIB,LIB][]
9:rtnEventQ 0 
11:setThisStack 
thisObj = BasicSystem[LIB,LIB][]  thisStack = LIB[BETAworld,BETAworld][]
12:pushthis 

13:rtn D BasicSystem:1005:descInx:72  to: LIB:1004:descInx:71 
thisObj = LIB[BETAworld,BETAworld,BasicSystem][]  thisStack = LIB[BETAworld,BETAworld,BasicSystem][]
13:rpop 
14:pushthis 

15:invoke 167 3 1 Complex:1006:descInx:167 
thisObj = Complex[LIB,LIB][]  thisStack = LIB[BETAworld,BETAworld,LIB][]
1:rstore 1 LIB->Complex[1]
3:allocEventQ 1 
5:mvStack 
thisObj = Complex[LIB,LIB][]  thisStack = Complex[LIB,LIB][]
6:rtnEventQ 0 
8:mvStack 
thisObj = Complex[LIB,LIB][]  thisStack = Complex[LIB,LIB][]
9:rtnEventQ 0 
11:setThisStack 
thisObj = Complex[LIB,LIB][]  thisStack = LIB[BETAworld,BETAworld][]
12:pushthis 

13:rtn D Complex:1006:descInx:167  to: LIB:1004:descInx:71 
thisObj = LIB[BETAworld,BETAworld,Complex][]  thisStack = LIB[BETAworld,BETAworld,Complex][]
21:rpop 
22:pushthis 

23:invoke 73 4 1 Containers:1007:descInx:73 
thisObj = Containers[LIB,LIB][]  thisStack = LIB[BETAworld,BETAworld,LIB][]
1:rstore 1 LIB->Containers[1]
3:allocEventQ 1 
5:mvStack 
thisObj = Containers[LIB,LIB][]  thisStack = Containers[LIB,LIB][]
6:pushthis 

7:invoke 81 3 1 mQueue:1008:descInx:81 
thisObj = mQueue[Containers,Containers][]  thisStack = Containers[LIB,LIB,Containers][]
1:rstore 1 Containers->mQueue[1]
3:allocEventQ 1 
5:mvStack 
thisObj = mQueue[Containers,Containers][]  thisStack = mQueue[Containers,Containers][]
6:rtnEventQ 0 
8:mvStack 
thisObj = mQueue[Containers,Containers][]  thisStack = mQueue[Containers,Containers][]
9:rtnEventQ 0 
11:setThisStack 
thisObj = mQueue[Containers,Containers][]  thisStack = Containers[LIB,LIB][]
12:pushthis 

13:rtn D mQueue:1008:descInx:81  to: Containers:1007:descInx:73 
thisObj = Containers[LIB,LIB,mQueue][]  thisStack = Containers[LIB,LIB,mQueue][]
13:rpop 
14:rtnEventQ 0 
16:mvStack 
thisObj = Containers[LIB,LIB][]  thisStack = Containers[LIB,LIB][]
17:rtnEventQ 0 
19:setThisStack 
thisObj = Containers[LIB,LIB][]  thisStack = LIB[BETAworld,BETAworld][]
20:pushthis 

21:rtn D Containers:1007:descInx:73  to: LIB:1004:descInx:71 
thisObj = LIB[BETAworld,BETAworld,Containers][]  thisStack = LIB[BETAworld,BETAworld,Containers][]
29:rpop 
30:pushthis 

31:invoke 172 5 1 EMC2array:1009:descInx:172 
thisObj = EMC2array[LIB,LIB][]  thisStack = LIB[BETAworld,BETAworld,LIB][]
1:rstore 1 LIB->EMC2array[1]
3:allocEventQ 1 
5:mvStack 
thisObj = EMC2array[LIB,LIB][]  thisStack = EMC2array[LIB,LIB][]
6:rtnEventQ 0 
8:mvStack 
thisObj = EMC2array[LIB,LIB][]  thisStack = EMC2array[LIB,LIB][]
9:rtnEventQ 0 
11:setThisStack 
thisObj = EMC2array[LIB,LIB][]  thisStack = LIB[BETAworld,BETAworld][]
12:pushthis 

13:rtn D EMC2array:1009:descInx:172  to: LIB:1004:descInx:71 
thisObj = LIB[BETAworld,BETAworld,EMC2array][]  thisStack = LIB[BETAworld,BETAworld,EMC2array][]
37:rpop 
38:pushthis 

39:invoke 197 6 1 ForkJoinSystem:1010:descInx:197 
thisObj = ForkJoinSystem[LIB,LIB][]  thisStack = LIB[BETAworld,BETAworld,LIB][]
1:rstore 1 LIB->ForkJoinSystem[1]
3:allocEventQ 1 
5:mvStack 
thisObj = ForkJoinSystem[LIB,LIB][]  thisStack = ForkJoinSystem[LIB,LIB][]
6:rtnEventQ 0 
8:mvStack 
thisObj = ForkJoinSystem[LIB,LIB][]  thisStack = ForkJoinSystem[LIB,LIB][]
9:rtnEventQ 0 
11:setThisStack 
thisObj = ForkJoinSystem[LIB,LIB][]  thisStack = LIB[BETAworld,BETAworld][]
12:pushthis 

13:rtn D ForkJoinSystem:1010:descInx:197  to: LIB:1004:descInx:71 
thisObj = LIB[BETAworld,BETAworld,ForkJoinSystem][]  thisStack = LIB[BETAworld,BETAworld,ForkJoinSystem][]
45:rpop 
46:pushthis 

47:invoke 204 7 1 MonitorSystem:1011:descInx:204 
thisObj = MonitorSystem[LIB,LIB][]  thisStack = LIB[BETAworld,BETAworld,LIB][]
1:rstore 1 LIB->MonitorSystem[1]
3:allocEventQ 1 
5:mvStack 
thisObj = MonitorSystem[LIB,LIB][]  thisStack = MonitorSystem[LIB,LIB][]
6:rtnEventQ 0 
8:mvStack 
thisObj = MonitorSystem[LIB,LIB][]  thisStack = MonitorSystem[LIB,LIB][]
9:rtnEventQ 0 
11:setThisStack 
thisObj = MonitorSystem[LIB,LIB][]  thisStack = LIB[BETAworld,BETAworld][]
12:pushthis 

13:rtn D MonitorSystem:1011:descInx:204  to: LIB:1004:descInx:71 
thisObj = LIB[BETAworld,BETAworld,MonitorSystem][]  thisStack = LIB[BETAworld,BETAworld,MonitorSystem][]
53:rpop 
54:pushthis 

55:invoke 96 9 1 String:1012:descInx:96 
thisObj = String[LIB,LIB][]  thisStack = LIB[BETAworld,BETAworld,LIB][]
1:rstore 1 LIB->String[1]
3:allocEventQ 1 
5:mvStack 
thisObj = String[LIB,LIB][]  thisStack = String[LIB,LIB][]
6:rtnEventQ 0 
8:mvStack 
thisObj = String[LIB,LIB][]  thisStack = String[LIB,LIB][]
9:rtnEventQ 0 
11:setThisStack 
thisObj = String[LIB,LIB][]  thisStack = LIB[BETAworld,BETAworld][]
12:pushthis 

13:rtn D String:1012:descInx:96  to: LIB:1004:descInx:71 
thisObj = LIB[BETAworld,BETAworld,String][]  thisStack = LIB[BETAworld,BETAworld,String][]
61:rpop 
62:rtnEventQ 0 
64:mvStack 
thisObj = LIB[BETAworld,BETAworld][]  thisStack = LIB[BETAworld,BETAworld][]
65:rtnEventQ 0 
67:setThisStack 
thisObj = LIB[BETAworld,BETAworld][]  thisStack = BETAworld[main,main][]
68:pushthis 

69:rtn D LIB:1004:descInx:71  to: BETAworld:1002:descInx:1 
thisObj = BETAworld[main,main,LIB][]  thisStack = BETAworld[main,main,LIB][]
23:rpop 
24:pushthis 

25:invoke 229 4 1 workspace:1013:descInx:229 
thisObj = workspace[BETAworld,BETAworld][]  thisStack = BETAworld[main,main,BETAworld][]
1:rstore 1 BETAworld->workspace[1]
3:allocEventQ 1 
5:mvStack 
thisObj = workspace[BETAworld,BETAworld][]  thisStack = workspace[BETAworld,BETAworld][]
6:pushthis 

7:invoke 429 4 1 demo:1014:descInx:429 
thisObj = demo[workspace,workspace][]  thisStack = workspace[BETAworld,BETAworld,workspace][]
1:rstore 1 workspace->demo[1]
3:allocEventQ 1 
5:mvStack 
thisObj = demo[workspace,workspace][]  thisStack = demo[workspace,workspace][]
6:pushthis 

7:invoke 430 2 1 ArrayDemos:1015:descInx:430 
thisObj = ArrayDemos[demo,demo][]  thisStack = demo[workspace,workspace,demo][]
1:rstore 1 demo->ArrayDemos[1]
3:allocEventQ 1 
5:mvStack 
thisObj = ArrayDemos[demo,demo][]  thisStack = ArrayDemos[demo,demo][]
6:pushthis 

7:invoke 441 4 1 List:1016:descInx:441 
thisObj = List[ArrayDemos,ArrayDemos][]  thisStack = ArrayDemos[demo,demo,ArrayDemos][]
1:rstore 1 ArrayDemos->List[1]
3:allocEventQ 0 
5:mvStack 
thisObj = List[ArrayDemos,ArrayDemos][]  thisStack = List[ArrayDemos,ArrayDemos][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = List[ArrayDemos,ArrayDemos][]  thisStack = List[ArrayDemos,ArrayDemos][]
10:pushText 1 
XmkTextObject
Object: String:1017 lsc: 0
VFields: 18 105 110 116 101 103 101 114 65 114 114 97 121 83 116 97 114 116 49 0 
Rfields: LIB:1004 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
VStack: 
RStack: 
VdtTable: 0 0 0 0 
lscStack: 
--------------


12:invoke 107 0 0 print:1018:descInx:107 
thisObj = print[List,List][]  thisStack = List[ArrayDemos,ArrayDemos,String][]
1:rstore 1 String->print[1]
3:allocEventQ 0 
5:mvStack 
thisObj = print[List,List][]  thisStack = print[List,List][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = print[List,List][]  thisStack = print[List,List][]
10:pushthis 

11:invoke 108 0 1 %for%to%%do%#S#108:1019:descInx:108 
thisObj = %for%to%%do%#S#108[print,print][]  thisStack = print[List,List,print][]
1:rstore 2 print->%for%to%%do%#S#108[2]
3:allocEventQ 1 
5:pushthis 
6:rpushg 2 %for%to%%do%#S#108[2]=print
8:rpushg 1 print[1]=String
10:rpushg 1 String[1]=LIB
12:rpushg 1 LIB[1]=BETAworld
14:pushc 1 
16:pushthis 
17:rpushg 2 %for%to%%do%#S#108[2]=print
19:rpushg 1 print[1]=String

21:invoke 98 0 0 length:1020:descInx:98 
thisObj = length[%for%to%%do%#S#108,print][]  thisStack = print[List,List,BETAworld,String][1]
1:rstore 1 String->length[1]
3:allocEventQ 0 
5:mvStack 
thisObj = length[%for%to%%do%#S#108,print][]  thisStack = length[%for%to%%do%#S#108,print][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = length[%for%to%%do%#S#108,print][]  thisStack = length[%for%to%%do%#S#108,print][]
10:pushthis 
11:pushthis 
12:rpushg 1 length[1]=String
14:pushc 0 
16:xpushg 1 String[1]=18
xpushg:
Object: String:1017 lsc: 0
VFields: 18 105 110 116 101 103 101 114 65 114 114 97 121 83 116 97 114 116 49 0 
Rfields: LIB:1004 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
VStack: 
RStack: 
VdtTable: 0 0 0 0 
lscStack: 
--------------

18:storeg 1 length[1]=18
20:rtnEventQ 0 
22:setThisStack 
thisObj = length[%for%to%%do%#S#108,print][]  thisStack = print[List,List,BETAworld][1]
23:pushthis 
24:pushg 1 length[1]=18

26:rtn D length:1020:descInx:98  to: %for%to%%do%#S#108:1019:descInx:108 
thisObj = %for%to%%do%#S#108[print,print][]  thisStack = print[List,List,BETAworld][1,18]
27:toSuper 63 63 glsc: 1
1:pushthis 
2:storeg 2 %for%to%%do%#S#108[2]=18
4:pushthis 
5:storeg 1 %for%to%%do%#S#108[1]=1
7:rstore 1 BETAworld->%for%to%%do%#S#108[1]
9:allocEventQ 0 
11:mvStack 
thisObj = %for%to%%do%#S#108[print,print][]  thisStack = %for%to%%do%#S#108[print,print][]
12:rtnEventQ 1 
14:doEventQ 
15:mvStack 
thisObj = %for%to%%do%#S#108[print,print][]  thisStack = %for%to%%do%#S#108[print,print][]
16:pushthis 
17:pushthis 
18:pushg 1 %for%to%%do%#S#108[1]=1
20:storeg 3 %for%to%%do%#S#108[3]=1
22:pushthis 

23:invoke 64 0 1 do:1021:descInx:64 
thisObj = do[%for%to%%do%#S#108,%for%to%%do%#S#108][]  thisStack = %for%to%%do%#S#108[print,print,%for%to%%do%#S#108][]
1:rstore 1 %for%to%%do%#S#108->do[1]
3:allocEventQ 1 
5:mvStack 
thisObj = do[%for%to%%do%#S#108,%for%to%%do%#S#108][]  thisStack = do[%for%to%%do%#S#108,%for%to%%do%#S#108][]
6:pushthis 

7:invoke 65 2 1 loop:1022:descInx:65 
thisObj = loop[do,do][]  thisStack = do[%for%to%%do%#S#108,%for%to%%do%#S#108,do][]
1:rstore 1 do->loop[1]
3:allocEventQ 0 
5:mvStack 
thisObj = loop[do,do][]  thisStack = loop[do,do][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = loop[do,do][]  thisStack = loop[do,do][]
10:pushthis 
11:rpushg 1 loop[1]=do
13:rpushg 1 do[1]=%for%to%%do%#S#108
15:pushg 3 %for%to%%do%#S#108[3]=1
17:pushthis 
18:rpushg 1 loop[1]=do
20:rpushg 1 do[1]=%for%to%%do%#S#108
22:pushg 2 %for%to%%do%#S#108[2]=18
24:<= 
25:jmpFalse (1)36 
28:pushthis 

29:invoke 535 0 1 #S#535:1023:descInx:535 
thisObj = #S#535[loop,loop][]  thisStack = loop[do,do,loop][]
1:rstore 1 loop->#S#535[1]
3:allocEventQ 0 
5:mvStack 
thisObj = #S#535[loop,loop][]  thisStack = #S#535[loop,loop][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = #S#535[loop,loop][]  thisStack = #S#535[loop,loop][]
10:pushthis 
11:rpushg 1 #S#535[1]=loop
13:rpushg 1 loop[1]=do
15:rpushg 1 do[1]=%for%to%%do%#S#108
thisObj = #S#535[loop,loop,%for%to%%do%#S#108][]  thisStack = #S#535[loop,loop,%for%to%%do%#S#108][]

17:sendv  1 body#SB#550:1024:descInx:550 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = #S#535[loop,loop,%for%to%%do%#S#108][]
1:rstore 2 %for%to%%do%#S#108->body#SB#550[2]
3:allocEventQ 0 
5:mvStack 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = body#SB#550[#S#535,#S#535][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = body#SB#550[#S#535,#S#535][]
10:pushthis 
11:rpushg 2 body#SB#550[2]=%for%to%%do%#S#108
13:rpushg 2 %for%to%%do%#S#108[2]=print
15:rpushg 1 print[1]=String
17:pushthis 
18:rpushg 2 body#SB#550[2]=%for%to%%do%#S#108
20:pushg 3 %for%to%%do%#S#108[3]=1
22:xpushg 1 String[2]=105
xpushg:
Object: String:1017 lsc: 0
VFields: 18 105 110 116 101 103 101 114 65 114 114 97 121 83 116 97 114 116 49 0 
Rfields: LIB:1004 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
VStack: 
RStack: 
VdtTable: 0 0 0 0 
lscStack: 
--------------

24:%prim 2 105 i
26:rtnEventQ 0 
28:setThisStack 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = #S#535[loop,loop][]
29:pushthis 

30:rtn D body#SB#550:1024:descInx:550  to: #S#535:1023:descInx:535 
thisObj = #S#535[loop,loop,body#SB#550][]  thisStack = #S#535[loop,loop,body#SB#550][]
19:rpop 
20:pushthis 
21:rpushg 1 #S#535[1]=loop
23:rpushg 1 loop[1]=do
25:rpushg 1 do[1]=%for%to%%do%#S#108
27:pushthis 
28:rpushg 1 #S#535[1]=loop
30:rpushg 1 loop[1]=do
32:rpushg 1 do[1]=%for%to%%do%#S#108
34:pushg 3 %for%to%%do%#S#108[3]=1
36:pushc 1 
38:+ 1 1
39:storeg 3 %for%to%%do%#S#108[3]=2
41:break 1 81 
10:pushthis 
11:rpushg 1 loop[1]=do
13:rpushg 1 do[1]=%for%to%%do%#S#108
15:pushg 3 %for%to%%do%#S#108[3]=2
17:pushthis 
18:rpushg 1 loop[1]=do
20:rpushg 1 do[1]=%for%to%%do%#S#108
22:pushg 2 %for%to%%do%#S#108[2]=18
24:<= 
25:jmpFalse (1)36 
28:pushthis 

29:invoke 535 0 1 #S#535:1025:descInx:535 
thisObj = #S#535[loop,loop][]  thisStack = loop[do,do,loop][]
1:rstore 1 loop->#S#535[1]
3:allocEventQ 0 
5:mvStack 
thisObj = #S#535[loop,loop][]  thisStack = #S#535[loop,loop][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = #S#535[loop,loop][]  thisStack = #S#535[loop,loop][]
10:pushthis 
11:rpushg 1 #S#535[1]=loop
13:rpushg 1 loop[1]=do
15:rpushg 1 do[1]=%for%to%%do%#S#108
thisObj = #S#535[loop,loop,%for%to%%do%#S#108][]  thisStack = #S#535[loop,loop,%for%to%%do%#S#108][]

17:sendv  1 body#SB#550:1026:descInx:550 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = #S#535[loop,loop,%for%to%%do%#S#108][]
1:rstore 2 %for%to%%do%#S#108->body#SB#550[2]
3:allocEventQ 0 
5:mvStack 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = body#SB#550[#S#535,#S#535][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = body#SB#550[#S#535,#S#535][]
10:pushthis 
11:rpushg 2 body#SB#550[2]=%for%to%%do%#S#108
13:rpushg 2 %for%to%%do%#S#108[2]=print
15:rpushg 1 print[1]=String
17:pushthis 
18:rpushg 2 body#SB#550[2]=%for%to%%do%#S#108
20:pushg 3 %for%to%%do%#S#108[3]=2
22:xpushg 1 String[3]=110
xpushg:
Object: String:1017 lsc: 0
VFields: 18 105 110 116 101 103 101 114 65 114 114 97 121 83 116 97 114 116 49 0 
Rfields: LIB:1004 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
VStack: 
RStack: 
VdtTable: 0 0 0 0 
lscStack: 
--------------

24:%prim 2 110 n
26:rtnEventQ 0 
28:setThisStack 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = #S#535[loop,loop][]
29:pushthis 

30:rtn D body#SB#550:1026:descInx:550  to: #S#535:1025:descInx:535 
thisObj = #S#535[loop,loop,body#SB#550][]  thisStack = #S#535[loop,loop,body#SB#550][]
19:rpop 
20:pushthis 
21:rpushg 1 #S#535[1]=loop
23:rpushg 1 loop[1]=do
25:rpushg 1 do[1]=%for%to%%do%#S#108
27:pushthis 
28:rpushg 1 #S#535[1]=loop
30:rpushg 1 loop[1]=do
32:rpushg 1 do[1]=%for%to%%do%#S#108
34:pushg 3 %for%to%%do%#S#108[3]=2
36:pushc 1 
38:+ 2 1
39:storeg 3 %for%to%%do%#S#108[3]=3
41:break 1 81 
10:pushthis 
11:rpushg 1 loop[1]=do
13:rpushg 1 do[1]=%for%to%%do%#S#108
15:pushg 3 %for%to%%do%#S#108[3]=3
17:pushthis 
18:rpushg 1 loop[1]=do
20:rpushg 1 do[1]=%for%to%%do%#S#108
22:pushg 2 %for%to%%do%#S#108[2]=18
24:<= 
25:jmpFalse (1)36 
28:pushthis 

29:invoke 535 0 1 #S#535:1027:descInx:535 
thisObj = #S#535[loop,loop][]  thisStack = loop[do,do,loop][]
1:rstore 1 loop->#S#535[1]
3:allocEventQ 0 
5:mvStack 
thisObj = #S#535[loop,loop][]  thisStack = #S#535[loop,loop][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = #S#535[loop,loop][]  thisStack = #S#535[loop,loop][]
10:pushthis 
11:rpushg 1 #S#535[1]=loop
13:rpushg 1 loop[1]=do
15:rpushg 1 do[1]=%for%to%%do%#S#108
thisObj = #S#535[loop,loop,%for%to%%do%#S#108][]  thisStack = #S#535[loop,loop,%for%to%%do%#S#108][]

17:sendv  1 body#SB#550:1028:descInx:550 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = #S#535[loop,loop,%for%to%%do%#S#108][]
1:rstore 2 %for%to%%do%#S#108->body#SB#550[2]
3:allocEventQ 0 
5:mvStack 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = body#SB#550[#S#535,#S#535][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = body#SB#550[#S#535,#S#535][]
10:pushthis 
11:rpushg 2 body#SB#550[2]=%for%to%%do%#S#108
13:rpushg 2 %for%to%%do%#S#108[2]=print
15:rpushg 1 print[1]=String
17:pushthis 
18:rpushg 2 body#SB#550[2]=%for%to%%do%#S#108
20:pushg 3 %for%to%%do%#S#108[3]=3
22:xpushg 1 String[4]=116
xpushg:
Object: String:1017 lsc: 0
VFields: 18 105 110 116 101 103 101 114 65 114 114 97 121 83 116 97 114 116 49 0 
Rfields: LIB:1004 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
VStack: 
RStack: 
VdtTable: 0 0 0 0 
lscStack: 
--------------

24:%prim 2 116 t
26:rtnEventQ 0 
28:setThisStack 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = #S#535[loop,loop][]
29:pushthis 

30:rtn D body#SB#550:1028:descInx:550  to: #S#535:1027:descInx:535 
thisObj = #S#535[loop,loop,body#SB#550][]  thisStack = #S#535[loop,loop,body#SB#550][]
19:rpop 
20:pushthis 
21:rpushg 1 #S#535[1]=loop
23:rpushg 1 loop[1]=do
25:rpushg 1 do[1]=%for%to%%do%#S#108
27:pushthis 
28:rpushg 1 #S#535[1]=loop
30:rpushg 1 loop[1]=do
32:rpushg 1 do[1]=%for%to%%do%#S#108
34:pushg 3 %for%to%%do%#S#108[3]=3
36:pushc 1 
38:+ 3 1
39:storeg 3 %for%to%%do%#S#108[3]=4
41:break 1 81 
10:pushthis 
11:rpushg 1 loop[1]=do
13:rpushg 1 do[1]=%for%to%%do%#S#108
15:pushg 3 %for%to%%do%#S#108[3]=4
17:pushthis 
18:rpushg 1 loop[1]=do
20:rpushg 1 do[1]=%for%to%%do%#S#108
22:pushg 2 %for%to%%do%#S#108[2]=18
24:<= 
25:jmpFalse (1)36 
28:pushthis 

29:invoke 535 0 1 #S#535:1029:descInx:535 
thisObj = #S#535[loop,loop][]  thisStack = loop[do,do,loop][]
1:rstore 1 loop->#S#535[1]
3:allocEventQ 0 
5:mvStack 
thisObj = #S#535[loop,loop][]  thisStack = #S#535[loop,loop][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = #S#535[loop,loop][]  thisStack = #S#535[loop,loop][]
10:pushthis 
11:rpushg 1 #S#535[1]=loop
13:rpushg 1 loop[1]=do
15:rpushg 1 do[1]=%for%to%%do%#S#108
thisObj = #S#535[loop,loop,%for%to%%do%#S#108][]  thisStack = #S#535[loop,loop,%for%to%%do%#S#108][]

17:sendv  1 body#SB#550:1030:descInx:550 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = #S#535[loop,loop,%for%to%%do%#S#108][]
1:rstore 2 %for%to%%do%#S#108->body#SB#550[2]
3:allocEventQ 0 
5:mvStack 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = body#SB#550[#S#535,#S#535][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = body#SB#550[#S#535,#S#535][]
10:pushthis 
11:rpushg 2 body#SB#550[2]=%for%to%%do%#S#108
13:rpushg 2 %for%to%%do%#S#108[2]=print
15:rpushg 1 print[1]=String
17:pushthis 
18:rpushg 2 body#SB#550[2]=%for%to%%do%#S#108
20:pushg 3 %for%to%%do%#S#108[3]=4
22:xpushg 1 String[5]=101
xpushg:
Object: String:1017 lsc: 0
VFields: 18 105 110 116 101 103 101 114 65 114 114 97 121 83 116 97 114 116 49 0 
Rfields: LIB:1004 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
VStack: 
RStack: 
VdtTable: 0 0 0 0 
lscStack: 
--------------

24:%prim 2 101 e
26:rtnEventQ 0 
28:setThisStack 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = #S#535[loop,loop][]
29:pushthis 

30:rtn D body#SB#550:1030:descInx:550  to: #S#535:1029:descInx:535 
thisObj = #S#535[loop,loop,body#SB#550][]  thisStack = #S#535[loop,loop,body#SB#550][]
19:rpop 
20:pushthis 
21:rpushg 1 #S#535[1]=loop
23:rpushg 1 loop[1]=do
25:rpushg 1 do[1]=%for%to%%do%#S#108
27:pushthis 
28:rpushg 1 #S#535[1]=loop
30:rpushg 1 loop[1]=do
32:rpushg 1 do[1]=%for%to%%do%#S#108
34:pushg 3 %for%to%%do%#S#108[3]=4
36:pushc 1 
38:+ 4 1
39:storeg 3 %for%to%%do%#S#108[3]=5
41:break 1 81 
10:pushthis 
11:rpushg 1 loop[1]=do
13:rpushg 1 do[1]=%for%to%%do%#S#108
15:pushg 3 %for%to%%do%#S#108[3]=5
17:pushthis 
18:rpushg 1 loop[1]=do
20:rpushg 1 do[1]=%for%to%%do%#S#108
22:pushg 2 %for%to%%do%#S#108[2]=18
24:<= 
25:jmpFalse (1)36 
28:pushthis 

29:invoke 535 0 1 #S#535:1031:descInx:535 
thisObj = #S#535[loop,loop][]  thisStack = loop[do,do,loop][]
1:rstore 1 loop->#S#535[1]
3:allocEventQ 0 
5:mvStack 
thisObj = #S#535[loop,loop][]  thisStack = #S#535[loop,loop][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = #S#535[loop,loop][]  thisStack = #S#535[loop,loop][]
10:pushthis 
11:rpushg 1 #S#535[1]=loop
13:rpushg 1 loop[1]=do
15:rpushg 1 do[1]=%for%to%%do%#S#108
thisObj = #S#535[loop,loop,%for%to%%do%#S#108][]  thisStack = #S#535[loop,loop,%for%to%%do%#S#108][]

17:sendv  1 body#SB#550:1032:descInx:550 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = #S#535[loop,loop,%for%to%%do%#S#108][]
1:rstore 2 %for%to%%do%#S#108->body#SB#550[2]
3:allocEventQ 0 
5:mvStack 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = body#SB#550[#S#535,#S#535][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = body#SB#550[#S#535,#S#535][]
10:pushthis 
11:rpushg 2 body#SB#550[2]=%for%to%%do%#S#108
13:rpushg 2 %for%to%%do%#S#108[2]=print
15:rpushg 1 print[1]=String
17:pushthis 
18:rpushg 2 body#SB#550[2]=%for%to%%do%#S#108
20:pushg 3 %for%to%%do%#S#108[3]=5
22:xpushg 1 String[6]=103
xpushg:
Object: String:1017 lsc: 0
VFields: 18 105 110 116 101 103 101 114 65 114 114 97 121 83 116 97 114 116 49 0 
Rfields: LIB:1004 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
VStack: 
RStack: 
VdtTable: 0 0 0 0 
lscStack: 
--------------

24:%prim 2 103 g
26:rtnEventQ 0 
28:setThisStack 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = #S#535[loop,loop][]
29:pushthis 

30:rtn D body#SB#550:1032:descInx:550  to: #S#535:1031:descInx:535 
thisObj = #S#535[loop,loop,body#SB#550][]  thisStack = #S#535[loop,loop,body#SB#550][]
19:rpop 
20:pushthis 
21:rpushg 1 #S#535[1]=loop
23:rpushg 1 loop[1]=do
25:rpushg 1 do[1]=%for%to%%do%#S#108
27:pushthis 
28:rpushg 1 #S#535[1]=loop
30:rpushg 1 loop[1]=do
32:rpushg 1 do[1]=%for%to%%do%#S#108
34:pushg 3 %for%to%%do%#S#108[3]=5
36:pushc 1 
38:+ 5 1
39:storeg 3 %for%to%%do%#S#108[3]=6
41:break 1 81 
10:pushthis 
11:rpushg 1 loop[1]=do
13:rpushg 1 do[1]=%for%to%%do%#S#108
15:pushg 3 %for%to%%do%#S#108[3]=6
17:pushthis 
18:rpushg 1 loop[1]=do
20:rpushg 1 do[1]=%for%to%%do%#S#108
22:pushg 2 %for%to%%do%#S#108[2]=18
24:<= 
25:jmpFalse (1)36 
28:pushthis 

29:invoke 535 0 1 #S#535:1033:descInx:535 
thisObj = #S#535[loop,loop][]  thisStack = loop[do,do,loop][]
1:rstore 1 loop->#S#535[1]
3:allocEventQ 0 
5:mvStack 
thisObj = #S#535[loop,loop][]  thisStack = #S#535[loop,loop][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = #S#535[loop,loop][]  thisStack = #S#535[loop,loop][]
10:pushthis 
11:rpushg 1 #S#535[1]=loop
13:rpushg 1 loop[1]=do
15:rpushg 1 do[1]=%for%to%%do%#S#108
thisObj = #S#535[loop,loop,%for%to%%do%#S#108][]  thisStack = #S#535[loop,loop,%for%to%%do%#S#108][]

17:sendv  1 body#SB#550:1034:descInx:550 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = #S#535[loop,loop,%for%to%%do%#S#108][]
1:rstore 2 %for%to%%do%#S#108->body#SB#550[2]
3:allocEventQ 0 
5:mvStack 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = body#SB#550[#S#535,#S#535][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = body#SB#550[#S#535,#S#535][]
10:pushthis 
11:rpushg 2 body#SB#550[2]=%for%to%%do%#S#108
13:rpushg 2 %for%to%%do%#S#108[2]=print
15:rpushg 1 print[1]=String
17:pushthis 
18:rpushg 2 body#SB#550[2]=%for%to%%do%#S#108
20:pushg 3 %for%to%%do%#S#108[3]=6
22:xpushg 1 String[7]=101
xpushg:
Object: String:1017 lsc: 0
VFields: 18 105 110 116 101 103 101 114 65 114 114 97 121 83 116 97 114 116 49 0 
Rfields: LIB:1004 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
VStack: 
RStack: 
VdtTable: 0 0 0 0 
lscStack: 
--------------

24:%prim 2 101 e
26:rtnEventQ 0 
28:setThisStack 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = #S#535[loop,loop][]
29:pushthis 

30:rtn D body#SB#550:1034:descInx:550  to: #S#535:1033:descInx:535 
thisObj = #S#535[loop,loop,body#SB#550][]  thisStack = #S#535[loop,loop,body#SB#550][]
19:rpop 
20:pushthis 
21:rpushg 1 #S#535[1]=loop
23:rpushg 1 loop[1]=do
25:rpushg 1 do[1]=%for%to%%do%#S#108
27:pushthis 
28:rpushg 1 #S#535[1]=loop
30:rpushg 1 loop[1]=do
32:rpushg 1 do[1]=%for%to%%do%#S#108
34:pushg 3 %for%to%%do%#S#108[3]=6
36:pushc 1 
38:+ 6 1
39:storeg 3 %for%to%%do%#S#108[3]=7
41:break 1 81 
10:pushthis 
11:rpushg 1 loop[1]=do
13:rpushg 1 do[1]=%for%to%%do%#S#108
15:pushg 3 %for%to%%do%#S#108[3]=7
17:pushthis 
18:rpushg 1 loop[1]=do
20:rpushg 1 do[1]=%for%to%%do%#S#108
22:pushg 2 %for%to%%do%#S#108[2]=18
24:<= 
25:jmpFalse (1)36 
28:pushthis 

29:invoke 535 0 1 #S#535:1035:descInx:535 
thisObj = #S#535[loop,loop][]  thisStack = loop[do,do,loop][]
1:rstore 1 loop->#S#535[1]
3:allocEventQ 0 
5:mvStack 
thisObj = #S#535[loop,loop][]  thisStack = #S#535[loop,loop][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = #S#535[loop,loop][]  thisStack = #S#535[loop,loop][]
10:pushthis 
11:rpushg 1 #S#535[1]=loop
13:rpushg 1 loop[1]=do
15:rpushg 1 do[1]=%for%to%%do%#S#108
thisObj = #S#535[loop,loop,%for%to%%do%#S#108][]  thisStack = #S#535[loop,loop,%for%to%%do%#S#108][]

17:sendv  1 body#SB#550:1036:descInx:550 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = #S#535[loop,loop,%for%to%%do%#S#108][]
1:rstore 2 %for%to%%do%#S#108->body#SB#550[2]
3:allocEventQ 0 
5:mvStack 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = body#SB#550[#S#535,#S#535][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = body#SB#550[#S#535,#S#535][]
10:pushthis 
11:rpushg 2 body#SB#550[2]=%for%to%%do%#S#108
13:rpushg 2 %for%to%%do%#S#108[2]=print
15:rpushg 1 print[1]=String
17:pushthis 
18:rpushg 2 body#SB#550[2]=%for%to%%do%#S#108
20:pushg 3 %for%to%%do%#S#108[3]=7
22:xpushg 1 String[8]=114
xpushg:
Object: String:1017 lsc: 0
VFields: 18 105 110 116 101 103 101 114 65 114 114 97 121 83 116 97 114 116 49 0 
Rfields: LIB:1004 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
VStack: 
RStack: 
VdtTable: 0 0 0 0 
lscStack: 
--------------

24:%prim 2 114 r
26:rtnEventQ 0 
28:setThisStack 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = #S#535[loop,loop][]
29:pushthis 

30:rtn D body#SB#550:1036:descInx:550  to: #S#535:1035:descInx:535 
thisObj = #S#535[loop,loop,body#SB#550][]  thisStack = #S#535[loop,loop,body#SB#550][]
19:rpop 
20:pushthis 
21:rpushg 1 #S#535[1]=loop
23:rpushg 1 loop[1]=do
25:rpushg 1 do[1]=%for%to%%do%#S#108
27:pushthis 
28:rpushg 1 #S#535[1]=loop
30:rpushg 1 loop[1]=do
32:rpushg 1 do[1]=%for%to%%do%#S#108
34:pushg 3 %for%to%%do%#S#108[3]=7
36:pushc 1 
38:+ 7 1
39:storeg 3 %for%to%%do%#S#108[3]=8
41:break 1 81 
10:pushthis 
11:rpushg 1 loop[1]=do
13:rpushg 1 do[1]=%for%to%%do%#S#108
15:pushg 3 %for%to%%do%#S#108[3]=8
17:pushthis 
18:rpushg 1 loop[1]=do
20:rpushg 1 do[1]=%for%to%%do%#S#108
22:pushg 2 %for%to%%do%#S#108[2]=18
24:<= 
25:jmpFalse (1)36 
28:pushthis 

29:invoke 535 0 1 #S#535:1037:descInx:535 
thisObj = #S#535[loop,loop][]  thisStack = loop[do,do,loop][]
1:rstore 1 loop->#S#535[1]
3:allocEventQ 0 
5:mvStack 
thisObj = #S#535[loop,loop][]  thisStack = #S#535[loop,loop][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = #S#535[loop,loop][]  thisStack = #S#535[loop,loop][]
10:pushthis 
11:rpushg 1 #S#535[1]=loop
13:rpushg 1 loop[1]=do
15:rpushg 1 do[1]=%for%to%%do%#S#108
thisObj = #S#535[loop,loop,%for%to%%do%#S#108][]  thisStack = #S#535[loop,loop,%for%to%%do%#S#108][]

17:sendv  1 body#SB#550:1038:descInx:550 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = #S#535[loop,loop,%for%to%%do%#S#108][]
1:rstore 2 %for%to%%do%#S#108->body#SB#550[2]
3:allocEventQ 0 
5:mvStack 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = body#SB#550[#S#535,#S#535][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = body#SB#550[#S#535,#S#535][]
10:pushthis 
11:rpushg 2 body#SB#550[2]=%for%to%%do%#S#108
13:rpushg 2 %for%to%%do%#S#108[2]=print
15:rpushg 1 print[1]=String
17:pushthis 
18:rpushg 2 body#SB#550[2]=%for%to%%do%#S#108
20:pushg 3 %for%to%%do%#S#108[3]=8
22:xpushg 1 String[9]=65
xpushg:
Object: String:1017 lsc: 0
VFields: 18 105 110 116 101 103 101 114 65 114 114 97 121 83 116 97 114 116 49 0 
Rfields: LIB:1004 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
VStack: 
RStack: 
VdtTable: 0 0 0 0 
lscStack: 
--------------

24:%prim 2 65 A
26:rtnEventQ 0 
28:setThisStack 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = #S#535[loop,loop][]
29:pushthis 

30:rtn D body#SB#550:1038:descInx:550  to: #S#535:1037:descInx:535 
thisObj = #S#535[loop,loop,body#SB#550][]  thisStack = #S#535[loop,loop,body#SB#550][]
19:rpop 
20:pushthis 
21:rpushg 1 #S#535[1]=loop
23:rpushg 1 loop[1]=do
25:rpushg 1 do[1]=%for%to%%do%#S#108
27:pushthis 
28:rpushg 1 #S#535[1]=loop
30:rpushg 1 loop[1]=do
32:rpushg 1 do[1]=%for%to%%do%#S#108
34:pushg 3 %for%to%%do%#S#108[3]=8
36:pushc 1 
38:+ 8 1
39:storeg 3 %for%to%%do%#S#108[3]=9
41:break 1 81 
10:pushthis 
11:rpushg 1 loop[1]=do
13:rpushg 1 do[1]=%for%to%%do%#S#108
15:pushg 3 %for%to%%do%#S#108[3]=9
17:pushthis 
18:rpushg 1 loop[1]=do
20:rpushg 1 do[1]=%for%to%%do%#S#108
22:pushg 2 %for%to%%do%#S#108[2]=18
24:<= 
25:jmpFalse (1)36 
28:pushthis 

29:invoke 535 0 1 #S#535:1039:descInx:535 
thisObj = #S#535[loop,loop][]  thisStack = loop[do,do,loop][]
1:rstore 1 loop->#S#535[1]
3:allocEventQ 0 
5:mvStack 
thisObj = #S#535[loop,loop][]  thisStack = #S#535[loop,loop][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = #S#535[loop,loop][]  thisStack = #S#535[loop,loop][]
10:pushthis 
11:rpushg 1 #S#535[1]=loop
13:rpushg 1 loop[1]=do
15:rpushg 1 do[1]=%for%to%%do%#S#108
thisObj = #S#535[loop,loop,%for%to%%do%#S#108][]  thisStack = #S#535[loop,loop,%for%to%%do%#S#108][]

17:sendv  1 body#SB#550:1040:descInx:550 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = #S#535[loop,loop,%for%to%%do%#S#108][]
1:rstore 2 %for%to%%do%#S#108->body#SB#550[2]
3:allocEventQ 0 
5:mvStack 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = body#SB#550[#S#535,#S#535][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = body#SB#550[#S#535,#S#535][]
10:pushthis 
11:rpushg 2 body#SB#550[2]=%for%to%%do%#S#108
13:rpushg 2 %for%to%%do%#S#108[2]=print
15:rpushg 1 print[1]=String
17:pushthis 
18:rpushg 2 body#SB#550[2]=%for%to%%do%#S#108
20:pushg 3 %for%to%%do%#S#108[3]=9
22:xpushg 1 String[10]=114
xpushg:
Object: String:1017 lsc: 0
VFields: 18 105 110 116 101 103 101 114 65 114 114 97 121 83 116 97 114 116 49 0 
Rfields: LIB:1004 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
VStack: 
RStack: 
VdtTable: 0 0 0 0 
lscStack: 
--------------

24:%prim 2 114 r
26:rtnEventQ 0 
28:setThisStack 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = #S#535[loop,loop][]
29:pushthis 

30:rtn D body#SB#550:1040:descInx:550  to: #S#535:1039:descInx:535 
thisObj = #S#535[loop,loop,body#SB#550][]  thisStack = #S#535[loop,loop,body#SB#550][]
19:rpop 
20:pushthis 
21:rpushg 1 #S#535[1]=loop
23:rpushg 1 loop[1]=do
25:rpushg 1 do[1]=%for%to%%do%#S#108
27:pushthis 
28:rpushg 1 #S#535[1]=loop
30:rpushg 1 loop[1]=do
32:rpushg 1 do[1]=%for%to%%do%#S#108
34:pushg 3 %for%to%%do%#S#108[3]=9
36:pushc 1 
38:+ 9 1
39:storeg 3 %for%to%%do%#S#108[3]=10
41:break 1 81 
10:pushthis 
11:rpushg 1 loop[1]=do
13:rpushg 1 do[1]=%for%to%%do%#S#108
15:pushg 3 %for%to%%do%#S#108[3]=10
17:pushthis 
18:rpushg 1 loop[1]=do
20:rpushg 1 do[1]=%for%to%%do%#S#108
22:pushg 2 %for%to%%do%#S#108[2]=18
24:<= 
25:jmpFalse (1)36 
28:pushthis 

29:invoke 535 0 1 #S#535:1041:descInx:535 
thisObj = #S#535[loop,loop][]  thisStack = loop[do,do,loop][]
1:rstore 1 loop->#S#535[1]
3:allocEventQ 0 
5:mvStack 
thisObj = #S#535[loop,loop][]  thisStack = #S#535[loop,loop][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = #S#535[loop,loop][]  thisStack = #S#535[loop,loop][]
10:pushthis 
11:rpushg 1 #S#535[1]=loop
13:rpushg 1 loop[1]=do
15:rpushg 1 do[1]=%for%to%%do%#S#108
thisObj = #S#535[loop,loop,%for%to%%do%#S#108][]  thisStack = #S#535[loop,loop,%for%to%%do%#S#108][]

17:sendv  1 body#SB#550:1042:descInx:550 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = #S#535[loop,loop,%for%to%%do%#S#108][]
1:rstore 2 %for%to%%do%#S#108->body#SB#550[2]
3:allocEventQ 0 
5:mvStack 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = body#SB#550[#S#535,#S#535][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = body#SB#550[#S#535,#S#535][]
10:pushthis 
11:rpushg 2 body#SB#550[2]=%for%to%%do%#S#108
13:rpushg 2 %for%to%%do%#S#108[2]=print
15:rpushg 1 print[1]=String
17:pushthis 
18:rpushg 2 body#SB#550[2]=%for%to%%do%#S#108
20:pushg 3 %for%to%%do%#S#108[3]=10
22:xpushg 1 String[11]=114
xpushg:
Object: String:1017 lsc: 0
VFields: 18 105 110 116 101 103 101 114 65 114 114 97 121 83 116 97 114 116 49 0 
Rfields: LIB:1004 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
VStack: 
RStack: 
VdtTable: 0 0 0 0 
lscStack: 
--------------

24:%prim 2 114 r
26:rtnEventQ 0 
28:setThisStack 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = #S#535[loop,loop][]
29:pushthis 

30:rtn D body#SB#550:1042:descInx:550  to: #S#535:1041:descInx:535 
thisObj = #S#535[loop,loop,body#SB#550][]  thisStack = #S#535[loop,loop,body#SB#550][]
19:rpop 
20:pushthis 
21:rpushg 1 #S#535[1]=loop
23:rpushg 1 loop[1]=do
25:rpushg 1 do[1]=%for%to%%do%#S#108
27:pushthis 
28:rpushg 1 #S#535[1]=loop
30:rpushg 1 loop[1]=do
32:rpushg 1 do[1]=%for%to%%do%#S#108
34:pushg 3 %for%to%%do%#S#108[3]=10
36:pushc 1 
38:+ 10 1
39:storeg 3 %for%to%%do%#S#108[3]=11
41:break 1 81 
10:pushthis 
11:rpushg 1 loop[1]=do
13:rpushg 1 do[1]=%for%to%%do%#S#108
15:pushg 3 %for%to%%do%#S#108[3]=11
17:pushthis 
18:rpushg 1 loop[1]=do
20:rpushg 1 do[1]=%for%to%%do%#S#108
22:pushg 2 %for%to%%do%#S#108[2]=18
24:<= 
25:jmpFalse (1)36 
28:pushthis 

29:invoke 535 0 1 #S#535:1043:descInx:535 
thisObj = #S#535[loop,loop][]  thisStack = loop[do,do,loop][]
1:rstore 1 loop->#S#535[1]
3:allocEventQ 0 
5:mvStack 
thisObj = #S#535[loop,loop][]  thisStack = #S#535[loop,loop][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = #S#535[loop,loop][]  thisStack = #S#535[loop,loop][]
10:pushthis 
11:rpushg 1 #S#535[1]=loop
13:rpushg 1 loop[1]=do
15:rpushg 1 do[1]=%for%to%%do%#S#108
thisObj = #S#535[loop,loop,%for%to%%do%#S#108][]  thisStack = #S#535[loop,loop,%for%to%%do%#S#108][]

17:sendv  1 body#SB#550:1044:descInx:550 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = #S#535[loop,loop,%for%to%%do%#S#108][]
1:rstore 2 %for%to%%do%#S#108->body#SB#550[2]
3:allocEventQ 0 
5:mvStack 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = body#SB#550[#S#535,#S#535][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = body#SB#550[#S#535,#S#535][]
10:pushthis 
11:rpushg 2 body#SB#550[2]=%for%to%%do%#S#108
13:rpushg 2 %for%to%%do%#S#108[2]=print
15:rpushg 1 print[1]=String
17:pushthis 
18:rpushg 2 body#SB#550[2]=%for%to%%do%#S#108
20:pushg 3 %for%to%%do%#S#108[3]=11
22:xpushg 1 String[12]=97
xpushg:
Object: String:1017 lsc: 0
VFields: 18 105 110 116 101 103 101 114 65 114 114 97 121 83 116 97 114 116 49 0 
Rfields: LIB:1004 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
VStack: 
RStack: 
VdtTable: 0 0 0 0 
lscStack: 
--------------

24:%prim 2 97 a
26:rtnEventQ 0 
28:setThisStack 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = #S#535[loop,loop][]
29:pushthis 

30:rtn D body#SB#550:1044:descInx:550  to: #S#535:1043:descInx:535 
thisObj = #S#535[loop,loop,body#SB#550][]  thisStack = #S#535[loop,loop,body#SB#550][]
19:rpop 
20:pushthis 
21:rpushg 1 #S#535[1]=loop
23:rpushg 1 loop[1]=do
25:rpushg 1 do[1]=%for%to%%do%#S#108
27:pushthis 
28:rpushg 1 #S#535[1]=loop
30:rpushg 1 loop[1]=do
32:rpushg 1 do[1]=%for%to%%do%#S#108
34:pushg 3 %for%to%%do%#S#108[3]=11
36:pushc 1 
38:+ 11 1
39:storeg 3 %for%to%%do%#S#108[3]=12
41:break 1 81 
10:pushthis 
11:rpushg 1 loop[1]=do
13:rpushg 1 do[1]=%for%to%%do%#S#108
15:pushg 3 %for%to%%do%#S#108[3]=12
17:pushthis 
18:rpushg 1 loop[1]=do
20:rpushg 1 do[1]=%for%to%%do%#S#108
22:pushg 2 %for%to%%do%#S#108[2]=18
24:<= 
25:jmpFalse (1)36 
28:pushthis 

29:invoke 535 0 1 #S#535:1045:descInx:535 
thisObj = #S#535[loop,loop][]  thisStack = loop[do,do,loop][]
1:rstore 1 loop->#S#535[1]
3:allocEventQ 0 
5:mvStack 
thisObj = #S#535[loop,loop][]  thisStack = #S#535[loop,loop][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = #S#535[loop,loop][]  thisStack = #S#535[loop,loop][]
10:pushthis 
11:rpushg 1 #S#535[1]=loop
13:rpushg 1 loop[1]=do
15:rpushg 1 do[1]=%for%to%%do%#S#108
thisObj = #S#535[loop,loop,%for%to%%do%#S#108][]  thisStack = #S#535[loop,loop,%for%to%%do%#S#108][]

17:sendv  1 body#SB#550:1046:descInx:550 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = #S#535[loop,loop,%for%to%%do%#S#108][]
1:rstore 2 %for%to%%do%#S#108->body#SB#550[2]
3:allocEventQ 0 
5:mvStack 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = body#SB#550[#S#535,#S#535][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = body#SB#550[#S#535,#S#535][]
10:pushthis 
11:rpushg 2 body#SB#550[2]=%for%to%%do%#S#108
13:rpushg 2 %for%to%%do%#S#108[2]=print
15:rpushg 1 print[1]=String
17:pushthis 
18:rpushg 2 body#SB#550[2]=%for%to%%do%#S#108
20:pushg 3 %for%to%%do%#S#108[3]=12
22:xpushg 1 String[13]=121
xpushg:
Object: String:1017 lsc: 0
VFields: 18 105 110 116 101 103 101 114 65 114 114 97 121 83 116 97 114 116 49 0 
Rfields: LIB:1004 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
VStack: 
RStack: 
VdtTable: 0 0 0 0 
lscStack: 
--------------

24:%prim 2 121 y
26:rtnEventQ 0 
28:setThisStack 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = #S#535[loop,loop][]
29:pushthis 

30:rtn D body#SB#550:1046:descInx:550  to: #S#535:1045:descInx:535 
thisObj = #S#535[loop,loop,body#SB#550][]  thisStack = #S#535[loop,loop,body#SB#550][]
19:rpop 
20:pushthis 
21:rpushg 1 #S#535[1]=loop
23:rpushg 1 loop[1]=do
25:rpushg 1 do[1]=%for%to%%do%#S#108
27:pushthis 
28:rpushg 1 #S#535[1]=loop
30:rpushg 1 loop[1]=do
32:rpushg 1 do[1]=%for%to%%do%#S#108
34:pushg 3 %for%to%%do%#S#108[3]=12
36:pushc 1 
38:+ 12 1
39:storeg 3 %for%to%%do%#S#108[3]=13
41:break 1 81 
10:pushthis 
11:rpushg 1 loop[1]=do
13:rpushg 1 do[1]=%for%to%%do%#S#108
15:pushg 3 %for%to%%do%#S#108[3]=13
17:pushthis 
18:rpushg 1 loop[1]=do
20:rpushg 1 do[1]=%for%to%%do%#S#108
22:pushg 2 %for%to%%do%#S#108[2]=18
24:<= 
25:jmpFalse (1)36 
28:pushthis 

29:invoke 535 0 1 #S#535:1047:descInx:535 
thisObj = #S#535[loop,loop][]  thisStack = loop[do,do,loop][]
1:rstore 1 loop->#S#535[1]
3:allocEventQ 0 
5:mvStack 
thisObj = #S#535[loop,loop][]  thisStack = #S#535[loop,loop][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = #S#535[loop,loop][]  thisStack = #S#535[loop,loop][]
10:pushthis 
11:rpushg 1 #S#535[1]=loop
13:rpushg 1 loop[1]=do
15:rpushg 1 do[1]=%for%to%%do%#S#108
thisObj = #S#535[loop,loop,%for%to%%do%#S#108][]  thisStack = #S#535[loop,loop,%for%to%%do%#S#108][]

17:sendv  1 body#SB#550:1048:descInx:550 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = #S#535[loop,loop,%for%to%%do%#S#108][]
1:rstore 2 %for%to%%do%#S#108->body#SB#550[2]
3:allocEventQ 0 
5:mvStack 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = body#SB#550[#S#535,#S#535][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = body#SB#550[#S#535,#S#535][]
10:pushthis 
11:rpushg 2 body#SB#550[2]=%for%to%%do%#S#108
13:rpushg 2 %for%to%%do%#S#108[2]=print
15:rpushg 1 print[1]=String
17:pushthis 
18:rpushg 2 body#SB#550[2]=%for%to%%do%#S#108
20:pushg 3 %for%to%%do%#S#108[3]=13
22:xpushg 1 String[14]=83
xpushg:
Object: String:1017 lsc: 0
VFields: 18 105 110 116 101 103 101 114 65 114 114 97 121 83 116 97 114 116 49 0 
Rfields: LIB:1004 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
VStack: 
RStack: 
VdtTable: 0 0 0 0 
lscStack: 
--------------

24:%prim 2 83 S
26:rtnEventQ 0 
28:setThisStack 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = #S#535[loop,loop][]
29:pushthis 

30:rtn D body#SB#550:1048:descInx:550  to: #S#535:1047:descInx:535 
thisObj = #S#535[loop,loop,body#SB#550][]  thisStack = #S#535[loop,loop,body#SB#550][]
19:rpop 
20:pushthis 
21:rpushg 1 #S#535[1]=loop
23:rpushg 1 loop[1]=do
25:rpushg 1 do[1]=%for%to%%do%#S#108
27:pushthis 
28:rpushg 1 #S#535[1]=loop
30:rpushg 1 loop[1]=do
32:rpushg 1 do[1]=%for%to%%do%#S#108
34:pushg 3 %for%to%%do%#S#108[3]=13
36:pushc 1 
38:+ 13 1
39:storeg 3 %for%to%%do%#S#108[3]=14
41:break 1 81 
10:pushthis 
11:rpushg 1 loop[1]=do
13:rpushg 1 do[1]=%for%to%%do%#S#108
15:pushg 3 %for%to%%do%#S#108[3]=14
17:pushthis 
18:rpushg 1 loop[1]=do
20:rpushg 1 do[1]=%for%to%%do%#S#108
22:pushg 2 %for%to%%do%#S#108[2]=18
24:<= 
25:jmpFalse (1)36 
28:pushthis 

29:invoke 535 0 1 #S#535:1049:descInx:535 
thisObj = #S#535[loop,loop][]  thisStack = loop[do,do,loop][]
1:rstore 1 loop->#S#535[1]
3:allocEventQ 0 
5:mvStack 
thisObj = #S#535[loop,loop][]  thisStack = #S#535[loop,loop][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = #S#535[loop,loop][]  thisStack = #S#535[loop,loop][]
10:pushthis 
11:rpushg 1 #S#535[1]=loop
13:rpushg 1 loop[1]=do
15:rpushg 1 do[1]=%for%to%%do%#S#108
thisObj = #S#535[loop,loop,%for%to%%do%#S#108][]  thisStack = #S#535[loop,loop,%for%to%%do%#S#108][]

17:sendv  1 body#SB#550:1050:descInx:550 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = #S#535[loop,loop,%for%to%%do%#S#108][]
1:rstore 2 %for%to%%do%#S#108->body#SB#550[2]
3:allocEventQ 0 
5:mvStack 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = body#SB#550[#S#535,#S#535][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = body#SB#550[#S#535,#S#535][]
10:pushthis 
11:rpushg 2 body#SB#550[2]=%for%to%%do%#S#108
13:rpushg 2 %for%to%%do%#S#108[2]=print
15:rpushg 1 print[1]=String
17:pushthis 
18:rpushg 2 body#SB#550[2]=%for%to%%do%#S#108
20:pushg 3 %for%to%%do%#S#108[3]=14
22:xpushg 1 String[15]=116
xpushg:
Object: String:1017 lsc: 0
VFields: 18 105 110 116 101 103 101 114 65 114 114 97 121 83 116 97 114 116 49 0 
Rfields: LIB:1004 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
VStack: 
RStack: 
VdtTable: 0 0 0 0 
lscStack: 
--------------

24:%prim 2 116 t
26:rtnEventQ 0 
28:setThisStack 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = #S#535[loop,loop][]
29:pushthis 

30:rtn D body#SB#550:1050:descInx:550  to: #S#535:1049:descInx:535 
thisObj = #S#535[loop,loop,body#SB#550][]  thisStack = #S#535[loop,loop,body#SB#550][]
19:rpop 
20:pushthis 
21:rpushg 1 #S#535[1]=loop
23:rpushg 1 loop[1]=do
25:rpushg 1 do[1]=%for%to%%do%#S#108
27:pushthis 
28:rpushg 1 #S#535[1]=loop
30:rpushg 1 loop[1]=do
32:rpushg 1 do[1]=%for%to%%do%#S#108
34:pushg 3 %for%to%%do%#S#108[3]=14
36:pushc 1 
38:+ 14 1
39:storeg 3 %for%to%%do%#S#108[3]=15
41:break 1 81 
10:pushthis 
11:rpushg 1 loop[1]=do
13:rpushg 1 do[1]=%for%to%%do%#S#108
15:pushg 3 %for%to%%do%#S#108[3]=15
17:pushthis 
18:rpushg 1 loop[1]=do
20:rpushg 1 do[1]=%for%to%%do%#S#108
22:pushg 2 %for%to%%do%#S#108[2]=18
24:<= 
25:jmpFalse (1)36 
28:pushthis 

29:invoke 535 0 1 #S#535:1051:descInx:535 
thisObj = #S#535[loop,loop][]  thisStack = loop[do,do,loop][]
1:rstore 1 loop->#S#535[1]
3:allocEventQ 0 
5:mvStack 
thisObj = #S#535[loop,loop][]  thisStack = #S#535[loop,loop][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = #S#535[loop,loop][]  thisStack = #S#535[loop,loop][]
10:pushthis 
11:rpushg 1 #S#535[1]=loop
13:rpushg 1 loop[1]=do
15:rpushg 1 do[1]=%for%to%%do%#S#108
thisObj = #S#535[loop,loop,%for%to%%do%#S#108][]  thisStack = #S#535[loop,loop,%for%to%%do%#S#108][]

17:sendv  1 body#SB#550:1052:descInx:550 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = #S#535[loop,loop,%for%to%%do%#S#108][]
1:rstore 2 %for%to%%do%#S#108->body#SB#550[2]
3:allocEventQ 0 
5:mvStack 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = body#SB#550[#S#535,#S#535][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = body#SB#550[#S#535,#S#535][]
10:pushthis 
11:rpushg 2 body#SB#550[2]=%for%to%%do%#S#108
13:rpushg 2 %for%to%%do%#S#108[2]=print
15:rpushg 1 print[1]=String
17:pushthis 
18:rpushg 2 body#SB#550[2]=%for%to%%do%#S#108
20:pushg 3 %for%to%%do%#S#108[3]=15
22:xpushg 1 String[16]=97
xpushg:
Object: String:1017 lsc: 0
VFields: 18 105 110 116 101 103 101 114 65 114 114 97 121 83 116 97 114 116 49 0 
Rfields: LIB:1004 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
VStack: 
RStack: 
VdtTable: 0 0 0 0 
lscStack: 
--------------

24:%prim 2 97 a
26:rtnEventQ 0 
28:setThisStack 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = #S#535[loop,loop][]
29:pushthis 

30:rtn D body#SB#550:1052:descInx:550  to: #S#535:1051:descInx:535 
thisObj = #S#535[loop,loop,body#SB#550][]  thisStack = #S#535[loop,loop,body#SB#550][]
19:rpop 
20:pushthis 
21:rpushg 1 #S#535[1]=loop
23:rpushg 1 loop[1]=do
25:rpushg 1 do[1]=%for%to%%do%#S#108
27:pushthis 
28:rpushg 1 #S#535[1]=loop
30:rpushg 1 loop[1]=do
32:rpushg 1 do[1]=%for%to%%do%#S#108
34:pushg 3 %for%to%%do%#S#108[3]=15
36:pushc 1 
38:+ 15 1
39:storeg 3 %for%to%%do%#S#108[3]=16
41:break 1 81 
10:pushthis 
11:rpushg 1 loop[1]=do
13:rpushg 1 do[1]=%for%to%%do%#S#108
15:pushg 3 %for%to%%do%#S#108[3]=16
17:pushthis 
18:rpushg 1 loop[1]=do
20:rpushg 1 do[1]=%for%to%%do%#S#108
22:pushg 2 %for%to%%do%#S#108[2]=18
24:<= 
25:jmpFalse (1)36 
28:pushthis 

29:invoke 535 0 1 #S#535:1053:descInx:535 
thisObj = #S#535[loop,loop][]  thisStack = loop[do,do,loop][]
1:rstore 1 loop->#S#535[1]
3:allocEventQ 0 
5:mvStack 
thisObj = #S#535[loop,loop][]  thisStack = #S#535[loop,loop][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = #S#535[loop,loop][]  thisStack = #S#535[loop,loop][]
10:pushthis 
11:rpushg 1 #S#535[1]=loop
13:rpushg 1 loop[1]=do
15:rpushg 1 do[1]=%for%to%%do%#S#108
thisObj = #S#535[loop,loop,%for%to%%do%#S#108][]  thisStack = #S#535[loop,loop,%for%to%%do%#S#108][]

17:sendv  1 body#SB#550:1054:descInx:550 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = #S#535[loop,loop,%for%to%%do%#S#108][]
1:rstore 2 %for%to%%do%#S#108->body#SB#550[2]
3:allocEventQ 0 
5:mvStack 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = body#SB#550[#S#535,#S#535][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = body#SB#550[#S#535,#S#535][]
10:pushthis 
11:rpushg 2 body#SB#550[2]=%for%to%%do%#S#108
13:rpushg 2 %for%to%%do%#S#108[2]=print
15:rpushg 1 print[1]=String
17:pushthis 
18:rpushg 2 body#SB#550[2]=%for%to%%do%#S#108
20:pushg 3 %for%to%%do%#S#108[3]=16
22:xpushg 1 String[17]=114
xpushg:
Object: String:1017 lsc: 0
VFields: 18 105 110 116 101 103 101 114 65 114 114 97 121 83 116 97 114 116 49 0 
Rfields: LIB:1004 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
VStack: 
RStack: 
VdtTable: 0 0 0 0 
lscStack: 
--------------

24:%prim 2 114 r
26:rtnEventQ 0 
28:setThisStack 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = #S#535[loop,loop][]
29:pushthis 

30:rtn D body#SB#550:1054:descInx:550  to: #S#535:1053:descInx:535 
thisObj = #S#535[loop,loop,body#SB#550][]  thisStack = #S#535[loop,loop,body#SB#550][]
19:rpop 
20:pushthis 
21:rpushg 1 #S#535[1]=loop
23:rpushg 1 loop[1]=do
25:rpushg 1 do[1]=%for%to%%do%#S#108
27:pushthis 
28:rpushg 1 #S#535[1]=loop
30:rpushg 1 loop[1]=do
32:rpushg 1 do[1]=%for%to%%do%#S#108
34:pushg 3 %for%to%%do%#S#108[3]=16
36:pushc 1 
38:+ 16 1
39:storeg 3 %for%to%%do%#S#108[3]=17
41:break 1 81 
10:pushthis 
11:rpushg 1 loop[1]=do
13:rpushg 1 do[1]=%for%to%%do%#S#108
15:pushg 3 %for%to%%do%#S#108[3]=17
17:pushthis 
18:rpushg 1 loop[1]=do
20:rpushg 1 do[1]=%for%to%%do%#S#108
22:pushg 2 %for%to%%do%#S#108[2]=18
24:<= 
25:jmpFalse (1)36 
28:pushthis 

29:invoke 535 0 1 #S#535:1055:descInx:535 
thisObj = #S#535[loop,loop][]  thisStack = loop[do,do,loop][]
1:rstore 1 loop->#S#535[1]
3:allocEventQ 0 
5:mvStack 
thisObj = #S#535[loop,loop][]  thisStack = #S#535[loop,loop][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = #S#535[loop,loop][]  thisStack = #S#535[loop,loop][]
10:pushthis 
11:rpushg 1 #S#535[1]=loop
13:rpushg 1 loop[1]=do
15:rpushg 1 do[1]=%for%to%%do%#S#108
thisObj = #S#535[loop,loop,%for%to%%do%#S#108][]  thisStack = #S#535[loop,loop,%for%to%%do%#S#108][]

17:sendv  1 body#SB#550:1056:descInx:550 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = #S#535[loop,loop,%for%to%%do%#S#108][]
1:rstore 2 %for%to%%do%#S#108->body#SB#550[2]
3:allocEventQ 0 
5:mvStack 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = body#SB#550[#S#535,#S#535][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = body#SB#550[#S#535,#S#535][]
10:pushthis 
11:rpushg 2 body#SB#550[2]=%for%to%%do%#S#108
13:rpushg 2 %for%to%%do%#S#108[2]=print
15:rpushg 1 print[1]=String
17:pushthis 
18:rpushg 2 body#SB#550[2]=%for%to%%do%#S#108
20:pushg 3 %for%to%%do%#S#108[3]=17
22:xpushg 1 String[18]=116
xpushg:
Object: String:1017 lsc: 0
VFields: 18 105 110 116 101 103 101 114 65 114 114 97 121 83 116 97 114 116 49 0 
Rfields: LIB:1004 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
VStack: 
RStack: 
VdtTable: 0 0 0 0 
lscStack: 
--------------

24:%prim 2 116 t
26:rtnEventQ 0 
28:setThisStack 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = #S#535[loop,loop][]
29:pushthis 

30:rtn D body#SB#550:1056:descInx:550  to: #S#535:1055:descInx:535 
thisObj = #S#535[loop,loop,body#SB#550][]  thisStack = #S#535[loop,loop,body#SB#550][]
19:rpop 
20:pushthis 
21:rpushg 1 #S#535[1]=loop
23:rpushg 1 loop[1]=do
25:rpushg 1 do[1]=%for%to%%do%#S#108
27:pushthis 
28:rpushg 1 #S#535[1]=loop
30:rpushg 1 loop[1]=do
32:rpushg 1 do[1]=%for%to%%do%#S#108
34:pushg 3 %for%to%%do%#S#108[3]=17
36:pushc 1 
38:+ 17 1
39:storeg 3 %for%to%%do%#S#108[3]=18
41:break 1 81 
10:pushthis 
11:rpushg 1 loop[1]=do
13:rpushg 1 do[1]=%for%to%%do%#S#108
15:pushg 3 %for%to%%do%#S#108[3]=18
17:pushthis 
18:rpushg 1 loop[1]=do
20:rpushg 1 do[1]=%for%to%%do%#S#108
22:pushg 2 %for%to%%do%#S#108[2]=18
24:<= 
25:jmpFalse (1)36 
28:pushthis 

29:invoke 535 0 1 #S#535:1057:descInx:535 
thisObj = #S#535[loop,loop][]  thisStack = loop[do,do,loop][]
1:rstore 1 loop->#S#535[1]
3:allocEventQ 0 
5:mvStack 
thisObj = #S#535[loop,loop][]  thisStack = #S#535[loop,loop][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = #S#535[loop,loop][]  thisStack = #S#535[loop,loop][]
10:pushthis 
11:rpushg 1 #S#535[1]=loop
13:rpushg 1 loop[1]=do
15:rpushg 1 do[1]=%for%to%%do%#S#108
thisObj = #S#535[loop,loop,%for%to%%do%#S#108][]  thisStack = #S#535[loop,loop,%for%to%%do%#S#108][]

17:sendv  1 body#SB#550:1058:descInx:550 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = #S#535[loop,loop,%for%to%%do%#S#108][]
1:rstore 2 %for%to%%do%#S#108->body#SB#550[2]
3:allocEventQ 0 
5:mvStack 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = body#SB#550[#S#535,#S#535][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = body#SB#550[#S#535,#S#535][]
10:pushthis 
11:rpushg 2 body#SB#550[2]=%for%to%%do%#S#108
13:rpushg 2 %for%to%%do%#S#108[2]=print
15:rpushg 1 print[1]=String
17:pushthis 
18:rpushg 2 body#SB#550[2]=%for%to%%do%#S#108
20:pushg 3 %for%to%%do%#S#108[3]=18
22:xpushg 1 String[19]=49
xpushg:
Object: String:1017 lsc: 0
VFields: 18 105 110 116 101 103 101 114 65 114 114 97 121 83 116 97 114 116 49 0 
Rfields: LIB:1004 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
VStack: 
RStack: 
VdtTable: 0 0 0 0 
lscStack: 
--------------

24:%prim 2 49 1
26:rtnEventQ 0 
28:setThisStack 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = #S#535[loop,loop][]
29:pushthis 

30:rtn D body#SB#550:1058:descInx:550  to: #S#535:1057:descInx:535 
thisObj = #S#535[loop,loop,body#SB#550][]  thisStack = #S#535[loop,loop,body#SB#550][]
19:rpop 
20:pushthis 
21:rpushg 1 #S#535[1]=loop
23:rpushg 1 loop[1]=do
25:rpushg 1 do[1]=%for%to%%do%#S#108
27:pushthis 
28:rpushg 1 #S#535[1]=loop
30:rpushg 1 loop[1]=do
32:rpushg 1 do[1]=%for%to%%do%#S#108
34:pushg 3 %for%to%%do%#S#108[3]=18
36:pushc 1 
38:+ 18 1
39:storeg 3 %for%to%%do%#S#108[3]=19
41:break 1 81 
10:pushthis 
11:rpushg 1 loop[1]=do
13:rpushg 1 do[1]=%for%to%%do%#S#108
15:pushg 3 %for%to%%do%#S#108[3]=19
17:pushthis 
18:rpushg 1 loop[1]=do
20:rpushg 1 do[1]=%for%to%%do%#S#108
22:pushg 2 %for%to%%do%#S#108[2]=18
24:<= 
25:jmpFalse (0)36 
36:rtnEventQ 0 
38:setThisStack 
thisObj = loop[do,do][]  thisStack = do[%for%to%%do%#S#108,%for%to%%do%#S#108][]
39:pushthis 

40:rtn D loop:1022:descInx:65  to: do:1021:descInx:64 
thisObj = do[%for%to%%do%#S#108,%for%to%%do%#S#108,loop][]  thisStack = do[%for%to%%do%#S#108,%for%to%%do%#S#108,loop][]
13:rpop 
14:rtnEventQ 0 
16:mvStack 
thisObj = do[%for%to%%do%#S#108,%for%to%%do%#S#108][]  thisStack = do[%for%to%%do%#S#108,%for%to%%do%#S#108][]
17:rtnEventQ 0 
19:setThisStack 
thisObj = do[%for%to%%do%#S#108,%for%to%%do%#S#108][]  thisStack = %for%to%%do%#S#108[print,print][]
20:pushthis 

21:rtn D do:1021:descInx:64  to: %for%to%%do%#S#108:1019:descInx:108 
thisObj = %for%to%%do%#S#108[print,print,do][]  thisStack = %for%to%%do%#S#108[print,print,do][]
29:rpop 
30:rtnEventQ 0 
32:setThisStack 
thisObj = %for%to%%do%#S#108[print,print][]  thisStack = print[List,List][]
33:pushthis 

34:rtn D %for%to%%do%#S#108:1019:descInx:108  to: print:1018:descInx:107 
thisObj = print[List,List,%for%to%%do%#S#108][]  thisStack = print[List,List,%for%to%%do%#S#108][]
17:rpop 
18:rtnEventQ 0 
20:setThisStack 
thisObj = print[List,List][]  thisStack = List[ArrayDemos,ArrayDemos][]
21:pushthis 

22:rtn D print:1018:descInx:107  to: List:1016:descInx:441 
thisObj = List[ArrayDemos,ArrayDemos,print][]  thisStack = List[ArrayDemos,ArrayDemos,print][]
18:rpop 
19:pushthis 
20:rpushg 1 List[1]=ArrayDemos
22:rpushg 1 ArrayDemos[1]=demo
24:rpushg 1 demo[1]=workspace

26:invoke 66 0 0 newline:1059:descInx:66 
thisObj = newline[List,List][]  thisStack = List[ArrayDemos,ArrayDemos,workspace][]
1:rstore 1 workspace->newline[1]
3:allocEventQ 0 
5:mvStack 
thisObj = newline[List,List][]  thisStack = newline[List,List][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = newline[List,List][]  thisStack = newline[List,List][]
10:pushc 10 
12:%prim 2 10 

14:rtnEventQ 0 
16:setThisStack 
thisObj = newline[List,List][]  thisStack = List[ArrayDemos,ArrayDemos][]
17:pushthis 

18:rtn D newline:1059:descInx:66  to: List:1016:descInx:441 
thisObj = List[ArrayDemos,ArrayDemos,newline][]  thisStack = List[ArrayDemos,ArrayDemos,newline][]
32:rpop 
33:pushthis 
34:pushthis 

35:invoke 637 0 1 List#S#637:1060:descInx:637 
thisObj = List#S#637[List,List][]  thisStack = List[ArrayDemos,ArrayDemos,List,List][]
1:rstore 1 List->List#S#637[1]
3:allocEventQ 1 
5:pushthis 
6:rpushg 1 List#S#637[1]=List
8:pushNone 
9:pushNone 
10:toSuper 443 443 glsc: 1
1:pushthis 
2:rstoreg 3 List#S#637[3]=none
4:pushthis 
5:rstoreg 2 List#S#637[2]=none
7:rstore 1 List->List#S#637[1]
9:allocEventQ 1 
11:mvStack 
thisObj = List#S#637[List,List][]  thisStack = List#S#637[List,List][]
12:rtnEventQ 0 
14:mvStack 
thisObj = List#S#637[List,List][]  thisStack = List#S#637[List,List][]
15:rtnEventQ 0 
17:setThisStack 
thisObj = List#S#637[List,List][]  thisStack = List[ArrayDemos,ArrayDemos,List][]
18:pushthis 

19:rtn D List#S#637:1060:descInx:637  to: List:1016:descInx:441 
thisObj = List[ArrayDemos,ArrayDemos,List,List#S#637][]  thisStack = List[ArrayDemos,ArrayDemos,List,List#S#637][]
41:rswap 
42:rstoreg 4 List[4]=List#S#637
44:pushthis 
45:pushthis 
46:pushthis 
47:rpushg 1 List[1]=ArrayDemos
49:rpushg 1 ArrayDemos[1]=demo
51:rpushg 1 demo[1]=workspace
53:pushc 2 
55:pushc 0 
57:pushc 1 

59:allocIndexed 52 1 
AllocQ_indexed:
Object: Indexed:1061 lsc: 0
VFields: 2 0 0 
Rfields: * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
VStack: 
RStack: 
VdtTable: 0 0 0 0 
lscStack: 
--------------


63:invoke 447 0 0 Range:1062:descInx:447 
thisObj = Range[List,List][]  thisStack = List[ArrayDemos,ArrayDemos,List,List,Indexed][]
1:pushthis 
2:rstoreg 2 Range[2]=Indexed
4:rstore 1 List->Range[1]
6:allocEventQ 0 
8:mvStack 
thisObj = Range[List,List][]  thisStack = Range[List,List][]

9:innerA 1  exe: 0

11:rtnEventQ 1 
13:doEventQ 
14:mvStack 
thisObj = Range[List,List][]  thisStack = Range[List,List][]
15:pushthis 

16:inner P 1  exe: 0

18:rpopThisObj 
19:rtnEventQ 0 
21:setThisStack 
thisObj = Range[List,List][]  thisStack = List[ArrayDemos,ArrayDemos,List][]
22:pushthis 

23:rtn D Range:1062:descInx:447  to: List:1016:descInx:441 
thisObj = List[ArrayDemos,ArrayDemos,List,Range][]  thisStack = List[ArrayDemos,ArrayDemos,List,Range][]
69:rswap 
70:rstoreg 6 List[6]=Range
72:pushthis 
73:pushthis 
74:pushthis 
75:rpushg 1 List[1]=ArrayDemos
77:rpushg 1 ArrayDemos[1]=demo
79:rpushg 1 demo[1]=workspace
81:pushc 2 
83:pushc 0 
85:pushc 1 

87:allocIndexed 52 1 
AllocQ_indexed:
Object: Indexed:1063 lsc: 0
VFields: 2 0 0 
Rfields: * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
VStack: 
RStack: 
VdtTable: 0 0 0 0 
lscStack: 
--------------


91:invoke 447 0 0 Range:1064:descInx:447 
thisObj = Range[List,List][]  thisStack = List[ArrayDemos,ArrayDemos,List,List,Indexed][]
1:pushthis 
2:rstoreg 2 Range[2]=Indexed
4:rstore 1 List->Range[1]
6:allocEventQ 0 
8:mvStack 
thisObj = Range[List,List][]  thisStack = Range[List,List][]

9:innerA 1  exe: 0

11:rtnEventQ 1 
13:doEventQ 
14:mvStack 
thisObj = Range[List,List][]  thisStack = Range[List,List][]
15:pushthis 

16:inner P 1  exe: 0

18:rpopThisObj 
19:rtnEventQ 0 
21:setThisStack 
thisObj = Range[List,List][]  thisStack = List[ArrayDemos,ArrayDemos,List][]
22:pushthis 

23:rtn D Range:1064:descInx:447  to: List:1016:descInx:441 
thisObj = List[ArrayDemos,ArrayDemos,List,Range][]  thisStack = List[ArrayDemos,ArrayDemos,List,Range][]
97:rswap 
98:rstoreg 7 List[7]=Range
100:pushthis 
101:pushthis 
102:pushthis 
103:rpushg 6 List[6]=Range
105:pushthis 
106:rpushg 4 List[4]=List#S#637

108:invoke 445 0 0 RangeList:1065:descInx:445 
thisObj = RangeList[List,List][]  thisStack = List[ArrayDemos,ArrayDemos,List,List,Range,List#S#637][]
1:rstore 1 List#S#637->RangeList[1]
3:allocEventQ 0 
5:pushthis 
6:rpushg 1 RangeList[1]=List#S#637
8:pushthis 
9:rpushg 1 RangeList[1]=List#S#637
11:rpushg 1 List#S#637[1]=List

13:invoke 447 0 0 Range:1066:descInx:447 
thisObj = Range[RangeList,List][]  thisStack = List[ArrayDemos,ArrayDemos,List,List,Range,List#S#637,List][]
1:pushthis 
2:rstoreg 2 Range[2]=List
4:rstore 1 List#S#637->Range[1]
6:allocEventQ 0 
8:mvStack 
thisObj = Range[RangeList,List][]  thisStack = Range[RangeList,List][]

9:innerA 1  exe: 0

11:rtnEventQ 1 
13:doEventQ 
14:mvStack 
thisObj = Range[RangeList,List][]  thisStack = Range[RangeList,List][]
15:pushthis 

16:inner P 1  exe: 0

18:rpopThisObj 
19:rtnEventQ 0 
21:setThisStack 
thisObj = Range[RangeList,List][]  thisStack = List[ArrayDemos,ArrayDemos,List,List,Range][]
22:pushthis 

23:rtn D Range:1066:descInx:447  to: RangeList:1065:descInx:445 
thisObj = RangeList[List,List][]  thisStack = List[ArrayDemos,ArrayDemos,List,List,Range,Range][]
19:toSuper 443 443 glsc: 1
1:pushthis 
2:rstoreg 3 RangeList[3]=Range
4:pushthis 
5:rstoreg 2 RangeList[2]=Range
7:rstore 1 List->RangeList[1]
9:allocEventQ 1 
11:mvStack 
thisObj = RangeList[List,List][]  thisStack = RangeList[List,List][]
12:rtnEventQ 0 
14:mvStack 
thisObj = RangeList[List,List][]  thisStack = RangeList[List,List][]
15:rtnEventQ 0 
17:setThisStack 
thisObj = RangeList[List,List][]  thisStack = List[ArrayDemos,ArrayDemos,List][]
18:pushthis 

19:rtn D RangeList:1065:descInx:445  to: List:1016:descInx:441 
thisObj = List[ArrayDemos,ArrayDemos,List,RangeList][]  thisStack = List[ArrayDemos,ArrayDemos,List,RangeList][]
114:rswap 
115:rstoreg 3 List[3]=RangeList
117:pushText 20 
XmkTextObject
Object: String:1067 lsc: 0
VFields: 18 105 110 116 101 103 101 114 65 114 114 97 121 83 116 97 114 116 50 0 
Rfields: LIB:1004 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
VStack: 
RStack: 
VdtTable: 0 0 0 0 
lscStack: 
--------------


119:invoke 107 0 0 print:1068:descInx:107 
thisObj = print[List,List][]  thisStack = List[ArrayDemos,ArrayDemos,String][]
1:rstore 1 String->print[1]
3:allocEventQ 0 
5:mvStack 
thisObj = print[List,List][]  thisStack = print[List,List][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = print[List,List][]  thisStack = print[List,List][]
10:pushthis 

11:invoke 108 0 1 %for%to%%do%#S#108:1069:descInx:108 
thisObj = %for%to%%do%#S#108[print,print][]  thisStack = print[List,List,print][]
1:rstore 2 print->%for%to%%do%#S#108[2]
3:allocEventQ 1 
5:pushthis 
6:rpushg 2 %for%to%%do%#S#108[2]=print
8:rpushg 1 print[1]=String
10:rpushg 1 String[1]=LIB
12:rpushg 1 LIB[1]=BETAworld
14:pushc 1 
16:pushthis 
17:rpushg 2 %for%to%%do%#S#108[2]=print
19:rpushg 1 print[1]=String

21:invoke 98 0 0 length:1070:descInx:98 
thisObj = length[%for%to%%do%#S#108,print][]  thisStack = print[List,List,BETAworld,String][1]
1:rstore 1 String->length[1]
3:allocEventQ 0 
5:mvStack 
thisObj = length[%for%to%%do%#S#108,print][]  thisStack = length[%for%to%%do%#S#108,print][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = length[%for%to%%do%#S#108,print][]  thisStack = length[%for%to%%do%#S#108,print][]
10:pushthis 
11:pushthis 
12:rpushg 1 length[1]=String
14:pushc 0 
16:xpushg 1 String[1]=18
xpushg:
Object: String:1067 lsc: 0
VFields: 18 105 110 116 101 103 101 114 65 114 114 97 121 83 116 97 114 116 50 0 
Rfields: LIB:1004 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
VStack: 
RStack: 
VdtTable: 0 0 0 0 
lscStack: 
--------------

18:storeg 1 length[1]=18
20:rtnEventQ 0 
22:setThisStack 
thisObj = length[%for%to%%do%#S#108,print][]  thisStack = print[List,List,BETAworld][1]
23:pushthis 
24:pushg 1 length[1]=18

26:rtn D length:1070:descInx:98  to: %for%to%%do%#S#108:1069:descInx:108 
thisObj = %for%to%%do%#S#108[print,print][]  thisStack = print[List,List,BETAworld][1,18]
27:toSuper 63 63 glsc: 1
1:pushthis 
2:storeg 2 %for%to%%do%#S#108[2]=18
4:pushthis 
5:storeg 1 %for%to%%do%#S#108[1]=1
7:rstore 1 BETAworld->%for%to%%do%#S#108[1]
9:allocEventQ 0 
11:mvStack 
thisObj = %for%to%%do%#S#108[print,print][]  thisStack = %for%to%%do%#S#108[print,print][]
12:rtnEventQ 1 
14:doEventQ 
15:mvStack 
thisObj = %for%to%%do%#S#108[print,print][]  thisStack = %for%to%%do%#S#108[print,print][]
16:pushthis 
17:pushthis 
18:pushg 1 %for%to%%do%#S#108[1]=1
20:storeg 3 %for%to%%do%#S#108[3]=1
22:pushthis 

23:invoke 64 0 1 do:1071:descInx:64 
thisObj = do[%for%to%%do%#S#108,%for%to%%do%#S#108][]  thisStack = %for%to%%do%#S#108[print,print,%for%to%%do%#S#108][]
1:rstore 1 %for%to%%do%#S#108->do[1]
3:allocEventQ 1 
5:mvStack 
thisObj = do[%for%to%%do%#S#108,%for%to%%do%#S#108][]  thisStack = do[%for%to%%do%#S#108,%for%to%%do%#S#108][]
6:pushthis 

7:invoke 65 2 1 loop:1072:descInx:65 
thisObj = loop[do,do][]  thisStack = do[%for%to%%do%#S#108,%for%to%%do%#S#108,do][]
1:rstore 1 do->loop[1]
3:allocEventQ 0 
5:mvStack 
thisObj = loop[do,do][]  thisStack = loop[do,do][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = loop[do,do][]  thisStack = loop[do,do][]
10:pushthis 
11:rpushg 1 loop[1]=do
13:rpushg 1 do[1]=%for%to%%do%#S#108
15:pushg 3 %for%to%%do%#S#108[3]=1
17:pushthis 
18:rpushg 1 loop[1]=do
20:rpushg 1 do[1]=%for%to%%do%#S#108
22:pushg 2 %for%to%%do%#S#108[2]=18
24:<= 
25:jmpFalse (1)36 
28:pushthis 

29:invoke 535 0 1 #S#535:1073:descInx:535 
thisObj = #S#535[loop,loop][]  thisStack = loop[do,do,loop][]
1:rstore 1 loop->#S#535[1]
3:allocEventQ 0 
5:mvStack 
thisObj = #S#535[loop,loop][]  thisStack = #S#535[loop,loop][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = #S#535[loop,loop][]  thisStack = #S#535[loop,loop][]
10:pushthis 
11:rpushg 1 #S#535[1]=loop
13:rpushg 1 loop[1]=do
15:rpushg 1 do[1]=%for%to%%do%#S#108
thisObj = #S#535[loop,loop,%for%to%%do%#S#108][]  thisStack = #S#535[loop,loop,%for%to%%do%#S#108][]

17:sendv  1 body#SB#550:1074:descInx:550 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = #S#535[loop,loop,%for%to%%do%#S#108][]
1:rstore 2 %for%to%%do%#S#108->body#SB#550[2]
3:allocEventQ 0 
5:mvStack 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = body#SB#550[#S#535,#S#535][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = body#SB#550[#S#535,#S#535][]
10:pushthis 
11:rpushg 2 body#SB#550[2]=%for%to%%do%#S#108
13:rpushg 2 %for%to%%do%#S#108[2]=print
15:rpushg 1 print[1]=String
17:pushthis 
18:rpushg 2 body#SB#550[2]=%for%to%%do%#S#108
20:pushg 3 %for%to%%do%#S#108[3]=1
22:xpushg 1 String[2]=105
xpushg:
Object: String:1067 lsc: 0
VFields: 18 105 110 116 101 103 101 114 65 114 114 97 121 83 116 97 114 116 50 0 
Rfields: LIB:1004 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
VStack: 
RStack: 
VdtTable: 0 0 0 0 
lscStack: 
--------------

24:%prim 2 105 i
26:rtnEventQ 0 
28:setThisStack 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = #S#535[loop,loop][]
29:pushthis 

30:rtn D body#SB#550:1074:descInx:550  to: #S#535:1073:descInx:535 
thisObj = #S#535[loop,loop,body#SB#550][]  thisStack = #S#535[loop,loop,body#SB#550][]
19:rpop 
20:pushthis 
21:rpushg 1 #S#535[1]=loop
23:rpushg 1 loop[1]=do
25:rpushg 1 do[1]=%for%to%%do%#S#108
27:pushthis 
28:rpushg 1 #S#535[1]=loop
30:rpushg 1 loop[1]=do
32:rpushg 1 do[1]=%for%to%%do%#S#108
34:pushg 3 %for%to%%do%#S#108[3]=1
36:pushc 1 
38:+ 1 1
39:storeg 3 %for%to%%do%#S#108[3]=2
41:break 1 81 
10:pushthis 
11:rpushg 1 loop[1]=do
13:rpushg 1 do[1]=%for%to%%do%#S#108
15:pushg 3 %for%to%%do%#S#108[3]=2
17:pushthis 
18:rpushg 1 loop[1]=do
20:rpushg 1 do[1]=%for%to%%do%#S#108
22:pushg 2 %for%to%%do%#S#108[2]=18
24:<= 
25:jmpFalse (1)36 
28:pushthis 

29:invoke 535 0 1 #S#535:1075:descInx:535 
thisObj = #S#535[loop,loop][]  thisStack = loop[do,do,loop][]
1:rstore 1 loop->#S#535[1]
3:allocEventQ 0 
5:mvStack 
thisObj = #S#535[loop,loop][]  thisStack = #S#535[loop,loop][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = #S#535[loop,loop][]  thisStack = #S#535[loop,loop][]
10:pushthis 
11:rpushg 1 #S#535[1]=loop
13:rpushg 1 loop[1]=do
15:rpushg 1 do[1]=%for%to%%do%#S#108
thisObj = #S#535[loop,loop,%for%to%%do%#S#108][]  thisStack = #S#535[loop,loop,%for%to%%do%#S#108][]

17:sendv  1 body#SB#550:1076:descInx:550 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = #S#535[loop,loop,%for%to%%do%#S#108][]
1:rstore 2 %for%to%%do%#S#108->body#SB#550[2]
3:allocEventQ 0 
5:mvStack 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = body#SB#550[#S#535,#S#535][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = body#SB#550[#S#535,#S#535][]
10:pushthis 
11:rpushg 2 body#SB#550[2]=%for%to%%do%#S#108
13:rpushg 2 %for%to%%do%#S#108[2]=print
15:rpushg 1 print[1]=String
17:pushthis 
18:rpushg 2 body#SB#550[2]=%for%to%%do%#S#108
20:pushg 3 %for%to%%do%#S#108[3]=2
22:xpushg 1 String[3]=110
xpushg:
Object: String:1067 lsc: 0
VFields: 18 105 110 116 101 103 101 114 65 114 114 97 121 83 116 97 114 116 50 0 
Rfields: LIB:1004 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
VStack: 
RStack: 
VdtTable: 0 0 0 0 
lscStack: 
--------------

24:%prim 2 110 n
26:rtnEventQ 0 
28:setThisStack 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = #S#535[loop,loop][]
29:pushthis 

30:rtn D body#SB#550:1076:descInx:550  to: #S#535:1075:descInx:535 
thisObj = #S#535[loop,loop,body#SB#550][]  thisStack = #S#535[loop,loop,body#SB#550][]
19:rpop 
20:pushthis 
21:rpushg 1 #S#535[1]=loop
23:rpushg 1 loop[1]=do
25:rpushg 1 do[1]=%for%to%%do%#S#108
27:pushthis 
28:rpushg 1 #S#535[1]=loop
30:rpushg 1 loop[1]=do
32:rpushg 1 do[1]=%for%to%%do%#S#108
34:pushg 3 %for%to%%do%#S#108[3]=2
36:pushc 1 
38:+ 2 1
39:storeg 3 %for%to%%do%#S#108[3]=3
41:break 1 81 
10:pushthis 
11:rpushg 1 loop[1]=do
13:rpushg 1 do[1]=%for%to%%do%#S#108
15:pushg 3 %for%to%%do%#S#108[3]=3
17:pushthis 
18:rpushg 1 loop[1]=do
20:rpushg 1 do[1]=%for%to%%do%#S#108
22:pushg 2 %for%to%%do%#S#108[2]=18
24:<= 
25:jmpFalse (1)36 
28:pushthis 

29:invoke 535 0 1 #S#535:1077:descInx:535 
thisObj = #S#535[loop,loop][]  thisStack = loop[do,do,loop][]
1:rstore 1 loop->#S#535[1]
3:allocEventQ 0 
5:mvStack 
thisObj = #S#535[loop,loop][]  thisStack = #S#535[loop,loop][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = #S#535[loop,loop][]  thisStack = #S#535[loop,loop][]
10:pushthis 
11:rpushg 1 #S#535[1]=loop
13:rpushg 1 loop[1]=do
15:rpushg 1 do[1]=%for%to%%do%#S#108
thisObj = #S#535[loop,loop,%for%to%%do%#S#108][]  thisStack = #S#535[loop,loop,%for%to%%do%#S#108][]

17:sendv  1 body#SB#550:1078:descInx:550 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = #S#535[loop,loop,%for%to%%do%#S#108][]
1:rstore 2 %for%to%%do%#S#108->body#SB#550[2]
3:allocEventQ 0 
5:mvStack 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = body#SB#550[#S#535,#S#535][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = body#SB#550[#S#535,#S#535][]
10:pushthis 
11:rpushg 2 body#SB#550[2]=%for%to%%do%#S#108
13:rpushg 2 %for%to%%do%#S#108[2]=print
15:rpushg 1 print[1]=String
17:pushthis 
18:rpushg 2 body#SB#550[2]=%for%to%%do%#S#108
20:pushg 3 %for%to%%do%#S#108[3]=3
22:xpushg 1 String[4]=116
xpushg:
Object: String:1067 lsc: 0
VFields: 18 105 110 116 101 103 101 114 65 114 114 97 121 83 116 97 114 116 50 0 
Rfields: LIB:1004 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
VStack: 
RStack: 
VdtTable: 0 0 0 0 
lscStack: 
--------------

24:%prim 2 116 t
26:rtnEventQ 0 
28:setThisStack 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = #S#535[loop,loop][]
29:pushthis 

30:rtn D body#SB#550:1078:descInx:550  to: #S#535:1077:descInx:535 
thisObj = #S#535[loop,loop,body#SB#550][]  thisStack = #S#535[loop,loop,body#SB#550][]
19:rpop 
20:pushthis 
21:rpushg 1 #S#535[1]=loop
23:rpushg 1 loop[1]=do
25:rpushg 1 do[1]=%for%to%%do%#S#108
27:pushthis 
28:rpushg 1 #S#535[1]=loop
30:rpushg 1 loop[1]=do
32:rpushg 1 do[1]=%for%to%%do%#S#108
34:pushg 3 %for%to%%do%#S#108[3]=3
36:pushc 1 
38:+ 3 1
39:storeg 3 %for%to%%do%#S#108[3]=4
41:break 1 81 
10:pushthis 
11:rpushg 1 loop[1]=do
13:rpushg 1 do[1]=%for%to%%do%#S#108
15:pushg 3 %for%to%%do%#S#108[3]=4
17:pushthis 
18:rpushg 1 loop[1]=do
20:rpushg 1 do[1]=%for%to%%do%#S#108
22:pushg 2 %for%to%%do%#S#108[2]=18
24:<= 
25:jmpFalse (1)36 
28:pushthis 

29:invoke 535 0 1 #S#535:1079:descInx:535 
thisObj = #S#535[loop,loop][]  thisStack = loop[do,do,loop][]
1:rstore 1 loop->#S#535[1]
3:allocEventQ 0 
5:mvStack 
thisObj = #S#535[loop,loop][]  thisStack = #S#535[loop,loop][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = #S#535[loop,loop][]  thisStack = #S#535[loop,loop][]
10:pushthis 
11:rpushg 1 #S#535[1]=loop
13:rpushg 1 loop[1]=do
15:rpushg 1 do[1]=%for%to%%do%#S#108
thisObj = #S#535[loop,loop,%for%to%%do%#S#108][]  thisStack = #S#535[loop,loop,%for%to%%do%#S#108][]

17:sendv  1 body#SB#550:1080:descInx:550 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = #S#535[loop,loop,%for%to%%do%#S#108][]
1:rstore 2 %for%to%%do%#S#108->body#SB#550[2]
3:allocEventQ 0 
5:mvStack 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = body#SB#550[#S#535,#S#535][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = body#SB#550[#S#535,#S#535][]
10:pushthis 
11:rpushg 2 body#SB#550[2]=%for%to%%do%#S#108
13:rpushg 2 %for%to%%do%#S#108[2]=print
15:rpushg 1 print[1]=String
17:pushthis 
18:rpushg 2 body#SB#550[2]=%for%to%%do%#S#108
20:pushg 3 %for%to%%do%#S#108[3]=4
22:xpushg 1 String[5]=101
xpushg:
Object: String:1067 lsc: 0
VFields: 18 105 110 116 101 103 101 114 65 114 114 97 121 83 116 97 114 116 50 0 
Rfields: LIB:1004 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
VStack: 
RStack: 
VdtTable: 0 0 0 0 
lscStack: 
--------------

24:%prim 2 101 e
26:rtnEventQ 0 
28:setThisStack 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = #S#535[loop,loop][]
29:pushthis 

30:rtn D body#SB#550:1080:descInx:550  to: #S#535:1079:descInx:535 
thisObj = #S#535[loop,loop,body#SB#550][]  thisStack = #S#535[loop,loop,body#SB#550][]
19:rpop 
20:pushthis 
21:rpushg 1 #S#535[1]=loop
23:rpushg 1 loop[1]=do
25:rpushg 1 do[1]=%for%to%%do%#S#108
27:pushthis 
28:rpushg 1 #S#535[1]=loop
30:rpushg 1 loop[1]=do
32:rpushg 1 do[1]=%for%to%%do%#S#108
34:pushg 3 %for%to%%do%#S#108[3]=4
36:pushc 1 
38:+ 4 1
39:storeg 3 %for%to%%do%#S#108[3]=5
41:break 1 81 
10:pushthis 
11:rpushg 1 loop[1]=do
13:rpushg 1 do[1]=%for%to%%do%#S#108
15:pushg 3 %for%to%%do%#S#108[3]=5
17:pushthis 
18:rpushg 1 loop[1]=do
20:rpushg 1 do[1]=%for%to%%do%#S#108
22:pushg 2 %for%to%%do%#S#108[2]=18
24:<= 
25:jmpFalse (1)36 
28:pushthis 

29:invoke 535 0 1 #S#535:1081:descInx:535 
thisObj = #S#535[loop,loop][]  thisStack = loop[do,do,loop][]
1:rstore 1 loop->#S#535[1]
3:allocEventQ 0 
5:mvStack 
thisObj = #S#535[loop,loop][]  thisStack = #S#535[loop,loop][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = #S#535[loop,loop][]  thisStack = #S#535[loop,loop][]
10:pushthis 
11:rpushg 1 #S#535[1]=loop
13:rpushg 1 loop[1]=do
15:rpushg 1 do[1]=%for%to%%do%#S#108
thisObj = #S#535[loop,loop,%for%to%%do%#S#108][]  thisStack = #S#535[loop,loop,%for%to%%do%#S#108][]

17:sendv  1 body#SB#550:1082:descInx:550 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = #S#535[loop,loop,%for%to%%do%#S#108][]
1:rstore 2 %for%to%%do%#S#108->body#SB#550[2]
3:allocEventQ 0 
5:mvStack 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = body#SB#550[#S#535,#S#535][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = body#SB#550[#S#535,#S#535][]
10:pushthis 
11:rpushg 2 body#SB#550[2]=%for%to%%do%#S#108
13:rpushg 2 %for%to%%do%#S#108[2]=print
15:rpushg 1 print[1]=String
17:pushthis 
18:rpushg 2 body#SB#550[2]=%for%to%%do%#S#108
20:pushg 3 %for%to%%do%#S#108[3]=5
22:xpushg 1 String[6]=103
xpushg:
Object: String:1067 lsc: 0
VFields: 18 105 110 116 101 103 101 114 65 114 114 97 121 83 116 97 114 116 50 0 
Rfields: LIB:1004 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
VStack: 
RStack: 
VdtTable: 0 0 0 0 
lscStack: 
--------------

24:%prim 2 103 g
26:rtnEventQ 0 
28:setThisStack 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = #S#535[loop,loop][]
29:pushthis 

30:rtn D body#SB#550:1082:descInx:550  to: #S#535:1081:descInx:535 
thisObj = #S#535[loop,loop,body#SB#550][]  thisStack = #S#535[loop,loop,body#SB#550][]
19:rpop 
20:pushthis 
21:rpushg 1 #S#535[1]=loop
23:rpushg 1 loop[1]=do
25:rpushg 1 do[1]=%for%to%%do%#S#108
27:pushthis 
28:rpushg 1 #S#535[1]=loop
30:rpushg 1 loop[1]=do
32:rpushg 1 do[1]=%for%to%%do%#S#108
34:pushg 3 %for%to%%do%#S#108[3]=5
36:pushc 1 
38:+ 5 1
39:storeg 3 %for%to%%do%#S#108[3]=6
41:break 1 81 
10:pushthis 
11:rpushg 1 loop[1]=do
13:rpushg 1 do[1]=%for%to%%do%#S#108
15:pushg 3 %for%to%%do%#S#108[3]=6
17:pushthis 
18:rpushg 1 loop[1]=do
20:rpushg 1 do[1]=%for%to%%do%#S#108
22:pushg 2 %for%to%%do%#S#108[2]=18
24:<= 
25:jmpFalse (1)36 
28:pushthis 

29:invoke 535 0 1 #S#535:1083:descInx:535 
thisObj = #S#535[loop,loop][]  thisStack = loop[do,do,loop][]
1:rstore 1 loop->#S#535[1]
3:allocEventQ 0 
5:mvStack 
thisObj = #S#535[loop,loop][]  thisStack = #S#535[loop,loop][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = #S#535[loop,loop][]  thisStack = #S#535[loop,loop][]
10:pushthis 
11:rpushg 1 #S#535[1]=loop
13:rpushg 1 loop[1]=do
15:rpushg 1 do[1]=%for%to%%do%#S#108
thisObj = #S#535[loop,loop,%for%to%%do%#S#108][]  thisStack = #S#535[loop,loop,%for%to%%do%#S#108][]

17:sendv  1 body#SB#550:1084:descInx:550 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = #S#535[loop,loop,%for%to%%do%#S#108][]
1:rstore 2 %for%to%%do%#S#108->body#SB#550[2]
3:allocEventQ 0 
5:mvStack 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = body#SB#550[#S#535,#S#535][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = body#SB#550[#S#535,#S#535][]
10:pushthis 
11:rpushg 2 body#SB#550[2]=%for%to%%do%#S#108
13:rpushg 2 %for%to%%do%#S#108[2]=print
15:rpushg 1 print[1]=String
17:pushthis 
18:rpushg 2 body#SB#550[2]=%for%to%%do%#S#108
20:pushg 3 %for%to%%do%#S#108[3]=6
22:xpushg 1 String[7]=101
xpushg:
Object: String:1067 lsc: 0
VFields: 18 105 110 116 101 103 101 114 65 114 114 97 121 83 116 97 114 116 50 0 
Rfields: LIB:1004 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
VStack: 
RStack: 
VdtTable: 0 0 0 0 
lscStack: 
--------------

24:%prim 2 101 e
26:rtnEventQ 0 
28:setThisStack 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = #S#535[loop,loop][]
29:pushthis 

30:rtn D body#SB#550:1084:descInx:550  to: #S#535:1083:descInx:535 
thisObj = #S#535[loop,loop,body#SB#550][]  thisStack = #S#535[loop,loop,body#SB#550][]
19:rpop 
20:pushthis 
21:rpushg 1 #S#535[1]=loop
23:rpushg 1 loop[1]=do
25:rpushg 1 do[1]=%for%to%%do%#S#108
27:pushthis 
28:rpushg 1 #S#535[1]=loop
30:rpushg 1 loop[1]=do
32:rpushg 1 do[1]=%for%to%%do%#S#108
34:pushg 3 %for%to%%do%#S#108[3]=6
36:pushc 1 
38:+ 6 1
39:storeg 3 %for%to%%do%#S#108[3]=7
41:break 1 81 
10:pushthis 
11:rpushg 1 loop[1]=do
13:rpushg 1 do[1]=%for%to%%do%#S#108
15:pushg 3 %for%to%%do%#S#108[3]=7
17:pushthis 
18:rpushg 1 loop[1]=do
20:rpushg 1 do[1]=%for%to%%do%#S#108
22:pushg 2 %for%to%%do%#S#108[2]=18
24:<= 
25:jmpFalse (1)36 
28:pushthis 

29:invoke 535 0 1 #S#535:1085:descInx:535 
thisObj = #S#535[loop,loop][]  thisStack = loop[do,do,loop][]
1:rstore 1 loop->#S#535[1]
3:allocEventQ 0 
5:mvStack 
thisObj = #S#535[loop,loop][]  thisStack = #S#535[loop,loop][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = #S#535[loop,loop][]  thisStack = #S#535[loop,loop][]
10:pushthis 
11:rpushg 1 #S#535[1]=loop
13:rpushg 1 loop[1]=do
15:rpushg 1 do[1]=%for%to%%do%#S#108
thisObj = #S#535[loop,loop,%for%to%%do%#S#108][]  thisStack = #S#535[loop,loop,%for%to%%do%#S#108][]

17:sendv  1 body#SB#550:1086:descInx:550 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = #S#535[loop,loop,%for%to%%do%#S#108][]
1:rstore 2 %for%to%%do%#S#108->body#SB#550[2]
3:allocEventQ 0 
5:mvStack 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = body#SB#550[#S#535,#S#535][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = body#SB#550[#S#535,#S#535][]
10:pushthis 
11:rpushg 2 body#SB#550[2]=%for%to%%do%#S#108
13:rpushg 2 %for%to%%do%#S#108[2]=print
15:rpushg 1 print[1]=String
17:pushthis 
18:rpushg 2 body#SB#550[2]=%for%to%%do%#S#108
20:pushg 3 %for%to%%do%#S#108[3]=7
22:xpushg 1 String[8]=114
xpushg:
Object: String:1067 lsc: 0
VFields: 18 105 110 116 101 103 101 114 65 114 114 97 121 83 116 97 114 116 50 0 
Rfields: LIB:1004 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
VStack: 
RStack: 
VdtTable: 0 0 0 0 
lscStack: 
--------------

24:%prim 2 114 r
26:rtnEventQ 0 
28:setThisStack 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = #S#535[loop,loop][]
29:pushthis 

30:rtn D body#SB#550:1086:descInx:550  to: #S#535:1085:descInx:535 
thisObj = #S#535[loop,loop,body#SB#550][]  thisStack = #S#535[loop,loop,body#SB#550][]
19:rpop 
20:pushthis 
21:rpushg 1 #S#535[1]=loop
23:rpushg 1 loop[1]=do
25:rpushg 1 do[1]=%for%to%%do%#S#108
27:pushthis 
28:rpushg 1 #S#535[1]=loop
30:rpushg 1 loop[1]=do
32:rpushg 1 do[1]=%for%to%%do%#S#108
34:pushg 3 %for%to%%do%#S#108[3]=7
36:pushc 1 
38:+ 7 1
39:storeg 3 %for%to%%do%#S#108[3]=8
41:break 1 81 
10:pushthis 
11:rpushg 1 loop[1]=do
13:rpushg 1 do[1]=%for%to%%do%#S#108
15:pushg 3 %for%to%%do%#S#108[3]=8
17:pushthis 
18:rpushg 1 loop[1]=do
20:rpushg 1 do[1]=%for%to%%do%#S#108
22:pushg 2 %for%to%%do%#S#108[2]=18
24:<= 
25:jmpFalse (1)36 
28:pushthis 

29:invoke 535 0 1 #S#535:1087:descInx:535 
thisObj = #S#535[loop,loop][]  thisStack = loop[do,do,loop][]
1:rstore 1 loop->#S#535[1]
3:allocEventQ 0 
5:mvStack 
thisObj = #S#535[loop,loop][]  thisStack = #S#535[loop,loop][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = #S#535[loop,loop][]  thisStack = #S#535[loop,loop][]
10:pushthis 
11:rpushg 1 #S#535[1]=loop
13:rpushg 1 loop[1]=do
15:rpushg 1 do[1]=%for%to%%do%#S#108
thisObj = #S#535[loop,loop,%for%to%%do%#S#108][]  thisStack = #S#535[loop,loop,%for%to%%do%#S#108][]

17:sendv  1 body#SB#550:1088:descInx:550 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = #S#535[loop,loop,%for%to%%do%#S#108][]
1:rstore 2 %for%to%%do%#S#108->body#SB#550[2]
3:allocEventQ 0 
5:mvStack 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = body#SB#550[#S#535,#S#535][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = body#SB#550[#S#535,#S#535][]
10:pushthis 
11:rpushg 2 body#SB#550[2]=%for%to%%do%#S#108
13:rpushg 2 %for%to%%do%#S#108[2]=print
15:rpushg 1 print[1]=String
17:pushthis 
18:rpushg 2 body#SB#550[2]=%for%to%%do%#S#108
20:pushg 3 %for%to%%do%#S#108[3]=8
22:xpushg 1 String[9]=65
xpushg:
Object: String:1067 lsc: 0
VFields: 18 105 110 116 101 103 101 114 65 114 114 97 121 83 116 97 114 116 50 0 
Rfields: LIB:1004 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
VStack: 
RStack: 
VdtTable: 0 0 0 0 
lscStack: 
--------------

24:%prim 2 65 A
26:rtnEventQ 0 
28:setThisStack 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = #S#535[loop,loop][]
29:pushthis 

30:rtn D body#SB#550:1088:descInx:550  to: #S#535:1087:descInx:535 
thisObj = #S#535[loop,loop,body#SB#550][]  thisStack = #S#535[loop,loop,body#SB#550][]
19:rpop 
20:pushthis 
21:rpushg 1 #S#535[1]=loop
23:rpushg 1 loop[1]=do
25:rpushg 1 do[1]=%for%to%%do%#S#108
27:pushthis 
28:rpushg 1 #S#535[1]=loop
30:rpushg 1 loop[1]=do
32:rpushg 1 do[1]=%for%to%%do%#S#108
34:pushg 3 %for%to%%do%#S#108[3]=8
36:pushc 1 
38:+ 8 1
39:storeg 3 %for%to%%do%#S#108[3]=9
41:break 1 81 
10:pushthis 
11:rpushg 1 loop[1]=do
13:rpushg 1 do[1]=%for%to%%do%#S#108
15:pushg 3 %for%to%%do%#S#108[3]=9
17:pushthis 
18:rpushg 1 loop[1]=do
20:rpushg 1 do[1]=%for%to%%do%#S#108
22:pushg 2 %for%to%%do%#S#108[2]=18
24:<= 
25:jmpFalse (1)36 
28:pushthis 

29:invoke 535 0 1 #S#535:1089:descInx:535 
thisObj = #S#535[loop,loop][]  thisStack = loop[do,do,loop][]
1:rstore 1 loop->#S#535[1]
3:allocEventQ 0 
5:mvStack 
thisObj = #S#535[loop,loop][]  thisStack = #S#535[loop,loop][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = #S#535[loop,loop][]  thisStack = #S#535[loop,loop][]
10:pushthis 
11:rpushg 1 #S#535[1]=loop
13:rpushg 1 loop[1]=do
15:rpushg 1 do[1]=%for%to%%do%#S#108
thisObj = #S#535[loop,loop,%for%to%%do%#S#108][]  thisStack = #S#535[loop,loop,%for%to%%do%#S#108][]

17:sendv  1 body#SB#550:1090:descInx:550 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = #S#535[loop,loop,%for%to%%do%#S#108][]
1:rstore 2 %for%to%%do%#S#108->body#SB#550[2]
3:allocEventQ 0 
5:mvStack 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = body#SB#550[#S#535,#S#535][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = body#SB#550[#S#535,#S#535][]
10:pushthis 
11:rpushg 2 body#SB#550[2]=%for%to%%do%#S#108
13:rpushg 2 %for%to%%do%#S#108[2]=print
15:rpushg 1 print[1]=String
17:pushthis 
18:rpushg 2 body#SB#550[2]=%for%to%%do%#S#108
20:pushg 3 %for%to%%do%#S#108[3]=9
22:xpushg 1 String[10]=114
xpushg:
Object: String:1067 lsc: 0
VFields: 18 105 110 116 101 103 101 114 65 114 114 97 121 83 116 97 114 116 50 0 
Rfields: LIB:1004 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
VStack: 
RStack: 
VdtTable: 0 0 0 0 
lscStack: 
--------------

24:%prim 2 114 r
26:rtnEventQ 0 
28:setThisStack 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = #S#535[loop,loop][]
29:pushthis 

30:rtn D body#SB#550:1090:descInx:550  to: #S#535:1089:descInx:535 
thisObj = #S#535[loop,loop,body#SB#550][]  thisStack = #S#535[loop,loop,body#SB#550][]
19:rpop 
20:pushthis 
21:rpushg 1 #S#535[1]=loop
23:rpushg 1 loop[1]=do
25:rpushg 1 do[1]=%for%to%%do%#S#108
27:pushthis 
28:rpushg 1 #S#535[1]=loop
30:rpushg 1 loop[1]=do
32:rpushg 1 do[1]=%for%to%%do%#S#108
34:pushg 3 %for%to%%do%#S#108[3]=9
36:pushc 1 
38:+ 9 1
39:storeg 3 %for%to%%do%#S#108[3]=10
41:break 1 81 
10:pushthis 
11:rpushg 1 loop[1]=do
13:rpushg 1 do[1]=%for%to%%do%#S#108
15:pushg 3 %for%to%%do%#S#108[3]=10
17:pushthis 
18:rpushg 1 loop[1]=do
20:rpushg 1 do[1]=%for%to%%do%#S#108
22:pushg 2 %for%to%%do%#S#108[2]=18
24:<= 
25:jmpFalse (1)36 
28:pushthis 

29:invoke 535 0 1 #S#535:1091:descInx:535 
thisObj = #S#535[loop,loop][]  thisStack = loop[do,do,loop][]
1:rstore 1 loop->#S#535[1]
3:allocEventQ 0 
5:mvStack 
thisObj = #S#535[loop,loop][]  thisStack = #S#535[loop,loop][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = #S#535[loop,loop][]  thisStack = #S#535[loop,loop][]
10:pushthis 
11:rpushg 1 #S#535[1]=loop
13:rpushg 1 loop[1]=do
15:rpushg 1 do[1]=%for%to%%do%#S#108
thisObj = #S#535[loop,loop,%for%to%%do%#S#108][]  thisStack = #S#535[loop,loop,%for%to%%do%#S#108][]

17:sendv  1 body#SB#550:1092:descInx:550 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = #S#535[loop,loop,%for%to%%do%#S#108][]
1:rstore 2 %for%to%%do%#S#108->body#SB#550[2]
3:allocEventQ 0 
5:mvStack 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = body#SB#550[#S#535,#S#535][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = body#SB#550[#S#535,#S#535][]
10:pushthis 
11:rpushg 2 body#SB#550[2]=%for%to%%do%#S#108
13:rpushg 2 %for%to%%do%#S#108[2]=print
15:rpushg 1 print[1]=String
17:pushthis 
18:rpushg 2 body#SB#550[2]=%for%to%%do%#S#108
20:pushg 3 %for%to%%do%#S#108[3]=10
22:xpushg 1 String[11]=114
xpushg:
Object: String:1067 lsc: 0
VFields: 18 105 110 116 101 103 101 114 65 114 114 97 121 83 116 97 114 116 50 0 
Rfields: LIB:1004 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
VStack: 
RStack: 
VdtTable: 0 0 0 0 
lscStack: 
--------------

24:%prim 2 114 r
26:rtnEventQ 0 
28:setThisStack 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = #S#535[loop,loop][]
29:pushthis 

30:rtn D body#SB#550:1092:descInx:550  to: #S#535:1091:descInx:535 
thisObj = #S#535[loop,loop,body#SB#550][]  thisStack = #S#535[loop,loop,body#SB#550][]
19:rpop 
20:pushthis 
21:rpushg 1 #S#535[1]=loop
23:rpushg 1 loop[1]=do
25:rpushg 1 do[1]=%for%to%%do%#S#108
27:pushthis 
28:rpushg 1 #S#535[1]=loop
30:rpushg 1 loop[1]=do
32:rpushg 1 do[1]=%for%to%%do%#S#108
34:pushg 3 %for%to%%do%#S#108[3]=10
36:pushc 1 
38:+ 10 1
39:storeg 3 %for%to%%do%#S#108[3]=11
41:break 1 81 
10:pushthis 
11:rpushg 1 loop[1]=do
13:rpushg 1 do[1]=%for%to%%do%#S#108
15:pushg 3 %for%to%%do%#S#108[3]=11
17:pushthis 
18:rpushg 1 loop[1]=do
20:rpushg 1 do[1]=%for%to%%do%#S#108
22:pushg 2 %for%to%%do%#S#108[2]=18
24:<= 
25:jmpFalse (1)36 
28:pushthis 

29:invoke 535 0 1 #S#535:1093:descInx:535 
thisObj = #S#535[loop,loop][]  thisStack = loop[do,do,loop][]
1:rstore 1 loop->#S#535[1]
3:allocEventQ 0 
5:mvStack 
thisObj = #S#535[loop,loop][]  thisStack = #S#535[loop,loop][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = #S#535[loop,loop][]  thisStack = #S#535[loop,loop][]
10:pushthis 
11:rpushg 1 #S#535[1]=loop
13:rpushg 1 loop[1]=do
15:rpushg 1 do[1]=%for%to%%do%#S#108
thisObj = #S#535[loop,loop,%for%to%%do%#S#108][]  thisStack = #S#535[loop,loop,%for%to%%do%#S#108][]

17:sendv  1 body#SB#550:1094:descInx:550 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = #S#535[loop,loop,%for%to%%do%#S#108][]
1:rstore 2 %for%to%%do%#S#108->body#SB#550[2]
3:allocEventQ 0 
5:mvStack 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = body#SB#550[#S#535,#S#535][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = body#SB#550[#S#535,#S#535][]
10:pushthis 
11:rpushg 2 body#SB#550[2]=%for%to%%do%#S#108
13:rpushg 2 %for%to%%do%#S#108[2]=print
15:rpushg 1 print[1]=String
17:pushthis 
18:rpushg 2 body#SB#550[2]=%for%to%%do%#S#108
20:pushg 3 %for%to%%do%#S#108[3]=11
22:xpushg 1 String[12]=97
xpushg:
Object: String:1067 lsc: 0
VFields: 18 105 110 116 101 103 101 114 65 114 114 97 121 83 116 97 114 116 50 0 
Rfields: LIB:1004 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
VStack: 
RStack: 
VdtTable: 0 0 0 0 
lscStack: 
--------------

24:%prim 2 97 a
26:rtnEventQ 0 
28:setThisStack 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = #S#535[loop,loop][]
29:pushthis 

30:rtn D body#SB#550:1094:descInx:550  to: #S#535:1093:descInx:535 
thisObj = #S#535[loop,loop,body#SB#550][]  thisStack = #S#535[loop,loop,body#SB#550][]
19:rpop 
20:pushthis 
21:rpushg 1 #S#535[1]=loop
23:rpushg 1 loop[1]=do
25:rpushg 1 do[1]=%for%to%%do%#S#108
27:pushthis 
28:rpushg 1 #S#535[1]=loop
30:rpushg 1 loop[1]=do
32:rpushg 1 do[1]=%for%to%%do%#S#108
34:pushg 3 %for%to%%do%#S#108[3]=11
36:pushc 1 
38:+ 11 1
39:storeg 3 %for%to%%do%#S#108[3]=12
41:break 1 81 
10:pushthis 
11:rpushg 1 loop[1]=do
13:rpushg 1 do[1]=%for%to%%do%#S#108
15:pushg 3 %for%to%%do%#S#108[3]=12
17:pushthis 
18:rpushg 1 loop[1]=do
20:rpushg 1 do[1]=%for%to%%do%#S#108
22:pushg 2 %for%to%%do%#S#108[2]=18
24:<= 
25:jmpFalse (1)36 
28:pushthis 

29:invoke 535 0 1 #S#535:1095:descInx:535 
thisObj = #S#535[loop,loop][]  thisStack = loop[do,do,loop][]
1:rstore 1 loop->#S#535[1]
3:allocEventQ 0 
5:mvStack 
thisObj = #S#535[loop,loop][]  thisStack = #S#535[loop,loop][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = #S#535[loop,loop][]  thisStack = #S#535[loop,loop][]
10:pushthis 
11:rpushg 1 #S#535[1]=loop
13:rpushg 1 loop[1]=do
15:rpushg 1 do[1]=%for%to%%do%#S#108
thisObj = #S#535[loop,loop,%for%to%%do%#S#108][]  thisStack = #S#535[loop,loop,%for%to%%do%#S#108][]

17:sendv  1 body#SB#550:1096:descInx:550 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = #S#535[loop,loop,%for%to%%do%#S#108][]
1:rstore 2 %for%to%%do%#S#108->body#SB#550[2]
3:allocEventQ 0 
5:mvStack 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = body#SB#550[#S#535,#S#535][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = body#SB#550[#S#535,#S#535][]
10:pushthis 
11:rpushg 2 body#SB#550[2]=%for%to%%do%#S#108
13:rpushg 2 %for%to%%do%#S#108[2]=print
15:rpushg 1 print[1]=String
17:pushthis 
18:rpushg 2 body#SB#550[2]=%for%to%%do%#S#108
20:pushg 3 %for%to%%do%#S#108[3]=12
22:xpushg 1 String[13]=121
xpushg:
Object: String:1067 lsc: 0
VFields: 18 105 110 116 101 103 101 114 65 114 114 97 121 83 116 97 114 116 50 0 
Rfields: LIB:1004 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
VStack: 
RStack: 
VdtTable: 0 0 0 0 
lscStack: 
--------------

24:%prim 2 121 y
26:rtnEventQ 0 
28:setThisStack 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = #S#535[loop,loop][]
29:pushthis 

30:rtn D body#SB#550:1096:descInx:550  to: #S#535:1095:descInx:535 
thisObj = #S#535[loop,loop,body#SB#550][]  thisStack = #S#535[loop,loop,body#SB#550][]
19:rpop 
20:pushthis 
21:rpushg 1 #S#535[1]=loop
23:rpushg 1 loop[1]=do
25:rpushg 1 do[1]=%for%to%%do%#S#108
27:pushthis 
28:rpushg 1 #S#535[1]=loop
30:rpushg 1 loop[1]=do
32:rpushg 1 do[1]=%for%to%%do%#S#108
34:pushg 3 %for%to%%do%#S#108[3]=12
36:pushc 1 
38:+ 12 1
39:storeg 3 %for%to%%do%#S#108[3]=13
41:break 1 81 
10:pushthis 
11:rpushg 1 loop[1]=do
13:rpushg 1 do[1]=%for%to%%do%#S#108
15:pushg 3 %for%to%%do%#S#108[3]=13
17:pushthis 
18:rpushg 1 loop[1]=do
20:rpushg 1 do[1]=%for%to%%do%#S#108
22:pushg 2 %for%to%%do%#S#108[2]=18
24:<= 
25:jmpFalse (1)36 
28:pushthis 

29:invoke 535 0 1 #S#535:1097:descInx:535 
thisObj = #S#535[loop,loop][]  thisStack = loop[do,do,loop][]
1:rstore 1 loop->#S#535[1]
3:allocEventQ 0 
5:mvStack 
thisObj = #S#535[loop,loop][]  thisStack = #S#535[loop,loop][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = #S#535[loop,loop][]  thisStack = #S#535[loop,loop][]
10:pushthis 
11:rpushg 1 #S#535[1]=loop
13:rpushg 1 loop[1]=do
15:rpushg 1 do[1]=%for%to%%do%#S#108
thisObj = #S#535[loop,loop,%for%to%%do%#S#108][]  thisStack = #S#535[loop,loop,%for%to%%do%#S#108][]

17:sendv  1 body#SB#550:1098:descInx:550 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = #S#535[loop,loop,%for%to%%do%#S#108][]
1:rstore 2 %for%to%%do%#S#108->body#SB#550[2]
3:allocEventQ 0 
5:mvStack 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = body#SB#550[#S#535,#S#535][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = body#SB#550[#S#535,#S#535][]
10:pushthis 
11:rpushg 2 body#SB#550[2]=%for%to%%do%#S#108
13:rpushg 2 %for%to%%do%#S#108[2]=print
15:rpushg 1 print[1]=String
17:pushthis 
18:rpushg 2 body#SB#550[2]=%for%to%%do%#S#108
20:pushg 3 %for%to%%do%#S#108[3]=13
22:xpushg 1 String[14]=83
xpushg:
Object: String:1067 lsc: 0
VFields: 18 105 110 116 101 103 101 114 65 114 114 97 121 83 116 97 114 116 50 0 
Rfields: LIB:1004 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
VStack: 
RStack: 
VdtTable: 0 0 0 0 
lscStack: 
--------------

24:%prim 2 83 S
26:rtnEventQ 0 
28:setThisStack 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = #S#535[loop,loop][]
29:pushthis 

30:rtn D body#SB#550:1098:descInx:550  to: #S#535:1097:descInx:535 
thisObj = #S#535[loop,loop,body#SB#550][]  thisStack = #S#535[loop,loop,body#SB#550][]
19:rpop 
20:pushthis 
21:rpushg 1 #S#535[1]=loop
23:rpushg 1 loop[1]=do
25:rpushg 1 do[1]=%for%to%%do%#S#108
27:pushthis 
28:rpushg 1 #S#535[1]=loop
30:rpushg 1 loop[1]=do
32:rpushg 1 do[1]=%for%to%%do%#S#108
34:pushg 3 %for%to%%do%#S#108[3]=13
36:pushc 1 
38:+ 13 1
39:storeg 3 %for%to%%do%#S#108[3]=14
41:break 1 81 
10:pushthis 
11:rpushg 1 loop[1]=do
13:rpushg 1 do[1]=%for%to%%do%#S#108
15:pushg 3 %for%to%%do%#S#108[3]=14
17:pushthis 
18:rpushg 1 loop[1]=do
20:rpushg 1 do[1]=%for%to%%do%#S#108
22:pushg 2 %for%to%%do%#S#108[2]=18
24:<= 
25:jmpFalse (1)36 
28:pushthis 

29:invoke 535 0 1 #S#535:1099:descInx:535 
thisObj = #S#535[loop,loop][]  thisStack = loop[do,do,loop][]
1:rstore 1 loop->#S#535[1]
3:allocEventQ 0 
5:mvStack 
thisObj = #S#535[loop,loop][]  thisStack = #S#535[loop,loop][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = #S#535[loop,loop][]  thisStack = #S#535[loop,loop][]
10:pushthis 
11:rpushg 1 #S#535[1]=loop
13:rpushg 1 loop[1]=do
15:rpushg 1 do[1]=%for%to%%do%#S#108
thisObj = #S#535[loop,loop,%for%to%%do%#S#108][]  thisStack = #S#535[loop,loop,%for%to%%do%#S#108][]

17:sendv  1 body#SB#550:1100:descInx:550 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = #S#535[loop,loop,%for%to%%do%#S#108][]
1:rstore 2 %for%to%%do%#S#108->body#SB#550[2]
3:allocEventQ 0 
5:mvStack 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = body#SB#550[#S#535,#S#535][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = body#SB#550[#S#535,#S#535][]
10:pushthis 
11:rpushg 2 body#SB#550[2]=%for%to%%do%#S#108
13:rpushg 2 %for%to%%do%#S#108[2]=print
15:rpushg 1 print[1]=String
17:pushthis 
18:rpushg 2 body#SB#550[2]=%for%to%%do%#S#108
20:pushg 3 %for%to%%do%#S#108[3]=14
22:xpushg 1 String[15]=116
xpushg:
Object: String:1067 lsc: 0
VFields: 18 105 110 116 101 103 101 114 65 114 114 97 121 83 116 97 114 116 50 0 
Rfields: LIB:1004 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
VStack: 
RStack: 
VdtTable: 0 0 0 0 
lscStack: 
--------------

24:%prim 2 116 t
26:rtnEventQ 0 
28:setThisStack 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = #S#535[loop,loop][]
29:pushthis 

30:rtn D body#SB#550:1100:descInx:550  to: #S#535:1099:descInx:535 
thisObj = #S#535[loop,loop,body#SB#550][]  thisStack = #S#535[loop,loop,body#SB#550][]
19:rpop 
20:pushthis 
21:rpushg 1 #S#535[1]=loop
23:rpushg 1 loop[1]=do
25:rpushg 1 do[1]=%for%to%%do%#S#108
27:pushthis 
28:rpushg 1 #S#535[1]=loop
30:rpushg 1 loop[1]=do
32:rpushg 1 do[1]=%for%to%%do%#S#108
34:pushg 3 %for%to%%do%#S#108[3]=14
36:pushc 1 
38:+ 14 1
39:storeg 3 %for%to%%do%#S#108[3]=15
41:break 1 81 
10:pushthis 
11:rpushg 1 loop[1]=do
13:rpushg 1 do[1]=%for%to%%do%#S#108
15:pushg 3 %for%to%%do%#S#108[3]=15
17:pushthis 
18:rpushg 1 loop[1]=do
20:rpushg 1 do[1]=%for%to%%do%#S#108
22:pushg 2 %for%to%%do%#S#108[2]=18
24:<= 
25:jmpFalse (1)36 
28:pushthis 

29:invoke 535 0 1 #S#535:1101:descInx:535 
thisObj = #S#535[loop,loop][]  thisStack = loop[do,do,loop][]
1:rstore 1 loop->#S#535[1]
3:allocEventQ 0 
5:mvStack 
thisObj = #S#535[loop,loop][]  thisStack = #S#535[loop,loop][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = #S#535[loop,loop][]  thisStack = #S#535[loop,loop][]
10:pushthis 
11:rpushg 1 #S#535[1]=loop
13:rpushg 1 loop[1]=do
15:rpushg 1 do[1]=%for%to%%do%#S#108
thisObj = #S#535[loop,loop,%for%to%%do%#S#108][]  thisStack = #S#535[loop,loop,%for%to%%do%#S#108][]

17:sendv  1 body#SB#550:1102:descInx:550 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = #S#535[loop,loop,%for%to%%do%#S#108][]
1:rstore 2 %for%to%%do%#S#108->body#SB#550[2]
3:allocEventQ 0 
5:mvStack 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = body#SB#550[#S#535,#S#535][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = body#SB#550[#S#535,#S#535][]
10:pushthis 
11:rpushg 2 body#SB#550[2]=%for%to%%do%#S#108
13:rpushg 2 %for%to%%do%#S#108[2]=print
15:rpushg 1 print[1]=String
17:pushthis 
18:rpushg 2 body#SB#550[2]=%for%to%%do%#S#108
20:pushg 3 %for%to%%do%#S#108[3]=15
22:xpushg 1 String[16]=97
xpushg:
Object: String:1067 lsc: 0
VFields: 18 105 110 116 101 103 101 114 65 114 114 97 121 83 116 97 114 116 50 0 
Rfields: LIB:1004 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
VStack: 
RStack: 
VdtTable: 0 0 0 0 
lscStack: 
--------------

24:%prim 2 97 a
26:rtnEventQ 0 
28:setThisStack 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = #S#535[loop,loop][]
29:pushthis 

30:rtn D body#SB#550:1102:descInx:550  to: #S#535:1101:descInx:535 
thisObj = #S#535[loop,loop,body#SB#550][]  thisStack = #S#535[loop,loop,body#SB#550][]
19:rpop 
20:pushthis 
21:rpushg 1 #S#535[1]=loop
23:rpushg 1 loop[1]=do
25:rpushg 1 do[1]=%for%to%%do%#S#108
27:pushthis 
28:rpushg 1 #S#535[1]=loop
30:rpushg 1 loop[1]=do
32:rpushg 1 do[1]=%for%to%%do%#S#108
34:pushg 3 %for%to%%do%#S#108[3]=15
36:pushc 1 
38:+ 15 1
39:storeg 3 %for%to%%do%#S#108[3]=16
41:break 1 81 
10:pushthis 
11:rpushg 1 loop[1]=do
13:rpushg 1 do[1]=%for%to%%do%#S#108
15:pushg 3 %for%to%%do%#S#108[3]=16
17:pushthis 
18:rpushg 1 loop[1]=do
20:rpushg 1 do[1]=%for%to%%do%#S#108
22:pushg 2 %for%to%%do%#S#108[2]=18
24:<= 
25:jmpFalse (1)36 
28:pushthis 

29:invoke 535 0 1 #S#535:1103:descInx:535 
thisObj = #S#535[loop,loop][]  thisStack = loop[do,do,loop][]
1:rstore 1 loop->#S#535[1]
3:allocEventQ 0 
5:mvStack 
thisObj = #S#535[loop,loop][]  thisStack = #S#535[loop,loop][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = #S#535[loop,loop][]  thisStack = #S#535[loop,loop][]
10:pushthis 
11:rpushg 1 #S#535[1]=loop
13:rpushg 1 loop[1]=do
15:rpushg 1 do[1]=%for%to%%do%#S#108
thisObj = #S#535[loop,loop,%for%to%%do%#S#108][]  thisStack = #S#535[loop,loop,%for%to%%do%#S#108][]

17:sendv  1 body#SB#550:1104:descInx:550 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = #S#535[loop,loop,%for%to%%do%#S#108][]
1:rstore 2 %for%to%%do%#S#108->body#SB#550[2]
3:allocEventQ 0 
5:mvStack 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = body#SB#550[#S#535,#S#535][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = body#SB#550[#S#535,#S#535][]
10:pushthis 
11:rpushg 2 body#SB#550[2]=%for%to%%do%#S#108
13:rpushg 2 %for%to%%do%#S#108[2]=print
15:rpushg 1 print[1]=String
17:pushthis 
18:rpushg 2 body#SB#550[2]=%for%to%%do%#S#108
20:pushg 3 %for%to%%do%#S#108[3]=16
22:xpushg 1 String[17]=114
xpushg:
Object: String:1067 lsc: 0
VFields: 18 105 110 116 101 103 101 114 65 114 114 97 121 83 116 97 114 116 50 0 
Rfields: LIB:1004 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
VStack: 
RStack: 
VdtTable: 0 0 0 0 
lscStack: 
--------------

24:%prim 2 114 r
26:rtnEventQ 0 
28:setThisStack 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = #S#535[loop,loop][]
29:pushthis 

30:rtn D body#SB#550:1104:descInx:550  to: #S#535:1103:descInx:535 
thisObj = #S#535[loop,loop,body#SB#550][]  thisStack = #S#535[loop,loop,body#SB#550][]
19:rpop 
20:pushthis 
21:rpushg 1 #S#535[1]=loop
23:rpushg 1 loop[1]=do
25:rpushg 1 do[1]=%for%to%%do%#S#108
27:pushthis 
28:rpushg 1 #S#535[1]=loop
30:rpushg 1 loop[1]=do
32:rpushg 1 do[1]=%for%to%%do%#S#108
34:pushg 3 %for%to%%do%#S#108[3]=16
36:pushc 1 
38:+ 16 1
39:storeg 3 %for%to%%do%#S#108[3]=17
41:break 1 81 
10:pushthis 
11:rpushg 1 loop[1]=do
13:rpushg 1 do[1]=%for%to%%do%#S#108
15:pushg 3 %for%to%%do%#S#108[3]=17
17:pushthis 
18:rpushg 1 loop[1]=do
20:rpushg 1 do[1]=%for%to%%do%#S#108
22:pushg 2 %for%to%%do%#S#108[2]=18
24:<= 
25:jmpFalse (1)36 
28:pushthis 

29:invoke 535 0 1 #S#535:1105:descInx:535 
thisObj = #S#535[loop,loop][]  thisStack = loop[do,do,loop][]
1:rstore 1 loop->#S#535[1]
3:allocEventQ 0 
5:mvStack 
thisObj = #S#535[loop,loop][]  thisStack = #S#535[loop,loop][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = #S#535[loop,loop][]  thisStack = #S#535[loop,loop][]
10:pushthis 
11:rpushg 1 #S#535[1]=loop
13:rpushg 1 loop[1]=do
15:rpushg 1 do[1]=%for%to%%do%#S#108
thisObj = #S#535[loop,loop,%for%to%%do%#S#108][]  thisStack = #S#535[loop,loop,%for%to%%do%#S#108][]

17:sendv  1 body#SB#550:1106:descInx:550 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = #S#535[loop,loop,%for%to%%do%#S#108][]
1:rstore 2 %for%to%%do%#S#108->body#SB#550[2]
3:allocEventQ 0 
5:mvStack 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = body#SB#550[#S#535,#S#535][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = body#SB#550[#S#535,#S#535][]
10:pushthis 
11:rpushg 2 body#SB#550[2]=%for%to%%do%#S#108
13:rpushg 2 %for%to%%do%#S#108[2]=print
15:rpushg 1 print[1]=String
17:pushthis 
18:rpushg 2 body#SB#550[2]=%for%to%%do%#S#108
20:pushg 3 %for%to%%do%#S#108[3]=17
22:xpushg 1 String[18]=116
xpushg:
Object: String:1067 lsc: 0
VFields: 18 105 110 116 101 103 101 114 65 114 114 97 121 83 116 97 114 116 50 0 
Rfields: LIB:1004 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
VStack: 
RStack: 
VdtTable: 0 0 0 0 
lscStack: 
--------------

24:%prim 2 116 t
26:rtnEventQ 0 
28:setThisStack 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = #S#535[loop,loop][]
29:pushthis 

30:rtn D body#SB#550:1106:descInx:550  to: #S#535:1105:descInx:535 
thisObj = #S#535[loop,loop,body#SB#550][]  thisStack = #S#535[loop,loop,body#SB#550][]
19:rpop 
20:pushthis 
21:rpushg 1 #S#535[1]=loop
23:rpushg 1 loop[1]=do
25:rpushg 1 do[1]=%for%to%%do%#S#108
27:pushthis 
28:rpushg 1 #S#535[1]=loop
30:rpushg 1 loop[1]=do
32:rpushg 1 do[1]=%for%to%%do%#S#108
34:pushg 3 %for%to%%do%#S#108[3]=17
36:pushc 1 
38:+ 17 1
39:storeg 3 %for%to%%do%#S#108[3]=18
41:break 1 81 
10:pushthis 
11:rpushg 1 loop[1]=do
13:rpushg 1 do[1]=%for%to%%do%#S#108
15:pushg 3 %for%to%%do%#S#108[3]=18
17:pushthis 
18:rpushg 1 loop[1]=do
20:rpushg 1 do[1]=%for%to%%do%#S#108
22:pushg 2 %for%to%%do%#S#108[2]=18
24:<= 
25:jmpFalse (1)36 
28:pushthis 

29:invoke 535 0 1 #S#535:1107:descInx:535 
thisObj = #S#535[loop,loop][]  thisStack = loop[do,do,loop][]
1:rstore 1 loop->#S#535[1]
3:allocEventQ 0 
5:mvStack 
thisObj = #S#535[loop,loop][]  thisStack = #S#535[loop,loop][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = #S#535[loop,loop][]  thisStack = #S#535[loop,loop][]
10:pushthis 
11:rpushg 1 #S#535[1]=loop
13:rpushg 1 loop[1]=do
15:rpushg 1 do[1]=%for%to%%do%#S#108
thisObj = #S#535[loop,loop,%for%to%%do%#S#108][]  thisStack = #S#535[loop,loop,%for%to%%do%#S#108][]

17:sendv  1 body#SB#550:1108:descInx:550 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = #S#535[loop,loop,%for%to%%do%#S#108][]
1:rstore 2 %for%to%%do%#S#108->body#SB#550[2]
3:allocEventQ 0 
5:mvStack 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = body#SB#550[#S#535,#S#535][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = body#SB#550[#S#535,#S#535][]
10:pushthis 
11:rpushg 2 body#SB#550[2]=%for%to%%do%#S#108
13:rpushg 2 %for%to%%do%#S#108[2]=print
15:rpushg 1 print[1]=String
17:pushthis 
18:rpushg 2 body#SB#550[2]=%for%to%%do%#S#108
20:pushg 3 %for%to%%do%#S#108[3]=18
22:xpushg 1 String[19]=50
xpushg:
Object: String:1067 lsc: 0
VFields: 18 105 110 116 101 103 101 114 65 114 114 97 121 83 116 97 114 116 50 0 
Rfields: LIB:1004 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
VStack: 
RStack: 
VdtTable: 0 0 0 0 
lscStack: 
--------------

24:%prim 2 50 2
26:rtnEventQ 0 
28:setThisStack 
thisObj = body#SB#550[#S#535,#S#535][]  thisStack = #S#535[loop,loop][]
29:pushthis 

30:rtn D body#SB#550:1108:descInx:550  to: #S#535:1107:descInx:535 
thisObj = #S#535[loop,loop,body#SB#550][]  thisStack = #S#535[loop,loop,body#SB#550][]
19:rpop 
20:pushthis 
21:rpushg 1 #S#535[1]=loop
23:rpushg 1 loop[1]=do
25:rpushg 1 do[1]=%for%to%%do%#S#108
27:pushthis 
28:rpushg 1 #S#535[1]=loop
30:rpushg 1 loop[1]=do
32:rpushg 1 do[1]=%for%to%%do%#S#108
34:pushg 3 %for%to%%do%#S#108[3]=18
36:pushc 1 
38:+ 18 1
39:storeg 3 %for%to%%do%#S#108[3]=19
41:break 1 81 
10:pushthis 
11:rpushg 1 loop[1]=do
13:rpushg 1 do[1]=%for%to%%do%#S#108
15:pushg 3 %for%to%%do%#S#108[3]=19
17:pushthis 
18:rpushg 1 loop[1]=do
20:rpushg 1 do[1]=%for%to%%do%#S#108
22:pushg 2 %for%to%%do%#S#108[2]=18
24:<= 
25:jmpFalse (0)36 
36:rtnEventQ 0 
38:setThisStack 
thisObj = loop[do,do][]  thisStack = do[%for%to%%do%#S#108,%for%to%%do%#S#108][]
39:pushthis 

40:rtn D loop:1072:descInx:65  to: do:1071:descInx:64 
thisObj = do[%for%to%%do%#S#108,%for%to%%do%#S#108,loop][]  thisStack = do[%for%to%%do%#S#108,%for%to%%do%#S#108,loop][]
13:rpop 
14:rtnEventQ 0 
16:mvStack 
thisObj = do[%for%to%%do%#S#108,%for%to%%do%#S#108][]  thisStack = do[%for%to%%do%#S#108,%for%to%%do%#S#108][]
17:rtnEventQ 0 
19:setThisStack 
thisObj = do[%for%to%%do%#S#108,%for%to%%do%#S#108][]  thisStack = %for%to%%do%#S#108[print,print][]
20:pushthis 

21:rtn D do:1071:descInx:64  to: %for%to%%do%#S#108:1069:descInx:108 
thisObj = %for%to%%do%#S#108[print,print,do][]  thisStack = %for%to%%do%#S#108[print,print,do][]
29:rpop 
30:rtnEventQ 0 
32:setThisStack 
thisObj = %for%to%%do%#S#108[print,print][]  thisStack = print[List,List][]
33:pushthis 

34:rtn D %for%to%%do%#S#108:1069:descInx:108  to: print:1068:descInx:107 
thisObj = print[List,List,%for%to%%do%#S#108][]  thisStack = print[List,List,%for%to%%do%#S#108][]
17:rpop 
18:rtnEventQ 0 
20:setThisStack 
thisObj = print[List,List][]  thisStack = List[ArrayDemos,ArrayDemos][]
21:pushthis 

22:rtn D print:1068:descInx:107  to: List:1016:descInx:441 
thisObj = List[ArrayDemos,ArrayDemos,print][]  thisStack = List[ArrayDemos,ArrayDemos,print][]
125:rpop 
126:pushthis 
127:rpushg 1 List[1]=ArrayDemos
129:rpushg 1 ArrayDemos[1]=demo
131:rpushg 1 demo[1]=workspace

133:invoke 66 0 0 newline:1109:descInx:66 
thisObj = newline[List,List][]  thisStack = List[ArrayDemos,ArrayDemos,workspace][]
1:rstore 1 workspace->newline[1]
3:allocEventQ 0 
5:mvStack 
thisObj = newline[List,List][]  thisStack = newline[List,List][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = newline[List,List][]  thisStack = newline[List,List][]
10:pushc 10 
12:%prim 2 10 

14:rtnEventQ 0 
16:setThisStack 
thisObj = newline[List,List][]  thisStack = List[ArrayDemos,ArrayDemos][]
17:pushthis 

18:rtn D newline:1109:descInx:66  to: List:1016:descInx:441 
thisObj = List[ArrayDemos,ArrayDemos,newline][]  thisStack = List[ArrayDemos,ArrayDemos,newline][]
139:rpop 
140:pushthis 
141:rpushg 6 List[6]=Range
143:rpushg 2 Range[2]=Indexed
145:pushc 2 
147:pushc 1 
149:xstoreg 1 Indexed[2]=2
xstoreg:
Object: Indexed:1061 lsc: 0
VFields: 2 2 0 
Rfields: * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
VStack: 
RStack: 
VdtTable: 0 0 0 0 
lscStack: 
--------------

151:pushthis 
152:rpushg 6 List[6]=Range
154:rpushg 2 Range[2]=Indexed
156:pushc 3 
158:pushc 2 
160:xstoreg 1 Indexed[3]=3
xstoreg:
Object: Indexed:1061 lsc: 0
VFields: 2 2 3 
Rfields: * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
VStack: 
RStack: 
VdtTable: 0 0 0 0 
lscStack: 
--------------

162:pushthis 
163:rpushg 7 List[7]=Range
165:rpushg 2 Range[2]=Indexed
167:pushc 4 
169:pushc 1 
171:xstoreg 1 Indexed[2]=4
xstoreg:
Object: Indexed:1063 lsc: 0
VFields: 2 4 0 
Rfields: * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
VStack: 
RStack: 
VdtTable: 0 0 0 0 
lscStack: 
--------------

173:pushthis 
174:rpushg 7 List[7]=Range
176:rpushg 2 Range[2]=Indexed
178:pushc 5 
180:pushc 2 
182:xstoreg 1 Indexed[3]=5
xstoreg:
Object: Indexed:1063 lsc: 0
VFields: 2 4 5 
Rfields: * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
VStack: 
RStack: 
VdtTable: 0 0 0 0 
lscStack: 
--------------

184:pushthis 
185:rpushg 1 List[1]=ArrayDemos
187:rpushg 1 ArrayDemos[1]=demo
189:rpushg 1 demo[1]=workspace
191:pushthis 
192:rpushg 6 List[6]=Range
194:rpushg 2 Range[2]=Indexed
196:pushc 1 
198:xpushg 1 Indexed[2]=2
xpushg:
Object: Indexed:1061 lsc: 0
VFields: 2 2 3 
Rfields: * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
VStack: 
RStack: 
VdtTable: 0 0 0 0 
lscStack: 
--------------


200:invoke 67 0 0 putint:1110:descInx:67 
thisObj = putint[List,List][]  thisStack = List[ArrayDemos,ArrayDemos,workspace][2]
1:pushthis 
2:storeg 1 putint[1]=2
4:rstore 1 workspace->putint[1]
6:allocEventQ 0 
8:mvStack 
thisObj = putint[List,List][]  thisStack = putint[List,List][]
9:pushthis 
10:rpushg 1 putint[1]=workspace
12:pushc 20 
14:pushc 0 
16:pushc 1 

18:allocIndexed 52 1 
AllocQ_indexed:
Object: Indexed:1111 lsc: 0
VFields: 20 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
Rfields: * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
VStack: 
RStack: 
VdtTable: 0 0 0 0 
lscStack: 
--------------

22:pushthis 
23:rstoreg 2 putint[2]=Indexed
25:rtnEventQ 1 
27:doEventQ 
28:mvStack 
thisObj = putint[List,List][]  thisStack = putint[List,List][]
29:pushthis 
30:pushthis 
31:pushg 1 putint[1]=2
33:pushc 0 
35:< 2<0
36:storeg 3 putint[3]=0
38:pushthis 
39:pushg 3 putint[3]=0
41:jmpFalse (0)53 
53:pushthis 

54:invoke 68 0 0 doit:1112:descInx:68 
thisObj = doit[putint,putint][]  thisStack = putint[List,List,putint][]
1:rstore 1 putint->doit[1]
3:allocEventQ 0 
5:mvStack 
thisObj = doit[putint,putint][]  thisStack = doit[putint,putint][]
6:pushthis 

7:invoke 69 2 1 loop:1113:descInx:69 
thisObj = loop[doit,doit][]  thisStack = doit[putint,putint,doit][]
1:rstore 1 doit->loop[1]
3:allocEventQ 0 
5:mvStack 
thisObj = loop[doit,doit][]  thisStack = loop[doit,doit][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = loop[doit,doit][]  thisStack = loop[doit,doit][]
10:pushthis 
11:rpushg 1 loop[1]=doit
13:rpushg 1 doit[1]=putint
15:pushthis 
16:rpushg 1 loop[1]=doit
18:rpushg 1 doit[1]=putint
20:pushg 2 putint[2]=0
22:pushc 1 
24:+ 0 1
25:storeg 2 putint[2]=1
27:pushthis 
28:rpushg 1 loop[1]=doit
30:rpushg 1 doit[1]=putint
32:rpushg 2 putint[2]=Indexed
34:pushthis 
35:rpushg 1 loop[1]=doit
37:rpushg 1 doit[1]=putint
39:pushg 1 putint[1]=2
41:pushc 10 
43:mod 
44:pushthis 
45:rpushg 1 loop[1]=doit
47:rpushg 1 doit[1]=putint
49:pushg 2 putint[2]=1
51:xstoreg 1 Indexed[2]=2
xstoreg:
Object: Indexed:1111 lsc: 0
VFields: 20 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
Rfields: * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
VStack: 
RStack: 
VdtTable: 0 0 0 0 
lscStack: 
--------------

53:pushthis 
54:rpushg 1 loop[1]=doit
56:rpushg 1 doit[1]=putint
58:pushthis 
59:rpushg 1 loop[1]=doit
61:rpushg 1 doit[1]=putint
63:pushg 1 putint[1]=2
65:pushc 10 
67:div 
68:storeg 1 putint[1]=0
70:pushthis 
71:rpushg 1 loop[1]=doit
73:rpushg 1 doit[1]=putint
75:pushg 1 putint[1]=0
77:pushc 0 
79:> 0>0
80:jmpFalse (0)91 
91:rtnEventQ 0 
93:setThisStack 
thisObj = loop[doit,doit][]  thisStack = doit[putint,putint][]
94:pushthis 

95:rtn D loop:1113:descInx:69  to: doit:1112:descInx:68 
thisObj = doit[putint,putint,loop][]  thisStack = doit[putint,putint,loop][]
13:rpop 
14:rtnEventQ 1 
16:doEventQ 
17:mvStack 
thisObj = doit[putint,putint][]  thisStack = doit[putint,putint][]
18:pushthis 
19:rpushg 1 doit[1]=putint
21:pushg 3 putint[3]=0
23:jmpFalse (0)30 
30:pushthis 

31:invoke 70 0 1 %for%to%%do%#S#70:1114:descInx:70 
thisObj = %for%to%%do%#S#70[doit,doit][]  thisStack = doit[putint,putint,doit][]
1:rstore 2 doit->%for%to%%do%#S#70[2]
3:allocEventQ 1 
5:pushthis 
6:rpushg 2 %for%to%%do%#S#70[2]=doit
8:rpushg 1 doit[1]=putint
10:rpushg 1 putint[1]=workspace
12:pushc 1 
14:pushthis 
15:rpushg 2 %for%to%%do%#S#70[2]=doit
17:rpushg 1 doit[1]=putint
19:pushg 2 putint[2]=1
21:toSuper 63 63 glsc: 1
1:pushthis 
2:storeg 2 %for%to%%do%#S#70[2]=1
4:pushthis 
5:storeg 1 %for%to%%do%#S#70[1]=1
7:rstore 1 workspace->%for%to%%do%#S#70[1]
9:allocEventQ 0 
11:mvStack 
thisObj = %for%to%%do%#S#70[doit,doit][]  thisStack = %for%to%%do%#S#70[doit,doit][]
12:rtnEventQ 1 
14:doEventQ 
15:mvStack 
thisObj = %for%to%%do%#S#70[doit,doit][]  thisStack = %for%to%%do%#S#70[doit,doit][]
16:pushthis 
17:pushthis 
18:pushg 1 %for%to%%do%#S#70[1]=1
20:storeg 3 %for%to%%do%#S#70[3]=1
22:pushthis 

23:invoke 64 0 1 do:1115:descInx:64 
thisObj = do[%for%to%%do%#S#70,%for%to%%do%#S#70][]  thisStack = %for%to%%do%#S#70[doit,doit,%for%to%%do%#S#70][]
1:rstore 1 %for%to%%do%#S#70->do[1]
3:allocEventQ 1 
5:mvStack 
thisObj = do[%for%to%%do%#S#70,%for%to%%do%#S#70][]  thisStack = do[%for%to%%do%#S#70,%for%to%%do%#S#70][]
6:pushthis 

7:invoke 65 2 1 loop:1116:descInx:65 
thisObj = loop[do,do][]  thisStack = do[%for%to%%do%#S#70,%for%to%%do%#S#70,do][]
1:rstore 1 do->loop[1]
3:allocEventQ 0 
5:mvStack 
thisObj = loop[do,do][]  thisStack = loop[do,do][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = loop[do,do][]  thisStack = loop[do,do][]
10:pushthis 
11:rpushg 1 loop[1]=do
13:rpushg 1 do[1]=%for%to%%do%#S#70
15:pushg 3 %for%to%%do%#S#70[3]=1
17:pushthis 
18:rpushg 1 loop[1]=do
20:rpushg 1 do[1]=%for%to%%do%#S#70
22:pushg 2 %for%to%%do%#S#70[2]=1
24:<= 
25:jmpFalse (1)36 
28:pushthis 

29:invoke 535 0 1 #S#535:1117:descInx:535 
thisObj = #S#535[loop,loop][]  thisStack = loop[do,do,loop][]
1:rstore 1 loop->#S#535[1]
3:allocEventQ 0 
5:mvStack 
thisObj = #S#535[loop,loop][]  thisStack = #S#535[loop,loop][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = #S#535[loop,loop][]  thisStack = #S#535[loop,loop][]
10:pushthis 
11:rpushg 1 #S#535[1]=loop
13:rpushg 1 loop[1]=do
15:rpushg 1 do[1]=%for%to%%do%#S#70
thisObj = #S#535[loop,loop,%for%to%%do%#S#70][]  thisStack = #S#535[loop,loop,%for%to%%do%#S#70][]

17:sendv  1 body#SB#537:1118:descInx:537 
thisObj = body#SB#537[#S#535,#S#535][]  thisStack = #S#535[loop,loop,%for%to%%do%#S#70][]
1:rstore 2 %for%to%%do%#S#70->body#SB#537[2]
3:allocEventQ 0 
5:mvStack 
thisObj = body#SB#537[#S#535,#S#535][]  thisStack = body#SB#537[#S#535,#S#535][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = body#SB#537[#S#535,#S#535][]  thisStack = body#SB#537[#S#535,#S#535][]
10:pushthis 
11:pushthis 
12:rpushg 2 body#SB#537[2]=%for%to%%do%#S#70
14:rpushg 2 %for%to%%do%#S#70[2]=doit
16:rpushg 1 doit[1]=putint
18:pushg 2 putint[2]=1
20:pushc 1 
22:pushthis 
23:rpushg 2 body#SB#537[2]=%for%to%%do%#S#70
25:pushg 3 %for%to%%do%#S#70[3]=1
27:- 1 1
28:+ 1 0
29:storeg 1 body#SB#537[1]=1
31:pushc 48 
33:pushthis 
34:rpushg 2 body#SB#537[2]=%for%to%%do%#S#70
36:rpushg 2 %for%to%%do%#S#70[2]=doit
38:rpushg 1 doit[1]=putint
40:rpushg 2 putint[2]=Indexed
42:pushthis 
43:pushg 1 body#SB#537[1]=1
45:xpushg 1 Indexed[2]=2
xpushg:
Object: Indexed:1111 lsc: 0
VFields: 20 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
Rfields: * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
VStack: 
RStack: 
VdtTable: 0 0 0 0 
lscStack: 
--------------

47:+ 48 2
48:%prim 2 50 2
50:rtnEventQ 0 
52:setThisStack 
thisObj = body#SB#537[#S#535,#S#535][]  thisStack = #S#535[loop,loop][]
53:pushthis 

54:rtn D body#SB#537:1118:descInx:537  to: #S#535:1117:descInx:535 
thisObj = #S#535[loop,loop,body#SB#537][]  thisStack = #S#535[loop,loop,body#SB#537][]
19:rpop 
20:pushthis 
21:rpushg 1 #S#535[1]=loop
23:rpushg 1 loop[1]=do
25:rpushg 1 do[1]=%for%to%%do%#S#70
27:pushthis 
28:rpushg 1 #S#535[1]=loop
30:rpushg 1 loop[1]=do
32:rpushg 1 do[1]=%for%to%%do%#S#70
34:pushg 3 %for%to%%do%#S#70[3]=1
36:pushc 1 
38:+ 1 1
39:storeg 3 %for%to%%do%#S#70[3]=2
41:break 1 81 
10:pushthis 
11:rpushg 1 loop[1]=do
13:rpushg 1 do[1]=%for%to%%do%#S#70
15:pushg 3 %for%to%%do%#S#70[3]=2
17:pushthis 
18:rpushg 1 loop[1]=do
20:rpushg 1 do[1]=%for%to%%do%#S#70
22:pushg 2 %for%to%%do%#S#70[2]=1
24:<= 
25:jmpFalse (0)36 
36:rtnEventQ 0 
38:setThisStack 
thisObj = loop[do,do][]  thisStack = do[%for%to%%do%#S#70,%for%to%%do%#S#70][]
39:pushthis 

40:rtn D loop:1116:descInx:65  to: do:1115:descInx:64 
thisObj = do[%for%to%%do%#S#70,%for%to%%do%#S#70,loop][]  thisStack = do[%for%to%%do%#S#70,%for%to%%do%#S#70,loop][]
13:rpop 
14:rtnEventQ 0 
16:mvStack 
thisObj = do[%for%to%%do%#S#70,%for%to%%do%#S#70][]  thisStack = do[%for%to%%do%#S#70,%for%to%%do%#S#70][]
17:rtnEventQ 0 
19:setThisStack 
thisObj = do[%for%to%%do%#S#70,%for%to%%do%#S#70][]  thisStack = %for%to%%do%#S#70[doit,doit][]
20:pushthis 

21:rtn D do:1115:descInx:64  to: %for%to%%do%#S#70:1114:descInx:70 
thisObj = %for%to%%do%#S#70[doit,doit,do][]  thisStack = %for%to%%do%#S#70[doit,doit,do][]
29:rpop 
30:rtnEventQ 0 
32:setThisStack 
thisObj = %for%to%%do%#S#70[doit,doit][]  thisStack = doit[putint,putint][]
33:pushthis 

34:rtn D %for%to%%do%#S#70:1114:descInx:70  to: doit:1112:descInx:68 
thisObj = doit[putint,putint,%for%to%%do%#S#70][]  thisStack = doit[putint,putint,%for%to%%do%#S#70][]
37:rpop 
38:rtnEventQ 0 
40:setThisStack 
thisObj = doit[putint,putint][]  thisStack = putint[List,List][]
41:pushthis 

42:rtn D doit:1112:descInx:68  to: putint:1110:descInx:67 
thisObj = putint[List,List,doit][]  thisStack = putint[List,List,doit][]
60:rpop 
61:rtnEventQ 0 
63:setThisStack 
thisObj = putint[List,List][]  thisStack = List[ArrayDemos,ArrayDemos][]
64:pushthis 

65:rtn D putint:1110:descInx:67  to: List:1016:descInx:441 
thisObj = List[ArrayDemos,ArrayDemos,putint][]  thisStack = List[ArrayDemos,ArrayDemos,putint][]
206:rpop 
207:pushthis 
208:rpushg 1 List[1]=ArrayDemos
210:rpushg 1 ArrayDemos[1]=demo
212:rpushg 1 demo[1]=workspace
214:pushthis 
215:rpushg 6 List[6]=Range
217:rpushg 2 Range[2]=Indexed
219:pushc 2 
221:xpushg 1 Indexed[3]=3
xpushg:
Object: Indexed:1061 lsc: 0
VFields: 2 2 3 
Rfields: * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
VStack: 
RStack: 
VdtTable: 0 0 0 0 
lscStack: 
--------------


223:invoke 67 0 0 putint:1119:descInx:67 
thisObj = putint[List,List][]  thisStack = List[ArrayDemos,ArrayDemos,workspace][3]
1:pushthis 
2:storeg 1 putint[1]=3
4:rstore 1 workspace->putint[1]
6:allocEventQ 0 
8:mvStack 
thisObj = putint[List,List][]  thisStack = putint[List,List][]
9:pushthis 
10:rpushg 1 putint[1]=workspace
12:pushc 20 
14:pushc 0 
16:pushc 1 

18:allocIndexed 52 1 
AllocQ_indexed:
Object: Indexed:1120 lsc: 0
VFields: 20 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
Rfields: * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
VStack: 
RStack: 
VdtTable: 0 0 0 0 
lscStack: 
--------------

22:pushthis 
23:rstoreg 2 putint[2]=Indexed
25:rtnEventQ 1 
27:doEventQ 
28:mvStack 
thisObj = putint[List,List][]  thisStack = putint[List,List][]
29:pushthis 
30:pushthis 
31:pushg 1 putint[1]=3
33:pushc 0 
35:< 3<0
36:storeg 3 putint[3]=0
38:pushthis 
39:pushg 3 putint[3]=0
41:jmpFalse (0)53 
53:pushthis 

54:invoke 68 0 0 doit:1121:descInx:68 
thisObj = doit[putint,putint][]  thisStack = putint[List,List,putint][]
1:rstore 1 putint->doit[1]
3:allocEventQ 0 
5:mvStack 
thisObj = doit[putint,putint][]  thisStack = doit[putint,putint][]
6:pushthis 

7:invoke 69 2 1 loop:1122:descInx:69 
thisObj = loop[doit,doit][]  thisStack = doit[putint,putint,doit][]
1:rstore 1 doit->loop[1]
3:allocEventQ 0 
5:mvStack 
thisObj = loop[doit,doit][]  thisStack = loop[doit,doit][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = loop[doit,doit][]  thisStack = loop[doit,doit][]
10:pushthis 
11:rpushg 1 loop[1]=doit
13:rpushg 1 doit[1]=putint
15:pushthis 
16:rpushg 1 loop[1]=doit
18:rpushg 1 doit[1]=putint
20:pushg 2 putint[2]=0
22:pushc 1 
24:+ 0 1
25:storeg 2 putint[2]=1
27:pushthis 
28:rpushg 1 loop[1]=doit
30:rpushg 1 doit[1]=putint
32:rpushg 2 putint[2]=Indexed
34:pushthis 
35:rpushg 1 loop[1]=doit
37:rpushg 1 doit[1]=putint
39:pushg 1 putint[1]=3
41:pushc 10 
43:mod 
44:pushthis 
45:rpushg 1 loop[1]=doit
47:rpushg 1 doit[1]=putint
49:pushg 2 putint[2]=1
51:xstoreg 1 Indexed[2]=3
xstoreg:
Object: Indexed:1120 lsc: 0
VFields: 20 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
Rfields: * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
VStack: 
RStack: 
VdtTable: 0 0 0 0 
lscStack: 
--------------

53:pushthis 
54:rpushg 1 loop[1]=doit
56:rpushg 1 doit[1]=putint
58:pushthis 
59:rpushg 1 loop[1]=doit
61:rpushg 1 doit[1]=putint
63:pushg 1 putint[1]=3
65:pushc 10 
67:div 
68:storeg 1 putint[1]=0
70:pushthis 
71:rpushg 1 loop[1]=doit
73:rpushg 1 doit[1]=putint
75:pushg 1 putint[1]=0
77:pushc 0 
79:> 0>0
80:jmpFalse (0)91 
91:rtnEventQ 0 
93:setThisStack 
thisObj = loop[doit,doit][]  thisStack = doit[putint,putint][]
94:pushthis 

95:rtn D loop:1122:descInx:69  to: doit:1121:descInx:68 
thisObj = doit[putint,putint,loop][]  thisStack = doit[putint,putint,loop][]
13:rpop 
14:rtnEventQ 1 
16:doEventQ 
17:mvStack 
thisObj = doit[putint,putint][]  thisStack = doit[putint,putint][]
18:pushthis 
19:rpushg 1 doit[1]=putint
21:pushg 3 putint[3]=0
23:jmpFalse (0)30 
30:pushthis 

31:invoke 70 0 1 %for%to%%do%#S#70:1123:descInx:70 
thisObj = %for%to%%do%#S#70[doit,doit][]  thisStack = doit[putint,putint,doit][]
1:rstore 2 doit->%for%to%%do%#S#70[2]
3:allocEventQ 1 
5:pushthis 
6:rpushg 2 %for%to%%do%#S#70[2]=doit
8:rpushg 1 doit[1]=putint
10:rpushg 1 putint[1]=workspace
12:pushc 1 
14:pushthis 
15:rpushg 2 %for%to%%do%#S#70[2]=doit
17:rpushg 1 doit[1]=putint
19:pushg 2 putint[2]=1
21:toSuper 63 63 glsc: 1
1:pushthis 
2:storeg 2 %for%to%%do%#S#70[2]=1
4:pushthis 
5:storeg 1 %for%to%%do%#S#70[1]=1
7:rstore 1 workspace->%for%to%%do%#S#70[1]
9:allocEventQ 0 
11:mvStack 
thisObj = %for%to%%do%#S#70[doit,doit][]  thisStack = %for%to%%do%#S#70[doit,doit][]
12:rtnEventQ 1 
14:doEventQ 
15:mvStack 
thisObj = %for%to%%do%#S#70[doit,doit][]  thisStack = %for%to%%do%#S#70[doit,doit][]
16:pushthis 
17:pushthis 
18:pushg 1 %for%to%%do%#S#70[1]=1
20:storeg 3 %for%to%%do%#S#70[3]=1
22:pushthis 

23:invoke 64 0 1 do:1124:descInx:64 
thisObj = do[%for%to%%do%#S#70,%for%to%%do%#S#70][]  thisStack = %for%to%%do%#S#70[doit,doit,%for%to%%do%#S#70][]
1:rstore 1 %for%to%%do%#S#70->do[1]
3:allocEventQ 1 
5:mvStack 
thisObj = do[%for%to%%do%#S#70,%for%to%%do%#S#70][]  thisStack = do[%for%to%%do%#S#70,%for%to%%do%#S#70][]
6:pushthis 

7:invoke 65 2 1 loop:1125:descInx:65 
thisObj = loop[do,do][]  thisStack = do[%for%to%%do%#S#70,%for%to%%do%#S#70,do][]
1:rstore 1 do->loop[1]
3:allocEventQ 0 
5:mvStack 
thisObj = loop[do,do][]  thisStack = loop[do,do][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = loop[do,do][]  thisStack = loop[do,do][]
10:pushthis 
11:rpushg 1 loop[1]=do
13:rpushg 1 do[1]=%for%to%%do%#S#70
15:pushg 3 %for%to%%do%#S#70[3]=1
17:pushthis 
18:rpushg 1 loop[1]=do
20:rpushg 1 do[1]=%for%to%%do%#S#70
22:pushg 2 %for%to%%do%#S#70[2]=1
24:<= 
25:jmpFalse (1)36 
28:pushthis 

29:invoke 535 0 1 #S#535:1126:descInx:535 
thisObj = #S#535[loop,loop][]  thisStack = loop[do,do,loop][]
1:rstore 1 loop->#S#535[1]
3:allocEventQ 0 
5:mvStack 
thisObj = #S#535[loop,loop][]  thisStack = #S#535[loop,loop][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = #S#535[loop,loop][]  thisStack = #S#535[loop,loop][]
10:pushthis 
11:rpushg 1 #S#535[1]=loop
13:rpushg 1 loop[1]=do
15:rpushg 1 do[1]=%for%to%%do%#S#70
thisObj = #S#535[loop,loop,%for%to%%do%#S#70][]  thisStack = #S#535[loop,loop,%for%to%%do%#S#70][]

17:sendv  1 body#SB#537:1127:descInx:537 
thisObj = body#SB#537[#S#535,#S#535][]  thisStack = #S#535[loop,loop,%for%to%%do%#S#70][]
1:rstore 2 %for%to%%do%#S#70->body#SB#537[2]
3:allocEventQ 0 
5:mvStack 
thisObj = body#SB#537[#S#535,#S#535][]  thisStack = body#SB#537[#S#535,#S#535][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = body#SB#537[#S#535,#S#535][]  thisStack = body#SB#537[#S#535,#S#535][]
10:pushthis 
11:pushthis 
12:rpushg 2 body#SB#537[2]=%for%to%%do%#S#70
14:rpushg 2 %for%to%%do%#S#70[2]=doit
16:rpushg 1 doit[1]=putint
18:pushg 2 putint[2]=1
20:pushc 1 
22:pushthis 
23:rpushg 2 body#SB#537[2]=%for%to%%do%#S#70
25:pushg 3 %for%to%%do%#S#70[3]=1
27:- 1 1
28:+ 1 0
29:storeg 1 body#SB#537[1]=1
31:pushc 48 
33:pushthis 
34:rpushg 2 body#SB#537[2]=%for%to%%do%#S#70
36:rpushg 2 %for%to%%do%#S#70[2]=doit
38:rpushg 1 doit[1]=putint
40:rpushg 2 putint[2]=Indexed
42:pushthis 
43:pushg 1 body#SB#537[1]=1
45:xpushg 1 Indexed[2]=3
xpushg:
Object: Indexed:1120 lsc: 0
VFields: 20 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
Rfields: * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
VStack: 
RStack: 
VdtTable: 0 0 0 0 
lscStack: 
--------------

47:+ 48 3
48:%prim 2 51 3
50:rtnEventQ 0 
52:setThisStack 
thisObj = body#SB#537[#S#535,#S#535][]  thisStack = #S#535[loop,loop][]
53:pushthis 

54:rtn D body#SB#537:1127:descInx:537  to: #S#535:1126:descInx:535 
thisObj = #S#535[loop,loop,body#SB#537][]  thisStack = #S#535[loop,loop,body#SB#537][]
19:rpop 
20:pushthis 
21:rpushg 1 #S#535[1]=loop
23:rpushg 1 loop[1]=do
25:rpushg 1 do[1]=%for%to%%do%#S#70
27:pushthis 
28:rpushg 1 #S#535[1]=loop
30:rpushg 1 loop[1]=do
32:rpushg 1 do[1]=%for%to%%do%#S#70
34:pushg 3 %for%to%%do%#S#70[3]=1
36:pushc 1 
38:+ 1 1
39:storeg 3 %for%to%%do%#S#70[3]=2
41:break 1 81 
10:pushthis 
11:rpushg 1 loop[1]=do
13:rpushg 1 do[1]=%for%to%%do%#S#70
15:pushg 3 %for%to%%do%#S#70[3]=2
17:pushthis 
18:rpushg 1 loop[1]=do
20:rpushg 1 do[1]=%for%to%%do%#S#70
22:pushg 2 %for%to%%do%#S#70[2]=1
24:<= 
25:jmpFalse (0)36 
36:rtnEventQ 0 
38:setThisStack 
thisObj = loop[do,do][]  thisStack = do[%for%to%%do%#S#70,%for%to%%do%#S#70][]
39:pushthis 

40:rtn D loop:1125:descInx:65  to: do:1124:descInx:64 
thisObj = do[%for%to%%do%#S#70,%for%to%%do%#S#70,loop][]  thisStack = do[%for%to%%do%#S#70,%for%to%%do%#S#70,loop][]
13:rpop 
14:rtnEventQ 0 
16:mvStack 
thisObj = do[%for%to%%do%#S#70,%for%to%%do%#S#70][]  thisStack = do[%for%to%%do%#S#70,%for%to%%do%#S#70][]
17:rtnEventQ 0 
19:setThisStack 
thisObj = do[%for%to%%do%#S#70,%for%to%%do%#S#70][]  thisStack = %for%to%%do%#S#70[doit,doit][]
20:pushthis 

21:rtn D do:1124:descInx:64  to: %for%to%%do%#S#70:1123:descInx:70 
thisObj = %for%to%%do%#S#70[doit,doit,do][]  thisStack = %for%to%%do%#S#70[doit,doit,do][]
29:rpop 
30:rtnEventQ 0 
32:setThisStack 
thisObj = %for%to%%do%#S#70[doit,doit][]  thisStack = doit[putint,putint][]
33:pushthis 

34:rtn D %for%to%%do%#S#70:1123:descInx:70  to: doit:1121:descInx:68 
thisObj = doit[putint,putint,%for%to%%do%#S#70][]  thisStack = doit[putint,putint,%for%to%%do%#S#70][]
37:rpop 
38:rtnEventQ 0 
40:setThisStack 
thisObj = doit[putint,putint][]  thisStack = putint[List,List][]
41:pushthis 

42:rtn D doit:1121:descInx:68  to: putint:1119:descInx:67 
thisObj = putint[List,List,doit][]  thisStack = putint[List,List,doit][]
60:rpop 
61:rtnEventQ 0 
63:setThisStack 
thisObj = putint[List,List][]  thisStack = List[ArrayDemos,ArrayDemos][]
64:pushthis 

65:rtn D putint:1119:descInx:67  to: List:1016:descInx:441 
thisObj = List[ArrayDemos,ArrayDemos,putint][]  thisStack = List[ArrayDemos,ArrayDemos,putint][]
229:rpop 
230:pushthis 
231:rpushg 1 List[1]=ArrayDemos
233:rpushg 1 ArrayDemos[1]=demo
235:rpushg 1 demo[1]=workspace
237:pushthis 
238:rpushg 7 List[7]=Range
240:rpushg 2 Range[2]=Indexed
242:pushc 1 
244:xpushg 1 Indexed[2]=4
xpushg:
Object: Indexed:1063 lsc: 0
VFields: 2 4 5 
Rfields: * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
VStack: 
RStack: 
VdtTable: 0 0 0 0 
lscStack: 
--------------


246:invoke 67 0 0 putint:1128:descInx:67 
thisObj = putint[List,List][]  thisStack = List[ArrayDemos,ArrayDemos,workspace][4]
1:pushthis 
2:storeg 1 putint[1]=4
4:rstore 1 workspace->putint[1]
6:allocEventQ 0 
8:mvStack 
thisObj = putint[List,List][]  thisStack = putint[List,List][]
9:pushthis 
10:rpushg 1 putint[1]=workspace
12:pushc 20 
14:pushc 0 
16:pushc 1 

18:allocIndexed 52 1 
AllocQ_indexed:
Object: Indexed:1129 lsc: 0
VFields: 20 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
Rfields: * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
VStack: 
RStack: 
VdtTable: 0 0 0 0 
lscStack: 
--------------

22:pushthis 
23:rstoreg 2 putint[2]=Indexed
25:rtnEventQ 1 
27:doEventQ 
28:mvStack 
thisObj = putint[List,List][]  thisStack = putint[List,List][]
29:pushthis 
30:pushthis 
31:pushg 1 putint[1]=4
33:pushc 0 
35:< 4<0
36:storeg 3 putint[3]=0
38:pushthis 
39:pushg 3 putint[3]=0
41:jmpFalse (0)53 
53:pushthis 

54:invoke 68 0 0 doit:1130:descInx:68 
thisObj = doit[putint,putint][]  thisStack = putint[List,List,putint][]
1:rstore 1 putint->doit[1]
3:allocEventQ 0 
5:mvStack 
thisObj = doit[putint,putint][]  thisStack = doit[putint,putint][]
6:pushthis 

7:invoke 69 2 1 loop:1131:descInx:69 
thisObj = loop[doit,doit][]  thisStack = doit[putint,putint,doit][]
1:rstore 1 doit->loop[1]
3:allocEventQ 0 
5:mvStack 
thisObj = loop[doit,doit][]  thisStack = loop[doit,doit][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = loop[doit,doit][]  thisStack = loop[doit,doit][]
10:pushthis 
11:rpushg 1 loop[1]=doit
13:rpushg 1 doit[1]=putint
15:pushthis 
16:rpushg 1 loop[1]=doit
18:rpushg 1 doit[1]=putint
20:pushg 2 putint[2]=0
22:pushc 1 
24:+ 0 1
25:storeg 2 putint[2]=1
27:pushthis 
28:rpushg 1 loop[1]=doit
30:rpushg 1 doit[1]=putint
32:rpushg 2 putint[2]=Indexed
34:pushthis 
35:rpushg 1 loop[1]=doit
37:rpushg 1 doit[1]=putint
39:pushg 1 putint[1]=4
41:pushc 10 
43:mod 
44:pushthis 
45:rpushg 1 loop[1]=doit
47:rpushg 1 doit[1]=putint
49:pushg 2 putint[2]=1
51:xstoreg 1 Indexed[2]=4
xstoreg:
Object: Indexed:1129 lsc: 0
VFields: 20 4 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
Rfields: * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
VStack: 
RStack: 
VdtTable: 0 0 0 0 
lscStack: 
--------------

53:pushthis 
54:rpushg 1 loop[1]=doit
56:rpushg 1 doit[1]=putint
58:pushthis 
59:rpushg 1 loop[1]=doit
61:rpushg 1 doit[1]=putint
63:pushg 1 putint[1]=4
65:pushc 10 
67:div 
68:storeg 1 putint[1]=0
70:pushthis 
71:rpushg 1 loop[1]=doit
73:rpushg 1 doit[1]=putint
75:pushg 1 putint[1]=0
77:pushc 0 
79:> 0>0
80:jmpFalse (0)91 
91:rtnEventQ 0 
93:setThisStack 
thisObj = loop[doit,doit][]  thisStack = doit[putint,putint][]
94:pushthis 

95:rtn D loop:1131:descInx:69  to: doit:1130:descInx:68 
thisObj = doit[putint,putint,loop][]  thisStack = doit[putint,putint,loop][]
13:rpop 
14:rtnEventQ 1 
16:doEventQ 
17:mvStack 
thisObj = doit[putint,putint][]  thisStack = doit[putint,putint][]
18:pushthis 
19:rpushg 1 doit[1]=putint
21:pushg 3 putint[3]=0
23:jmpFalse (0)30 
30:pushthis 

31:invoke 70 0 1 %for%to%%do%#S#70:1132:descInx:70 
thisObj = %for%to%%do%#S#70[doit,doit][]  thisStack = doit[putint,putint,doit][]
1:rstore 2 doit->%for%to%%do%#S#70[2]
3:allocEventQ 1 
5:pushthis 
6:rpushg 2 %for%to%%do%#S#70[2]=doit
8:rpushg 1 doit[1]=putint
10:rpushg 1 putint[1]=workspace
12:pushc 1 
14:pushthis 
15:rpushg 2 %for%to%%do%#S#70[2]=doit
17:rpushg 1 doit[1]=putint
19:pushg 2 putint[2]=1
21:toSuper 63 63 glsc: 1
1:pushthis 
2:storeg 2 %for%to%%do%#S#70[2]=1
4:pushthis 
5:storeg 1 %for%to%%do%#S#70[1]=1
7:rstore 1 workspace->%for%to%%do%#S#70[1]
9:allocEventQ 0 
11:mvStack 
thisObj = %for%to%%do%#S#70[doit,doit][]  thisStack = %for%to%%do%#S#70[doit,doit][]
12:rtnEventQ 1 
14:doEventQ 
15:mvStack 
thisObj = %for%to%%do%#S#70[doit,doit][]  thisStack = %for%to%%do%#S#70[doit,doit][]
16:pushthis 
17:pushthis 
18:pushg 1 %for%to%%do%#S#70[1]=1
20:storeg 3 %for%to%%do%#S#70[3]=1
22:pushthis 

23:invoke 64 0 1 do:1133:descInx:64 
thisObj = do[%for%to%%do%#S#70,%for%to%%do%#S#70][]  thisStack = %for%to%%do%#S#70[doit,doit,%for%to%%do%#S#70][]
1:rstore 1 %for%to%%do%#S#70->do[1]
3:allocEventQ 1 
5:mvStack 
thisObj = do[%for%to%%do%#S#70,%for%to%%do%#S#70][]  thisStack = do[%for%to%%do%#S#70,%for%to%%do%#S#70][]
6:pushthis 

7:invoke 65 2 1 loop:1134:descInx:65 
thisObj = loop[do,do][]  thisStack = do[%for%to%%do%#S#70,%for%to%%do%#S#70,do][]
1:rstore 1 do->loop[1]
3:allocEventQ 0 
5:mvStack 
thisObj = loop[do,do][]  thisStack = loop[do,do][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = loop[do,do][]  thisStack = loop[do,do][]
10:pushthis 
11:rpushg 1 loop[1]=do
13:rpushg 1 do[1]=%for%to%%do%#S#70
15:pushg 3 %for%to%%do%#S#70[3]=1
17:pushthis 
18:rpushg 1 loop[1]=do
20:rpushg 1 do[1]=%for%to%%do%#S#70
22:pushg 2 %for%to%%do%#S#70[2]=1
24:<= 
25:jmpFalse (1)36 
28:pushthis 

29:invoke 535 0 1 #S#535:1135:descInx:535 
thisObj = #S#535[loop,loop][]  thisStack = loop[do,do,loop][]
1:rstore 1 loop->#S#535[1]
3:allocEventQ 0 
5:mvStack 
thisObj = #S#535[loop,loop][]  thisStack = #S#535[loop,loop][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = #S#535[loop,loop][]  thisStack = #S#535[loop,loop][]
10:pushthis 
11:rpushg 1 #S#535[1]=loop
13:rpushg 1 loop[1]=do
15:rpushg 1 do[1]=%for%to%%do%#S#70
thisObj = #S#535[loop,loop,%for%to%%do%#S#70][]  thisStack = #S#535[loop,loop,%for%to%%do%#S#70][]

17:sendv  1 body#SB#537:1136:descInx:537 
thisObj = body#SB#537[#S#535,#S#535][]  thisStack = #S#535[loop,loop,%for%to%%do%#S#70][]
1:rstore 2 %for%to%%do%#S#70->body#SB#537[2]
3:allocEventQ 0 
5:mvStack 
thisObj = body#SB#537[#S#535,#S#535][]  thisStack = body#SB#537[#S#535,#S#535][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = body#SB#537[#S#535,#S#535][]  thisStack = body#SB#537[#S#535,#S#535][]
10:pushthis 
11:pushthis 
12:rpushg 2 body#SB#537[2]=%for%to%%do%#S#70
14:rpushg 2 %for%to%%do%#S#70[2]=doit
16:rpushg 1 doit[1]=putint
18:pushg 2 putint[2]=1
20:pushc 1 
22:pushthis 
23:rpushg 2 body#SB#537[2]=%for%to%%do%#S#70
25:pushg 3 %for%to%%do%#S#70[3]=1
27:- 1 1
28:+ 1 0
29:storeg 1 body#SB#537[1]=1
31:pushc 48 
33:pushthis 
34:rpushg 2 body#SB#537[2]=%for%to%%do%#S#70
36:rpushg 2 %for%to%%do%#S#70[2]=doit
38:rpushg 1 doit[1]=putint
40:rpushg 2 putint[2]=Indexed
42:pushthis 
43:pushg 1 body#SB#537[1]=1
45:xpushg 1 Indexed[2]=4
xpushg:
Object: Indexed:1129 lsc: 0
VFields: 20 4 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
Rfields: * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
VStack: 
RStack: 
VdtTable: 0 0 0 0 
lscStack: 
--------------

47:+ 48 4
48:%prim 2 52 4
50:rtnEventQ 0 
52:setThisStack 
thisObj = body#SB#537[#S#535,#S#535][]  thisStack = #S#535[loop,loop][]
53:pushthis 

54:rtn D body#SB#537:1136:descInx:537  to: #S#535:1135:descInx:535 
thisObj = #S#535[loop,loop,body#SB#537][]  thisStack = #S#535[loop,loop,body#SB#537][]
19:rpop 
20:pushthis 
21:rpushg 1 #S#535[1]=loop
23:rpushg 1 loop[1]=do
25:rpushg 1 do[1]=%for%to%%do%#S#70
27:pushthis 
28:rpushg 1 #S#535[1]=loop
30:rpushg 1 loop[1]=do
32:rpushg 1 do[1]=%for%to%%do%#S#70
34:pushg 3 %for%to%%do%#S#70[3]=1
36:pushc 1 
38:+ 1 1
39:storeg 3 %for%to%%do%#S#70[3]=2
41:break 1 81 
10:pushthis 
11:rpushg 1 loop[1]=do
13:rpushg 1 do[1]=%for%to%%do%#S#70
15:pushg 3 %for%to%%do%#S#70[3]=2
17:pushthis 
18:rpushg 1 loop[1]=do
20:rpushg 1 do[1]=%for%to%%do%#S#70
22:pushg 2 %for%to%%do%#S#70[2]=1
24:<= 
25:jmpFalse (0)36 
36:rtnEventQ 0 
38:setThisStack 
thisObj = loop[do,do][]  thisStack = do[%for%to%%do%#S#70,%for%to%%do%#S#70][]
39:pushthis 

40:rtn D loop:1134:descInx:65  to: do:1133:descInx:64 
thisObj = do[%for%to%%do%#S#70,%for%to%%do%#S#70,loop][]  thisStack = do[%for%to%%do%#S#70,%for%to%%do%#S#70,loop][]
13:rpop 
14:rtnEventQ 0 
16:mvStack 
thisObj = do[%for%to%%do%#S#70,%for%to%%do%#S#70][]  thisStack = do[%for%to%%do%#S#70,%for%to%%do%#S#70][]
17:rtnEventQ 0 
19:setThisStack 
thisObj = do[%for%to%%do%#S#70,%for%to%%do%#S#70][]  thisStack = %for%to%%do%#S#70[doit,doit][]
20:pushthis 

21:rtn D do:1133:descInx:64  to: %for%to%%do%#S#70:1132:descInx:70 
thisObj = %for%to%%do%#S#70[doit,doit,do][]  thisStack = %for%to%%do%#S#70[doit,doit,do][]
29:rpop 
30:rtnEventQ 0 
32:setThisStack 
thisObj = %for%to%%do%#S#70[doit,doit][]  thisStack = doit[putint,putint][]
33:pushthis 

34:rtn D %for%to%%do%#S#70:1132:descInx:70  to: doit:1130:descInx:68 
thisObj = doit[putint,putint,%for%to%%do%#S#70][]  thisStack = doit[putint,putint,%for%to%%do%#S#70][]
37:rpop 
38:rtnEventQ 0 
40:setThisStack 
thisObj = doit[putint,putint][]  thisStack = putint[List,List][]
41:pushthis 

42:rtn D doit:1130:descInx:68  to: putint:1128:descInx:67 
thisObj = putint[List,List,doit][]  thisStack = putint[List,List,doit][]
60:rpop 
61:rtnEventQ 0 
63:setThisStack 
thisObj = putint[List,List][]  thisStack = List[ArrayDemos,ArrayDemos][]
64:pushthis 

65:rtn D putint:1128:descInx:67  to: List:1016:descInx:441 
thisObj = List[ArrayDemos,ArrayDemos,putint][]  thisStack = List[ArrayDemos,ArrayDemos,putint][]
252:rpop 
253:pushthis 
254:rpushg 1 List[1]=ArrayDemos
256:rpushg 1 ArrayDemos[1]=demo
258:rpushg 1 demo[1]=workspace
260:pushthis 
261:rpushg 7 List[7]=Range
263:rpushg 2 Range[2]=Indexed
265:pushc 2 
267:xpushg 1 Indexed[3]=5
xpushg:
Object: Indexed:1063 lsc: 0
VFields: 2 4 5 
Rfields: * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
VStack: 
RStack: 
VdtTable: 0 0 0 0 
lscStack: 
--------------


269:invoke 67 0 0 putint:1137:descInx:67 
thisObj = putint[List,List][]  thisStack = List[ArrayDemos,ArrayDemos,workspace][5]
1:pushthis 
2:storeg 1 putint[1]=5
4:rstore 1 workspace->putint[1]
6:allocEventQ 0 
8:mvStack 
thisObj = putint[List,List][]  thisStack = putint[List,List][]
9:pushthis 
10:rpushg 1 putint[1]=workspace
12:pushc 20 
14:pushc 0 
16:pushc 1 

18:allocIndexed 52 1 
AllocQ_indexed:
Object: Indexed:1138 lsc: 0
VFields: 20 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
Rfields: * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
VStack: 
RStack: 
VdtTable: 0 0 0 0 
lscStack: 
--------------

22:pushthis 
23:rstoreg 2 putint[2]=Indexed
25:rtnEventQ 1 
27:doEventQ 
28:mvStack 
thisObj = putint[List,List][]  thisStack = putint[List,List][]
29:pushthis 
30:pushthis 
31:pushg 1 putint[1]=5
33:pushc 0 
35:< 5<0
36:storeg 3 putint[3]=0
38:pushthis 
39:pushg 3 putint[3]=0
41:jmpFalse (0)53 
53:pushthis 

54:invoke 68 0 0 doit:1139:descInx:68 
thisObj = doit[putint,putint][]  thisStack = putint[List,List,putint][]
1:rstore 1 putint->doit[1]
3:allocEventQ 0 
5:mvStack 
thisObj = doit[putint,putint][]  thisStack = doit[putint,putint][]
6:pushthis 

7:invoke 69 2 1 loop:1140:descInx:69 
thisObj = loop[doit,doit][]  thisStack = doit[putint,putint,doit][]
1:rstore 1 doit->loop[1]
3:allocEventQ 0 
5:mvStack 
thisObj = loop[doit,doit][]  thisStack = loop[doit,doit][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = loop[doit,doit][]  thisStack = loop[doit,doit][]
10:pushthis 
11:rpushg 1 loop[1]=doit
13:rpushg 1 doit[1]=putint
15:pushthis 
16:rpushg 1 loop[1]=doit
18:rpushg 1 doit[1]=putint
20:pushg 2 putint[2]=0
22:pushc 1 
24:+ 0 1
25:storeg 2 putint[2]=1
27:pushthis 
28:rpushg 1 loop[1]=doit
30:rpushg 1 doit[1]=putint
32:rpushg 2 putint[2]=Indexed
34:pushthis 
35:rpushg 1 loop[1]=doit
37:rpushg 1 doit[1]=putint
39:pushg 1 putint[1]=5
41:pushc 10 
43:mod 
44:pushthis 
45:rpushg 1 loop[1]=doit
47:rpushg 1 doit[1]=putint
49:pushg 2 putint[2]=1
51:xstoreg 1 Indexed[2]=5
xstoreg:
Object: Indexed:1138 lsc: 0
VFields: 20 5 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
Rfields: * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
VStack: 
RStack: 
VdtTable: 0 0 0 0 
lscStack: 
--------------

53:pushthis 
54:rpushg 1 loop[1]=doit
56:rpushg 1 doit[1]=putint
58:pushthis 
59:rpushg 1 loop[1]=doit
61:rpushg 1 doit[1]=putint
63:pushg 1 putint[1]=5
65:pushc 10 
67:div 
68:storeg 1 putint[1]=0
70:pushthis 
71:rpushg 1 loop[1]=doit
73:rpushg 1 doit[1]=putint
75:pushg 1 putint[1]=0
77:pushc 0 
79:> 0>0
80:jmpFalse (0)91 
91:rtnEventQ 0 
93:setThisStack 
thisObj = loop[doit,doit][]  thisStack = doit[putint,putint][]
94:pushthis 

95:rtn D loop:1140:descInx:69  to: doit:1139:descInx:68 
thisObj = doit[putint,putint,loop][]  thisStack = doit[putint,putint,loop][]
13:rpop 
14:rtnEventQ 1 
16:doEventQ 
17:mvStack 
thisObj = doit[putint,putint][]  thisStack = doit[putint,putint][]
18:pushthis 
19:rpushg 1 doit[1]=putint
21:pushg 3 putint[3]=0
23:jmpFalse (0)30 
30:pushthis 

31:invoke 70 0 1 %for%to%%do%#S#70:1141:descInx:70 
thisObj = %for%to%%do%#S#70[doit,doit][]  thisStack = doit[putint,putint,doit][]
1:rstore 2 doit->%for%to%%do%#S#70[2]
3:allocEventQ 1 
5:pushthis 
6:rpushg 2 %for%to%%do%#S#70[2]=doit
8:rpushg 1 doit[1]=putint
10:rpushg 1 putint[1]=workspace
12:pushc 1 
14:pushthis 
15:rpushg 2 %for%to%%do%#S#70[2]=doit
17:rpushg 1 doit[1]=putint
19:pushg 2 putint[2]=1
21:toSuper 63 63 glsc: 1
1:pushthis 
2:storeg 2 %for%to%%do%#S#70[2]=1
4:pushthis 
5:storeg 1 %for%to%%do%#S#70[1]=1
7:rstore 1 workspace->%for%to%%do%#S#70[1]
9:allocEventQ 0 
11:mvStack 
thisObj = %for%to%%do%#S#70[doit,doit][]  thisStack = %for%to%%do%#S#70[doit,doit][]
12:rtnEventQ 1 
14:doEventQ 
15:mvStack 
thisObj = %for%to%%do%#S#70[doit,doit][]  thisStack = %for%to%%do%#S#70[doit,doit][]
16:pushthis 
17:pushthis 
18:pushg 1 %for%to%%do%#S#70[1]=1
20:storeg 3 %for%to%%do%#S#70[3]=1
22:pushthis 

23:invoke 64 0 1 do:1142:descInx:64 
thisObj = do[%for%to%%do%#S#70,%for%to%%do%#S#70][]  thisStack = %for%to%%do%#S#70[doit,doit,%for%to%%do%#S#70][]
1:rstore 1 %for%to%%do%#S#70->do[1]
3:allocEventQ 1 
5:mvStack 
thisObj = do[%for%to%%do%#S#70,%for%to%%do%#S#70][]  thisStack = do[%for%to%%do%#S#70,%for%to%%do%#S#70][]
6:pushthis 

7:invoke 65 2 1 loop:1143:descInx:65 
thisObj = loop[do,do][]  thisStack = do[%for%to%%do%#S#70,%for%to%%do%#S#70,do][]
1:rstore 1 do->loop[1]
3:allocEventQ 0 
5:mvStack 
thisObj = loop[do,do][]  thisStack = loop[do,do][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = loop[do,do][]  thisStack = loop[do,do][]
10:pushthis 
11:rpushg 1 loop[1]=do
13:rpushg 1 do[1]=%for%to%%do%#S#70
15:pushg 3 %for%to%%do%#S#70[3]=1
17:pushthis 
18:rpushg 1 loop[1]=do
20:rpushg 1 do[1]=%for%to%%do%#S#70
22:pushg 2 %for%to%%do%#S#70[2]=1
24:<= 
25:jmpFalse (1)36 
28:pushthis 

29:invoke 535 0 1 #S#535:1144:descInx:535 
thisObj = #S#535[loop,loop][]  thisStack = loop[do,do,loop][]
1:rstore 1 loop->#S#535[1]
3:allocEventQ 0 
5:mvStack 
thisObj = #S#535[loop,loop][]  thisStack = #S#535[loop,loop][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = #S#535[loop,loop][]  thisStack = #S#535[loop,loop][]
10:pushthis 
11:rpushg 1 #S#535[1]=loop
13:rpushg 1 loop[1]=do
15:rpushg 1 do[1]=%for%to%%do%#S#70
thisObj = #S#535[loop,loop,%for%to%%do%#S#70][]  thisStack = #S#535[loop,loop,%for%to%%do%#S#70][]

17:sendv  1 body#SB#537:1145:descInx:537 
thisObj = body#SB#537[#S#535,#S#535][]  thisStack = #S#535[loop,loop,%for%to%%do%#S#70][]
1:rstore 2 %for%to%%do%#S#70->body#SB#537[2]
3:allocEventQ 0 
5:mvStack 
thisObj = body#SB#537[#S#535,#S#535][]  thisStack = body#SB#537[#S#535,#S#535][]
6:rtnEventQ 1 
8:doEventQ 
9:mvStack 
thisObj = body#SB#537[#S#535,#S#535][]  thisStack = body#SB#537[#S#535,#S#535][]
10:pushthis 
11:pushthis 
12:rpushg 2 body#SB#537[2]=%for%to%%do%#S#70
14:rpushg 2 %for%to%%do%#S#70[2]=doit
16:rpushg 1 doit[1]=putint
18:pushg 2 putint[2]=1
20:pushc 1 
22:pushthis 
23:rpushg 2 body#SB#537[2]=%for%to%%do%#S#70
25:pushg 3 %for%to%%do%#S#70[3]=1
27:- 1 1
28:+ 1 0
29:storeg 1 body#SB#537[1]=1
31:pushc 48 
33:pushthis 
34:rpushg 2 body#SB#537[2]=%for%to%%do%#S#70
36:rpushg 2 %for%to%%do%#S#70[2]=doit
38:rpushg 1 doit[1]=putint
40:rpushg 2 putint[2]=Indexed
42:pushthis 
43:pushg 1 body#SB#537[1]=1
45:xpushg 1 Indexed[2]=5
xpushg:
Object: Indexed:1138 lsc: 0
VFields: 20 5 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
Rfields: * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
VStack: 
RStack: 
VdtTable: 0 0 0 0 
lscStack: 
--------------

47:+ 48 5
48:%prim 2 53 5
50:rtnEventQ 0 
52:setThisStack 
thisObj = body#SB#537[#S#535,#S#535][]  thisStack = #S#535[loop,loop][]
53:pushthis 

54:rtn D body#SB#537:1145:descInx:537  to: #S#535:1144:descInx:535 
thisObj = #S#535[loop,loop,body#SB#537][]  thisStack = #S#535[loop,loop,body#SB#537][]
19:rpop 
20:pushthis 
21:rpushg 1 #S#535[1]=loop
23:rpushg 1 loop[1]=do
25:rpushg 1 do[1]=%for%to%%do%#S#70
27:pushthis 
28:rpushg 1 #S#535[1]=loop
30:rpushg 1 loop[1]=do
32:rpushg 1 do[1]=%for%to%%do%#S#70
34:pushg 3 %for%to%%do%#S#70[3]=1
36:pushc 1 
38:+ 1 1
39:storeg 3 %for%to%%do%#S#70[3]=2
41:break 1 81 
10:pushthis 
11:rpushg 1 loop[1]=do
13:rpushg 1 do[1]=%for%to%%do%#S#70
15:pushg 3 %for%to%%do%#S#70[3]=2
17:pushthis 
18:rpushg 1 loop[1]=do
20:rpushg 1 do[1]=%for%to%%do%#S#70
22:pushg 2 %for%to%%do%#S#70[2]=1
24:<= 
25:jmpFalse (0)36 
36:rtnEventQ 0 
38:setThisStack 
thisObj = loop[do,do][]  thisStack = do[%for%to%%do%#S#70,%for%to%%do%#S#70][]
39:pushthis 

40:rtn D loop:1143:descInx:65  to: do:1142:descInx:64 
thisObj = do[%for%to%%do%#S#70,%for%to%%do%#S#70,loop][]  thisStack = do[%for%to%%do%#S#70,%for%to%%do%#S#70,loop][]
13:rpop 
14:rtnEventQ 0 
16:mvStack 
thisObj = do[%for%to%%do%#S#70,%for%to%%do%#S#70][]  thisStack = do[%for%to%%do%#S#70,%for%to%%do%#S#70][]
17:rtnEventQ 0 
19:setThisStack 
thisObj = do[%for%to%%do%#S#70,%for%to%%do%#S#70][]  thisStack = %for%to%%do%#S#70[doit,doit][]
20:pushthis 

21:rtn D do:1142:descInx:64  to: %for%to%%do%#S#70:1141:descInx:70 
thisObj = %for%to%%do%#S#70[doit,doit,do][]  thisStack = %for%to%%do%#S#70[doit,doit,do][]
29:rpop 
30:rtnEventQ 0 
32:setThisStack 
thisObj = %for%to%%do%#S#70[doit,doit][]  thisStack = doit[putint,putint][]
33:pushthis 

34:rtn D %for%to%%do%#S#70:1141:descInx:70  to: doit:1139:descInx:68 
thisObj = doit[putint,putint,%for%to%%do%#S#70][]  thisStack = doit[putint,putint,%for%to%%do%#S#70][]
37:rpop 
38:rtnEventQ 0 
40:setThisStack 
thisObj = doit[putint,putint][]  thisStack = putint[List,List][]
41:pushthis 

42:rtn D doit:1139:descInx:68  to: putint:1137:descInx:67 
thisObj = putint[List,List,doit][]  thisStack = putint[List,List,doit][]
60:rpop 
61:rtnEventQ 0 
63:setThisStack 
thisObj = putint[List,List][]  thisStack = List[ArrayDemos,ArrayDemos][]
64:pushthis 

65:rtn D putint:1137:descInx:67  to: List:1016:descInx:441 
thisObj = List[ArrayDemos,ArrayDemos,putint][]  thisStack = List[ArrayDemos,ArrayDemos,putint][]
275:rpop 
276:pushthis 
277:pushthis 
278:pushthis 
279:rpushg 6 List[6]=Range
281:pushthis 
282:pushthis 
283:rpushg 7 List[7]=Range
285:pushthis 
286:rpushg 4 List[4]=List#S#637

288:invoke 445 0 0 RangeList:1146:descInx:445 
thisObj = RangeList[List,List][]  thisStack = List[ArrayDemos,ArrayDemos,List,List,Range,List,Range,List#S#637][]
1:rstore 1 List#S#637->RangeList[1]
3:allocEventQ 0 
5:pushthis 
6:rpushg 1 RangeList[1]=List#S#637
8:pushthis 
9:rpushg 1 RangeList[1]=List#S#637
11:rpushg 1 List#S#637[1]=List

13:invoke 447 0 0 Range:1147:descInx:447 
thisObj = Range[RangeList,List][]  thisStack = List[ArrayDemos,ArrayDemos,List,List,Range,List,Range,List#S#637,List][]
1:pushthis 
2:rstoreg 2 Range[2]=List
4:rstore 1 List#S#637->Range[1]
6:allocEventQ 0 
8:mvStack 
thisObj = Range[RangeList,List][]  thisStack = Range[RangeList,List][]

9:innerA 1  exe: 0

11:rtnEventQ 1 
13:doEventQ 
14:mvStack 
thisObj = Range[RangeList,List][]  thisStack = Range[RangeList,List][]
15:pushthis 

16:inner P 1  exe: 0

18:rpopThisObj 
19:rtnEventQ 0 
21:setThisStack 
thisObj = Range[RangeList,List][]  thisStack = List[ArrayDemos,ArrayDemos,List,List,Range,List,Range][]
22:pushthis 

23:rtn D Range:1147:descInx:447  to: RangeList:1146:descInx:445 
thisObj = RangeList[List,List][]  thisStack = List[ArrayDemos,ArrayDemos,List,List,Range,List,Range,Range][]
19:toSuper 443 443 glsc: 1
1:pushthis 
2:rstoreg 3 RangeList[3]=Range
4:pushthis 
5:rstoreg 2 RangeList[2]=Range
7:rstore 1 List->RangeList[1]
9:allocEventQ 1 
11:mvStack 
thisObj = RangeList[List,List][]  thisStack = RangeList[List,List][]
12:rtnEventQ 0 
14:mvStack 
thisObj = RangeList[List,List][]  thisStack = RangeList[List,List][]
15:rtnEventQ 0 
17:setThisStack 
thisObj = RangeList[List,List][]  thisStack = List[ArrayDemos,ArrayDemos,List,List,Range][]
18:pushthis 

19:rtn D RangeList:1146:descInx:445  to: List:1016:descInx:441 
thisObj = List[ArrayDemos,ArrayDemos,List,List,Range,RangeList][]  thisStack = List[ArrayDemos,ArrayDemos,List,List,Range,RangeList][]

294:invoke 445 0 0 RangeList:1148:descInx:445 
thisObj = RangeList[List,List][]  thisStack = List[ArrayDemos,ArrayDemos,List,List,Range,RangeList][]
1:rstore 1 RangeList->RangeList[1]
3:allocEventQ 0 
5:pushthis 
6:rpushg 1 RangeList[1]=RangeList
8:pushthis 
9:rpushg 1 RangeList[1]=RangeList
11:rpushg 1 RangeList[1]=List

13:invoke 447 0 0 Range:1149:descInx:447 
thisObj = Range[RangeList,List][]  thisStack = List[ArrayDemos,ArrayDemos,List,List,Range,RangeList,List][]
1:pushthis 
2:rstoreg 2 Range[2]=List
4:rstore 1 RangeList->Range[1]
6:allocEventQ 0 
8:mvStack 
thisObj = Range[RangeList,List][]  thisStack = Range[RangeList,List][]

9:innerA 1  exe: 0

11:rtnEventQ 1 
13:doEventQ 
14:mvStack 
thisObj = Range[RangeList,List][]  thisStack = Range[RangeList,List][]
15:pushthis 

16:inner P 1  exe: 0

18:rpopThisObj 
19:rtnEventQ 0 
21:setThisStack 
thisObj = Range[RangeList,List][]  thisStack = List[ArrayDemos,ArrayDemos,List,List,Range][]
22:pushthis 

23:rtn D Range:1149:descInx:447  to: RangeList:1148:descInx:445 
thisObj = RangeList[List,List][]  thisStack = List[ArrayDemos,ArrayDemos,List,List,Range,Range][]
19:toSuper 443 443 glsc: 1
1:pushthis 
2:rstoreg 3 RangeList[3]=Range
4:pushthis 
5:rstoreg 2 RangeList[2]=Range
7:rstore 1 List->RangeList[1]
9:allocEventQ 1 
11:mvStack 
thisObj = RangeList[List,List][]  thisStack = RangeList[List,List][]
12:rtnEventQ 0 
14:mvStack 
thisObj = RangeList[List,List][]  thisStack = RangeList[List,List][]
15:rtnEventQ 0 
17:setThisStack 
thisObj = RangeList[List,List][]  thisStack = List[ArrayDemos,ArrayDemos,List][]
18:pushthis 

19:rtn D RangeList:1148:descInx:445  to: List:1016:descInx:441 
thisObj = List[ArrayDemos,ArrayDemos,List,RangeList][]  thisStack = List[ArrayDemos,ArrayDemos,List,RangeList][]
300:rswap 
301:rstoreg 2 List[2]=RangeList
303:pushthis 
304:pushthis 
305:pushc 2 
307:pushthis 
308:rpushg 2 List[2]=RangeList

310:invoke 448 0 0 testArray:1150:descInx:448 
thisObj = testArray[List,List][]  thisStack = List[ArrayDemos,ArrayDemos,List,List,RangeList][2]
1:pushthis 
2:pushthis 
3:storeg 1 testArray[1]=2
5:rstore 1 testArray->testArray[1]
7:allocEventQ 0 
9:mvStack 
thisObj = testArray[List,List][]  thisStack = testArray[List,List][]

10:innerA 1  exe: 0

12:rtnEventQ 1 
14:doEventQ 
15:mvStack 
thisObj = testArray[List,List][]  thisStack = testArray[List,List][]
16:pushthis 

17:inner P 1  exe: 0

19:rpopThisObj 
20:rtnEventQ 0 
22:setThisStack 
thisObj = testArray[List,List][]  thisStack = List[ArrayDemos,ArrayDemos,List,List,RangeList][]
23:pushthis 

24:rtn D testArray:1150:descInx:448  to: List:1016:descInx:441 
thisObj = List[ArrayDemos,ArrayDemos,List,List,RangeList,testArray][]  thisStack = List[ArrayDemos,ArrayDemos,List,List,RangeList,testArray][]
316:rswap 
317:rstoreg 8 RangeList[8]=testArray
319:pushthis 
320:pushthis 
321:pushc 2 
323:pushthis 
324:pushthis 
325:rpushg 6 List[6]=Range
327:pushthis 
328:pushthis 
329:rpushg 7 List[7]=Range
331:pushthis 
332:rpushg 4 List[4]=List#S#637

334:invoke 445 0 0 RangeList:1151:descInx:445 
thisObj = RangeList[List,List][]  thisStack = List[ArrayDemos,ArrayDemos,List,List,List,List,List,Range,List,Range,List#S#637][2]
1:rstore 1 List#S#637->RangeList[1]
3:allocEventQ 0 
5:pushthis 
6:rpushg 1 RangeList[1]=List#S#637
8:pushthis 
9:rpushg 1 RangeList[1]=List#S#637
11:rpushg 1 List#S#637[1]=List

13:invoke 447 0 0 Range:1152:descInx:447 
thisObj = Range[RangeList,List][]  thisStack = List[ArrayDemos,ArrayDemos,List,List,List,List,List,Range,List,Range,List#S#637,List][2]
1:pushthis 
2:rstoreg 2 Range[2]=List
4:rstore 1 List#S#637->Range[1]
6:allocEventQ 0 
8:mvStack 
thisObj = Range[RangeList,List][]  thisStack = Range[RangeList,List][]

9:innerA 1  exe: 0

11:rtnEventQ 1 
13:doEventQ 
14:mvStack 
thisObj = Range[RangeList,List][]  thisStack = Range[RangeList,List][]
15:pushthis 

16:inner P 1  exe: 0

18:rpopThisObj 
19:rtnEventQ 0 
21:setThisStack 
thisObj = Range[RangeList,List][]  thisStack = List[ArrayDemos,ArrayDemos,List,List,List,List,List,Range,List,Range][2]
22:pushthis 

23:rtn D Range:1152:descInx:447  to: RangeList:1151:descInx:445 
thisObj = RangeList[List,List][]  thisStack = List[ArrayDemos,ArrayDemos,List,List,List,List,List,Range,List,Range,Range][2]
19:toSuper 443 443 glsc: 1
1:pushthis 
2:rstoreg 3 RangeList[3]=Range
4:pushthis 
5:rstoreg 2 RangeList[2]=Range
7:rstore 1 List->RangeList[1]
9:allocEventQ 1 
11:mvStack 
thisObj = RangeList[List,List][]  thisStack = RangeList[List,List][]
12:rtnEventQ 0 
14:mvStack 
thisObj = RangeList[List,List][]  thisStack = RangeList[List,List][]
15:rtnEventQ 0 
17:setThisStack 
thisObj = RangeList[List,List][]  thisStack = List[ArrayDemos,ArrayDemos,List,List,List,List,List,Range][2]
18:pushthis 

19:rtn D RangeList:1151:descInx:445  to: List:1016:descInx:441 
thisObj = List[ArrayDemos,ArrayDemos,List,List,List,List,List,Range,RangeList][2]  thisStack = List[ArrayDemos,ArrayDemos,List,List,List,List,List,Range,RangeList][2]

340:invoke 445 0 0 RangeList:1153:descInx:445 
thisObj = RangeList[List,List][]  thisStack = List[ArrayDemos,ArrayDemos,List,List,List,List,List,Range,RangeList][2]
1:rstore 1 RangeList->RangeList[1]
3:allocEventQ 0 
5:pushthis 
6:rpushg 1 RangeList[1]=RangeList
8:pushthis 
9:rpushg 1 RangeList[1]=RangeList
11:rpushg 1 RangeList[1]=List

13:invoke 447 0 0 Range:1154:descInx:447 
thisObj = Range[RangeList,List][]  thisStack = List[ArrayDemos,ArrayDemos,List,List,List,List,List,Range,RangeList,List][2]
1:pushthis 
2:rstoreg 2 Range[2]=List
4:rstore 1 RangeList->Range[1]
6:allocEventQ 0 
8:mvStack 
thisObj = Range[RangeList,List][]  thisStack = Range[RangeList,List][]

9:innerA 1  exe: 0

11:rtnEventQ 1 
13:doEventQ 
14:mvStack 
thisObj = Range[RangeList,List][]  thisStack = Range[RangeList,List][]
15:pushthis 

16:inner P 1  exe: 0

18:rpopThisObj 
19:rtnEventQ 0 
21:setThisStack 
thisObj = Range[RangeList,List][]  thisStack = List[ArrayDemos,ArrayDemos,List,List,List,List,List,Range][2]
22:pushthis 

23:rtn D Range:1154:descInx:447  to: RangeList:1153:descInx:445 
thisObj = RangeList[List,List][]  thisStack = List[ArrayDemos,ArrayDemos,List,List,List,List,List,Range,Range][2]
19:toSuper 443 443 glsc: 1
1:pushthis 
2:rstoreg 3 RangeList[3]=Range
4:pushthis 
5:rstoreg 2 RangeList[2]=Range
7:rstore 1 List->RangeList[1]
9:allocEventQ 1 
11:mvStack 
thisObj = RangeList[List,List][]  thisStack = RangeList[List,List][]
12:rtnEventQ 0 
14:mvStack 
thisObj = RangeList[List,List][]  thisStack = RangeList[List,List][]
15:rtnEventQ 0 
17:setThisStack 
thisObj = RangeList[List,List][]  thisStack = List[ArrayDemos,ArrayDemos,List,List,List,List][2]
18:pushthis 

19:rtn D RangeList:1153:descInx:445  to: List:1016:descInx:441 
thisObj = List[ArrayDemos,ArrayDemos,List,List,List,List,RangeList][2]  thisStack = List[ArrayDemos,ArrayDemos,List,List,List,List,RangeList][2]

346:invoke 448 0 0 testArray:1155:descInx:448 
thisObj = testArray[List,List][]  thisStack = List[ArrayDemos,ArrayDemos,List,List,List,List,RangeList][2]
1:pushthis 
2:pushthis 
3:storeg 1 testArray[1]=2
5:rstore 1 testArray->testArray[1]
7:allocEventQ 0 
9:mvStack 
thisObj = testArray[List,List][]  thisStack = testArray[List,List][]

10:innerA 1  exe: 0

12:rtnEventQ 1 
14:doEventQ 
15:mvStack 
thisObj = testArray[List,List][]  thisStack = testArray[List,List][]
16:pushthis 

17:inner P 1  exe: 0

19:rpopThisObj 
20:rtnEventQ 0 
22:setThisStack 
thisObj = testArray[List,List][]  thisStack = List[ArrayDemos,ArrayDemos,List,List,List,List,RangeList][]
23:pushthis 

24:rtn D testArray:1155:descInx:448  to: List:1016:descInx:441 
thisObj = List[ArrayDemos,ArrayDemos,List,List,List,List,RangeList,testArray][]  thisStack = List[ArrayDemos,ArrayDemos,List,List,List,List,RangeList,testArray][]
352:rswap 
353:rstoreg 8 RangeList[8]=testArray
355:rtnEventQ 0 
357:setThisStack 
thisObj = List[ArrayDemos,ArrayDemos,List,List,List,List][]  thisStack = List[ArrayDemos,ArrayDemos,List,List,List,List][]
358:pushthis 

359:rtn D List:1016:descInx:441  to: List:1016:descInx:441 