#!/usr/local/bin/perl -s

my ($BETALIB) = $ENV{'BETALIB'};
my ($verbose) = $v;

print STDERR "Updating $BETALIB/man\n" if ($verbose);
if ($verbose){
    system "cd $BETALIB/man; perl -s build -v";
} else {
    system "cd $BETALIB/man; perl -s build";
}

if (! -d "src"){
    mkdir ("src", 0755) || die "Cannot create directory 'src': $!\n";
}

my ($dir) = "$BETALIB/man/cat1";
my @files = ();

opendir(DIR, $dir) || die "Failed to open $dir: $!";

foreach $file (readdir DIR) {
    next if ($file eq '.' or $file eq '..');
    push (@files, $file) if ($file =~ m%\.1$%);
}

if ($#files==-1){
    print STDERR "No .1 files found?\n";
} else {
    foreach $file (@files){
	my ($html, $title);
	$html = $file;
	$html =~ s%\.1$%%;
	$title = "Manpage for $html";
	$html = "src/" . $html . ".html";
	print STDERR "Generating $html\n      from $dir/$file\n" if ($verbose);
	system "perl ../bin/man2html -cgiurl '$title.html' -sun -compress -title '$title' < $dir/$file > $html";
    }
}
1;
