#!/bin/sh

# set -x

sh -c 'cd $BETALIB/man; make'

FILES=`sh -c 'cd $BETALIB/man/cat1; echo *.1'`

for f in $FILES
do
   html=`basename $f .1`.html
   title=`basename $f .1`
   title="Manpage for $title"
   echo "Converting $BETALIB/man/cat1/$f -> $html"
   ../bin/man2html -sun -compress -title "$title" < $BETALIB/man/cat1/$f > $html
done