<HTML>

<HEAD>
<TITLE>The BETA Home Page</TITLE>
<LINK REV="made" HREF="mailto:jlk@daimi.au.dk">
<LINK REL="stylesheet" HREF="http://www.daimi.au.dk/~beta/doc/style/miadoc.css" TYPE="text/css">
</HEAD>

<BODY>

<A HREF="/~beta/Icons/beta/beta.pjs.big.gif"><IMG SRC="/~beta/Icons/beta/beta.pjs.gif" ALT=""></A>

<H1>The BETA Home Page</H1>

Welcome to the WWW home page for the object-oriented BETA 
programming language.
The home page contains information on the BETA language and its 
environments. 
The material is gathered from many sources, and will be augmented with 
as much public information as possible. 
If you wish to supply material for this page, or would like us to 
make links to some of your material, please do not hesitate to contact 
us.
<P>

<H2><A NAME="info@mjolner">The Mj&oslash;lner System Home Page</A></H2>

You may find more information on BETA and the Mj&oslash;lner System 
at the 
<UL>
<LI><A HREF="http://www.mjolner.com/mjolner-system/" TARGET="_top">Mj&oslash;lner System Home Page</A>
</UL>
maintained by <A HREF="http://www.mjolner.com/" TARGET="_top">Mj&oslash;lner Informatics</A>, Denmark.

<H2><A NAME="faq">Frequently Asked Questions</A></H2>
<UL>
<LI><A HREF="doc/faq/beta-language-faq.html">BETA Programming Language FAQ</A>
</UL>

<H2><A NAME="newsgroup">Newsgroups</A></H2>
<UL>
<LI><A HREF="news:comp.lang.beta"><TT>comp.lang.beta</TT></A>
<LI><TT>comp.lang.beta</TT> <A HREF="News/index.html">news archive</A>
<LI><A HREF="news:comp.object"><TT>comp.object</TT></A>
</UL>

<H2><A NAME="ftp">FTP Services</A></H2>
<UL>
<LI><A HREF="ftp://ftp.daimi.au.dk/pub/beta">Aarhus University BETA archive</A>
</UL>

<H2><A NAME="tutorial">Tutorials</A></H2>

<UL>
<LI><A HREF="doc/tutorials.html">List of tutorials</A>
<LI><A HREF="doc/beta-intro/Terminology.html">BETA Terminology</A>
<LI><A HREF="doc/beta-intro/Quick-Reference-Card.html">BETA Quick Reference Card</A>
<LI><A HREF="BETAbookExamples/BETAbookExamples.html">The code fragments from the BETA book</A>
</UL>

<H2><A NAME="teaching">Teaching Experiences</A></H2>

<UL>
<LI><A HREF="Teaching/aarhus.html">Teaching BETA at Aarhus University, Denmark</A>
</UL>

<H2><A NAME="papers">Papers</A></H2>

This section contains links to papers on different aspects of BETA, 
as well as a preliminary reference list.

<UL>

<LI>Madsen:
&quot;<A HREF="Papers/BetaOverview/betaoverview.abstract.html">Overview of the BETA Programming Language</A>&quot;

<LI>Andersen et al.:
&quot;<A HREF="Papers/MBSoverview/mbsoverview.abstract.html">Overview of the Mj&oslash;lner BETA System</A>&quot;

<LI>Brandt: 
&quot;<A HREF="Papers/sbrandt/betamli.html">Reflection in a Statically Typed and Object Oriented Language - A Meta-Level Interface for BETA</A>&quot;

<LI>Brandt &amp; Madsen: 
&quot;<A HREF="Papers/OODP/oodp.abstract.html">Object-Oriented Distributed Programming in BETA</A>&quot;

<LI>Brandt &amp; Schmidt: 
&quot;<A HREF="Papers/sbrandt/meta95.html">The Design of a Meta-Level Architecture for the BETA Language</A>&quot;

<LI>Knudsen &amp; Middelfart: 
&quot;<A HREF="Papers/BETAconstraints/BETAconstraints.abstract.html">Supporting Constraints in BETA</A>&quot;

<LI>Madsen: 
&quot;<A HREF="Papers/Conc/concpaper.abstract.html">Building Abstractions for Concurrent Object-Oriented Programming</A>&quot;

<LI>Madsen &amp; M&oslash;ller-Pedersen: 
&quot;<A HREF="Papers/PartObjects/partobjects.abstract.html">Part Objects and Their Location</A>&quot;

<LI>Seligmann &amp; Grarup: 
&quot;<A HREF="Papers/Train/train.abstract.html">Incremental Mature Garbage Collection Using the Train Algorithm</A>&quot;

<P>

<LI><A HREF="Papers/References.html">BETA Reference List</A>

</UL>

<P><H2><A NAME="MBSatDaimi">The Mj&oslash;lner System at DAIMI</A></H2>

<UL>
<LI><A HREF="Daimi/index.html">The Mj&oslash;lner System at DAIMI</A>
</UL>

<P>

<H2><A NAME="ResearchProjects"></A>Research Projects</H2>

This section contains links to research projects on different aspects
of BETA.  This section is under construction, and you are invited to
contribute to this list by sending us your URL plus a 2-3 lines
description of your project.

<UL>

<LI><A HREF="http://www.daimi.au.dk/~kgronbak/DHM/DHMHome.html" TARGET="_top">DEVISE
Hypermedia</A>: DEVISE Hypermedia covers a hypermedia development
framework plus a number of applications for different platforms. DHM
is developed within the DEVISE project at the Computer Science
Department, Aarhus University, Denmark.

<LI><A HREF="Mli/mli.html">The MetaBETA
Project</A>: The aim of the MetaBETA project is to design and
implement a meta-level interface for the statically typed and compiled
language BETA.

</UL>

<H2>Related Information</H2>
For more information on object-oriented technology, 
take a look at:
<UL>
<LI><A HREF="http://iamwww.unibe.ch/~scg/OOinfo/FAQ" TARGET="_top">The Object-Orientation FAQ</A>
<LI><A HREF="http://iamwww.unibe.ch/cgi-bin/ooinfo" TARGET="_top">The Object-Oriented Information Sources</A>
<LI><A HREF="http://www.daimi.au.dk/index.html" TARGET="_top">The DAIMI Home Page</A>
</UL>

<P><H2><A NAME="commentary">Commentary</A></H2>
In order to make the BETA Home Page as useful as 
possible, we would like to hear 
<A HREF="forms/commentary.html">your opinion</A>.

</BODY>
</HTML>

