.TH betafs 1 "June-20-1996" "MBS r4.0" "Mjolner Informatics" 
.\"  Copyright (c) 1996 Mjolner Informatics
.de BP
.sp
.ti \-.2i
\(**
..

.SH NAME
betafs \- Mjolner BETA Fragment Structure Lister
.SH SYNOPSIS
.hy 0
.na
.B betafs
.RB "[\|" \-\-all "\|]"
.RB "[\|" \-\-special "\|]"
.RB "[\|" \-t targetMachine "\|]"
.IR file ...
.ad b
.hy 1
.PP
.SH AVAILABILITY
The Mjolner BETA Fragment Structure Lister is available as part of the Mjolner
BETA System from Mjolner Informatics.
.PP
.SH DESCRIPTION
.I Betafs
is a small utility for printing out the entire dependency graph (in
textual format) of a fragment file.  Is usefull for documentation
purposes, and for identifuing possible version problems in the
dependency graph.

.SH OPTIONS

.TP
.B \-\-all
all properties including internal ones are shown. This option may
show properties with a binary value
.PD 0
.TP
.B \-\-special
show special compiler options such as: 
donecheck, slots and unique_group_id
.PD 0
.TP
.BI "\-t " targetMachine
where 
targetMachine
may be: 
sun4s, linux, nti, hpux9pa, sgi, ppcmac, etc.
The fragments structure for this target machine is shown

.PP
.SH ENVIRONMENT
.I betafs
recognizes the environment variable $BETALIB. Please note
that this variable is given default value in the Bourne Shell
script 
.I $BETALIB/configuration/r4.0/env.sh
.TP
.B BETALIB
Specifies where 
.I ~beta
is located.  If not set,
.I beta
is assumed to be a username, and 
.I ~beta
being the home directory of that user.  Is used by many tools in the Mjolner
BETA System.

.PP
.SH SEE ALSO
.I beta(1)
- BETA Compiler
.br
.sp
.I valhalla(1)
- Mjolner BETA Source-Level Debugger
.br
.sp
.I betatar(1)
- BETA tar(1) front-end
.br
.sp
.I betawc(1)
- BETA fragment analyzer

.PP
.SH AUTHORS
Betafs is developed by Mjolner Informatics as part of the Mjolner BETA
System.

Questions, bug-reports, etc. may be directed to support@mjolner.dk if the
local support organization cannot find solutions to the problems.

For more information of the Mjolner BETA System, please contact
Mjolner Informatics, Science Park Aarhus, Gustav Wieds Vej 10, DK-8000
Aarhus C, Denmark, phone: +45 86 20 20 00, fax: +45 86 20 12 22,
e-mail: info@mjolner.dk.
