OK.
ninetynine bottles of beer on the wall, ninetynine bottles of beer.
Take one down, pass it around, ninetyeight bottles of beer on the wall.

ninetyeight bottles of beer on the wall, ninetyeight bottles of beer.
Take one down, pass it around, ninetyseven bottles of beer on the wall.

ninetyseven bottles of beer on the wall, ninetyseven bottles of beer.
Take one down, pass it around, ninetysix bottles of beer on the wall.

ninetysix bottles of beer on the wall, ninetysix bottles of beer.
Take one down, pass it around, ninetyfive bottles of beer on the wall.

ninetyfive bottles of beer on the wall, ninetyfive bottles of beer.
Take one down, pass it around, ninetyfour bottles of beer on the wall.

ninetyfour bottles of beer on the wall, ninetyfour bottles of beer.
Take one down, pass it around, ninetythree bottles of beer on the wall.

ninetythree bottles of beer on the wall, ninetythree bottles of beer.
Take one down, pass it around, ninetytwo bottles of beer on the wall.

ninetytwo bottles of beer on the wall, ninetytwo bottles of beer.
Take one down, pass it around, ninetyone bottles of beer on the wall.

ninetyone bottles of beer on the wall, ninetyone bottles of beer.
Take one down, pass it around, ninety bottles of beer on the wall.

ninety bottles of beer on the wall, ninety bottles of beer.
Take one down, pass it around, eightynine bottles of beer on the wall.

eightynine bottles of beer on the wall, eightynine bottles of beer.
Take one down, pass it around, eightyeight bottles of beer on the wall.

eightyeight bottles of beer on the wall, eightyeight bottles of beer.
Take one down, pass it around, eightyseven bottles of beer on the wall.

eightyseven bottles of beer on the wall, eightyseven bottles of beer.
Take one down, pass it around, eightysix bottles of beer on the wall.

eightysix bottles of beer on the wall, eightysix bottles of beer.
Take one down, pass it around, eightyfive bottles of beer on the wall.

eightyfive bottles of beer on the wall, eightyfive bottles of beer.
Take one down, pass it around, eightyfour bottles of beer on the wall.

eightyfour bottles of beer on the wall, eightyfour bottles of beer.
Take one down, pass it around, eightythree bottles of beer on the wall.

eightythree bottles of beer on the wall, eightythree bottles of beer.
Take one down, pass it around, eightytwo bottles of beer on the wall.

eightytwo bottles of beer on the wall, eightytwo bottles of beer.
Take one down, pass it around, eightyone bottles of beer on the wall.

eightyone bottles of beer on the wall, eightyone bottles of beer.
Take one down, pass it around, eighty bottles of beer on the wall.

eighty bottles of beer on the wall, eighty bottles of beer.
Take one down, pass it around, seventynine bottles of beer on the wall.

seventynine bottles of beer on the wall, seventynine bottles of beer.
Take one down, pass it around, seventyeight bottles of beer on the wall.

seventyeight bottles of beer on the wall, seventyeight bottles of beer.
Take one down, pass it around, seventyseven bottles of beer on the wall.

seventyseven bottles of beer on the wall, seventyseven bottles of beer.
Take one down, pass it around, seventysix bottles of beer on the wall.

seventysix bottles of beer on the wall, seventysix bottles of beer.
Take one down, pass it around, seventyfive bottles of beer on the wall.

seventyfive bottles of beer on the wall, seventyfive bottles of beer.
Take one down, pass it around, seventyfour bottles of beer on the wall.

seventyfour bottles of beer on the wall, seventyfour bottles of beer.
Take one down, pass it around, seventythree bottles of beer on the wall.

seventythree bottles of beer on the wall, seventythree bottles of beer.
Take one down, pass it around, seventytwo bottles of beer on the wall.

seventytwo bottles of beer on the wall, seventytwo bottles of beer.
Take one down, pass it around, seventyone bottles of beer on the wall.

seventyone bottles of beer on the wall, seventyone bottles of beer.
Take one down, pass it around, seventy bottles of beer on the wall.

seventy bottles of beer on the wall, seventy bottles of beer.
Take one down, pass it around, sixtynine bottles of beer on the wall.

sixtynine bottles of beer on the wall, sixtynine bottles of beer.
Take one down, pass it around, sixtyeight bottles of beer on the wall.

sixtyeight bottles of beer on the wall, sixtyeight bottles of beer.
Take one down, pass it around, sixtyseven bottles of beer on the wall.

sixtyseven bottles of beer on the wall, sixtyseven bottles of beer.
Take one down, pass it around, sixtysix bottles of beer on the wall.

sixtysix bottles of beer on the wall, sixtysix bottles of beer.
Take one down, pass it around, sixtyfive bottles of beer on the wall.

sixtyfive bottles of beer on the wall, sixtyfive bottles of beer.
Take one down, pass it around, sixtyfour bottles of beer on the wall.

sixtyfour bottles of beer on the wall, sixtyfour bottles of beer.
Take one down, pass it around, sixtythree bottles of beer on the wall.

sixtythree bottles of beer on the wall, sixtythree bottles of beer.
Take one down, pass it around, sixtytwo bottles of beer on the wall.

sixtytwo bottles of beer on the wall, sixtytwo bottles of beer.
Take one down, pass it around, sixtyone bottles of beer on the wall.

sixtyone bottles of beer on the wall, sixtyone bottles of beer.
Take one down, pass it around, sixty bottles of beer on the wall.

sixty bottles of beer on the wall, sixty bottles of beer.
Take one down, pass it around, fiftynine bottles of beer on the wall.

fiftynine bottles of beer on the wall, fiftynine bottles of beer.
Take one down, pass it around, fiftyeight bottles of beer on the wall.

fiftyeight bottles of beer on the wall, fiftyeight bottles of beer.
Take one down, pass it around, fiftyseven bottles of beer on the wall.

fiftyseven bottles of beer on the wall, fiftyseven bottles of beer.
Take one down, pass it around, fiftysix bottles of beer on the wall.

fiftysix bottles of beer on the wall, fiftysix bottles of beer.
Take one down, pass it around, fiftyfive bottles of beer on the wall.

fiftyfive bottles of beer on the wall, fiftyfive bottles of beer.
Take one down, pass it around, fiftyfour bottles of beer on the wall.

fiftyfour bottles of beer on the wall, fiftyfour bottles of beer.
Take one down, pass it around, fiftythree bottles of beer on the wall.

fiftythree bottles of beer on the wall, fiftythree bottles of beer.
Take one down, pass it around, fiftytwo bottles of beer on the wall.

fiftytwo bottles of beer on the wall, fiftytwo bottles of beer.
Take one down, pass it around, fiftyone bottles of beer on the wall.

fiftyone bottles of beer on the wall, fiftyone bottles of beer.
Take one down, pass it around, fifty bottles of beer on the wall.

fifty bottles of beer on the wall, fifty bottles of beer.
Take one down, pass it around, fourtynine bottles of beer on the wall.

fourtynine bottles of beer on the wall, fourtynine bottles of beer.
Take one down, pass it around, fourtyeight bottles of beer on the wall.

fourtyeight bottles of beer on the wall, fourtyeight bottles of beer.
Take one down, pass it around, fourtyseven bottles of beer on the wall.

fourtyseven bottles of beer on the wall, fourtyseven bottles of beer.
Take one down, pass it around, fourtysix bottles of beer on the wall.

fourtysix bottles of beer on the wall, fourtysix bottles of beer.
Take one down, pass it around, fourtyfive bottles of beer on the wall.

fourtyfive bottles of beer on the wall, fourtyfive bottles of beer.
Take one down, pass it around, fourtyfour bottles of beer on the wall.

fourtyfour bottles of beer on the wall, fourtyfour bottles of beer.
Take one down, pass it around, fourtythree bottles of beer on the wall.

fourtythree bottles of beer on the wall, fourtythree bottles of beer.
Take one down, pass it around, fourtytwo bottles of beer on the wall.

fourtytwo bottles of beer on the wall, fourtytwo bottles of beer.
Take one down, pass it around, fourtyone bottles of beer on the wall.

fourtyone bottles of beer on the wall, fourtyone bottles of beer.
Take one down, pass it around, fourty bottles of beer on the wall.

fourty bottles of beer on the wall, fourty bottles of beer.
Take one down, pass it around, thirtynine bottles of beer on the wall.

thirtynine bottles of beer on the wall, thirtynine bottles of beer.
Take one down, pass it around, thirtyeight bottles of beer on the wall.

thirtyeight bottles of beer on the wall, thirtyeight bottles of beer.
Take one down, pass it around, thirtyseven bottles of beer on the wall.

thirtyseven bottles of beer on the wall, thirtyseven bottles of beer.
Take one down, pass it around, thirtysix bottles of beer on the wall.

thirtysix bottles of beer on the wall, thirtysix bottles of beer.
Take one down, pass it around, thirtyfive bottles of beer on the wall.

thirtyfive bottles of beer on the wall, thirtyfive bottles of beer.
Take one down, pass it around, thirtyfour bottles of beer on the wall.

thirtyfour bottles of beer on the wall, thirtyfour bottles of beer.
Take one down, pass it around, thirtythree bottles of beer on the wall.

thirtythree bottles of beer on the wall, thirtythree bottles of beer.
Take one down, pass it around, thirtytwo bottles of beer on the wall.

thirtytwo bottles of beer on the wall, thirtytwo bottles of beer.
Take one down, pass it around, thirtyone bottles of beer on the wall.

thirtyone bottles of beer on the wall, thirtyone bottles of beer.
Take one down, pass it around, thirty bottles of beer on the wall.

thirty bottles of beer on the wall, thirty bottles of beer.
Take one down, pass it around, twentynine bottles of beer on the wall.

twentynine bottles of beer on the wall, twentynine bottles of beer.
Take one down, pass it around, twentyeight bottles of beer on the wall.

twentyeight bottles of beer on the wall, twentyeight bottles of beer.
Take one down, pass it around, twentyseven bottles of beer on the wall.

twentyseven bottles of beer on the wall, twentyseven bottles of beer.
Take one down, pass it around, twentysix bottles of beer on the wall.

twentysix bottles of beer on the wall, twentysix bottles of beer.
Take one down, pass it around, twentyfive bottles of beer on the wall.

twentyfive bottles of beer on the wall, twentyfive bottles of beer.
Take one down, pass it around, twentyfour bottles of beer on the wall.

twentyfour bottles of beer on the wall, twentyfour bottles of beer.
Take one down, pass it around, twentythree bottles of beer on the wall.

twentythree bottles of beer on the wall, twentythree bottles of beer.
Take one down, pass it around, twentytwo bottles of beer on the wall.

twentytwo bottles of beer on the wall, twentytwo bottles of beer.
Take one down, pass it around, twentyone bottles of beer on the wall.

twentyone bottles of beer on the wall, twentyone bottles of beer.
Take one down, pass it around, twenty bottles of beer on the wall.

twenty bottles of beer on the wall, twenty bottles of beer.
Take one down, pass it around, nineteen bottles of beer on the wall.

nineteen bottles of beer on the wall, nineteen bottles of beer.
Take one down, pass it around, eighteen bottles of beer on the wall.

eighteen bottles of beer on the wall, eighteen bottles of beer.
Take one down, pass it around, seventeen bottles of beer on the wall.

seventeen bottles of beer on the wall, seventeen bottles of beer.
Take one down, pass it around, sixteen bottles of beer on the wall.

sixteen bottles of beer on the wall, sixteen bottles of beer.
Take one down, pass it around, fifteen bottles of beer on the wall.

fifteen bottles of beer on the wall, fifteen bottles of beer.
Take one down, pass it around, fourteen bottles of beer on the wall.

fourteen bottles of beer on the wall, fourteen bottles of beer.
Take one down, pass it around, thirteen bottles of beer on the wall.

thirteen bottles of beer on the wall, thirteen bottles of beer.
Take one down, pass it around, twelve bottles of beer on the wall.

twelve bottles of beer on the wall, twelve bottles of beer.
Take one down, pass it around, eleven bottles of beer on the wall.

eleven bottles of beer on the wall, eleven bottles of beer.
Take one down, pass it around, ten bottles of beer on the wall.

ten bottles of beer on the wall, ten bottles of beer.
Take one down, pass it around, nine bottles of beer on the wall.

nine bottles of beer on the wall, nine bottles of beer.
Take one down, pass it around, eight bottles of beer on the wall.

eight bottles of beer on the wall, eight bottles of beer.
Take one down, pass it around, seven bottles of beer on the wall.

seven bottles of beer on the wall, seven bottles of beer.
Take one down, pass it around, six bottles of beer on the wall.

six bottles of beer on the wall, six bottles of beer.
Take one down, pass it around, five bottles of beer on the wall.

five bottles of beer on the wall, five bottles of beer.
Take one down, pass it around, four bottles of beer on the wall.

four bottles of beer on the wall, four bottles of beer.
Take one down, pass it around, three bottles of beer on the wall.

three bottles of beer on the wall, three bottles of beer.
Take one down, pass it around, two bottles of beer on the wall.

two bottles of beer on the wall, two bottles of beer.
Take one down, pass it around, one bottle of beer on the wall.

one bottle of beer on the wall, one bottle of beer.
Take one down, pass it around, no more bottles of beer on the wall.


