OK.
.
ArithOp   : abcdefghijklmnopqrstuvwxyz0123456789.
ArithOp   : abcdefghijklmnopqrstuvwxyz0123456789.
ArithOp   : abcdefghijklmnopqrstuvwxyz0123456789.
Multiply  : abcdefghijklmnopqrstuvwxyz0123456789.
Multiply  : abcdefghijklmnopqrstuvwxyz0123456789.
Divide    : abcdefghijklmnopqrstuvwxyz0123456789.
Divide    : abcdefghijklmnopqrstuvwxyz0123456789.
Divide    : abcdefghijklmnopqrstuvwxyz0123456789.
RelOp     : abcdefghijklmnopqrstuvwxyz0123456789.
BoolOp    : abcdefghijklmnopqrstuvwxyz0123456789.
Repetition: abcdefghijklmnopqrstuvwxyz0123456789.
Repetition: abcdefghijklmnopqrstuvwxyz0123456789.
Repetition: abcdefghijklmnopqrstuvwxyz0123456789.
Ref. rep  : abcdefghijklmnopqrstuvwxyz0123456789.
Ref. rep2 : abcdefghijklmnopqrstuvwxyz0123456789.
Ref. rep3 : abcdefghijklmnopqrstuvwxyz0123456789.
Block     : abcdefghijklmnopqrstuvwxyz0123456789.
Break     : abcdefghijklmnopqrstuvwxyz0123456789.
Break2    : ## (BreakComponent/BreakCallback) ##.
Virtual   : abcdefghijklmnopqrstuvwxyz0123456789.
Virtual1b : abcdefghijklmnopqrstuvwxyz0123456789.
Virtual2  : abcdefghijklmnopqrstuvwxyz0123456789.
Virtual2b : abcdefghijklmnopqrstuvwxyz0123456789.
tstref    : abcdefghijklmnopqrstuvwxyz0123456789.
int8      : abcdefghijklmnopqrstuvwxyz0123456789.
if        : abcdefghijklmnopqrstuvwxyz0123456789.
for       : abcdefghijklmnopqrstuvwxyz0123456789.
case      : abcdefghijklmnopqrstuvwxyz0123456789.
dopart    : abcdefghijklmnopqrstuvwxyz0123456789.
tstnx     : abcdefghijklmnopqrstuvwxyz0123456789.
tstnx     : abcdefghijklmnopqrstuvwxyz0123456789.
tstnx2    : abcdefghijklmnopqrstuvwxyz0123456789.
tstnx3    : abcdefghijklmnopqrstuvwxyz0123456789.
NXoff     : abcdefghijklmnopqrstuvwxyz0123456789.
NXoff1    : abcdefghijklmnopqrstuvwxyz0123456789.
NXoff2    : abcdefghijklmnopqrstuvwxyz0123456789.
NXoff3    : abcdefghijklmnopqrstuvwxyz0123456789.
This      : abcdefghijklmnopqrstuvwxyz0123456789.
Comprem   : abcdefghijklmnopqrstuvwxyz0123456789.
Comprem2  : abcdefghijklmnopqrstuvwxyz0123456789.
BigObject : abcdefghijklmnopqrstuvwxyz0123456789.
Oldprim   : ################qrstuvw#############.
Newprim   : abcdefghijklmnopqrstuvwxyz###3456###.
NewPrim2  : ############mnopqrstuvw###0123####89.
NewPrim4  : abcd##ghijklmnopqrstuvwxyz0123456789.
Real      : abcdefghijklmnopqrstuvwxyz0123456789.
Real2     : abcdefghijklmnopqrstuvwxyz0123456789.
Real3     : abcdefghijklmnopqrstuvwxyz0123456789.
Real4     : abcdefghijklmnopqrstuvwxyz0123456789.
MainPart  : abcdefghijklmnopqrstuvwxyz0123456789.
MainPart  : abcdefghijklmnopqrstuvwxyz0123456789.
VarPtn    : abcdefghijklmnopqrstuvwxyz0123456789.
LVRA      : abcdefghijklmnopqrstuvwxyz0123456789.
list2rep  : abcdefghijklmnopqrstuvwxyz0123456789.
List2rep2 : abcdefghijklmnopqrstuvwxyz0123456789.
List2rep3 : abcdefghijklmnopqrstuvwxyz0123456789.
Component : abcdefghijklmnopqrstuvwxyz0123456789
