OK.
.
ArithOp   : abcdefghijklmnopqrstuvwxyz0123456789.
ArithOp   : abcdefghijklmnopqrstuvwxyz0123456789.
ArithOp   : abcdefghijklmnopqrstuvwxyz0123456789.
Multiply  : abcdefghijklmnopqrstuvwxyz0123456789.
Multiply  : abcdefghijklmnopqrstuvwxyz0123456789.
Divide    : abcdefghijklmnopqrstuvwxyz0123456789.
Divide    : abcdefghijklmnopqrstuvwxyz0123456789.
Divide    : abcdefghijklmnopqrstuvwxyz0123456789.
RelOp     : abcdefghijklmnopqrstuvwxyz0123456789.
BoolOp    : abcdefghijklmnopqrstuvwxyz0123456789.
Repetition: abcdefghijklmnopqrstuvwxyz0123456789.
Repetition: abcdefghijklmnopqrst############6789.
Ref. rep  : abcdefghijklmnopqrstuvwxyz0123456789.
Ref. rep2 : abcdefghij################0123456789.
Block     : abcdefghijklmnopqrstuvwxyz0123456789.
Break     : abcdefghijklmnopqrstuvwxyz0123456789.
Break2    : ## (BreakComponent/BreakCallback) ##.
Virtual   : abcdefghijklmnopqrstuvwxyz0123456789.
Virtual1b : abcdef##ijklmnopqrstuvwxyz0123456789.
Virtual2  : abcdefghijklmnopqrstuvwxyz#123456789.
Virtual2b : abcdefghijklmnopqrstu#####0123456789.
tstref    : abcdefghijklmnopqrstuvwxyz012345678#.
int8      : abc#efghijklmnopqrstuvwxyz0123456789.
if        : abcdefghijklmnopqrstuvwxyz0123456789.
for       : abcdefghijklmnopqrstuvwxyz0123456789.
case      : abcdefghijklmnopqrstuvwxyz0123456789.
dopart    : abcdefghijklmnopqrstuvwxyz0123456789.
tstnx     : abcdefghijklmnopqrstuvwxyz0123456789.
tstnx     : abcdefghijklmnopqrstuvwxyz0123456789.
tstnx2    : abcdefghijklmnopqrstuvwxyz0123456789.
tstnx3    : abcde#ghijklmnopqrstuvwxyz0123456789.
NXoff     : abcdefghijklmnopqrstuvwxy#########89.
NXoff1    : abcdefghijklmnopqrstu###########6###.
NXoff2    : abcde###############################.
NXoff3    : abc#efghijklmnopqrstuvwxyz0123456789.
This      : abcdefghijklmnopqrs#######0123456789.
Compref   : abcdefghijklmno#####uvwxyz0123456789.
Comprem2  : abc#efghijklmnopqrstuvwxyz0123456789.
BigObject : abcdefghijklmnopqrstuvwxyz0123456789.
Oldprim   : ################qrstuvw#############.
Newprim   : ################qrstuvw###########89.
NewPrim4  : abcd##ghijklmnopqrstuvwxyz0123456789.
Real      : abcdefghijklmnopqrstuvwxyz0123456789.
Real2     : abcdefghijklmnopqrstuvwxyz0123456789.
Real3     : abcdefghi#klmnopqrstuvwxyz0123456789.
Real4     : abcdefgh#jklmnopqrstuvwxyz0123456789.
MainPart  : abcdefghijklmnopqrstuvwxyz0123456789.
MainPart  : abcdefghijklmnopqrstuvwxyz0123456789.
VarPtn    : abcde###ijklmnopqrstuvwxyz012345###9.
LVRA      : abc#######klmnopqrstuvwxyz0123456789
