rm -rf jvm *.a2s *.ast *.astL *~ *.out *.run
mkdir jvm
javac -classpath jvm -d jvm IDocument.java
javac -classpath jvm -d jvm DefaultAutoIndentStrategy.java
javac -classpath jvm -d jvm DocumentCommand.java
javac -classpath jvm -d jvm Screen.java
jbeta -qw -s 188 --mute BetaAutoIndentStrategy.bet
Parsing: 'C:\beta\r5.4\compiler\GENERATOR\BYTECODE\TEST\ECLIPSE\BetaAutoIndentStrategy.bet'
Parsing: 'C:\beta\r5.4\compiler\GENERATOR\BYTECODE\TEST\ECLIPSE\eclipseStuff.bet'
Creating library JAR file
Library JAR file on file: ~beta/compiler/GENERATOR/BYTECODE/TEST/ECLIPSE/jvm/BetaAutoIndentStrategy.jar
javac -classpath jvm -d jvm Eclipse.java
java -classpath "jvm/BetaAutoIndentStrategy.jar;jvm" Eclipse
Eclipse Screen.Putline
Eclipse: creating BetaAutoIndentStrategy.
Eclipse: calling customizeDocumentCommand.
customizeDocumentCommand: BETA putline!
insert: IDocumentImpl
Eclipse: done.
