rm -rf jvm *.a2s *.ast *.astL *~ *.out *.run
mkdir jvm
javac -classpath jvm -d jvm IDocument.java
javac -classpath jvm -d jvm DefaultAutoIndentStrategy.java
javac -classpath jvm -d jvm DocumentCommand.java
javac -classpath jvm -d jvm Screen.java
jbeta --mute -qw -s 188 BETALIB
betacc: compiling for target sun4s
betacc: /usr/local/bin/gcc  -g -I. -Ijvm -I/home/java/Solaris/include -I/home/java/Solaris/include/solaris -Dsun4s -fpic -shared -O6 -o jvm/sun4s/libBetaHelpers.so BetaHelpers.c
Creating library JAR file
Library JAR file on file: jvm/BETALIB.jar
jbeta --mute -qw -s 188 BetaAutoIndentStrategy.bet
Creating library JAR file
Library JAR file on file: jvm/BetaAutoIndentStrategy.jar
javac -classpath jvm -d jvm Eclipse.java
java -classpath "jvm/BETALIB.jar:jvm" Eclipse
Eclipse Screen.Putline
Eclipse: creating BetaAutoIndentStrategy.
Eclipse: calling customizeDocumentCommand.
customizeDocumentCommand: BETA putline!
insert: dummy
Eclipse: done.
