Search term for Google: Results for Google search: Ole Lehrmann Madsen BETA.NET

URL: http://www.pervasive.dk/projects/langInter/langInter_summary.htm
Snippet:
  <b>...</b> <b>BETA</b>.<b>NET</b> ? porting the BETA language to the .NET-platform; BETA.Java ? porting<br> the BETA language to the Java <b>...</b> People: <b>Ole</b> <b>Lehrmann</b> <b>Madsen</b> - olm <b>...</b>  

URL: http://www.au.dk/da/nat/datalogi/fsk2001.htm
Snippet:
  <b>...</b> <b>BETA</b>.<b>NET</b> - Porting the BETA Language to the NET-platform. DAIMI responsible:<br> <b>Ole</b> <b>Lehrmann</b> <b>Madsen</b>, Peter Andersen, Henry Michael Lassen. <b>...</b>  

URL: http://www.daimi.au.dk/doc73.html
Snippet:
  <b>...</b> <b>BETA</b>.<b>NET</b> - Porting the BETA Language to the .NET-platform. DAIMI responsible:<br> <b>Ole</b> <b>Lehrmann</b> <b>Madsen</b>, Peter Andersen, Henry Michael Lassen External partners <b>...</b>  

URL: http://www.ecoop2002.lcc.uma.es/ecoop2002-programme.pdf
Snippet:
 Page 1. ECOOP 2002 1 Welcome! It is our pleasure to welcome you to ECOOP<br> 2002, the 16th European Conference on Object-Oriented Programming. <b>...</b>  
