Search term for Google: Results for Google search: Ole Lehrmann Madsen BETA.NET

URL: http://www.pervasive.dk/projects/langInter/langInter_summary.htm
Snippet:
  ... activities of the project are the following subprojects: BETA.NET - porting the ... People:
 Ole Lehrmann Madsen - olm@daimi.au.dk; Peter Andersen - datpete@daimi.au ...  

URL: http://www.au.dk/da/nat/datalogi/fsk2001.htm
Snippet:
  ... BETA.NET - Porting the BETA Language to the NET-platform. DAIMI responsible:
 Ole Lehrmann Madsen, Peter Andersen, Henry Michael Lassen. ...  

URL: http://www.daimi.au.dk/doc73.html
Snippet:
  ... BETA.NET - Porting the BETA Language to the .NET-platform. DAIMI responsible:
 Ole Lehrmann Madsen, Peter Andersen, Henry Michael Lassen External partners ...  

URL: http://www.daimi.au.dk/~falk/speciale/speciale.pdf
Snippet:
  ... Service Technology Implementing Distributed systems, using Web Service Technology
 Kim Falk J›gensen, falk@daimi.au.dk advisor Ole Lehrmann Madsen, olm@daimi.au ...  

URL: http://www.ecoop2002.lcc.uma.es/ecoop2002-programme.pdf
Snippet:
 Page 1. ECOOP 2002 1 Welcome! It is our pleasure to welcome you to ECOOP
 2002, the 16th European Conference on Object-Oriented Programming. ...  
