Search term for Google: Results for Google search: Ole Lehrmann Madsen BETA.NET

URL: http://www.pervasive.dk/projects/langInter/langInter_summary.htm
Snippet:
  <b>...</b> <b>BETA</b>.<b>NET</b> – porting the BETA language to the .NET-platform; BETA.Java – porting <b>...</b> <b>Ole</b><br> <b>Lehrmann</b> <b>Madsen</b> - olm@daimi.au.dk; Peter Andersen - datpete@daimi.au.dk; <b>...</b>  

URL: http://www.daimi.au.dk/research/projects-external-funding.php
Snippet:
  <b>...</b> <b>BETA</b>.<b>NET</b> - Porting the BETA Language to the .NET-platform DAIMI responsible.<br> <b>Ole</b> <b>Lehrmann</b> <b>Madsen</b>, Peter Andersen, Henry Michael Lassen. External partners. <b>...</b>  

URL: http://www.daimi.au.dk/~beta/ooli/MS-Rotor-Presentation-Day-2004-06-16/BETA-ROTOR-Cambridge-2004-06-16.pps
Snippet:
  <b>...</b> 2004-06-16. Implementation of Components in <b>BETA</b>.<b>Net</b>. Any pattern in BETA may<br> be used as a coroutine. <b>...</b> <b>Ole</b> <b>Lehrmann</b> <b>Madsen</b>. mailto:olm@daimi.au.dk. Download: <b>...</b>  

URL: http://www.ecoop2002.lcc.uma.es/ecoop2002-programme.pdf
Snippet:
 Page 1. ECOOP 2002 1 Welcome! It is our pleasure to welcome you to ECOOP<br> 2002, the 16th European Conference on Object-Oriented Programming. <b>...</b>  
