Search term for Google: Results for Google search: Ole Lehrmann Madsen BETA.NET

URL: http://www.pervasive.dk/projects/langInter/langInter_summary.htm
Snippet:
  <b>...</b> <b>BETA</b>.<b>NET</b> ? porting the BETA language to the .NET-platform; BETA.Java ? porting <b>...</b> <b>Ole</b><br> <b>Lehrmann</b> <b>Madsen</b> - olm@daimi.au.dk; Peter Andersen - datpete@daimi.au.dk; <b>...</b>  

URL: http://www.au.dk/da/nat/datalogi/fsk2002.htm
Snippet:
  <b>...</b> <b>BETA</b>.<b>NET</b> - Porting the BETA Language to the .NET-platform. DAIMI responsible:<br> <b>Ole</b> <b>Lehrmann</b> <b>Madsen</b>, Peter Andersen, Henry Michael Lassen. <b>...</b>  

URL: http://ecoop2002.lcc.uma.es/ecoop2002-programme.pdf
Snippet:
 Page 1. ECOOP 2002 1 Welcome! It is our pleasure to welcome you to ECOOP<br> 2002, the 16th European Conference on Object-Oriented Programming. <b>...</b>  
