// Deep_Thought.idl : IDL source for Deep_Thought.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (Deep_Thought.tlb) and marshalling code.
//
// File created by Kristian Lippert, DTI, 980205
// for Phase 5, COT Case 3: Pilot Application
// The GUIDS for the interfaces as in phase 2, 3, and 4:
// ICalc :  6FB6D32F-9E06-11D1-AE78-0020AF72F3D6
// ICalc2:  08407980-9e15-11d1-ae78-0020af72f3d6
// IConv :  ed297100-9e0b-11d1-ae78-0020af72f3d6


import "oaidl.idl";
import "ocidl.idl";

	[
		uuid(6FB6D32F-9E06-11D1-AE78-0020AF72F3D6),
		helpstring("ICalc Interface"),
		pointer_default(unique)
	]
	interface ICalc : IUnknown
	{
		[helpstring("method Add")] HRESULT Add([in] long v1, [in] long v2, [out, retval] long* res);
		[helpstring("method Subtract")] HRESULT Subtract([in] long v1, [in] long v2, [out, retval] long* res);
		[helpstring("method Multiply")] HRESULT Multiply([in] long v1, [in] long v2, [out, retval] long* res);
		[helpstring("method Divide")] HRESULT Divide([in] long v1, [in] long v2, [out, retval] long* res);
		[helpstring("method Modulus")] HRESULT Modulus([in] long v1, [in] long v2, [out, retval] long* res);
	};
	[
		uuid(08407980-9e15-11d1-ae78-0020af72f3d6),
		helpstring("ICalc2 Interface"),
		pointer_default(unique)
	]
	interface ICalc2 : IUnknown
	{
		[helpstring("method Power")] HRESULT Power([in] long v, [out, retval] long* res);
	};

	[
		uuid(ed297100-9e0b-11d1-ae78-0020af72f3d6),
		helpstring("IConv Interface"),
		pointer_default(unique)
	]
	interface IConv : IUnknown
	{
		[helpstring("method Hex2Dec")] HRESULT Hex2Dec([in] BSTR v, [out,retval] long *res);
		[helpstring("method Dec2Hex")] HRESULT Dec2Hex([in] long v, [out,retval] BSTR *res);
	};


[
	uuid(6FB6D322-9E06-11D1-AE78-0020AF72F3D6),
	version(1.0),
	helpstring("Deep_Thought 1.0 Type Library")
]
library DEEP_THOUGHTLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[
		uuid(97723080-9e15-11d1-ae78-0020af72f3d6),
		helpstring("CalcAggr Class")
	]
	coclass Calc
	{
		[default] interface ICalc;
		interface ICalc2;
	};
	[
		uuid(FC9BFDE3-9E0D-11D1-AE78-0020AF72F3D6),
		helpstring("Conv Class")
	]
	coclass Conv
	{
		[default] interface IConv;
	};
};
