#!/bin/sh

#--------- Configuration: ------

# Directories containing source files:
SRC="${BETALIB}/guienv"

# Files to include in interface. The order given here will
# be the order they appear in in the generated interface.
FILES="\
openGL/glenv.bet \
openGL/openGL.bet \
openGL/openGLBlib.bet \
openGL/openGLUlib.bet \
openGL/openGLWlib.bet \
openGL/openGLXlib.bet \
openGL/openGLlib.bet \
"

MAKEINT=../../bin/beta2int.perl
MAKEHTML=../../bin/int2html.perl

. ../../bin/makeHTML.sh
