#!/bin/sh

#--------- Configuration: ------

# Directories containing source files:
SRC="${BETALIB}/process"

# Files to include in interface. The order given here will
# be the order they appear in in the generated interface.
FILES="\
commaddress.bet \
errorcallback.bet \
basicsocket.bet \
binarysocket.bet \
streamsocket.bet \
socketgenerator.bet \
binarygenerator.bet \
streamgenerator.bet \
commpool.bet \
systemcomm.bet \
processmanager.bet \
commpipe.bet \
"

MAKEINT=../../bin/beta2int.perl
#MAKEHTML=../../bin/int2html.perl
MAKEHTML=../../bin/int2frames.perl

. ../../bin/makeHTML.sh
