java:
	javac helloworld.java
	java HelloWorld

beta:
	beta writehelloworld
	./writehelloworld
	java HelloWorld

clean:
	/bin/rm -f *~ *.class core core.* writehelloworld *.a2s *.ast *.astL
	/bin/rm -rf sun4s linux nti_ms clr jvm
