#!/bin/sh

BETALIB=${BETALIB-/users/beta}
. $BETALIB/configuration/env.sh

case "$MACHINETYPE" in
	SGI)
		CC="cc -32"
		;;
	HPUX9PA)
		CC=gcc
		;;
	*)
		CC=cc
		;;
esac
export CC

echo make -f MACHINEmakefile
make -f MACHINEmakefile 
