#!/usr/local/bin/perl -s
$BETALIB=$ENV{'BETALIB'};
$BETALIB=~s%\\%/%g;
push(@INC, $ENV{'BETALIB'} . "/bin/admin");
if (-e "c:\\" && $ENV{'MIASDK'} eq ""){
    $ENV{'MIASDK'} = ms;
}
require "env.perl";

# -------------- Configuration-----------------------------------------

if ($OS eq "WIN"){
    $dest    = "C:/BETA_OOLI";
} else {
    $dest    = "BETA_OOLI";
}
$beta        = "$BETALIB/boot/bin/$objdir/beta";
$publish_dir = "Z:public_html/ooli";

@std_libs    = ("basiclib",
		"sysutils",
		"containers",
		"process",
		);

@examples    = (# output from testall -d -L
		"Aclass.bet",
		"Bmini0.bet",
		"Bmini1.bet",
		"Calculator.bet",
		"Counter.bet",
		"ECStest.bet",
		"ECtest.bet",
		"LL1.bet",
		"List.bet",
		"NumList.bet",
		"Ptn.bet",
		"Server.bet",
		"Singular.bet",
		"SuperFields.bet",
		"array.bet",
		"bconvert.bet",
		"beer.bet",
		"coerce.bet",
		"constructor.bet",
		"faclink.bet",
		"go.bet",
		"google.bet",
		"googlesnip.bet",
		"googlesnipre.bet",
		"hello.bet",
		"multiple.bet",
		"nstring.bet",
		"real32.bet",
		"small.bet",
		"stackuser.bet",

		# hello implementation
		"hellolib.bet",

		# stack implementation
		"stack.bet",
		"stackbody.bet",

		# google implementation
		"googlesearch.bet", 
		"google_*.bet", 
		"google*.exe.config",
		"googleapi/LICENSE.txt",
		"googleapi/googleapi.jar",
		"googleapi/dotnet/GoogleSearchService.cs",

		# clr specific stuff
		"hellobox.bet",
		"hellographics.bet",
		"nstringuser.cs",

		# java specific stuff
		"bpackage.bet",
		"bpackageuser.java",
		"jstringuser.java",
		"jstring.bet",
		"javastring.bet",
		"greetings.bet",
		"helloapplet.bet",
		"helloapplet.html",

		# External programs
		"EC.{cs,java}",
		"Bclass*.{bet,cs,config,java}",
		"xreal32class.{cs,java}",

		# Misc
		"GNUmakefile",
		"make_clean.bat",
		"cmd_setup.bat",
		
		);

@presentations = ( "JAOO-2002/OOLI.pdf",
		   "DAIMI-Posten-2003/OOLI-Daimiposten.pdf",
		   "ETX-2004-03-30/beta-eclipse-etx-2004.pdf",
		   "ETX-2004-03-30/ETX.pdf",
		   "ETX-2004-03-30/ETX.ppt",
		   "ETX-2004-03-30/Calculator.bet",
		  );

@cleanup = ( "configuration/mbs_id",
	     "configuration/ymer.pjt",
	     "configuration/env.*",
	     "examples/googleapi/dotnet/GoogleSearchService.dll",
	     "examples/googleapi/dotnet/GoogleSearchService.pdb",
	     );

# -------------- Main -------------------------------------------------


sub usage()
{
    local($msg) = @_;
    print "pack_dotnet: $msg\n" if ($msg ne "");
    print<<EOT;
usage: pack_release [-h][-v][-C][-z][-p]
     -h  print this help
     -v  verbose mode
     -C  skip compilation of compilers
     -Z  skip zipping of directory
     -D  skip deletion of existing BETA_OOLI directory
     -T  include testall and reference output
     -p  "publish" new zip file on web (copy to "$publish_dir")
EOT
    exit;
}

use File::Path;
use File::Copy;
use File::Find;

&usage() if ($h);

$skipdeletion = $D;
$skipcompilation = $C;
$skipzipping = $Z;
$publish = $p;

$|=1;

chdir ("..") || die "Cannot change directory to parent directory\n";

print "Creating BETA OOLI preliminary distribution in directory $dest\n";
 
if ( -d $dest && !$skipdeletion ){
   print "Deleting existing $dest\n";
   #&rmtree($dest, 0, 1);
   system "rm -rf $dest";
}

if ($skipcompilation){
    print "Skipping recompilation of compilers (-C option)\n";
} else {
    print "Recompiling compilers\n";
    $nbetasrc = "$BETALIB/compiler/nbeta.bet";
    $nbeta    = "$BETALIB/bin/$objdir/nbeta.exe";
    $jbetasrc = "$BETALIB/compiler/jbeta.bet";
    $jbeta    = "$BETALIB/bin/$objdir/jbeta.exe";
    print "Compiling nbeta\n";
    $cmd = "beta -qwd -o $nbeta $nbetasrc > nbetaboot.out";
    print "$cmd\n" if $verbose;
    system $cmd;
    print "Compiling jbeta\n";
    $cmd = "beta -qwd -o $jbeta $jbetasrc > jbetaboot.out";
    print "$cmd\n" if $verbose;
    system $cmd;
    print "Compiling managed nbeta\n";
    &pushd("$BETALIB/compiler");
    $cmd = "nbeta -s 328 -o managed-nbeta.exe nbeta > managed-nbetaboot.out";
    print "$cmd\n" if $verbose;
    system $cmd;
    &popd();
}

print "Creating directory $dest\n";
&mkpath($dest, 0, 0755);

print "Copying compilers\n";
&my_copyexecutable("$BETALIB/bin/$objdir", "nbeta.exe", "bin");
&my_copyexecutable("$BETALIB/bin/$objdir", "jbeta.exe", "bin");
&my_copyexecutable("export",            "managed-nbeta.bat", "bin");
&my_copyexecutable("$BETALIB/compiler", "managed-nbeta.exe", "bin");
&my_copyfiles     ("$BETALIB/compiler", "managed-nbeta.exe.config", "bin");
if (0){
    # Fails to run on .NET CLR (access denied) if copied this way?
    # Problems with time stamps?
    &my_copydir("$BETALIB/compiler/clr/managed-nbeta", "bin/clr/managed-nbeta");
} else {
    &mkpath("$dest/bin/clr");
    system("cp -rp $BETALIB/compiler/clr/managed-nbeta $dest/bin/clr");
}

print "Copying grammars\n";
&my_copydir("$BETALIB/grammars/metagram", "grammars/metagram");
&my_copydir("$BETALIB/grammars/pretty", "grammars/pretty");
&my_copydir("$BETALIB/grammars/beta", "grammars/beta");

print "Copying configuration\n";
&my_copydir("$BETALIB/configuration", "configuration");

print "Copying standard libraries\n";
foreach $lib (@std_libs){
    &my_copy_std_library($lib);
}
print "     -> javalib ";
&my_copy_beta_dir_recursively("$BETALIB/javalib",  "javalib", 1);
print "     -> dotnetlib ";
&my_copy_beta_dir_recursively("$BETALIB/dotnetlib",  "dotnetlib", 1);
&my_copyfiles("$BETALIB/dotnetlib", "conversion-rules.txt", "dotnetlib");

print "Copying tools\n";
&my_copyexecutable("$BETALIB/bin/$objdir", "dotnet2beta.exe", "bin");
&my_copyexecutable("$BETALIB/bin/$objdir", "BetaOutput.dll",  "bin");
&my_copyexecutable("$BETALIB/bin",         "java2beta.bat",   "bin");
&my_copyexecutable("$BETALIB/bin/$objdir", "betacc.exe",      "bin");
&my_copyfiles("$BETALIB/javalib/java2beta/classes/beta/converter", "*.class", "javalib/java2beta/classes/beta/converter");

print "Copying examples\n";
foreach $f (@examples){
    &my_copyfiles(".", $f, "examples");
}
open SEE_ALSO, ">$dest/examples/SEE_ALSO.txt" 
    || die "Cannot open $dest/examples/SEE_ALSO.txt for writing: $!\n";
print SEE_ALSO<<EOT;
Besides the exmples in this directory (of which some are explained
in the README file), you may find various demo programs in the following
directories:

EOT

foreach $lib (@std_libs){
    if (-d "$BETALIB/$lib/demo"){
	print SEE_ALSO "  ../$lib/demo\n";
    }
}
print SEE_ALSO<<EOT;

Notice that a number of the demo programs in these directories mail still
fail, but at least some of them should work.
EOT
close SEE_ALSO;

print "Copying documentation\n";
&my_copyfiles("$BETALIB/compiler/DOC/BYTECODE", "*.*", "documentation");
&my_copyfiles("$BETALIB/compiler/DOC/BYTECODE/images", "*.*", "documentation/images");
&my_copyfiles("$BETALIB/compiler/DOC/BYTECODE/converter", "*.*", "documentation/converter");

print "Copying presentations\n";
foreach $f (@presentations){
    &my_copyfiles("$BETALIB/compiler/DOC/BYTECODE/", $f, "documentation");
}

print "Copying setup files\n";
copy("export/cmd_setup.bat", "$dest/configuration");
copy("export/cygwin_bash_setup.sh", "$dest/configuration");

if ($T){
    print "Copying testall suite (-T option)\n";
    copy("testall", "$dest/examples");
    &my_copydir("reference", "examples/reference");
    &my_copydir("$BETALIB/bin/admin", "bin/admin");
}

print "Creating README.txt\n";
&pushd("$dest/documentation");
open README, ">$dest/README.txt" || die "Cannot open README.txt for writing: $\n";
print README "   NOTICE: an HTML version of this file is available in \r\n\t   documentation/README.html\r\n\r\n";
open LYNX, "sed -e 's%<pre%<dl><dt><dd%gi' -e 's%</pre>%</dl>%gi' README.html | lynx -dump -stdin |" || die "Cannot start lynx on documentation/README.html: $!\n";
while(<LYNX>){
    last if (/^References/);
    s/^>/\t  >/;
    s/\[[0-9]+\]//g;
    chomp;
    print README; print README "\r\n";
}
close LYNX;
close README;
&popd();

print "Clean up\n";
foreach $f (@cleanup){
    foreach $g (glob("$dest/$f")){
	print "  Deleting $g\n" if ($verbose);
	&rmtree($g, 0, 1);
    }
}

if ($skipzipping){
    print "Skipping zipping of directory (-Z option)\n";
} else {
    local ($sec,$min,$hour,$date,$month,$year,$day,$yday,$isdst) = localtime(time);
    $zipname = sprintf("$dest-%02d-%02d-%02d.zip", 1900+$year, $month+1, $date);
    unlink "$zipname" if (-e "$zipname");
    print "Zipping directory to $zipname\n";
    system "zip -qr $zipname $dest";
}

if ($publish){
    print "Publishing $zipname (to $publish_dir)\n";
    if ( -d $publish_dir ){
	copy($zipname, "$publish_dir");
    } else {
	print "Cannot publish: $publish_dir is not a directory\n";
    }
}

# -------------- Routines  ---------------------------------------------

sub my_copydir($srcbase, $destbase){
    my ($srcbase, $destbase) = @_;
    &my_copyfiles($srcbase, "*", $destbase);
}

sub my_copyexecutable($srcbase, $file, $destdir){
    my ($srcbase, $file, $destdir) = @_;
    &my_copyfiles ($srcbase, $file, $destdir);
    chmod 0755, "$dest/$destdir/$file";
}

sub my_copyfiles ($srcbase, $filespec, $destdir){
    my ($srcbase, $filespec, $destdir) = @_;
    foreach $g (glob("$srcbase/$filespec")){
	my ($path) = "$g";
	next if ($path =~ m%~$%); # skip tilde files
	next if ($path =~ m%/CVS%); # skip CVS files
	# skip various autogenerated files:
	next if ($path =~ m%(\.lst$|\.pdb$|\.sln$|\.duo$|\.suo$|\.dln$)%); 
	next if ($path =~ m%\.pdb$%);
	next if ($path =~ m%\.sln$%); 
	$path = substr $path, length($srcbase);  # remove srcbase/ prefix
	$path =~ s%/[^/]*$%%;                    # delete file component
	$path = "$dest/$destdir$path";
	if (! -d "$path"){
	    print "Making directory $path\n" if ($verbose);
	    &mkpath($path, 0, 0755);
	}
	print "Copy $g $path\n" if ($verbose);
	# system "/usr/bin/cp -p $g \"$path\""; # very slow
	copy($g, "$path"); 
    }
}



sub find_beta_files()
{
    $f = $File::Find::name;
    next unless $f =~ m%(\.bet$|\.c$|\.h$|\.java$|\.cs$)%;
    next if ($f =~ m%/test/%);
    $f =~ s%^\./%%; # strip ./ prefix
    push @beta_files, $f;
}

sub my_copy_beta_dir_recursively($srcdir, $destdir, $progress)
{
    my ($srcdir, $destdir, $progress) = @_;
    &pushd($srcdir);
    undef @beta_files;
    find(\&find_beta_files, ".");
    &popd();
    print "(" . scalar(@beta_files) . " files)\n" if ($progress);
    foreach $f (@beta_files){
	print (".") if ($progress);
	&my_copyfiles("$srcdir", $f, "$destdir");
    }
    print ("\n") if ($progress);
}

sub my_copy_std_library($name)
{
    my ($name) = @_;
    print "     -> $name ";
    &my_copy_beta_dir_recursively("$BETALIB/$name", "$name", 1);
};

sub my_copy_clr_directory($srcbase, $destbase)
{
    my ($srcbase, $destbase) = @_;
    return if (! -d "$srcbase/clr");
    &my_copyfiles($srcbase, "clr/*.il",  $destbase);
    &my_copyfiles($srcbase, "clr/*.pdb",  $destbase);
    &my_copyfiles($srcbase, "clr/*.clst",  $destbase);
    &my_copyfiles($srcbase, "clr/*.dll",  $destbase);
}

sub my_copy_jvm_directory($srcbase, $destbase)
{
    my ($srcbase, $destbase) = @_;
    return if (! -d "$srcbase/jvm");
    &my_copyfiles($srcbase, "jvm/*.dep",  $destbase);
    &my_copyfiles($srcbase, "jvm/*.clst",  $destbase);
    &my_copyfiles($srcbase, "jvm/beta/*.class",  $destbase);
}
