#!/bin/sh

#--------- Configuration: ------

# Directories containing source files:
SRC="${BETALIB}/win32lib"

# Files to include in interface. The order given here will
# be the order they appear in in the generated interface.
FILES="\
winnt.bet \
"

MAKEINT=../../bin/beta2int.perl
MAKEHTML=../../bin/int2html.perl
 
. ../../bin/makeHTML.sh
 