#!/bin/sh

#--------- Configuration: ------

# Directories containing source files:
SRC="${BETALIB}/sysutils"

# Files to include in interface. The order given here will
# be the order they appear in in the generated interface.
FILES="\
binarystream.bet \
cstring.bet \
endian.bet \
envstring.bet \
errorscreen.bet \
heapinfo.bet \
objinterface.bet \
pathhandler.bet \
RepetitionObject.bet \
scanobjects.bet \
time.bet \
timeHistory.bet \
"

MAKEINT=../../bin/beta2int.perl
MAKEHTML=../../bin/int2html.perl

. ../../bin/makeHTML.sh
