#!/usr/local/bin/perl

print "Splitting run.default into separate files in directory reference\n";

print "Opening run.default\n";
open DEF, "run.default" || die "Cannot open run.default: $!\n";

if (! -d "reference"){
    print "Creating directory reference\n";
    mkdir "reference", 0755 || die "Cannot create directory reference: $!\n";
    print "Adding directory reference to CVS\n";
    system "cvs add reference";
}

print "Reading run.default\n";
$run    = 0;
$blank  = 0;
while (<DEF>){
    if (/^############# Running (.*)$/){
	if ($run){
	    print "    Closing $run\n";
	    close RUN;
	    print "    CVS adding (not yet)\n";
	    #print "    "; system "cvs add $run";
	    $blank = 0;
	}
	$run = "reference/$1.run";
	print "   Creating $run\n";
	open RUN, ">$run" || die "Cannot create $run: $!\n";
    } elsif (/^$/){
	# Delay blank line: Must not be printed if next line is "Running" line
	$blank = 1;
    } else {
	if ($run){
	    if ($blank){
		print RUN "\n";
		$blank = 0;
	    }
	    print RUN;
	} else {
	    "Warning: this line has no run file to go into:\n";
	    print;
	}
    }
}
if ($run){
    print "    Closing $run\n";
    close RUN;
    print "    CVS adding (not yet)\n";
    #print "    "; system "cvs add $run";
}

print "Closing run.default\n";
close DEF;

print "Removing run.default (not yet)\n";
#unlink "run.default";
print "CVS removing run.default (not yet)\n";
#system "cvs rm run.default";

print "Done.\n";
print "Now try run.demos and cvs commit if all is well.\n";



