#!/usr/local/bin/perl -s
$BETALIB=$ENV{'BETALIB'};
$BETALIB=~s%\\%/%g;
require "$BETALIB/bin/admin/env.perl";

# -------------- Configuration-----------------------------------------

$dest        = "BETA_Net";
$beta        = "$BETALIB/boot/bin/$objdir/beta";
$compilersrc = "$BETALIB/compiler/nbeta.bet";
$compiler    = "$BETALIB/compiler/$objdir/nbeta.exe";
$readme      = "README-dotnet.txt";
@examples    = ("tstenv.bet",
		"dotnettstenvbody.bet",
		"javabctstenvbody.bet",
		"Bmini0.bet", 
		"Bmini1.bet", 
		"Server.bet", 
		"Calculator.bet", 
		"Counter.bet", 
		"List.bet", 
		"NumList.bet",
		"Aclass.bet", 
		"Singular.bet", 
		"SuperFields.bet",
		"Ptn.bet", 
		"array.bet",
		"small.bet",
		"hellobox.bet",
		"Bclass*.{bet,cs}",
		);

# -------------- Main -------------------------------------------------

use File::Path;
use File::Copy;
use File::Find;

$skipcompilation = $C;
$skipzipping = $Z;

print "Creating BETA .Net preliminary distribution in directory $dest\n";
 
if ( -d $dest ){
   print "Deleting existing $dest\n";
   &rmtree($dest, 0, 1);
}

if ($skipcompilation){
    print "Skipping recompilation of compiler (-C option)\n";
} else {
    print "Recompiling compiler\n";
    system "$beta -qwd -o $compiler $compilersrc > bootbeta.out";
}

print "Creating directory $dest\n";
&mkpath($dest, 0, 0755);

print "Copying $readme\n";
&copy($readme, "$dest");

print "Copying compiler\n";
&mkpath("$dest/bin", 0, 0755);
&copy($compiler, "$dest/bin");

print "Copying grammars\n";
&mkpath("$dest/grammars", 0, 0755);
&copydir("$BETALIB/grammars/metagram", "$dest/grammars");
&copydir("$BETALIB/grammars/pretty", "$dest/grammars");
&copydir("$BETALIB/grammars/beta", "$dest/grammars");

print "Copying configuration\n";
&copydir("$BETALIB/configuration", "$dest");

print "Copying examples\n";
&mkpath("$dest/examples", 0, 0755);
foreach $f (@examples){
    foreach $g (glob($f)){
	&copy($g, "$dest/examples");
    }
}

print "Copying documentation\n";
&mkpath("$dest/doc", 0, 0755);
foreach $f (<$BETALIB/compiler/DOC/BYTECODE/*.*>){
    &copy($f, "$dest/doc");
}

if ($skipzipping){
    print "Skipping zipping of directory (-Z option)\n";
} else {
    print "Zipping directory\n";
    system "zip -qr $dest.zip $dest";
}

# -------------- Routines  ---------------------------------------------

sub copydir($srcdir, $destdir){
    my ($srcdir, $destdir) = @_;
    if (1){
	system "cp -rp $srcdir $destdir";
    } else {
	# Recursive copy not part of std perl (;-(
	# Found in groups.google.com, not tested:
	my $length = length $srcroot;
	use File::Copy;
	find  sub {
	    my $dest = $File::Find::name; # full source path
	    substr($dest, 0, $length)= $destdir;
	    if(-d) {
		mkdir $dest, 0777;
	    } elsif(-f _) {
		copy $_, $dest;
	    }
	}, $srcdir;
    }
}

sub usage()
{
    local($msg) = @_;
    print "pack_dotnet: $msg\n" if ($msg ne "");
    print<<EOT;
usage: pack_dotnet [-h][-v][-r][-c][-C][-x][-d][-j]
     -h  print this help
     -v  verbose mode
     -C  skip compilation of compiler
     -Z  skip zipping of directory
EOT
    exit;
}
