#!/usr/local/bin/perl -s
$BETALIB=$ENV{'BETALIB'};
$BETALIB=~s%\\%/%g;
require "$BETALIB/bin/admin/env.perl";

sub usage()
{
    local($msg) = @_;
    print "pack_dotnet: $msg\n" if ($msg ne "");
    print<<EOT;
usage: pack_dotnet [-h][-v][-C][-z][-p]
     -h  print this help
     -v  verbose mode
     -C  skip compilation of compilers
     -Z  skip zipping of directory
     -T  include testall and reference output
     -p  "publish" new zip file on web (datpete only)
EOT
    exit;
}

# -------------- Configuration-----------------------------------------

$dest        = "BETA_Net";
$beta        = "$BETALIB/boot/bin/$objdir/beta";
$nbetasrc    = "$BETALIB/compiler/nbeta.bet";
$nbeta       = "$BETALIB/bin/$objdir/nbeta.exe";
$jbetasrc    = "$BETALIB/compiler/jbeta.bet";
$jbeta       = "$BETALIB/bin/$objdir/jbeta.exe";
$publish_dir = "Z:public_html/dotnet/beta_net";

@examples    = (# betaenv and implementation
		# output from testall -d -l
		"Aclass.bet",
		"Bmini0.bet",
		"Bmini1.bet",
		"Calculator.bet",
		"Counter.bet",
		"ECStest.bet",
		"ECtest.bet",
		"LL1.bet",
		"List.bet",
		"NumList.bet",
		"Ptn.bet",
		"Server.bet",
		"Singular.bet",
		"SuperFields.bet",
		"array.bet",
		"beer.bet",
		"constructor.bet",
		"faclink.bet",
		"go.bet",
		"google.bet",
		"googlesnip.bet",
		"googlesnipre.bet",
		"hello.bet",
		"multiple.bet",
		"nstring.bet",
		"real32.bet",
		"small.bet",
		"stackuser.bet",

		# hello implementation
		"hellolib.bet",

		# stack implementation
		"stack.bet",
		"stackbody.bet",

		# google implementation
		"googlesearch.bet", 
		"google_*.bet", 
		"google*.exe.config",
		"googleapi/LICENSE.txt",
		"googleapi/googleapi.jar",
		"googleapi/dotnet/GoogleSearchService.cs",

		# clr specific stuff
		"hellobox.bet",
		"hellographics.bet",
		"nstringuser.cs",

		# java specific stuff
		"bpackage.bet",
		"bpackageuser.java",
		"jstringuser.java",
		"jstring.bet",
		"javastring.bet",
		"greetings.bet",
		"helloapplet.bet",
		"helloapplet.html",

		# External programs
		"EC.{cs,java}",
		"Bclass*.{bet,cs,config,java}",
		"xreal32class.{cs,java}",

		# Misc
		"GNUmakefile",
		"make_clean.bat",
		);

@cleanup = ( "*/CVS",
	     "*/*/CVS",
	     "configuration/mbs_id",
	     "configuration/ymer.pjt",
	     "configuration/env.*",
	     "documentation/*~",
	     "grammars/*/CVS",
	     "grammars/*/*.lst",
	     "examples/googleapi/CVS",
	     "examples/googleapi/*/CVS",
	     "examples/googleapi/*/*/CVS",
	     "examples/googleapi/*/*/*/CVS",
	     "examples/googleapi/*/*/*/*/CVS",
	     "examples/googleapi/*/*/*/*/*/CVS",
	     "examples/googleapi/*/*/*/*/*/*/CVS",
	     "examples/googleapi/dotnet/GoogleSearchService.dll",
	     "examples/googleapi/dotnet/GoogleSearchService.pdb",
	     );

# -------------- Main -------------------------------------------------

use File::Path;
use File::Copy;
use File::Find;

&usage() if ($h);

$skipcompilation = $C;
$skipzipping = $Z;
$publish = $p;

print "Creating BETA .Net preliminary distribution in directory $dest\n";
 
if ( -d $dest ){
   print "Deleting existing $dest\n";
   #&rmtree($dest, 0, 1);
   system "rm -rf $dest";
}

if ($skipcompilation){
    print "Skipping recompilation of compilers (-C option)\n";
} else {
    print "Recompiling compilers\n";
    system "$beta -qwd -o $nbeta $nbetasrc > nbetaboot.out";
    system "$beta -qwd -o $jbeta $jbetasrc > jbetaboot.out";
}

print "Creating directory $dest\n";
&mkpath($dest, 0, 0755);

print "Copying compilers\n";
&mkpath("$dest/bin", 0, 0755);
&copy($nbeta, "$dest/bin/nbeta.exe");
chmod 0755, "$dest/bin/nbeta.exe";
&copy($jbeta, "$dest/bin/jbeta.exe");
chmod 0755, "$dest/bin/jbeta.exe";

print "Copying grammars\n";
&copydir("$BETALIB/grammars/metagram", "$dest/grammars");
&copydir("$BETALIB/grammars/pretty", "$dest/grammars");
&copydir("$BETALIB/grammars/beta", "$dest/grammars");

print "Copying configuration\n";
&copydir("$BETALIB/configuration", "$dest");

print "Copying basiclib\n";
&copyfiles("$BETALIB/basiclib", "*.bet",         "basiclib");
&copyfiles("$BETALIB/basiclib", "private/*.bet", "basiclib");
#&copyfiles("$BETALIB/basiclib", "demo/*/*.bet",  "basiclib");

print "Copying examples\n";
foreach $f (@examples){
    &copyfiles(".", $f, "examples");
}

print "Copying documentation\n";
&copyfiles("$BETALIB/compiler/DOC/BYTECODE", "*.*", "documentation");

print "Copying setup files\n";
&copy("cmd_setup.bat", "$dest");
&copy("bash_setup.sh", "$dest");

if ($T){
    print "Copying testall suite (-T option)\n";
    &copy("testall", "$dest/examples");
    &copydir("reference", "$dest/examples");
    &copydir("$BETALIB/bin/admin", "$dest/bin");
}

print "Creating README-dotnet.txt\n";
open README, ">$dest/README-dotnet.txt" || die "Cannot open README-dotnet.txt for writing: $\n";
print README "   NOTICE: an HTML version of this file is available in \n\t   documentation/README-dotnet.html\n\n";
open LYNX, "lynx -dump $dest/documentation/README-dotnet.html|" || die "Cannot start lynx on documentation/README-dotnet.html: $!\n";
while(<LYNX>){
    last if (/^References/);
    s/^>/\t  >/;
    s/\[[0-9]+\]//g;
    print README;
}
close LYNX;
close README;

print "Clean up\n";
foreach $f (@cleanup){
    foreach $g (glob("$dest/$f")){
	print "  Deleting $g\n" if ($verbose);
	&rmtree($g, 0, 1);
    }
}

if ($skipzipping){
    print "Skipping zipping of directory (-Z option)\n";
} else {
    local ($sec,$min,$hour,$date,$month,$year,$day,$yday,$isdst) = localtime(time);
    $zipname = sprintf("$dest-%02d-%02d-%02d.zip", 1900+$year, $month+1, $date);
    unlink "$zipname" if (-e "$zipname");
    print "Zipping directory to $zipname\n";
    system "zip -qr $zipname $dest";
}

if ($publish){
    print "Publishing $zipname (to $publish_dir)\n";
    if ( -d $publish_dir ){
	&copy($zipname, "$publish_dir");
    } else {
	print "Cannot publish: $publish_dir is not a directory\n";
    }
}

# -------------- Routines  ---------------------------------------------

sub copydir($srcdir, $destdir){
    my ($srcdir, $destdir) = @_;
    &mkpath("$destdir", 0, 0755);
    if (1){
	system "cp -rp $srcdir $destdir";
    } else {
	# Recursive copy not part of std perl (;-(
	# Found in groups.google.com, not tested:
	my $length = length $srcdir;
	find  sub {
	    my $dest = $File::Find::name; # full source path
	    substr($dest, 0, $length) = $destdir;
	    if(-d) {
		mkdir $dest, 0777;
	    } elsif(-f _) {
		copy $_, $dest;
	    }
	}, $srcdir;
    }
}

sub copyfiles ($srcbase, $filespec, $destdir){
    my ($srcbase, $filespec, $destdir) = @_;
    foreach $g (glob("$srcbase/$filespec")){
	my ($path) = "$g";
	$path = substr $path, length($srcbase);  # remove srcbase/ prefix
	$path =~ s%/[^/]*$%%;                    # delete file component
	$path = "$dest/$destdir$path";
	print "Making directory $path\n" if ($verbose);
	&mkpath($path, 0, 0755);
	print "Copy $g $path\n" if ($verbose);
	&copy($g, "$path");
    }
}
