#!/bin/sh

#--------- Configuration: ------

# Directories containing source files:
#SRC="${BETALIB}/betadbc"
SRC="../../../betadbc"
QUIET=0
# Files to include in interface. The order given here will
# be the order they appear in in the generated interface.
FILES="\
betadbc.bet \
scrollingresultset.bet \
tables.bet \
transactions.bet \
"

MAKEINT=../../bin/beta2int.perl
#MAKEHTML=../../bin/int2html.perl
MAKEHTML=../../bin/int2frames.perl


. ../../bin/makeHTML.sh



