#! /bin/sh

# Script to stick bounding box finder in front of a postscript file
#    Adapted from Ned's original

# $Header: /a/home/alhambra02/beta/.CVSHOME/beta_project/freja/EPS/bbfig,v 1.1 1997-01-29 12:44:24 beta Exp $

# BBPSDIR=<wherever>  # Define this if bb.ps doesn't live in same
                      #   directory as bbfig
#BBPSDIR=/local/scripts
PRINT=0
#if [ ! -f ${BBPSDIR=`dirname $0`}/bb.ps ]
if [ ! -f ${BBPSDIR}/bb.ps ]
then
    echo >&2 "Can't locate $BBPSDIR/bb.ps"
    exit 1
fi

case $# in
    0)
	  ;;
    *)  if [ $1 = "-gs" ]
	then
          PRINT=1
	  shift
        fi
	  ;;
esac

if [ $PRINT -eq 1 ]
then
case $# in
    0)    cat $BBPSDIR/bb.ps - | gs -dNODISPLAY -r600 -q -
	  ;;
    *)    cat $BBPSDIR/bb.ps "$@" | gs -dNODISPLAY -r600 -q -
	  ;;
esac
else
case $# in
    0)    cat $BBPSDIR/bb.ps -
	  ;;
    *)    cat $BBPSDIR/bb.ps "$@"
	  ;;
esac
fi
