tags:
	etags *.bet misc/*.bet tstdump/*.bet *.make *.c
clean:
	-/bin/rm -f *~ *.ast *.astL *.lst *.dump */*~ */*.ast */*.astL */*.lst */*.dump */*.o */*.s */*..job */*/*.o */*/*.s */*/*..job tstdump/tstdump?? tst misc/tstgc misc/tstcb misc/tstqua misc/tstrepgc
