tags:
	etags *.bet misc/*.bet tstdump/*.bet *.make *.c
clean:
	@echo Cleaning TST
	-@/bin/rm -f *~ *.ast *.astL *.lst *.dump */*~ */*.ast */*.astL */*.lst */*.o */*.s */*..job */*/*.o */*/*.s */*/*..job tstdump/tstdump?? tstdump/*.out tst misc/tstgc misc/tstcb misc/tstqua misc/tstrepgc
