//==========================================================================;
//
//  THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY
//  KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
//  IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR
//  PURPOSE.
//
//  Copyright (c) 1992 - 1996  Microsoft Corporation.  All Rights Reserved.
//
//--------------------------------------------------------------------------;

// ActiveMovie interface definitions


import "Unknwn.Idl";
import "ObjIdl.Idl";	// for IPersist (IFilter's root)

// core interfaces
#include "axcore.idl"

// extended, ActiveMovie-only interfaces
#include "axextend.idl"

// ActiveMovie-only sample plug-in distributor interface
#include "iamovie.idl"

#include "devenum.idl"

// application interfaces for DVD
#include "dvdif.idl"
