import "Excel01.Idl";


    [
      odl,
      uuid(0002084D-0001-0000-C000-000000000046),
      helpcontext(0x0002000d),
      hidden
    ]
    interface IFont : IDispatch {
        [propget, helpcontext(0x00010094)]
        HRESULT _stdcall Application([out, retval] Application** RHS);
        [propget, helpcontext(0x00010095)]
        HRESULT _stdcall Creator([out, retval] XlCreator* RHS);
        [propget, helpcontext(0x00010096)]
        HRESULT _stdcall Parent([out, retval] IDispatch** RHS);
        [propget, helpcontext(0x000100b4)]
        HRESULT _stdcall Background([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x000100b4)]
        HRESULT _stdcall Background([in] VARIANT RHS);
        [propget, helpcontext(0x00010060)]
        HRESULT _stdcall Bold([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010060)]
        HRESULT _stdcall Bold([in] VARIANT RHS);
        [propget, helpcontext(0x00010063)]
        HRESULT _stdcall Color([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010063)]
        HRESULT _stdcall Color([in] VARIANT RHS);
        [propget, helpcontext(0x00010061)]
        HRESULT _stdcall ColorIndex([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010061)]
        HRESULT _stdcall ColorIndex([in] VARIANT RHS);
        [propget, helpcontext(0x000100b1)]
        HRESULT _stdcall FontStyle([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x000100b1)]
        HRESULT _stdcall FontStyle([in] VARIANT RHS);
        [propget, helpcontext(0x00010065)]
        HRESULT _stdcall Italic([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010065)]
        HRESULT _stdcall Italic([in] VARIANT RHS);
        [propget, helpcontext(0x0001006e)]
        HRESULT _stdcall Name([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x0001006e)]
        HRESULT _stdcall Name([in] VARIANT RHS);
        [propget, helpcontext(0x000100dd)]
        HRESULT _stdcall OutlineFont([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x000100dd)]
        HRESULT _stdcall OutlineFont([in] VARIANT RHS);
        [propget, helpcontext(0x00010067)]
        HRESULT _stdcall Shadow([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010067)]
        HRESULT _stdcall Shadow([in] VARIANT RHS);
        [propget, helpcontext(0x00010068)]
        HRESULT _stdcall Size([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010068)]
        HRESULT _stdcall Size([in] VARIANT RHS);
        [propget, helpcontext(0x00010069)]
        HRESULT _stdcall Strikethrough([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010069)]
        HRESULT _stdcall Strikethrough([in] VARIANT RHS);
        [propget, helpcontext(0x000100b3)]
        HRESULT _stdcall Subscript([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x000100b3)]
        HRESULT _stdcall Subscript([in] VARIANT RHS);
        [propget, helpcontext(0x000100b2)]
        HRESULT _stdcall Superscript([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x000100b2)]
        HRESULT _stdcall Superscript([in] VARIANT RHS);
        [propget, helpcontext(0x0001006a)]
        HRESULT _stdcall Underline([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x0001006a)]
        HRESULT _stdcall Underline([in] VARIANT RHS);
    };

    [
      odl,
      uuid(00020893-0001-0000-C000-000000000046),
      helpcontext(0x00020053),
      hidden
    ]
    interface IWindow : IDispatch {
        [propget, helpcontext(0x00010094)]
        HRESULT _stdcall Application([out, retval] Application** RHS);
        [propget, helpcontext(0x00010095)]
        HRESULT _stdcall Creator([out, retval] XlCreator* RHS);
        [propget, helpcontext(0x00010096)]
        HRESULT _stdcall Parent([out, retval] IDispatch** RHS);
        [helpcontext(0x00010130)]
        HRESULT _stdcall Activate();
        [helpcontext(0x0001045b)]
        HRESULT _stdcall ActivateNext();
        [helpcontext(0x0001045c)]
        HRESULT _stdcall ActivatePrevious();
        [propget, helpcontext(0x00010131)]
        HRESULT _stdcall ActiveCell([out, retval] Range** RHS);
        [propget, helpcontext(0x000100b7)]
        HRESULT _stdcall ActiveChart([out, retval] Chart** RHS);
        [propget, helpcontext(0x00010282)]
        HRESULT _stdcall ActivePane([out, retval] Pane** RHS);
        [propget, helpcontext(0x00010133)]
        HRESULT _stdcall ActiveSheet([out, retval] IDispatch** RHS);
        [propget, helpcontext(0x0001008b)]
        HRESULT _stdcall Caption([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x0001008b)]
        HRESULT _stdcall Caption([in] VARIANT RHS);
        [helpcontext(0x00010115)]
        HRESULT _stdcall Close(
                        [in, optional] VARIANT SaveChanges, 
                        [in, optional] VARIANT Filename, 
                        [in, optional] VARIANT RouteWorkbook);
        [propget, helpcontext(0x00010284)]
        HRESULT _stdcall DisplayFormulas([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010284)]
        HRESULT _stdcall DisplayFormulas([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x00010285)]
        HRESULT _stdcall DisplayGridlines([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010285)]
        HRESULT _stdcall DisplayGridlines([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x00010286)]
        HRESULT _stdcall DisplayHeadings([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010286)]
        HRESULT _stdcall DisplayHeadings([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x00010399)]
        HRESULT _stdcall DisplayHorizontalScrollBar([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010399)]
        HRESULT _stdcall DisplayHorizontalScrollBar([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x00010287)]
        HRESULT _stdcall DisplayOutline([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010287)]
        HRESULT _stdcall DisplayOutline([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x00010288)]
        HRESULT _stdcall DisplayRightToLeft([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010288)]
        HRESULT _stdcall DisplayRightToLeft([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x0001039a)]
        HRESULT _stdcall DisplayVerticalScrollBar([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x0001039a)]
        HRESULT _stdcall DisplayVerticalScrollBar([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x0001039b)]
        HRESULT _stdcall DisplayWorkbookTabs([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x0001039b)]
        HRESULT _stdcall DisplayWorkbookTabs([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x00010289)]
        HRESULT _stdcall DisplayZeros([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010289)]
        HRESULT _stdcall DisplayZeros([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x000104a8)]
        HRESULT _stdcall EnableResize([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x000104a8)]
        HRESULT _stdcall EnableResize([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x0001028a)]
        HRESULT _stdcall FreezePanes([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x0001028a)]
        HRESULT _stdcall FreezePanes([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x0001028b)]
        HRESULT _stdcall GridlineColor([out, retval] long* RHS);
        [propput, helpcontext(0x0001028b)]
        HRESULT _stdcall GridlineColor([in] long RHS);
        [propget, helpcontext(0x0001028c)]
        HRESULT _stdcall GridlineColorIndex([out, retval] XlColorIndex* RHS);
        [propput, helpcontext(0x0001028c)]
        HRESULT _stdcall GridlineColorIndex([in] XlColorIndex RHS);
        [propget, helpcontext(0x0001007b)]
        HRESULT _stdcall Height([out, retval] double* RHS);
        [propput, helpcontext(0x0001007b)]
        HRESULT _stdcall Height([in] double RHS);
        [propget, helpcontext(0x000101e6)]
        HRESULT _stdcall Index([out, retval] long* RHS);
        [helpcontext(0x00010223)]
        HRESULT _stdcall LargeScroll(
                        [in, optional] VARIANT Down, 
                        [in, optional] VARIANT Up, 
                        [in, optional] VARIANT ToRight, 
                        [in, optional] VARIANT ToLeft);
        [propget, helpcontext(0x0001007f)]
        HRESULT _stdcall Left([out, retval] double* RHS);
        [propput, helpcontext(0x0001007f)]
        HRESULT _stdcall Left([in] double RHS);
        [helpcontext(0x00010118)]
        HRESULT _stdcall NewWindow([out, retval] Window** RHS);
        [propget, helpcontext(0x0001026f)]
        HRESULT _stdcall OnWindow([out, retval] BSTR* RHS);
        [propput, helpcontext(0x0001026f)]
        HRESULT _stdcall OnWindow([in] BSTR RHS);
        [propget, helpcontext(0x0001028d)]
        HRESULT _stdcall Panes([out, retval] Panes** RHS);
        [helpcontext(0x00010389)]
        HRESULT _stdcall PrintOut(
                        [in, optional] VARIANT From, 
                        [in, optional] VARIANT To, 
                        [in, optional] VARIANT Copies, 
                        [in, optional] VARIANT Preview, 
                        [in, optional] VARIANT ActivePrinter, 
                        [in, optional] VARIANT PrintToFile, 
                        [in, optional] VARIANT Collate);
        [helpcontext(0x00010119)]
        HRESULT _stdcall PrintPreview([in, optional] VARIANT EnableChanges);
        [propget, helpcontext(0x000104a5)]
        HRESULT _stdcall RangeSelection([out, retval] Range** RHS);
        [propget, helpcontext(0x0001028e)]
        HRESULT _stdcall ScrollColumn([out, retval] long* RHS);
        [propput, helpcontext(0x0001028e)]
        HRESULT _stdcall ScrollColumn([in] long RHS);
        [propget, helpcontext(0x0001028f)]
        HRESULT _stdcall ScrollRow([out, retval] long* RHS);
        [propput, helpcontext(0x0001028f)]
        HRESULT _stdcall ScrollRow([in] long RHS);
        [helpcontext(0x00010296)]
        HRESULT _stdcall ScrollWorkbookTabs(
                        [in, optional] VARIANT Sheets, 
                        [in, optional] VARIANT Position);
        [propget, helpcontext(0x00010290)]
        HRESULT _stdcall SelectedSheets([out, retval] Sheets** RHS);
        [propget, helpcontext(0x00010093)]
        HRESULT _stdcall Selection([out, retval] IDispatch** RHS);
        [helpcontext(0x00010224)]
        HRESULT _stdcall SmallScroll(
                        [in, optional] VARIANT Down, 
                        [in, optional] VARIANT Up, 
                        [in, optional] VARIANT ToRight, 
                        [in, optional] VARIANT ToLeft);
        [propget, helpcontext(0x00010291)]
        HRESULT _stdcall Split([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010291)]
        HRESULT _stdcall Split([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x00010292)]
        HRESULT _stdcall SplitColumn([out, retval] long* RHS);
        [propput, helpcontext(0x00010292)]
        HRESULT _stdcall SplitColumn([in] long RHS);
        [propget, helpcontext(0x00010293)]
        HRESULT _stdcall SplitHorizontal([out, retval] double* RHS);
        [propput, helpcontext(0x00010293)]
        HRESULT _stdcall SplitHorizontal([in] double RHS);
        [propget, helpcontext(0x00010294)]
        HRESULT _stdcall SplitRow([out, retval] long* RHS);
        [propput, helpcontext(0x00010294)]
        HRESULT _stdcall SplitRow([in] long RHS);
        [propget, helpcontext(0x00010295)]
        HRESULT _stdcall SplitVertical([out, retval] double* RHS);
        [propput, helpcontext(0x00010295)]
        HRESULT _stdcall SplitVertical([in] double RHS);
        [propget, helpcontext(0x000102a1)]
        HRESULT _stdcall TabRatio([out, retval] double* RHS);
        [propput, helpcontext(0x000102a1)]
        HRESULT _stdcall TabRatio([in] double RHS);
        [propget, helpcontext(0x0001007e)]
        HRESULT _stdcall Top([out, retval] double* RHS);
        [propput, helpcontext(0x0001007e)]
        HRESULT _stdcall Top([in] double RHS);
        [propget, helpcontext(0x0001006c)]
        HRESULT _stdcall Type([out, retval] XlWindowType* RHS);
        [propget, helpcontext(0x00010185)]
        HRESULT _stdcall UsableHeight([out, retval] double* RHS);
        [propget, helpcontext(0x00010186)]
        HRESULT _stdcall UsableWidth([out, retval] double* RHS);
        [propget, helpcontext(0x0001022e)]
        HRESULT _stdcall Visible([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x0001022e)]
        HRESULT _stdcall Visible([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x0001045e)]
        HRESULT _stdcall VisibleRange([out, retval] Range** RHS);
        [propget, helpcontext(0x0001007a)]
        HRESULT _stdcall Width([out, retval] double* RHS);
        [propput, helpcontext(0x0001007a)]
        HRESULT _stdcall Width([in] double RHS);
        [propget, helpcontext(0x0001045f)]
        HRESULT _stdcall WindowNumber([out, retval] long* RHS);
        [propget, helpcontext(0x0001018c)]
        HRESULT _stdcall WindowState([out, retval] XlWindowState* RHS);
        [propput, helpcontext(0x0001018c)]
        HRESULT _stdcall WindowState([in] XlWindowState RHS);
        [propget, helpcontext(0x00010297)]
        HRESULT _stdcall Zoom([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010297)]
        HRESULT _stdcall Zoom([in] VARIANT RHS);
        [propget, helpcontext(0x000104aa)]
        HRESULT _stdcall View([out, retval] XlWindowView* RHS);
        [propput, helpcontext(0x000104aa)]
        HRESULT _stdcall View([in] XlWindowView RHS);
    };

    [
      odl,
      uuid(00020892-0001-0000-C000-000000000046),
      helpcontext(0x00020052),
      hidden
    ]
    interface IWindows : IDispatch {
        [propget, helpcontext(0x00010094)]
        HRESULT _stdcall Application([out, retval] Application** RHS);
        [propget, helpcontext(0x00010095)]
        HRESULT _stdcall Creator([out, retval] XlCreator* RHS);
        [propget, helpcontext(0x00010096)]
        HRESULT _stdcall Parent([out, retval] IDispatch** RHS);
        [helpcontext(0x0001027e)]
        HRESULT _stdcall Arrange(
                        [in, optional, defaultvalue(1)] XlArrangeStyle ArrangeStyle, 
                        [in, optional] VARIANT ActiveWorkbook, 
                        [in, optional] VARIANT SyncHorizontal, 
                        [in, optional] VARIANT SyncVertical);
        [propget, helpcontext(0x00010076)]
        HRESULT _stdcall Count([out, retval] long* RHS);
        [propget, helpcontext(0x000100aa)]
        HRESULT _stdcall Item(
                        [in] VARIANT Index, 
                        [out, retval] Window** RHS);
        [propget, helpcontext(0x0000fffc)]
        HRESULT _stdcall _NewEnum([out, retval] IUnknown** RHS);
        [propget, helpcontext(0x00010000)]
        HRESULT _stdcall _Default(
                        [in] VARIANT Index, 
                        [out, retval] Window** RHS);
    };

    [
      odl,
      uuid(00024413-0001-0000-C000-000000000046),
      helpcontext(0x000200a9),
      hidden
    ]
    interface IAppEvents : IDispatch {
        [helpcontext(0x0001061d)]
        HRESULT _stdcall NewWorkbook([in] Workbook* Wb);
        [helpcontext(0x00010616)]
        HRESULT _stdcall SheetSelectionChange(
                        [in] IDispatch* Sh, 
                        [in] Range* Target);
        [helpcontext(0x00010617)]
        HRESULT _stdcall SheetBeforeDoubleClick(
                        [in] IDispatch* Sh, 
                        [in] Range* Target, 
                        [in] VARIANT_BOOL* Cancel);
        [helpcontext(0x00010618)]
        HRESULT _stdcall SheetBeforeRightClick(
                        [in] IDispatch* Sh, 
                        [in] Range* Target, 
                        [in] VARIANT_BOOL* Cancel);
        [helpcontext(0x00010619)]
        HRESULT _stdcall SheetActivate([in] IDispatch* Sh);
        [helpcontext(0x0001061a)]
        HRESULT _stdcall SheetDeactivate([in] IDispatch* Sh);
        [helpcontext(0x0001061b)]
        HRESULT _stdcall SheetCalculate([in] IDispatch* Sh);
        [helpcontext(0x0001061c)]
        HRESULT _stdcall SheetChange(
                        [in] IDispatch* Sh, 
                        [in] Range* Target);
        [helpcontext(0x0001061f)]
        HRESULT _stdcall WorkbookOpen([in] Workbook* Wb);
        [helpcontext(0x00010620)]
        HRESULT _stdcall WorkbookActivate([in] Workbook* Wb);
        [helpcontext(0x00010621)]
        HRESULT _stdcall WorkbookDeactivate([in] Workbook* Wb);
        [helpcontext(0x00010622)]
        HRESULT _stdcall WorkbookBeforeClose(
                        [in] Workbook* Wb, 
                        [in] VARIANT_BOOL* Cancel);
        [helpcontext(0x00010623)]
        HRESULT _stdcall WorkbookBeforeSave(
                        [in] Workbook* Wb, 
                        [in] VARIANT_BOOL SaveAsUI, 
                        [in] VARIANT_BOOL* Cancel);
        [helpcontext(0x00010624)]
        HRESULT _stdcall WorkbookBeforePrint(
                        [in] Workbook* Wb, 
                        [in] VARIANT_BOOL* Cancel);
        [helpcontext(0x00010625)]
        HRESULT _stdcall WorkbookNewSheet(
                        [in] Workbook* Wb, 
                        [in] IDispatch* Sh);
        [helpcontext(0x00010626)]
        HRESULT _stdcall WorkbookAddinInstall([in] Workbook* Wb);
        [helpcontext(0x00010627)]
        HRESULT _stdcall WorkbookAddinUninstall([in] Workbook* Wb);
        [helpcontext(0x00010612)]
        HRESULT _stdcall WindowResize(
                        [in] Workbook* Wb, 
                        [in] Window* Wn);
        [helpcontext(0x00010614)]
        HRESULT _stdcall WindowActivate(
                        [in] Workbook* Wb, 
                        [in] Window* Wn);
        [helpcontext(0x00010615)]
        HRESULT _stdcall WindowDeactivate(
                        [in] Workbook* Wb, 
                        [in] Window* Wn);
    };

    [
      odl,
      uuid(000208D5-0000-0000-C000-000000000046),
      helpcontext(0x00020001),
      dual,
      oleautomation
    ]
    interface _Application : IDispatch {
        [id(0x00000094), propget, helpcontext(0x00010094)]
        HRESULT Application([out, retval] Application** RHS);
        [id(0x00000095), propget, helpcontext(0x00010095)]
        HRESULT Creator([out, retval] XlCreator* RHS);
        [id(0x00000096), propget, helpcontext(0x00010096)]
        HRESULT Parent([out, retval] Application** RHS);
        [id(0x00000131), propget, helpcontext(0x00010131)]
        HRESULT ActiveCell([out, retval] Range** RHS);
        [id(0x000000b7), propget, helpcontext(0x000100b7)]
        HRESULT ActiveChart([out, retval] Chart** RHS);
        [id(0x0000032f), propget, hidden, helpcontext(0x0001032f)]
        HRESULT ActiveDialog([out, retval] DialogSheet** RHS);
        [id(0x000002f6), propget, hidden, helpcontext(0x000102f6)]
        HRESULT ActiveMenuBar([out, retval] MenuBar** RHS);
        [id(0x00000132), propget, helpcontext(0x00010132)]
        HRESULT ActivePrinter(
                        [in, lcid] long lcid, 
                        [out, retval] BSTR* RHS);
        [id(0x00000132), propput, helpcontext(0x00010132)]
        HRESULT ActivePrinter(
                        [in, lcid] long lcid, 
                        [in] BSTR RHS);
        [id(0x00000133), propget, helpcontext(0x00010133)]
        HRESULT ActiveSheet([out, retval] IDispatch** RHS);
        [id(0x000002f7), propget, helpcontext(0x000102f7)]
        HRESULT ActiveWindow([out, retval] Window** RHS);
        [id(0x00000134), propget, helpcontext(0x00010134)]
        HRESULT ActiveWorkbook([out, retval] Workbook** RHS);
        [id(0x00000225), propget, helpcontext(0x00010225)]
        HRESULT AddIns([out, retval] AddIns** RHS);
        [id(0x0000059e), propget, helpcontext(0x0001059e)]
        HRESULT Assistant([out, retval] Assistant** RHS);
        [id(0x00000117), helpcontext(0x00010117)]
        HRESULT Calculate([in, lcid] long lcid);
        [id(0x000000ee), propget, helpcontext(0x000100ee)]
        HRESULT Cells([out, retval] Range** RHS);
        [id(0x00000079), propget, helpcontext(0x00010079)]
        HRESULT Charts([out, retval] Sheets** RHS);
        [id(0x000000f1), propget, helpcontext(0x000100f1)]
        HRESULT Columns([out, retval] Range** RHS);
        [id(0x0000059f), propget, helpcontext(0x0001059f)]
        HRESULT CommandBars([out, retval] CommandBars** RHS);
        [id(0x0000014c), propget, helpcontext(0x0001014c)]
        HRESULT DDEAppReturnCode(
                        [in, lcid] long lcid, 
                        [out, retval] long* RHS);
        [id(0x0000014d), helpcontext(0x0001014d)]
        HRESULT DDEExecute(
                        [in] long Channel, 
                        [in] BSTR String, 
                        [in, lcid] long lcid);
        [id(0x0000014e), helpcontext(0x0001014e)]
        HRESULT DDEInitiate(
                        [in] BSTR App, 
                        [in] BSTR Topic, 
                        [in, lcid] long lcid, 
                        [out, retval] long* RHS);
        [id(0x0000014f), helpcontext(0x0001014f)]
        HRESULT DDEPoke(
                        [in] long Channel, 
                        [in] VARIANT Item, 
                        [in] VARIANT Data, 
                        [in, lcid] long lcid);
        [id(0x00000150), helpcontext(0x00010150)]
        HRESULT DDERequest(
                        [in] long Channel, 
                        [in] BSTR Item, 
                        [in, lcid] long lcid, 
                        [out, retval] VARIANT* RHS);
        [id(0x00000151), helpcontext(0x00010151)]
        HRESULT DDETerminate(
                        [in] long Channel, 
                        [in, lcid] long lcid);
        [id(0x000002fc), propget, hidden, helpcontext(0x000102fc)]
        HRESULT DialogSheets([out, retval] Sheets** RHS);
        [id(0x00000001), helpcontext(0x00010001)]
        HRESULT Evaluate(
                        [in] VARIANT Name, 
                        [in, lcid] long lcid, 
                        [out, retval] VARIANT* RHS);
        [id(0xfffffffb), helpcontext(0x0000fffb)]
        HRESULT _Evaluate(
                        [in] VARIANT Name, 
                        [in, lcid] long lcid, 
                        [out, retval] VARIANT* RHS);
        [id(0x0000015e), helpcontext(0x0001015e)]
        HRESULT ExecuteExcel4Macro(
                        [in] BSTR String, 
                        [in, lcid] long lcid, 
                        [out, retval] VARIANT* RHS);
        [id(0x000002fe), helpcontext(0x000102fe)]
        HRESULT Intersect(
                        [in] Range* Arg1, 
                        [in] Range* Arg2, 
                        [in, optional] VARIANT Arg3, 
                        [in, optional] VARIANT Arg4, 
                        [in, optional] VARIANT Arg5, 
                        [in, optional] VARIANT Arg6, 
                        [in, optional] VARIANT Arg7, 
                        [in, optional] VARIANT Arg8, 
                        [in, optional] VARIANT Arg9, 
                        [in, optional] VARIANT Arg10, 
                        [in, optional] VARIANT Arg11, 
                        [in, optional] VARIANT Arg12, 
                        [in, optional] VARIANT Arg13, 
                        [in, optional] VARIANT Arg14, 
                        [in, optional] VARIANT Arg15, 
                        [in, optional] VARIANT Arg16, 
                        [in, optional] VARIANT Arg17, 
                        [in, optional] VARIANT Arg18, 
                        [in, optional] VARIANT Arg19, 
                        [in, optional] VARIANT Arg20, 
                        [in, optional] VARIANT Arg21, 
                        [in, optional] VARIANT Arg22, 
                        [in, optional] VARIANT Arg23, 
                        [in, optional] VARIANT Arg24, 
                        [in, optional] VARIANT Arg25, 
                        [in, optional] VARIANT Arg26, 
                        [in, optional] VARIANT Arg27, 
                        [in, optional] VARIANT Arg28, 
                        [in, optional] VARIANT Arg29, 
                        [in, optional] VARIANT Arg30, 
                        [in, lcid] long lcid, 
                        [out, retval] Range** RHS);
        [id(0x0000024d), propget, hidden, helpcontext(0x0001024d)]
        HRESULT MenuBars([out, retval] MenuBars** RHS);
        [id(0x00000246), propget, hidden, helpcontext(0x00010246)]
        HRESULT Modules([out, retval] Modules** RHS);
        [id(0x000001ba), propget, helpcontext(0x000101ba)]
        HRESULT Names([out, retval] Names** RHS);
        [id(0x000000c5), propget, helpcontext(0x000100c5)]
        HRESULT Range(
                        [in] VARIANT Cell1, 
                        [in, optional] VARIANT Cell2, 
                        [out, retval] Range** RHS);
        [id(0x00000102), propget, helpcontext(0x00010102)]
        HRESULT Rows([out, retval] Range** RHS);
        [id(0x00000103), helpcontext(0x00010103)]
        HRESULT Run(
                        [in, optional] VARIANT Macro, 
                        [in, optional] VARIANT Arg1, 
                        [in, optional] VARIANT Arg2, 
                        [in, optional] VARIANT Arg3, 
                        [in, optional] VARIANT Arg4, 
                        [in, optional] VARIANT Arg5, 
                        [in, optional] VARIANT Arg6, 
                        [in, optional] VARIANT Arg7, 
                        [in, optional] VARIANT Arg8, 
                        [in, optional] VARIANT Arg9, 
                        [in, optional] VARIANT Arg10, 
                        [in, optional] VARIANT Arg11, 
                        [in, optional] VARIANT Arg12, 
                        [in, optional] VARIANT Arg13, 
                        [in, optional] VARIANT Arg14, 
                        [in, optional] VARIANT Arg15, 
                        [in, optional] VARIANT Arg16, 
                        [in, optional] VARIANT Arg17, 
                        [in, optional] VARIANT Arg18, 
                        [in, optional] VARIANT Arg19, 
                        [in, optional] VARIANT Arg20, 
                        [in, optional] VARIANT Arg21, 
                        [in, optional] VARIANT Arg22, 
                        [in, optional] VARIANT Arg23, 
                        [in, optional] VARIANT Arg24, 
                        [in, optional] VARIANT Arg25, 
                        [in, optional] VARIANT Arg26, 
                        [in, optional] VARIANT Arg27, 
                        [in, optional] VARIANT Arg28, 
                        [in, optional] VARIANT Arg29, 
                        [in, optional] VARIANT Arg30, 
                        [out, retval] VARIANT* RHS);
        [id(0x00000326), helpcontext(0x00010326)]
        HRESULT _Run2(
                        [in, optional] VARIANT Macro, 
                        [in, optional] VARIANT Arg1, 
                        [in, optional] VARIANT Arg2, 
                        [in, optional] VARIANT Arg3, 
                        [in, optional] VARIANT Arg4, 
                        [in, optional] VARIANT Arg5, 
                        [in, optional] VARIANT Arg6, 
                        [in, optional] VARIANT Arg7, 
                        [in, optional] VARIANT Arg8, 
                        [in, optional] VARIANT Arg9, 
                        [in, optional] VARIANT Arg10, 
                        [in, optional] VARIANT Arg11, 
                        [in, optional] VARIANT Arg12, 
                        [in, optional] VARIANT Arg13, 
                        [in, optional] VARIANT Arg14, 
                        [in, optional] VARIANT Arg15, 
                        [in, optional] VARIANT Arg16, 
                        [in, optional] VARIANT Arg17, 
                        [in, optional] VARIANT Arg18, 
                        [in, optional] VARIANT Arg19, 
                        [in, optional] VARIANT Arg20, 
                        [in, optional] VARIANT Arg21, 
                        [in, optional] VARIANT Arg22, 
                        [in, optional] VARIANT Arg23, 
                        [in, optional] VARIANT Arg24, 
                        [in, optional] VARIANT Arg25, 
                        [in, optional] VARIANT Arg26, 
                        [in, optional] VARIANT Arg27, 
                        [in, optional] VARIANT Arg28, 
                        [in, optional] VARIANT Arg29, 
                        [in, optional] VARIANT Arg30, 
                        [in, lcid] long lcid, 
                        [out, retval] VARIANT* RHS);
        [id(0x00000093), propget, helpcontext(0x00010093)]
        HRESULT Selection(
                        [in, lcid] long lcid, 
                        [out, retval] IDispatch** RHS);
        [id(0x0000017f), helpcontext(0x0001017f)]
        HRESULT SendKeys(
                        [in] VARIANT Keys, 
                        [in, optional] VARIANT Wait, 
                        [in, lcid] long lcid);
        [id(0x000001e5), propget, helpcontext(0x000101e5)]
        HRESULT Sheets([out, retval] Sheets** RHS);
        [id(0x00000308), propget, hidden, helpcontext(0x00010308)]
        HRESULT ShortcutMenus(
                        [in] long Index, 
                        [out, retval] Menu** RHS);
        [id(0x0000030a), propget, helpcontext(0x0001030a)]
        HRESULT ThisWorkbook(
                        [in, lcid] long lcid, 
                        [out, retval] Workbook** RHS);
        [id(0x00000228), propget, hidden, helpcontext(0x00010228)]
        HRESULT Toolbars([out, retval] Toolbars** RHS);
        [id(0x0000030b), helpcontext(0x0001030b)]
        HRESULT Union(
                        [in] Range* Arg1, 
                        [in] Range* Arg2, 
                        [in, optional] VARIANT Arg3, 
                        [in, optional] VARIANT Arg4, 
                        [in, optional] VARIANT Arg5, 
                        [in, optional] VARIANT Arg6, 
                        [in, optional] VARIANT Arg7, 
                        [in, optional] VARIANT Arg8, 
                        [in, optional] VARIANT Arg9, 
                        [in, optional] VARIANT Arg10, 
                        [in, optional] VARIANT Arg11, 
                        [in, optional] VARIANT Arg12, 
                        [in, optional] VARIANT Arg13, 
                        [in, optional] VARIANT Arg14, 
                        [in, optional] VARIANT Arg15, 
                        [in, optional] VARIANT Arg16, 
                        [in, optional] VARIANT Arg17, 
                        [in, optional] VARIANT Arg18, 
                        [in, optional] VARIANT Arg19, 
                        [in, optional] VARIANT Arg20, 
                        [in, optional] VARIANT Arg21, 
                        [in, optional] VARIANT Arg22, 
                        [in, optional] VARIANT Arg23, 
                        [in, optional] VARIANT Arg24, 
                        [in, optional] VARIANT Arg25, 
                        [in, optional] VARIANT Arg26, 
                        [in, optional] VARIANT Arg27, 
                        [in, optional] VARIANT Arg28, 
                        [in, optional] VARIANT Arg29, 
                        [in, optional] VARIANT Arg30, 
                        [in, lcid] long lcid, 
                        [out, retval] Range** RHS);
        [id(0x000001ae), propget, helpcontext(0x000101ae)]
        HRESULT Windows([out, retval] Windows** RHS);
        [id(0x0000023c), propget, helpcontext(0x0001023c)]
        HRESULT Workbooks([out, retval] Workbooks** RHS);
        [id(0x000005a0), propget, helpcontext(0x000105a0)]
        HRESULT WorksheetFunction([out, retval] WorksheetFunction** RHS);
        [id(0x000001ee), propget, helpcontext(0x000101ee)]
        HRESULT Worksheets([out, retval] Sheets** RHS);
        [id(0x00000245), propget, helpcontext(0x00010245)]
        HRESULT Excel4IntlMacroSheets([out, retval] Sheets** RHS);
        [id(0x00000243), propget, helpcontext(0x00010243)]
        HRESULT Excel4MacroSheets([out, retval] Sheets** RHS);
        [id(0x00000447), helpcontext(0x00010447)]
        HRESULT ActivateMicrosoftApp(
                        [in] XlMSApplication Index, 
                        [in, lcid] long lcid);
        [id(0x000000d8), helpcontext(0x000100d8)]
        HRESULT AddChartAutoFormat(
                        [in] VARIANT Chart, 
                        [in] BSTR Name, 
                        [in, optional] VARIANT Description, 
                        [in, lcid] long lcid);
        [id(0x0000030c), helpcontext(0x0001030c)]
        HRESULT AddCustomList(
                        [in] VARIANT ListArray, 
                        [in, optional] VARIANT ByRow, 
                        [in, lcid] long lcid);
        [id(0x000003a2), propget, helpcontext(0x000103a2)]
        HRESULT AlertBeforeOverwriting(
                        [in, lcid] long lcid, 
                        [out, retval] VARIANT_BOOL* RHS);
        [id(0x000003a2), propput, helpcontext(0x000103a2)]
        HRESULT AlertBeforeOverwriting(
                        [in, lcid] long lcid, 
                        [in] VARIANT_BOOL RHS);
        [id(0x00000139), propget, helpcontext(0x00010139)]
        HRESULT AltStartupPath(
                        [in, lcid] long lcid, 
                        [out, retval] BSTR* RHS);
        [id(0x00000139), propput, helpcontext(0x00010139)]
        HRESULT AltStartupPath(
                        [in, lcid] long lcid, 
                        [in] BSTR RHS);
        [id(0x000003e0), propget, helpcontext(0x000103e0)]
        HRESULT AskToUpdateLinks(
                        [in, lcid] long lcid, 
                        [out, retval] VARIANT_BOOL* RHS);
        [id(0x000003e0), propput, helpcontext(0x000103e0)]
        HRESULT AskToUpdateLinks(
                        [in, lcid] long lcid, 
                        [in] VARIANT_BOOL RHS);
        [id(0x0000049c), propget, helpcontext(0x0001049c)]
        HRESULT EnableAnimations(
                        [in, lcid] long lcid, 
                        [out, retval] VARIANT_BOOL* RHS);
        [id(0x0000049c), propput, helpcontext(0x0001049c)]
        HRESULT EnableAnimations(
                        [in, lcid] long lcid, 
                        [in] VARIANT_BOOL RHS);
        [id(0x00000479), propget, helpcontext(0x00010479)]
        HRESULT AutoCorrect([out, retval] AutoCorrect** RHS);
        [id(0x0000013a), propget, helpcontext(0x0001013a)]
        HRESULT Build(
                        [in, lcid] long lcid, 
                        [out, retval] long* RHS);
        [id(0x0000013b), propget, helpcontext(0x0001013b)]
        HRESULT CalculateBeforeSave(
                        [in, lcid] long lcid, 
                        [out, retval] VARIANT_BOOL* RHS);
        [id(0x0000013b), propput, helpcontext(0x0001013b)]
        HRESULT CalculateBeforeSave(
                        [in, lcid] long lcid, 
                        [in] VARIANT_BOOL RHS);
        [id(0x0000013c), propget, helpcontext(0x0001013c)]
        HRESULT Calculation(
                        [in, lcid] long lcid, 
                        [out, retval] XlCalculation* RHS);
        [id(0x0000013c), propput, helpcontext(0x0001013c)]
        HRESULT Calculation(
                        [in, lcid] long lcid, 
                        [in] XlCalculation RHS);
        [id(0x0000013d), propget, helpcontext(0x0001013d)]
        HRESULT Caller(
                        [in, optional] VARIANT Index, 
                        [in, lcid] long lcid, 
                        [out, retval] VARIANT* RHS);
        [id(0x0000013e), propget, helpcontext(0x0001013e)]
        HRESULT CanPlaySounds(
                        [in, lcid] long lcid, 
                        [out, retval] VARIANT_BOOL* RHS);
        [id(0x0000013f), propget, helpcontext(0x0001013f)]
        HRESULT CanRecordSounds(
                        [in, lcid] long lcid, 
                        [out, retval] VARIANT_BOOL* RHS);
        [id(0x0000008b), propget, helpcontext(0x0001008b)]
        HRESULT Caption([out, retval] BSTR* RHS);
        [id(0x0000008b), propput, helpcontext(0x0001008b)]
        HRESULT Caption([in] BSTR RHS);
        [id(0x00000140), propget, helpcontext(0x00010140)]
        HRESULT CellDragAndDrop(
                        [in, lcid] long lcid, 
                        [out, retval] VARIANT_BOOL* RHS);
        [id(0x00000140), propput, helpcontext(0x00010140)]
        HRESULT CellDragAndDrop(
                        [in, lcid] long lcid, 
                        [in] VARIANT_BOOL RHS);
        [id(0x0000043e), helpcontext(0x0001043e)]
        HRESULT CentimetersToPoints(
                        [in] double Centimeters, 
                        [in, lcid] long lcid, 
                        [out, retval] double* RHS);
        [id(0x000001f9), helpcontext(0x000101f9)]
        HRESULT CheckSpelling(
                        [in] BSTR Word, 
                        [in, optional] VARIANT CustomDictionary, 
                        [in, optional] VARIANT IgnoreUppercase, 
                        [in, lcid] long lcid, 
                        [out, retval] VARIANT_BOOL* RHS);
        [id(0x00000141), propget, helpcontext(0x00010141)]
        HRESULT ClipboardFormats(
                        [in, optional] VARIANT Index, 
                        [in, lcid] long lcid, 
                        [out, retval] VARIANT* RHS);
        [id(0x00000142), propget, helpcontext(0x00010142)]
        HRESULT DisplayClipboardWindow(
                        [in, lcid] long lcid, 
                        [out, retval] VARIANT_BOOL* RHS);
        [id(0x00000142), propput, helpcontext(0x00010142)]
        HRESULT DisplayClipboardWindow(
                        [in, lcid] long lcid, 
                        [in] VARIANT_BOOL RHS);
        [id(0x0000016d), propget, hidden, helpcontext(0x0001016d)]
        HRESULT ColorButtons([out, retval] VARIANT_BOOL* RHS);
        [id(0x0000016d), propput, hidden, helpcontext(0x0001016d)]
        HRESULT ColorButtons([in] VARIANT_BOOL RHS);
        [id(0x00000143), propget, helpcontext(0x00010143)]
        HRESULT CommandUnderlines(
                        [in, lcid] long lcid, 
                        [out, retval] XlCommandUnderlines* RHS);
        [id(0x00000143), propput, helpcontext(0x00010143)]
        HRESULT CommandUnderlines(
                        [in, lcid] long lcid, 
                        [in] XlCommandUnderlines RHS);
        [id(0x00000144), propget, helpcontext(0x00010144)]
        HRESULT ConstrainNumeric(
                        [in, lcid] long lcid, 
                        [out, retval] VARIANT_BOOL* RHS);
        [id(0x00000144), propput, helpcontext(0x00010144)]
        HRESULT ConstrainNumeric(
                        [in, lcid] long lcid, 
                        [in] VARIANT_BOOL RHS);
        [id(0x00000145), helpcontext(0x00010145)]
        HRESULT ConvertFormula(
                        [in] VARIANT Formula, 
                        [in] XlReferenceStyle FromReferenceStyle, 
                        [in, optional] VARIANT ToReferenceStyle, 
                        [in, optional] VARIANT ToAbsolute, 
                        [in, optional] VARIANT RelativeTo, 
                        [in, lcid] long lcid, 
                        [out, retval] VARIANT* RHS);
        [id(0x000003df), propget, helpcontext(0x000103df)]
        HRESULT CopyObjectsWithCells(
                        [in, lcid] long lcid, 
                        [out, retval] VARIANT_BOOL* RHS);
        [id(0x000003df), propput, helpcontext(0x000103df)]
        HRESULT CopyObjectsWithCells(
                        [in, lcid] long lcid, 
                        [in] VARIANT_BOOL RHS);
        [id(0x00000489), propget, helpcontext(0x00010489)]
        HRESULT Cursor(
                        [in, lcid] long lcid, 
                        [out, retval] XlMousePointer* RHS);
        [id(0x00000489), propput, helpcontext(0x00010489)]
        HRESULT Cursor(
                        [in, lcid] long lcid, 
                        [in] XlMousePointer RHS);
        [id(0x00000313), propget, helpcontext(0x00010313)]
        HRESULT CustomListCount(
                        [in, lcid] long lcid, 
                        [out, retval] long* RHS);
        [id(0x0000014a), propget, helpcontext(0x0001014a)]
        HRESULT CutCopyMode(
                        [in, lcid] long lcid, 
                        [out, retval] XlCutCopyMode* RHS);
        [id(0x0000014a), propput, helpcontext(0x0001014a)]
        HRESULT CutCopyMode(
                        [in, lcid] long lcid, 
                        [in] XlCutCopyMode RHS);
        [id(0x0000014b), propget, helpcontext(0x0001014b)]
        HRESULT DataEntryMode(
                        [in, lcid] long lcid, 
                        [out, retval] long* RHS);
        [id(0x0000014b), propput, helpcontext(0x0001014b)]
        HRESULT DataEntryMode(
                        [in, lcid] long lcid, 
                        [in] long RHS);
        [id(0x000006e7), hidden, helpcontext(0x000106e7)]
        HRESULT Dummy1();
        [id(0x000006e8), hidden, helpcontext(0x000106e8)]
        HRESULT Dummy2();
        [id(0x000006e9), hidden, helpcontext(0x000106e9)]
        HRESULT Dummy3();
        [id(0x000006ea), hidden, helpcontext(0x000106ea)]
        HRESULT Dummy4();
        [id(0x000006eb), hidden, helpcontext(0x000106eb)]
        HRESULT Dummy5();
        [id(0x000006ec), hidden, helpcontext(0x000106ec)]
        HRESULT Dummy6();
        [id(0x000006ed), hidden, helpcontext(0x000106ed)]
        HRESULT Dummy7();
        [id(0x000006ee), hidden, helpcontext(0x000106ee)]
        HRESULT Dummy8();
        [id(0x000006ef), hidden, helpcontext(0x000106ef)]
        HRESULT Dummy9();
        [id(0x000006f0), hidden, helpcontext(0x000106f0)]
        HRESULT Dummy10();
        [id(0x000006f1), hidden, helpcontext(0x000106f1)]
        HRESULT Dummy11();
        [id(00000000), propget, helpcontext(0x00010000)]
        HRESULT _Default([out, retval] BSTR* RHS);
        [id(0x0000040e), propget, helpcontext(0x0001040e)]
        HRESULT DefaultFilePath(
                        [in, lcid] long lcid, 
                        [out, retval] BSTR* RHS);
        [id(0x0000040e), propput, helpcontext(0x0001040e)]
        HRESULT DefaultFilePath(
                        [in, lcid] long lcid, 
                        [in] BSTR RHS);
        [id(0x000000d9), helpcontext(0x000100d9)]
        HRESULT DeleteChartAutoFormat(
                        [in] BSTR Name, 
                        [in, lcid] long lcid);
        [id(0x0000030f), helpcontext(0x0001030f)]
        HRESULT DeleteCustomList(
                        [in] long ListNum, 
                        [in, lcid] long lcid);
        [id(0x000002f9), propget, helpcontext(0x000102f9)]
        HRESULT Dialogs([out, retval] Dialogs** RHS);
        [id(0x00000157), propget, helpcontext(0x00010157)]
        HRESULT DisplayAlerts(
                        [in, lcid] long lcid, 
                        [out, retval] VARIANT_BOOL* RHS);
        [id(0x00000157), propput, helpcontext(0x00010157)]
        HRESULT DisplayAlerts(
                        [in, lcid] long lcid, 
                        [in] VARIANT_BOOL RHS);
        [id(0x00000158), propget, helpcontext(0x00010158)]
        HRESULT DisplayFormulaBar(
                        [in, lcid] long lcid, 
                        [out, retval] VARIANT_BOOL* RHS);
        [id(0x00000158), propput, helpcontext(0x00010158)]
        HRESULT DisplayFormulaBar(
                        [in, lcid] long lcid, 
                        [in] VARIANT_BOOL RHS);
        [id(0x00000425), propget, helpcontext(0x00010425)]
        HRESULT DisplayFullScreen(
                        [in, lcid] long lcid, 
                        [out, retval] VARIANT_BOOL* RHS);
        [id(0x00000425), propput, helpcontext(0x00010425)]
        HRESULT DisplayFullScreen(
                        [in, lcid] long lcid, 
                        [in] VARIANT_BOOL RHS);
        [id(0x00000159), propget, helpcontext(0x00010159)]
        HRESULT DisplayNoteIndicator([out, retval] VARIANT_BOOL* RHS);
        [id(0x00000159), propput, helpcontext(0x00010159)]
        HRESULT DisplayNoteIndicator([in] VARIANT_BOOL RHS);
        [id(0x000004ac), propget, helpcontext(0x000104ac)]
        HRESULT DisplayCommentIndicator([out, retval] XlCommentDisplayMode* RHS);
        [id(0x000004ac), propput, helpcontext(0x000104ac)]
        HRESULT DisplayCommentIndicator([in] XlCommentDisplayMode RHS);
        [id(0x0000039f), propget, helpcontext(0x0001039f)]
        HRESULT DisplayExcel4Menus(
                        [in, lcid] long lcid, 
                        [out, retval] VARIANT_BOOL* RHS);
        [id(0x0000039f), propput, helpcontext(0x0001039f)]
        HRESULT DisplayExcel4Menus(
                        [in, lcid] long lcid, 
                        [in] VARIANT_BOOL RHS);
        [id(0x0000039e), propget, helpcontext(0x0001039e)]
        HRESULT DisplayRecentFiles([out, retval] VARIANT_BOOL* RHS);
        [id(0x0000039e), propput, helpcontext(0x0001039e)]
        HRESULT DisplayRecentFiles([in] VARIANT_BOOL RHS);
        [id(0x0000015a), propget, helpcontext(0x0001015a)]
        HRESULT DisplayScrollBars(
                        [in, lcid] long lcid, 
                        [out, retval] VARIANT_BOOL* RHS);
        [id(0x0000015a), propput, helpcontext(0x0001015a)]
        HRESULT DisplayScrollBars(
                        [in, lcid] long lcid, 
                        [in] VARIANT_BOOL RHS);
        [id(0x0000015b), propget, helpcontext(0x0001015b)]
        HRESULT DisplayStatusBar(
                        [in, lcid] long lcid, 
                        [out, retval] VARIANT_BOOL* RHS);
        [id(0x0000015b), propput, helpcontext(0x0001015b)]
        HRESULT DisplayStatusBar(
                        [in, lcid] long lcid, 
                        [in] VARIANT_BOOL RHS);
        [id(0x0000015d), helpcontext(0x0001015d)]
        HRESULT DoubleClick([in, lcid] long lcid);
        [id(0x000003a1), propget, helpcontext(0x000103a1)]
        HRESULT EditDirectlyInCell(
                        [in, lcid] long lcid, 
                        [out, retval] VARIANT_BOOL* RHS);
        [id(0x000003a1), propput, helpcontext(0x000103a1)]
        HRESULT EditDirectlyInCell(
                        [in, lcid] long lcid, 
                        [in] VARIANT_BOOL RHS);
        [id(0x0000049b), propget, helpcontext(0x0001049b)]
        HRESULT EnableAutoComplete([out, retval] VARIANT_BOOL* RHS);
        [id(0x0000049b), propput, helpcontext(0x0001049b)]
        HRESULT EnableAutoComplete([in] VARIANT_BOOL RHS);
        [id(0x00000448), propget, helpcontext(0x00010448)]
        HRESULT EnableCancelKey(
                        [in, lcid] long lcid, 
                        [out, retval] XlEnableCancelKey* RHS);
        [id(0x00000448), propput, helpcontext(0x00010448)]
        HRESULT EnableCancelKey(
                        [in, lcid] long lcid, 
                        [in] XlEnableCancelKey RHS);
        [id(0x000004ad), propget, helpcontext(0x000104ad)]
        HRESULT EnableSound([out, retval] VARIANT_BOOL* RHS);
        [id(0x000004ad), propput, helpcontext(0x000104ad)]
        HRESULT EnableSound([in] VARIANT_BOOL RHS);
        [id(0x00000428), propget, hidden, helpcontext(0x00010428)]
        HRESULT EnableTipWizard(
                        [in, lcid] long lcid, 
                        [out, retval] VARIANT_BOOL* RHS);
        [id(0x00000428), propput, hidden, helpcontext(0x00010428)]
        HRESULT EnableTipWizard(
                        [in, lcid] long lcid, 
                        [in] VARIANT_BOOL RHS);
        [id(0x000003a3), propget, helpcontext(0x000103a3)]
        HRESULT FileConverters(
                        [in, optional] VARIANT Index1, 
                        [in, optional] VARIANT Index2, 
                        [in, lcid] long lcid, 
                        [out, retval] VARIANT* RHS);
        [id(0x000004b0), propget, helpcontext(0x000104b0)]
        HRESULT FileSearch([out, retval] FileSearch** RHS);
        [id(0x000004b1), propget, helpcontext(0x000104b1)]
        HRESULT FileFind([out, retval] IFind** RHS);
        [id(0x0000042c), helpcontext(0x0001042c)]
        HRESULT FindFile([in, lcid] long lcid);
        [id(0x0000015f), propget, helpcontext(0x0001015f)]
        HRESULT FixedDecimal(
                        [in, lcid] long lcid, 
                        [out, retval] VARIANT_BOOL* RHS);
        [id(0x0000015f), propput, helpcontext(0x0001015f)]
        HRESULT FixedDecimal(
                        [in, lcid] long lcid, 
                        [in] VARIANT_BOOL RHS);
        [id(0x00000160), propget, helpcontext(0x00010160)]
        HRESULT FixedDecimalPlaces(
                        [in, lcid] long lcid, 
                        [out, retval] long* RHS);
        [id(0x00000160), propput, helpcontext(0x00010160)]
        HRESULT FixedDecimalPlaces(
                        [in, lcid] long lcid, 
                        [in] long RHS);
        [id(0x00000312), helpcontext(0x00010312)]
        HRESULT GetCustomListContents(
                        [in] long ListNum, 
                        [in, lcid] long lcid, 
                        [out, retval] VARIANT* RHS);
        [id(0x00000311), helpcontext(0x00010311)]
        HRESULT GetCustomListNum(
                        [in] VARIANT ListArray, 
                        [in, lcid] long lcid, 
                        [out, retval] long* RHS);
        [id(0x00000433), helpcontext(0x00010433)]
        HRESULT GetOpenFilename(
                        [in, optional] VARIANT FileFilter, 
                        [in, optional] VARIANT FilterIndex, 
                        [in, optional] VARIANT Title, 
                        [in, optional] VARIANT ButtonText, 
                        [in, optional] VARIANT MultiSelect, 
                        [in, lcid] long lcid, 
                        [out, retval] VARIANT* RHS);
        [id(0x00000434), helpcontext(0x00010434)]
        HRESULT GetSaveAsFilename(
                        [in, optional] VARIANT InitialFilename, 
                        [in, optional] VARIANT FileFilter, 
                        [in, optional] VARIANT FilterIndex, 
                        [in, optional] VARIANT Title, 
                        [in, optional] VARIANT ButtonText, 
                        [in, lcid] long lcid, 
                        [out, retval] VARIANT* RHS);
        [id(0x000001db), helpcontext(0x000101db)]
        HRESULT Goto(
                        [in, optional] VARIANT Reference, 
                        [in, optional] VARIANT Scroll, 
                        [in, lcid] long lcid);
        [id(0x0000007b), propget, helpcontext(0x0001007b)]
        HRESULT Height(
                        [in, lcid] long lcid, 
                        [out, retval] double* RHS);
        [id(0x0000007b), propput, helpcontext(0x0001007b)]
        HRESULT Height(
                        [in, lcid] long lcid, 
                        [in] double RHS);
        [id(0x00000162), helpcontext(0x00010162)]
        HRESULT Help(
                        [in, optional] VARIANT HelpFile, 
                        [in, optional] VARIANT HelpContextID, 
                        [in, lcid] long lcid);
        [id(0x00000164), propget, helpcontext(0x00010164)]
        HRESULT IgnoreRemoteRequests(
                        [in, lcid] long lcid, 
                        [out, retval] VARIANT_BOOL* RHS);
        [id(0x00000164), propput, helpcontext(0x00010164)]
        HRESULT IgnoreRemoteRequests(
                        [in, lcid] long lcid, 
                        [in] VARIANT_BOOL RHS);
        [id(0x0000043f), helpcontext(0x0001043f)]
        HRESULT InchesToPoints(
                        [in] double Inches, 
                        [in, lcid] long lcid, 
                        [out, retval] double* RHS);
        [id(0x00000165), helpcontext(0x00010165)]
        HRESULT InputBox(
                        [in] BSTR Prompt, 
                        [in, optional] VARIANT Title, 
                        [in, optional] VARIANT Default, 
                        [in, optional] VARIANT Left, 
                        [in, optional] VARIANT Top, 
                        [in, optional] VARIANT HelpFile, 
                        [in, optional] VARIANT HelpContextID, 
                        [in, optional] VARIANT Type, 
                        [in, lcid] long lcid, 
                        [out, retval] VARIANT* RHS);
        [id(0x00000169), propget, helpcontext(0x00010169)]
        HRESULT Interactive(
                        [in, lcid] long lcid, 
                        [out, retval] VARIANT_BOOL* RHS);
        [id(0x00000169), propput, helpcontext(0x00010169)]
        HRESULT Interactive(
                        [in, lcid] long lcid, 
                        [in] VARIANT_BOOL RHS);
        [id(0x0000016a), propget, helpcontext(0x0001016a)]
        HRESULT International(
                        [in, optional] VARIANT Index, 
                        [in, lcid] long lcid, 
                        [out, retval] VARIANT* RHS);
        [id(0x0000016b), propget, helpcontext(0x0001016b)]
        HRESULT Iteration(
                        [in, lcid] long lcid, 
                        [out, retval] VARIANT_BOOL* RHS);
        [id(0x0000016b), propput, helpcontext(0x0001016b)]
        HRESULT Iteration(
                        [in, lcid] long lcid, 
                        [in] VARIANT_BOOL RHS);
        [id(0x0000016c), propget, hidden, helpcontext(0x0001016c)]
        HRESULT LargeButtons([out, retval] VARIANT_BOOL* RHS);
        [id(0x0000016c), propput, hidden, helpcontext(0x0001016c)]
        HRESULT LargeButtons([in] VARIANT_BOOL RHS);
        [id(0x0000007f), propget, helpcontext(0x0001007f)]
        HRESULT Left(
                        [in, lcid] long lcid, 
                        [out, retval] double* RHS);
        [id(0x0000007f), propput, helpcontext(0x0001007f)]
        HRESULT Left(
                        [in, lcid] long lcid, 
                        [in] double RHS);
        [id(0x0000016e), propget, helpcontext(0x0001016e)]
        HRESULT LibraryPath(
                        [in, lcid] long lcid, 
                        [out, retval] BSTR* RHS);
        [id(0x0000046f), helpcontext(0x0001046f)]
        HRESULT MacroOptions(
                        [in, optional] VARIANT Macro, 
                        [in, optional] VARIANT Description, 
                        [in, optional] VARIANT HasMenu, 
                        [in, optional] VARIANT MenuText, 
                        [in, optional] VARIANT HasShortcutKey, 
                        [in, optional] VARIANT ShortcutKey, 
                        [in, optional] VARIANT Category, 
                        [in, optional] VARIANT StatusBar, 
                        [in, optional] VARIANT HelpContextID, 
                        [in, optional] VARIANT HelpFile, 
                        [in, lcid] long lcid);
        [id(0x000003b1), helpcontext(0x000103b1)]
        HRESULT MailLogoff([in, lcid] long lcid);
        [id(0x000003af), helpcontext(0x000103af)]
        HRESULT MailLogon(
                        [in, optional] VARIANT Name, 
                        [in, optional] VARIANT Password, 
                        [in, optional] VARIANT DownloadNewMail, 
                        [in, lcid] long lcid);
        [id(0x000003ae), propget, helpcontext(0x000103ae)]
        HRESULT MailSession(
                        [in, lcid] long lcid, 
                        [out, retval] VARIANT* RHS);
        [id(0x000003cb), propget, helpcontext(0x000103cb)]
        HRESULT MailSystem(
                        [in, lcid] long lcid, 
                        [out, retval] XlMailSystem* RHS);
        [id(0x0000016f), propget, helpcontext(0x0001016f)]
        HRESULT MathCoprocessorAvailable(
                        [in, lcid] long lcid, 
                        [out, retval] VARIANT_BOOL* RHS);
        [id(0x00000170), propget, helpcontext(0x00010170)]
        HRESULT MaxChange(
                        [in, lcid] long lcid, 
                        [out, retval] double* RHS);
        [id(0x00000170), propput, helpcontext(0x00010170)]
        HRESULT MaxChange(
                        [in, lcid] long lcid, 
                        [in] double RHS);
        [id(0x00000171), propget, helpcontext(0x00010171)]
        HRESULT MaxIterations(
                        [in, lcid] long lcid, 
                        [out, retval] long* RHS);
        [id(0x00000171), propput, helpcontext(0x00010171)]
        HRESULT MaxIterations(
                        [in, lcid] long lcid, 
                        [in] long RHS);
        [id(0x00000172), propget, helpcontext(0x00010172)]
        HRESULT MemoryFree(
                        [in, lcid] long lcid, 
                        [out, retval] long* RHS);
        [id(0x00000173), propget, helpcontext(0x00010173)]
        HRESULT MemoryTotal(
                        [in, lcid] long lcid, 
                        [out, retval] long* RHS);
        [id(0x00000174), propget, helpcontext(0x00010174)]
        HRESULT MemoryUsed(
                        [in, lcid] long lcid, 
                        [out, retval] long* RHS);
        [id(0x00000175), propget, helpcontext(0x00010175)]
        HRESULT MouseAvailable(
                        [in, lcid] long lcid, 
                        [out, retval] VARIANT_BOOL* RHS);
        [id(0x00000176), propget, helpcontext(0x00010176)]
        HRESULT MoveAfterReturn(
                        [in, lcid] long lcid, 
                        [out, retval] VARIANT_BOOL* RHS);
        [id(0x00000176), propput, helpcontext(0x00010176)]
        HRESULT MoveAfterReturn(
                        [in, lcid] long lcid, 
                        [in] VARIANT_BOOL RHS);
        [id(0x00000478), propget, helpcontext(0x00010478)]
        HRESULT MoveAfterReturnDirection(
                        [in, lcid] long lcid, 
                        [out, retval] XlDirection* RHS);
        [id(0x00000478), propput, helpcontext(0x00010478)]
        HRESULT MoveAfterReturnDirection(
                        [in, lcid] long lcid, 
                        [in] XlDirection RHS);
        [id(0x000004b2), propget, helpcontext(0x000104b2)]
        HRESULT RecentFiles([out, retval] RecentFiles** RHS);
        [id(0x0000006e), propget, helpcontext(0x0001006e)]
        HRESULT Name([out, retval] BSTR* RHS);
        [id(0x000003cc), helpcontext(0x000103cc)]
        HRESULT NextLetter(
                        [in, lcid] long lcid, 
                        [out, retval] Workbook** RHS);
        [id(0x00000184), propget, helpcontext(0x00010184)]
        HRESULT NetworkTemplatesPath(
                        [in, lcid] long lcid, 
                        [out, retval] BSTR* RHS);
        [id(0x000004b3), propget, helpcontext(0x000104b3)]
        HRESULT ODBCErrors([out, retval] ODBCErrors** RHS);
        [id(0x000004b4), propget, helpcontext(0x000104b4)]
        HRESULT ODBCTimeout([out, retval] long* RHS);
        [id(0x000004b4), propput, helpcontext(0x000104b4)]
        HRESULT ODBCTimeout([in] long RHS);
        [id(0x00000271), propget, hidden, helpcontext(0x00010271)]
        HRESULT OnCalculate(
                        [in, lcid] long lcid, 
                        [out, retval] BSTR* RHS);
        [id(0x00000271), propput, hidden, helpcontext(0x00010271)]
        HRESULT OnCalculate(
                        [in, lcid] long lcid, 
                        [in] BSTR RHS);
        [id(0x00000275), propget, hidden, helpcontext(0x00010275)]
        HRESULT OnData(
                        [in, lcid] long lcid, 
                        [out, retval] BSTR* RHS);
        [id(0x00000275), propput, hidden, helpcontext(0x00010275)]
        HRESULT OnData(
                        [in, lcid] long lcid, 
                        [in] BSTR RHS);
        [id(0x00000274), propget, hidden, helpcontext(0x00010274)]
        HRESULT OnDoubleClick(
                        [in, lcid] long lcid, 
                        [out, retval] BSTR* RHS);
        [id(0x00000274), propput, hidden, helpcontext(0x00010274)]
        HRESULT OnDoubleClick(
                        [in, lcid] long lcid, 
                        [in] BSTR RHS);
        [id(0x00000273), propget, hidden, helpcontext(0x00010273)]
        HRESULT OnEntry(
                        [in, lcid] long lcid, 
                        [out, retval] BSTR* RHS);
        [id(0x00000273), propput, hidden, helpcontext(0x00010273)]
        HRESULT OnEntry(
                        [in, lcid] long lcid, 
                        [in] BSTR RHS);
        [id(0x00000272), helpcontext(0x00010272)]
        HRESULT OnKey(
                        [in] BSTR Key, 
                        [in, optional] VARIANT Procedure, 
                        [in, lcid] long lcid);
        [id(0x00000301), helpcontext(0x00010301)]
        HRESULT OnRepeat(
                        [in] BSTR Text, 
                        [in] BSTR Procedure, 
                        [in, lcid] long lcid);
        [id(0x00000407), propget, hidden, helpcontext(0x00010407)]
        HRESULT OnSheetActivate(
                        [in, lcid] long lcid, 
                        [out, retval] BSTR* RHS);
        [id(0x00000407), propput, hidden, helpcontext(0x00010407)]
        HRESULT OnSheetActivate(
                        [in, lcid] long lcid, 
                        [in] BSTR RHS);
        [id(0x00000439), propget, hidden, helpcontext(0x00010439)]
        HRESULT OnSheetDeactivate(
                        [in, lcid] long lcid, 
                        [out, retval] BSTR* RHS);
        [id(0x00000439), propput, hidden, helpcontext(0x00010439)]
        HRESULT OnSheetDeactivate(
                        [in, lcid] long lcid, 
                        [in] BSTR RHS);
        [id(0x00000270), helpcontext(0x00010270)]
        HRESULT OnTime(
                        [in] VARIANT EarliestTime, 
                        [in] BSTR Procedure, 
                        [in, optional] VARIANT LatestTime, 
                        [in, optional] VARIANT Schedule, 
                        [in, lcid] long lcid);
        [id(0x00000302), helpcontext(0x00010302)]
        HRESULT OnUndo(
                        [in] BSTR Text, 
                        [in] BSTR Procedure, 
                        [in, lcid] long lcid);
        [id(0x0000026f), propget, helpcontext(0x0001026f)]
        HRESULT OnWindow(
                        [in, lcid] long lcid, 
                        [out, retval] BSTR* RHS);
        [id(0x0000026f), propput, helpcontext(0x0001026f)]
        HRESULT OnWindow(
                        [in, lcid] long lcid, 
                        [in] BSTR RHS);
        [id(0x00000177), propget, helpcontext(0x00010177)]
        HRESULT OperatingSystem(
                        [in, lcid] long lcid, 
                        [out, retval] BSTR* RHS);
        [id(0x00000178), propget, helpcontext(0x00010178)]
        HRESULT OrganizationName(
                        [in, lcid] long lcid, 
                        [out, retval] BSTR* RHS);
        [id(0x00000123), propget, helpcontext(0x00010123)]
        HRESULT Path(
                        [in, lcid] long lcid, 
                        [out, retval] BSTR* RHS);
        [id(0x00000179), propget, helpcontext(0x00010179)]
        HRESULT PathSeparator(
                        [in, lcid] long lcid, 
                        [out, retval] BSTR* RHS);
        [id(0x0000017a), propget, helpcontext(0x0001017a)]
        HRESULT PreviousSelections(
                        [in, optional] VARIANT Index, 
                        [in, lcid] long lcid, 
                        [out, retval] VARIANT* RHS);
        [id(0x000004b5), propget, helpcontext(0x000104b5)]
        HRESULT PivotTableSelection([out, retval] VARIANT_BOOL* RHS);
        [id(0x000004b5), propput, helpcontext(0x000104b5)]
        HRESULT PivotTableSelection([in] VARIANT_BOOL RHS);
        [id(0x00000426), propget, helpcontext(0x00010426)]
        HRESULT PromptForSummaryInfo(
                        [in, lcid] long lcid, 
                        [out, retval] VARIANT_BOOL* RHS);
        [id(0x00000426), propput, helpcontext(0x00010426)]
        HRESULT PromptForSummaryInfo(
                        [in, lcid] long lcid, 
                        [in] VARIANT_BOOL RHS);
        [id(0x0000012e), helpcontext(0x0001012e)]
        HRESULT Quit();
        [id(0x00000305), helpcontext(0x00010305)]
        HRESULT RecordMacro(
                        [in, optional] VARIANT BasicCode, 
                        [in, optional] VARIANT XlmCode, 
                        [in, lcid] long lcid);
        [id(0x0000017b), propget, helpcontext(0x0001017b)]
        HRESULT RecordRelative(
                        [in, lcid] long lcid, 
                        [out, retval] VARIANT_BOOL* RHS);
        [id(0x0000017c), propget, helpcontext(0x0001017c)]
        HRESULT ReferenceStyle(
                        [in, lcid] long lcid, 
                        [out, retval] XlReferenceStyle* RHS);
        [id(0x0000017c), propput, helpcontext(0x0001017c)]
        HRESULT ReferenceStyle(
                        [in, lcid] long lcid, 
                        [in] XlReferenceStyle RHS);
        [id(0x00000307), propget, helpcontext(0x00010307)]
        HRESULT RegisteredFunctions(
                        [in, optional] VARIANT Index1, 
                        [in, optional] VARIANT Index2, 
                        [in, lcid] long lcid, 
                        [out, retval] VARIANT* RHS);
        [id(0x0000001e), helpcontext(0x0001001e)]
        HRESULT RegisterXLL(
                        [in] BSTR Filename, 
                        [in, lcid] long lcid, 
                        [out, retval] VARIANT_BOOL* RHS);
        [id(0x0000012d), helpcontext(0x0001012d)]
        HRESULT Repeat([in, lcid] long lcid);
        [id(0x000003a0), hidden, helpcontext(0x000103a0)]
        HRESULT ResetTipWizard([in, lcid] long lcid);
        [id(0x000004b6), propget, helpcontext(0x000104b6)]
        HRESULT RollZoom([out, retval] VARIANT_BOOL* RHS);
        [id(0x000004b6), propput, helpcontext(0x000104b6)]
        HRESULT RollZoom([in] VARIANT_BOOL RHS);
        [id(0x0000011b), hidden, helpcontext(0x0001011b)]
        HRESULT Save(
                        [in, optional] VARIANT Filename, 
                        [in, lcid] long lcid);
        [id(0x000000d4), helpcontext(0x000100d4)]
        HRESULT SaveWorkspace(
                        [in, optional] VARIANT Filename, 
                        [in, lcid] long lcid);
        [id(0x0000017e), propget, helpcontext(0x0001017e)]
        HRESULT ScreenUpdating(
                        [in, lcid] long lcid, 
                        [out, retval] VARIANT_BOOL* RHS);
        [id(0x0000017e), propput, helpcontext(0x0001017e)]
        HRESULT ScreenUpdating(
                        [in, lcid] long lcid, 
                        [in] VARIANT_BOOL RHS);
        [id(0x000000db), helpcontext(0x000100db)]
        HRESULT SetDefaultChart(
                        [in, optional] VARIANT FormatName, 
                        [in, optional] VARIANT Gallery);
        [id(0x000003e1), propget, helpcontext(0x000103e1)]
        HRESULT SheetsInNewWorkbook(
                        [in, lcid] long lcid, 
                        [out, retval] long* RHS);
        [id(0x000003e1), propput, helpcontext(0x000103e1)]
        HRESULT SheetsInNewWorkbook(
                        [in, lcid] long lcid, 
                        [in] long RHS);
        [id(0x000004b7), propget, helpcontext(0x000104b7)]
        HRESULT ShowChartTipNames([out, retval] VARIANT_BOOL* RHS);
        [id(0x000004b7), propput, helpcontext(0x000104b7)]
        HRESULT ShowChartTipNames([in] VARIANT_BOOL RHS);
        [id(0x000004b8), propget, helpcontext(0x000104b8)]
        HRESULT ShowChartTipValues([out, retval] VARIANT_BOOL* RHS);
        [id(0x000004b8), propput, helpcontext(0x000104b8)]
        HRESULT ShowChartTipValues([in] VARIANT_BOOL RHS);
        [id(0x0000039c), propget, helpcontext(0x0001039c)]
        HRESULT StandardFont(
                        [in, lcid] long lcid, 
                        [out, retval] BSTR* RHS);
        [id(0x0000039c), propput, helpcontext(0x0001039c)]
        HRESULT StandardFont(
                        [in, lcid] long lcid, 
                        [in] BSTR RHS);
        [id(0x0000039d), propget, helpcontext(0x0001039d)]
        HRESULT StandardFontSize(
                        [in, lcid] long lcid, 
                        [out, retval] double* RHS);
        [id(0x0000039d), propput, helpcontext(0x0001039d)]
        HRESULT StandardFontSize(
                        [in, lcid] long lcid, 
                        [in] double RHS);
        [id(0x00000181), propget, helpcontext(0x00010181)]
        HRESULT StartupPath(
                        [in, lcid] long lcid, 
                        [out, retval] BSTR* RHS);
        [id(0x00000182), propget, helpcontext(0x00010182)]
        HRESULT StatusBar(
                        [in, lcid] long lcid, 
                        [out, retval] VARIANT* RHS);
        [id(0x00000182), propput, helpcontext(0x00010182)]
        HRESULT StatusBar(
                        [in, lcid] long lcid, 
                        [in] VARIANT RHS);
        [id(0x0000017d), propget, helpcontext(0x0001017d)]
        HRESULT TemplatesPath(
                        [in, lcid] long lcid, 
                        [out, retval] BSTR* RHS);
        [id(0x00000183), propget, helpcontext(0x00010183)]
        HRESULT ShowToolTips([out, retval] VARIANT_BOOL* RHS);
        [id(0x00000183), propput, helpcontext(0x00010183)]
        HRESULT ShowToolTips([in] VARIANT_BOOL RHS);
        [id(0x0000007e), propget, helpcontext(0x0001007e)]
        HRESULT Top(
                        [in, lcid] long lcid, 
                        [out, retval] double* RHS);
        [id(0x0000007e), propput, helpcontext(0x0001007e)]
        HRESULT Top(
                        [in, lcid] long lcid, 
                        [in] double RHS);
        [id(0x000004b9), propget, helpcontext(0x000104b9)]
        HRESULT DefaultSaveFormat([out, retval] XlFileFormat* RHS);
        [id(0x000004b9), propput, helpcontext(0x000104b9)]
        HRESULT DefaultSaveFormat([in] XlFileFormat RHS);
        [id(0x00000136), propget, helpcontext(0x00010136)]
        HRESULT TransitionMenuKey(
                        [in, lcid] long lcid, 
                        [out, retval] BSTR* RHS);
        [id(0x00000136), propput, helpcontext(0x00010136)]
        HRESULT TransitionMenuKey(
                        [in, lcid] long lcid, 
                        [in] BSTR RHS);
        [id(0x00000137), propget, helpcontext(0x00010137)]
        HRESULT TransitionMenuKeyAction(
                        [in, lcid] long lcid, 
                        [out, retval] long* RHS);
        [id(0x00000137), propput, helpcontext(0x00010137)]
        HRESULT TransitionMenuKeyAction(
                        [in, lcid] long lcid, 
                        [in] long RHS);
        [id(0x00000138), propget, helpcontext(0x00010138)]
        HRESULT TransitionNavigKeys(
                        [in, lcid] long lcid, 
                        [out, retval] VARIANT_BOOL* RHS);
        [id(0x00000138), propput, helpcontext(0x00010138)]
        HRESULT TransitionNavigKeys(
                        [in, lcid] long lcid, 
                        [in] VARIANT_BOOL RHS);
        [id(0x0000012f), helpcontext(0x0001012f)]
        HRESULT Undo([in, lcid] long lcid);
        [id(0x00000185), propget, helpcontext(0x00010185)]
        HRESULT UsableHeight(
                        [in, lcid] long lcid, 
                        [out, retval] double* RHS);
        [id(0x00000186), propget, helpcontext(0x00010186)]
        HRESULT UsableWidth(
                        [in, lcid] long lcid, 
                        [out, retval] double* RHS);
        [id(0x000004ba), propget, helpcontext(0x000104ba)]
        HRESULT UserControl([out, retval] VARIANT_BOOL* RHS);
        [id(0x000004ba), propput, helpcontext(0x000104ba)]
        HRESULT UserControl([in] VARIANT_BOOL RHS);
        [id(0x00000187), propget, helpcontext(0x00010187)]
        HRESULT UserName(
                        [in, lcid] long lcid, 
                        [out, retval] BSTR* RHS);
        [id(0x00000187), propput, helpcontext(0x00010187)]
        HRESULT UserName(
                        [in, lcid] long lcid, 
                        [in] BSTR RHS);
        [id(0x00000006), propget, helpcontext(0x00010006)]
        HRESULT Value([out, retval] BSTR* RHS);
        [id(0x000004bb), propget, helpcontext(0x000104bb)]
        HRESULT VBE([out, retval] VBE** RHS);
        [id(0x00000188), propget, helpcontext(0x00010188)]
        HRESULT Version(
                        [in, lcid] long lcid, 
                        [out, retval] BSTR* RHS);
        [id(0x0000022e), propget, helpcontext(0x0001022e)]
        HRESULT Visible(
                        [in, lcid] long lcid, 
                        [out, retval] VARIANT_BOOL* RHS);
        [id(0x0000022e), propput, helpcontext(0x0001022e)]
        HRESULT Visible(
                        [in, lcid] long lcid, 
                        [in] VARIANT_BOOL RHS);
        [id(0x00000314), helpcontext(0x00010314)]
        HRESULT Volatile(
                        [in, optional] VARIANT Volatile, 
                        [in, lcid] long lcid);
        [id(0x00000189), helpcontext(0x00010189)]
        HRESULT Wait(
                        [in] VARIANT Time, 
                        [in, lcid] long lcid);
        [id(0x0000007a), propget, helpcontext(0x0001007a)]
        HRESULT Width(
                        [in, lcid] long lcid, 
                        [out, retval] double* RHS);
        [id(0x0000007a), propput, helpcontext(0x0001007a)]
        HRESULT Width(
                        [in, lcid] long lcid, 
                        [in] double RHS);
        [id(0x0000018b), propget, helpcontext(0x0001018b)]
        HRESULT WindowsForPens(
                        [in, lcid] long lcid, 
                        [out, retval] VARIANT_BOOL* RHS);
        [id(0x0000018c), propget, helpcontext(0x0001018c)]
        HRESULT WindowState(
                        [in, lcid] long lcid, 
                        [out, retval] XlWindowState* RHS);
        [id(0x0000018c), propput, helpcontext(0x0001018c)]
        HRESULT WindowState(
                        [in, lcid] long lcid, 
                        [in] XlWindowState RHS);
        [id(0x00000002), propget, helpcontext(0x00010002)]
        HRESULT UILanguage(
                        [in, lcid] long lcid, 
                        [out, retval] long* RHS);
        [id(0x00000002), propput, helpcontext(0x00010002)]
        HRESULT UILanguage(
                        [in, lcid] long lcid, 
                        [in] long RHS);
        [id(0x000000e5), propget, helpcontext(0x000100e5)]
        HRESULT DefaultSheetDirection(
                        [in, lcid] long lcid, 
                        [out, retval] long* RHS);
        [id(0x000000e5), propput, helpcontext(0x000100e5)]
        HRESULT DefaultSheetDirection(
                        [in, lcid] long lcid, 
                        [in] long RHS);
        [id(0x000000e8), propget, helpcontext(0x000100e8)]
        HRESULT CursorMovement(
                        [in, lcid] long lcid, 
                        [out, retval] long* RHS);
        [id(0x000000e8), propput, helpcontext(0x000100e8)]
        HRESULT CursorMovement(
                        [in, lcid] long lcid, 
                        [in] long RHS);
        [id(0x000000e9), propget, helpcontext(0x000100e9)]
        HRESULT ControlCharacters(
                        [in, lcid] long lcid, 
                        [out, retval] long* RHS);
        [id(0x000000e9), propput, helpcontext(0x000100e9)]
        HRESULT ControlCharacters(
                        [in, lcid] long lcid, 
                        [in] long RHS);
        [id(0x000000a9), hidden, helpcontext(0x000100a9)]
        HRESULT _WSFunction(
                        [in, optional] VARIANT Arg1, 
                        [in, optional] VARIANT Arg2, 
                        [in, optional] VARIANT Arg3, 
                        [in, optional] VARIANT Arg4, 
                        [in, optional] VARIANT Arg5, 
                        [in, optional] VARIANT Arg6, 
                        [in, optional] VARIANT Arg7, 
                        [in, optional] VARIANT Arg8, 
                        [in, optional] VARIANT Arg9, 
                        [in, optional] VARIANT Arg10, 
                        [in, optional] VARIANT Arg11, 
                        [in, optional] VARIANT Arg12, 
                        [in, optional] VARIANT Arg13, 
                        [in, optional] VARIANT Arg14, 
                        [in, optional] VARIANT Arg15, 
                        [in, optional] VARIANT Arg16, 
                        [in, optional] VARIANT Arg17, 
                        [in, optional] VARIANT Arg18, 
                        [in, optional] VARIANT Arg19, 
                        [in, optional] VARIANT Arg20, 
                        [in, optional] VARIANT Arg21, 
                        [in, optional] VARIANT Arg22, 
                        [in, optional] VARIANT Arg23, 
                        [in, optional] VARIANT Arg24, 
                        [in, optional] VARIANT Arg25, 
                        [in, optional] VARIANT Arg26, 
                        [in, optional] VARIANT Arg27, 
                        [in, optional] VARIANT Arg28, 
                        [in, optional] VARIANT Arg29, 
                        [in, optional] VARIANT Arg30, 
                        [in, lcid] long lcid, 
                        [out, retval] VARIANT* RHS);
        [id(0x000004bc), propget, helpcontext(0x000104bc)]
        HRESULT EnableEvents([out, retval] VARIANT_BOOL* RHS);
        [id(0x000004bc), propput, helpcontext(0x000104bc)]
        HRESULT EnableEvents([in] VARIANT_BOOL RHS);
        [id(0x000004bd), propget, hidden, helpcontext(0x000104bd)]
        HRESULT DisplayInfoWindow([out, retval] VARIANT_BOOL* RHS);
        [id(0x000004bd), propput, hidden, helpcontext(0x000104bd)]
        HRESULT DisplayInfoWindow([in] VARIANT_BOOL RHS);
    };
