import "Excel11.Idl";

    [
      odl,
      uuid(000208AA-0001-0000-C000-000000000046),
      helpcontext(0x0002006a),
      hidden
    ]
    interface IRoutingSlip : IDispatch {
        [propget, helpcontext(0x00010094)]
        HRESULT _stdcall Application([out, retval] Application** RHS);
        [propget, helpcontext(0x00010095)]
        HRESULT _stdcall Creator([out, retval] XlCreator* RHS);
        [propget, helpcontext(0x00010096)]
        HRESULT _stdcall Parent([out, retval] IDispatch** RHS);
        [propget, helpcontext(0x000103bb)]
        HRESULT _stdcall Delivery([out, retval] XlRoutingSlipDelivery* RHS);
        [propput, helpcontext(0x000103bb)]
        HRESULT _stdcall Delivery([in] XlRoutingSlipDelivery RHS);
        [propget, helpcontext(0x000103ba)]
        HRESULT _stdcall Message([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x000103ba)]
        HRESULT _stdcall Message([in] VARIANT RHS);
        [helpcontext(0x000103b8)]
        HRESULT _stdcall Recipients(
                        [in, optional] VARIANT Index, 
                        [out, retval] VARIANT* RHS);
        [helpcontext(0x0001022b)]
        HRESULT _stdcall Reset();
        [propget, helpcontext(0x000103bc)]
        HRESULT _stdcall ReturnWhenDone([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x000103bc)]
        HRESULT _stdcall ReturnWhenDone([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x000103be)]
        HRESULT _stdcall Status([out, retval] XlRoutingSlipStatus* RHS);
        [propget, helpcontext(0x000103b9)]
        HRESULT _stdcall Subject([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x000103b9)]
        HRESULT _stdcall Subject([in] VARIANT RHS);
        [propget, helpcontext(0x000103bd)]
        HRESULT _stdcall TrackStatus([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x000103bd)]
        HRESULT _stdcall TrackStatus([in] VARIANT_BOOL RHS);
    };

    [
      odl,
      uuid(000208AB-0001-0000-C000-000000000046),
      helpcontext(0x0002006b),
      hidden
    ]
    interface IOutline : IDispatch {
        [propget, helpcontext(0x00010094)]
        HRESULT _stdcall Application([out, retval] Application** RHS);
        [propget, helpcontext(0x00010095)]
        HRESULT _stdcall Creator([out, retval] XlCreator* RHS);
        [propget, helpcontext(0x00010096)]
        HRESULT _stdcall Parent([out, retval] IDispatch** RHS);
        [propget, helpcontext(0x000103bf)]
        HRESULT _stdcall AutomaticStyles([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x000103bf)]
        HRESULT _stdcall AutomaticStyles([in] VARIANT_BOOL RHS);
        [helpcontext(0x000103c0)]
        HRESULT _stdcall ShowLevels(
                        [in, optional] VARIANT RowLevels, 
                        [in, optional] VARIANT ColumnLevels);
        [propget, helpcontext(0x000103c1)]
        HRESULT _stdcall SummaryColumn([out, retval] XlSummaryColumn* RHS);
        [propput, helpcontext(0x000103c1)]
        HRESULT _stdcall SummaryColumn([in] XlSummaryColumn RHS);
        [propget, helpcontext(0x00010386)]
        HRESULT _stdcall SummaryRow([out, retval] XlSummaryRow* RHS);
        [propput, helpcontext(0x00010386)]
        HRESULT _stdcall SummaryRow([in] XlSummaryRow RHS);
    };

    [
      odl,
      uuid(000208AD-0001-0000-C000-000000000046),
      helpcontext(0x0002006d),
      hidden
    ]
    interface IModule : IDispatch {
        [propget, helpcontext(0x00010094)]
        HRESULT _stdcall Application([out, retval] Application** RHS);
        [propget, helpcontext(0x00010095)]
        HRESULT _stdcall Creator([out, retval] XlCreator* RHS);
        [propget, helpcontext(0x00010096)]
        HRESULT _stdcall Parent([out, retval] IDispatch** RHS);
        [helpcontext(0x00010130)]
        HRESULT _stdcall Activate([in, lcid] long lcid);
        [helpcontext(0x00010227)]
        HRESULT _stdcall Copy(
                        [in, optional] VARIANT Before, 
                        [in, optional] VARIANT After, 
                        [in, lcid] long lcid);
        [helpcontext(0x00010075)]
        HRESULT _stdcall Delete([in, lcid] long lcid);
        [propget, helpcontext(0x0001055d)]
        HRESULT _stdcall CodeName([out, retval] BSTR* RHS);
        [propget, helpcontext(0x80020000)]
        HRESULT _stdcall _CodeName([out, retval] BSTR* RHS);
        [propput, helpcontext(0x80020000)]
        HRESULT _stdcall _CodeName([in] BSTR RHS);
        [propget, helpcontext(0x000101e6)]
        HRESULT _stdcall Index(
                        [in, lcid] long lcid, 
                        [out, retval] long* RHS);
        [helpcontext(0x0001027d)]
        HRESULT _stdcall Move(
                        [in, optional] VARIANT Before, 
                        [in, optional] VARIANT After, 
                        [in, lcid] long lcid);
        [propget, helpcontext(0x0001006e)]
        HRESULT _stdcall Name([out, retval] BSTR* RHS);
        [propput, helpcontext(0x0001006e)]
        HRESULT _stdcall Name([in] BSTR RHS);
        [propget, helpcontext(0x000101f6)]
        HRESULT _stdcall Next([out, retval] IDispatch** RHS);
        [propget, hidden, helpcontext(0x00010274)]
        HRESULT _stdcall OnDoubleClick(
                        [in, lcid] long lcid, 
                        [out, retval] BSTR* RHS);
        [propput, hidden, helpcontext(0x00010274)]
        HRESULT _stdcall OnDoubleClick(
                        [in, lcid] long lcid, 
                        [in] BSTR RHS);
        [propget, hidden, helpcontext(0x00010407)]
        HRESULT _stdcall OnSheetActivate(
                        [in, lcid] long lcid, 
                        [out, retval] BSTR* RHS);
        [propput, hidden, helpcontext(0x00010407)]
        HRESULT _stdcall OnSheetActivate(
                        [in, lcid] long lcid, 
                        [in] BSTR RHS);
        [propget, hidden, helpcontext(0x00010439)]
        HRESULT _stdcall OnSheetDeactivate(
                        [in, lcid] long lcid, 
                        [out, retval] BSTR* RHS);
        [propput, hidden, helpcontext(0x00010439)]
        HRESULT _stdcall OnSheetDeactivate(
                        [in, lcid] long lcid, 
                        [in] BSTR RHS);
        [propget, helpcontext(0x000103e6)]
        HRESULT _stdcall PageSetup([out, retval] PageSetup** RHS);
        [propget, helpcontext(0x000101f7)]
        HRESULT _stdcall Previous([out, retval] IDispatch** RHS);
        [helpcontext(0x00010389)]
        HRESULT _stdcall PrintOut(
                        [in, optional] VARIANT From, 
                        [in, optional] VARIANT To, 
                        [in, optional] VARIANT Copies, 
                        [in, optional] VARIANT Preview, 
                        [in, optional] VARIANT ActivePrinter, 
                        [in, optional] VARIANT PrintToFile, 
                        [in, optional] VARIANT Collate, 
                        [in, lcid] long lcid);
        [restricted, hidden]
        void _stdcall _Dummy18();
        [helpcontext(0x0001011a)]
        HRESULT _stdcall Protect(
                        [in, optional] VARIANT Password, 
                        [in, optional] VARIANT DrawingObjects, 
                        [in, optional] VARIANT Contents, 
                        [in, optional] VARIANT Scenarios, 
                        [in, optional] VARIANT UserInterfaceOnly, 
                        [in, lcid] long lcid);
        [propget, helpcontext(0x00010124)]
        HRESULT _stdcall ProtectContents(
                        [in, lcid] long lcid, 
                        [out, retval] VARIANT_BOOL* RHS);
        [restricted, hidden]
        void _stdcall _Dummy21();
        [propget, helpcontext(0x00010487)]
        HRESULT _stdcall ProtectionMode(
                        [in, lcid] long lcid, 
                        [out, retval] VARIANT_BOOL* RHS);
        [restricted, hidden]
        void _stdcall _Dummy23();
        [helpcontext(0x0001011c)]
        HRESULT _stdcall SaveAs(
                        [in] BSTR Filename, 
                        [in, optional] VARIANT FileFormat, 
                        [in, optional] VARIANT Password, 
                        [in, optional] VARIANT WriteResPassword, 
                        [in, optional] VARIANT ReadOnlyRecommended, 
                        [in, optional] VARIANT CreateBackup, 
                        [in, optional] VARIANT AddToMru, 
                        [in, optional] VARIANT TextCodepage, 
                        [in, optional] VARIANT TextVisualLayout, 
                        [in, lcid] long lcid);
        [helpcontext(0x000100eb)]
        HRESULT _stdcall Select(
                        [in, optional] VARIANT Replace, 
                        [in, lcid] long lcid);
        [helpcontext(0x0001011d)]
        HRESULT _stdcall Unprotect(
                        [in, optional] VARIANT Password, 
                        [in, lcid] long lcid);
        [propget, helpcontext(0x0001022e)]
        HRESULT _stdcall Visible(
                        [in, lcid] long lcid, 
                        [out, retval] XlSheetVisibility* RHS);
        [propput, helpcontext(0x0001022e)]
        HRESULT _stdcall Visible(
                        [in, lcid] long lcid, 
                        [in] XlSheetVisibility RHS);
        [propget, helpcontext(0x00010561)]
        HRESULT _stdcall Shapes([out, retval] Shapes** RHS);
        [helpcontext(0x00010248)]
        HRESULT _stdcall InsertFile(
                        [in] VARIANT Filename, 
                        [in, optional] VARIANT Merge);
    };

    [
      odl,
      uuid(000208AE-0001-0000-C000-000000000046),
      helpcontext(0x0002006e),
      hidden
    ]
    interface IModules : IDispatch {
        [propget, helpcontext(0x00010094)]
        HRESULT _stdcall Application([out, retval] Application** RHS);
        [propget, helpcontext(0x00010095)]
        HRESULT _stdcall Creator([out, retval] XlCreator* RHS);
        [propget, helpcontext(0x00010096)]
        HRESULT _stdcall Parent([out, retval] IDispatch** RHS);
        [helpcontext(0x000100b5)]
        HRESULT _stdcall Add(
                        [in, optional] VARIANT Before, 
                        [in, optional] VARIANT After, 
                        [in, optional] VARIANT Count, 
                        [out, retval] Module** RHS);
        [helpcontext(0x00010227)]
        HRESULT _stdcall Copy(
                        [in, optional] VARIANT Before, 
                        [in, optional] VARIANT After, 
                        [in, lcid] long lcid);
        [propget, helpcontext(0x00010076)]
        HRESULT _stdcall Count([out, retval] long* RHS);
        [helpcontext(0x00010075)]
        HRESULT _stdcall Delete([in, lcid] long lcid);
        [restricted, hidden]
        void _stdcall _Dummy7();
        [propget, helpcontext(0x000100aa)]
        HRESULT _stdcall Item(
                        [in] VARIANT Index, 
                        [out, retval] IDispatch** RHS);
        [helpcontext(0x0001027d)]
        HRESULT _stdcall Move(
                        [in, optional] VARIANT Before, 
                        [in, optional] VARIANT After, 
                        [in, lcid] long lcid);
        [propget, helpcontext(0x0000fffc)]
        HRESULT _stdcall _NewEnum([out, retval] IUnknown** RHS);
        [helpcontext(0x00010389)]
        HRESULT _stdcall PrintOut(
                        [in, optional] VARIANT From, 
                        [in, optional] VARIANT To, 
                        [in, optional] VARIANT Copies, 
                        [in, optional] VARIANT Preview, 
                        [in, optional] VARIANT ActivePrinter, 
                        [in, optional] VARIANT PrintToFile, 
                        [in, optional] VARIANT Collate, 
                        [in, lcid] long lcid);
        [restricted, hidden]
        void _stdcall _Dummy12();
        [helpcontext(0x000100eb)]
        HRESULT _stdcall Select(
                        [in, optional] VARIANT Replace, 
                        [in, lcid] long lcid);
        [propget, helpcontext(0x0001058a)]
        HRESULT _stdcall HPageBreaks([out, retval] HPageBreaks** RHS);
        [propget, helpcontext(0x0001058b)]
        HRESULT _stdcall VPageBreaks([out, retval] VPageBreaks** RHS);
        [propget, helpcontext(0x0001022e)]
        HRESULT _stdcall Visible(
                        [in, lcid] long lcid, 
                        [out, retval] VARIANT* RHS);
        [propput, helpcontext(0x0001022e)]
        HRESULT _stdcall Visible(
                        [in, lcid] long lcid, 
                        [in] VARIANT RHS);
        [propget, helpcontext(0x00010000)]
        HRESULT _stdcall _Default(
                        [in] VARIANT Index, 
                        [out, retval] IDispatch** RHS);
    };

    [
      odl,
      uuid(000208AF-0001-0000-C000-000000000046),
      helpcontext(0x0002006f),
      hidden
    ]
    interface IDialogSheet : IDispatch {
        [propget, helpcontext(0x00010094)]
        HRESULT _stdcall Application([out, retval] Application** RHS);
        [propget, helpcontext(0x00010095)]
        HRESULT _stdcall Creator([out, retval] XlCreator* RHS);
        [propget, helpcontext(0x00010096)]
        HRESULT _stdcall Parent([out, retval] IDispatch** RHS);
        [helpcontext(0x00010130)]
        HRESULT _stdcall Activate([in, lcid] long lcid);
        [helpcontext(0x00010227)]
        HRESULT _stdcall Copy(
                        [in, optional] VARIANT Before, 
                        [in, optional] VARIANT After, 
                        [in, lcid] long lcid);
        [helpcontext(0x00010075)]
        HRESULT _stdcall Delete([in, lcid] long lcid);
        [propget, helpcontext(0x0001055d)]
        HRESULT _stdcall CodeName([out, retval] BSTR* RHS);
        [propget, helpcontext(0x80020000)]
        HRESULT _stdcall _CodeName([out, retval] BSTR* RHS);
        [propput, helpcontext(0x80020000)]
        HRESULT _stdcall _CodeName([in] BSTR RHS);
        [propget, helpcontext(0x000101e6)]
        HRESULT _stdcall Index(
                        [in, lcid] long lcid, 
                        [out, retval] long* RHS);
        [helpcontext(0x0001027d)]
        HRESULT _stdcall Move(
                        [in, optional] VARIANT Before, 
                        [in, optional] VARIANT After, 
                        [in, lcid] long lcid);
        [propget, helpcontext(0x0001006e)]
        HRESULT _stdcall Name([out, retval] BSTR* RHS);
        [propput, helpcontext(0x0001006e)]
        HRESULT _stdcall Name([in] BSTR RHS);
        [propget, helpcontext(0x000101f6)]
        HRESULT _stdcall Next([out, retval] IDispatch** RHS);
        [propget, hidden, helpcontext(0x00010274)]
        HRESULT _stdcall OnDoubleClick(
                        [in, lcid] long lcid, 
                        [out, retval] BSTR* RHS);
        [propput, hidden, helpcontext(0x00010274)]
        HRESULT _stdcall OnDoubleClick(
                        [in, lcid] long lcid, 
                        [in] BSTR RHS);
        [propget, hidden, helpcontext(0x00010407)]
        HRESULT _stdcall OnSheetActivate(
                        [in, lcid] long lcid, 
                        [out, retval] BSTR* RHS);
        [propput, hidden, helpcontext(0x00010407)]
        HRESULT _stdcall OnSheetActivate(
                        [in, lcid] long lcid, 
                        [in] BSTR RHS);
        [propget, hidden, helpcontext(0x00010439)]
        HRESULT _stdcall OnSheetDeactivate(
                        [in, lcid] long lcid, 
                        [out, retval] BSTR* RHS);
        [propput, hidden, helpcontext(0x00010439)]
        HRESULT _stdcall OnSheetDeactivate(
                        [in, lcid] long lcid, 
                        [in] BSTR RHS);
        [propget, helpcontext(0x000103e6)]
        HRESULT _stdcall PageSetup([out, retval] PageSetup** RHS);
        [propget, helpcontext(0x000101f7)]
        HRESULT _stdcall Previous([out, retval] IDispatch** RHS);
        [helpcontext(0x00010389)]
        HRESULT _stdcall PrintOut(
                        [in, optional] VARIANT From, 
                        [in, optional] VARIANT To, 
                        [in, optional] VARIANT Copies, 
                        [in, optional] VARIANT Preview, 
                        [in, optional] VARIANT ActivePrinter, 
                        [in, optional] VARIANT PrintToFile, 
                        [in, optional] VARIANT Collate, 
                        [in, lcid] long lcid);
        [helpcontext(0x00010119)]
        HRESULT _stdcall PrintPreview(
                        [in, optional] VARIANT EnableChanges, 
                        [in, lcid] long lcid);
        [helpcontext(0x0001011a)]
        HRESULT _stdcall Protect(
                        [in, optional] VARIANT Password, 
                        [in, optional] VARIANT DrawingObjects, 
                        [in, optional] VARIANT Contents, 
                        [in, optional] VARIANT Scenarios, 
                        [in, optional] VARIANT UserInterfaceOnly, 
                        [in, lcid] long lcid);
        [propget, helpcontext(0x00010124)]
        HRESULT _stdcall ProtectContents(
                        [in, lcid] long lcid, 
                        [out, retval] VARIANT_BOOL* RHS);
        [propget, helpcontext(0x00010125)]
        HRESULT _stdcall ProtectDrawingObjects(
                        [in, lcid] long lcid, 
                        [out, retval] VARIANT_BOOL* RHS);
        [propget, helpcontext(0x00010487)]
        HRESULT _stdcall ProtectionMode(
                        [in, lcid] long lcid, 
                        [out, retval] VARIANT_BOOL* RHS);
        [propget, helpcontext(0x00010126)]
        HRESULT _stdcall ProtectScenarios(
                        [in, lcid] long lcid, 
                        [out, retval] VARIANT_BOOL* RHS);
        [helpcontext(0x0001011c)]
        HRESULT _stdcall SaveAs(
                        [in] BSTR Filename, 
                        [in, optional] VARIANT FileFormat, 
                        [in, optional] VARIANT Password, 
                        [in, optional] VARIANT WriteResPassword, 
                        [in, optional] VARIANT ReadOnlyRecommended, 
                        [in, optional] VARIANT CreateBackup, 
                        [in, optional] VARIANT AddToMru, 
                        [in, optional] VARIANT TextCodepage, 
                        [in, optional] VARIANT TextVisualLayout, 
                        [in, lcid] long lcid);
        [helpcontext(0x000100eb)]
        HRESULT _stdcall Select(
                        [in, optional] VARIANT Replace, 
                        [in, lcid] long lcid);
        [helpcontext(0x0001011d)]
        HRESULT _stdcall Unprotect(
                        [in, optional] VARIANT Password, 
                        [in, lcid] long lcid);
        [propget, helpcontext(0x0001022e)]
        HRESULT _stdcall Visible(
                        [in, lcid] long lcid, 
                        [out, retval] XlSheetVisibility* RHS);
        [propput, helpcontext(0x0001022e)]
        HRESULT _stdcall Visible(
                        [in, lcid] long lcid, 
                        [in] XlSheetVisibility RHS);
        [propget, helpcontext(0x00010561)]
        HRESULT _stdcall Shapes([out, retval] Shapes** RHS);
        [restricted, hidden]
        void _stdcall _Dummy29();
        [hidden, helpcontext(0x000102f8)]
        HRESULT _stdcall Arcs(
                        [in, optional] VARIANT Index, 
                        [in, lcid] long lcid, 
                        [out, retval] IDispatch** RHS);
        [restricted, hidden]
        void _stdcall _Dummy31();
        [restricted, hidden]
        void _stdcall _Dummy32();
        [hidden, helpcontext(0x0001022d)]
        HRESULT _stdcall Buttons(
                        [in, optional] VARIANT Index, 
                        [in, lcid] long lcid, 
                        [out, retval] IDispatch** RHS);
        [restricted, hidden]
        void _stdcall _Dummy34();
        [propget, helpcontext(0x00010590)]
        HRESULT _stdcall EnableCalculation([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010590)]
        HRESULT _stdcall EnableCalculation([in] VARIANT_BOOL RHS);
        [restricted, hidden]
        void _stdcall _Dummy36();
        [helpcontext(0x00010424)]
        HRESULT _stdcall ChartObjects(
                        [in, optional] VARIANT Index, 
                        [in, lcid] long lcid, 
                        [out, retval] IDispatch** RHS);
        [hidden, helpcontext(0x00010338)]
        HRESULT _stdcall CheckBoxes(
                        [in, optional] VARIANT Index, 
                        [in, lcid] long lcid, 
                        [out, retval] IDispatch** RHS);
        [helpcontext(0x000101f9)]
        HRESULT _stdcall CheckSpelling(
                        [in, optional] VARIANT CustomDictionary, 
                        [in, optional] VARIANT IgnoreUppercase, 
                        [in, optional] VARIANT AlwaysSuggest, 
                        [in, optional] VARIANT IgnoreInitialAlefHamza, 
                        [in, optional] VARIANT IgnoreFinalYaa, 
                        [in, optional] VARIANT SpellScript, 
                        [in, lcid] long lcid);
        [restricted, hidden]
        void _stdcall _Dummy40();
        [restricted, hidden]
        void _stdcall _Dummy41();
        [restricted, hidden]
        void _stdcall _Dummy42();
        [restricted, hidden]
        void _stdcall _Dummy43();
        [restricted, hidden]
        void _stdcall _Dummy44();
        [restricted, hidden]
        void _stdcall _Dummy45();
        [propget, hidden, helpcontext(0x00010283)]
        HRESULT _stdcall DisplayAutomaticPageBreaks(
                        [in, lcid] long lcid, 
                        [out, retval] VARIANT_BOOL* RHS);
        [propput, hidden, helpcontext(0x00010283)]
        HRESULT _stdcall DisplayAutomaticPageBreaks(
                        [in, lcid] long lcid, 
                        [in] VARIANT_BOOL RHS);
        [hidden, helpcontext(0x00010304)]
        HRESULT _stdcall Drawings(
                        [in, optional] VARIANT Index, 
                        [in, lcid] long lcid, 
                        [out, retval] IDispatch** RHS);
        [hidden, helpcontext(0x00010058)]
        HRESULT _stdcall DrawingObjects(
                        [in, optional] VARIANT Index, 
                        [in, lcid] long lcid, 
                        [out, retval] IDispatch** RHS);
        [hidden, helpcontext(0x00010344)]
        HRESULT _stdcall DropDowns(
                        [in, optional] VARIANT Index, 
                        [in, lcid] long lcid, 
                        [out, retval] IDispatch** RHS);
        [propget, helpcontext(0x00010484)]
        HRESULT _stdcall EnableAutoFilter(
                        [in, lcid] long lcid, 
                        [out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010484)]
        HRESULT _stdcall EnableAutoFilter(
                        [in, lcid] long lcid, 
                        [in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x00010591)]
        HRESULT _stdcall EnableSelection([out, retval] XlEnableSelection* RHS);
        [propput, helpcontext(0x00010591)]
        HRESULT _stdcall EnableSelection([in] XlEnableSelection RHS);
        [propget, helpcontext(0x00010485)]
        HRESULT _stdcall EnableOutlining(
                        [in, lcid] long lcid, 
                        [out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010485)]
        HRESULT _stdcall EnableOutlining(
                        [in, lcid] long lcid, 
                        [in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x00010486)]
        HRESULT _stdcall EnablePivotTable(
                        [in, lcid] long lcid, 
                        [out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010486)]
        HRESULT _stdcall EnablePivotTable(
                        [in, lcid] long lcid, 
                        [in] VARIANT_BOOL RHS);
        [helpcontext(0x00010001)]
        HRESULT _stdcall Evaluate(
                        [in] VARIANT Name, 
                        [in, lcid] long lcid, 
                        [out, retval] VARIANT* RHS);
        [helpcontext(0x0000fffb)]
        HRESULT _stdcall _Evaluate(
                        [in] VARIANT Name, 
                        [in, lcid] long lcid, 
                        [out, retval] VARIANT* RHS);
        [restricted, hidden]
        void _stdcall _Dummy56();
        [helpcontext(0x00010592)]
        HRESULT _stdcall ResetAllPageBreaks();
        [hidden, helpcontext(0x00010342)]
        HRESULT _stdcall GroupBoxes(
                        [in, optional] VARIANT Index, 
                        [in, lcid] long lcid, 
                        [out, retval] IDispatch** RHS);
        [hidden, helpcontext(0x00010459)]
        HRESULT _stdcall GroupObjects(
                        [in, optional] VARIANT Index, 
                        [in, lcid] long lcid, 
                        [out, retval] IDispatch** RHS);
        [hidden, helpcontext(0x00010349)]
        HRESULT _stdcall Labels(
                        [in, optional] VARIANT Index, 
                        [in, lcid] long lcid, 
                        [out, retval] IDispatch** RHS);
        [hidden, helpcontext(0x000102ff)]
        HRESULT _stdcall Lines(
                        [in, optional] VARIANT Index, 
                        [in, lcid] long lcid, 
                        [out, retval] IDispatch** RHS);
        [hidden, helpcontext(0x00010340)]
        HRESULT _stdcall ListBoxes(
                        [in, optional] VARIANT Index, 
                        [in, lcid] long lcid, 
                        [out, retval] IDispatch** RHS);
        [propget, helpcontext(0x000101ba)]
        HRESULT _stdcall Names([out, retval] Names** RHS);
        [helpcontext(0x0001031f)]
        HRESULT _stdcall OLEObjects(
                        [in, optional] VARIANT Index, 
                        [in, lcid] long lcid, 
                        [out, retval] IDispatch** RHS);
        [restricted, hidden]
        void _stdcall _Dummy65();
        [restricted, hidden]
        void _stdcall _Dummy66();
        [restricted, hidden]
        void _stdcall _Dummy67();
        [hidden, helpcontext(0x0001033a)]
        HRESULT _stdcall OptionButtons(
                        [in, optional] VARIANT Index, 
                        [in, lcid] long lcid, 
                        [out, retval] IDispatch** RHS);
        [restricted, hidden]
        void _stdcall _Dummy69();
        [hidden, helpcontext(0x00010321)]
        HRESULT _stdcall Ovals(
                        [in, optional] VARIANT Index, 
                        [in, lcid] long lcid, 
                        [out, retval] IDispatch** RHS);
        [helpcontext(0x000100d3)]
        HRESULT _stdcall Paste(
                        [in, optional] VARIANT Destination, 
                        [in, optional] VARIANT Link, 
                        [in, lcid] long lcid);
        [helpcontext(0x00010403)]
        HRESULT _stdcall PasteSpecial(
                        [in, optional] VARIANT Format, 
                        [in, optional] VARIANT Link, 
                        [in, optional] VARIANT DisplayAsIcon, 
                        [in, optional] VARIANT IconFileName, 
                        [in, optional] VARIANT IconIndex, 
                        [in, optional] VARIANT IconLabel, 
                        [in, lcid] long lcid);
        [hidden, helpcontext(0x00010303)]
        HRESULT _stdcall Pictures(
                        [in, optional] VARIANT Index, 
                        [in, lcid] long lcid, 
                        [out, retval] IDispatch** RHS);
        [restricted, hidden]
        void _stdcall _Dummy74();
        [restricted, hidden]
        void _stdcall _Dummy75();
        [restricted, hidden]
        void _stdcall _Dummy76();
        [hidden, helpcontext(0x00010306)]
        HRESULT _stdcall Rectangles(
                        [in, optional] VARIANT Index, 
                        [in, lcid] long lcid, 
                        [out, retval] IDispatch** RHS);
        [restricted, hidden]
        void _stdcall _Dummy78();
        [restricted, hidden]
        void _stdcall _Dummy79();
        [propget, helpcontext(0x00010599)]
        HRESULT _stdcall ScrollArea([out, retval] BSTR* RHS);
        [propput, helpcontext(0x00010599)]
        HRESULT _stdcall ScrollArea([in] BSTR RHS);
        [hidden, helpcontext(0x0001033e)]
        HRESULT _stdcall ScrollBars(
                        [in, optional] VARIANT Index, 
                        [in, lcid] long lcid, 
                        [out, retval] IDispatch** RHS);
        [restricted, hidden]
        void _stdcall _Dummy82();
        [restricted, hidden]
        void _stdcall _Dummy83();
        [hidden, helpcontext(0x00010346)]
        HRESULT _stdcall Spinners(
                        [in, optional] VARIANT Index, 
                        [in, lcid] long lcid, 
                        [out, retval] IDispatch** RHS);
        [restricted, hidden]
        void _stdcall _Dummy85();
        [restricted, hidden]
        void _stdcall _Dummy86();
        [hidden, helpcontext(0x00010309)]
        HRESULT _stdcall TextBoxes(
                        [in, optional] VARIANT Index, 
                        [in, lcid] long lcid, 
                        [out, retval] IDispatch** RHS);
        [restricted, hidden]
        void _stdcall _Dummy88();
        [restricted, hidden]
        void _stdcall _Dummy89();
        [restricted, hidden]
        void _stdcall _Dummy90();
        [propget, helpcontext(0x0001058a)]
        HRESULT _stdcall HPageBreaks([out, retval] HPageBreaks** RHS);
        [propget, helpcontext(0x0001058b)]
        HRESULT _stdcall VPageBreaks([out, retval] VPageBreaks** RHS);
        [propget, helpcontext(0x0001059a)]
        HRESULT _stdcall QueryTables([out, retval] QueryTables** RHS);
        [propget, helpcontext(0x0001059b)]
        HRESULT _stdcall DisplayPageBreaks([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x0001059b)]
        HRESULT _stdcall DisplayPageBreaks([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x0001023f)]
        HRESULT _stdcall Comments([out, retval] Comments** RHS);
        [propget, helpcontext(0x00010571)]
        HRESULT _stdcall Hyperlinks([out, retval] Hyperlinks** RHS);
        [helpcontext(0x0001059c)]
        HRESULT _stdcall ClearCircles();
        [helpcontext(0x0001059d)]
        HRESULT _stdcall CircleInvalid();
        [propget, hidden, helpcontext(0x00010288)]
        HRESULT _stdcall DisplayRightToLeft(
                        [in, lcid] long lcid, 
                        [out, retval] long* RHS);
        [propput, hidden, helpcontext(0x00010288)]
        HRESULT _stdcall DisplayRightToLeft(
                        [in, lcid] long lcid, 
                        [in] long RHS);
        [propget, helpcontext(0x00010319)]
        HRESULT _stdcall AutoFilter([out, retval] AutoFilter** RHS);
        [propget, helpcontext(0x00010359)]
        HRESULT _stdcall DefaultButton([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010359)]
        HRESULT _stdcall DefaultButton([in] VARIANT RHS);
        [propget, hidden, helpcontext(0x00010347)]
        HRESULT _stdcall DialogFrame([out, retval] DialogFrame** RHS);
        [hidden, helpcontext(0x0001033c)]
        HRESULT _stdcall EditBoxes(
                        [in, optional] VARIANT Index, 
                        [out, retval] IDispatch** RHS);
        [propget, helpcontext(0x0001032e)]
        HRESULT _stdcall Focus([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x0001032e)]
        HRESULT _stdcall Focus([in] VARIANT RHS);
        [helpcontext(0x0001032d)]
        HRESULT _stdcall Hide(
                        [in, optional] VARIANT Cancel, 
                        [out, retval] VARIANT_BOOL* RHS);
        [helpcontext(0x000101f0)]
        HRESULT _stdcall Show([out, retval] VARIANT_BOOL* RHS);
    };

    [
      odl,
      uuid(000208B0-0001-0000-C000-000000000046),
      helpcontext(0x00020070),
      hidden
    ]
    interface IDialogSheets : IDispatch {
        [propget, helpcontext(0x00010094)]
        HRESULT _stdcall Application([out, retval] Application** RHS);
        [propget, helpcontext(0x00010095)]
        HRESULT _stdcall Creator([out, retval] XlCreator* RHS);
        [propget, helpcontext(0x00010096)]
        HRESULT _stdcall Parent([out, retval] IDispatch** RHS);
        [helpcontext(0x000100b5)]
        HRESULT _stdcall Add(
                        [in, optional] VARIANT Before, 
                        [in, optional] VARIANT After, 
                        [in, optional] VARIANT Count, 
                        [out, retval] DialogSheet** RHS);
        [helpcontext(0x00010227)]
        HRESULT _stdcall Copy(
                        [in, optional] VARIANT Before, 
                        [in, optional] VARIANT After, 
                        [in, lcid] long lcid);
        [propget, helpcontext(0x00010076)]
        HRESULT _stdcall Count([out, retval] long* RHS);
        [helpcontext(0x00010075)]
        HRESULT _stdcall Delete([in, lcid] long lcid);
        [restricted, hidden]
        void _stdcall _Dummy7();
        [propget, helpcontext(0x000100aa)]
        HRESULT _stdcall Item(
                        [in] VARIANT Index, 
                        [out, retval] IDispatch** RHS);
        [helpcontext(0x0001027d)]
        HRESULT _stdcall Move(
                        [in, optional] VARIANT Before, 
                        [in, optional] VARIANT After, 
                        [in, lcid] long lcid);
        [propget, helpcontext(0x0000fffc)]
        HRESULT _stdcall _NewEnum([out, retval] IUnknown** RHS);
        [helpcontext(0x00010389)]
        HRESULT _stdcall PrintOut(
                        [in, optional] VARIANT From, 
                        [in, optional] VARIANT To, 
                        [in, optional] VARIANT Copies, 
                        [in, optional] VARIANT Preview, 
                        [in, optional] VARIANT ActivePrinter, 
                        [in, optional] VARIANT PrintToFile, 
                        [in, optional] VARIANT Collate, 
                        [in, lcid] long lcid);
        [helpcontext(0x00010119)]
        HRESULT _stdcall PrintPreview(
                        [in, optional] VARIANT EnableChanges, 
                        [in, lcid] long lcid);
        [helpcontext(0x000100eb)]
        HRESULT _stdcall Select(
                        [in, optional] VARIANT Replace, 
                        [in, lcid] long lcid);
        [propget, helpcontext(0x0001058a)]
        HRESULT _stdcall HPageBreaks([out, retval] HPageBreaks** RHS);
        [propget, helpcontext(0x0001058b)]
        HRESULT _stdcall VPageBreaks([out, retval] VPageBreaks** RHS);
        [propget, helpcontext(0x0001022e)]
        HRESULT _stdcall Visible(
                        [in, lcid] long lcid, 
                        [out, retval] VARIANT* RHS);
        [propput, helpcontext(0x0001022e)]
        HRESULT _stdcall Visible(
                        [in, lcid] long lcid, 
                        [in] VARIANT RHS);
        [propget, helpcontext(0x00010000)]
        HRESULT _stdcall _Default(
                        [in] VARIANT Index, 
                        [out, retval] IDispatch** RHS);
    };

    [
      odl,
      uuid(000208B1-0001-0000-C000-000000000046),
      helpcontext(0x00020071),
      hidden
    ]
    interface IWorksheets : IDispatch {
        [propget, helpcontext(0x00010094)]
        HRESULT _stdcall Application([out, retval] Application** RHS);
        [propget, helpcontext(0x00010095)]
        HRESULT _stdcall Creator([out, retval] XlCreator* RHS);
        [propget, helpcontext(0x00010096)]
        HRESULT _stdcall Parent([out, retval] IDispatch** RHS);
        [helpcontext(0x000100b5)]
        HRESULT _stdcall Add(
                        [in, optional] VARIANT Before, 
                        [in, optional] VARIANT After, 
                        [in, optional] VARIANT Count, 
                        [in, optional] VARIANT Type, 
                        [in, lcid] long lcid, 
                        [out, retval] IDispatch** RHS);
        [helpcontext(0x00010227)]
        HRESULT _stdcall Copy(
                        [in, optional] VARIANT Before, 
                        [in, optional] VARIANT After, 
                        [in, lcid] long lcid);
        [propget, helpcontext(0x00010076)]
        HRESULT _stdcall Count([out, retval] long* RHS);
        [helpcontext(0x00010075)]
        HRESULT _stdcall Delete([in, lcid] long lcid);
        [helpcontext(0x000101d5)]
        HRESULT _stdcall FillAcrossSheets(
                        [in] Range* Range, 
                        [in, optional, defaultvalue(-4104)] XlFillWith Type, 
                        [in, lcid] long lcid);
        [propget, helpcontext(0x000100aa)]
        HRESULT _stdcall Item(
                        [in] VARIANT Index, 
                        [out, retval] IDispatch** RHS);
        [helpcontext(0x0001027d)]
        HRESULT _stdcall Move(
                        [in, optional] VARIANT Before, 
                        [in, optional] VARIANT After, 
                        [in, lcid] long lcid);
        [propget, helpcontext(0x0000fffc)]
        HRESULT _stdcall _NewEnum([out, retval] IUnknown** RHS);
        [helpcontext(0x00010389)]
        HRESULT _stdcall PrintOut(
                        [in, optional] VARIANT From, 
                        [in, optional] VARIANT To, 
                        [in, optional] VARIANT Copies, 
                        [in, optional] VARIANT Preview, 
                        [in, optional] VARIANT ActivePrinter, 
                        [in, optional] VARIANT PrintToFile, 
                        [in, optional] VARIANT Collate, 
                        [in, lcid] long lcid);
        [helpcontext(0x00010119)]
        HRESULT _stdcall PrintPreview(
                        [in, optional] VARIANT EnableChanges, 
                        [in, lcid] long lcid);
        [helpcontext(0x000100eb)]
        HRESULT _stdcall Select(
                        [in, optional] VARIANT Replace, 
                        [in, lcid] long lcid);
        [propget, helpcontext(0x0001058a)]
        HRESULT _stdcall HPageBreaks([out, retval] HPageBreaks** RHS);
        [propget, helpcontext(0x0001058b)]
        HRESULT _stdcall VPageBreaks([out, retval] VPageBreaks** RHS);
        [propget, helpcontext(0x0001022e)]
        HRESULT _stdcall Visible(
                        [in, lcid] long lcid, 
                        [out, retval] VARIANT* RHS);
        [propput, helpcontext(0x0001022e)]
        HRESULT _stdcall Visible(
                        [in, lcid] long lcid, 
                        [in] VARIANT RHS);
        [propget, helpcontext(0x00010000)]
        HRESULT _stdcall _Default(
                        [in] VARIANT Index, 
                        [out, retval] IDispatch** RHS);
    };

    [
      odl,
      uuid(000208B4-0001-0000-C000-000000000046),
      helpcontext(0x00020074),
      hidden
    ]
    interface IPageSetup : IDispatch {
        [propget, helpcontext(0x00010094)]
        HRESULT _stdcall Application([out, retval] Application** RHS);
        [propget, helpcontext(0x00010095)]
        HRESULT _stdcall Creator([out, retval] XlCreator* RHS);
        [propget, helpcontext(0x00010096)]
        HRESULT _stdcall Parent([out, retval] IDispatch** RHS);
        [propget, helpcontext(0x000103f1)]
        HRESULT _stdcall BlackAndWhite([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x000103f1)]
        HRESULT _stdcall BlackAndWhite([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x000103ea)]
        HRESULT _stdcall BottomMargin([out, retval] double* RHS);
        [propput, helpcontext(0x000103ea)]
        HRESULT _stdcall BottomMargin([in] double RHS);
        [propget, helpcontext(0x000103f2)]
        HRESULT _stdcall CenterFooter([out, retval] BSTR* RHS);
        [propput, helpcontext(0x000103f2)]
        HRESULT _stdcall CenterFooter([in] BSTR RHS);
        [propget, helpcontext(0x000103f3)]
        HRESULT _stdcall CenterHeader([out, retval] BSTR* RHS);
        [propput, helpcontext(0x000103f3)]
        HRESULT _stdcall CenterHeader([in] BSTR RHS);
        [propget, helpcontext(0x000103ed)]
        HRESULT _stdcall CenterHorizontally([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x000103ed)]
        HRESULT _stdcall CenterHorizontally([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x000103ee)]
        HRESULT _stdcall CenterVertically([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x000103ee)]
        HRESULT _stdcall CenterVertically([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x000103f4)]
        HRESULT _stdcall ChartSize([out, retval] XlObjectSize* RHS);
        [propput, helpcontext(0x000103f4)]
        HRESULT _stdcall ChartSize([in] XlObjectSize RHS);
        [propget, helpcontext(0x000103fc)]
        HRESULT _stdcall Draft([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x000103fc)]
        HRESULT _stdcall Draft([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x000103f0)]
        HRESULT _stdcall FirstPageNumber([out, retval] long* RHS);
        [propput, helpcontext(0x000103f0)]
        HRESULT _stdcall FirstPageNumber([in] long RHS);
        [propget, helpcontext(0x000103f5)]
        HRESULT _stdcall FitToPagesTall([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x000103f5)]
        HRESULT _stdcall FitToPagesTall([in] VARIANT RHS);
        [propget, helpcontext(0x000103f6)]
        HRESULT _stdcall FitToPagesWide([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x000103f6)]
        HRESULT _stdcall FitToPagesWide([in] VARIANT RHS);
        [propget, helpcontext(0x000103f7)]
        HRESULT _stdcall FooterMargin([out, retval] double* RHS);
        [propput, helpcontext(0x000103f7)]
        HRESULT _stdcall FooterMargin([in] double RHS);
        [propget, helpcontext(0x000103f8)]
        HRESULT _stdcall HeaderMargin([out, retval] double* RHS);
        [propput, helpcontext(0x000103f8)]
        HRESULT _stdcall HeaderMargin([in] double RHS);
        [propget, helpcontext(0x000103f9)]
        HRESULT _stdcall LeftFooter([out, retval] BSTR* RHS);
        [propput, helpcontext(0x000103f9)]
        HRESULT _stdcall LeftFooter([in] BSTR RHS);
        [propget, helpcontext(0x000103fa)]
        HRESULT _stdcall LeftHeader([out, retval] BSTR* RHS);
        [propput, helpcontext(0x000103fa)]
        HRESULT _stdcall LeftHeader([in] BSTR RHS);
        [propget, helpcontext(0x000103e7)]
        HRESULT _stdcall LeftMargin([out, retval] double* RHS);
        [propput, helpcontext(0x000103e7)]
        HRESULT _stdcall LeftMargin([in] double RHS);
        [propget, helpcontext(0x000100c0)]
        HRESULT _stdcall Order([out, retval] XlOrder* RHS);
        [propput, helpcontext(0x000100c0)]
        HRESULT _stdcall Order([in] XlOrder RHS);
        [propget, helpcontext(0x00010086)]
        HRESULT _stdcall Orientation([out, retval] XlPageOrientation* RHS);
        [propput, helpcontext(0x00010086)]
        HRESULT _stdcall Orientation([in] XlPageOrientation RHS);
        [propget, helpcontext(0x000103ef)]
        HRESULT _stdcall PaperSize([out, retval] XlPaperSize* RHS);
        [propput, helpcontext(0x000103ef)]
        HRESULT _stdcall PaperSize([in] XlPaperSize RHS);
        [propget, helpcontext(0x000103fb)]
        HRESULT _stdcall PrintArea([out, retval] BSTR* RHS);
        [propput, helpcontext(0x000103fb)]
        HRESULT _stdcall PrintArea([in] BSTR RHS);
        [propget, helpcontext(0x000103ec)]
        HRESULT _stdcall PrintGridlines([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x000103ec)]
        HRESULT _stdcall PrintGridlines([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x000103eb)]
        HRESULT _stdcall PrintHeadings([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x000103eb)]
        HRESULT _stdcall PrintHeadings([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x000103fd)]
        HRESULT _stdcall PrintNotes([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x000103fd)]
        HRESULT _stdcall PrintNotes([in] VARIANT_BOOL RHS);
        [helpcontext(0x000103fe)]
        HRESULT _stdcall PrintQuality(
                        [in, optional] VARIANT Index, 
                        [out, retval] VARIANT* RHS);
        [propget, helpcontext(0x000103ff)]
        HRESULT _stdcall PrintTitleColumns([out, retval] BSTR* RHS);
        [propput, helpcontext(0x000103ff)]
        HRESULT _stdcall PrintTitleColumns([in] BSTR RHS);
        [propget, helpcontext(0x00010400)]
        HRESULT _stdcall PrintTitleRows([out, retval] BSTR* RHS);
        [propput, helpcontext(0x00010400)]
        HRESULT _stdcall PrintTitleRows([in] BSTR RHS);
        [propget, helpcontext(0x00010401)]
        HRESULT _stdcall RightFooter([out, retval] BSTR* RHS);
        [propput, helpcontext(0x00010401)]
        HRESULT _stdcall RightFooter([in] BSTR RHS);
        [propget, helpcontext(0x00010402)]
        HRESULT _stdcall RightHeader([out, retval] BSTR* RHS);
        [propput, helpcontext(0x00010402)]
        HRESULT _stdcall RightHeader([in] BSTR RHS);
        [propget, helpcontext(0x000103e8)]
        HRESULT _stdcall RightMargin([out, retval] double* RHS);
        [propput, helpcontext(0x000103e8)]
        HRESULT _stdcall RightMargin([in] double RHS);
        [propget, helpcontext(0x000103e9)]
        HRESULT _stdcall TopMargin([out, retval] double* RHS);
        [propput, helpcontext(0x000103e9)]
        HRESULT _stdcall TopMargin([in] double RHS);
        [propget, helpcontext(0x00010297)]
        HRESULT _stdcall Zoom([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010297)]
        HRESULT _stdcall Zoom([in] VARIANT RHS);
        [propget, helpcontext(0x000105f4)]
        HRESULT _stdcall PrintComments([out, retval] XlPrintLocation* RHS);
        [propput, helpcontext(0x000105f4)]
        HRESULT _stdcall PrintComments([in] XlPrintLocation RHS);
    };

    [
      odl,
      uuid(000208B8-0001-0000-C000-000000000046),
      helpcontext(0x00020078),
      hidden
    ]
    interface INames : IDispatch {
        [propget, helpcontext(0x00010094)]
        HRESULT _stdcall Application([out, retval] Application** RHS);
        [propget, helpcontext(0x00010095)]
        HRESULT _stdcall Creator([out, retval] XlCreator* RHS);
        [propget, helpcontext(0x00010096)]
        HRESULT _stdcall Parent([out, retval] IDispatch** RHS);
        [helpcontext(0x000100b5)]
        HRESULT _stdcall Add(
                        [in, optional] VARIANT Name, 
                        [in, optional] VARIANT RefersTo, 
                        [in, optional] VARIANT Visible, 
                        [in, optional] VARIANT MacroType, 
                        [in, optional] VARIANT ShortcutKey, 
                        [in, optional] VARIANT Category, 
                        [in, optional] VARIANT NameLocal, 
                        [in, optional] VARIANT RefersToLocal, 
                        [in, optional] VARIANT CategoryLocal, 
                        [in, optional] VARIANT RefersToR1C1, 
                        [in, optional] VARIANT RefersToR1C1Local, 
                        [out, retval] Name** RHS);
        [helpcontext(0x000100aa)]
        HRESULT _stdcall Item(
                        [in, optional] VARIANT Index, 
                        [in, optional] VARIANT IndexLocal, 
                        [in, optional] VARIANT RefersTo, 
                        [in, lcid] long lcid, 
                        [out, retval] Name** RHS);
        [helpcontext(0x00010000)]
        HRESULT _stdcall _Default(
                        [in, optional] VARIANT Index, 
                        [in, optional] VARIANT IndexLocal, 
                        [in, optional] VARIANT RefersTo, 
                        [in, lcid] long lcid, 
                        [out, retval] Name** RHS);
        [propget, helpcontext(0x00010076)]
        HRESULT _stdcall Count([out, retval] long* RHS);
        [propget, helpcontext(0x0000fffc)]
        HRESULT _stdcall _NewEnum([out, retval] IUnknown** RHS);
    };

    [
      odl,
      uuid(000208B9-0001-0000-C000-000000000046),
      helpcontext(0x00020079),
      hidden
    ]
    interface IName : IDispatch {
        [propget, helpcontext(0x00010094)]
        HRESULT _stdcall Application([out, retval] Application** RHS);
        [propget, helpcontext(0x00010095)]
        HRESULT _stdcall Creator([out, retval] XlCreator* RHS);
        [propget, helpcontext(0x00010096)]
        HRESULT _stdcall Parent([out, retval] IDispatch** RHS);
        [propget, helpcontext(0x00010000)]
        HRESULT _stdcall _Default([out, retval] BSTR* RHS);
        [propget, helpcontext(0x000101e6)]
        HRESULT _stdcall Index([out, retval] long* RHS);
        [propget, helpcontext(0x000103a6)]
        HRESULT _stdcall Category(
                        [in, lcid] long lcidIn, 
                        [out, retval] BSTR* RHS);
        [propput, helpcontext(0x000103a6)]
        HRESULT _stdcall Category(
                        [in, lcid] long lcidIn, 
                        [in] BSTR RHS);
        [propget, helpcontext(0x000103a7)]
        HRESULT _stdcall CategoryLocal([out, retval] BSTR* RHS);
        [propput, helpcontext(0x000103a7)]
        HRESULT _stdcall CategoryLocal([in] BSTR RHS);
        [helpcontext(0x00010075)]
        HRESULT _stdcall Delete();
        [propget, helpcontext(0x000103a8)]
        HRESULT _stdcall MacroType([out, retval] XlXLMMacroType* RHS);
        [propput, helpcontext(0x000103a8)]
        HRESULT _stdcall MacroType([in] XlXLMMacroType RHS);
        [propget, helpcontext(0x0001006e)]
        HRESULT _stdcall Name(
                        [in, lcid] long lcidIn, 
                        [out, retval] BSTR* RHS);
        [propput, helpcontext(0x0001006e)]
        HRESULT _stdcall Name(
                        [in, lcid] long lcidIn, 
                        [in] BSTR RHS);
        [propget, helpcontext(0x000103aa)]
        HRESULT _stdcall RefersTo(
                        [in, lcid] long lcidIn, 
                        [out, retval] VARIANT* RHS);
        [propput, helpcontext(0x000103aa)]
        HRESULT _stdcall RefersTo(
                        [in, lcid] long lcidIn, 
                        [in] VARIANT RHS);
        [propget, helpcontext(0x00010255)]
        HRESULT _stdcall ShortcutKey([out, retval] BSTR* RHS);
        [propput, helpcontext(0x00010255)]
        HRESULT _stdcall ShortcutKey([in] BSTR RHS);
        [propget, helpcontext(0x00010006)]
        HRESULT _stdcall Value([out, retval] BSTR* RHS);
        [propput, helpcontext(0x00010006)]
        HRESULT _stdcall Value([in] BSTR RHS);
        [propget, helpcontext(0x0001022e)]
        HRESULT _stdcall Visible([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x0001022e)]
        HRESULT _stdcall Visible([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x000103a9)]
        HRESULT _stdcall NameLocal([out, retval] BSTR* RHS);
        [propput, helpcontext(0x000103a9)]
        HRESULT _stdcall NameLocal([in] BSTR RHS);
        [propget, helpcontext(0x000103ab)]
        HRESULT _stdcall RefersToLocal([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x000103ab)]
        HRESULT _stdcall RefersToLocal([in] VARIANT RHS);
        [propget, helpcontext(0x000103ac)]
        HRESULT _stdcall RefersToR1C1(
                        [in, lcid] long lcidIn, 
                        [out, retval] VARIANT* RHS);
        [propput, helpcontext(0x000103ac)]
        HRESULT _stdcall RefersToR1C1(
                        [in, lcid] long lcidIn, 
                        [in] VARIANT RHS);
        [propget, helpcontext(0x000103ad)]
        HRESULT _stdcall RefersToR1C1Local([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x000103ad)]
        HRESULT _stdcall RefersToR1C1Local([in] VARIANT RHS);
        [propget, helpcontext(0x00010488)]
        HRESULT _stdcall RefersToRange([out, retval] Range** RHS);
    };

    [
      odl,
      uuid(000208CF-0001-0000-C000-000000000046),
      helpcontext(0x0002008e),
      hidden
    ]
    interface IChartObject : IDispatch {
        [propget, helpcontext(0x00010094)]
        HRESULT _stdcall Application([out, retval] Application** RHS);
        [propget, helpcontext(0x00010095)]
        HRESULT _stdcall Creator([out, retval] XlCreator* RHS);
        [propget, helpcontext(0x00010096)]
        HRESULT _stdcall Parent([out, retval] IDispatch** RHS);
        [propget, helpcontext(0x00010267)]
        HRESULT _stdcall BottomRightCell([out, retval] Range** RHS);
        [helpcontext(0x0001025a)]
        HRESULT _stdcall BringToFront();
        [helpcontext(0x00010227)]
        HRESULT _stdcall Copy();
        [helpcontext(0x000100d5)]
        HRESULT _stdcall CopyPicture(
                        [in, optional, defaultvalue(2)] XlPictureAppearance Appearance, 
                        [in, optional, defaultvalue(-4147)] XlCopyPictureFormat Format);
        [helpcontext(0x00010235)]
        HRESULT _stdcall Cut();
        [helpcontext(0x00010075)]
        HRESULT _stdcall Delete();
        [helpcontext(0x0001040f)]
        HRESULT _stdcall Duplicate([out, retval] IDispatch** RHS);
        [propget, helpcontext(0x00010258)]
        HRESULT _stdcall Enabled([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010258)]
        HRESULT _stdcall Enabled([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x0001007b)]
        HRESULT _stdcall Height([out, retval] double* RHS);
        [propput, helpcontext(0x0001007b)]
        HRESULT _stdcall Height([in] double RHS);
        [propget, helpcontext(0x000101e6)]
        HRESULT _stdcall Index([out, retval] long* RHS);
        [propget, helpcontext(0x0001007f)]
        HRESULT _stdcall Left([out, retval] double* RHS);
        [propput, helpcontext(0x0001007f)]
        HRESULT _stdcall Left([in] double RHS);
        [propget, helpcontext(0x0001010d)]
        HRESULT _stdcall Locked([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x0001010d)]
        HRESULT _stdcall Locked([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x0001006e)]
        HRESULT _stdcall Name([out, retval] BSTR* RHS);
        [propput, helpcontext(0x0001006e)]
        HRESULT _stdcall Name([in] BSTR RHS);
        [propget, hidden, helpcontext(0x00010254)]
        HRESULT _stdcall OnAction([out, retval] BSTR* RHS);
        [propput, hidden, helpcontext(0x00010254)]
        HRESULT _stdcall OnAction([in] BSTR RHS);
        [propget, helpcontext(0x00010269)]
        HRESULT _stdcall Placement([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010269)]
        HRESULT _stdcall Placement([in] VARIANT RHS);
        [propget, helpcontext(0x0001026a)]
        HRESULT _stdcall PrintObject([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x0001026a)]
        HRESULT _stdcall PrintObject([in] VARIANT_BOOL RHS);
        [helpcontext(0x000100eb)]
        HRESULT _stdcall Select([in, optional] VARIANT Replace);
        [helpcontext(0x0001025d)]
        HRESULT _stdcall SendToBack();
        [propget, helpcontext(0x0001007e)]
        HRESULT _stdcall Top([out, retval] double* RHS);
        [propput, helpcontext(0x0001007e)]
        HRESULT _stdcall Top([in] double RHS);
        [propget, helpcontext(0x0001026c)]
        HRESULT _stdcall TopLeftCell([out, retval] Range** RHS);
        [propget, helpcontext(0x0001022e)]
        HRESULT _stdcall Visible([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x0001022e)]
        HRESULT _stdcall Visible([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x0001007a)]
        HRESULT _stdcall Width([out, retval] double* RHS);
        [propput, helpcontext(0x0001007a)]
        HRESULT _stdcall Width([in] double RHS);
        [propget, helpcontext(0x0001026e)]
        HRESULT _stdcall ZOrder([out, retval] long* RHS);
        [propget, helpcontext(0x000105f8)]
        HRESULT _stdcall ShapeRange([out, retval] ShapeRange** RHS);
        [helpcontext(0x00010130)]
        HRESULT _stdcall Activate();
        [propget, helpcontext(0x00010007)]
        HRESULT _stdcall Chart([out, retval] Chart** RHS);
        [propget, helpcontext(0x000105f9)]
        HRESULT _stdcall ProtectChartObject([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x000105f9)]
        HRESULT _stdcall ProtectChartObject([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x0001026b)]
        HRESULT _stdcall RoundedCorners([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x0001026b)]
        HRESULT _stdcall RoundedCorners([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x00010080)]
        HRESULT _stdcall Border([out, retval] Border** RHS);
        [propget, helpcontext(0x00010081)]
        HRESULT _stdcall Interior([out, retval] Interior** RHS);
        [propget, helpcontext(0x00010067)]
        HRESULT _stdcall Shadow([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010067)]
        HRESULT _stdcall Shadow([in] VARIANT_BOOL RHS);
    };

    [
      odl,
      uuid(000208D0-0001-0000-C000-000000000046),
      helpcontext(0x0002008f),
      hidden
    ]
    interface IChartObjects : IDispatch {
        [propget, helpcontext(0x00010094)]
        HRESULT _stdcall Application([out, retval] Application** RHS);
        [propget, helpcontext(0x00010095)]
        HRESULT _stdcall Creator([out, retval] XlCreator* RHS);
        [propget, helpcontext(0x00010096)]
        HRESULT _stdcall Parent([out, retval] IDispatch** RHS);
        [restricted, hidden]
        void _stdcall _Dummy3();
        [helpcontext(0x0001025a)]
        HRESULT _stdcall BringToFront();
        [helpcontext(0x00010227)]
        HRESULT _stdcall Copy();
        [helpcontext(0x000100d5)]
        HRESULT _stdcall CopyPicture(
                        [in, optional, defaultvalue(2)] XlPictureAppearance Appearance, 
                        [in, optional, defaultvalue(-4147)] XlCopyPictureFormat Format);
        [helpcontext(0x00010235)]
        HRESULT _stdcall Cut();
        [helpcontext(0x00010075)]
        HRESULT _stdcall Delete();
        [helpcontext(0x0001040f)]
        HRESULT _stdcall Duplicate([out, retval] IDispatch** RHS);
        [propget, helpcontext(0x00010258)]
        HRESULT _stdcall Enabled([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010258)]
        HRESULT _stdcall Enabled([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x0001007b)]
        HRESULT _stdcall Height([out, retval] double* RHS);
        [propput, helpcontext(0x0001007b)]
        HRESULT _stdcall Height([in] double RHS);
        [restricted, hidden]
        void _stdcall _Dummy12();
        [propget, helpcontext(0x0001007f)]
        HRESULT _stdcall Left([out, retval] double* RHS);
        [propput, helpcontext(0x0001007f)]
        HRESULT _stdcall Left([in] double RHS);
        [propget, helpcontext(0x0001010d)]
        HRESULT _stdcall Locked([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x0001010d)]
        HRESULT _stdcall Locked([in] VARIANT_BOOL RHS);
        [restricted, hidden]
        void _stdcall _Dummy15();
        [propget, hidden, helpcontext(0x00010254)]
        HRESULT _stdcall OnAction([out, retval] BSTR* RHS);
        [propput, hidden, helpcontext(0x00010254)]
        HRESULT _stdcall OnAction([in] BSTR RHS);
        [propget, helpcontext(0x00010269)]
        HRESULT _stdcall Placement([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010269)]
        HRESULT _stdcall Placement([in] VARIANT RHS);
        [propget, helpcontext(0x0001026a)]
        HRESULT _stdcall PrintObject([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x0001026a)]
        HRESULT _stdcall PrintObject([in] VARIANT_BOOL RHS);
        [helpcontext(0x000100eb)]
        HRESULT _stdcall Select([in, optional] VARIANT Replace);
        [helpcontext(0x0001025d)]
        HRESULT _stdcall SendToBack();
        [propget, helpcontext(0x0001007e)]
        HRESULT _stdcall Top([out, retval] double* RHS);
        [propput, helpcontext(0x0001007e)]
        HRESULT _stdcall Top([in] double RHS);
        [restricted, hidden]
        void _stdcall _Dummy22();
        [propget, helpcontext(0x0001022e)]
        HRESULT _stdcall Visible([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x0001022e)]
        HRESULT _stdcall Visible([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x0001007a)]
        HRESULT _stdcall Width([out, retval] double* RHS);
        [propput, helpcontext(0x0001007a)]
        HRESULT _stdcall Width([in] double RHS);
        [restricted, hidden]
        void _stdcall _Dummy25();
        [propget, helpcontext(0x000105f8)]
        HRESULT _stdcall ShapeRange([out, retval] ShapeRange** RHS);
        [restricted, hidden]
        void _stdcall _Dummy27();
        [restricted, hidden]
        void _stdcall _Dummy28();
        [restricted, hidden]
        void _stdcall _Dummy29();
        [propget, helpcontext(0x0001026b)]
        HRESULT _stdcall RoundedCorners([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x0001026b)]
        HRESULT _stdcall RoundedCorners([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x00010080)]
        HRESULT _stdcall Border([out, retval] Border** RHS);
        [propget, helpcontext(0x00010081)]
        HRESULT _stdcall Interior([out, retval] Interior** RHS);
        [propget, helpcontext(0x00010067)]
        HRESULT _stdcall Shadow([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010067)]
        HRESULT _stdcall Shadow([in] VARIANT_BOOL RHS);
        [helpcontext(0x000100b5)]
        HRESULT _stdcall Add(
                        [in] double Left, 
                        [in] double Top, 
                        [in] double Width, 
                        [in] double Height, 
                        [out, retval] ChartObject** RHS);
        [propget, helpcontext(0x00010076)]
        HRESULT _stdcall Count([out, retval] long* RHS);
        [hidden, helpcontext(0x0001002e)]
        HRESULT _stdcall Group([out, retval] GroupObject** RHS);
        [helpcontext(0x000100aa)]
        HRESULT _stdcall Item(
                        [in] VARIANT Index, 
                        [out, retval] IDispatch** RHS);
        [helpcontext(0x0000fffc)]
        HRESULT _stdcall _NewEnum([out, retval] IUnknown** RHS);
    };
