import "Excel12.Idl";


    [
      odl,
      uuid(000208D1-0001-0000-C000-000000000046),
      helpcontext(0x00020090),
      hidden
    ]
    interface IMailer : IDispatch {
        [propget, helpcontext(0x00010094)]
        HRESULT _stdcall Application([out, retval] Application** RHS);
        [propget, helpcontext(0x00010095)]
        HRESULT _stdcall Creator([out, retval] XlCreator* RHS);
        [propget, helpcontext(0x00010096)]
        HRESULT _stdcall Parent([out, retval] IDispatch** RHS);
        [propget, helpcontext(0x000103d7)]
        HRESULT _stdcall BCCRecipients([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x000103d7)]
        HRESULT _stdcall BCCRecipients([in] VARIANT RHS);
        [propget, helpcontext(0x000103d6)]
        HRESULT _stdcall CCRecipients([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x000103d6)]
        HRESULT _stdcall CCRecipients([in] VARIANT RHS);
        [propget, helpcontext(0x000103d8)]
        HRESULT _stdcall Enclosures([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x000103d8)]
        HRESULT _stdcall Enclosures([in] VARIANT RHS);
        [propget, helpcontext(0x000103da)]
        HRESULT _stdcall Received([out, retval] VARIANT_BOOL* RHS);
        [propget, helpcontext(0x000103db)]
        HRESULT _stdcall SendDateTime([out, retval] DATE* RHS);
        [propget, helpcontext(0x000103dc)]
        HRESULT _stdcall Sender([out, retval] BSTR* RHS);
        [propget, helpcontext(0x000103b9)]
        HRESULT _stdcall Subject([out, retval] BSTR* RHS);
        [propput, helpcontext(0x000103b9)]
        HRESULT _stdcall Subject([in] BSTR RHS);
        [propget, helpcontext(0x000103d5)]
        HRESULT _stdcall ToRecipients([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x000103d5)]
        HRESULT _stdcall ToRecipients([in] VARIANT RHS);
        [propget, helpcontext(0x000103ce)]
        HRESULT _stdcall WhichAddress([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x000103ce)]
        HRESULT _stdcall WhichAddress([in] VARIANT RHS);
    };

    [
      odl,
      uuid(00024422-0001-0000-C000-000000000046),
      helpcontext(0x000200b8),
      hidden
    ]
    interface ICustomViews : IDispatch {
        [propget, helpcontext(0x00010094)]
        HRESULT _stdcall Application([out, retval] Application** RHS);
        [propget, helpcontext(0x00010095)]
        HRESULT _stdcall Creator([out, retval] XlCreator* RHS);
        [propget, helpcontext(0x00010096)]
        HRESULT _stdcall Parent([out, retval] IDispatch** RHS);
        [propget, helpcontext(0x00010076)]
        HRESULT _stdcall Count([out, retval] long* RHS);
        [helpcontext(0x000100aa)]
        HRESULT _stdcall Item(
                        [in] VARIANT ViewName, 
                        [out, retval] CustomView** RHS);
        [helpcontext(0x000100b5)]
        HRESULT _stdcall Add(
                        [in] BSTR ViewName, 
                        [in, optional] VARIANT PrintSettings, 
                        [in, optional] VARIANT RowColSettings, 
                        [out, retval] CustomView** RHS);
        [propget, helpcontext(0x00010000)]
        HRESULT _stdcall _Default(
                        [in] VARIANT ViewName, 
                        [out, retval] CustomView** RHS);
        [propget, helpcontext(0x0000fffc)]
        HRESULT _stdcall _NewEnum([out, retval] IUnknown** RHS);
    };

    [
      odl,
      uuid(00024423-0001-0000-C000-000000000046),
      helpcontext(0x000200b9),
      hidden
    ]
    interface ICustomView : IDispatch {
        [propget, helpcontext(0x00010094)]
        HRESULT _stdcall Application([out, retval] Application** RHS);
        [propget, helpcontext(0x00010095)]
        HRESULT _stdcall Creator([out, retval] XlCreator* RHS);
        [propget, helpcontext(0x00010096)]
        HRESULT _stdcall Parent([out, retval] IDispatch** RHS);
        [propget, helpcontext(0x0001006e)]
        HRESULT _stdcall Name([out, retval] BSTR* RHS);
        [propget, helpcontext(0x00010629)]
        HRESULT _stdcall PrintSettings([out, retval] VARIANT_BOOL* RHS);
        [propget, helpcontext(0x0001062a)]
        HRESULT _stdcall RowColSettings([out, retval] VARIANT_BOOL* RHS);
        [helpcontext(0x000101f0)]
        HRESULT _stdcall Show();
        [helpcontext(0x00010075)]
        HRESULT _stdcall Delete();
    };

    [
      odl,
      uuid(00024424-0001-0000-C000-000000000046),
      helpcontext(0x000200ba),
      hidden
    ]
    interface IFormatConditions : IDispatch {
        [propget, helpcontext(0x00010094)]
        HRESULT _stdcall Application([out, retval] Application** RHS);
        [propget, helpcontext(0x00010095)]
        HRESULT _stdcall Creator([out, retval] XlCreator* RHS);
        [propget, helpcontext(0x00010096)]
        HRESULT _stdcall Parent([out, retval] IDispatch** RHS);
        [propget, helpcontext(0x00010076)]
        HRESULT _stdcall Count([out, retval] long* RHS);
        [helpcontext(0x000100aa)]
        HRESULT _stdcall Item(
                        [in] VARIANT Index, 
                        [out, retval] FormatCondition** RHS);
        [helpcontext(0x000100b5)]
        HRESULT _stdcall Add(
                        [in] XlFormatConditionType Type, 
                        [in, optional] VARIANT Operator, 
                        [in, optional] VARIANT Formula1, 
                        [in, optional] VARIANT Formula2, 
                        [out, retval] FormatCondition** RHS);
        [propget, helpcontext(0x00010000)]
        HRESULT _stdcall _Default(
                        [in] VARIANT Index, 
                        [out, retval] FormatCondition** RHS);
        [propget, helpcontext(0x0000fffc)]
        HRESULT _stdcall _NewEnum([out, retval] IUnknown** RHS);
        [helpcontext(0x00010075)]
        HRESULT _stdcall Delete();
    };

    [
      odl,
      uuid(00024425-0001-0000-C000-000000000046),
      helpcontext(0x000200bb),
      hidden
    ]
    interface IFormatCondition : IDispatch {
        [propget, helpcontext(0x00010094)]
        HRESULT _stdcall Application([out, retval] Application** RHS);
        [propget, helpcontext(0x00010095)]
        HRESULT _stdcall Creator([out, retval] XlCreator* RHS);
        [propget, helpcontext(0x00010096)]
        HRESULT _stdcall Parent([out, retval] IDispatch** RHS);
        [helpcontext(0x0001062d)]
        HRESULT _stdcall Modify(
                        [in] XlFormatConditionType Type, 
                        [in, optional] VARIANT Operator, 
                        [in, optional] VARIANT Formula1, 
                        [in, optional] VARIANT Formula2);
        [propget, helpcontext(0x0001006c)]
        HRESULT _stdcall Type([out, retval] long* RHS);
        [propget, helpcontext(0x0001031d)]
        HRESULT _stdcall Operator([out, retval] long* RHS);
        [propget, helpcontext(0x0001062b)]
        HRESULT _stdcall Formula1([out, retval] BSTR* RHS);
        [propget, helpcontext(0x0001062c)]
        HRESULT _stdcall Formula2([out, retval] BSTR* RHS);
        [propget, helpcontext(0x00010081)]
        HRESULT _stdcall Interior([out, retval] Interior** RHS);
        [propget, helpcontext(0x000101b3)]
        HRESULT _stdcall Borders([out, retval] Borders** RHS);
        [propget, helpcontext(0x00010092)]
        HRESULT _stdcall Font([out, retval] Font** RHS);
        [helpcontext(0x00010075)]
        HRESULT _stdcall Delete();
    };

    [
      odl,
      uuid(00024426-0001-0000-C000-000000000046),
      helpcontext(0x000200bc),
      hidden
    ]
    interface IComments : IDispatch {
        [propget, helpcontext(0x00010094)]
        HRESULT _stdcall Application([out, retval] Application** RHS);
        [propget, helpcontext(0x00010095)]
        HRESULT _stdcall Creator([out, retval] XlCreator* RHS);
        [propget, helpcontext(0x00010096)]
        HRESULT _stdcall Parent([out, retval] IDispatch** RHS);
        [propget, helpcontext(0x00010076)]
        HRESULT _stdcall Count([out, retval] long* RHS);
        [helpcontext(0x000100aa)]
        HRESULT _stdcall Item(
                        [in] long Index, 
                        [out, retval] Comment** RHS);
        [propget, helpcontext(0x00010000)]
        HRESULT _stdcall _Default(
                        [in] long Index, 
                        [out, retval] Comment** RHS);
        [propget, helpcontext(0x0000fffc)]
        HRESULT _stdcall _NewEnum([out, retval] IUnknown** RHS);
    };

    [
      odl,
      uuid(00024427-0001-0000-C000-000000000046),
      helpcontext(0x000200bd),
      hidden
    ]
    interface IComment : IDispatch {
        [propget, helpcontext(0x00010094)]
        HRESULT _stdcall Application([out, retval] Application** RHS);
        [propget, helpcontext(0x00010095)]
        HRESULT _stdcall Creator([out, retval] XlCreator* RHS);
        [propget, helpcontext(0x00010096)]
        HRESULT _stdcall Parent([out, retval] IDispatch** RHS);
        [propget, helpcontext(0x0001023e)]
        HRESULT _stdcall Author([out, retval] BSTR* RHS);
        [propget, helpcontext(0x0001062e)]
        HRESULT _stdcall Shape([out, retval] Shape** RHS);
        [propget, helpcontext(0x0001022e)]
        HRESULT _stdcall Visible([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x0001022e)]
        HRESULT _stdcall Visible([in] VARIANT_BOOL RHS);
        [helpcontext(0x0001008a)]
        HRESULT _stdcall Text(
                        [in, optional] VARIANT Text, 
                        [in, optional] VARIANT Start, 
                        [in, optional] VARIANT Overwrite, 
                        [out, retval] BSTR* RHS);
        [helpcontext(0x00010075)]
        HRESULT _stdcall Delete();
        [helpcontext(0x000101f6)]
        HRESULT _stdcall Next([out, retval] Comment** RHS);
        [helpcontext(0x000101f7)]
        HRESULT _stdcall Previous([out, retval] Comment** RHS);
    };

    [
      odl,
      uuid(0002441B-0001-0000-C000-000000000046),
      helpcontext(0x000200b1),
      hidden
    ]
    interface IRefreshEvents : IDispatch {
        [helpcontext(0x0001063c)]
        HRESULT _stdcall BeforeRefresh([in] VARIANT_BOOL* Cancel);
        [helpcontext(0x0001063d)]
        HRESULT _stdcall AfterRefresh([in] VARIANT_BOOL Success);
    };

    [
      odl,
      uuid(00024428-0001-0000-C000-000000000046),
      helpcontext(0x000200be),
      hidden
    ]
    interface _IQueryTable : IDispatch {
        [propget, helpcontext(0x00010094)]
        HRESULT _stdcall Application([out, retval] Application** RHS);
        [propget, helpcontext(0x00010095)]
        HRESULT _stdcall Creator([out, retval] XlCreator* RHS);
        [propget, helpcontext(0x00010096)]
        HRESULT _stdcall Parent([out, retval] IDispatch** RHS);
        [propget, helpcontext(0x0001006e)]
        HRESULT _stdcall Name([out, retval] BSTR* RHS);
        [propput, helpcontext(0x0001006e)]
        HRESULT _stdcall Name([in] BSTR RHS);
        [propget, helpcontext(0x00010630)]
        HRESULT _stdcall FieldNames([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010630)]
        HRESULT _stdcall FieldNames([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x00010631)]
        HRESULT _stdcall RowNumbers([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010631)]
        HRESULT _stdcall RowNumbers([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x00010632)]
        HRESULT _stdcall FillAdjacentFormulas([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010632)]
        HRESULT _stdcall FillAdjacentFormulas([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x000102b7)]
        HRESULT _stdcall HasAutoFormat([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x000102b7)]
        HRESULT _stdcall HasAutoFormat([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x000105c7)]
        HRESULT _stdcall RefreshOnFileOpen([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x000105c7)]
        HRESULT _stdcall RefreshOnFileOpen([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x00010633)]
        HRESULT _stdcall Refreshing([out, retval] VARIANT_BOOL* RHS);
        [propget, helpcontext(0x00010634)]
        HRESULT _stdcall FetchedRowOverflow([out, retval] VARIANT_BOOL* RHS);
        [propget, helpcontext(0x00010593)]
        HRESULT _stdcall BackgroundQuery([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010593)]
        HRESULT _stdcall BackgroundQuery([in] VARIANT_BOOL RHS);
        [helpcontext(0x00010635)]
        HRESULT _stdcall CancelRefresh();
        [propget, helpcontext(0x00010636)]
        HRESULT _stdcall RefreshStyle([out, retval] XlCellInsertionMode* RHS);
        [propput, helpcontext(0x00010636)]
        HRESULT _stdcall RefreshStyle([in] XlCellInsertionMode RHS);
        [propget, helpcontext(0x000105c5)]
        HRESULT _stdcall EnableRefresh([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x000105c5)]
        HRESULT _stdcall EnableRefresh([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x000105c9)]
        HRESULT _stdcall SavePassword([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x000105c9)]
        HRESULT _stdcall SavePassword([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x000102a9)]
        HRESULT _stdcall Destination([out, retval] Range** RHS);
        [propget, helpcontext(0x00010598)]
        HRESULT _stdcall Connection([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010598)]
        HRESULT _stdcall Connection([in] VARIANT RHS);
        [propget, helpcontext(0x000105c8)]
        HRESULT _stdcall Sql([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x000105c8)]
        HRESULT _stdcall Sql([in] VARIANT RHS);
        [propget, helpcontext(0x00010637)]
        HRESULT _stdcall PostText([out, retval] BSTR* RHS);
        [propput, helpcontext(0x00010637)]
        HRESULT _stdcall PostText([in] BSTR RHS);
        [propget, helpcontext(0x00010638)]
        HRESULT _stdcall ResultRange([out, retval] Range** RHS);
        [helpcontext(0x00010075)]
        HRESULT _stdcall Delete();
        [helpcontext(0x00010589)]
        HRESULT _stdcall Refresh(
                        [in, optional] VARIANT BackgroundQuery, 
                        [out, retval] VARIANT_BOOL* RHS);
        [propget, helpcontext(0x00010639)]
        HRESULT _stdcall Parameters([out, retval] Parameters** RHS);
        [propget, helpcontext(0x0001048d)]
        HRESULT _stdcall Recordset([out, retval] IDispatch** RHS);
        [propputref, helpcontext(0x0001048d)]
        HRESULT _stdcall Recordset([in] IDispatch* RHS);
        [propget, helpcontext(0x000102b4)]
        HRESULT _stdcall SaveData([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x000102b4)]
        HRESULT _stdcall SaveData([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x0001063a)]
        HRESULT _stdcall TablesOnlyFromHTML([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x0001063a)]
        HRESULT _stdcall TablesOnlyFromHTML([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x0001063b)]
        HRESULT _stdcall EnableEditing([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x0001063b)]
        HRESULT _stdcall EnableEditing([in] VARIANT_BOOL RHS);
    };

    [
      odl,
      uuid(00024429-0001-0000-C000-000000000046),
      helpcontext(0x000200bf),
      hidden
    ]
    interface IQueryTables : IDispatch {
        [propget, helpcontext(0x00010094)]
        HRESULT _stdcall Application([out, retval] Application** RHS);
        [propget, helpcontext(0x00010095)]
        HRESULT _stdcall Creator([out, retval] XlCreator* RHS);
        [propget, helpcontext(0x00010096)]
        HRESULT _stdcall Parent([out, retval] IDispatch** RHS);
        [propget, helpcontext(0x00010076)]
        HRESULT _stdcall Count([out, retval] long* RHS);
        [helpcontext(0x000100b5)]
        HRESULT _stdcall Add(
                        [in] VARIANT Connection, 
                        [in] Range* Destination, 
                        [in, optional] VARIANT Sql, 
                        [out, retval] QueryTable** RHS);
        [helpcontext(0x000100aa)]
        HRESULT _stdcall Item(
                        [in] VARIANT Index, 
                        [out, retval] QueryTable** RHS);
        [propget, helpcontext(0x00010000)]
        HRESULT _stdcall _Default(
                        [in] VARIANT Index, 
                        [out, retval] QueryTable** RHS);
        [helpcontext(0x0000fffc)]
        HRESULT _stdcall _NewEnum([out, retval] IUnknown** RHS);
    };

    [
      odl,
      uuid(0002442A-0001-0000-C000-000000000046),
      helpcontext(0x000200c0),
      hidden
    ]
    interface IParameter : IDispatch {
        [propget, helpcontext(0x00010094)]
        HRESULT _stdcall Application([out, retval] Application** RHS);
        [propget, helpcontext(0x00010095)]
        HRESULT _stdcall Creator([out, retval] XlCreator* RHS);
        [propget, helpcontext(0x00010096)]
        HRESULT _stdcall Parent([out, retval] IDispatch** RHS);
        [propget, helpcontext(0x000102d2)]
        HRESULT _stdcall DataType([out, retval] XlParameterDataType* RHS);
        [propput, helpcontext(0x000102d2)]
        HRESULT _stdcall DataType([in] XlParameterDataType RHS);
        [propget, helpcontext(0x0001006c)]
        HRESULT _stdcall Type([out, retval] XlParameterType* RHS);
        [propget, helpcontext(0x0001063f)]
        HRESULT _stdcall PromptString([out, retval] BSTR* RHS);
        [propget, helpcontext(0x00010006)]
        HRESULT _stdcall Value([out, retval] VARIANT* RHS);
        [propget, helpcontext(0x00010640)]
        HRESULT _stdcall SourceRange([out, retval] Range** RHS);
        [propget, helpcontext(0x0001006e)]
        HRESULT _stdcall Name([out, retval] BSTR* RHS);
        [propput, helpcontext(0x0001006e)]
        HRESULT _stdcall Name([in] BSTR RHS);
        [helpcontext(0x00010641)]
        HRESULT _stdcall SetParam(
                        [in] XlParameterType Type, 
                        [in] VARIANT Value);
    };

    [
      odl,
      uuid(0002442B-0001-0000-C000-000000000046),
      helpcontext(0x000200c1),
      hidden
    ]
    interface IParameters : IDispatch {
        [propget, helpcontext(0x00010094)]
        HRESULT _stdcall Application([out, retval] Application** RHS);
        [propget, helpcontext(0x00010095)]
        HRESULT _stdcall Creator([out, retval] XlCreator* RHS);
        [propget, helpcontext(0x00010096)]
        HRESULT _stdcall Parent([out, retval] IDispatch** RHS);
        [helpcontext(0x000100b5)]
        HRESULT _stdcall Add(
                        [in] BSTR Name, 
                        [in, optional] VARIANT iDataType, 
                        [out, retval] Parameter** RHS);
        [propget, helpcontext(0x00010076)]
        HRESULT _stdcall Count([out, retval] long* RHS);
        [helpcontext(0x000100aa)]
        HRESULT _stdcall Item(
                        [in] VARIANT Index, 
                        [out, retval] Parameter** RHS);
        [propget, helpcontext(0x00010000)]
        HRESULT _stdcall _Default(
                        [in] VARIANT Index, 
                        [out, retval] Parameter** RHS);
        [helpcontext(0x00010075)]
        HRESULT _stdcall Delete();
        [helpcontext(0x0000fffc)]
        HRESULT _stdcall _NewEnum([out, retval] IUnknown** RHS);
    };

    [
      odl,
      uuid(0002442C-0001-0000-C000-000000000046),
      helpcontext(0x000200c2),
      hidden
    ]
    interface IODBCError : IDispatch {
        [propget, helpcontext(0x00010094)]
        HRESULT _stdcall Application([out, retval] Application** RHS);
        [propget, helpcontext(0x00010095)]
        HRESULT _stdcall Creator([out, retval] XlCreator* RHS);
        [propget, helpcontext(0x00010096)]
        HRESULT _stdcall Parent([out, retval] IDispatch** RHS);
        [propget, helpcontext(0x00010643)]
        HRESULT _stdcall SqlState([out, retval] BSTR* RHS);
        [propget, helpcontext(0x000105d2)]
        HRESULT _stdcall ErrorString([out, retval] BSTR* RHS);
    };

    [
      odl,
      uuid(0002442D-0001-0000-C000-000000000046),
      helpcontext(0x000200c3),
      hidden
    ]
    interface IODBCErrors : IDispatch {
        [propget, helpcontext(0x00010094)]
        HRESULT _stdcall Application([out, retval] Application** RHS);
        [propget, helpcontext(0x00010095)]
        HRESULT _stdcall Creator([out, retval] XlCreator* RHS);
        [propget, helpcontext(0x00010096)]
        HRESULT _stdcall Parent([out, retval] IDispatch** RHS);
        [propget, helpcontext(0x00010076)]
        HRESULT _stdcall Count([out, retval] long* RHS);
        [helpcontext(0x000100aa)]
        HRESULT _stdcall Item(
                        [in] long Index, 
                        [out, retval] ODBCError** RHS);
        [propget, helpcontext(0x00010000)]
        HRESULT _stdcall _Default(
                        [in] long Index, 
                        [out, retval] ODBCError** RHS);
        [helpcontext(0x0000fffc)]
        HRESULT _stdcall _NewEnum([out, retval] IUnknown** RHS);
    };

    [
      odl,
      uuid(0002442F-0001-0000-C000-000000000046),
      helpcontext(0x000200c5),
      hidden
    ]
    interface IValidation : IDispatch {
        [propget, helpcontext(0x00010094)]
        HRESULT _stdcall Application([out, retval] Application** RHS);
        [propget, helpcontext(0x00010095)]
        HRESULT _stdcall Creator([out, retval] XlCreator* RHS);
        [propget, helpcontext(0x00010096)]
        HRESULT _stdcall Parent([out, retval] IDispatch** RHS);
        [helpcontext(0x000100b5)]
        HRESULT _stdcall Add(
                        [in] XlDVType Type, 
                        [in, optional] VARIANT AlertStyle, 
                        [in, optional] VARIANT Operator, 
                        [in, optional] VARIANT Formula1, 
                        [in, optional] VARIANT Formula2);
        [propget, helpcontext(0x00010645)]
        HRESULT _stdcall AlertStyle([out, retval] long* RHS);
        [propget, helpcontext(0x00010646)]
        HRESULT _stdcall IgnoreBlank([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010646)]
        HRESULT _stdcall IgnoreBlank([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x00010647)]
        HRESULT _stdcall IMEMode([out, retval] long* RHS);
        [propput, helpcontext(0x00010647)]
        HRESULT _stdcall IMEMode([in] long RHS);
        [propget, helpcontext(0x00010648)]
        HRESULT _stdcall InCellDropdown([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010648)]
        HRESULT _stdcall InCellDropdown([in] VARIANT_BOOL RHS);
        [helpcontext(0x00010075)]
        HRESULT _stdcall Delete();
        [propget, helpcontext(0x00010649)]
        HRESULT _stdcall ErrorMessage([out, retval] BSTR* RHS);
        [propput, helpcontext(0x00010649)]
        HRESULT _stdcall ErrorMessage([in] BSTR RHS);
        [propget, helpcontext(0x0001064a)]
        HRESULT _stdcall ErrorTitle([out, retval] BSTR* RHS);
        [propput, helpcontext(0x0001064a)]
        HRESULT _stdcall ErrorTitle([in] BSTR RHS);
        [propget, helpcontext(0x0001064b)]
        HRESULT _stdcall InputMessage([out, retval] BSTR* RHS);
        [propput, helpcontext(0x0001064b)]
        HRESULT _stdcall InputMessage([in] BSTR RHS);
        [propget, helpcontext(0x0001064c)]
        HRESULT _stdcall InputTitle([out, retval] BSTR* RHS);
        [propput, helpcontext(0x0001064c)]
        HRESULT _stdcall InputTitle([in] BSTR RHS);
        [propget, helpcontext(0x0001062b)]
        HRESULT _stdcall Formula1([out, retval] BSTR* RHS);
        [propget, helpcontext(0x0001062c)]
        HRESULT _stdcall Formula2([out, retval] BSTR* RHS);
        [helpcontext(0x0001062d)]
        HRESULT _stdcall Modify(
                        [in, optional] VARIANT Type, 
                        [in, optional] VARIANT AlertStyle, 
                        [in, optional] VARIANT Operator, 
                        [in, optional] VARIANT Formula1, 
                        [in, optional] VARIANT Formula2);
        [propget, helpcontext(0x0001031d)]
        HRESULT _stdcall Operator([out, retval] long* RHS);
        [propget, helpcontext(0x0001064d)]
        HRESULT _stdcall ShowError([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x0001064d)]
        HRESULT _stdcall ShowError([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x0001064e)]
        HRESULT _stdcall ShowInput([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x0001064e)]
        HRESULT _stdcall ShowInput([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x0001006c)]
        HRESULT _stdcall Type([out, retval] long* RHS);
        [propget, helpcontext(0x00010006)]
        HRESULT _stdcall Value([out, retval] VARIANT_BOOL* RHS);
    };

    [
      odl,
      uuid(00024430-0001-0000-C000-000000000046),
      helpcontext(0x000200c6),
      hidden
    ]
    interface IHyperlinks : IDispatch {
        [propget, helpcontext(0x00010094)]
        HRESULT _stdcall Application([out, retval] Application** RHS);
        [propget, helpcontext(0x00010095)]
        HRESULT _stdcall Creator([out, retval] XlCreator* RHS);
        [propget, helpcontext(0x00010096)]
        HRESULT _stdcall Parent([out, retval] IDispatch** RHS);
        [helpcontext(0x000100b5)]
        HRESULT _stdcall Add(
                        [in] IDispatch* Anchor, 
                        [in] BSTR Address, 
                        [in, optional] VARIANT SubAddress, 
                        [out, retval] IDispatch** RHS);
        [propget, helpcontext(0x00010076)]
        HRESULT _stdcall Count([out, retval] long* RHS);
        [propget, helpcontext(0x000100aa)]
        HRESULT _stdcall Item(
                        [in] VARIANT Index, 
                        [out, retval] Hyperlink** RHS);
        [propget, helpcontext(0x00010000)]
        HRESULT _stdcall _Default(
                        [in] VARIANT Index, 
                        [out, retval] Hyperlink** RHS);
        [propget, helpcontext(0x0000fffc)]
        HRESULT _stdcall _NewEnum([out, retval] IUnknown** RHS);
        [helpcontext(0x00010075)]
        HRESULT _stdcall Delete();
    };

    [
      odl,
      uuid(00024431-0001-0000-C000-000000000046),
      helpcontext(0x000200c7),
      hidden
    ]
    interface IHyperlink : IDispatch {
        [propget, helpcontext(0x00010094)]
        HRESULT _stdcall Application([out, retval] Application** RHS);
        [propget, helpcontext(0x00010095)]
        HRESULT _stdcall Creator([out, retval] XlCreator* RHS);
        [propget, helpcontext(0x00010096)]
        HRESULT _stdcall Parent([out, retval] IDispatch** RHS);
        [propget, helpcontext(0x0001006e)]
        HRESULT _stdcall Name([out, retval] BSTR* RHS);
        [propget, helpcontext(0x000100c5)]
        HRESULT _stdcall Range([out, retval] Range** RHS);
        [propget, helpcontext(0x0001062e)]
        HRESULT _stdcall Shape([out, retval] Shape** RHS);
        [propget, helpcontext(0x000105bf)]
        HRESULT _stdcall SubAddress([out, retval] BSTR* RHS);
        [propput, helpcontext(0x000105bf)]
        HRESULT _stdcall SubAddress([in] BSTR RHS);
        [propget, helpcontext(0x000100ec)]
        HRESULT _stdcall Address([out, retval] BSTR* RHS);
        [propput, helpcontext(0x000100ec)]
        HRESULT _stdcall Address([in] BSTR RHS);
        [propget, helpcontext(0x0001006c)]
        HRESULT _stdcall Type([out, retval] long* RHS);
        [helpcontext(0x000105c4)]
        HRESULT _stdcall AddToFavorites();
        [helpcontext(0x00010075)]
        HRESULT _stdcall Delete();
        [helpcontext(0x00010650)]
        HRESULT _stdcall Follow(
                        [in, optional] VARIANT NewWindow, 
                        [in, optional] VARIANT AddHistory, 
                        [in, optional] VARIANT ExtraInfo, 
                        [in, optional] VARIANT Method, 
                        [in, optional] VARIANT HeaderInfo);
    };

    [
      odl,
      uuid(00024432-0001-0000-C000-000000000046),
      helpcontext(0x000200c8),
      hidden
    ]
    interface IAutoFilter : IDispatch {
        [propget, helpcontext(0x00010094)]
        HRESULT _stdcall Application([out, retval] Application** RHS);
        [propget, helpcontext(0x00010095)]
        HRESULT _stdcall Creator([out, retval] XlCreator* RHS);
        [propget, helpcontext(0x00010096)]
        HRESULT _stdcall Parent([out, retval] IDispatch** RHS);
        [propget, helpcontext(0x000100c5)]
        HRESULT _stdcall Range([out, retval] Range** RHS);
        [propget, helpcontext(0x00010651)]
        HRESULT _stdcall Filters([out, retval] Filters** RHS);
    };

    [
      odl,
      uuid(00024433-0001-0000-C000-000000000046),
      helpcontext(0x000200c9),
      hidden
    ]
    interface IFilters : IDispatch {
        [propget, helpcontext(0x00010094)]
        HRESULT _stdcall Application([out, retval] Application** RHS);
        [propget, helpcontext(0x00010095)]
        HRESULT _stdcall Creator([out, retval] XlCreator* RHS);
        [propget, helpcontext(0x00010096)]
        HRESULT _stdcall Parent([out, retval] IDispatch** RHS);
        [propget, helpcontext(0x00010076)]
        HRESULT _stdcall Count([out, retval] long* RHS);
        [propget, helpcontext(0x00010000)]
        HRESULT _stdcall _Default(
                        [in] long Index, 
                        [out, retval] Filter** RHS);
        [propget, helpcontext(0x000100aa)]
        HRESULT _stdcall Item(
                        [in] long Index, 
                        [out, retval] Filter** RHS);
        [propget, helpcontext(0x0000fffc)]
        HRESULT _stdcall _NewEnum([out, retval] IUnknown** RHS);
    };

    [
      odl,
      uuid(00024434-0001-0000-C000-000000000046),
      helpcontext(0x000200ca),
      hidden
    ]
    interface IFilter : IDispatch {
        [propget, helpcontext(0x00010094)]
        HRESULT _stdcall Application([out, retval] Application** RHS);
        [propget, helpcontext(0x00010095)]
        HRESULT _stdcall Creator([out, retval] XlCreator* RHS);
        [propget, helpcontext(0x00010096)]
        HRESULT _stdcall Parent([out, retval] IDispatch** RHS);
        [propget, helpcontext(0x00010652)]
        HRESULT _stdcall On([out, retval] VARIANT_BOOL* RHS);
        [propget, helpcontext(0x0001031c)]
        HRESULT _stdcall Criteria1([out, retval] VARIANT* RHS);
        [propget, helpcontext(0x0001031d)]
        HRESULT _stdcall Operator([out, retval] XlAutoFilterOperator* RHS);
        [propget, helpcontext(0x0001031e)]
        HRESULT _stdcall Criteria2([out, retval] VARIANT* RHS);
    };

    [
      odl,
      uuid(000208D4-0001-0000-C000-000000000046),
      helpcontext(0x00020093),
      hidden
    ]
    interface IAutoCorrect : IDispatch {
        [propget, helpcontext(0x00010094)]
        HRESULT _stdcall Application([out, retval] Application** RHS);
        [propget, helpcontext(0x00010095)]
        HRESULT _stdcall Creator([out, retval] XlCreator* RHS);
        [propget, helpcontext(0x00010096)]
        HRESULT _stdcall Parent([out, retval] IDispatch** RHS);
        [helpcontext(0x0001047a)]
        HRESULT _stdcall AddReplacement(
                        [in] BSTR What, 
                        [in] BSTR Replacement);
        [propget, helpcontext(0x0001047e)]
        HRESULT _stdcall CapitalizeNamesOfDays([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x0001047e)]
        HRESULT _stdcall CapitalizeNamesOfDays([in] VARIANT_BOOL RHS);
        [helpcontext(0x0001047b)]
        HRESULT _stdcall DeleteReplacement([in] BSTR What);
        [helpcontext(0x0001047f)]
        HRESULT _stdcall ReplacementList(
                        [in, optional] VARIANT Index, 
                        [out, retval] VARIANT* RHS);
        [propget, helpcontext(0x0001047c)]
        HRESULT _stdcall ReplaceText([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x0001047c)]
        HRESULT _stdcall ReplaceText([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x0001047d)]
        HRESULT _stdcall TwoInitialCapitals([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x0001047d)]
        HRESULT _stdcall TwoInitialCapitals([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x00010653)]
        HRESULT _stdcall CorrectSentenceCap([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010653)]
        HRESULT _stdcall CorrectSentenceCap([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x00010654)]
        HRESULT _stdcall CorrectCapsLock([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010654)]
        HRESULT _stdcall CorrectCapsLock([in] VARIANT_BOOL RHS);
    };

    [
      odl,
      uuid(00020854-0001-0000-C000-000000000046),
      helpcontext(0x00020014),
      hidden
    ]
    interface IBorder : IDispatch {
        [propget, helpcontext(0x00010094)]
        HRESULT _stdcall Application([out, retval] Application** RHS);
        [propget, helpcontext(0x00010095)]
        HRESULT _stdcall Creator([out, retval] XlCreator* RHS);
        [propget, helpcontext(0x00010096)]
        HRESULT _stdcall Parent([out, retval] IDispatch** RHS);
        [propget, helpcontext(0x00010063)]
        HRESULT _stdcall Color([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010063)]
        HRESULT _stdcall Color([in] VARIANT RHS);
        [propget, helpcontext(0x00010061)]
        HRESULT _stdcall ColorIndex([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010061)]
        HRESULT _stdcall ColorIndex([in] VARIANT RHS);
        [propget, helpcontext(0x00010077)]
        HRESULT _stdcall LineStyle([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010077)]
        HRESULT _stdcall LineStyle([in] VARIANT RHS);
        [propget, helpcontext(0x00010078)]
        HRESULT _stdcall Weight([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010078)]
        HRESULT _stdcall Weight([in] VARIANT RHS);
    };

    [
      odl,
      uuid(00020870-0001-0000-C000-000000000046),
      helpcontext(0x00020030),
      hidden
    ]
    interface IInterior : IDispatch {
        [propget, helpcontext(0x00010094)]
        HRESULT _stdcall Application([out, retval] Application** RHS);
        [propget, helpcontext(0x00010095)]
        HRESULT _stdcall Creator([out, retval] XlCreator* RHS);
        [propget, helpcontext(0x00010096)]
        HRESULT _stdcall Parent([out, retval] IDispatch** RHS);
        [propget, helpcontext(0x00010063)]
        HRESULT _stdcall Color([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010063)]
        HRESULT _stdcall Color([in] VARIANT RHS);
        [propget, helpcontext(0x00010061)]
        HRESULT _stdcall ColorIndex([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010061)]
        HRESULT _stdcall ColorIndex([in] VARIANT RHS);
        [propget, helpcontext(0x00010084)]
        HRESULT _stdcall InvertIfNegative([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010084)]
        HRESULT _stdcall InvertIfNegative([in] VARIANT RHS);
        [propget, helpcontext(0x0001005f)]
        HRESULT _stdcall Pattern([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x0001005f)]
        HRESULT _stdcall Pattern([in] VARIANT RHS);
        [propget, helpcontext(0x00010064)]
        HRESULT _stdcall PatternColor([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010064)]
        HRESULT _stdcall PatternColor([in] VARIANT RHS);
        [propget, helpcontext(0x00010062)]
        HRESULT _stdcall PatternColorIndex([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010062)]
        HRESULT _stdcall PatternColorIndex([in] VARIANT RHS);
    };

    [
      odl,
      uuid(00024435-0001-0000-C000-000000000046),
      helpcontext(0x000200cb),
      hidden
    ]
    interface IChartFillFormat : IDispatch {
        [propget, helpcontext(0x00010094)]
        HRESULT _stdcall Application([out, retval] Application** RHS);
        [propget, helpcontext(0x00010095)]
        HRESULT _stdcall Creator([out, retval] XlCreator* RHS);
        [propget, helpcontext(0x00010096)]
        HRESULT _stdcall Parent([out, retval] IDispatch** RHS);
        [helpcontext(0x00010655)]
        HRESULT _stdcall OneColorGradient(
                        [in] MsoGradientStyle Style, 
                        [in] long Variant, 
                        [in] single Degree);
        [helpcontext(0x00010658)]
        HRESULT _stdcall TwoColorGradient(
                        [in] MsoGradientStyle Style, 
                        [in] long Variant);
        [helpcontext(0x00010659)]
        HRESULT _stdcall PresetTextured([in] MsoPresetTexture PresetTexture);
        [helpcontext(0x0001065b)]
        HRESULT _stdcall Solid();
        [helpcontext(0x0001065c)]
        HRESULT _stdcall Patterned([in] MsoPatternType Pattern);
        [helpcontext(0x0001065d)]
        HRESULT _stdcall UserPicture(
                        [in, optional] VARIANT PictureFile, 
                        [in, optional] VARIANT PictureFormat, 
                        [in, optional] VARIANT PictureStackUnit, 
                        [in, optional] VARIANT PicturePlacement);
        [helpcontext(0x00010662)]
        HRESULT _stdcall UserTextured([in] BSTR TextureFile);
        [helpcontext(0x00010664)]
        HRESULT _stdcall PresetGradient(
                        [in] MsoGradientStyle Style, 
                        [in] long Variant, 
                        [in] MsoPresetGradientType PresetGradientType);
        [propget, helpcontext(0x00010666)]
        HRESULT _stdcall BackColor([out, retval] ChartColorFormat** RHS);
        [propget, helpcontext(0x00010667)]
        HRESULT _stdcall ForeColor([out, retval] ChartColorFormat** RHS);
        [propget, helpcontext(0x00010668)]
        HRESULT _stdcall GradientColorType([out, retval] MsoGradientColorType* RHS);
        [propget, helpcontext(0x00010669)]
        HRESULT _stdcall GradientDegree([out, retval] single* RHS);
        [propget, helpcontext(0x0001066a)]
        HRESULT _stdcall GradientStyle([out, retval] MsoGradientStyle* RHS);
        [propget, helpcontext(0x0001066b)]
        HRESULT _stdcall GradientVariant([out, retval] long* RHS);
        [propget, helpcontext(0x0001005f)]
        HRESULT _stdcall Pattern([out, retval] MsoPatternType* RHS);
        [propget, helpcontext(0x00010665)]
        HRESULT _stdcall PresetGradientType([out, retval] MsoPresetGradientType* RHS);
        [propget, helpcontext(0x0001065a)]
        HRESULT _stdcall PresetTexture([out, retval] MsoPresetTexture* RHS);
        [propget, helpcontext(0x0001066c)]
        HRESULT _stdcall TextureName([out, retval] BSTR* RHS);
        [propget, helpcontext(0x0001066d)]
        HRESULT _stdcall TextureType([out, retval] MsoTextureType* RHS);
        [propget, helpcontext(0x0001006c)]
        HRESULT _stdcall Type([out, retval] MsoFillType* RHS);
        [propget, helpcontext(0x0001022e)]
        HRESULT _stdcall Visible([out, retval] MsoTriState* RHS);
        [propput, helpcontext(0x0001022e)]
        HRESULT _stdcall Visible([in] MsoTriState RHS);
    };

    [
      odl,
      uuid(00024436-0001-0000-C000-000000000046),
      helpcontext(0x000200cc),
      hidden
    ]
    interface IChartColorFormat : IDispatch {
        [propget, helpcontext(0x00010094)]
        HRESULT _stdcall Application([out, retval] Application** RHS);
        [propget, helpcontext(0x00010095)]
        HRESULT _stdcall Creator([out, retval] XlCreator* RHS);
        [propget, helpcontext(0x00010096)]
        HRESULT _stdcall Parent([out, retval] IDispatch** RHS);
        [propget, helpcontext(0x0001066e)]
        HRESULT _stdcall SchemeColor([out, retval] long* RHS);
        [propput, helpcontext(0x0001066e)]
        HRESULT _stdcall SchemeColor([in] long RHS);
        [propget, helpcontext(0x0001041f)]
        HRESULT _stdcall RGB([out, retval] long* RHS);
        [propget, helpcontext(0x00010000)]
        HRESULT _stdcall _Default([out, retval] long* RHS);
        [propget, helpcontext(0x0001006c)]
        HRESULT _stdcall Type([out, retval] long* RHS);
    };

    [
      odl,
      uuid(00020848-0001-0000-C000-000000000046),
      helpcontext(0x00020008),
      hidden
    ]
    interface IAxis : IDispatch {
        [propget, helpcontext(0x00010094)]
        HRESULT _stdcall Application([out, retval] Application** RHS);
        [propget, helpcontext(0x00010095)]
        HRESULT _stdcall Creator([out, retval] XlCreator* RHS);
        [propget, helpcontext(0x00010096)]
        HRESULT _stdcall Parent([out, retval] IDispatch** RHS);
        [propget, helpcontext(0x0001002d)]
        HRESULT _stdcall AxisBetweenCategories([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x0001002d)]
        HRESULT _stdcall AxisBetweenCategories([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x0001002f)]
        HRESULT _stdcall AxisGroup([out, retval] XlAxisGroup* RHS);
        [propget, helpcontext(0x00010052)]
        HRESULT _stdcall AxisTitle([out, retval] AxisTitle** RHS);
        [propget, helpcontext(0x00010080)]
        HRESULT _stdcall Border([out, retval] Border** RHS);
        [propget, helpcontext(0x0001009c)]
        HRESULT _stdcall CategoryNames([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x0001009c)]
        HRESULT _stdcall CategoryNames([in] VARIANT RHS);
        [propget, helpcontext(0x0001002a)]
        HRESULT _stdcall Crosses([out, retval] XlAxisCrosses* RHS);
        [propput, helpcontext(0x0001002a)]
        HRESULT _stdcall Crosses([in] XlAxisCrosses RHS);
        [propget, helpcontext(0x0001002b)]
        HRESULT _stdcall CrossesAt([out, retval] double* RHS);
        [propput, helpcontext(0x0001002b)]
        HRESULT _stdcall CrossesAt([in] double RHS);
        [helpcontext(0x00010075)]
        HRESULT _stdcall Delete();
        [propget, helpcontext(0x00010018)]
        HRESULT _stdcall HasMajorGridlines([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010018)]
        HRESULT _stdcall HasMajorGridlines([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x00010019)]
        HRESULT _stdcall HasMinorGridlines([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010019)]
        HRESULT _stdcall HasMinorGridlines([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x00010036)]
        HRESULT _stdcall HasTitle([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010036)]
        HRESULT _stdcall HasTitle([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x00010059)]
        HRESULT _stdcall MajorGridlines([out, retval] Gridlines** RHS);
        [propget, helpcontext(0x0001001a)]
        HRESULT _stdcall MajorTickMark([out, retval] XlTickMark* RHS);
        [propput, helpcontext(0x0001001a)]
        HRESULT _stdcall MajorTickMark([in] XlTickMark RHS);
        [propget, helpcontext(0x00010025)]
        HRESULT _stdcall MajorUnit([out, retval] double* RHS);
        [propput, helpcontext(0x00010025)]
        HRESULT _stdcall MajorUnit([in] double RHS);
        [propget, helpcontext(0x00010026)]
        HRESULT _stdcall MajorUnitIsAuto([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010026)]
        HRESULT _stdcall MajorUnitIsAuto([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x00010023)]
        HRESULT _stdcall MaximumScale([out, retval] double* RHS);
        [propput, helpcontext(0x00010023)]
        HRESULT _stdcall MaximumScale([in] double RHS);
        [propget, helpcontext(0x00010024)]
        HRESULT _stdcall MaximumScaleIsAuto([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010024)]
        HRESULT _stdcall MaximumScaleIsAuto([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x00010021)]
        HRESULT _stdcall MinimumScale([out, retval] double* RHS);
        [propput, helpcontext(0x00010021)]
        HRESULT _stdcall MinimumScale([in] double RHS);
        [propget, helpcontext(0x00010022)]
        HRESULT _stdcall MinimumScaleIsAuto([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010022)]
        HRESULT _stdcall MinimumScaleIsAuto([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x0001005a)]
        HRESULT _stdcall MinorGridlines([out, retval] Gridlines** RHS);
        [propget, helpcontext(0x0001001b)]
        HRESULT _stdcall MinorTickMark([out, retval] XlTickMark* RHS);
        [propput, helpcontext(0x0001001b)]
        HRESULT _stdcall MinorTickMark([in] XlTickMark RHS);
        [propget, helpcontext(0x00010027)]
        HRESULT _stdcall MinorUnit([out, retval] double* RHS);
        [propput, helpcontext(0x00010027)]
        HRESULT _stdcall MinorUnit([in] double RHS);
        [propget, helpcontext(0x00010028)]
        HRESULT _stdcall MinorUnitIsAuto([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010028)]
        HRESULT _stdcall MinorUnitIsAuto([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x0001002c)]
        HRESULT _stdcall ReversePlotOrder([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x0001002c)]
        HRESULT _stdcall ReversePlotOrder([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x00010029)]
        HRESULT _stdcall ScaleType([out, retval] XlScaleType* RHS);
        [propput, helpcontext(0x00010029)]
        HRESULT _stdcall ScaleType([in] XlScaleType RHS);
        [helpcontext(0x000100eb)]
        HRESULT _stdcall Select();
        [propget, helpcontext(0x0001001c)]
        HRESULT _stdcall TickLabelPosition([out, retval] XlTickLabelPosition* RHS);
        [propput, helpcontext(0x0001001c)]
        HRESULT _stdcall TickLabelPosition([in] XlTickLabelPosition RHS);
        [propget, helpcontext(0x0001005b)]
        HRESULT _stdcall TickLabels([out, retval] TickLabels** RHS);
        [propget, helpcontext(0x0001001d)]
        HRESULT _stdcall TickLabelSpacing([out, retval] long* RHS);
        [propput, helpcontext(0x0001001d)]
        HRESULT _stdcall TickLabelSpacing([in] long RHS);
        [propget, helpcontext(0x0001001f)]
        HRESULT _stdcall TickMarkSpacing([out, retval] long* RHS);
        [propput, helpcontext(0x0001001f)]
        HRESULT _stdcall TickMarkSpacing([in] long RHS);
        [propget, helpcontext(0x0001006c)]
        HRESULT _stdcall Type([out, retval] XlAxisType* RHS);
        [propput, helpcontext(0x0001006c)]
        HRESULT _stdcall Type([in] XlAxisType RHS);
        [propget, helpcontext(0x0001066f)]
        HRESULT _stdcall BaseUnit([out, retval] XlTimeUnit* RHS);
        [propput, helpcontext(0x0001066f)]
        HRESULT _stdcall BaseUnit([in] XlTimeUnit RHS);
        [propget, helpcontext(0x00010670)]
        HRESULT _stdcall BaseUnitIsAuto([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010670)]
        HRESULT _stdcall BaseUnitIsAuto([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x00010671)]
        HRESULT _stdcall MajorUnitScale([out, retval] XlTimeUnit* RHS);
        [propput, helpcontext(0x00010671)]
        HRESULT _stdcall MajorUnitScale([in] XlTimeUnit RHS);
        [propget, helpcontext(0x00010672)]
        HRESULT _stdcall MinorUnitScale([out, retval] XlTimeUnit* RHS);
        [propput, helpcontext(0x00010672)]
        HRESULT _stdcall MinorUnitScale([in] XlTimeUnit RHS);
        [propget, helpcontext(0x00010673)]
        HRESULT _stdcall CategoryType([out, retval] XlCategoryType* RHS);
        [propput, helpcontext(0x00010673)]
        HRESULT _stdcall CategoryType([in] XlCategoryType RHS);
        [propget, helpcontext(0x0001007f)]
        HRESULT _stdcall Left([out, retval] double* RHS);
        [propget, helpcontext(0x0001007e)]
        HRESULT _stdcall Top([out, retval] double* RHS);
        [propget, helpcontext(0x0001007a)]
        HRESULT _stdcall Width([out, retval] double* RHS);
        [propget, helpcontext(0x0001007b)]
        HRESULT _stdcall Height([out, retval] double* RHS);
    };

    [
      odl,
      uuid(00020849-0001-0000-C000-000000000046),
      helpcontext(0x00020009),
      hidden
    ]
    interface IChartTitle : IDispatch {
        [propget, helpcontext(0x00010094)]
        HRESULT _stdcall Application([out, retval] Application** RHS);
        [propget, helpcontext(0x00010095)]
        HRESULT _stdcall Creator([out, retval] XlCreator* RHS);
        [propget, helpcontext(0x00010096)]
        HRESULT _stdcall Parent([out, retval] IDispatch** RHS);
        [propget, helpcontext(0x0001006e)]
        HRESULT _stdcall Name([out, retval] BSTR* RHS);
        [helpcontext(0x000100eb)]
        HRESULT _stdcall Select();
        [propget, helpcontext(0x00010080)]
        HRESULT _stdcall Border([out, retval] Border** RHS);
        [helpcontext(0x00010075)]
        HRESULT _stdcall Delete();
        [propget, helpcontext(0x00010081)]
        HRESULT _stdcall Interior([out, retval] Interior** RHS);
        [propget, helpcontext(0x0001067f)]
        HRESULT _stdcall Fill([out, retval] ChartFillFormat** RHS);
        [propget, helpcontext(0x0001008b)]
        HRESULT _stdcall Caption([out, retval] BSTR* RHS);
        [propput, helpcontext(0x0001008b)]
        HRESULT _stdcall Caption([in] BSTR RHS);
        [propget, helpcontext(0x0001025b)]
        HRESULT _stdcall Characters(
                        [in, optional] VARIANT Start, 
                        [in, optional] VARIANT Length, 
                        [out, retval] Characters** RHS);
        [propget, helpcontext(0x00010092)]
        HRESULT _stdcall Font([out, retval] Font** RHS);
        [propget, helpcontext(0x00010088)]
        HRESULT _stdcall HorizontalAlignment([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010088)]
        HRESULT _stdcall HorizontalAlignment([in] VARIANT RHS);
        [propget, helpcontext(0x0001007f)]
        HRESULT _stdcall Left([out, retval] double* RHS);
        [propput, helpcontext(0x0001007f)]
        HRESULT _stdcall Left([in] double RHS);
        [propget, helpcontext(0x00010086)]
        HRESULT _stdcall Orientation([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010086)]
        HRESULT _stdcall Orientation([in] VARIANT RHS);
        [propget, helpcontext(0x00010067)]
        HRESULT _stdcall Shadow([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010067)]
        HRESULT _stdcall Shadow([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x0001008a)]
        HRESULT _stdcall Text([out, retval] BSTR* RHS);
        [propput, helpcontext(0x0001008a)]
        HRESULT _stdcall Text([in] BSTR RHS);
        [propget, helpcontext(0x0001007e)]
        HRESULT _stdcall Top([out, retval] double* RHS);
        [propput, helpcontext(0x0001007e)]
        HRESULT _stdcall Top([in] double RHS);
        [propget, helpcontext(0x00010089)]
        HRESULT _stdcall VerticalAlignment([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010089)]
        HRESULT _stdcall VerticalAlignment([in] VARIANT RHS);
        [propget, helpcontext(0x000103cf)]
        HRESULT _stdcall ReadingOrder([out, retval] long* RHS);
        [propput, helpcontext(0x000103cf)]
        HRESULT _stdcall ReadingOrder([in] long RHS);
        [propget, helpcontext(0x000105f5)]
        HRESULT _stdcall AutoScaleFont([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x000105f5)]
        HRESULT _stdcall AutoScaleFont([in] VARIANT RHS);
    };

    [
      odl,
      uuid(0002084A-0001-0000-C000-000000000046),
      helpcontext(0x0002000a),
      hidden
    ]
    interface IAxisTitle : IDispatch {
        [propget, helpcontext(0x00010094)]
        HRESULT _stdcall Application([out, retval] Application** RHS);
        [propget, helpcontext(0x00010095)]
        HRESULT _stdcall Creator([out, retval] XlCreator* RHS);
        [propget, helpcontext(0x00010096)]
        HRESULT _stdcall Parent([out, retval] IDispatch** RHS);
        [propget, helpcontext(0x0001006e)]
        HRESULT _stdcall Name([out, retval] BSTR* RHS);
        [helpcontext(0x000100eb)]
        HRESULT _stdcall Select();
        [propget, helpcontext(0x00010080)]
        HRESULT _stdcall Border([out, retval] Border** RHS);
        [helpcontext(0x00010075)]
        HRESULT _stdcall Delete();
        [propget, helpcontext(0x00010081)]
        HRESULT _stdcall Interior([out, retval] Interior** RHS);
        [propget, helpcontext(0x0001067f)]
        HRESULT _stdcall Fill([out, retval] ChartFillFormat** RHS);
        [propget, helpcontext(0x0001008b)]
        HRESULT _stdcall Caption([out, retval] BSTR* RHS);
        [propput, helpcontext(0x0001008b)]
        HRESULT _stdcall Caption([in] BSTR RHS);
        [propget, helpcontext(0x0001025b)]
        HRESULT _stdcall Characters(
                        [in, optional] VARIANT Start, 
                        [in, optional] VARIANT Length, 
                        [out, retval] Characters** RHS);
        [propget, helpcontext(0x00010092)]
        HRESULT _stdcall Font([out, retval] Font** RHS);
        [propget, helpcontext(0x00010088)]
        HRESULT _stdcall HorizontalAlignment([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010088)]
        HRESULT _stdcall HorizontalAlignment([in] VARIANT RHS);
        [propget, helpcontext(0x0001007f)]
        HRESULT _stdcall Left([out, retval] double* RHS);
        [propput, helpcontext(0x0001007f)]
        HRESULT _stdcall Left([in] double RHS);
        [propget, helpcontext(0x00010086)]
        HRESULT _stdcall Orientation([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010086)]
        HRESULT _stdcall Orientation([in] VARIANT RHS);
        [propget, helpcontext(0x00010067)]
        HRESULT _stdcall Shadow([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010067)]
        HRESULT _stdcall Shadow([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x0001008a)]
        HRESULT _stdcall Text([out, retval] BSTR* RHS);
        [propput, helpcontext(0x0001008a)]
        HRESULT _stdcall Text([in] BSTR RHS);
        [propget, helpcontext(0x0001007e)]
        HRESULT _stdcall Top([out, retval] double* RHS);
        [propput, helpcontext(0x0001007e)]
        HRESULT _stdcall Top([in] double RHS);
        [propget, helpcontext(0x00010089)]
        HRESULT _stdcall VerticalAlignment([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010089)]
        HRESULT _stdcall VerticalAlignment([in] VARIANT RHS);
        [propget, helpcontext(0x000103cf)]
        HRESULT _stdcall ReadingOrder([out, retval] long* RHS);
        [propput, helpcontext(0x000103cf)]
        HRESULT _stdcall ReadingOrder([in] long RHS);
        [propget, helpcontext(0x000105f5)]
        HRESULT _stdcall AutoScaleFont([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x000105f5)]
        HRESULT _stdcall AutoScaleFont([in] VARIANT RHS);
    };

    [
      odl,
      uuid(00020859-0001-0000-C000-000000000046),
      helpcontext(0x00020019),
      hidden
    ]
    interface IChartGroup : IDispatch {
        [propget, helpcontext(0x00010094)]
        HRESULT _stdcall Application([out, retval] Application** RHS);
        [propget, helpcontext(0x00010095)]
        HRESULT _stdcall Creator([out, retval] XlCreator* RHS);
        [propget, helpcontext(0x00010096)]
        HRESULT _stdcall Parent([out, retval] IDispatch** RHS);
        [propget, helpcontext(0x0001002f)]
        HRESULT _stdcall AxisGroup([out, retval] XlAxisGroup* RHS);
        [propput, helpcontext(0x0001002f)]
        HRESULT _stdcall AxisGroup([in] XlAxisGroup RHS);
        [propget, helpcontext(0x00010466)]
        HRESULT _stdcall DoughnutHoleSize([out, retval] long* RHS);
        [propput, helpcontext(0x00010466)]
        HRESULT _stdcall DoughnutHoleSize([in] long RHS);
        [propget, helpcontext(0x0001008d)]
        HRESULT _stdcall DownBars([out, retval] DownBars** RHS);
        [propget, helpcontext(0x0001008e)]
        HRESULT _stdcall DropLines([out, retval] DropLines** RHS);
        [propget, helpcontext(0x0001003f)]
        HRESULT _stdcall FirstSliceAngle([out, retval] long* RHS);
        [propput, helpcontext(0x0001003f)]
        HRESULT _stdcall FirstSliceAngle([in] long RHS);
        [propget, helpcontext(0x00010033)]
        HRESULT _stdcall GapWidth([out, retval] long* RHS);
        [propput, helpcontext(0x00010033)]
        HRESULT _stdcall GapWidth([in] long RHS);
        [propget, helpcontext(0x0001003d)]
        HRESULT _stdcall HasDropLines([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x0001003d)]
        HRESULT _stdcall HasDropLines([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x0001003e)]
        HRESULT _stdcall HasHiLoLines([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x0001003e)]
        HRESULT _stdcall HasHiLoLines([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x00010040)]
        HRESULT _stdcall HasRadarAxisLabels([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010040)]
        HRESULT _stdcall HasRadarAxisLabels([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x00010041)]
        HRESULT _stdcall HasSeriesLines([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010041)]
        HRESULT _stdcall HasSeriesLines([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x00010042)]
        HRESULT _stdcall HasUpDownBars([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010042)]
        HRESULT _stdcall HasUpDownBars([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x0001008f)]
        HRESULT _stdcall HiLoLines([out, retval] HiLoLines** RHS);
        [propget, helpcontext(0x000101e6)]
        HRESULT _stdcall Index([out, retval] long* RHS);
        [propget, helpcontext(0x00010038)]
        HRESULT _stdcall Overlap([out, retval] long* RHS);
        [propput, helpcontext(0x00010038)]
        HRESULT _stdcall Overlap([in] long RHS);
        [propget, helpcontext(0x00010090)]
        HRESULT _stdcall RadarAxisLabels([out, retval] TickLabels** RHS);
        [helpcontext(0x00010044)]
        HRESULT _stdcall SeriesCollection(
                        [in, optional] VARIANT Index, 
                        [out, retval] IDispatch** RHS);
        [propget, helpcontext(0x00010091)]
        HRESULT _stdcall SeriesLines([out, retval] SeriesLines** RHS);
        [propget, hidden, helpcontext(0x0001006d)]
        HRESULT _stdcall SubType([out, retval] long* RHS);
        [propput, hidden, helpcontext(0x0001006d)]
        HRESULT _stdcall SubType([in] long RHS);
        [propget, hidden, helpcontext(0x0001006c)]
        HRESULT _stdcall Type([out, retval] long* RHS);
        [propput, hidden, helpcontext(0x0001006c)]
        HRESULT _stdcall Type([in] long RHS);
        [propget, helpcontext(0x0001008c)]
        HRESULT _stdcall UpBars([out, retval] UpBars** RHS);
        [propget, helpcontext(0x0001003c)]
        HRESULT _stdcall VaryByCategories([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x0001003c)]
        HRESULT _stdcall VaryByCategories([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x00010674)]
        HRESULT _stdcall SizeRepresents([out, retval] XlSizeRepresents* RHS);
        [propput, helpcontext(0x00010674)]
        HRESULT _stdcall SizeRepresents([in] XlSizeRepresents RHS);
        [propget, helpcontext(0x00010675)]
        HRESULT _stdcall BubbleScale([out, retval] long* RHS);
        [propput, helpcontext(0x00010675)]
        HRESULT _stdcall BubbleScale([in] long RHS);
        [propget, helpcontext(0x00010676)]
        HRESULT _stdcall ShowNegativeBubbles([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010676)]
        HRESULT _stdcall ShowNegativeBubbles([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x00010677)]
        HRESULT _stdcall SplitType([out, retval] XlChartSplitType* RHS);
        [propput, helpcontext(0x00010677)]
        HRESULT _stdcall SplitType([in] XlChartSplitType RHS);
        [propget, helpcontext(0x00010678)]
        HRESULT _stdcall SplitValue([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010678)]
        HRESULT _stdcall SplitValue([in] VARIANT RHS);
        [propget, helpcontext(0x00010679)]
        HRESULT _stdcall SecondPlotSize([out, retval] long* RHS);
        [propput, helpcontext(0x00010679)]
        HRESULT _stdcall SecondPlotSize([in] long RHS);
        [propget, helpcontext(0x0001067a)]
        HRESULT _stdcall Has3DShading([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x0001067a)]
        HRESULT _stdcall Has3DShading([in] VARIANT_BOOL RHS);
    };
