import "Excel20.Idl";


    [
      uuid(00020886-0000-0000-C000-000000000046),
      helpcontext(0x00020046),
      hidden
    ]
    dispinterface ScrollBars {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x00010003), restricted, hidden]
            void _Dummy3();
            [id(0x0000025a), helpcontext(0x0001025a)]
            void BringToFront();
            [id(0x00000227), helpcontext(0x00010227)]
            void Copy();
            [id(0x000000d5), helpcontext(0x000100d5)]
            void CopyPicture(
                            [in, optional, defaultvalue(2)] XlPictureAppearance Appearance, 
                            [in, optional, defaultvalue(-4147)] XlCopyPictureFormat Format);
            [id(0x00000235), helpcontext(0x00010235)]
            void Cut();
            [id(0x00000075), helpcontext(0x00010075)]
            void Delete();
            [id(0x0000040f), helpcontext(0x0001040f)]
            IDispatch* Duplicate();
            [id(0x00000258), propget, helpcontext(0x00010258)]
            VARIANT_BOOL Enabled();
            [id(0x00000258), propput, helpcontext(0x00010258)]
            void Enabled([in] VARIANT_BOOL rhs);
            [id(0x0000007b), propget, helpcontext(0x0001007b)]
            double Height();
            [id(0x0000007b), propput, helpcontext(0x0001007b)]
            void Height([in] double rhs);
            [id(0x0001000c), restricted, hidden]
            void _Dummy12();
            [id(0x0000007f), propget, helpcontext(0x0001007f)]
            double Left();
            [id(0x0000007f), propput, helpcontext(0x0001007f)]
            void Left([in] double rhs);
            [id(0x0000010d), propget, helpcontext(0x0001010d)]
            VARIANT_BOOL Locked();
            [id(0x0000010d), propput, helpcontext(0x0001010d)]
            void Locked([in] VARIANT_BOOL rhs);
            [id(0x0001000f), restricted, hidden]
            void _Dummy15();
            [id(0x00000254), propget, hidden, helpcontext(0x00010254)]
            BSTR OnAction();
            [id(0x00000254), propput, hidden, helpcontext(0x00010254)]
            void OnAction([in] BSTR rhs);
            [id(0x00000269), propget, helpcontext(0x00010269)]
            VARIANT Placement();
            [id(0x00000269), propput, helpcontext(0x00010269)]
            void Placement([in] VARIANT rhs);
            [id(0x0000026a), propget, helpcontext(0x0001026a)]
            VARIANT_BOOL PrintObject();
            [id(0x0000026a), propput, helpcontext(0x0001026a)]
            void PrintObject([in] VARIANT_BOOL rhs);
            [id(0x000000eb), helpcontext(0x000100eb)]
            void Select([in, optional] VARIANT Replace);
            [id(0x0000025d), helpcontext(0x0001025d)]
            void SendToBack();
            [id(0x0000007e), propget, helpcontext(0x0001007e)]
            double Top();
            [id(0x0000007e), propput, helpcontext(0x0001007e)]
            void Top([in] double rhs);
            [id(0x00010016), restricted, hidden]
            void _Dummy22();
            [id(0x0000022e), propget, helpcontext(0x0001022e)]
            VARIANT_BOOL Visible();
            [id(0x0000022e), propput, helpcontext(0x0001022e)]
            void Visible([in] VARIANT_BOOL rhs);
            [id(0x0000007a), propget, helpcontext(0x0001007a)]
            double Width();
            [id(0x0000007a), propput, helpcontext(0x0001007a)]
            void Width([in] double rhs);
            [id(0x0000026e), propget, helpcontext(0x0001026e)]
            long ZOrder();
            [id(0x000005f8), propget, helpcontext(0x000105f8)]
            ShapeRange* ShapeRange();
            [id(00000000), propget, helpcontext(0x00010000)]
            long _Default();
            [id(00000000), propput, helpcontext(0x00010000)]
            void _Default([in] long rhs);
            [id(0x00000462), propget, helpcontext(0x00010462)]
            VARIANT_BOOL Display3DShading();
            [id(0x00000462), propput, helpcontext(0x00010462)]
            void Display3DShading([in] VARIANT_BOOL rhs);
            [id(0x00000422), propget, helpcontext(0x00010422)]
            BSTR LinkedCell();
            [id(0x00000422), propput, helpcontext(0x00010422)]
            void LinkedCell([in] BSTR rhs);
            [id(0x0000034a), propget, helpcontext(0x0001034a)]
            long Max();
            [id(0x0000034a), propput, helpcontext(0x0001034a)]
            void Max([in] long rhs);
            [id(0x0000034b), propget, helpcontext(0x0001034b)]
            long Min();
            [id(0x0000034b), propput, helpcontext(0x0001034b)]
            void Min([in] long rhs);
            [id(0x0000034c), propget, helpcontext(0x0001034c)]
            long SmallChange();
            [id(0x0000034c), propput, helpcontext(0x0001034c)]
            void SmallChange([in] long rhs);
            [id(0x00000006), propget, helpcontext(0x00010006)]
            long Value();
            [id(0x00000006), propput, helpcontext(0x00010006)]
            void Value([in] long rhs);
            [id(0x0000034d), propget, helpcontext(0x0001034d)]
            long LargeChange();
            [id(0x0000034d), propput, helpcontext(0x0001034d)]
            void LargeChange([in] long rhs);
            [id(0x000000b5), helpcontext(0x000100b5)]
            ScrollBar* Add(
                            [in] double Left, 
                            [in] double Top, 
                            [in] double Width, 
                            [in] double Height);
            [id(0x00000076), propget, helpcontext(0x00010076)]
            long Count();
            [id(0x0000002e), helpcontext(0x0001002e)]
            GroupObject* Group();
            [id(0x000000aa), helpcontext(0x000100aa)]
            IDispatch* Item([in] VARIANT Index);
            [id(0xfffffffc), helpcontext(0x0000fffc)]
            IUnknown* _NewEnum();
    };

    [
      uuid(00020887-0000-0000-C000-000000000046),
      helpcontext(0x00020047),
      hidden
    ]
    dispinterface ListBox {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x00000267), propget, helpcontext(0x00010267)]
            Range* BottomRightCell();
            [id(0x0000025a), helpcontext(0x0001025a)]
            void BringToFront();
            [id(0x00000227), helpcontext(0x00010227)]
            void Copy();
            [id(0x000000d5), helpcontext(0x000100d5)]
            void CopyPicture(
                            [in, optional, defaultvalue(2)] XlPictureAppearance Appearance, 
                            [in, optional, defaultvalue(-4147)] XlCopyPictureFormat Format);
            [id(0x00000235), helpcontext(0x00010235)]
            void Cut();
            [id(0x00000075), helpcontext(0x00010075)]
            void Delete();
            [id(0x0000040f), helpcontext(0x0001040f)]
            IDispatch* Duplicate();
            [id(0x00000258), propget, helpcontext(0x00010258)]
            VARIANT_BOOL Enabled();
            [id(0x00000258), propput, helpcontext(0x00010258)]
            void Enabled([in] VARIANT_BOOL rhs);
            [id(0x0000007b), propget, helpcontext(0x0001007b)]
            double Height();
            [id(0x0000007b), propput, helpcontext(0x0001007b)]
            void Height([in] double rhs);
            [id(0x000001e6), propget, helpcontext(0x000101e6)]
            long Index();
            [id(0x0000007f), propget, helpcontext(0x0001007f)]
            double Left();
            [id(0x0000007f), propput, helpcontext(0x0001007f)]
            void Left([in] double rhs);
            [id(0x0000010d), propget, helpcontext(0x0001010d)]
            VARIANT_BOOL Locked();
            [id(0x0000010d), propput, helpcontext(0x0001010d)]
            void Locked([in] VARIANT_BOOL rhs);
            [id(0x0000006e), propget, helpcontext(0x0001006e)]
            BSTR Name();
            [id(0x0000006e), propput, helpcontext(0x0001006e)]
            void Name([in] BSTR rhs);
            [id(0x00000254), propget, hidden, helpcontext(0x00010254)]
            BSTR OnAction();
            [id(0x00000254), propput, hidden, helpcontext(0x00010254)]
            void OnAction([in] BSTR rhs);
            [id(0x00000269), propget, helpcontext(0x00010269)]
            VARIANT Placement();
            [id(0x00000269), propput, helpcontext(0x00010269)]
            void Placement([in] VARIANT rhs);
            [id(0x0000026a), propget, helpcontext(0x0001026a)]
            VARIANT_BOOL PrintObject();
            [id(0x0000026a), propput, helpcontext(0x0001026a)]
            void PrintObject([in] VARIANT_BOOL rhs);
            [id(0x000000eb), helpcontext(0x000100eb)]
            void Select([in, optional] VARIANT Replace);
            [id(0x0000025d), helpcontext(0x0001025d)]
            void SendToBack();
            [id(0x0000007e), propget, helpcontext(0x0001007e)]
            double Top();
            [id(0x0000007e), propput, helpcontext(0x0001007e)]
            void Top([in] double rhs);
            [id(0x0000026c), propget, helpcontext(0x0001026c)]
            Range* TopLeftCell();
            [id(0x0000022e), propget, helpcontext(0x0001022e)]
            VARIANT_BOOL Visible();
            [id(0x0000022e), propput, helpcontext(0x0001022e)]
            void Visible([in] VARIANT_BOOL rhs);
            [id(0x0000007a), propget, helpcontext(0x0001007a)]
            double Width();
            [id(0x0000007a), propput, helpcontext(0x0001007a)]
            void Width([in] double rhs);
            [id(0x0000026e), propget, helpcontext(0x0001026e)]
            long ZOrder();
            [id(0x000005f8), propget, helpcontext(0x000105f8)]
            ShapeRange* ShapeRange();
            [id(0x00000353), helpcontext(0x00010353)]
            void AddItem(
                            [in] VARIANT Text, 
                            [in, optional] VARIANT Index);
            [id(0x00000462), propget, helpcontext(0x00010462)]
            VARIANT_BOOL Display3DShading();
            [id(0x00000462), propput, helpcontext(0x00010462)]
            void Display3DShading([in] VARIANT_BOOL rhs);
            [id(00000000), propget, helpcontext(0x00010000)]
            long _Default();
            [id(00000000), propput, helpcontext(0x00010000)]
            void _Default([in] long rhs);
            [id(0x00000422), propget, helpcontext(0x00010422)]
            BSTR LinkedCell();
            [id(0x00000422), propput, helpcontext(0x00010422)]
            void LinkedCell([in] BSTR rhs);
            [id(0x0000035e), propget, helpcontext(0x0001035e)]
            VARIANT LinkedObject();
            [id(0x0000035d), helpcontext(0x0001035d)]
            VARIANT List([in, optional] VARIANT Index);
            [id(0x00000351), propget, helpcontext(0x00010351)]
            long ListCount();
            [id(0x0000034f), propget, helpcontext(0x0001034f)]
            BSTR ListFillRange();
            [id(0x0000034f), propput, helpcontext(0x0001034f)]
            void ListFillRange([in] BSTR rhs);
            [id(0x00000352), propget, helpcontext(0x00010352)]
            long ListIndex();
            [id(0x00000352), propput, helpcontext(0x00010352)]
            void ListIndex([in] long rhs);
            [id(0x00000020), propget, helpcontext(0x00010020)]
            long MultiSelect();
            [id(0x00000020), propput, helpcontext(0x00010020)]
            void MultiSelect([in] long rhs);
            [id(0x00000355), helpcontext(0x00010355)]
            void RemoveAllItems();
            [id(0x00000354), helpcontext(0x00010354)]
            void RemoveItem(
                            [in] long Index, 
                            [in, optional] VARIANT Count);
            [id(0x00000463), helpcontext(0x00010463)]
            VARIANT Selected([in, optional] VARIANT Index);
            [id(0x00000006), propget, helpcontext(0x00010006)]
            long Value();
            [id(0x00000006), propput, helpcontext(0x00010006)]
            void Value([in] long rhs);
    };

    [
      uuid(00020888-0000-0000-C000-000000000046),
      helpcontext(0x00020048),
      hidden
    ]
    dispinterface ListBoxes {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x00010003), restricted, hidden]
            void _Dummy3();
            [id(0x0000025a), helpcontext(0x0001025a)]
            void BringToFront();
            [id(0x00000227), helpcontext(0x00010227)]
            void Copy();
            [id(0x000000d5), helpcontext(0x000100d5)]
            void CopyPicture(
                            [in, optional, defaultvalue(2)] XlPictureAppearance Appearance, 
                            [in, optional, defaultvalue(-4147)] XlCopyPictureFormat Format);
            [id(0x00000235), helpcontext(0x00010235)]
            void Cut();
            [id(0x00000075), helpcontext(0x00010075)]
            void Delete();
            [id(0x0000040f), helpcontext(0x0001040f)]
            IDispatch* Duplicate();
            [id(0x00000258), propget, helpcontext(0x00010258)]
            VARIANT_BOOL Enabled();
            [id(0x00000258), propput, helpcontext(0x00010258)]
            void Enabled([in] VARIANT_BOOL rhs);
            [id(0x0000007b), propget, helpcontext(0x0001007b)]
            double Height();
            [id(0x0000007b), propput, helpcontext(0x0001007b)]
            void Height([in] double rhs);
            [id(0x0001000c), restricted, hidden]
            void _Dummy12();
            [id(0x0000007f), propget, helpcontext(0x0001007f)]
            double Left();
            [id(0x0000007f), propput, helpcontext(0x0001007f)]
            void Left([in] double rhs);
            [id(0x0000010d), propget, helpcontext(0x0001010d)]
            VARIANT_BOOL Locked();
            [id(0x0000010d), propput, helpcontext(0x0001010d)]
            void Locked([in] VARIANT_BOOL rhs);
            [id(0x0001000f), restricted, hidden]
            void _Dummy15();
            [id(0x00000254), propget, hidden, helpcontext(0x00010254)]
            BSTR OnAction();
            [id(0x00000254), propput, hidden, helpcontext(0x00010254)]
            void OnAction([in] BSTR rhs);
            [id(0x00000269), propget, helpcontext(0x00010269)]
            VARIANT Placement();
            [id(0x00000269), propput, helpcontext(0x00010269)]
            void Placement([in] VARIANT rhs);
            [id(0x0000026a), propget, helpcontext(0x0001026a)]
            VARIANT_BOOL PrintObject();
            [id(0x0000026a), propput, helpcontext(0x0001026a)]
            void PrintObject([in] VARIANT_BOOL rhs);
            [id(0x000000eb), helpcontext(0x000100eb)]
            void Select([in, optional] VARIANT Replace);
            [id(0x0000025d), helpcontext(0x0001025d)]
            void SendToBack();
            [id(0x0000007e), propget, helpcontext(0x0001007e)]
            double Top();
            [id(0x0000007e), propput, helpcontext(0x0001007e)]
            void Top([in] double rhs);
            [id(0x00010016), restricted, hidden]
            void _Dummy22();
            [id(0x0000022e), propget, helpcontext(0x0001022e)]
            VARIANT_BOOL Visible();
            [id(0x0000022e), propput, helpcontext(0x0001022e)]
            void Visible([in] VARIANT_BOOL rhs);
            [id(0x0000007a), propget, helpcontext(0x0001007a)]
            double Width();
            [id(0x0000007a), propput, helpcontext(0x0001007a)]
            void Width([in] double rhs);
            [id(0x0000026e), propget, helpcontext(0x0001026e)]
            long ZOrder();
            [id(0x000005f8), propget, helpcontext(0x000105f8)]
            ShapeRange* ShapeRange();
            [id(0x00000353), helpcontext(0x00010353)]
            void AddItem(
                            [in] VARIANT Text, 
                            [in, optional] VARIANT Index);
            [id(0x00000462), propget, helpcontext(0x00010462)]
            VARIANT_BOOL Display3DShading();
            [id(0x00000462), propput, helpcontext(0x00010462)]
            void Display3DShading([in] VARIANT_BOOL rhs);
            [id(00000000), propget, helpcontext(0x00010000)]
            long _Default();
            [id(00000000), propput, helpcontext(0x00010000)]
            void _Default([in] long rhs);
            [id(0x00000422), propget, helpcontext(0x00010422)]
            BSTR LinkedCell();
            [id(0x00000422), propput, helpcontext(0x00010422)]
            void LinkedCell([in] BSTR rhs);
            [id(0x0001001f), restricted, hidden]
            void _Dummy31();
            [id(0x0000035d), helpcontext(0x0001035d)]
            VARIANT List([in, optional] VARIANT Index);
            [id(0x00010021), restricted, hidden]
            void _Dummy33();
            [id(0x0000034f), propget, helpcontext(0x0001034f)]
            BSTR ListFillRange();
            [id(0x0000034f), propput, helpcontext(0x0001034f)]
            void ListFillRange([in] BSTR rhs);
            [id(0x00000352), propget, helpcontext(0x00010352)]
            long ListIndex();
            [id(0x00000352), propput, helpcontext(0x00010352)]
            void ListIndex([in] long rhs);
            [id(0x00000020), propget, helpcontext(0x00010020)]
            long MultiSelect();
            [id(0x00000020), propput, helpcontext(0x00010020)]
            void MultiSelect([in] long rhs);
            [id(0x00000355), helpcontext(0x00010355)]
            void RemoveAllItems();
            [id(0x00000354), helpcontext(0x00010354)]
            void RemoveItem(
                            [in] long Index, 
                            [in, optional] VARIANT Count);
            [id(0x00000463), helpcontext(0x00010463)]
            VARIANT Selected([in, optional] VARIANT Index);
            [id(0x00000006), propget, helpcontext(0x00010006)]
            long Value();
            [id(0x00000006), propput, helpcontext(0x00010006)]
            void Value([in] long rhs);
            [id(0x000000b5), helpcontext(0x000100b5)]
            ListBox* Add(
                            [in] double Left, 
                            [in] double Top, 
                            [in] double Width, 
                            [in] double Height);
            [id(0x00000076), propget, helpcontext(0x00010076)]
            long Count();
            [id(0x0000002e), helpcontext(0x0001002e)]
            GroupObject* Group();
            [id(0x000000aa), helpcontext(0x000100aa)]
            IDispatch* Item([in] VARIANT Index);
            [id(0xfffffffc), helpcontext(0x0000fffc)]
            IUnknown* _NewEnum();
    };

    [
      uuid(00020889-0000-0000-C000-000000000046),
      helpcontext(0x00020049),
      hidden
    ]
    dispinterface GroupBox {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x00000267), propget, helpcontext(0x00010267)]
            Range* BottomRightCell();
            [id(0x0000025a), helpcontext(0x0001025a)]
            void BringToFront();
            [id(0x00000227), helpcontext(0x00010227)]
            void Copy();
            [id(0x000000d5), helpcontext(0x000100d5)]
            void CopyPicture(
                            [in, optional, defaultvalue(2)] XlPictureAppearance Appearance, 
                            [in, optional, defaultvalue(-4147)] XlCopyPictureFormat Format);
            [id(0x00000235), helpcontext(0x00010235)]
            void Cut();
            [id(0x00000075), helpcontext(0x00010075)]
            void Delete();
            [id(0x0000040f), helpcontext(0x0001040f)]
            IDispatch* Duplicate();
            [id(0x00000258), propget, helpcontext(0x00010258)]
            VARIANT_BOOL Enabled();
            [id(0x00000258), propput, helpcontext(0x00010258)]
            void Enabled([in] VARIANT_BOOL rhs);
            [id(0x0000007b), propget, helpcontext(0x0001007b)]
            double Height();
            [id(0x0000007b), propput, helpcontext(0x0001007b)]
            void Height([in] double rhs);
            [id(0x000001e6), propget, helpcontext(0x000101e6)]
            long Index();
            [id(0x0000007f), propget, helpcontext(0x0001007f)]
            double Left();
            [id(0x0000007f), propput, helpcontext(0x0001007f)]
            void Left([in] double rhs);
            [id(0x0000010d), propget, helpcontext(0x0001010d)]
            VARIANT_BOOL Locked();
            [id(0x0000010d), propput, helpcontext(0x0001010d)]
            void Locked([in] VARIANT_BOOL rhs);
            [id(0x0000006e), propget, helpcontext(0x0001006e)]
            BSTR Name();
            [id(0x0000006e), propput, helpcontext(0x0001006e)]
            void Name([in] BSTR rhs);
            [id(0x00000254), propget, hidden, helpcontext(0x00010254)]
            BSTR OnAction();
            [id(0x00000254), propput, hidden, helpcontext(0x00010254)]
            void OnAction([in] BSTR rhs);
            [id(0x00000269), propget, helpcontext(0x00010269)]
            VARIANT Placement();
            [id(0x00000269), propput, helpcontext(0x00010269)]
            void Placement([in] VARIANT rhs);
            [id(0x0000026a), propget, helpcontext(0x0001026a)]
            VARIANT_BOOL PrintObject();
            [id(0x0000026a), propput, helpcontext(0x0001026a)]
            void PrintObject([in] VARIANT_BOOL rhs);
            [id(0x000000eb), helpcontext(0x000100eb)]
            void Select([in, optional] VARIANT Replace);
            [id(0x0000025d), helpcontext(0x0001025d)]
            void SendToBack();
            [id(0x0000007e), propget, helpcontext(0x0001007e)]
            double Top();
            [id(0x0000007e), propput, helpcontext(0x0001007e)]
            void Top([in] double rhs);
            [id(0x0000026c), propget, helpcontext(0x0001026c)]
            Range* TopLeftCell();
            [id(0x0000022e), propget, helpcontext(0x0001022e)]
            VARIANT_BOOL Visible();
            [id(0x0000022e), propput, helpcontext(0x0001022e)]
            void Visible([in] VARIANT_BOOL rhs);
            [id(0x0000007a), propget, helpcontext(0x0001007a)]
            double Width();
            [id(0x0000007a), propput, helpcontext(0x0001007a)]
            void Width([in] double rhs);
            [id(0x0000026e), propget, helpcontext(0x0001026e)]
            long ZOrder();
            [id(0x000005f8), propget, helpcontext(0x000105f8)]
            ShapeRange* ShapeRange();
            [id(0x0000008b), propget, helpcontext(0x0001008b)]
            BSTR Caption();
            [id(0x0000008b), propput, helpcontext(0x0001008b)]
            void Caption([in] BSTR rhs);
            [id(0x0000025b), propget, helpcontext(0x0001025b)]
            Characters* Characters(
                            [in, optional] VARIANT Start, 
                            [in, optional] VARIANT Length);
            [id(0x000001f9), helpcontext(0x000101f9)]
            void CheckSpelling(
                            [in, optional] VARIANT CustomDictionary, 
                            [in, optional] VARIANT IgnoreUppercase, 
                            [in, optional] VARIANT AlwaysSuggest, 
                            [in, optional] VARIANT IgnoreInitialAlefHamza, 
                            [in, optional] VARIANT IgnoreFinalYaa, 
                            [in, optional] VARIANT SpellScript);
            [id(0x00000268), propget, helpcontext(0x00010268)]
            VARIANT_BOOL LockedText();
            [id(0x00000268), propput, helpcontext(0x00010268)]
            void LockedText([in] VARIANT_BOOL rhs);
            [id(0x0000008a), propget, helpcontext(0x0001008a)]
            BSTR Text();
            [id(0x0000008a), propput, helpcontext(0x0001008a)]
            void Text([in] BSTR rhs);
            [id(0x0000034e), propget, helpcontext(0x0001034e)]
            VARIANT Accelerator();
            [id(0x0000034e), propput, helpcontext(0x0001034e)]
            void Accelerator([in] VARIANT rhs);
            [id(0x00000462), propget, helpcontext(0x00010462)]
            VARIANT_BOOL Display3DShading();
            [id(0x00000462), propput, helpcontext(0x00010462)]
            void Display3DShading([in] VARIANT_BOOL rhs);
            [id(0x00000461), propget, helpcontext(0x00010461)]
            VARIANT PhoneticAccelerator();
            [id(0x00000461), propput, helpcontext(0x00010461)]
            void PhoneticAccelerator([in] VARIANT rhs);
    };

    [
      uuid(0002088A-0000-0000-C000-000000000046),
      helpcontext(0x0002004a),
      hidden
    ]
    dispinterface GroupBoxes {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x00010003), restricted, hidden]
            void _Dummy3();
            [id(0x0000025a), helpcontext(0x0001025a)]
            void BringToFront();
            [id(0x00000227), helpcontext(0x00010227)]
            void Copy();
            [id(0x000000d5), helpcontext(0x000100d5)]
            void CopyPicture(
                            [in, optional, defaultvalue(2)] XlPictureAppearance Appearance, 
                            [in, optional, defaultvalue(-4147)] XlCopyPictureFormat Format);
            [id(0x00000235), helpcontext(0x00010235)]
            void Cut();
            [id(0x00000075), helpcontext(0x00010075)]
            void Delete();
            [id(0x0000040f), helpcontext(0x0001040f)]
            IDispatch* Duplicate();
            [id(0x00000258), propget, helpcontext(0x00010258)]
            VARIANT_BOOL Enabled();
            [id(0x00000258), propput, helpcontext(0x00010258)]
            void Enabled([in] VARIANT_BOOL rhs);
            [id(0x0000007b), propget, helpcontext(0x0001007b)]
            double Height();
            [id(0x0000007b), propput, helpcontext(0x0001007b)]
            void Height([in] double rhs);
            [id(0x0001000c), restricted, hidden]
            void _Dummy12();
            [id(0x0000007f), propget, helpcontext(0x0001007f)]
            double Left();
            [id(0x0000007f), propput, helpcontext(0x0001007f)]
            void Left([in] double rhs);
            [id(0x0000010d), propget, helpcontext(0x0001010d)]
            VARIANT_BOOL Locked();
            [id(0x0000010d), propput, helpcontext(0x0001010d)]
            void Locked([in] VARIANT_BOOL rhs);
            [id(0x0001000f), restricted, hidden]
            void _Dummy15();
            [id(0x00000254), propget, hidden, helpcontext(0x00010254)]
            BSTR OnAction();
            [id(0x00000254), propput, hidden, helpcontext(0x00010254)]
            void OnAction([in] BSTR rhs);
            [id(0x00000269), propget, helpcontext(0x00010269)]
            VARIANT Placement();
            [id(0x00000269), propput, helpcontext(0x00010269)]
            void Placement([in] VARIANT rhs);
            [id(0x0000026a), propget, helpcontext(0x0001026a)]
            VARIANT_BOOL PrintObject();
            [id(0x0000026a), propput, helpcontext(0x0001026a)]
            void PrintObject([in] VARIANT_BOOL rhs);
            [id(0x000000eb), helpcontext(0x000100eb)]
            void Select([in, optional] VARIANT Replace);
            [id(0x0000025d), helpcontext(0x0001025d)]
            void SendToBack();
            [id(0x0000007e), propget, helpcontext(0x0001007e)]
            double Top();
            [id(0x0000007e), propput, helpcontext(0x0001007e)]
            void Top([in] double rhs);
            [id(0x00010016), restricted, hidden]
            void _Dummy22();
            [id(0x0000022e), propget, helpcontext(0x0001022e)]
            VARIANT_BOOL Visible();
            [id(0x0000022e), propput, helpcontext(0x0001022e)]
            void Visible([in] VARIANT_BOOL rhs);
            [id(0x0000007a), propget, helpcontext(0x0001007a)]
            double Width();
            [id(0x0000007a), propput, helpcontext(0x0001007a)]
            void Width([in] double rhs);
            [id(0x0000026e), propget, helpcontext(0x0001026e)]
            long ZOrder();
            [id(0x000005f8), propget, helpcontext(0x000105f8)]
            ShapeRange* ShapeRange();
            [id(0x0000008b), propget, helpcontext(0x0001008b)]
            BSTR Caption();
            [id(0x0000008b), propput, helpcontext(0x0001008b)]
            void Caption([in] BSTR rhs);
            [id(0x0000025b), propget, helpcontext(0x0001025b)]
            Characters* Characters(
                            [in, optional] VARIANT Start, 
                            [in, optional] VARIANT Length);
            [id(0x000001f9), helpcontext(0x000101f9)]
            void CheckSpelling(
                            [in, optional] VARIANT CustomDictionary, 
                            [in, optional] VARIANT IgnoreUppercase, 
                            [in, optional] VARIANT AlwaysSuggest, 
                            [in, optional] VARIANT IgnoreInitialAlefHamza, 
                            [in, optional] VARIANT IgnoreFinalYaa, 
                            [in, optional] VARIANT SpellScript);
            [id(0x00000268), propget, helpcontext(0x00010268)]
            VARIANT_BOOL LockedText();
            [id(0x00000268), propput, helpcontext(0x00010268)]
            void LockedText([in] VARIANT_BOOL rhs);
            [id(0x0000008a), propget, helpcontext(0x0001008a)]
            BSTR Text();
            [id(0x0000008a), propput, helpcontext(0x0001008a)]
            void Text([in] BSTR rhs);
            [id(0x0000034e), propget, helpcontext(0x0001034e)]
            VARIANT Accelerator();
            [id(0x0000034e), propput, helpcontext(0x0001034e)]
            void Accelerator([in] VARIANT rhs);
            [id(0x00000462), propget, helpcontext(0x00010462)]
            VARIANT_BOOL Display3DShading();
            [id(0x00000462), propput, helpcontext(0x00010462)]
            void Display3DShading([in] VARIANT_BOOL rhs);
            [id(0x00000461), propget, helpcontext(0x00010461)]
            VARIANT PhoneticAccelerator();
            [id(0x00000461), propput, helpcontext(0x00010461)]
            void PhoneticAccelerator([in] VARIANT rhs);
            [id(0x000000b5), helpcontext(0x000100b5)]
            GroupBox* Add(
                            [in] double Left, 
                            [in] double Top, 
                            [in] double Width, 
                            [in] double Height);
            [id(0x00000076), propget, helpcontext(0x00010076)]
            long Count();
            [id(0x0000002e), helpcontext(0x0001002e)]
            GroupObject* Group();
            [id(0x000000aa), helpcontext(0x000100aa)]
            IDispatch* Item([in] VARIANT Index);
            [id(0xfffffffc), helpcontext(0x0000fffc)]
            IUnknown* _NewEnum();
    };

    [
      uuid(0002088B-0000-0000-C000-000000000046),
      helpcontext(0x0002004b),
      hidden
    ]
    dispinterface DropDown {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x00000267), propget, helpcontext(0x00010267)]
            Range* BottomRightCell();
            [id(0x0000025a), helpcontext(0x0001025a)]
            void BringToFront();
            [id(0x00000227), helpcontext(0x00010227)]
            void Copy();
            [id(0x000000d5), helpcontext(0x000100d5)]
            void CopyPicture(
                            [in, optional, defaultvalue(2)] XlPictureAppearance Appearance, 
                            [in, optional, defaultvalue(-4147)] XlCopyPictureFormat Format);
            [id(0x00000235), helpcontext(0x00010235)]
            void Cut();
            [id(0x00000075), helpcontext(0x00010075)]
            void Delete();
            [id(0x0000040f), helpcontext(0x0001040f)]
            IDispatch* Duplicate();
            [id(0x00000258), propget, helpcontext(0x00010258)]
            VARIANT_BOOL Enabled();
            [id(0x00000258), propput, helpcontext(0x00010258)]
            void Enabled([in] VARIANT_BOOL rhs);
            [id(0x0000007b), propget, helpcontext(0x0001007b)]
            double Height();
            [id(0x0000007b), propput, helpcontext(0x0001007b)]
            void Height([in] double rhs);
            [id(0x000001e6), propget, helpcontext(0x000101e6)]
            long Index();
            [id(0x0000007f), propget, helpcontext(0x0001007f)]
            double Left();
            [id(0x0000007f), propput, helpcontext(0x0001007f)]
            void Left([in] double rhs);
            [id(0x0000010d), propget, helpcontext(0x0001010d)]
            VARIANT_BOOL Locked();
            [id(0x0000010d), propput, helpcontext(0x0001010d)]
            void Locked([in] VARIANT_BOOL rhs);
            [id(0x0000006e), propget, helpcontext(0x0001006e)]
            BSTR Name();
            [id(0x0000006e), propput, helpcontext(0x0001006e)]
            void Name([in] BSTR rhs);
            [id(0x00000254), propget, hidden, helpcontext(0x00010254)]
            BSTR OnAction();
            [id(0x00000254), propput, hidden, helpcontext(0x00010254)]
            void OnAction([in] BSTR rhs);
            [id(0x00000269), propget, helpcontext(0x00010269)]
            VARIANT Placement();
            [id(0x00000269), propput, helpcontext(0x00010269)]
            void Placement([in] VARIANT rhs);
            [id(0x0000026a), propget, helpcontext(0x0001026a)]
            VARIANT_BOOL PrintObject();
            [id(0x0000026a), propput, helpcontext(0x0001026a)]
            void PrintObject([in] VARIANT_BOOL rhs);
            [id(0x000000eb), helpcontext(0x000100eb)]
            void Select([in, optional] VARIANT Replace);
            [id(0x0000025d), helpcontext(0x0001025d)]
            void SendToBack();
            [id(0x0000007e), propget, helpcontext(0x0001007e)]
            double Top();
            [id(0x0000007e), propput, helpcontext(0x0001007e)]
            void Top([in] double rhs);
            [id(0x0000026c), propget, helpcontext(0x0001026c)]
            Range* TopLeftCell();
            [id(0x0000022e), propget, helpcontext(0x0001022e)]
            VARIANT_BOOL Visible();
            [id(0x0000022e), propput, helpcontext(0x0001022e)]
            void Visible([in] VARIANT_BOOL rhs);
            [id(0x0000007a), propget, helpcontext(0x0001007a)]
            double Width();
            [id(0x0000007a), propput, helpcontext(0x0001007a)]
            void Width([in] double rhs);
            [id(0x0000026e), propget, helpcontext(0x0001026e)]
            long ZOrder();
            [id(0x000005f8), propget, helpcontext(0x000105f8)]
            ShapeRange* ShapeRange();
            [id(0x00000353), helpcontext(0x00010353)]
            void AddItem(
                            [in] VARIANT Text, 
                            [in, optional] VARIANT Index);
            [id(0x00000462), propget, helpcontext(0x00010462)]
            VARIANT_BOOL Display3DShading();
            [id(0x00000462), propput, helpcontext(0x00010462)]
            void Display3DShading([in] VARIANT_BOOL rhs);
            [id(00000000), propget, helpcontext(0x00010000)]
            long _Default();
            [id(00000000), propput, helpcontext(0x00010000)]
            void _Default([in] long rhs);
            [id(0x00000422), propget, helpcontext(0x00010422)]
            BSTR LinkedCell();
            [id(0x00000422), propput, helpcontext(0x00010422)]
            void LinkedCell([in] BSTR rhs);
            [id(0x0000035e), propget, helpcontext(0x0001035e)]
            VARIANT LinkedObject();
            [id(0x0000035d), helpcontext(0x0001035d)]
            VARIANT List([in, optional] VARIANT Index);
            [id(0x00000351), propget, helpcontext(0x00010351)]
            long ListCount();
            [id(0x0000034f), propget, helpcontext(0x0001034f)]
            BSTR ListFillRange();
            [id(0x0000034f), propput, helpcontext(0x0001034f)]
            void ListFillRange([in] BSTR rhs);
            [id(0x00000352), propget, helpcontext(0x00010352)]
            long ListIndex();
            [id(0x00000352), propput, helpcontext(0x00010352)]
            void ListIndex([in] long rhs);
            [id(0x00010024), restricted, hidden]
            void _Dummy36();
            [id(0x00000355), helpcontext(0x00010355)]
            void RemoveAllItems();
            [id(0x00000354), helpcontext(0x00010354)]
            void RemoveItem(
                            [in] long Index, 
                            [in, optional] VARIANT Count);
            [id(0x00000463), helpcontext(0x00010463)]
            VARIANT Selected([in, optional] VARIANT Index);
            [id(0x00000006), propget, helpcontext(0x00010006)]
            long Value();
            [id(0x00000006), propput, helpcontext(0x00010006)]
            void Value([in] long rhs);
            [id(0x0000008b), propget, helpcontext(0x0001008b)]
            BSTR Caption();
            [id(0x0000008b), propput, helpcontext(0x0001008b)]
            void Caption([in] BSTR rhs);
            [id(0x0000025b), propget, helpcontext(0x0001025b)]
            Characters* Characters(
                            [in, optional] VARIANT Start, 
                            [in, optional] VARIANT Length);
            [id(0x00000350), propget, helpcontext(0x00010350)]
            long DropDownLines();
            [id(0x00000350), propput, helpcontext(0x00010350)]
            void DropDownLines([in] long rhs);
            [id(0x0000008a), propget, helpcontext(0x0001008a)]
            BSTR Text();
            [id(0x0000008a), propput, helpcontext(0x0001008a)]
            void Text([in] BSTR rhs);
    };

    [
      uuid(0002088C-0000-0000-C000-000000000046),
      helpcontext(0x0002004c),
      hidden
    ]
    dispinterface DropDowns {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x00010003), restricted, hidden]
            void _Dummy3();
            [id(0x0000025a), helpcontext(0x0001025a)]
            void BringToFront();
            [id(0x00000227), helpcontext(0x00010227)]
            void Copy();
            [id(0x000000d5), helpcontext(0x000100d5)]
            void CopyPicture(
                            [in, optional, defaultvalue(2)] XlPictureAppearance Appearance, 
                            [in, optional, defaultvalue(-4147)] XlCopyPictureFormat Format);
            [id(0x00000235), helpcontext(0x00010235)]
            void Cut();
            [id(0x00000075), helpcontext(0x00010075)]
            void Delete();
            [id(0x0000040f), helpcontext(0x0001040f)]
            IDispatch* Duplicate();
            [id(0x00000258), propget, helpcontext(0x00010258)]
            VARIANT_BOOL Enabled();
            [id(0x00000258), propput, helpcontext(0x00010258)]
            void Enabled([in] VARIANT_BOOL rhs);
            [id(0x0000007b), propget, helpcontext(0x0001007b)]
            double Height();
            [id(0x0000007b), propput, helpcontext(0x0001007b)]
            void Height([in] double rhs);
            [id(0x0001000c), restricted, hidden]
            void _Dummy12();
            [id(0x0000007f), propget, helpcontext(0x0001007f)]
            double Left();
            [id(0x0000007f), propput, helpcontext(0x0001007f)]
            void Left([in] double rhs);
            [id(0x0000010d), propget, helpcontext(0x0001010d)]
            VARIANT_BOOL Locked();
            [id(0x0000010d), propput, helpcontext(0x0001010d)]
            void Locked([in] VARIANT_BOOL rhs);
            [id(0x0001000f), restricted, hidden]
            void _Dummy15();
            [id(0x00000254), propget, hidden, helpcontext(0x00010254)]
            BSTR OnAction();
            [id(0x00000254), propput, hidden, helpcontext(0x00010254)]
            void OnAction([in] BSTR rhs);
            [id(0x00000269), propget, helpcontext(0x00010269)]
            VARIANT Placement();
            [id(0x00000269), propput, helpcontext(0x00010269)]
            void Placement([in] VARIANT rhs);
            [id(0x0000026a), propget, helpcontext(0x0001026a)]
            VARIANT_BOOL PrintObject();
            [id(0x0000026a), propput, helpcontext(0x0001026a)]
            void PrintObject([in] VARIANT_BOOL rhs);
            [id(0x000000eb), helpcontext(0x000100eb)]
            void Select([in, optional] VARIANT Replace);
            [id(0x0000025d), helpcontext(0x0001025d)]
            void SendToBack();
            [id(0x0000007e), propget, helpcontext(0x0001007e)]
            double Top();
            [id(0x0000007e), propput, helpcontext(0x0001007e)]
            void Top([in] double rhs);
            [id(0x00010016), restricted, hidden]
            void _Dummy22();
            [id(0x0000022e), propget, helpcontext(0x0001022e)]
            VARIANT_BOOL Visible();
            [id(0x0000022e), propput, helpcontext(0x0001022e)]
            void Visible([in] VARIANT_BOOL rhs);
            [id(0x0000007a), propget, helpcontext(0x0001007a)]
            double Width();
            [id(0x0000007a), propput, helpcontext(0x0001007a)]
            void Width([in] double rhs);
            [id(0x0000026e), propget, helpcontext(0x0001026e)]
            long ZOrder();
            [id(0x000005f8), propget, helpcontext(0x000105f8)]
            ShapeRange* ShapeRange();
            [id(0x00000353), helpcontext(0x00010353)]
            void AddItem(
                            [in] VARIANT Text, 
                            [in, optional] VARIANT Index);
            [id(0x00000462), propget, helpcontext(0x00010462)]
            VARIANT_BOOL Display3DShading();
            [id(0x00000462), propput, helpcontext(0x00010462)]
            void Display3DShading([in] VARIANT_BOOL rhs);
            [id(00000000), propget, helpcontext(0x00010000)]
            long _Default();
            [id(00000000), propput, helpcontext(0x00010000)]
            void _Default([in] long rhs);
            [id(0x00000422), propget, helpcontext(0x00010422)]
            BSTR LinkedCell();
            [id(0x00000422), propput, helpcontext(0x00010422)]
            void LinkedCell([in] BSTR rhs);
            [id(0x0001001f), restricted, hidden]
            void _Dummy31();
            [id(0x0000035d), helpcontext(0x0001035d)]
            VARIANT List([in, optional] VARIANT Index);
            [id(0x00010021), restricted, hidden]
            void _Dummy33();
            [id(0x0000034f), propget, helpcontext(0x0001034f)]
            BSTR ListFillRange();
            [id(0x0000034f), propput, helpcontext(0x0001034f)]
            void ListFillRange([in] BSTR rhs);
            [id(0x00000352), propget, helpcontext(0x00010352)]
            long ListIndex();
            [id(0x00000352), propput, helpcontext(0x00010352)]
            void ListIndex([in] long rhs);
            [id(0x00010024), restricted, hidden]
            void _Dummy36();
            [id(0x00000355), helpcontext(0x00010355)]
            void RemoveAllItems();
            [id(0x00000354), helpcontext(0x00010354)]
            void RemoveItem(
                            [in] long Index, 
                            [in, optional] VARIANT Count);
            [id(0x00000463), helpcontext(0x00010463)]
            VARIANT Selected([in, optional] VARIANT Index);
            [id(0x00000006), propget, helpcontext(0x00010006)]
            long Value();
            [id(0x00000006), propput, helpcontext(0x00010006)]
            void Value([in] long rhs);
            [id(0x0000008b), propget, helpcontext(0x0001008b)]
            BSTR Caption();
            [id(0x0000008b), propput, helpcontext(0x0001008b)]
            void Caption([in] BSTR rhs);
            [id(0x0000025b), propget, helpcontext(0x0001025b)]
            Characters* Characters(
                            [in, optional] VARIANT Start, 
                            [in, optional] VARIANT Length);
            [id(0x00000350), propget, helpcontext(0x00010350)]
            long DropDownLines();
            [id(0x00000350), propput, helpcontext(0x00010350)]
            void DropDownLines([in] long rhs);
            [id(0x0000008a), propget, helpcontext(0x0001008a)]
            BSTR Text();
            [id(0x0000008a), propput, helpcontext(0x0001008a)]
            void Text([in] BSTR rhs);
            [id(0x000000b5), helpcontext(0x000100b5)]
            DropDown* Add(
                            [in] double Left, 
                            [in] double Top, 
                            [in] double Width, 
                            [in] double Height, 
                            [in, optional] VARIANT Editable);
            [id(0x00000076), propget, helpcontext(0x00010076)]
            long Count();
            [id(0x0000002e), helpcontext(0x0001002e)]
            GroupObject* Group();
            [id(0x000000aa), helpcontext(0x000100aa)]
            IDispatch* Item([in] VARIANT Index);
            [id(0xfffffffc), helpcontext(0x0000fffc)]
            IUnknown* _NewEnum();
    };

    [
      uuid(0002088D-0000-0000-C000-000000000046),
      helpcontext(0x0002004d),
      hidden
    ]
    dispinterface Spinner {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x00000267), propget, helpcontext(0x00010267)]
            Range* BottomRightCell();
            [id(0x0000025a), helpcontext(0x0001025a)]
            void BringToFront();
            [id(0x00000227), helpcontext(0x00010227)]
            void Copy();
            [id(0x000000d5), helpcontext(0x000100d5)]
            void CopyPicture(
                            [in, optional, defaultvalue(2)] XlPictureAppearance Appearance, 
                            [in, optional, defaultvalue(-4147)] XlCopyPictureFormat Format);
            [id(0x00000235), helpcontext(0x00010235)]
            void Cut();
            [id(0x00000075), helpcontext(0x00010075)]
            void Delete();
            [id(0x0000040f), helpcontext(0x0001040f)]
            IDispatch* Duplicate();
            [id(0x00000258), propget, helpcontext(0x00010258)]
            VARIANT_BOOL Enabled();
            [id(0x00000258), propput, helpcontext(0x00010258)]
            void Enabled([in] VARIANT_BOOL rhs);
            [id(0x0000007b), propget, helpcontext(0x0001007b)]
            double Height();
            [id(0x0000007b), propput, helpcontext(0x0001007b)]
            void Height([in] double rhs);
            [id(0x000001e6), propget, helpcontext(0x000101e6)]
            long Index();
            [id(0x0000007f), propget, helpcontext(0x0001007f)]
            double Left();
            [id(0x0000007f), propput, helpcontext(0x0001007f)]
            void Left([in] double rhs);
            [id(0x0000010d), propget, helpcontext(0x0001010d)]
            VARIANT_BOOL Locked();
            [id(0x0000010d), propput, helpcontext(0x0001010d)]
            void Locked([in] VARIANT_BOOL rhs);
            [id(0x0000006e), propget, helpcontext(0x0001006e)]
            BSTR Name();
            [id(0x0000006e), propput, helpcontext(0x0001006e)]
            void Name([in] BSTR rhs);
            [id(0x00000254), propget, hidden, helpcontext(0x00010254)]
            BSTR OnAction();
            [id(0x00000254), propput, hidden, helpcontext(0x00010254)]
            void OnAction([in] BSTR rhs);
            [id(0x00000269), propget, helpcontext(0x00010269)]
            VARIANT Placement();
            [id(0x00000269), propput, helpcontext(0x00010269)]
            void Placement([in] VARIANT rhs);
            [id(0x0000026a), propget, helpcontext(0x0001026a)]
            VARIANT_BOOL PrintObject();
            [id(0x0000026a), propput, helpcontext(0x0001026a)]
            void PrintObject([in] VARIANT_BOOL rhs);
            [id(0x000000eb), helpcontext(0x000100eb)]
            void Select([in, optional] VARIANT Replace);
            [id(0x0000025d), helpcontext(0x0001025d)]
            void SendToBack();
            [id(0x0000007e), propget, helpcontext(0x0001007e)]
            double Top();
            [id(0x0000007e), propput, helpcontext(0x0001007e)]
            void Top([in] double rhs);
            [id(0x0000026c), propget, helpcontext(0x0001026c)]
            Range* TopLeftCell();
            [id(0x0000022e), propget, helpcontext(0x0001022e)]
            VARIANT_BOOL Visible();
            [id(0x0000022e), propput, helpcontext(0x0001022e)]
            void Visible([in] VARIANT_BOOL rhs);
            [id(0x0000007a), propget, helpcontext(0x0001007a)]
            double Width();
            [id(0x0000007a), propput, helpcontext(0x0001007a)]
            void Width([in] double rhs);
            [id(0x0000026e), propget, helpcontext(0x0001026e)]
            long ZOrder();
            [id(0x000005f8), propget, helpcontext(0x000105f8)]
            ShapeRange* ShapeRange();
            [id(00000000), propget, helpcontext(0x00010000)]
            long _Default();
            [id(00000000), propput, helpcontext(0x00010000)]
            void _Default([in] long rhs);
            [id(0x00000462), propget, helpcontext(0x00010462)]
            VARIANT_BOOL Display3DShading();
            [id(0x00000462), propput, helpcontext(0x00010462)]
            void Display3DShading([in] VARIANT_BOOL rhs);
            [id(0x00000422), propget, helpcontext(0x00010422)]
            BSTR LinkedCell();
            [id(0x00000422), propput, helpcontext(0x00010422)]
            void LinkedCell([in] BSTR rhs);
            [id(0x0000034a), propget, helpcontext(0x0001034a)]
            long Max();
            [id(0x0000034a), propput, helpcontext(0x0001034a)]
            void Max([in] long rhs);
            [id(0x0000034b), propget, helpcontext(0x0001034b)]
            long Min();
            [id(0x0000034b), propput, helpcontext(0x0001034b)]
            void Min([in] long rhs);
            [id(0x0000034c), propget, helpcontext(0x0001034c)]
            long SmallChange();
            [id(0x0000034c), propput, helpcontext(0x0001034c)]
            void SmallChange([in] long rhs);
            [id(0x00000006), propget, helpcontext(0x00010006)]
            long Value();
            [id(0x00000006), propput, helpcontext(0x00010006)]
            void Value([in] long rhs);
    };

    [
      uuid(0002088E-0000-0000-C000-000000000046),
      helpcontext(0x0002004e),
      hidden
    ]
    dispinterface Spinners {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x00010003), restricted, hidden]
            void _Dummy3();
            [id(0x0000025a), helpcontext(0x0001025a)]
            void BringToFront();
            [id(0x00000227), helpcontext(0x00010227)]
            void Copy();
            [id(0x000000d5), helpcontext(0x000100d5)]
            void CopyPicture(
                            [in, optional, defaultvalue(2)] XlPictureAppearance Appearance, 
                            [in, optional, defaultvalue(-4147)] XlCopyPictureFormat Format);
            [id(0x00000235), helpcontext(0x00010235)]
            void Cut();
            [id(0x00000075), helpcontext(0x00010075)]
            void Delete();
            [id(0x0000040f), helpcontext(0x0001040f)]
            IDispatch* Duplicate();
            [id(0x00000258), propget, helpcontext(0x00010258)]
            VARIANT_BOOL Enabled();
            [id(0x00000258), propput, helpcontext(0x00010258)]
            void Enabled([in] VARIANT_BOOL rhs);
            [id(0x0000007b), propget, helpcontext(0x0001007b)]
            double Height();
            [id(0x0000007b), propput, helpcontext(0x0001007b)]
            void Height([in] double rhs);
            [id(0x0001000c), restricted, hidden]
            void _Dummy12();
            [id(0x0000007f), propget, helpcontext(0x0001007f)]
            double Left();
            [id(0x0000007f), propput, helpcontext(0x0001007f)]
            void Left([in] double rhs);
            [id(0x0000010d), propget, helpcontext(0x0001010d)]
            VARIANT_BOOL Locked();
            [id(0x0000010d), propput, helpcontext(0x0001010d)]
            void Locked([in] VARIANT_BOOL rhs);
            [id(0x0001000f), restricted, hidden]
            void _Dummy15();
            [id(0x00000254), propget, hidden, helpcontext(0x00010254)]
            BSTR OnAction();
            [id(0x00000254), propput, hidden, helpcontext(0x00010254)]
            void OnAction([in] BSTR rhs);
            [id(0x00000269), propget, helpcontext(0x00010269)]
            VARIANT Placement();
            [id(0x00000269), propput, helpcontext(0x00010269)]
            void Placement([in] VARIANT rhs);
            [id(0x0000026a), propget, helpcontext(0x0001026a)]
            VARIANT_BOOL PrintObject();
            [id(0x0000026a), propput, helpcontext(0x0001026a)]
            void PrintObject([in] VARIANT_BOOL rhs);
            [id(0x000000eb), helpcontext(0x000100eb)]
            void Select([in, optional] VARIANT Replace);
            [id(0x0000025d), helpcontext(0x0001025d)]
            void SendToBack();
            [id(0x0000007e), propget, helpcontext(0x0001007e)]
            double Top();
            [id(0x0000007e), propput, helpcontext(0x0001007e)]
            void Top([in] double rhs);
            [id(0x00010016), restricted, hidden]
            void _Dummy22();
            [id(0x0000022e), propget, helpcontext(0x0001022e)]
            VARIANT_BOOL Visible();
            [id(0x0000022e), propput, helpcontext(0x0001022e)]
            void Visible([in] VARIANT_BOOL rhs);
            [id(0x0000007a), propget, helpcontext(0x0001007a)]
            double Width();
            [id(0x0000007a), propput, helpcontext(0x0001007a)]
            void Width([in] double rhs);
            [id(0x0000026e), propget, helpcontext(0x0001026e)]
            long ZOrder();
            [id(0x000005f8), propget, helpcontext(0x000105f8)]
            ShapeRange* ShapeRange();
            [id(00000000), propget, helpcontext(0x00010000)]
            long _Default();
            [id(00000000), propput, helpcontext(0x00010000)]
            void _Default([in] long rhs);
            [id(0x00000462), propget, helpcontext(0x00010462)]
            VARIANT_BOOL Display3DShading();
            [id(0x00000462), propput, helpcontext(0x00010462)]
            void Display3DShading([in] VARIANT_BOOL rhs);
            [id(0x00000422), propget, helpcontext(0x00010422)]
            BSTR LinkedCell();
            [id(0x00000422), propput, helpcontext(0x00010422)]
            void LinkedCell([in] BSTR rhs);
            [id(0x0000034a), propget, helpcontext(0x0001034a)]
            long Max();
            [id(0x0000034a), propput, helpcontext(0x0001034a)]
            void Max([in] long rhs);
            [id(0x0000034b), propget, helpcontext(0x0001034b)]
            long Min();
            [id(0x0000034b), propput, helpcontext(0x0001034b)]
            void Min([in] long rhs);
            [id(0x0000034c), propget, helpcontext(0x0001034c)]
            long SmallChange();
            [id(0x0000034c), propput, helpcontext(0x0001034c)]
            void SmallChange([in] long rhs);
            [id(0x00000006), propget, helpcontext(0x00010006)]
            long Value();
            [id(0x00000006), propput, helpcontext(0x00010006)]
            void Value([in] long rhs);
            [id(0x000000b5), helpcontext(0x000100b5)]
            Spinner* Add(
                            [in] double Left, 
                            [in] double Top, 
                            [in] double Width, 
                            [in] double Height);
            [id(0x00000076), propget, helpcontext(0x00010076)]
            long Count();
            [id(0x0000002e), helpcontext(0x0001002e)]
            GroupObject* Group();
            [id(0x000000aa), helpcontext(0x000100aa)]
            IDispatch* Item([in] VARIANT Index);
            [id(0xfffffffc), helpcontext(0x0000fffc)]
            IUnknown* _NewEnum();
    };
