import "Excel17.Idl";


    [
      uuid(00020858-0000-0000-C000-000000000046),
      helpcontext(0x00020018)
    ]
    dispinterface AddIns {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x000000b5), helpcontext(0x000100b5)]
            AddIn* Add(
                            [in] BSTR Filename, 
                            [in, optional] VARIANT CopyFile);
            [id(0x00000076), propget, helpcontext(0x00010076)]
            long Count();
            [id(0x000000aa), propget, helpcontext(0x000100aa)]
            AddIn* Item([in] VARIANT Index);
            [id(0xfffffffc), propget, helpcontext(0x0000fffc)]
            IUnknown* _NewEnum();
            [id(00000000), propget, helpcontext(0x00010000)]
            AddIn* _Default([in] VARIANT Index);
    };

    [
      uuid(0002085C-0000-0000-C000-000000000046),
      helpcontext(0x0002001c),
      hidden
    ]
    dispinterface Toolbar {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x00000229), propget, helpcontext(0x00010229)]
            VARIANT_BOOL BuiltIn();
            [id(0x00000075), helpcontext(0x00010075)]
            void Delete();
            [id(0x0000007b), propget, helpcontext(0x0001007b)]
            long Height();
            [id(0x0000007b), propput, helpcontext(0x0001007b)]
            void Height([in] long rhs);
            [id(0x0000007f), propget, helpcontext(0x0001007f)]
            long Left();
            [id(0x0000007f), propput, helpcontext(0x0001007f)]
            void Left([in] long rhs);
            [id(0x0000006e), propget, helpcontext(0x0001006e)]
            BSTR Name();
            [id(0x00000085), propget, helpcontext(0x00010085)]
            long Position();
            [id(0x00000085), propput, helpcontext(0x00010085)]
            void Position([in] long rhs);
            [id(0x000000b0), propget, helpcontext(0x000100b0)]
            XlToolbarProtection Protection();
            [id(0x000000b0), propput, helpcontext(0x000100b0)]
            void Protection([in] XlToolbarProtection rhs);
            [id(0x0000022b), helpcontext(0x0001022b)]
            void Reset();
            [id(0x000003c4), propget, helpcontext(0x000103c4)]
            ToolbarButtons* ToolbarButtons();
            [id(0x0000007e), propget, helpcontext(0x0001007e)]
            long Top();
            [id(0x0000007e), propput, helpcontext(0x0001007e)]
            void Top([in] long rhs);
            [id(0x0000022e), propget, helpcontext(0x0001022e)]
            VARIANT_BOOL Visible();
            [id(0x0000022e), propput, helpcontext(0x0001022e)]
            void Visible([in] VARIANT_BOOL rhs);
            [id(0x0000007a), propget, helpcontext(0x0001007a)]
            long Width();
            [id(0x0000007a), propput, helpcontext(0x0001007a)]
            void Width([in] long rhs);
    };

    [
      uuid(0002085D-0000-0000-C000-000000000046),
      helpcontext(0x0002001d),
      hidden
    ]
    dispinterface Toolbars {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x000000b5), helpcontext(0x000100b5)]
            Toolbar* Add([in, optional] VARIANT Name);
            [id(0x00000076), propget, helpcontext(0x00010076)]
            long Count();
            [id(00000000), propget, helpcontext(0x00010000)]
            Toolbar* _Default([in] VARIANT Index);
            [id(0x000000aa), propget, helpcontext(0x000100aa)]
            Toolbar* Item([in] VARIANT Index);
            [id(0xfffffffc), propget, helpcontext(0x0000fffc)]
            IUnknown* _NewEnum();
    };

    [
      uuid(0002085E-0000-0000-C000-000000000046),
      helpcontext(0x0002001e),
      hidden
    ]
    dispinterface ToolbarButton {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x00000229), propget, helpcontext(0x00010229)]
            VARIANT_BOOL BuiltIn();
            [id(0x0000022a), propget, helpcontext(0x0001022a)]
            VARIANT_BOOL BuiltInFace();
            [id(0x0000022a), propput, helpcontext(0x0001022a)]
            void BuiltInFace([in] VARIANT_BOOL rhs);
            [id(0x00000227), helpcontext(0x00010227)]
            void Copy(
                            [in] Toolbar* Toolbar, 
                            [in] long Before);
            [id(0x000003c6), helpcontext(0x000103c6)]
            void CopyFace();
            [id(0x00000075), helpcontext(0x00010075)]
            void Delete();
            [id(0x00000232), helpcontext(0x00010232)]
            void Edit();
            [id(0x00000258), propget, helpcontext(0x00010258)]
            VARIANT_BOOL Enabled();
            [id(0x00000258), propput, helpcontext(0x00010258)]
            void Enabled([in] VARIANT_BOOL rhs);
            [id(0x00000163), propget, helpcontext(0x00010163)]
            long HelpContextID();
            [id(0x00000163), propput, helpcontext(0x00010163)]
            void HelpContextID([in] long rhs);
            [id(0x00000168), propget, helpcontext(0x00010168)]
            BSTR HelpFile();
            [id(0x00000168), propput, helpcontext(0x00010168)]
            void HelpFile([in] BSTR rhs);
            [id(0x0000023a), propget, helpcontext(0x0001023a)]
            long Id();
            [id(0x00000231), propget, helpcontext(0x00010231)]
            VARIANT_BOOL IsGap();
            [id(0x0000027d), helpcontext(0x0001027d)]
            void Move(
                            [in] Toolbar* Toolbar, 
                            [in] long Before);
            [id(0x0000006e), propget, helpcontext(0x0001006e)]
            BSTR Name();
            [id(0x0000006e), propput, helpcontext(0x0001006e)]
            void Name([in] BSTR rhs);
            [id(0x00000254), propget, helpcontext(0x00010254)]
            BSTR OnAction();
            [id(0x00000254), propput, helpcontext(0x00010254)]
            void OnAction([in] BSTR rhs);
            [id(0x000003c7), helpcontext(0x000103c7)]
            void PasteFace();
            [id(0x00000230), propget, helpcontext(0x00010230)]
            VARIANT_BOOL Pushed();
            [id(0x00000230), propput, helpcontext(0x00010230)]
            void Pushed([in] VARIANT_BOOL rhs);
            [id(0x0000022b), helpcontext(0x0001022b)]
            void Reset();
            [id(0x00000182), propget, helpcontext(0x00010182)]
            BSTR StatusBar();
            [id(0x00000182), propput, helpcontext(0x00010182)]
            void StatusBar([in] BSTR rhs);
            [id(0x0000007a), propget, helpcontext(0x0001007a)]
            long Width();
            [id(0x0000007a), propput, helpcontext(0x0001007a)]
            void Width([in] long rhs);
    };

    [
      uuid(0002085F-0000-0000-C000-000000000046),
      helpcontext(0x0002001f),
      hidden
    ]
    dispinterface ToolbarButtons {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x000000b5), helpcontext(0x000100b5)]
            ToolbarButton* Add(
                            [in, optional] VARIANT Button, 
                            [in, optional] VARIANT Before, 
                            [in, optional] VARIANT OnAction, 
                            [in, optional] VARIANT Pushed, 
                            [in, optional] VARIANT Enabled, 
                            [in, optional] VARIANT StatusBar, 
                            [in, optional] VARIANT HelpFile, 
                            [in, optional] VARIANT HelpContextID);
            [id(0x00000076), propget, helpcontext(0x00010076)]
            long Count();
            [id(0x000000aa), propget, helpcontext(0x000100aa)]
            ToolbarButton* Item([in] long Index);
            [id(0xfffffffc), propget, helpcontext(0x0000fffc)]
            IUnknown* _NewEnum();
            [id(00000000), propget, helpcontext(0x00010000)]
            ToolbarButton* _Default([in] long Index);
    };

    [
      uuid(00020860-0000-0000-C000-000000000046),
      helpcontext(0x00020020)
    ]
    dispinterface Areas {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x00000076), propget, helpcontext(0x00010076)]
            long Count();
            [id(0x000000aa), propget, helpcontext(0x000100aa)]
            Range* Item([in] long Index);
            [id(0xfffffffc), propget, helpcontext(0x0000fffc)]
            IUnknown* _NewEnum();
            [id(00000000), propget, helpcontext(0x00010000)]
            Range* _Default([in] long Index);
    };

    [
      uuid(00024412-0000-0000-C000-000000000046),
      helpcontext(0x000200a8),
      hidden
    ]
    dispinterface WorkbookEvents {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x000002aa), helpcontext(0x000102aa)]
            void Open();
            [id(0x00000130), helpcontext(0x00010130)]
            void Activate();
            [id(0x000005fa), helpcontext(0x000105fa)]
            void Deactivate();
            [id(0x0000060a), helpcontext(0x0001060a)]
            void BeforeClose([in] VARIANT_BOOL* Cancel);
            [id(0x0000060b), helpcontext(0x0001060b)]
            void BeforeSave(
                            [in] VARIANT_BOOL SaveAsUI, 
                            [in] VARIANT_BOOL* Cancel);
            [id(0x0000060d), helpcontext(0x0001060d)]
            void BeforePrint([in] VARIANT_BOOL* Cancel);
            [id(0x0000060e), helpcontext(0x0001060e)]
            void NewSheet([in] IDispatch* Sh);
            [id(0x00000610), helpcontext(0x00010610)]
            void AddinInstall();
            [id(0x00000611), helpcontext(0x00010611)]
            void AddinUninstall();
            [id(0x00000612), helpcontext(0x00010612)]
            void WindowResize([in] Window* Wn);
            [id(0x00000614), helpcontext(0x00010614)]
            void WindowActivate([in] Window* Wn);
            [id(0x00000615), helpcontext(0x00010615)]
            void WindowDeactivate([in] Window* Wn);
            [id(0x00000616), helpcontext(0x00010616)]
            void SheetSelectionChange(
                            [in] IDispatch* Sh, 
                            [in] Range* Target);
            [id(0x00000617), helpcontext(0x00010617)]
            void SheetBeforeDoubleClick(
                            [in] IDispatch* Sh, 
                            [in] Range* Target, 
                            [in] VARIANT_BOOL* Cancel);
            [id(0x00000618), helpcontext(0x00010618)]
            void SheetBeforeRightClick(
                            [in] IDispatch* Sh, 
                            [in] Range* Target, 
                            [in] VARIANT_BOOL* Cancel);
            [id(0x00000619), helpcontext(0x00010619)]
            void SheetActivate([in] IDispatch* Sh);
            [id(0x0000061a), helpcontext(0x0001061a)]
            void SheetDeactivate([in] IDispatch* Sh);
            [id(0x0000061b), helpcontext(0x0001061b)]
            void SheetCalculate([in] IDispatch* Sh);
            [id(0x0000061c), helpcontext(0x0001061c)]
            void SheetChange(
                            [in] IDispatch* Sh, 
                            [in] Range* Target);
    };

    [
      uuid(00020863-0000-0000-C000-000000000046),
      helpcontext(0x00020023),
      hidden
    ]
    dispinterface MenuBars {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x000000b5), helpcontext(0x000100b5)]
            MenuBar* Add([in, optional] VARIANT Name);
            [id(0x00000076), propget, helpcontext(0x00010076)]
            long Count();
            [id(00000000), propget, helpcontext(0x00010000)]
            MenuBar* _Default([in] VARIANT Index);
            [id(0x000000aa), propget, helpcontext(0x000100aa)]
            MenuBar* Item([in] VARIANT Index);
            [id(0xfffffffc), propget, helpcontext(0x0000fffc)]
            IUnknown* _NewEnum();
    };

    [
      uuid(00020864-0000-0000-C000-000000000046),
      helpcontext(0x00020024),
      hidden
    ]
    dispinterface MenuBar {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x00000130), helpcontext(0x00010130)]
            void Activate();
            [id(0x00000229), propget, helpcontext(0x00010229)]
            VARIANT_BOOL BuiltIn();
            [id(0x0000008b), propget, helpcontext(0x0001008b)]
            BSTR Caption();
            [id(0x0000008b), propput, helpcontext(0x0001008b)]
            void Caption([in] BSTR rhs);
            [id(0x00000075), helpcontext(0x00010075)]
            void Delete();
            [id(0x000001e6), propget, helpcontext(0x000101e6)]
            long Index();
            [id(0x0000024f), propget, helpcontext(0x0001024f)]
            Menus* Menus();
            [id(0x0000022b), helpcontext(0x0001022b)]
            void Reset();
    };

    [
      uuid(00020865-0000-0000-C000-000000000046),
      helpcontext(0x00020025),
      hidden
    ]
    dispinterface Menus {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x000000b5), helpcontext(0x000100b5)]
            Menu* Add(
                            [in] BSTR Caption, 
                            [in, optional] VARIANT Before, 
                            [in, optional] VARIANT Restore);
            [id(0x00000076), propget, helpcontext(0x00010076)]
            long Count();
            [id(00000000), propget, helpcontext(0x00010000)]
            Menu* _Default([in] VARIANT Index);
            [id(0x000000aa), propget, helpcontext(0x000100aa)]
            Menu* Item([in] VARIANT Index);
            [id(0xfffffffc), propget, helpcontext(0x0000fffc)]
            IUnknown* _NewEnum();
    };

    [
      uuid(00020866-0000-0000-C000-000000000046),
      helpcontext(0x00020026),
      hidden
    ]
    dispinterface Menu {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x0000008b), propget, helpcontext(0x0001008b)]
            BSTR Caption();
            [id(0x0000008b), propput, helpcontext(0x0001008b)]
            void Caption([in] BSTR rhs);
            [id(0x00000075), helpcontext(0x00010075)]
            void Delete();
            [id(0x00000258), propget, helpcontext(0x00010258)]
            VARIANT_BOOL Enabled();
            [id(0x00000258), propput, helpcontext(0x00010258)]
            void Enabled([in] VARIANT_BOOL rhs);
            [id(0x000001e6), propget, helpcontext(0x000101e6)]
            long Index();
            [id(0x00000251), propget, helpcontext(0x00010251)]
            MenuItems* MenuItems();
    };

    [
      uuid(00020867-0000-0000-C000-000000000046),
      helpcontext(0x00020027),
      hidden
    ]
    dispinterface MenuItems {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x000000b5), helpcontext(0x000100b5)]
            MenuItem* Add(
                            [in] BSTR Caption, 
                            [in, optional] VARIANT OnAction, 
                            [in, optional] VARIANT ShortcutKey, 
                            [in, optional] VARIANT Before, 
                            [in, optional] VARIANT Restore, 
                            [in, optional] VARIANT StatusBar, 
                            [in, optional] VARIANT HelpFile, 
                            [in, optional] VARIANT HelpContextID);
            [id(0x00000256), helpcontext(0x00010256)]
            Menu* AddMenu(
                            [in] BSTR Caption, 
                            [in, optional] VARIANT Before, 
                            [in, optional] VARIANT Restore);
            [id(0x00000076), propget, helpcontext(0x00010076)]
            long Count();
            [id(00000000), propget, helpcontext(0x00010000)]
            IDispatch* _Default([in] VARIANT Index);
            [id(0x000000aa), propget, helpcontext(0x000100aa)]
            IDispatch* Item([in] VARIANT Index);
            [id(0xfffffffc), propget, helpcontext(0x0000fffc)]
            IUnknown* _NewEnum();
    };

    [
      uuid(00020868-0000-0000-C000-000000000046),
      helpcontext(0x00020028),
      hidden
    ]
    dispinterface MenuItem {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x0000008b), propget, helpcontext(0x0001008b)]
            BSTR Caption();
            [id(0x0000008b), propput, helpcontext(0x0001008b)]
            void Caption([in] BSTR rhs);
            [id(0x00000257), propget, helpcontext(0x00010257)]
            VARIANT_BOOL Checked();
            [id(0x00000257), propput, helpcontext(0x00010257)]
            void Checked([in] VARIANT_BOOL rhs);
            [id(0x00000075), helpcontext(0x00010075)]
            void Delete();
            [id(0x00000258), propget, helpcontext(0x00010258)]
            VARIANT_BOOL Enabled();
            [id(0x00000258), propput, helpcontext(0x00010258)]
            void Enabled([in] VARIANT_BOOL rhs);
            [id(0x00000163), propget, helpcontext(0x00010163)]
            long HelpContextID();
            [id(0x00000163), propput, helpcontext(0x00010163)]
            void HelpContextID([in] long rhs);
            [id(0x00000168), propget, helpcontext(0x00010168)]
            BSTR HelpFile();
            [id(0x00000168), propput, helpcontext(0x00010168)]
            void HelpFile([in] BSTR rhs);
            [id(0x000001e6), propget, helpcontext(0x000101e6)]
            long Index();
            [id(0x00000254), propget, helpcontext(0x00010254)]
            BSTR OnAction();
            [id(0x00000254), propput, helpcontext(0x00010254)]
            void OnAction([in] BSTR rhs);
            [id(0x00000182), propget, helpcontext(0x00010182)]
            BSTR StatusBar();
            [id(0x00000182), propput, helpcontext(0x00010182)]
            void StatusBar([in] BSTR rhs);
    };

    [
      uuid(0002086D-0000-0000-C000-000000000046),
      helpcontext(0x0002002d)
    ]
    dispinterface Charts {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x000000b5), helpcontext(0x000100b5)]
            Chart* Add(
                            [in, optional] VARIANT Before, 
                            [in, optional] VARIANT After, 
                            [in, optional] VARIANT Count);
            [id(0x00000227), helpcontext(0x00010227)]
            void Copy(
                            [in, optional] VARIANT Before, 
                            [in, optional] VARIANT After);
            [id(0x00000076), propget, helpcontext(0x00010076)]
            long Count();
            [id(0x00000075), helpcontext(0x00010075)]
            void Delete();
            [id(0x00010007), restricted, hidden]
            void _Dummy7();
            [id(0x000000aa), propget, helpcontext(0x000100aa)]
            IDispatch* Item([in] VARIANT Index);
            [id(0x0000027d), helpcontext(0x0001027d)]
            void Move(
                            [in, optional] VARIANT Before, 
                            [in, optional] VARIANT After);
            [id(0xfffffffc), propget, helpcontext(0x0000fffc)]
            IUnknown* _NewEnum();
            [id(0x00000389), helpcontext(0x00010389)]
            void PrintOut(
                            [in, optional] VARIANT From, 
                            [in, optional] VARIANT To, 
                            [in, optional] VARIANT Copies, 
                            [in, optional] VARIANT Preview, 
                            [in, optional] VARIANT ActivePrinter, 
                            [in, optional] VARIANT PrintToFile, 
                            [in, optional] VARIANT Collate);
            [id(0x00000119), helpcontext(0x00010119)]
            void PrintPreview([in, optional] VARIANT EnableChanges);
            [id(0x000000eb), helpcontext(0x000100eb)]
            void Select([in, optional] VARIANT Replace);
            [id(0x0000058a), propget, helpcontext(0x0001058a)]
            HPageBreaks* HPageBreaks();
            [id(0x0000058b), propget, helpcontext(0x0001058b)]
            VPageBreaks* VPageBreaks();
            [id(0x0000022e), propget, helpcontext(0x0001022e)]
            VARIANT Visible();
            [id(0x0000022e), propput, helpcontext(0x0001022e)]
            void Visible([in] VARIANT rhs);
            [id(00000000), propget, helpcontext(0x00010000)]
            IDispatch* _Default([in] VARIANT Index);
    };

    [
      uuid(0002086F-0000-0000-C000-000000000046),
      helpcontext(0x0002002f),
      hidden
    ]
    dispinterface DrawingObjects {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x00010003), restricted, hidden]
            void _Dummy3();
            [id(0x0000025a), helpcontext(0x0001025a)]
            void BringToFront();
            [id(0x00000227), helpcontext(0x00010227)]
            void Copy();
            [id(0x000000d5), helpcontext(0x000100d5)]
            void CopyPicture(
                            [in, optional, defaultvalue(2)] XlPictureAppearance Appearance, 
                            [in, optional, defaultvalue(-4147)] XlCopyPictureFormat Format);
            [id(0x00000235), helpcontext(0x00010235)]
            void Cut();
            [id(0x00000075), helpcontext(0x00010075)]
            void Delete();
            [id(0x0000040f), helpcontext(0x0001040f)]
            IDispatch* Duplicate();
            [id(0x00000258), propget, helpcontext(0x00010258)]
            VARIANT_BOOL Enabled();
            [id(0x00000258), propput, helpcontext(0x00010258)]
            void Enabled([in] VARIANT_BOOL rhs);
            [id(0x0000007b), propget, helpcontext(0x0001007b)]
            double Height();
            [id(0x0000007b), propput, helpcontext(0x0001007b)]
            void Height([in] double rhs);
            [id(0x0001000c), restricted, hidden]
            void _Dummy12();
            [id(0x0000007f), propget, helpcontext(0x0001007f)]
            double Left();
            [id(0x0000007f), propput, helpcontext(0x0001007f)]
            void Left([in] double rhs);
            [id(0x0000010d), propget, helpcontext(0x0001010d)]
            VARIANT_BOOL Locked();
            [id(0x0000010d), propput, helpcontext(0x0001010d)]
            void Locked([in] VARIANT_BOOL rhs);
            [id(0x0001000f), restricted, hidden]
            void _Dummy15();
            [id(0x00000254), propget, hidden, helpcontext(0x00010254)]
            BSTR OnAction();
            [id(0x00000254), propput, hidden, helpcontext(0x00010254)]
            void OnAction([in] BSTR rhs);
            [id(0x00000269), propget, helpcontext(0x00010269)]
            VARIANT Placement();
            [id(0x00000269), propput, helpcontext(0x00010269)]
            void Placement([in] VARIANT rhs);
            [id(0x0000026a), propget, helpcontext(0x0001026a)]
            VARIANT_BOOL PrintObject();
            [id(0x0000026a), propput, helpcontext(0x0001026a)]
            void PrintObject([in] VARIANT_BOOL rhs);
            [id(0x000000eb), helpcontext(0x000100eb)]
            void Select([in, optional] VARIANT Replace);
            [id(0x0000025d), helpcontext(0x0001025d)]
            void SendToBack();
            [id(0x0000007e), propget, helpcontext(0x0001007e)]
            double Top();
            [id(0x0000007e), propput, helpcontext(0x0001007e)]
            void Top([in] double rhs);
            [id(0x00010016), restricted, hidden]
            void _Dummy22();
            [id(0x0000022e), propget, helpcontext(0x0001022e)]
            VARIANT_BOOL Visible();
            [id(0x0000022e), propput, helpcontext(0x0001022e)]
            void Visible([in] VARIANT_BOOL rhs);
            [id(0x0000007a), propget, helpcontext(0x0001007a)]
            double Width();
            [id(0x0000007a), propput, helpcontext(0x0001007a)]
            void Width([in] double rhs);
            [id(0x0000026e), propget, helpcontext(0x0001026e)]
            long ZOrder();
            [id(0x000005f8), propget, helpcontext(0x000105f8)]
            ShapeRange* ShapeRange();
            [id(0x0000034e), propget, helpcontext(0x0001034e)]
            VARIANT Accelerator();
            [id(0x0000034e), propput, helpcontext(0x0001034e)]
            void Accelerator([in] VARIANT rhs);
            [id(0x0001001c), restricted, hidden]
            void _Dummy28();
            [id(0x00000427), propget, helpcontext(0x00010427)]
            VARIANT_BOOL AddIndent();
            [id(0x00000427), propput, helpcontext(0x00010427)]
            void AddIndent([in] VARIANT_BOOL rhs);
            [id(0x00000353), helpcontext(0x00010353)]
            void AddItem(
                            [in] VARIANT Text, 
                            [in, optional] VARIANT Index);
            [id(0x00000263), propget, helpcontext(0x00010263)]
            VARIANT ArrowHeadLength();
            [id(0x00000263), propput, helpcontext(0x00010263)]
            void ArrowHeadLength([in] VARIANT rhs);
            [id(0x00000264), propget, helpcontext(0x00010264)]
            VARIANT ArrowHeadStyle();
            [id(0x00000264), propput, helpcontext(0x00010264)]
            void ArrowHeadStyle([in] VARIANT rhs);
            [id(0x00000265), propget, helpcontext(0x00010265)]
            VARIANT ArrowHeadWidth();
            [id(0x00000265), propput, helpcontext(0x00010265)]
            void ArrowHeadWidth([in] VARIANT rhs);
            [id(0x00000266), propget, helpcontext(0x00010266)]
            VARIANT_BOOL AutoSize();
            [id(0x00000266), propput, helpcontext(0x00010266)]
            void AutoSize([in] VARIANT_BOOL rhs);
            [id(0x00000080), propget, helpcontext(0x00010080)]
            Border* Border();
            [id(0x0000035a), propget, helpcontext(0x0001035a)]
            VARIANT_BOOL CancelButton();
            [id(0x0000035a), propput, helpcontext(0x0001035a)]
            void CancelButton([in] VARIANT_BOOL rhs);
            [id(0x0000008b), propget, helpcontext(0x0001008b)]
            BSTR Caption();
            [id(0x0000008b), propput, helpcontext(0x0001008b)]
            void Caption([in] BSTR rhs);
            [id(0x0000025b), propget, helpcontext(0x0001025b)]
            Characters* Characters(
                            [in, optional] VARIANT Start, 
                            [in, optional] VARIANT Length);
            [id(0x000001f9), helpcontext(0x000101f9)]
            void CheckSpelling(
                            [in, optional] VARIANT CustomDictionary, 
                            [in, optional] VARIANT IgnoreUppercase, 
                            [in, optional] VARIANT AlwaysSuggest, 
                            [in, optional] VARIANT IgnoreInitialAlefHamza, 
                            [in, optional] VARIANT IgnoreFinalYaa, 
                            [in, optional] VARIANT SpellScript);
            [id(00000000), propget, helpcontext(0x00010000)]
            long _Default();
            [id(00000000), propput, helpcontext(0x00010000)]
            void _Default([in] long rhs);
            [id(0x00000359), propget, helpcontext(0x00010359)]
            VARIANT_BOOL DefaultButton();
            [id(0x00000359), propput, helpcontext(0x00010359)]
            void DefaultButton([in] VARIANT_BOOL rhs);
            [id(0x0000035b), propget, helpcontext(0x0001035b)]
            VARIANT_BOOL DismissButton();
            [id(0x0000035b), propput, helpcontext(0x0001035b)]
            void DismissButton([in] VARIANT_BOOL rhs);
            [id(0x00000462), propget, helpcontext(0x00010462)]
            VARIANT_BOOL Display3DShading();
            [id(0x00000462), propput, helpcontext(0x00010462)]
            void Display3DShading([in] VARIANT_BOOL rhs);
            [id(0x0000039a), propget, helpcontext(0x0001039a)]
            VARIANT_BOOL DisplayVerticalScrollBar();
            [id(0x0000039a), propput, helpcontext(0x0001039a)]
            void DisplayVerticalScrollBar([in] VARIANT_BOOL rhs);
            [id(0x00000350), propget, helpcontext(0x00010350)]
            long DropDownLines();
            [id(0x00000350), propput, helpcontext(0x00010350)]
            void DropDownLines([in] long rhs);
            [id(0x00000092), propget, helpcontext(0x00010092)]
            Font* Font();
            [id(0x0001002f), restricted, hidden]
            void _Dummy47();
            [id(0x0000035c), propget, helpcontext(0x0001035c)]
            VARIANT_BOOL HelpButton();
            [id(0x0000035c), propput, helpcontext(0x0001035c)]
            void HelpButton([in] VARIANT_BOOL rhs);
            [id(0x00000088), propget, helpcontext(0x00010088)]
            VARIANT HorizontalAlignment();
            [id(0x00000088), propput, helpcontext(0x00010088)]
            void HorizontalAlignment([in] VARIANT rhs);
            [id(0x00000356), propget, helpcontext(0x00010356)]
            long InputType();
            [id(0x00000356), propput, helpcontext(0x00010356)]
            void InputType([in] long rhs);
            [id(0x00000081), propget, helpcontext(0x00010081)]
            Interior* Interior();
            [id(0x0000034d), propget, helpcontext(0x0001034d)]
            long LargeChange();
            [id(0x0000034d), propput, helpcontext(0x0001034d)]
            void LargeChange([in] long rhs);
            [id(0x00000422), propget, helpcontext(0x00010422)]
            BSTR LinkedCell();
            [id(0x00000422), propput, helpcontext(0x00010422)]
            void LinkedCell([in] BSTR rhs);
            [id(0x00010036), restricted, hidden]
            void _Dummy54();
            [id(0x0000035d), helpcontext(0x0001035d)]
            VARIANT List([in, optional] VARIANT Index);
            [id(0x00010038), restricted, hidden]
            void _Dummy56();
            [id(0x0000034f), propget, helpcontext(0x0001034f)]
            BSTR ListFillRange();
            [id(0x0000034f), propput, helpcontext(0x0001034f)]
            void ListFillRange([in] BSTR rhs);
            [id(0x00000352), propget, helpcontext(0x00010352)]
            long ListIndex();
            [id(0x00000352), propput, helpcontext(0x00010352)]
            void ListIndex([in] long rhs);
            [id(0x00000268), propget, helpcontext(0x00010268)]
            VARIANT_BOOL LockedText();
            [id(0x00000268), propput, helpcontext(0x00010268)]
            void LockedText([in] VARIANT_BOOL rhs);
            [id(0x0000034a), propget, helpcontext(0x0001034a)]
            long Max();
            [id(0x0000034a), propput, helpcontext(0x0001034a)]
            void Max([in] long rhs);
            [id(0x0000034b), propget, helpcontext(0x0001034b)]
            long Min();
            [id(0x0000034b), propput, helpcontext(0x0001034b)]
            void Min([in] long rhs);
            [id(0x00000357), propget, helpcontext(0x00010357)]
            VARIANT_BOOL MultiLine();
            [id(0x00000357), propput, helpcontext(0x00010357)]
            void MultiLine([in] VARIANT_BOOL rhs);
            [id(0x00000020), propget, helpcontext(0x00010020)]
            VARIANT_BOOL MultiSelect();
            [id(0x00000020), propput, helpcontext(0x00010020)]
            void MultiSelect([in] VARIANT_BOOL rhs);
            [id(0x00000086), propget, helpcontext(0x00010086)]
            VARIANT Orientation();
            [id(0x00000086), propput, helpcontext(0x00010086)]
            void Orientation([in] VARIANT rhs);
            [id(0x00000461), propget, helpcontext(0x00010461)]
            VARIANT PhoneticAccelerator();
            [id(0x00000461), propput, helpcontext(0x00010461)]
            void PhoneticAccelerator([in] VARIANT rhs);
            [id(0x00000355), helpcontext(0x00010355)]
            void RemoveAllItems();
            [id(0x00000354), helpcontext(0x00010354)]
            void RemoveItem(
                            [in] long Index, 
                            [in, optional] VARIANT Count);
            [id(0x0000025c), helpcontext(0x0001025c)]
            void Reshape(
                            [in] long Vertex, 
                            [in] VARIANT Insert, 
                            [in, optional] VARIANT Left, 
                            [in, optional] VARIANT Top);
            [id(0x0000026b), propget, helpcontext(0x0001026b)]
            VARIANT_BOOL RoundedCorners();
            [id(0x0000026b), propput, helpcontext(0x0001026b)]
            void RoundedCorners([in] VARIANT_BOOL rhs);
            [id(0x00000463), helpcontext(0x00010463)]
            VARIANT Selected([in, optional] VARIANT Index);
            [id(0x00000067), propget, helpcontext(0x00010067)]
            VARIANT_BOOL Shadow();
            [id(0x00000067), propput, helpcontext(0x00010067)]
            void Shadow([in] VARIANT_BOOL rhs);
            [id(0x0000034c), propget, helpcontext(0x0001034c)]
            long SmallChange();
            [id(0x0000034c), propput, helpcontext(0x0001034c)]
            void SmallChange([in] long rhs);
            [id(0x0000008a), propget, helpcontext(0x0001008a)]
            BSTR Text();
            [id(0x0000008a), propput, helpcontext(0x0001008a)]
            void Text([in] BSTR rhs);
            [id(0x000000f4), helpcontext(0x000100f4)]
            IDispatch* Ungroup();
            [id(0x00000006), propget, helpcontext(0x00010006)]
            long Value();
            [id(0x00000006), propput, helpcontext(0x00010006)]
            void Value([in] long rhs);
            [id(0x00000089), propget, helpcontext(0x00010089)]
            VARIANT VerticalAlignment();
            [id(0x00000089), propput, helpcontext(0x00010089)]
            void VerticalAlignment([in] VARIANT rhs);
            [id(0x0000026d), helpcontext(0x0001026d)]
            VARIANT Vertices(
                            [in, optional] VARIANT Index1, 
                            [in, optional] VARIANT Index2);
            [id(0x000003cf), propget, helpcontext(0x000103cf)]
            long ReadingOrder();
            [id(0x000003cf), propput, helpcontext(0x000103cf)]
            void ReadingOrder([in] long rhs);
            [id(0x00000076), propget, helpcontext(0x00010076)]
            long Count();
            [id(0x000000aa), helpcontext(0x000100aa)]
            IDispatch* Item([in] VARIANT Index);
            [id(0x0000002e), helpcontext(0x0001002e)]
            GroupObject* Group();
            [id(0x00000358), helpcontext(0x00010358)]
            void LinkCombo([in, optional] VARIANT Link);
            [id(0xfffffffc), helpcontext(0x0000fffc)]
            IUnknown* _NewEnum();
    };

    [
      uuid(0002441C-0000-0000-C000-000000000046),
      helpcontext(0x000200b2)
    ]
    dispinterface PivotCache {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x00000593), propget, helpcontext(0x00010593)]
            VARIANT_BOOL BackgroundQuery();
            [id(0x00000593), propput, helpcontext(0x00010593)]
            void BackgroundQuery([in] VARIANT_BOOL rhs);
            [id(0x00000598), propget, helpcontext(0x00010598)]
            VARIANT Connection();
            [id(0x00000598), propput, helpcontext(0x00010598)]
            void Connection([in] VARIANT rhs);
            [id(0x000005c5), propget, helpcontext(0x000105c5)]
            VARIANT_BOOL EnableRefresh();
            [id(0x000005c5), propput, helpcontext(0x000105c5)]
            void EnableRefresh([in] VARIANT_BOOL rhs);
            [id(0x000001e6), propget, helpcontext(0x000101e6)]
            long Index();
            [id(0x00000174), propget, helpcontext(0x00010174)]
            long MemoryUsed();
            [id(0x00000594), propget, helpcontext(0x00010594)]
            VARIANT_BOOL OptimizeCache();
            [id(0x00000594), propput, helpcontext(0x00010594)]
            void OptimizeCache([in] VARIANT_BOOL rhs);
            [id(0x000005c6), propget, helpcontext(0x000105c6)]
            long RecordCount();
            [id(0x00000589), helpcontext(0x00010589)]
            void Refresh();
            [id(0x000002b8), propget, helpcontext(0x000102b8)]
            DATE RefreshDate();
            [id(0x000002b9), propget, helpcontext(0x000102b9)]
            BSTR RefreshName();
            [id(0x000005c7), propget, helpcontext(0x000105c7)]
            VARIANT_BOOL RefreshOnFileOpen();
            [id(0x000005c7), propput, helpcontext(0x000105c7)]
            void RefreshOnFileOpen([in] VARIANT_BOOL rhs);
            [id(0x000005c8), propget, helpcontext(0x000105c8)]
            VARIANT Sql();
            [id(0x000005c8), propput, helpcontext(0x000105c8)]
            void Sql([in] VARIANT rhs);
            [id(0x000005c9), propget, helpcontext(0x000105c9)]
            VARIANT_BOOL SavePassword();
            [id(0x000005c9), propput, helpcontext(0x000105c9)]
            void SavePassword([in] VARIANT_BOOL rhs);
            [id(0x000002ae), propget, helpcontext(0x000102ae)]
            VARIANT SourceData();
            [id(0x000002ae), propput, helpcontext(0x000102ae)]
            void SourceData([in] VARIANT rhs);
    };

    [
      uuid(0002441D-0000-0000-C000-000000000046),
      helpcontext(0x000200b3)
    ]
    dispinterface PivotCaches {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x00000076), propget, helpcontext(0x00010076)]
            long Count();
            [id(0x000000aa), helpcontext(0x000100aa)]
            PivotCache* Item([in] VARIANT Index);
            [id(00000000), propget, helpcontext(0x00010000)]
            PivotCache* _Default([in] VARIANT Index);
            [id(0xfffffffc), helpcontext(0x0000fffc)]
            IUnknown* _NewEnum();
    };

