import "Excel27.Idl";

    [
      uuid(000208C2-0000-0000-C000-000000000046),
      helpcontext(0x00020082)
    ]
    dispinterface HiLoLines {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x0000006e), propget, helpcontext(0x0001006e)]
            BSTR Name();
            [id(0x000000eb), helpcontext(0x000100eb)]
            void Select();
            [id(0x00000080), propget, helpcontext(0x00010080)]
            Border* Border();
            [id(0x00000075), helpcontext(0x00010075)]
            void Delete();
    };

    [
      uuid(000208C3-0000-0000-C000-000000000046),
      helpcontext(0x00020083)
    ]
    dispinterface Gridlines {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x0000006e), propget, helpcontext(0x0001006e)]
            BSTR Name();
            [id(0x000000eb), helpcontext(0x000100eb)]
            void Select();
            [id(0x00000080), propget, helpcontext(0x00010080)]
            Border* Border();
            [id(0x00000075), helpcontext(0x00010075)]
            void Delete();
    };

    [
      uuid(000208C4-0000-0000-C000-000000000046),
      helpcontext(0x00020084)
    ]
    dispinterface DropLines {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x0000006e), propget, helpcontext(0x0001006e)]
            BSTR Name();
            [id(0x000000eb), helpcontext(0x000100eb)]
            void Select();
            [id(0x00000080), propget, helpcontext(0x00010080)]
            Border* Border();
            [id(0x00000075), helpcontext(0x00010075)]
            void Delete();
    };

    [
      uuid(00024437-0000-0000-C000-000000000046),
      helpcontext(0x000200cd)
    ]
    dispinterface LeaderLines {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x00000080), propget, helpcontext(0x00010080)]
            Border* Border();
            [id(0x00000075), helpcontext(0x00010075)]
            void Delete();
            [id(0x000000eb), helpcontext(0x000100eb)]
            void Select();
    };

    [
      uuid(000208C5-0000-0000-C000-000000000046),
      helpcontext(0x00020085)
    ]
    dispinterface UpBars {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x0000006e), propget, helpcontext(0x0001006e)]
            BSTR Name();
            [id(0x000000eb), helpcontext(0x000100eb)]
            void Select();
            [id(0x00000080), propget, helpcontext(0x00010080)]
            Border* Border();
            [id(0x00000075), helpcontext(0x00010075)]
            void Delete();
            [id(0x00000081), propget, helpcontext(0x00010081)]
            Interior* Interior();
            [id(0x0000067f), propget, helpcontext(0x0001067f)]
            ChartFillFormat* Fill();
    };

    [
      uuid(000208C6-0000-0000-C000-000000000046),
      helpcontext(0x00020086)
    ]
    dispinterface DownBars {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x0000006e), propget, helpcontext(0x0001006e)]
            BSTR Name();
            [id(0x000000eb), helpcontext(0x000100eb)]
            void Select();
            [id(0x00000080), propget, helpcontext(0x00010080)]
            Border* Border();
            [id(0x00000075), helpcontext(0x00010075)]
            void Delete();
            [id(0x00000081), propget, helpcontext(0x00010081)]
            Interior* Interior();
            [id(0x0000067f), propget, helpcontext(0x0001067f)]
            ChartFillFormat* Fill();
    };

    [
      uuid(000208C7-0000-0000-C000-000000000046),
      helpcontext(0x00020087)
    ]
    dispinterface Floor {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x0000006e), propget, helpcontext(0x0001006e)]
            BSTR Name();
            [id(0x000000eb), helpcontext(0x000100eb)]
            void Select();
            [id(0x00000080), propget, helpcontext(0x00010080)]
            Border* Border();
            [id(0x00000070), helpcontext(0x00010070)]
            void ClearFormats();
            [id(0x00000081), propget, helpcontext(0x00010081)]
            Interior* Interior();
            [id(0x0000067f), propget, helpcontext(0x0001067f)]
            ChartFillFormat* Fill();
            [id(0x000000a1), propget, helpcontext(0x000100a1)]
            VARIANT PictureType();
            [id(0x000000a1), propput, helpcontext(0x000100a1)]
            void PictureType([in] VARIANT rhs);
            [id(0x000000d3), helpcontext(0x000100d3)]
            void Paste();
    };

    [
      uuid(000208C8-0000-0000-C000-000000000046),
      helpcontext(0x00020088)
    ]
    dispinterface Walls {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x0000006e), propget, helpcontext(0x0001006e)]
            BSTR Name();
            [id(0x000000eb), helpcontext(0x000100eb)]
            void Select();
            [id(0x00000080), propget, helpcontext(0x00010080)]
            Border* Border();
            [id(0x00000070), helpcontext(0x00010070)]
            void ClearFormats();
            [id(0x00000081), propget, helpcontext(0x00010081)]
            Interior* Interior();
            [id(0x0000067f), propget, helpcontext(0x0001067f)]
            ChartFillFormat* Fill();
            [id(0x000000a1), propget, helpcontext(0x000100a1)]
            VARIANT PictureType();
            [id(0x000000a1), propput, helpcontext(0x000100a1)]
            void PictureType([in] VARIANT rhs);
            [id(0x000000d3), helpcontext(0x000100d3)]
            void Paste();
            [id(0x000000a2), propget, helpcontext(0x000100a2)]
            VARIANT PictureUnit();
            [id(0x000000a2), propput, helpcontext(0x000100a2)]
            void PictureUnit([in] VARIANT rhs);
    };

    [
      uuid(000208C9-0000-0000-C000-000000000046),
      helpcontext(0x00020089)
    ]
    dispinterface TickLabels {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x00000075), helpcontext(0x00010075)]
            void Delete();
            [id(0x00000092), propget, helpcontext(0x00010092)]
            Font* Font();
            [id(0x0000006e), propget, helpcontext(0x0001006e)]
            BSTR Name();
            [id(0x000000c1), propget, helpcontext(0x000100c1)]
            BSTR NumberFormat();
            [id(0x000000c1), propput, helpcontext(0x000100c1)]
            void NumberFormat([in] BSTR rhs);
            [id(0x000000c2), propget, helpcontext(0x000100c2)]
            VARIANT_BOOL NumberFormatLinked();
            [id(0x000000c2), propput, helpcontext(0x000100c2)]
            void NumberFormatLinked([in] VARIANT_BOOL rhs);
            [id(0x00000086), propget, helpcontext(0x00010086)]
            XlTickLabelOrientation Orientation();
            [id(0x00000086), propput, helpcontext(0x00010086)]
            void Orientation([in] XlTickLabelOrientation rhs);
            [id(0x000000eb), helpcontext(0x000100eb)]
            void Select();
            [id(0x000003cf), propget, helpcontext(0x000103cf)]
            long ReadingOrder();
            [id(0x000003cf), propput, helpcontext(0x000103cf)]
            void ReadingOrder([in] long rhs);
            [id(0x000005f5), propget, helpcontext(0x000105f5)]
            VARIANT AutoScaleFont();
            [id(0x000005f5), propput, helpcontext(0x000105f5)]
            void AutoScaleFont([in] VARIANT rhs);
    };

    [
      uuid(000208CB-0000-0000-C000-000000000046),
      helpcontext(0x0002008a)
    ]
    dispinterface PlotArea {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x0000006e), propget, helpcontext(0x0001006e)]
            BSTR Name();
            [id(0x000000eb), helpcontext(0x000100eb)]
            void Select();
            [id(0x00000080), propget, helpcontext(0x00010080)]
            Border* Border();
            [id(0x00000070), helpcontext(0x00010070)]
            void ClearFormats();
            [id(0x0000007b), propget, helpcontext(0x0001007b)]
            double Height();
            [id(0x0000007b), propput, helpcontext(0x0001007b)]
            void Height([in] double rhs);
            [id(0x00000081), propget, helpcontext(0x00010081)]
            Interior* Interior();
            [id(0x0000067f), propget, helpcontext(0x0001067f)]
            ChartFillFormat* Fill();
            [id(0x0000007f), propget, helpcontext(0x0001007f)]
            double Left();
            [id(0x0000007f), propput, helpcontext(0x0001007f)]
            void Left([in] double rhs);
            [id(0x0000007e), propget, helpcontext(0x0001007e)]
            double Top();
            [id(0x0000007e), propput, helpcontext(0x0001007e)]
            void Top([in] double rhs);
            [id(0x0000007a), propget, helpcontext(0x0001007a)]
            double Width();
            [id(0x0000007a), propput, helpcontext(0x0001007a)]
            void Width([in] double rhs);
            [id(0x00000683), propget, helpcontext(0x00010683)]
            double InsideLeft();
            [id(0x00000684), propget, helpcontext(0x00010684)]
            double InsideTop();
            [id(0x00000685), propget, helpcontext(0x00010685)]
            double InsideWidth();
            [id(0x00000686), propget, helpcontext(0x00010686)]
            double InsideHeight();
    };

    [
      uuid(000208CC-0000-0000-C000-000000000046),
      helpcontext(0x0002008b)
    ]
    dispinterface ChartArea {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x0000006e), propget, helpcontext(0x0001006e)]
            BSTR Name();
            [id(0x000000eb), helpcontext(0x000100eb)]
            void Select();
            [id(0x00000080), propget, helpcontext(0x00010080)]
            Border* Border();
            [id(0x0000006f), helpcontext(0x0001006f)]
            void Clear();
            [id(0x00000071), helpcontext(0x00010071)]
            void ClearContents();
            [id(0x00000227), helpcontext(0x00010227)]
            void Copy();
            [id(0x00000092), propget, helpcontext(0x00010092)]
            Font* Font();
            [id(0x00000067), propget, helpcontext(0x00010067)]
            VARIANT_BOOL Shadow();
            [id(0x00000067), propput, helpcontext(0x00010067)]
            void Shadow([in] VARIANT_BOOL rhs);
            [id(0x00000070), helpcontext(0x00010070)]
            void ClearFormats();
            [id(0x0000007b), propget, helpcontext(0x0001007b)]
            double Height();
            [id(0x0000007b), propput, helpcontext(0x0001007b)]
            void Height([in] double rhs);
            [id(0x00000081), propget, helpcontext(0x00010081)]
            Interior* Interior();
            [id(0x0000067f), propget, helpcontext(0x0001067f)]
            ChartFillFormat* Fill();
            [id(0x0000007f), propget, helpcontext(0x0001007f)]
            double Left();
            [id(0x0000007f), propput, helpcontext(0x0001007f)]
            void Left([in] double rhs);
            [id(0x0000007e), propget, helpcontext(0x0001007e)]
            double Top();
            [id(0x0000007e), propput, helpcontext(0x0001007e)]
            void Top([in] double rhs);
            [id(0x0000007a), propget, helpcontext(0x0001007a)]
            double Width();
            [id(0x0000007a), propput, helpcontext(0x0001007a)]
            void Width([in] double rhs);
            [id(0x000005f5), propget, helpcontext(0x000105f5)]
            VARIANT AutoScaleFont();
            [id(0x000005f5), propput, helpcontext(0x000105f5)]
            void AutoScaleFont([in] VARIANT rhs);
    };

    [
      uuid(000208CD-0000-0000-C000-000000000046),
      helpcontext(0x0002008c)
    ]
    dispinterface Legend {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x0000006e), propget, helpcontext(0x0001006e)]
            BSTR Name();
            [id(0x000000eb), helpcontext(0x000100eb)]
            void Select();
            [id(0x00000080), propget, helpcontext(0x00010080)]
            Border* Border();
            [id(0x00000075), helpcontext(0x00010075)]
            void Delete();
            [id(0x00000092), propget, helpcontext(0x00010092)]
            Font* Font();
            [id(0x000000ad), helpcontext(0x000100ad)]
            IDispatch* LegendEntries([in, optional] VARIANT Index);
            [id(0x00000085), propget, helpcontext(0x00010085)]
            XlLegendPosition Position();
            [id(0x00000085), propput, helpcontext(0x00010085)]
            void Position([in] XlLegendPosition rhs);
            [id(0x00000067), propget, helpcontext(0x00010067)]
            VARIANT_BOOL Shadow();
            [id(0x00000067), propput, helpcontext(0x00010067)]
            void Shadow([in] VARIANT_BOOL rhs);
            [id(0x0000006f), helpcontext(0x0001006f)]
            void Clear();
            [id(0x0000007b), propget, helpcontext(0x0001007b)]
            double Height();
            [id(0x0000007b), propput, helpcontext(0x0001007b)]
            void Height([in] double rhs);
            [id(0x00000081), propget, helpcontext(0x00010081)]
            Interior* Interior();
            [id(0x0000067f), propget, helpcontext(0x0001067f)]
            ChartFillFormat* Fill();
            [id(0x0000007f), propget, helpcontext(0x0001007f)]
            double Left();
            [id(0x0000007f), propput, helpcontext(0x0001007f)]
            void Left([in] double rhs);
            [id(0x0000007e), propget, helpcontext(0x0001007e)]
            double Top();
            [id(0x0000007e), propput, helpcontext(0x0001007e)]
            void Top([in] double rhs);
            [id(0x0000007a), propget, helpcontext(0x0001007a)]
            double Width();
            [id(0x0000007a), propput, helpcontext(0x0001007a)]
            void Width([in] double rhs);
            [id(0x000005f5), propget, helpcontext(0x000105f5)]
            VARIANT AutoScaleFont();
            [id(0x000005f5), propput, helpcontext(0x000105f5)]
            void AutoScaleFont([in] VARIANT rhs);
    };

    [
      uuid(000208CE-0000-0000-C000-000000000046),
      helpcontext(0x0002008d)
    ]
    dispinterface ErrorBars {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x0000006e), propget, helpcontext(0x0001006e)]
            BSTR Name();
            [id(0x000000eb), helpcontext(0x000100eb)]
            void Select();
            [id(0x00000080), propget, helpcontext(0x00010080)]
            Border* Border();
            [id(0x00000075), helpcontext(0x00010075)]
            void Delete();
            [id(0x00000070), helpcontext(0x00010070)]
            void ClearFormats();
            [id(0x00000464), propget, helpcontext(0x00010464)]
            XlEndStyleCap EndStyle();
            [id(0x00000464), propput, helpcontext(0x00010464)]
            void EndStyle([in] XlEndStyleCap rhs);
    };

    [
      uuid(00020843-0000-0000-C000-000000000046),
      helpcontext(0x00020003)
    ]
    dispinterface DataTable {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x000000ab), propget, helpcontext(0x000100ab)]
            VARIANT_BOOL ShowLegendKey();
            [id(0x000000ab), propput, helpcontext(0x000100ab)]
            void ShowLegendKey([in] VARIANT_BOOL rhs);
            [id(0x00000687), propget, helpcontext(0x00010687)]
            VARIANT_BOOL HasBorderHorizontal();
            [id(0x00000687), propput, helpcontext(0x00010687)]
            void HasBorderHorizontal([in] VARIANT_BOOL rhs);
            [id(0x00000688), propget, helpcontext(0x00010688)]
            VARIANT_BOOL HasBorderVertical();
            [id(0x00000688), propput, helpcontext(0x00010688)]
            void HasBorderVertical([in] VARIANT_BOOL rhs);
            [id(0x00000689), propget, helpcontext(0x00010689)]
            VARIANT_BOOL HasBorderOutline();
            [id(0x00000689), propput, helpcontext(0x00010689)]
            void HasBorderOutline([in] VARIANT_BOOL rhs);
            [id(0x00000080), propget, helpcontext(0x00010080)]
            Border* Border();
            [id(0x00000092), propget, helpcontext(0x00010092)]
            Font* Font();
            [id(0x000000eb), helpcontext(0x000100eb)]
            void Select();
            [id(0x00000075), helpcontext(0x00010075)]
            void Delete();
            [id(0x000005f5), propget, helpcontext(0x000105f5)]
            VARIANT AutoScaleFont();
            [id(0x000005f5), propput, helpcontext(0x000105f5)]
            void AutoScaleFont([in] VARIANT rhs);
    };

    [
      uuid(00024438-0000-0000-C000-000000000046),
      helpcontext(0x000200ce)
    ]
    dispinterface Phonetic {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x0000022e), propget, helpcontext(0x0001022e)]
            VARIANT_BOOL Visible();
            [id(0x0000022e), propput, helpcontext(0x0001022e)]
            void Visible([in] VARIANT_BOOL rhs);
            [id(0x0000068a), propget, helpcontext(0x0001068a)]
            long CharacterType();
            [id(0x0000068a), propput, helpcontext(0x0001068a)]
            void CharacterType([in] long rhs);
            [id(0x000001c5), propget, helpcontext(0x000101c5)]
            long Alignment();
            [id(0x000001c5), propput, helpcontext(0x000101c5)]
            void Alignment([in] long rhs);
            [id(0x00000092), propget, helpcontext(0x00010092)]
            Font* Font();
            [id(0x0000008a), propget, helpcontext(0x0001008a)]
            BSTR Text();
            [id(0x0000008a), propput, helpcontext(0x0001008a)]
            void Text([in] BSTR rhs);
    };

    [
      uuid(00024439-0000-0000-C000-000000000046),
      helpcontext(0x000200cf)
    ]
    dispinterface Shape {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x0000068b), helpcontext(0x0001068b)]
            void Apply();
            [id(0x00000075), helpcontext(0x00010075)]
            void Delete();
            [id(0x0000040f), helpcontext(0x0001040f)]
            Shape* Duplicate();
            [id(0x0000068c), helpcontext(0x0001068c)]
            void Flip([in] MsoFlipCmd FlipCmd);
            [id(0x0000068e), helpcontext(0x0001068e)]
            void IncrementLeft([in] single Increment);
            [id(0x00000690), helpcontext(0x00010690)]
            void IncrementRotation([in] single Increment);
            [id(0x00000691), helpcontext(0x00010691)]
            void IncrementTop([in] single Increment);
            [id(0x00000692), helpcontext(0x00010692)]
            void PickUp();
            [id(0x00000693), helpcontext(0x00010693)]
            void RerouteConnections();
            [id(0x00000694), helpcontext(0x00010694)]
            void ScaleHeight(
                            [in] single Factor, 
                            [in] MsoTriState RelativeToOriginalSize, 
                            [in, optional] VARIANT Scale);
            [id(0x00000698), helpcontext(0x00010698)]
            void ScaleWidth(
                            [in] single Factor, 
                            [in] MsoTriState RelativeToOriginalSize, 
                            [in, optional] VARIANT Scale);
            [id(0x000000eb), helpcontext(0x000100eb)]
            void Select([in, optional] VARIANT Replace);
            [id(0x00000699), helpcontext(0x00010699)]
            void SetShapesDefaultProperties();
            [id(0x000000f4), helpcontext(0x000100f4)]
            ShapeRange* Ungroup();
            [id(0x0000026e), helpcontext(0x0001026e)]
            void ZOrder([in] MsoZOrderCmd ZOrderCmd);
            [id(0x0000069b), propget, helpcontext(0x0001069b)]
            Adjustments* Adjustments();
            [id(0x0000069c), propget, helpcontext(0x0001069c)]
            TextFrame* TextFrame();
            [id(0x0000069d), propget, helpcontext(0x0001069d)]
            MsoAutoShapeType AutoShapeType();
            [id(0x0000069d), propput, helpcontext(0x0001069d)]
            void AutoShapeType([in] MsoAutoShapeType rhs);
            [id(0x0000069e), propget, helpcontext(0x0001069e)]
            CalloutFormat* Callout();
            [id(0x0000069f), propget, helpcontext(0x0001069f)]
            long ConnectionSiteCount();
            [id(0x000006a0), propget, helpcontext(0x000106a0)]
            MsoTriState Connector();
            [id(0x000006a1), propget, helpcontext(0x000106a1)]
            ConnectorFormat* ConnectorFormat();
            [id(0x0000067f), propget, helpcontext(0x0001067f)]
            FillFormat* Fill();
            [id(0x000006a2), propget, helpcontext(0x000106a2)]
            GroupShapes* GroupItems();
            [id(0x0000007b), propget, helpcontext(0x0001007b)]
            single Height();
            [id(0x0000007b), propput, helpcontext(0x0001007b)]
            void Height([in] single rhs);
            [id(0x000006a3), propget, helpcontext(0x000106a3)]
            MsoTriState HorizontalFlip();
            [id(0x0000007f), propget, helpcontext(0x0001007f)]
            single Left();
            [id(0x0000007f), propput, helpcontext(0x0001007f)]
            void Left([in] single rhs);
            [id(0x00000331), propget, helpcontext(0x00010331)]
            LineFormat* Line();
            [id(0x000006a4), propget, helpcontext(0x000106a4)]
            MsoTriState LockAspectRatio();
            [id(0x000006a4), propput, helpcontext(0x000106a4)]
            void LockAspectRatio([in] MsoTriState rhs);
            [id(0x0000006e), propget, helpcontext(0x0001006e)]
            BSTR Name();
            [id(0x0000006e), propput, helpcontext(0x0001006e)]
            void Name([in] BSTR rhs);
            [id(0x000006a5), propget, helpcontext(0x000106a5)]
            ShapeNodes* Nodes();
            [id(0x0000003b), propget, helpcontext(0x0001003b)]
            single Rotation();
            [id(0x0000003b), propput, helpcontext(0x0001003b)]
            void Rotation([in] single rhs);
            [id(0x0000065f), propget, helpcontext(0x0001065f)]
            PictureFormat* PictureFormat();
            [id(0x00000067), propget, helpcontext(0x00010067)]
            ShadowFormat* Shadow();
            [id(0x000006a6), propget, helpcontext(0x000106a6)]
            TextEffectFormat* TextEffect();
            [id(0x000006a7), propget, helpcontext(0x000106a7)]
            ThreeDFormat* ThreeD();
            [id(0x0000007e), propget, helpcontext(0x0001007e)]
            single Top();
            [id(0x0000007e), propput, helpcontext(0x0001007e)]
            void Top([in] single rhs);
            [id(0x0000006c), propget, helpcontext(0x0001006c)]
            MsoShapeType Type();
            [id(0x000006a8), propget, helpcontext(0x000106a8)]
            MsoTriState VerticalFlip();
            [id(0x0000026d), propget, helpcontext(0x0001026d)]
            VARIANT Vertices();
            [id(0x0000022e), propget, helpcontext(0x0001022e)]
            MsoTriState Visible();
            [id(0x0000022e), propput, helpcontext(0x0001022e)]
            void Visible([in] MsoTriState rhs);
            [id(0x0000007a), propget, helpcontext(0x0001007a)]
            single Width();
            [id(0x0000007a), propput, helpcontext(0x0001007a)]
            void Width([in] single rhs);
            [id(0x000006a9), propget, helpcontext(0x000106a9)]
            long ZOrderPosition();
            [id(0x000006aa), propget, helpcontext(0x000106aa)]
            Hyperlink* Hyperlink();
            [id(0x000006ab), propget, helpcontext(0x000106ab)]
            MsoBlackWhiteMode BlackWhiteMode();
            [id(0x000006ab), propput, helpcontext(0x000106ab)]
            void BlackWhiteMode([in] MsoBlackWhiteMode rhs);
            [id(0x000006ac), propget, hidden, helpcontext(0x000106ac)]
            IDispatch* DrawingObject();
            [id(0x00000254), propget, helpcontext(0x00010254)]
            BSTR OnAction();
            [id(0x00000254), propput, helpcontext(0x00010254)]
            void OnAction([in] BSTR rhs);
            [id(0x0000010d), propget, helpcontext(0x0001010d)]
            VARIANT_BOOL Locked();
            [id(0x0000010d), propput, helpcontext(0x0001010d)]
            void Locked([in] VARIANT_BOOL rhs);
            [id(0x0000026c), propget, helpcontext(0x0001026c)]
            Range* TopLeftCell();
            [id(0x00000267), propget, helpcontext(0x00010267)]
            Range* BottomRightCell();
            [id(0x00000269), propget, helpcontext(0x00010269)]
            XlPlacement Placement();
            [id(0x00000269), propput, helpcontext(0x00010269)]
            void Placement([in] XlPlacement rhs);
            [id(0x00000227), helpcontext(0x00010227)]
            void Copy();
            [id(0x00000235), helpcontext(0x00010235)]
            void Cut();
            [id(0x000000d5), helpcontext(0x000100d5)]
            void CopyPicture(
                            [in, optional] VARIANT Appearance, 
                            [in, optional] VARIANT Format);
            [id(0x000006ad), propget, helpcontext(0x000106ad)]
            ControlFormat* ControlFormat();
            [id(0x000006ae), propget, helpcontext(0x000106ae)]
            LinkFormat* LinkFormat();
            [id(0x000006af), propget, helpcontext(0x000106af)]
            OLEFormat* OLEFormat();
            [id(0x000006b0), propget, helpcontext(0x000106b0)]
            XlFormControl FormControlType();
    };
