import "Excel24.Idl";


    [
      uuid(000208B0-0000-0000-C000-000000000046),
      helpcontext(0x00020070),
      hidden
    ]
    dispinterface DialogSheets {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x000000b5), helpcontext(0x000100b5)]
            DialogSheet* Add(
                            [in, optional] VARIANT Before, 
                            [in, optional] VARIANT After, 
                            [in, optional] VARIANT Count);
            [id(0x00000227), helpcontext(0x00010227)]
            void Copy(
                            [in, optional] VARIANT Before, 
                            [in, optional] VARIANT After);
            [id(0x00000076), propget, helpcontext(0x00010076)]
            long Count();
            [id(0x00000075), helpcontext(0x00010075)]
            void Delete();
            [id(0x00010007), restricted, hidden]
            void _Dummy7();
            [id(0x000000aa), propget, helpcontext(0x000100aa)]
            IDispatch* Item([in] VARIANT Index);
            [id(0x0000027d), helpcontext(0x0001027d)]
            void Move(
                            [in, optional] VARIANT Before, 
                            [in, optional] VARIANT After);
            [id(0xfffffffc), propget, helpcontext(0x0000fffc)]
            IUnknown* _NewEnum();
            [id(0x00000389), helpcontext(0x00010389)]
            void PrintOut(
                            [in, optional] VARIANT From, 
                            [in, optional] VARIANT To, 
                            [in, optional] VARIANT Copies, 
                            [in, optional] VARIANT Preview, 
                            [in, optional] VARIANT ActivePrinter, 
                            [in, optional] VARIANT PrintToFile, 
                            [in, optional] VARIANT Collate);
            [id(0x00000119), helpcontext(0x00010119)]
            void PrintPreview([in, optional] VARIANT EnableChanges);
            [id(0x000000eb), helpcontext(0x000100eb)]
            void Select([in, optional] VARIANT Replace);
            [id(0x0000058a), propget, helpcontext(0x0001058a)]
            HPageBreaks* HPageBreaks();
            [id(0x0000058b), propget, helpcontext(0x0001058b)]
            VPageBreaks* VPageBreaks();
            [id(0x0000022e), propget, helpcontext(0x0001022e)]
            VARIANT Visible();
            [id(0x0000022e), propput, helpcontext(0x0001022e)]
            void Visible([in] VARIANT rhs);
            [id(00000000), propget, helpcontext(0x00010000)]
            IDispatch* _Default([in] VARIANT Index);
    };

    [
      uuid(000208B1-0000-0000-C000-000000000046),
      helpcontext(0x00020071)
    ]
    dispinterface Worksheets {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x000000b5), helpcontext(0x000100b5)]
            IDispatch* Add(
                            [in, optional] VARIANT Before, 
                            [in, optional] VARIANT After, 
                            [in, optional] VARIANT Count, 
                            [in, optional] VARIANT Type);
            [id(0x00000227), helpcontext(0x00010227)]
            void Copy(
                            [in, optional] VARIANT Before, 
                            [in, optional] VARIANT After);
            [id(0x00000076), propget, helpcontext(0x00010076)]
            long Count();
            [id(0x00000075), helpcontext(0x00010075)]
            void Delete();
            [id(0x000001d5), helpcontext(0x000101d5)]
            void FillAcrossSheets(
                            [in] Range* Range, 
                            [in, optional, defaultvalue(-4104)] XlFillWith Type);
            [id(0x000000aa), propget, helpcontext(0x000100aa)]
            IDispatch* Item([in] VARIANT Index);
            [id(0x0000027d), helpcontext(0x0001027d)]
            void Move(
                            [in, optional] VARIANT Before, 
                            [in, optional] VARIANT After);
            [id(0xfffffffc), propget, helpcontext(0x0000fffc)]
            IUnknown* _NewEnum();
            [id(0x00000389), helpcontext(0x00010389)]
            void PrintOut(
                            [in, optional] VARIANT From, 
                            [in, optional] VARIANT To, 
                            [in, optional] VARIANT Copies, 
                            [in, optional] VARIANT Preview, 
                            [in, optional] VARIANT ActivePrinter, 
                            [in, optional] VARIANT PrintToFile, 
                            [in, optional] VARIANT Collate);
            [id(0x00000119), helpcontext(0x00010119)]
            void PrintPreview([in, optional] VARIANT EnableChanges);
            [id(0x000000eb), helpcontext(0x000100eb)]
            void Select([in, optional] VARIANT Replace);
            [id(0x0000058a), propget, helpcontext(0x0001058a)]
            HPageBreaks* HPageBreaks();
            [id(0x0000058b), propget, helpcontext(0x0001058b)]
            VPageBreaks* VPageBreaks();
            [id(0x0000022e), propget, helpcontext(0x0001022e)]
            VARIANT Visible();
            [id(0x0000022e), propput, helpcontext(0x0001022e)]
            void Visible([in] VARIANT rhs);
            [id(00000000), propget, helpcontext(0x00010000)]
            IDispatch* _Default([in] VARIANT Index);
    };

    [
      uuid(000208B4-0000-0000-C000-000000000046),
      helpcontext(0x00020074)
    ]
    dispinterface PageSetup {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x000003f1), propget, helpcontext(0x000103f1)]
            VARIANT_BOOL BlackAndWhite();
            [id(0x000003f1), propput, helpcontext(0x000103f1)]
            void BlackAndWhite([in] VARIANT_BOOL rhs);
            [id(0x000003ea), propget, helpcontext(0x000103ea)]
            double BottomMargin();
            [id(0x000003ea), propput, helpcontext(0x000103ea)]
            void BottomMargin([in] double rhs);
            [id(0x000003f2), propget, helpcontext(0x000103f2)]
            BSTR CenterFooter();
            [id(0x000003f2), propput, helpcontext(0x000103f2)]
            void CenterFooter([in] BSTR rhs);
            [id(0x000003f3), propget, helpcontext(0x000103f3)]
            BSTR CenterHeader();
            [id(0x000003f3), propput, helpcontext(0x000103f3)]
            void CenterHeader([in] BSTR rhs);
            [id(0x000003ed), propget, helpcontext(0x000103ed)]
            VARIANT_BOOL CenterHorizontally();
            [id(0x000003ed), propput, helpcontext(0x000103ed)]
            void CenterHorizontally([in] VARIANT_BOOL rhs);
            [id(0x000003ee), propget, helpcontext(0x000103ee)]
            VARIANT_BOOL CenterVertically();
            [id(0x000003ee), propput, helpcontext(0x000103ee)]
            void CenterVertically([in] VARIANT_BOOL rhs);
            [id(0x000003f4), propget, helpcontext(0x000103f4)]
            XlObjectSize ChartSize();
            [id(0x000003f4), propput, helpcontext(0x000103f4)]
            void ChartSize([in] XlObjectSize rhs);
            [id(0x000003fc), propget, helpcontext(0x000103fc)]
            VARIANT_BOOL Draft();
            [id(0x000003fc), propput, helpcontext(0x000103fc)]
            void Draft([in] VARIANT_BOOL rhs);
            [id(0x000003f0), propget, helpcontext(0x000103f0)]
            long FirstPageNumber();
            [id(0x000003f0), propput, helpcontext(0x000103f0)]
            void FirstPageNumber([in] long rhs);
            [id(0x000003f5), propget, helpcontext(0x000103f5)]
            VARIANT FitToPagesTall();
            [id(0x000003f5), propput, helpcontext(0x000103f5)]
            void FitToPagesTall([in] VARIANT rhs);
            [id(0x000003f6), propget, helpcontext(0x000103f6)]
            VARIANT FitToPagesWide();
            [id(0x000003f6), propput, helpcontext(0x000103f6)]
            void FitToPagesWide([in] VARIANT rhs);
            [id(0x000003f7), propget, helpcontext(0x000103f7)]
            double FooterMargin();
            [id(0x000003f7), propput, helpcontext(0x000103f7)]
            void FooterMargin([in] double rhs);
            [id(0x000003f8), propget, helpcontext(0x000103f8)]
            double HeaderMargin();
            [id(0x000003f8), propput, helpcontext(0x000103f8)]
            void HeaderMargin([in] double rhs);
            [id(0x000003f9), propget, helpcontext(0x000103f9)]
            BSTR LeftFooter();
            [id(0x000003f9), propput, helpcontext(0x000103f9)]
            void LeftFooter([in] BSTR rhs);
            [id(0x000003fa), propget, helpcontext(0x000103fa)]
            BSTR LeftHeader();
            [id(0x000003fa), propput, helpcontext(0x000103fa)]
            void LeftHeader([in] BSTR rhs);
            [id(0x000003e7), propget, helpcontext(0x000103e7)]
            double LeftMargin();
            [id(0x000003e7), propput, helpcontext(0x000103e7)]
            void LeftMargin([in] double rhs);
            [id(0x000000c0), propget, helpcontext(0x000100c0)]
            XlOrder Order();
            [id(0x000000c0), propput, helpcontext(0x000100c0)]
            void Order([in] XlOrder rhs);
            [id(0x00000086), propget, helpcontext(0x00010086)]
            XlPageOrientation Orientation();
            [id(0x00000086), propput, helpcontext(0x00010086)]
            void Orientation([in] XlPageOrientation rhs);
            [id(0x000003ef), propget, helpcontext(0x000103ef)]
            XlPaperSize PaperSize();
            [id(0x000003ef), propput, helpcontext(0x000103ef)]
            void PaperSize([in] XlPaperSize rhs);
            [id(0x000003fb), propget, helpcontext(0x000103fb)]
            BSTR PrintArea();
            [id(0x000003fb), propput, helpcontext(0x000103fb)]
            void PrintArea([in] BSTR rhs);
            [id(0x000003ec), propget, helpcontext(0x000103ec)]
            VARIANT_BOOL PrintGridlines();
            [id(0x000003ec), propput, helpcontext(0x000103ec)]
            void PrintGridlines([in] VARIANT_BOOL rhs);
            [id(0x000003eb), propget, helpcontext(0x000103eb)]
            VARIANT_BOOL PrintHeadings();
            [id(0x000003eb), propput, helpcontext(0x000103eb)]
            void PrintHeadings([in] VARIANT_BOOL rhs);
            [id(0x000003fd), propget, helpcontext(0x000103fd)]
            VARIANT_BOOL PrintNotes();
            [id(0x000003fd), propput, helpcontext(0x000103fd)]
            void PrintNotes([in] VARIANT_BOOL rhs);
            [id(0x000003fe), helpcontext(0x000103fe)]
            VARIANT PrintQuality([in, optional] VARIANT Index);
            [id(0x000003ff), propget, helpcontext(0x000103ff)]
            BSTR PrintTitleColumns();
            [id(0x000003ff), propput, helpcontext(0x000103ff)]
            void PrintTitleColumns([in] BSTR rhs);
            [id(0x00000400), propget, helpcontext(0x00010400)]
            BSTR PrintTitleRows();
            [id(0x00000400), propput, helpcontext(0x00010400)]
            void PrintTitleRows([in] BSTR rhs);
            [id(0x00000401), propget, helpcontext(0x00010401)]
            BSTR RightFooter();
            [id(0x00000401), propput, helpcontext(0x00010401)]
            void RightFooter([in] BSTR rhs);
            [id(0x00000402), propget, helpcontext(0x00010402)]
            BSTR RightHeader();
            [id(0x00000402), propput, helpcontext(0x00010402)]
            void RightHeader([in] BSTR rhs);
            [id(0x000003e8), propget, helpcontext(0x000103e8)]
            double RightMargin();
            [id(0x000003e8), propput, helpcontext(0x000103e8)]
            void RightMargin([in] double rhs);
            [id(0x000003e9), propget, helpcontext(0x000103e9)]
            double TopMargin();
            [id(0x000003e9), propput, helpcontext(0x000103e9)]
            void TopMargin([in] double rhs);
            [id(0x00000297), propget, helpcontext(0x00010297)]
            VARIANT Zoom();
            [id(0x00000297), propput, helpcontext(0x00010297)]
            void Zoom([in] VARIANT rhs);
            [id(0x000005f4), propget, helpcontext(0x000105f4)]
            XlPrintLocation PrintComments();
            [id(0x000005f4), propput, helpcontext(0x000105f4)]
            void PrintComments([in] XlPrintLocation rhs);
    };

    [
      uuid(000208B8-0000-0000-C000-000000000046),
      helpcontext(0x00020078)
    ]
    dispinterface Names {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x000000b5), helpcontext(0x000100b5)]
            Name* Add(
                            [in, optional] VARIANT Name, 
                            [in, optional] VARIANT RefersTo, 
                            [in, optional] VARIANT Visible, 
                            [in, optional] VARIANT MacroType, 
                            [in, optional] VARIANT ShortcutKey, 
                            [in, optional] VARIANT Category, 
                            [in, optional] VARIANT NameLocal, 
                            [in, optional] VARIANT RefersToLocal, 
                            [in, optional] VARIANT CategoryLocal, 
                            [in, optional] VARIANT RefersToR1C1, 
                            [in, optional] VARIANT RefersToR1C1Local);
            [id(0x000000aa), helpcontext(0x000100aa)]
            Name* Item(
                            [in, optional] VARIANT Index, 
                            [in, optional] VARIANT IndexLocal, 
                            [in, optional] VARIANT RefersTo);
            [id(00000000), helpcontext(0x00010000)]
            Name* _Default(
                            [in, optional] VARIANT Index, 
                            [in, optional] VARIANT IndexLocal, 
                            [in, optional] VARIANT RefersTo);
            [id(0x00000076), propget, helpcontext(0x00010076)]
            long Count();
            [id(0xfffffffc), propget, helpcontext(0x0000fffc)]
            IUnknown* _NewEnum();
    };

    [
      uuid(000208B9-0000-0000-C000-000000000046),
      helpcontext(0x00020079)
    ]
    dispinterface Name {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(00000000), propget, helpcontext(0x00010000)]
            BSTR _Default();
            [id(0x000001e6), propget, helpcontext(0x000101e6)]
            long Index();
            [id(0x000003a6), propget, helpcontext(0x000103a6)]
            BSTR Category();
            [id(0x000003a6), propput, helpcontext(0x000103a6)]
            void Category([in] BSTR rhs);
            [id(0x000003a7), propget, helpcontext(0x000103a7)]
            BSTR CategoryLocal();
            [id(0x000003a7), propput, helpcontext(0x000103a7)]
            void CategoryLocal([in] BSTR rhs);
            [id(0x00000075), helpcontext(0x00010075)]
            void Delete();
            [id(0x000003a8), propget, helpcontext(0x000103a8)]
            XlXLMMacroType MacroType();
            [id(0x000003a8), propput, helpcontext(0x000103a8)]
            void MacroType([in] XlXLMMacroType rhs);
            [id(0x0000006e), propget, helpcontext(0x0001006e)]
            BSTR Name();
            [id(0x0000006e), propput, helpcontext(0x0001006e)]
            void Name([in] BSTR rhs);
            [id(0x000003aa), propget, helpcontext(0x000103aa)]
            VARIANT RefersTo();
            [id(0x000003aa), propput, helpcontext(0x000103aa)]
            void RefersTo([in] VARIANT rhs);
            [id(0x00000255), propget, helpcontext(0x00010255)]
            BSTR ShortcutKey();
            [id(0x00000255), propput, helpcontext(0x00010255)]
            void ShortcutKey([in] BSTR rhs);
            [id(0x00000006), propget, helpcontext(0x00010006)]
            BSTR Value();
            [id(0x00000006), propput, helpcontext(0x00010006)]
            void Value([in] BSTR rhs);
            [id(0x0000022e), propget, helpcontext(0x0001022e)]
            VARIANT_BOOL Visible();
            [id(0x0000022e), propput, helpcontext(0x0001022e)]
            void Visible([in] VARIANT_BOOL rhs);
            [id(0x000003a9), propget, helpcontext(0x000103a9)]
            BSTR NameLocal();
            [id(0x000003a9), propput, helpcontext(0x000103a9)]
            void NameLocal([in] BSTR rhs);
            [id(0x000003ab), propget, helpcontext(0x000103ab)]
            VARIANT RefersToLocal();
            [id(0x000003ab), propput, helpcontext(0x000103ab)]
            void RefersToLocal([in] VARIANT rhs);
            [id(0x000003ac), propget, helpcontext(0x000103ac)]
            VARIANT RefersToR1C1();
            [id(0x000003ac), propput, helpcontext(0x000103ac)]
            void RefersToR1C1([in] VARIANT rhs);
            [id(0x000003ad), propget, helpcontext(0x000103ad)]
            VARIANT RefersToR1C1Local();
            [id(0x000003ad), propput, helpcontext(0x000103ad)]
            void RefersToR1C1Local([in] VARIANT rhs);
            [id(0x00000488), propget, helpcontext(0x00010488)]
            Range* RefersToRange();
    };

    [
      uuid(000208CF-0000-0000-C000-000000000046),
      helpcontext(0x0002008e)
    ]
    dispinterface ChartObject {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x00000267), propget, helpcontext(0x00010267)]
            Range* BottomRightCell();
            [id(0x0000025a), helpcontext(0x0001025a)]
            void BringToFront();
            [id(0x00000227), helpcontext(0x00010227)]
            void Copy();
            [id(0x000000d5), helpcontext(0x000100d5)]
            void CopyPicture(
                            [in, optional, defaultvalue(2)] XlPictureAppearance Appearance, 
                            [in, optional, defaultvalue(-4147)] XlCopyPictureFormat Format);
            [id(0x00000235), helpcontext(0x00010235)]
            void Cut();
            [id(0x00000075), helpcontext(0x00010075)]
            void Delete();
            [id(0x0000040f), helpcontext(0x0001040f)]
            IDispatch* Duplicate();
            [id(0x00000258), propget, helpcontext(0x00010258)]
            VARIANT_BOOL Enabled();
            [id(0x00000258), propput, helpcontext(0x00010258)]
            void Enabled([in] VARIANT_BOOL rhs);
            [id(0x0000007b), propget, helpcontext(0x0001007b)]
            double Height();
            [id(0x0000007b), propput, helpcontext(0x0001007b)]
            void Height([in] double rhs);
            [id(0x000001e6), propget, helpcontext(0x000101e6)]
            long Index();
            [id(0x0000007f), propget, helpcontext(0x0001007f)]
            double Left();
            [id(0x0000007f), propput, helpcontext(0x0001007f)]
            void Left([in] double rhs);
            [id(0x0000010d), propget, helpcontext(0x0001010d)]
            VARIANT_BOOL Locked();
            [id(0x0000010d), propput, helpcontext(0x0001010d)]
            void Locked([in] VARIANT_BOOL rhs);
            [id(0x0000006e), propget, helpcontext(0x0001006e)]
            BSTR Name();
            [id(0x0000006e), propput, helpcontext(0x0001006e)]
            void Name([in] BSTR rhs);
            [id(0x00000254), propget, hidden, helpcontext(0x00010254)]
            BSTR OnAction();
            [id(0x00000254), propput, hidden, helpcontext(0x00010254)]
            void OnAction([in] BSTR rhs);
            [id(0x00000269), propget, helpcontext(0x00010269)]
            VARIANT Placement();
            [id(0x00000269), propput, helpcontext(0x00010269)]
            void Placement([in] VARIANT rhs);
            [id(0x0000026a), propget, helpcontext(0x0001026a)]
            VARIANT_BOOL PrintObject();
            [id(0x0000026a), propput, helpcontext(0x0001026a)]
            void PrintObject([in] VARIANT_BOOL rhs);
            [id(0x000000eb), helpcontext(0x000100eb)]
            void Select([in, optional] VARIANT Replace);
            [id(0x0000025d), helpcontext(0x0001025d)]
            void SendToBack();
            [id(0x0000007e), propget, helpcontext(0x0001007e)]
            double Top();
            [id(0x0000007e), propput, helpcontext(0x0001007e)]
            void Top([in] double rhs);
            [id(0x0000026c), propget, helpcontext(0x0001026c)]
            Range* TopLeftCell();
            [id(0x0000022e), propget, helpcontext(0x0001022e)]
            VARIANT_BOOL Visible();
            [id(0x0000022e), propput, helpcontext(0x0001022e)]
            void Visible([in] VARIANT_BOOL rhs);
            [id(0x0000007a), propget, helpcontext(0x0001007a)]
            double Width();
            [id(0x0000007a), propput, helpcontext(0x0001007a)]
            void Width([in] double rhs);
            [id(0x0000026e), propget, helpcontext(0x0001026e)]
            long ZOrder();
            [id(0x000005f8), propget, helpcontext(0x000105f8)]
            ShapeRange* ShapeRange();
            [id(0x00000130), helpcontext(0x00010130)]
            void Activate();
            [id(0x00000007), propget, helpcontext(0x00010007)]
            Chart* Chart();
            [id(0x000005f9), propget, helpcontext(0x000105f9)]
            VARIANT_BOOL ProtectChartObject();
            [id(0x000005f9), propput, helpcontext(0x000105f9)]
            void ProtectChartObject([in] VARIANT_BOOL rhs);
            [id(0x0000026b), propget, helpcontext(0x0001026b)]
            VARIANT_BOOL RoundedCorners();
            [id(0x0000026b), propput, helpcontext(0x0001026b)]
            void RoundedCorners([in] VARIANT_BOOL rhs);
            [id(0x00000080), propget, helpcontext(0x00010080)]
            Border* Border();
            [id(0x00000081), propget, helpcontext(0x00010081)]
            Interior* Interior();
            [id(0x00000067), propget, helpcontext(0x00010067)]
            VARIANT_BOOL Shadow();
            [id(0x00000067), propput, helpcontext(0x00010067)]
            void Shadow([in] VARIANT_BOOL rhs);
    };

    [
      uuid(000208D0-0000-0000-C000-000000000046),
      helpcontext(0x0002008f)
    ]
    dispinterface ChartObjects {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x00010003), restricted, hidden]
            void _Dummy3();
            [id(0x0000025a), helpcontext(0x0001025a)]
            void BringToFront();
            [id(0x00000227), helpcontext(0x00010227)]
            void Copy();
            [id(0x000000d5), helpcontext(0x000100d5)]
            void CopyPicture(
                            [in, optional, defaultvalue(2)] XlPictureAppearance Appearance, 
                            [in, optional, defaultvalue(-4147)] XlCopyPictureFormat Format);
            [id(0x00000235), helpcontext(0x00010235)]
            void Cut();
            [id(0x00000075), helpcontext(0x00010075)]
            void Delete();
            [id(0x0000040f), helpcontext(0x0001040f)]
            IDispatch* Duplicate();
            [id(0x00000258), propget, helpcontext(0x00010258)]
            VARIANT_BOOL Enabled();
            [id(0x00000258), propput, helpcontext(0x00010258)]
            void Enabled([in] VARIANT_BOOL rhs);
            [id(0x0000007b), propget, helpcontext(0x0001007b)]
            double Height();
            [id(0x0000007b), propput, helpcontext(0x0001007b)]
            void Height([in] double rhs);
            [id(0x0001000c), restricted, hidden]
            void _Dummy12();
            [id(0x0000007f), propget, helpcontext(0x0001007f)]
            double Left();
            [id(0x0000007f), propput, helpcontext(0x0001007f)]
            void Left([in] double rhs);
            [id(0x0000010d), propget, helpcontext(0x0001010d)]
            VARIANT_BOOL Locked();
            [id(0x0000010d), propput, helpcontext(0x0001010d)]
            void Locked([in] VARIANT_BOOL rhs);
            [id(0x0001000f), restricted, hidden]
            void _Dummy15();
            [id(0x00000254), propget, hidden, helpcontext(0x00010254)]
            BSTR OnAction();
            [id(0x00000254), propput, hidden, helpcontext(0x00010254)]
            void OnAction([in] BSTR rhs);
            [id(0x00000269), propget, helpcontext(0x00010269)]
            VARIANT Placement();
            [id(0x00000269), propput, helpcontext(0x00010269)]
            void Placement([in] VARIANT rhs);
            [id(0x0000026a), propget, helpcontext(0x0001026a)]
            VARIANT_BOOL PrintObject();
            [id(0x0000026a), propput, helpcontext(0x0001026a)]
            void PrintObject([in] VARIANT_BOOL rhs);
            [id(0x000000eb), helpcontext(0x000100eb)]
            void Select([in, optional] VARIANT Replace);
            [id(0x0000025d), helpcontext(0x0001025d)]
            void SendToBack();
            [id(0x0000007e), propget, helpcontext(0x0001007e)]
            double Top();
            [id(0x0000007e), propput, helpcontext(0x0001007e)]
            void Top([in] double rhs);
            [id(0x00010016), restricted, hidden]
            void _Dummy22();
            [id(0x0000022e), propget, helpcontext(0x0001022e)]
            VARIANT_BOOL Visible();
            [id(0x0000022e), propput, helpcontext(0x0001022e)]
            void Visible([in] VARIANT_BOOL rhs);
            [id(0x0000007a), propget, helpcontext(0x0001007a)]
            double Width();
            [id(0x0000007a), propput, helpcontext(0x0001007a)]
            void Width([in] double rhs);
            [id(0x00010019), restricted, hidden]
            void _Dummy25();
            [id(0x000005f8), propget, helpcontext(0x000105f8)]
            ShapeRange* ShapeRange();
            [id(0x0001001b), restricted, hidden]
            void _Dummy27();
            [id(0x0001001c), restricted, hidden]
            void _Dummy28();
            [id(0x0001001d), restricted, hidden]
            void _Dummy29();
            [id(0x0000026b), propget, helpcontext(0x0001026b)]
            VARIANT_BOOL RoundedCorners();
            [id(0x0000026b), propput, helpcontext(0x0001026b)]
            void RoundedCorners([in] VARIANT_BOOL rhs);
            [id(0x00000080), propget, helpcontext(0x00010080)]
            Border* Border();
            [id(0x00000081), propget, helpcontext(0x00010081)]
            Interior* Interior();
            [id(0x00000067), propget, helpcontext(0x00010067)]
            VARIANT_BOOL Shadow();
            [id(0x00000067), propput, helpcontext(0x00010067)]
            void Shadow([in] VARIANT_BOOL rhs);
            [id(0x000000b5), helpcontext(0x000100b5)]
            ChartObject* Add(
                            [in] double Left, 
                            [in] double Top, 
                            [in] double Width, 
                            [in] double Height);
            [id(0x00000076), propget, helpcontext(0x00010076)]
            long Count();
            [id(0x0000002e), hidden, helpcontext(0x0001002e)]
            GroupObject* Group();
            [id(0x000000aa), helpcontext(0x000100aa)]
            IDispatch* Item([in] VARIANT Index);
            [id(0xfffffffc), helpcontext(0x0000fffc)]
            IUnknown* _NewEnum();
    };

    [
      uuid(000208D1-0000-0000-C000-000000000046),
      helpcontext(0x00020090)
    ]
    dispinterface Mailer {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x000003d7), propget, helpcontext(0x000103d7)]
            VARIANT BCCRecipients();
            [id(0x000003d7), propput, helpcontext(0x000103d7)]
            void BCCRecipients([in] VARIANT rhs);
            [id(0x000003d6), propget, helpcontext(0x000103d6)]
            VARIANT CCRecipients();
            [id(0x000003d6), propput, helpcontext(0x000103d6)]
            void CCRecipients([in] VARIANT rhs);
            [id(0x000003d8), propget, helpcontext(0x000103d8)]
            VARIANT Enclosures();
            [id(0x000003d8), propput, helpcontext(0x000103d8)]
            void Enclosures([in] VARIANT rhs);
            [id(0x000003da), propget, helpcontext(0x000103da)]
            VARIANT_BOOL Received();
            [id(0x000003db), propget, helpcontext(0x000103db)]
            DATE SendDateTime();
            [id(0x000003dc), propget, helpcontext(0x000103dc)]
            BSTR Sender();
            [id(0x000003b9), propget, helpcontext(0x000103b9)]
            BSTR Subject();
            [id(0x000003b9), propput, helpcontext(0x000103b9)]
            void Subject([in] BSTR rhs);
            [id(0x000003d5), propget, helpcontext(0x000103d5)]
            VARIANT ToRecipients();
            [id(0x000003d5), propput, helpcontext(0x000103d5)]
            void ToRecipients([in] VARIANT rhs);
            [id(0x000003ce), propget, helpcontext(0x000103ce)]
            VARIANT WhichAddress();
            [id(0x000003ce), propput, helpcontext(0x000103ce)]
            void WhichAddress([in] VARIANT rhs);
    };

    [
      uuid(00024422-0000-0000-C000-000000000046),
      helpcontext(0x000200b8)
    ]
    dispinterface CustomViews {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x00000076), propget, helpcontext(0x00010076)]
            long Count();
            [id(0x000000aa), helpcontext(0x000100aa)]
            CustomView* Item([in] VARIANT ViewName);
            [id(0x000000b5), helpcontext(0x000100b5)]
            CustomView* Add(
                            [in] BSTR ViewName, 
                            [in, optional] VARIANT PrintSettings, 
                            [in, optional] VARIANT RowColSettings);
            [id(00000000), propget, helpcontext(0x00010000)]
            CustomView* _Default([in] VARIANT ViewName);
            [id(0xfffffffc), propget, helpcontext(0x0000fffc)]
            IUnknown* _NewEnum();
    };

    [
      uuid(00024423-0000-0000-C000-000000000046),
      helpcontext(0x000200b9)
    ]
    dispinterface CustomView {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x0000006e), propget, helpcontext(0x0001006e)]
            BSTR Name();
            [id(0x00000629), propget, helpcontext(0x00010629)]
            VARIANT_BOOL PrintSettings();
            [id(0x0000062a), propget, helpcontext(0x0001062a)]
            VARIANT_BOOL RowColSettings();
            [id(0x000001f0), helpcontext(0x000101f0)]
            void Show();
            [id(0x00000075), helpcontext(0x00010075)]
            void Delete();
    };

    [
      uuid(00024424-0000-0000-C000-000000000046),
      helpcontext(0x000200ba)
    ]
    dispinterface FormatConditions {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x00000076), propget, helpcontext(0x00010076)]
            long Count();
            [id(0x000000aa), helpcontext(0x000100aa)]
            FormatCondition* Item([in] VARIANT Index);
            [id(0x000000b5), helpcontext(0x000100b5)]
            FormatCondition* Add(
                            [in] XlFormatConditionType Type, 
                            [in, optional] VARIANT Operator, 
                            [in, optional] VARIANT Formula1, 
                            [in, optional] VARIANT Formula2);
            [id(00000000), propget, helpcontext(0x00010000)]
            FormatCondition* _Default([in] VARIANT Index);
            [id(0xfffffffc), propget, helpcontext(0x0000fffc)]
            IUnknown* _NewEnum();
            [id(0x00000075), helpcontext(0x00010075)]
            void Delete();
    };

    [
      uuid(00024425-0000-0000-C000-000000000046),
      helpcontext(0x000200bb)
    ]
    dispinterface FormatCondition {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x0000062d), helpcontext(0x0001062d)]
            void Modify(
                            [in] XlFormatConditionType Type, 
                            [in, optional] VARIANT Operator, 
                            [in, optional] VARIANT Formula1, 
                            [in, optional] VARIANT Formula2);
            [id(0x0000006c), propget, helpcontext(0x0001006c)]
            long Type();
            [id(0x0000031d), propget, helpcontext(0x0001031d)]
            long Operator();
            [id(0x0000062b), propget, helpcontext(0x0001062b)]
            BSTR Formula1();
            [id(0x0000062c), propget, helpcontext(0x0001062c)]
            BSTR Formula2();
            [id(0x00000081), propget, helpcontext(0x00010081)]
            Interior* Interior();
            [id(0x000001b3), propget, helpcontext(0x000101b3)]
            Borders* Borders();
            [id(0x00000092), propget, helpcontext(0x00010092)]
            Font* Font();
            [id(0x00000075), helpcontext(0x00010075)]
            void Delete();
    };

    [
      uuid(00024426-0000-0000-C000-000000000046),
      helpcontext(0x000200bc)
    ]
    dispinterface Comments {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x00000076), propget, helpcontext(0x00010076)]
            long Count();
            [id(0x000000aa), helpcontext(0x000100aa)]
            Comment* Item([in] long Index);
            [id(00000000), propget, helpcontext(0x00010000)]
            Comment* _Default([in] long Index);
            [id(0xfffffffc), propget, helpcontext(0x0000fffc)]
            IUnknown* _NewEnum();
    };

    [
      uuid(00024427-0000-0000-C000-000000000046),
      helpcontext(0x000200bd)
    ]
    dispinterface Comment {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x0000023e), propget, helpcontext(0x0001023e)]
            BSTR Author();
            [id(0x0000062e), propget, helpcontext(0x0001062e)]
            Shape* Shape();
            [id(0x0000022e), propget, helpcontext(0x0001022e)]
            VARIANT_BOOL Visible();
            [id(0x0000022e), propput, helpcontext(0x0001022e)]
            void Visible([in] VARIANT_BOOL rhs);
            [id(0x0000008a), helpcontext(0x0001008a)]
            BSTR Text(
                            [in, optional] VARIANT Text, 
                            [in, optional] VARIANT Start, 
                            [in, optional] VARIANT Overwrite);
            [id(0x00000075), helpcontext(0x00010075)]
            void Delete();
            [id(0x000001f6), helpcontext(0x000101f6)]
            Comment* Next();
            [id(0x000001f7), helpcontext(0x000101f7)]
            Comment* Previous();
    };

    [
      uuid(0002441B-0000-0000-C000-000000000046),
      helpcontext(0x000200b1),
      hidden
    ]
    dispinterface RefreshEvents {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x0000063c), helpcontext(0x0001063c)]
            void BeforeRefresh([in] VARIANT_BOOL* Cancel);
            [id(0x0000063d), helpcontext(0x0001063d)]
            void AfterRefresh([in] VARIANT_BOOL Success);
    };

    [
      uuid(00024428-0000-0000-C000-000000000046),
      helpcontext(0x000200be)
    ]
    dispinterface _QueryTable {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x0000006e), propget, helpcontext(0x0001006e)]
            BSTR Name();
            [id(0x0000006e), propput, helpcontext(0x0001006e)]
            void Name([in] BSTR rhs);
            [id(0x00000630), propget, helpcontext(0x00010630)]
            VARIANT_BOOL FieldNames();
            [id(0x00000630), propput, helpcontext(0x00010630)]
            void FieldNames([in] VARIANT_BOOL rhs);
            [id(0x00000631), propget, helpcontext(0x00010631)]
            VARIANT_BOOL RowNumbers();
            [id(0x00000631), propput, helpcontext(0x00010631)]
            void RowNumbers([in] VARIANT_BOOL rhs);
            [id(0x00000632), propget, helpcontext(0x00010632)]
            VARIANT_BOOL FillAdjacentFormulas();
            [id(0x00000632), propput, helpcontext(0x00010632)]
            void FillAdjacentFormulas([in] VARIANT_BOOL rhs);
            [id(0x000002b7), propget, helpcontext(0x000102b7)]
            VARIANT_BOOL HasAutoFormat();
            [id(0x000002b7), propput, helpcontext(0x000102b7)]
            void HasAutoFormat([in] VARIANT_BOOL rhs);
            [id(0x000005c7), propget, helpcontext(0x000105c7)]
            VARIANT_BOOL RefreshOnFileOpen();
            [id(0x000005c7), propput, helpcontext(0x000105c7)]
            void RefreshOnFileOpen([in] VARIANT_BOOL rhs);
            [id(0x00000633), propget, helpcontext(0x00010633)]
            VARIANT_BOOL Refreshing();
            [id(0x00000634), propget, helpcontext(0x00010634)]
            VARIANT_BOOL FetchedRowOverflow();
            [id(0x00000593), propget, helpcontext(0x00010593)]
            VARIANT_BOOL BackgroundQuery();
            [id(0x00000593), propput, helpcontext(0x00010593)]
            void BackgroundQuery([in] VARIANT_BOOL rhs);
            [id(0x00000635), helpcontext(0x00010635)]
            void CancelRefresh();
            [id(0x00000636), propget, helpcontext(0x00010636)]
            XlCellInsertionMode RefreshStyle();
            [id(0x00000636), propput, helpcontext(0x00010636)]
            void RefreshStyle([in] XlCellInsertionMode rhs);
            [id(0x000005c5), propget, helpcontext(0x000105c5)]
            VARIANT_BOOL EnableRefresh();
            [id(0x000005c5), propput, helpcontext(0x000105c5)]
            void EnableRefresh([in] VARIANT_BOOL rhs);
            [id(0x000005c9), propget, helpcontext(0x000105c9)]
            VARIANT_BOOL SavePassword();
            [id(0x000005c9), propput, helpcontext(0x000105c9)]
            void SavePassword([in] VARIANT_BOOL rhs);
            [id(0x000002a9), propget, helpcontext(0x000102a9)]
            Range* Destination();
            [id(0x00000598), propget, helpcontext(0x00010598)]
            VARIANT Connection();
            [id(0x00000598), propput, helpcontext(0x00010598)]
            void Connection([in] VARIANT rhs);
            [id(0x000005c8), propget, helpcontext(0x000105c8)]
            VARIANT Sql();
            [id(0x000005c8), propput, helpcontext(0x000105c8)]
            void Sql([in] VARIANT rhs);
            [id(0x00000637), propget, helpcontext(0x00010637)]
            BSTR PostText();
            [id(0x00000637), propput, helpcontext(0x00010637)]
            void PostText([in] BSTR rhs);
            [id(0x00000638), propget, helpcontext(0x00010638)]
            Range* ResultRange();
            [id(0x00000075), helpcontext(0x00010075)]
            void Delete();
            [id(0x00000589), helpcontext(0x00010589)]
            VARIANT_BOOL Refresh([in, optional] VARIANT BackgroundQuery);
            [id(0x00000639), propget, helpcontext(0x00010639)]
            Parameters* Parameters();
            [id(0x0000048d), propget, helpcontext(0x0001048d)]
            IDispatch* Recordset();
            [id(0x0000048d), propputref, helpcontext(0x0001048d)]
            void Recordset([in] IDispatch* rhs);
            [id(0x000002b4), propget, helpcontext(0x000102b4)]
            VARIANT_BOOL SaveData();
            [id(0x000002b4), propput, helpcontext(0x000102b4)]
            void SaveData([in] VARIANT_BOOL rhs);
            [id(0x0000063a), propget, helpcontext(0x0001063a)]
            VARIANT_BOOL TablesOnlyFromHTML();
            [id(0x0000063a), propput, helpcontext(0x0001063a)]
            void TablesOnlyFromHTML([in] VARIANT_BOOL rhs);
            [id(0x0000063b), propget, helpcontext(0x0001063b)]
            VARIANT_BOOL EnableEditing();
            [id(0x0000063b), propput, helpcontext(0x0001063b)]
            void EnableEditing([in] VARIANT_BOOL rhs);
    };

    [
      uuid(00024429-0000-0000-C000-000000000046),
      helpcontext(0x000200bf)
    ]
    dispinterface QueryTables {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x00000076), propget, helpcontext(0x00010076)]
            long Count();
            [id(0x000000b5), helpcontext(0x000100b5)]
            QueryTable* Add(
                            [in] VARIANT Connection, 
                            [in] Range* Destination, 
                            [in, optional] VARIANT Sql);
            [id(0x000000aa), helpcontext(0x000100aa)]
            QueryTable* Item([in] VARIANT Index);
            [id(00000000), propget, helpcontext(0x00010000)]
            QueryTable* _Default([in] VARIANT Index);
            [id(0xfffffffc), helpcontext(0x0000fffc)]
            IUnknown* _NewEnum();
    };

