import "Excel13.Idl";


    [
      odl,
      uuid(0002085A-0001-0000-C000-000000000046),
      helpcontext(0x0002001a),
      hidden
    ]
    interface IChartGroups : IDispatch {
        [propget, helpcontext(0x00010094)]
        HRESULT _stdcall Application([out, retval] Application** RHS);
        [propget, helpcontext(0x00010095)]
        HRESULT _stdcall Creator([out, retval] XlCreator* RHS);
        [propget, helpcontext(0x00010096)]
        HRESULT _stdcall Parent([out, retval] IDispatch** RHS);
        [propget, helpcontext(0x00010076)]
        HRESULT _stdcall Count([out, retval] long* RHS);
        [helpcontext(0x000100aa)]
        HRESULT _stdcall Item(
                        [in] VARIANT Index, 
                        [out, retval] ChartGroup** RHS);
        [helpcontext(0x0000fffc)]
        HRESULT _stdcall _NewEnum([out, retval] IUnknown** RHS);
    };

    [
      odl,
      uuid(0002085B-0001-0000-C000-000000000046),
      helpcontext(0x0002001b),
      hidden
    ]
    interface IAxes : IDispatch {
        [propget, helpcontext(0x00010094)]
        HRESULT _stdcall Application([out, retval] Application** RHS);
        [propget, helpcontext(0x00010095)]
        HRESULT _stdcall Creator([out, retval] XlCreator* RHS);
        [propget, helpcontext(0x00010096)]
        HRESULT _stdcall Parent([out, retval] IDispatch** RHS);
        [propget, helpcontext(0x00010076)]
        HRESULT _stdcall Count([out, retval] long* RHS);
        [helpcontext(0x000100aa)]
        HRESULT _stdcall Item(
                        [in] XlAxisType Type, 
                        [in, optional, defaultvalue(1)] XlAxisGroup AxisGroup, 
                        [out, retval] Axis** RHS);
        [helpcontext(0x0000fffc)]
        HRESULT _stdcall _NewEnum([out, retval] IUnknown** RHS);
    };

    [
      odl,
      uuid(00020869-0001-0000-C000-000000000046),
      helpcontext(0x00020029),
      hidden
    ]
    interface IPoints : IDispatch {
        [propget, helpcontext(0x00010094)]
        HRESULT _stdcall Application([out, retval] Application** RHS);
        [propget, helpcontext(0x00010095)]
        HRESULT _stdcall Creator([out, retval] XlCreator* RHS);
        [propget, helpcontext(0x00010096)]
        HRESULT _stdcall Parent([out, retval] IDispatch** RHS);
        [propget, helpcontext(0x00010076)]
        HRESULT _stdcall Count([out, retval] long* RHS);
        [helpcontext(0x000100aa)]
        HRESULT _stdcall Item(
                        [in] long Index, 
                        [out, retval] Point** RHS);
        [helpcontext(0x0000fffc)]
        HRESULT _stdcall _NewEnum([out, retval] IUnknown** RHS);
    };

    [
      odl,
      uuid(0002086A-0001-0000-C000-000000000046),
      helpcontext(0x0002002a),
      hidden
    ]
    interface IPoint : IDispatch {
        [propget, helpcontext(0x00010094)]
        HRESULT _stdcall Application([out, retval] Application** RHS);
        [propget, helpcontext(0x00010095)]
        HRESULT _stdcall Creator([out, retval] XlCreator* RHS);
        [propget, helpcontext(0x00010096)]
        HRESULT _stdcall Parent([out, retval] IDispatch** RHS);
        [helpcontext(0x00010097)]
        HRESULT _stdcall ApplyDataLabels(
                        [in, optional, defaultvalue(2)] XlDataLabelsType Type, 
                        [in, optional] VARIANT LegendKey, 
                        [in, optional] VARIANT AutoText);
        [propget, helpcontext(0x00010080)]
        HRESULT _stdcall Border([out, retval] Border** RHS);
        [helpcontext(0x00010070)]
        HRESULT _stdcall ClearFormats();
        [helpcontext(0x00010227)]
        HRESULT _stdcall Copy();
        [propget, helpcontext(0x0001009e)]
        HRESULT _stdcall DataLabel([out, retval] DataLabel** RHS);
        [helpcontext(0x00010075)]
        HRESULT _stdcall Delete();
        [propget, helpcontext(0x000100b6)]
        HRESULT _stdcall Explosion([out, retval] long* RHS);
        [propput, helpcontext(0x000100b6)]
        HRESULT _stdcall Explosion([in] long RHS);
        [propget, helpcontext(0x0001004d)]
        HRESULT _stdcall HasDataLabel([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x0001004d)]
        HRESULT _stdcall HasDataLabel([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x00010081)]
        HRESULT _stdcall Interior([out, retval] Interior** RHS);
        [propget, helpcontext(0x00010084)]
        HRESULT _stdcall InvertIfNegative([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010084)]
        HRESULT _stdcall InvertIfNegative([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x00010049)]
        HRESULT _stdcall MarkerBackgroundColor([out, retval] long* RHS);
        [propput, helpcontext(0x00010049)]
        HRESULT _stdcall MarkerBackgroundColor([in] long RHS);
        [propget, helpcontext(0x0001004a)]
        HRESULT _stdcall MarkerBackgroundColorIndex([out, retval] XlColorIndex* RHS);
        [propput, helpcontext(0x0001004a)]
        HRESULT _stdcall MarkerBackgroundColorIndex([in] XlColorIndex RHS);
        [propget, helpcontext(0x0001004b)]
        HRESULT _stdcall MarkerForegroundColor([out, retval] long* RHS);
        [propput, helpcontext(0x0001004b)]
        HRESULT _stdcall MarkerForegroundColor([in] long RHS);
        [propget, helpcontext(0x0001004c)]
        HRESULT _stdcall MarkerForegroundColorIndex([out, retval] XlColorIndex* RHS);
        [propput, helpcontext(0x0001004c)]
        HRESULT _stdcall MarkerForegroundColorIndex([in] XlColorIndex RHS);
        [propget, helpcontext(0x000100e7)]
        HRESULT _stdcall MarkerSize([out, retval] long* RHS);
        [propput, helpcontext(0x000100e7)]
        HRESULT _stdcall MarkerSize([in] long RHS);
        [propget, helpcontext(0x00010048)]
        HRESULT _stdcall MarkerStyle([out, retval] XlMarkerStyle* RHS);
        [propput, helpcontext(0x00010048)]
        HRESULT _stdcall MarkerStyle([in] XlMarkerStyle RHS);
        [helpcontext(0x000100d3)]
        HRESULT _stdcall Paste();
        [propget, helpcontext(0x000100a1)]
        HRESULT _stdcall PictureType([out, retval] XlChartPictureType* RHS);
        [propput, helpcontext(0x000100a1)]
        HRESULT _stdcall PictureType([in] XlChartPictureType RHS);
        [propget, helpcontext(0x000100a2)]
        HRESULT _stdcall PictureUnit([out, retval] long* RHS);
        [propput, helpcontext(0x000100a2)]
        HRESULT _stdcall PictureUnit([in] long RHS);
        [helpcontext(0x000100eb)]
        HRESULT _stdcall Select();
        [propget, helpcontext(0x0001067b)]
        HRESULT _stdcall ApplyPictToSides([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x0001067b)]
        HRESULT _stdcall ApplyPictToSides([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x0001067c)]
        HRESULT _stdcall ApplyPictToFront([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x0001067c)]
        HRESULT _stdcall ApplyPictToFront([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x0001067d)]
        HRESULT _stdcall ApplyPictToEnd([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x0001067d)]
        HRESULT _stdcall ApplyPictToEnd([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x00010067)]
        HRESULT _stdcall Shadow([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010067)]
        HRESULT _stdcall Shadow([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x0001067e)]
        HRESULT _stdcall SecondaryPlot([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x0001067e)]
        HRESULT _stdcall SecondaryPlot([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x0001067f)]
        HRESULT _stdcall Fill([out, retval] ChartFillFormat** RHS);
    };

    [
      odl,
      uuid(0002086B-0001-0000-C000-000000000046),
      helpcontext(0x0002002b),
      hidden
    ]
    interface ISeries : IDispatch {
        [propget, helpcontext(0x00010094)]
        HRESULT _stdcall Application([out, retval] Application** RHS);
        [propget, helpcontext(0x00010095)]
        HRESULT _stdcall Creator([out, retval] XlCreator* RHS);
        [propget, helpcontext(0x00010096)]
        HRESULT _stdcall Parent([out, retval] IDispatch** RHS);
        [helpcontext(0x00010097)]
        HRESULT _stdcall ApplyDataLabels(
                        [in, optional, defaultvalue(2)] XlDataLabelsType Type, 
                        [in, optional] VARIANT LegendKey, 
                        [in, optional] VARIANT AutoText, 
                        [in, optional] VARIANT HasLeaderLines);
        [propget, helpcontext(0x0001002f)]
        HRESULT _stdcall AxisGroup([out, retval] XlAxisGroup* RHS);
        [propput, helpcontext(0x0001002f)]
        HRESULT _stdcall AxisGroup([in] XlAxisGroup RHS);
        [propget, helpcontext(0x00010080)]
        HRESULT _stdcall Border([out, retval] Border** RHS);
        [helpcontext(0x00010070)]
        HRESULT _stdcall ClearFormats();
        [helpcontext(0x00010227)]
        HRESULT _stdcall Copy();
        [helpcontext(0x0001009d)]
        HRESULT _stdcall DataLabels(
                        [in, optional] VARIANT Index, 
                        [out, retval] IDispatch** RHS);
        [helpcontext(0x00010075)]
        HRESULT _stdcall Delete();
        [helpcontext(0x00010098)]
        HRESULT _stdcall ErrorBar(
                        [in] XlErrorBarDirection Direction, 
                        [in] XlErrorBarInclude Include, 
                        [in] XlErrorBarType Type, 
                        [in, optional] VARIANT Amount, 
                        [in, optional] VARIANT MinusValues);
        [propget, helpcontext(0x0001009f)]
        HRESULT _stdcall ErrorBars([out, retval] ErrorBars** RHS);
        [propget, helpcontext(0x000100b6)]
        HRESULT _stdcall Explosion([out, retval] long* RHS);
        [propput, helpcontext(0x000100b6)]
        HRESULT _stdcall Explosion([in] long RHS);
        [propget, helpcontext(0x00010105)]
        HRESULT _stdcall Formula([out, retval] BSTR* RHS);
        [propput, helpcontext(0x00010105)]
        HRESULT _stdcall Formula([in] BSTR RHS);
        [propget, helpcontext(0x00010107)]
        HRESULT _stdcall FormulaLocal([out, retval] BSTR* RHS);
        [propput, helpcontext(0x00010107)]
        HRESULT _stdcall FormulaLocal([in] BSTR RHS);
        [propget, helpcontext(0x00010108)]
        HRESULT _stdcall FormulaR1C1([out, retval] BSTR* RHS);
        [propput, helpcontext(0x00010108)]
        HRESULT _stdcall FormulaR1C1([in] BSTR RHS);
        [propget, helpcontext(0x00010109)]
        HRESULT _stdcall FormulaR1C1Local([out, retval] BSTR* RHS);
        [propput, helpcontext(0x00010109)]
        HRESULT _stdcall FormulaR1C1Local([in] BSTR RHS);
        [propget, helpcontext(0x0001004e)]
        HRESULT _stdcall HasDataLabels([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x0001004e)]
        HRESULT _stdcall HasDataLabels([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x000100a0)]
        HRESULT _stdcall HasErrorBars([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x000100a0)]
        HRESULT _stdcall HasErrorBars([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x00010081)]
        HRESULT _stdcall Interior([out, retval] Interior** RHS);
        [propget, helpcontext(0x0001067f)]
        HRESULT _stdcall Fill([out, retval] ChartFillFormat** RHS);
        [propget, helpcontext(0x00010084)]
        HRESULT _stdcall InvertIfNegative([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010084)]
        HRESULT _stdcall InvertIfNegative([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x00010049)]
        HRESULT _stdcall MarkerBackgroundColor([out, retval] long* RHS);
        [propput, helpcontext(0x00010049)]
        HRESULT _stdcall MarkerBackgroundColor([in] long RHS);
        [propget, helpcontext(0x0001004a)]
        HRESULT _stdcall MarkerBackgroundColorIndex([out, retval] XlColorIndex* RHS);
        [propput, helpcontext(0x0001004a)]
        HRESULT _stdcall MarkerBackgroundColorIndex([in] XlColorIndex RHS);
        [propget, helpcontext(0x0001004b)]
        HRESULT _stdcall MarkerForegroundColor([out, retval] long* RHS);
        [propput, helpcontext(0x0001004b)]
        HRESULT _stdcall MarkerForegroundColor([in] long RHS);
        [propget, helpcontext(0x0001004c)]
        HRESULT _stdcall MarkerForegroundColorIndex([out, retval] XlColorIndex* RHS);
        [propput, helpcontext(0x0001004c)]
        HRESULT _stdcall MarkerForegroundColorIndex([in] XlColorIndex RHS);
        [propget, helpcontext(0x000100e7)]
        HRESULT _stdcall MarkerSize([out, retval] long* RHS);
        [propput, helpcontext(0x000100e7)]
        HRESULT _stdcall MarkerSize([in] long RHS);
        [propget, helpcontext(0x00010048)]
        HRESULT _stdcall MarkerStyle([out, retval] XlMarkerStyle* RHS);
        [propput, helpcontext(0x00010048)]
        HRESULT _stdcall MarkerStyle([in] XlMarkerStyle RHS);
        [propget, helpcontext(0x0001006e)]
        HRESULT _stdcall Name([out, retval] BSTR* RHS);
        [propput, helpcontext(0x0001006e)]
        HRESULT _stdcall Name([in] BSTR RHS);
        [helpcontext(0x000100d3)]
        HRESULT _stdcall Paste();
        [propget, helpcontext(0x000100a1)]
        HRESULT _stdcall PictureType([out, retval] XlChartPictureType* RHS);
        [propput, helpcontext(0x000100a1)]
        HRESULT _stdcall PictureType([in] XlChartPictureType RHS);
        [propget, helpcontext(0x000100a2)]
        HRESULT _stdcall PictureUnit([out, retval] long* RHS);
        [propput, helpcontext(0x000100a2)]
        HRESULT _stdcall PictureUnit([in] long RHS);
        [propget, helpcontext(0x000100e4)]
        HRESULT _stdcall PlotOrder([out, retval] long* RHS);
        [propput, helpcontext(0x000100e4)]
        HRESULT _stdcall PlotOrder([in] long RHS);
        [helpcontext(0x00010046)]
        HRESULT _stdcall Points(
                        [in, optional] VARIANT Index, 
                        [out, retval] IDispatch** RHS);
        [helpcontext(0x000100eb)]
        HRESULT _stdcall Select();
        [propget, helpcontext(0x000100a3)]
        HRESULT _stdcall Smooth([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x000100a3)]
        HRESULT _stdcall Smooth([in] VARIANT_BOOL RHS);
        [helpcontext(0x0001009a)]
        HRESULT _stdcall Trendlines(
                        [in, optional] VARIANT Index, 
                        [out, retval] IDispatch** RHS);
        [propget, helpcontext(0x0001006c)]
        HRESULT _stdcall Type([out, retval] long* RHS);
        [propput, helpcontext(0x0001006c)]
        HRESULT _stdcall Type([in] long RHS);
        [propget, helpcontext(0x00010578)]
        HRESULT _stdcall ChartType([out, retval] XlChartType* RHS);
        [propput, helpcontext(0x00010578)]
        HRESULT _stdcall ChartType([in] XlChartType RHS);
        [helpcontext(0x00010579)]
        HRESULT _stdcall ApplyCustomType([in] XlChartType ChartType);
        [propget, helpcontext(0x000100a4)]
        HRESULT _stdcall Values([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x000100a4)]
        HRESULT _stdcall Values([in] VARIANT RHS);
        [propget, helpcontext(0x00010457)]
        HRESULT _stdcall XValues([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010457)]
        HRESULT _stdcall XValues([in] VARIANT RHS);
        [propget, helpcontext(0x00010680)]
        HRESULT _stdcall BubbleSizes([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010680)]
        HRESULT _stdcall BubbleSizes([in] VARIANT RHS);
        [propget, helpcontext(0x0001057b)]
        HRESULT _stdcall BarShape([out, retval] XlBarShape* RHS);
        [propput, helpcontext(0x0001057b)]
        HRESULT _stdcall BarShape([in] XlBarShape RHS);
        [propget, helpcontext(0x0001067b)]
        HRESULT _stdcall ApplyPictToSides([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x0001067b)]
        HRESULT _stdcall ApplyPictToSides([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x0001067c)]
        HRESULT _stdcall ApplyPictToFront([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x0001067c)]
        HRESULT _stdcall ApplyPictToFront([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x0001067d)]
        HRESULT _stdcall ApplyPictToEnd([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x0001067d)]
        HRESULT _stdcall ApplyPictToEnd([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x00010681)]
        HRESULT _stdcall Has3DEffect([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010681)]
        HRESULT _stdcall Has3DEffect([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x00010067)]
        HRESULT _stdcall Shadow([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010067)]
        HRESULT _stdcall Shadow([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x00010572)]
        HRESULT _stdcall HasLeaderLines([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010572)]
        HRESULT _stdcall HasLeaderLines([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x00010682)]
        HRESULT _stdcall LeaderLines([out, retval] LeaderLines** RHS);
    };

    [
      odl,
      uuid(0002086C-0001-0000-C000-000000000046),
      helpcontext(0x0002002c),
      hidden
    ]
    interface ISeriesCollection : IDispatch {
        [propget, helpcontext(0x00010094)]
        HRESULT _stdcall Application([out, retval] Application** RHS);
        [propget, helpcontext(0x00010095)]
        HRESULT _stdcall Creator([out, retval] XlCreator* RHS);
        [propget, helpcontext(0x00010096)]
        HRESULT _stdcall Parent([out, retval] IDispatch** RHS);
        [helpcontext(0x000100b5)]
        HRESULT _stdcall Add(
                        [in] VARIANT Source, 
                        [in, optional, defaultvalue(2)] XlRowCol Rowcol, 
                        [in, optional] VARIANT SeriesLabels, 
                        [in, optional] VARIANT CategoryLabels, 
                        [in, optional] VARIANT Replace, 
                        [out, retval] Series** RHS);
        [propget, helpcontext(0x00010076)]
        HRESULT _stdcall Count([out, retval] long* RHS);
        [helpcontext(0x000100e3)]
        HRESULT _stdcall Extend(
                        [in] VARIANT Source, 
                        [in, optional] VARIANT Rowcol, 
                        [in, optional] VARIANT CategoryLabels);
        [helpcontext(0x000100aa)]
        HRESULT _stdcall Item(
                        [in] VARIANT Index, 
                        [out, retval] Series** RHS);
        [helpcontext(0x0000fffc)]
        HRESULT _stdcall _NewEnum([out, retval] IUnknown** RHS);
        [helpcontext(0x000100d3)]
        HRESULT _stdcall Paste(
                        [in, optional, defaultvalue(2)] XlRowCol Rowcol, 
                        [in, optional] VARIANT SeriesLabels, 
                        [in, optional] VARIANT CategoryLabels, 
                        [in, optional] VARIANT Replace, 
                        [in, optional] VARIANT NewSeries);
        [helpcontext(0x0001045d)]
        HRESULT _stdcall NewSeries([out, retval] Series** RHS);
    };

    [
      odl,
      uuid(000208B2-0001-0000-C000-000000000046),
      helpcontext(0x00020072),
      hidden
    ]
    interface IDataLabel : IDispatch {
        [propget, helpcontext(0x00010094)]
        HRESULT _stdcall Application([out, retval] Application** RHS);
        [propget, helpcontext(0x00010095)]
        HRESULT _stdcall Creator([out, retval] XlCreator* RHS);
        [propget, helpcontext(0x00010096)]
        HRESULT _stdcall Parent([out, retval] IDispatch** RHS);
        [propget, helpcontext(0x0001006e)]
        HRESULT _stdcall Name([out, retval] BSTR* RHS);
        [helpcontext(0x000100eb)]
        HRESULT _stdcall Select();
        [propget, helpcontext(0x00010080)]
        HRESULT _stdcall Border([out, retval] Border** RHS);
        [helpcontext(0x00010075)]
        HRESULT _stdcall Delete();
        [propget, helpcontext(0x00010081)]
        HRESULT _stdcall Interior([out, retval] Interior** RHS);
        [propget, helpcontext(0x0001067f)]
        HRESULT _stdcall Fill([out, retval] ChartFillFormat** RHS);
        [propget, helpcontext(0x0001008b)]
        HRESULT _stdcall Caption([out, retval] BSTR* RHS);
        [propput, helpcontext(0x0001008b)]
        HRESULT _stdcall Caption([in] BSTR RHS);
        [propget, helpcontext(0x0001025b)]
        HRESULT _stdcall Characters(
                        [in, optional] VARIANT Start, 
                        [in, optional] VARIANT Length, 
                        [out, retval] Characters** RHS);
        [propget, helpcontext(0x00010092)]
        HRESULT _stdcall Font([out, retval] Font** RHS);
        [propget, helpcontext(0x00010088)]
        HRESULT _stdcall HorizontalAlignment([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010088)]
        HRESULT _stdcall HorizontalAlignment([in] VARIANT RHS);
        [propget, helpcontext(0x0001007f)]
        HRESULT _stdcall Left([out, retval] double* RHS);
        [propput, helpcontext(0x0001007f)]
        HRESULT _stdcall Left([in] double RHS);
        [propget, helpcontext(0x00010086)]
        HRESULT _stdcall Orientation([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010086)]
        HRESULT _stdcall Orientation([in] VARIANT RHS);
        [propget, helpcontext(0x00010067)]
        HRESULT _stdcall Shadow([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010067)]
        HRESULT _stdcall Shadow([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x0001008a)]
        HRESULT _stdcall Text([out, retval] BSTR* RHS);
        [propput, helpcontext(0x0001008a)]
        HRESULT _stdcall Text([in] BSTR RHS);
        [propget, helpcontext(0x0001007e)]
        HRESULT _stdcall Top([out, retval] double* RHS);
        [propput, helpcontext(0x0001007e)]
        HRESULT _stdcall Top([in] double RHS);
        [propget, helpcontext(0x00010089)]
        HRESULT _stdcall VerticalAlignment([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010089)]
        HRESULT _stdcall VerticalAlignment([in] VARIANT RHS);
        [propget, helpcontext(0x000103cf)]
        HRESULT _stdcall ReadingOrder([out, retval] long* RHS);
        [propput, helpcontext(0x000103cf)]
        HRESULT _stdcall ReadingOrder([in] long RHS);
        [propget, helpcontext(0x000105f5)]
        HRESULT _stdcall AutoScaleFont([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x000105f5)]
        HRESULT _stdcall AutoScaleFont([in] VARIANT RHS);
        [propget, helpcontext(0x00010087)]
        HRESULT _stdcall AutoText([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010087)]
        HRESULT _stdcall AutoText([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x000100c1)]
        HRESULT _stdcall NumberFormat([out, retval] BSTR* RHS);
        [propput, helpcontext(0x000100c1)]
        HRESULT _stdcall NumberFormat([in] BSTR RHS);
        [propget, helpcontext(0x000100c2)]
        HRESULT _stdcall NumberFormatLinked([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x000100c2)]
        HRESULT _stdcall NumberFormatLinked([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x000100ab)]
        HRESULT _stdcall ShowLegendKey([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x000100ab)]
        HRESULT _stdcall ShowLegendKey([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x0001006c)]
        HRESULT _stdcall Type([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x0001006c)]
        HRESULT _stdcall Type([in] VARIANT RHS);
        [propget, helpcontext(0x00010085)]
        HRESULT _stdcall Position([out, retval] XlDataLabelPosition* RHS);
        [propput, helpcontext(0x00010085)]
        HRESULT _stdcall Position([in] XlDataLabelPosition RHS);
    };

    [
      odl,
      uuid(000208B3-0001-0000-C000-000000000046),
      helpcontext(0x00020073),
      hidden
    ]
    interface IDataLabels : IDispatch {
        [propget, helpcontext(0x00010094)]
        HRESULT _stdcall Application([out, retval] Application** RHS);
        [propget, helpcontext(0x00010095)]
        HRESULT _stdcall Creator([out, retval] XlCreator* RHS);
        [propget, helpcontext(0x00010096)]
        HRESULT _stdcall Parent([out, retval] IDispatch** RHS);
        [propget, helpcontext(0x0001006e)]
        HRESULT _stdcall Name([out, retval] BSTR* RHS);
        [helpcontext(0x000100eb)]
        HRESULT _stdcall Select();
        [propget, helpcontext(0x00010080)]
        HRESULT _stdcall Border([out, retval] Border** RHS);
        [helpcontext(0x00010075)]
        HRESULT _stdcall Delete();
        [propget, helpcontext(0x00010081)]
        HRESULT _stdcall Interior([out, retval] Interior** RHS);
        [propget, helpcontext(0x0001067f)]
        HRESULT _stdcall Fill([out, retval] ChartFillFormat** RHS);
        [restricted, hidden]
        void _stdcall _Dummy9();
        [restricted, hidden]
        void _stdcall _Dummy10();
        [propget, helpcontext(0x00010092)]
        HRESULT _stdcall Font([out, retval] Font** RHS);
        [propget, helpcontext(0x00010088)]
        HRESULT _stdcall HorizontalAlignment([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010088)]
        HRESULT _stdcall HorizontalAlignment([in] VARIANT RHS);
        [restricted, hidden]
        void _stdcall _Dummy13();
        [propget, helpcontext(0x00010086)]
        HRESULT _stdcall Orientation([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010086)]
        HRESULT _stdcall Orientation([in] VARIANT RHS);
        [propget, helpcontext(0x00010067)]
        HRESULT _stdcall Shadow([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010067)]
        HRESULT _stdcall Shadow([in] VARIANT_BOOL RHS);
        [restricted, hidden]
        void _stdcall _Dummy16();
        [restricted, hidden]
        void _stdcall _Dummy17();
        [propget, helpcontext(0x00010089)]
        HRESULT _stdcall VerticalAlignment([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010089)]
        HRESULT _stdcall VerticalAlignment([in] VARIANT RHS);
        [propget, helpcontext(0x000103cf)]
        HRESULT _stdcall ReadingOrder([out, retval] long* RHS);
        [propput, helpcontext(0x000103cf)]
        HRESULT _stdcall ReadingOrder([in] long RHS);
        [propget, helpcontext(0x000105f5)]
        HRESULT _stdcall AutoScaleFont([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x000105f5)]
        HRESULT _stdcall AutoScaleFont([in] VARIANT RHS);
        [propget, helpcontext(0x00010087)]
        HRESULT _stdcall AutoText([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010087)]
        HRESULT _stdcall AutoText([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x000100c1)]
        HRESULT _stdcall NumberFormat([out, retval] BSTR* RHS);
        [propput, helpcontext(0x000100c1)]
        HRESULT _stdcall NumberFormat([in] BSTR RHS);
        [propget, helpcontext(0x000100c2)]
        HRESULT _stdcall NumberFormatLinked([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x000100c2)]
        HRESULT _stdcall NumberFormatLinked([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x000100ab)]
        HRESULT _stdcall ShowLegendKey([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x000100ab)]
        HRESULT _stdcall ShowLegendKey([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x0001006c)]
        HRESULT _stdcall Type([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x0001006c)]
        HRESULT _stdcall Type([in] VARIANT RHS);
        [propget, helpcontext(0x00010085)]
        HRESULT _stdcall Position([out, retval] XlDataLabelPosition* RHS);
        [propput, helpcontext(0x00010085)]
        HRESULT _stdcall Position([in] XlDataLabelPosition RHS);
        [propget, helpcontext(0x00010076)]
        HRESULT _stdcall Count([out, retval] long* RHS);
        [helpcontext(0x000100aa)]
        HRESULT _stdcall Item(
                        [in] VARIANT Index, 
                        [out, retval] DataLabel** RHS);
        [helpcontext(0x0000fffc)]
        HRESULT _stdcall _NewEnum([out, retval] IUnknown** RHS);
    };

    [
      odl,
      uuid(000208BA-0001-0000-C000-000000000046),
      helpcontext(0x0002007a),
      hidden
    ]
    interface ILegendEntry : IDispatch {
        [propget, helpcontext(0x00010094)]
        HRESULT _stdcall Application([out, retval] Application** RHS);
        [propget, helpcontext(0x00010095)]
        HRESULT _stdcall Creator([out, retval] XlCreator* RHS);
        [propget, helpcontext(0x00010096)]
        HRESULT _stdcall Parent([out, retval] IDispatch** RHS);
        [helpcontext(0x00010075)]
        HRESULT _stdcall Delete();
        [propget, helpcontext(0x00010092)]
        HRESULT _stdcall Font([out, retval] Font** RHS);
        [propget, helpcontext(0x000101e6)]
        HRESULT _stdcall Index([out, retval] long* RHS);
        [propget, helpcontext(0x000100ae)]
        HRESULT _stdcall LegendKey([out, retval] LegendKey** RHS);
        [helpcontext(0x000100eb)]
        HRESULT _stdcall Select();
        [propget, helpcontext(0x000105f5)]
        HRESULT _stdcall AutoScaleFont([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x000105f5)]
        HRESULT _stdcall AutoScaleFont([in] VARIANT RHS);
        [propget, helpcontext(0x0001007f)]
        HRESULT _stdcall Left([out, retval] double* RHS);
        [propget, helpcontext(0x0001007e)]
        HRESULT _stdcall Top([out, retval] double* RHS);
        [propget, helpcontext(0x0001007a)]
        HRESULT _stdcall Width([out, retval] double* RHS);
        [propget, helpcontext(0x0001007b)]
        HRESULT _stdcall Height([out, retval] double* RHS);
    };

    [
      odl,
      uuid(000208BB-0001-0000-C000-000000000046),
      helpcontext(0x0002007b),
      hidden
    ]
    interface ILegendEntries : IDispatch {
        [propget, helpcontext(0x00010094)]
        HRESULT _stdcall Application([out, retval] Application** RHS);
        [propget, helpcontext(0x00010095)]
        HRESULT _stdcall Creator([out, retval] XlCreator* RHS);
        [propget, helpcontext(0x00010096)]
        HRESULT _stdcall Parent([out, retval] IDispatch** RHS);
        [propget, helpcontext(0x00010076)]
        HRESULT _stdcall Count([out, retval] long* RHS);
        [helpcontext(0x000100aa)]
        HRESULT _stdcall Item(
                        [in] VARIANT Index, 
                        [out, retval] LegendEntry** RHS);
        [helpcontext(0x0000fffc)]
        HRESULT _stdcall _NewEnum([out, retval] IUnknown** RHS);
    };

    [
      odl,
      uuid(000208BC-0001-0000-C000-000000000046),
      helpcontext(0x0002007c),
      hidden
    ]
    interface ILegendKey : IDispatch {
        [propget, helpcontext(0x00010094)]
        HRESULT _stdcall Application([out, retval] Application** RHS);
        [propget, helpcontext(0x00010095)]
        HRESULT _stdcall Creator([out, retval] XlCreator* RHS);
        [propget, helpcontext(0x00010096)]
        HRESULT _stdcall Parent([out, retval] IDispatch** RHS);
        [propget, helpcontext(0x00010080)]
        HRESULT _stdcall Border([out, retval] Border** RHS);
        [helpcontext(0x00010070)]
        HRESULT _stdcall ClearFormats();
        [helpcontext(0x00010075)]
        HRESULT _stdcall Delete();
        [propget, helpcontext(0x00010081)]
        HRESULT _stdcall Interior([out, retval] Interior** RHS);
        [propget, helpcontext(0x0001067f)]
        HRESULT _stdcall Fill([out, retval] ChartFillFormat** RHS);
        [propget, helpcontext(0x00010084)]
        HRESULT _stdcall InvertIfNegative([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010084)]
        HRESULT _stdcall InvertIfNegative([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x00010049)]
        HRESULT _stdcall MarkerBackgroundColor([out, retval] long* RHS);
        [propput, helpcontext(0x00010049)]
        HRESULT _stdcall MarkerBackgroundColor([in] long RHS);
        [propget, helpcontext(0x0001004a)]
        HRESULT _stdcall MarkerBackgroundColorIndex([out, retval] XlColorIndex* RHS);
        [propput, helpcontext(0x0001004a)]
        HRESULT _stdcall MarkerBackgroundColorIndex([in] XlColorIndex RHS);
        [propget, helpcontext(0x0001004b)]
        HRESULT _stdcall MarkerForegroundColor([out, retval] long* RHS);
        [propput, helpcontext(0x0001004b)]
        HRESULT _stdcall MarkerForegroundColor([in] long RHS);
        [propget, helpcontext(0x0001004c)]
        HRESULT _stdcall MarkerForegroundColorIndex([out, retval] XlColorIndex* RHS);
        [propput, helpcontext(0x0001004c)]
        HRESULT _stdcall MarkerForegroundColorIndex([in] XlColorIndex RHS);
        [propget, helpcontext(0x000100e7)]
        HRESULT _stdcall MarkerSize([out, retval] long* RHS);
        [propput, helpcontext(0x000100e7)]
        HRESULT _stdcall MarkerSize([in] long RHS);
        [propget, helpcontext(0x00010048)]
        HRESULT _stdcall MarkerStyle([out, retval] XlMarkerStyle* RHS);
        [propput, helpcontext(0x00010048)]
        HRESULT _stdcall MarkerStyle([in] XlMarkerStyle RHS);
        [propget, helpcontext(0x000100a1)]
        HRESULT _stdcall PictureType([out, retval] long* RHS);
        [propput, helpcontext(0x000100a1)]
        HRESULT _stdcall PictureType([in] long RHS);
        [propget, helpcontext(0x000100a2)]
        HRESULT _stdcall PictureUnit([out, retval] long* RHS);
        [propput, helpcontext(0x000100a2)]
        HRESULT _stdcall PictureUnit([in] long RHS);
        [helpcontext(0x000100eb)]
        HRESULT _stdcall Select();
        [propget, helpcontext(0x000100a3)]
        HRESULT _stdcall Smooth([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x000100a3)]
        HRESULT _stdcall Smooth([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x0001007f)]
        HRESULT _stdcall Left([out, retval] double* RHS);
        [propget, helpcontext(0x0001007e)]
        HRESULT _stdcall Top([out, retval] double* RHS);
        [propget, helpcontext(0x0001007a)]
        HRESULT _stdcall Width([out, retval] double* RHS);
        [propget, helpcontext(0x0001007b)]
        HRESULT _stdcall Height([out, retval] double* RHS);
        [propget, helpcontext(0x00010067)]
        HRESULT _stdcall Shadow([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010067)]
        HRESULT _stdcall Shadow([in] VARIANT_BOOL RHS);
    };

    [
      odl,
      uuid(000208BD-0001-0000-C000-000000000046),
      helpcontext(0x0002007d),
      hidden
    ]
    interface ITrendlines : IDispatch {
        [propget, helpcontext(0x00010094)]
        HRESULT _stdcall Application([out, retval] Application** RHS);
        [propget, helpcontext(0x00010095)]
        HRESULT _stdcall Creator([out, retval] XlCreator* RHS);
        [propget, helpcontext(0x00010096)]
        HRESULT _stdcall Parent([out, retval] IDispatch** RHS);
        [helpcontext(0x000100b5)]
        HRESULT _stdcall Add(
                        [in, optional, defaultvalue(-4132)] XlTrendlineType Type, 
                        [in, optional] VARIANT Order, 
                        [in, optional] VARIANT Period, 
                        [in, optional] VARIANT Forward, 
                        [in, optional] VARIANT Backward, 
                        [in, optional] VARIANT Intercept, 
                        [in, optional] VARIANT DisplayEquation, 
                        [in, optional] VARIANT DisplayRSquared, 
                        [in, optional] VARIANT Name, 
                        [out, retval] Trendline** RHS);
        [propget, helpcontext(0x00010076)]
        HRESULT _stdcall Count([out, retval] long* RHS);
        [helpcontext(0x000100aa)]
        HRESULT _stdcall Item(
                        [in, optional] VARIANT Index, 
                        [out, retval] Trendline** RHS);
        [helpcontext(0x0000fffc)]
        HRESULT _stdcall _NewEnum([out, retval] IUnknown** RHS);
    };

    [
      odl,
      uuid(000208BE-0001-0000-C000-000000000046),
      helpcontext(0x0002007e),
      hidden
    ]
    interface ITrendline : IDispatch {
        [propget, helpcontext(0x00010094)]
        HRESULT _stdcall Application([out, retval] Application** RHS);
        [propget, helpcontext(0x00010095)]
        HRESULT _stdcall Creator([out, retval] XlCreator* RHS);
        [propget, helpcontext(0x00010096)]
        HRESULT _stdcall Parent([out, retval] IDispatch** RHS);
        [propget, helpcontext(0x000100b9)]
        HRESULT _stdcall Backward([out, retval] long* RHS);
        [propput, helpcontext(0x000100b9)]
        HRESULT _stdcall Backward([in] long RHS);
        [propget, helpcontext(0x00010080)]
        HRESULT _stdcall Border([out, retval] Border** RHS);
        [helpcontext(0x00010070)]
        HRESULT _stdcall ClearFormats();
        [propget, helpcontext(0x0001009e)]
        HRESULT _stdcall DataLabel([out, retval] DataLabel** RHS);
        [helpcontext(0x00010075)]
        HRESULT _stdcall Delete();
        [propget, helpcontext(0x000100be)]
        HRESULT _stdcall DisplayEquation([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x000100be)]
        HRESULT _stdcall DisplayEquation([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x000100bd)]
        HRESULT _stdcall DisplayRSquared([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x000100bd)]
        HRESULT _stdcall DisplayRSquared([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x000100bf)]
        HRESULT _stdcall Forward([out, retval] long* RHS);
        [propput, helpcontext(0x000100bf)]
        HRESULT _stdcall Forward([in] long RHS);
        [propget, helpcontext(0x000101e6)]
        HRESULT _stdcall Index([out, retval] long* RHS);
        [propget, helpcontext(0x000100ba)]
        HRESULT _stdcall Intercept([out, retval] double* RHS);
        [propput, helpcontext(0x000100ba)]
        HRESULT _stdcall Intercept([in] double RHS);
        [propget, helpcontext(0x000100bb)]
        HRESULT _stdcall InterceptIsAuto([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x000100bb)]
        HRESULT _stdcall InterceptIsAuto([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x0001006e)]
        HRESULT _stdcall Name([out, retval] BSTR* RHS);
        [propput, helpcontext(0x0001006e)]
        HRESULT _stdcall Name([in] BSTR RHS);
        [propget, helpcontext(0x000100bc)]
        HRESULT _stdcall NameIsAuto([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x000100bc)]
        HRESULT _stdcall NameIsAuto([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x000100c0)]
        HRESULT _stdcall Order([out, retval] long* RHS);
        [propput, helpcontext(0x000100c0)]
        HRESULT _stdcall Order([in] long RHS);
        [propget, helpcontext(0x000100b8)]
        HRESULT _stdcall Period([out, retval] long* RHS);
        [propput, helpcontext(0x000100b8)]
        HRESULT _stdcall Period([in] long RHS);
        [helpcontext(0x000100eb)]
        HRESULT _stdcall Select();
        [propget, helpcontext(0x0001006c)]
        HRESULT _stdcall Type([out, retval] XlTrendlineType* RHS);
        [propput, helpcontext(0x0001006c)]
        HRESULT _stdcall Type([in] XlTrendlineType RHS);
    };

    [
      odl,
      uuid(000208C0-0001-0000-C000-000000000046),
      helpcontext(0x00020080),
      hidden
    ]
    interface ICorners : IDispatch {
        [propget, helpcontext(0x00010094)]
        HRESULT _stdcall Application([out, retval] Application** RHS);
        [propget, helpcontext(0x00010095)]
        HRESULT _stdcall Creator([out, retval] XlCreator* RHS);
        [propget, helpcontext(0x00010096)]
        HRESULT _stdcall Parent([out, retval] IDispatch** RHS);
        [propget, helpcontext(0x0001006e)]
        HRESULT _stdcall Name([out, retval] BSTR* RHS);
        [helpcontext(0x000100eb)]
        HRESULT _stdcall Select();
    };

    [
      odl,
      uuid(000208C1-0001-0000-C000-000000000046),
      helpcontext(0x00020081),
      hidden
    ]
    interface ISeriesLines : IDispatch {
        [propget, helpcontext(0x00010094)]
        HRESULT _stdcall Application([out, retval] Application** RHS);
        [propget, helpcontext(0x00010095)]
        HRESULT _stdcall Creator([out, retval] XlCreator* RHS);
        [propget, helpcontext(0x00010096)]
        HRESULT _stdcall Parent([out, retval] IDispatch** RHS);
        [propget, helpcontext(0x0001006e)]
        HRESULT _stdcall Name([out, retval] BSTR* RHS);
        [helpcontext(0x000100eb)]
        HRESULT _stdcall Select();
        [propget, helpcontext(0x00010080)]
        HRESULT _stdcall Border([out, retval] Border** RHS);
        [helpcontext(0x00010075)]
        HRESULT _stdcall Delete();
    };

    [
      odl,
      uuid(000208C2-0001-0000-C000-000000000046),
      helpcontext(0x00020082),
      hidden
    ]
    interface IHiLoLines : IDispatch {
        [propget, helpcontext(0x00010094)]
        HRESULT _stdcall Application([out, retval] Application** RHS);
        [propget, helpcontext(0x00010095)]
        HRESULT _stdcall Creator([out, retval] XlCreator* RHS);
        [propget, helpcontext(0x00010096)]
        HRESULT _stdcall Parent([out, retval] IDispatch** RHS);
        [propget, helpcontext(0x0001006e)]
        HRESULT _stdcall Name([out, retval] BSTR* RHS);
        [helpcontext(0x000100eb)]
        HRESULT _stdcall Select();
        [propget, helpcontext(0x00010080)]
        HRESULT _stdcall Border([out, retval] Border** RHS);
        [helpcontext(0x00010075)]
        HRESULT _stdcall Delete();
    };

    [
      odl,
      uuid(000208C3-0001-0000-C000-000000000046),
      helpcontext(0x00020083),
      hidden
    ]
    interface IGridlines : IDispatch {
        [propget, helpcontext(0x00010094)]
        HRESULT _stdcall Application([out, retval] Application** RHS);
        [propget, helpcontext(0x00010095)]
        HRESULT _stdcall Creator([out, retval] XlCreator* RHS);
        [propget, helpcontext(0x00010096)]
        HRESULT _stdcall Parent([out, retval] IDispatch** RHS);
        [propget, helpcontext(0x0001006e)]
        HRESULT _stdcall Name([out, retval] BSTR* RHS);
        [helpcontext(0x000100eb)]
        HRESULT _stdcall Select();
        [propget, helpcontext(0x00010080)]
        HRESULT _stdcall Border([out, retval] Border** RHS);
        [helpcontext(0x00010075)]
        HRESULT _stdcall Delete();
    };

    [
      odl,
      uuid(000208C4-0001-0000-C000-000000000046),
      helpcontext(0x00020084),
      hidden
    ]
    interface IDropLines : IDispatch {
        [propget, helpcontext(0x00010094)]
        HRESULT _stdcall Application([out, retval] Application** RHS);
        [propget, helpcontext(0x00010095)]
        HRESULT _stdcall Creator([out, retval] XlCreator* RHS);
        [propget, helpcontext(0x00010096)]
        HRESULT _stdcall Parent([out, retval] IDispatch** RHS);
        [propget, helpcontext(0x0001006e)]
        HRESULT _stdcall Name([out, retval] BSTR* RHS);
        [helpcontext(0x000100eb)]
        HRESULT _stdcall Select();
        [propget, helpcontext(0x00010080)]
        HRESULT _stdcall Border([out, retval] Border** RHS);
        [helpcontext(0x00010075)]
        HRESULT _stdcall Delete();
    };

    [
      odl,
      uuid(00024437-0001-0000-C000-000000000046),
      helpcontext(0x000200cd),
      hidden
    ]
    interface ILeaderLines : IDispatch {
        [propget, helpcontext(0x00010094)]
        HRESULT _stdcall Application([out, retval] Application** RHS);
        [propget, helpcontext(0x00010095)]
        HRESULT _stdcall Creator([out, retval] XlCreator* RHS);
        [propget, helpcontext(0x00010096)]
        HRESULT _stdcall Parent([out, retval] IDispatch** RHS);
        [propget, helpcontext(0x00010080)]
        HRESULT _stdcall Border([out, retval] Border** RHS);
        [helpcontext(0x00010075)]
        HRESULT _stdcall Delete();
        [helpcontext(0x000100eb)]
        HRESULT _stdcall Select();
    };

    [
      odl,
      uuid(000208C5-0001-0000-C000-000000000046),
      helpcontext(0x00020085),
      hidden
    ]
    interface IUpBars : IDispatch {
        [propget, helpcontext(0x00010094)]
        HRESULT _stdcall Application([out, retval] Application** RHS);
        [propget, helpcontext(0x00010095)]
        HRESULT _stdcall Creator([out, retval] XlCreator* RHS);
        [propget, helpcontext(0x00010096)]
        HRESULT _stdcall Parent([out, retval] IDispatch** RHS);
        [propget, helpcontext(0x0001006e)]
        HRESULT _stdcall Name([out, retval] BSTR* RHS);
        [helpcontext(0x000100eb)]
        HRESULT _stdcall Select();
        [propget, helpcontext(0x00010080)]
        HRESULT _stdcall Border([out, retval] Border** RHS);
        [helpcontext(0x00010075)]
        HRESULT _stdcall Delete();
        [propget, helpcontext(0x00010081)]
        HRESULT _stdcall Interior([out, retval] Interior** RHS);
        [propget, helpcontext(0x0001067f)]
        HRESULT _stdcall Fill([out, retval] ChartFillFormat** RHS);
    };

    [
      odl,
      uuid(000208C6-0001-0000-C000-000000000046),
      helpcontext(0x00020086),
      hidden
    ]
    interface IDownBars : IDispatch {
        [propget, helpcontext(0x00010094)]
        HRESULT _stdcall Application([out, retval] Application** RHS);
        [propget, helpcontext(0x00010095)]
        HRESULT _stdcall Creator([out, retval] XlCreator* RHS);
        [propget, helpcontext(0x00010096)]
        HRESULT _stdcall Parent([out, retval] IDispatch** RHS);
        [propget, helpcontext(0x0001006e)]
        HRESULT _stdcall Name([out, retval] BSTR* RHS);
        [helpcontext(0x000100eb)]
        HRESULT _stdcall Select();
        [propget, helpcontext(0x00010080)]
        HRESULT _stdcall Border([out, retval] Border** RHS);
        [helpcontext(0x00010075)]
        HRESULT _stdcall Delete();
        [propget, helpcontext(0x00010081)]
        HRESULT _stdcall Interior([out, retval] Interior** RHS);
        [propget, helpcontext(0x0001067f)]
        HRESULT _stdcall Fill([out, retval] ChartFillFormat** RHS);
    };

    [
      odl,
      uuid(000208C7-0001-0000-C000-000000000046),
      helpcontext(0x00020087),
      hidden
    ]
    interface IFloor : IDispatch {
        [propget, helpcontext(0x00010094)]
        HRESULT _stdcall Application([out, retval] Application** RHS);
        [propget, helpcontext(0x00010095)]
        HRESULT _stdcall Creator([out, retval] XlCreator* RHS);
        [propget, helpcontext(0x00010096)]
        HRESULT _stdcall Parent([out, retval] IDispatch** RHS);
        [propget, helpcontext(0x0001006e)]
        HRESULT _stdcall Name([out, retval] BSTR* RHS);
        [helpcontext(0x000100eb)]
        HRESULT _stdcall Select();
        [propget, helpcontext(0x00010080)]
        HRESULT _stdcall Border([out, retval] Border** RHS);
        [helpcontext(0x00010070)]
        HRESULT _stdcall ClearFormats();
        [propget, helpcontext(0x00010081)]
        HRESULT _stdcall Interior([out, retval] Interior** RHS);
        [propget, helpcontext(0x0001067f)]
        HRESULT _stdcall Fill([out, retval] ChartFillFormat** RHS);
        [propget, helpcontext(0x000100a1)]
        HRESULT _stdcall PictureType([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x000100a1)]
        HRESULT _stdcall PictureType([in] VARIANT RHS);
        [helpcontext(0x000100d3)]
        HRESULT _stdcall Paste();
    };

    [
      odl,
      uuid(000208C8-0001-0000-C000-000000000046),
      helpcontext(0x00020088),
      hidden
    ]
    interface IWalls : IDispatch {
        [propget, helpcontext(0x00010094)]
        HRESULT _stdcall Application([out, retval] Application** RHS);
        [propget, helpcontext(0x00010095)]
        HRESULT _stdcall Creator([out, retval] XlCreator* RHS);
        [propget, helpcontext(0x00010096)]
        HRESULT _stdcall Parent([out, retval] IDispatch** RHS);
        [propget, helpcontext(0x0001006e)]
        HRESULT _stdcall Name([out, retval] BSTR* RHS);
        [helpcontext(0x000100eb)]
        HRESULT _stdcall Select();
        [propget, helpcontext(0x00010080)]
        HRESULT _stdcall Border([out, retval] Border** RHS);
        [helpcontext(0x00010070)]
        HRESULT _stdcall ClearFormats();
        [propget, helpcontext(0x00010081)]
        HRESULT _stdcall Interior([out, retval] Interior** RHS);
        [propget, helpcontext(0x0001067f)]
        HRESULT _stdcall Fill([out, retval] ChartFillFormat** RHS);
        [propget, helpcontext(0x000100a1)]
        HRESULT _stdcall PictureType([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x000100a1)]
        HRESULT _stdcall PictureType([in] VARIANT RHS);
        [helpcontext(0x000100d3)]
        HRESULT _stdcall Paste();
        [propget, helpcontext(0x000100a2)]
        HRESULT _stdcall PictureUnit([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x000100a2)]
        HRESULT _stdcall PictureUnit([in] VARIANT RHS);
    };

    [
      odl,
      uuid(000208C9-0001-0000-C000-000000000046),
      helpcontext(0x00020089),
      hidden
    ]
    interface ITickLabels : IDispatch {
        [propget, helpcontext(0x00010094)]
        HRESULT _stdcall Application([out, retval] Application** RHS);
        [propget, helpcontext(0x00010095)]
        HRESULT _stdcall Creator([out, retval] XlCreator* RHS);
        [propget, helpcontext(0x00010096)]
        HRESULT _stdcall Parent([out, retval] IDispatch** RHS);
        [helpcontext(0x00010075)]
        HRESULT _stdcall Delete();
        [propget, helpcontext(0x00010092)]
        HRESULT _stdcall Font([out, retval] Font** RHS);
        [propget, helpcontext(0x0001006e)]
        HRESULT _stdcall Name([out, retval] BSTR* RHS);
        [propget, helpcontext(0x000100c1)]
        HRESULT _stdcall NumberFormat([out, retval] BSTR* RHS);
        [propput, helpcontext(0x000100c1)]
        HRESULT _stdcall NumberFormat([in] BSTR RHS);
        [propget, helpcontext(0x000100c2)]
        HRESULT _stdcall NumberFormatLinked([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x000100c2)]
        HRESULT _stdcall NumberFormatLinked([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x00010086)]
        HRESULT _stdcall Orientation([out, retval] XlTickLabelOrientation* RHS);
        [propput, helpcontext(0x00010086)]
        HRESULT _stdcall Orientation([in] XlTickLabelOrientation RHS);
        [helpcontext(0x000100eb)]
        HRESULT _stdcall Select();
        [propget, helpcontext(0x000103cf)]
        HRESULT _stdcall ReadingOrder([out, retval] long* RHS);
        [propput, helpcontext(0x000103cf)]
        HRESULT _stdcall ReadingOrder([in] long RHS);
        [propget, helpcontext(0x000105f5)]
        HRESULT _stdcall AutoScaleFont([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x000105f5)]
        HRESULT _stdcall AutoScaleFont([in] VARIANT RHS);
    };

    [
      odl,
      uuid(000208CB-0001-0000-C000-000000000046),
      helpcontext(0x0002008a),
      hidden
    ]
    interface IPlotArea : IDispatch {
        [propget, helpcontext(0x00010094)]
        HRESULT _stdcall Application([out, retval] Application** RHS);
        [propget, helpcontext(0x00010095)]
        HRESULT _stdcall Creator([out, retval] XlCreator* RHS);
        [propget, helpcontext(0x00010096)]
        HRESULT _stdcall Parent([out, retval] IDispatch** RHS);
        [propget, helpcontext(0x0001006e)]
        HRESULT _stdcall Name([out, retval] BSTR* RHS);
        [helpcontext(0x000100eb)]
        HRESULT _stdcall Select();
        [propget, helpcontext(0x00010080)]
        HRESULT _stdcall Border([out, retval] Border** RHS);
        [helpcontext(0x00010070)]
        HRESULT _stdcall ClearFormats();
        [propget, helpcontext(0x0001007b)]
        HRESULT _stdcall Height([out, retval] double* RHS);
        [propput, helpcontext(0x0001007b)]
        HRESULT _stdcall Height([in] double RHS);
        [propget, helpcontext(0x00010081)]
        HRESULT _stdcall Interior([out, retval] Interior** RHS);
        [propget, helpcontext(0x0001067f)]
        HRESULT _stdcall Fill([out, retval] ChartFillFormat** RHS);
        [propget, helpcontext(0x0001007f)]
        HRESULT _stdcall Left([out, retval] double* RHS);
        [propput, helpcontext(0x0001007f)]
        HRESULT _stdcall Left([in] double RHS);
        [propget, helpcontext(0x0001007e)]
        HRESULT _stdcall Top([out, retval] double* RHS);
        [propput, helpcontext(0x0001007e)]
        HRESULT _stdcall Top([in] double RHS);
        [propget, helpcontext(0x0001007a)]
        HRESULT _stdcall Width([out, retval] double* RHS);
        [propput, helpcontext(0x0001007a)]
        HRESULT _stdcall Width([in] double RHS);
        [propget, helpcontext(0x00010683)]
        HRESULT _stdcall InsideLeft([out, retval] double* RHS);
        [propget, helpcontext(0x00010684)]
        HRESULT _stdcall InsideTop([out, retval] double* RHS);
        [propget, helpcontext(0x00010685)]
        HRESULT _stdcall InsideWidth([out, retval] double* RHS);
        [propget, helpcontext(0x00010686)]
        HRESULT _stdcall InsideHeight([out, retval] double* RHS);
    };

    [
      odl,
      uuid(000208CC-0001-0000-C000-000000000046),
      helpcontext(0x0002008b),
      hidden
    ]
    interface IChartArea : IDispatch {
        [propget, helpcontext(0x00010094)]
        HRESULT _stdcall Application([out, retval] Application** RHS);
        [propget, helpcontext(0x00010095)]
        HRESULT _stdcall Creator([out, retval] XlCreator* RHS);
        [propget, helpcontext(0x00010096)]
        HRESULT _stdcall Parent([out, retval] IDispatch** RHS);
        [propget, helpcontext(0x0001006e)]
        HRESULT _stdcall Name([out, retval] BSTR* RHS);
        [helpcontext(0x000100eb)]
        HRESULT _stdcall Select();
        [propget, helpcontext(0x00010080)]
        HRESULT _stdcall Border([out, retval] Border** RHS);
        [helpcontext(0x0001006f)]
        HRESULT _stdcall Clear();
        [helpcontext(0x00010071)]
        HRESULT _stdcall ClearContents();
        [helpcontext(0x00010227)]
        HRESULT _stdcall Copy();
        [propget, helpcontext(0x00010092)]
        HRESULT _stdcall Font([out, retval] Font** RHS);
        [propget, helpcontext(0x00010067)]
        HRESULT _stdcall Shadow([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010067)]
        HRESULT _stdcall Shadow([in] VARIANT_BOOL RHS);
        [helpcontext(0x00010070)]
        HRESULT _stdcall ClearFormats();
        [propget, helpcontext(0x0001007b)]
        HRESULT _stdcall Height([out, retval] double* RHS);
        [propput, helpcontext(0x0001007b)]
        HRESULT _stdcall Height([in] double RHS);
        [propget, helpcontext(0x00010081)]
        HRESULT _stdcall Interior([out, retval] Interior** RHS);
        [propget, helpcontext(0x0001067f)]
        HRESULT _stdcall Fill([out, retval] ChartFillFormat** RHS);
        [propget, helpcontext(0x0001007f)]
        HRESULT _stdcall Left([out, retval] double* RHS);
        [propput, helpcontext(0x0001007f)]
        HRESULT _stdcall Left([in] double RHS);
        [propget, helpcontext(0x0001007e)]
        HRESULT _stdcall Top([out, retval] double* RHS);
        [propput, helpcontext(0x0001007e)]
        HRESULT _stdcall Top([in] double RHS);
        [propget, helpcontext(0x0001007a)]
        HRESULT _stdcall Width([out, retval] double* RHS);
        [propput, helpcontext(0x0001007a)]
        HRESULT _stdcall Width([in] double RHS);
        [propget, helpcontext(0x000105f5)]
        HRESULT _stdcall AutoScaleFont([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x000105f5)]
        HRESULT _stdcall AutoScaleFont([in] VARIANT RHS);
    };

    [
      odl,
      uuid(000208CD-0001-0000-C000-000000000046),
      helpcontext(0x0002008c),
      hidden
    ]
    interface ILegend : IDispatch {
        [propget, helpcontext(0x00010094)]
        HRESULT _stdcall Application([out, retval] Application** RHS);
        [propget, helpcontext(0x00010095)]
        HRESULT _stdcall Creator([out, retval] XlCreator* RHS);
        [propget, helpcontext(0x00010096)]
        HRESULT _stdcall Parent([out, retval] IDispatch** RHS);
        [propget, helpcontext(0x0001006e)]
        HRESULT _stdcall Name([out, retval] BSTR* RHS);
        [helpcontext(0x000100eb)]
        HRESULT _stdcall Select();
        [propget, helpcontext(0x00010080)]
        HRESULT _stdcall Border([out, retval] Border** RHS);
        [helpcontext(0x00010075)]
        HRESULT _stdcall Delete();
        [propget, helpcontext(0x00010092)]
        HRESULT _stdcall Font([out, retval] Font** RHS);
        [helpcontext(0x000100ad)]
        HRESULT _stdcall LegendEntries(
                        [in, optional] VARIANT Index, 
                        [out, retval] IDispatch** RHS);
        [propget, helpcontext(0x00010085)]
        HRESULT _stdcall Position([out, retval] XlLegendPosition* RHS);
        [propput, helpcontext(0x00010085)]
        HRESULT _stdcall Position([in] XlLegendPosition RHS);
        [propget, helpcontext(0x00010067)]
        HRESULT _stdcall Shadow([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010067)]
        HRESULT _stdcall Shadow([in] VARIANT_BOOL RHS);
        [helpcontext(0x0001006f)]
        HRESULT _stdcall Clear();
        [propget, helpcontext(0x0001007b)]
        HRESULT _stdcall Height([out, retval] double* RHS);
        [propput, helpcontext(0x0001007b)]
        HRESULT _stdcall Height([in] double RHS);
        [propget, helpcontext(0x00010081)]
        HRESULT _stdcall Interior([out, retval] Interior** RHS);
        [propget, helpcontext(0x0001067f)]
        HRESULT _stdcall Fill([out, retval] ChartFillFormat** RHS);
        [propget, helpcontext(0x0001007f)]
        HRESULT _stdcall Left([out, retval] double* RHS);
        [propput, helpcontext(0x0001007f)]
        HRESULT _stdcall Left([in] double RHS);
        [propget, helpcontext(0x0001007e)]
        HRESULT _stdcall Top([out, retval] double* RHS);
        [propput, helpcontext(0x0001007e)]
        HRESULT _stdcall Top([in] double RHS);
        [propget, helpcontext(0x0001007a)]
        HRESULT _stdcall Width([out, retval] double* RHS);
        [propput, helpcontext(0x0001007a)]
        HRESULT _stdcall Width([in] double RHS);
        [propget, helpcontext(0x000105f5)]
        HRESULT _stdcall AutoScaleFont([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x000105f5)]
        HRESULT _stdcall AutoScaleFont([in] VARIANT RHS);
    };
