import "Excel18.Idl";

    [
      uuid(0002441E-0000-0000-C000-000000000046),
      helpcontext(0x000200b4)
    ]
    dispinterface PivotFormula {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x00000075), helpcontext(0x00010075)]
            void Delete();
            [id(00000000), propget, helpcontext(0x00010000)]
            BSTR _Default();
            [id(00000000), propput, helpcontext(0x00010000)]
            void _Default([in] BSTR rhs);
            [id(0x00000105), propget, helpcontext(0x00010105)]
            BSTR Formula();
            [id(0x00000105), propput, helpcontext(0x00010105)]
            void Formula([in] BSTR rhs);
            [id(0x00000006), propget, helpcontext(0x00010006)]
            BSTR Value();
            [id(0x00000006), propput, helpcontext(0x00010006)]
            void Value([in] BSTR rhs);
            [id(0x000001e6), propget, helpcontext(0x000101e6)]
            long Index();
            [id(0x000001e6), propput, helpcontext(0x000101e6)]
            void Index([in] long rhs);
    };

    [
      uuid(0002441F-0000-0000-C000-000000000046),
      helpcontext(0x000200b5)
    ]
    dispinterface PivotFormulas {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x00000076), propget, helpcontext(0x00010076)]
            long Count();
            [id(0x000000b5), helpcontext(0x000100b5)]
            PivotFormula* Add([in] BSTR Formula);
            [id(0x000000aa), helpcontext(0x000100aa)]
            PivotFormula* Item([in] VARIANT Index);
            [id(00000000), propget, helpcontext(0x00010000)]
            PivotFormula* _Default([in] VARIANT Index);
            [id(0xfffffffc), helpcontext(0x0000fffc)]
            IUnknown* _NewEnum();
    };

    [
      uuid(00020872-0000-0000-C000-000000000046),
      helpcontext(0x00020032)
    ]
    dispinterface PivotTable {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x000002c4), helpcontext(0x000102c4)]
            void AddFields(
                            [in, optional] VARIANT RowFields, 
                            [in, optional] VARIANT ColumnFields, 
                            [in, optional] VARIANT PageFields, 
                            [in, optional] VARIANT AddToTable);
            [id(0x000002c9), propget, helpcontext(0x000102c9)]
            IDispatch* ColumnFields([in, optional] VARIANT Index);
            [id(0x000002b6), propget, helpcontext(0x000102b6)]
            VARIANT_BOOL ColumnGrand();
            [id(0x000002b6), propput, helpcontext(0x000102b6)]
            void ColumnGrand([in] VARIANT_BOOL rhs);
            [id(0x000002be), propget, helpcontext(0x000102be)]
            Range* ColumnRange();
            [id(0x000002c2), helpcontext(0x000102c2)]
            void ShowPages([in, optional] VARIANT PageField);
            [id(0x000002c1), propget, helpcontext(0x000102c1)]
            Range* DataBodyRange();
            [id(0x000002cb), propget, helpcontext(0x000102cb)]
            IDispatch* DataFields([in, optional] VARIANT Index);
            [id(0x000002c0), propget, helpcontext(0x000102c0)]
            Range* DataLabelRange();
            [id(00000000), propget, helpcontext(0x00010000)]
            BSTR _Default();
            [id(00000000), propput, helpcontext(0x00010000)]
            void _Default([in] BSTR rhs);
            [id(0x000002b7), propget, helpcontext(0x000102b7)]
            VARIANT_BOOL HasAutoFormat();
            [id(0x000002b7), propput, helpcontext(0x000102b7)]
            void HasAutoFormat([in] VARIANT_BOOL rhs);
            [id(0x000002c7), propget, helpcontext(0x000102c7)]
            IDispatch* HiddenFields([in, optional] VARIANT Index);
            [id(0x000002ba), propget, helpcontext(0x000102ba)]
            BSTR InnerDetail();
            [id(0x000002ba), propput, helpcontext(0x000102ba)]
            void InnerDetail([in] BSTR rhs);
            [id(0x0000006e), propget, helpcontext(0x0001006e)]
            BSTR Name();
            [id(0x0000006e), propput, helpcontext(0x0001006e)]
            void Name([in] BSTR rhs);
            [id(0x000002ca), propget, helpcontext(0x000102ca)]
            IDispatch* PageFields([in, optional] VARIANT Index);
            [id(0x000002bf), propget, helpcontext(0x000102bf)]
            Range* PageRange();
            [id(0x000005ca), propget, helpcontext(0x000105ca)]
            Range* PageRangeCells();
            [id(0x000002ce), helpcontext(0x000102ce)]
            IDispatch* PivotFields([in, optional] VARIANT Index);
            [id(0x000002b8), propget, helpcontext(0x000102b8)]
            DATE RefreshDate();
            [id(0x000002b9), propget, helpcontext(0x000102b9)]
            BSTR RefreshName();
            [id(0x000002cd), helpcontext(0x000102cd)]
            VARIANT_BOOL RefreshTable();
            [id(0x000002c8), propget, helpcontext(0x000102c8)]
            IDispatch* RowFields([in, optional] VARIANT Index);
            [id(0x000002b5), propget, helpcontext(0x000102b5)]
            VARIANT_BOOL RowGrand();
            [id(0x000002b5), propput, helpcontext(0x000102b5)]
            void RowGrand([in] VARIANT_BOOL rhs);
            [id(0x000002bd), propget, helpcontext(0x000102bd)]
            Range* RowRange();
            [id(0x000002b4), propget, helpcontext(0x000102b4)]
            VARIANT_BOOL SaveData();
            [id(0x000002b4), propput, helpcontext(0x000102b4)]
            void SaveData([in] VARIANT_BOOL rhs);
            [id(0x000002ae), propget, helpcontext(0x000102ae)]
            VARIANT SourceData();
            [id(0x000002ae), propput, helpcontext(0x000102ae)]
            void SourceData([in] VARIANT rhs);
            [id(0x000002bb), propget, helpcontext(0x000102bb)]
            Range* TableRange1();
            [id(0x000002bc), propget, helpcontext(0x000102bc)]
            Range* TableRange2();
            [id(0x00000006), propget, helpcontext(0x00010006)]
            BSTR Value();
            [id(0x00000006), propput, helpcontext(0x00010006)]
            void Value([in] BSTR rhs);
            [id(0x000002c6), propget, helpcontext(0x000102c6)]
            IDispatch* VisibleFields([in, optional] VARIANT Index);
            [id(0x000005cb), propget, helpcontext(0x000105cb)]
            long CacheIndex();
            [id(0x000005cb), propput, helpcontext(0x000105cb)]
            void CacheIndex([in] long rhs);
            [id(0x000005cc), helpcontext(0x000105cc)]
            CalculatedFields* CalculatedFields();
            [id(0x000005cd), propget, helpcontext(0x000105cd)]
            VARIANT_BOOL DisplayErrorString();
            [id(0x000005cd), propput, helpcontext(0x000105cd)]
            void DisplayErrorString([in] VARIANT_BOOL rhs);
            [id(0x000005ce), propget, helpcontext(0x000105ce)]
            VARIANT_BOOL DisplayNullString();
            [id(0x000005ce), propput, helpcontext(0x000105ce)]
            void DisplayNullString([in] VARIANT_BOOL rhs);
            [id(0x000005cf), propget, helpcontext(0x000105cf)]
            VARIANT_BOOL EnableDrilldown();
            [id(0x000005cf), propput, helpcontext(0x000105cf)]
            void EnableDrilldown([in] VARIANT_BOOL rhs);
            [id(0x000005d0), propget, helpcontext(0x000105d0)]
            VARIANT_BOOL EnableFieldDialog();
            [id(0x000005d0), propput, helpcontext(0x000105d0)]
            void EnableFieldDialog([in] VARIANT_BOOL rhs);
            [id(0x000005d1), propget, helpcontext(0x000105d1)]
            VARIANT_BOOL EnableWizard();
            [id(0x000005d1), propput, helpcontext(0x000105d1)]
            void EnableWizard([in] VARIANT_BOOL rhs);
            [id(0x000005d2), propget, helpcontext(0x000105d2)]
            BSTR ErrorString();
            [id(0x000005d2), propput, helpcontext(0x000105d2)]
            void ErrorString([in] BSTR rhs);
            [id(0x000005d3), helpcontext(0x000105d3)]
            double GetData([in] BSTR Name);
            [id(0x000005d4), helpcontext(0x000105d4)]
            void ListFormulas();
            [id(0x000005d5), propget, helpcontext(0x000105d5)]
            VARIANT_BOOL ManualUpdate();
            [id(0x000005d5), propput, helpcontext(0x000105d5)]
            void ManualUpdate([in] VARIANT_BOOL rhs);
            [id(0x000005d6), propget, helpcontext(0x000105d6)]
            VARIANT_BOOL MergeLabels();
            [id(0x000005d6), propput, helpcontext(0x000105d6)]
            void MergeLabels([in] VARIANT_BOOL rhs);
            [id(0x000005d7), propget, helpcontext(0x000105d7)]
            BSTR NullString();
            [id(0x000005d7), propput, helpcontext(0x000105d7)]
            void NullString([in] BSTR rhs);
            [id(0x000005d8), helpcontext(0x000105d8)]
            PivotCache* PivotCache();
            [id(0x000005d9), helpcontext(0x000105d9)]
            PivotFormulas* PivotFormulas();
            [id(0x000002ac), helpcontext(0x000102ac)]
            void PivotTableWizard(
                            [in, optional] VARIANT SourceType, 
                            [in, optional] VARIANT SourceData, 
                            [in, optional] VARIANT TableDestination, 
                            [in, optional] VARIANT TableName, 
                            [in, optional] VARIANT RowGrand, 
                            [in, optional] VARIANT ColumnGrand, 
                            [in, optional] VARIANT SaveData, 
                            [in, optional] VARIANT HasAutoFormat, 
                            [in, optional] VARIANT AutoPage, 
                            [in, optional] VARIANT Reserved, 
                            [in, optional] VARIANT BackgroundQuery, 
                            [in, optional] VARIANT OptimizeCache, 
                            [in, optional] VARIANT PageFieldOrder, 
                            [in, optional] VARIANT PageFieldWrapCount, 
                            [in, optional] VARIANT ReadData, 
                            [in, optional] VARIANT Connection);
            [id(0x000005da), propget, helpcontext(0x000105da)]
            VARIANT_BOOL SubtotalHiddenPageItems();
            [id(0x000005da), propput, helpcontext(0x000105da)]
            void SubtotalHiddenPageItems([in] VARIANT_BOOL rhs);
            [id(0x00000595), propget, helpcontext(0x00010595)]
            long PageFieldOrder();
            [id(0x00000595), propput, helpcontext(0x00010595)]
            void PageFieldOrder([in] long rhs);
            [id(0x000005db), propget, helpcontext(0x000105db)]
            BSTR PageFieldStyle();
            [id(0x000005db), propput, helpcontext(0x000105db)]
            void PageFieldStyle([in] BSTR rhs);
            [id(0x00000596), propget, helpcontext(0x00010596)]
            long PageFieldWrapCount();
            [id(0x00000596), propput, helpcontext(0x00010596)]
            void PageFieldWrapCount([in] long rhs);
            [id(0x000005dc), propget, helpcontext(0x000105dc)]
            VARIANT_BOOL PreserveFormatting();
            [id(0x000005dc), propput, helpcontext(0x000105dc)]
            void PreserveFormatting([in] VARIANT_BOOL rhs);
            [id(0x000005dd), helpcontext(0x000105dd)]
            void PivotSelect(
                            [in] BSTR Name, 
                            [in] XlPTSelectionMode Mode);
            [id(0x000005de), propget, helpcontext(0x000105de)]
            BSTR PivotSelection();
            [id(0x000005de), propput, helpcontext(0x000105de)]
            void PivotSelection([in] BSTR rhs);
            [id(0x000005df), propget, helpcontext(0x000105df)]
            XlPTSelectionMode SelectionMode();
            [id(0x000005df), propput, helpcontext(0x000105df)]
            void SelectionMode([in] XlPTSelectionMode rhs);
            [id(0x000005e0), propget, helpcontext(0x000105e0)]
            BSTR TableStyle();
            [id(0x000005e0), propput, helpcontext(0x000105e0)]
            void TableStyle([in] BSTR rhs);
            [id(0x000005e1), propget, helpcontext(0x000105e1)]
            BSTR Tag();
            [id(0x000005e1), propput, helpcontext(0x000105e1)]
            void Tag([in] BSTR rhs);
            [id(0x000002a8), helpcontext(0x000102a8)]
            void Update();
            [id(0x000005e2), propget, helpcontext(0x000105e2)]
            BSTR VacatedStyle();
            [id(0x000005e2), propput, helpcontext(0x000105e2)]
            void VacatedStyle([in] BSTR rhs);
    };

    [
      uuid(00020873-0000-0000-C000-000000000046),
      helpcontext(0x00020033)
    ]
    dispinterface PivotTables {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x00000076), propget, helpcontext(0x00010076)]
            long Count();
            [id(0x000000aa), helpcontext(0x000100aa)]
            PivotTable* Item([in] VARIANT Index);
            [id(0xfffffffc), helpcontext(0x0000fffc)]
            IUnknown* _NewEnum();
    };

    [
      uuid(00020874-0000-0000-C000-000000000046),
      helpcontext(0x00020034)
    ]
    dispinterface PivotField {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            PivotTable* Parent();
            [id(0x0000013c), propget, helpcontext(0x0001013c)]
            XlPivotFieldCalculation Calculation();
            [id(0x0000013c), propput, helpcontext(0x0001013c)]
            void Calculation([in] XlPivotFieldCalculation rhs);
            [id(0x000002e0), propget, helpcontext(0x000102e0)]
            PivotField* ChildField();
            [id(0x000002da), propget, helpcontext(0x000102da)]
            VARIANT ChildItems([in, optional] VARIANT Index);
            [id(0x000002e2), propget, helpcontext(0x000102e2)]
            BSTR CurrentPage();
            [id(0x000002e2), propput, helpcontext(0x000102e2)]
            void CurrentPage([in] BSTR rhs);
            [id(0x000002d0), propget, helpcontext(0x000102d0)]
            Range* DataRange();
            [id(0x000002d2), propget, helpcontext(0x000102d2)]
            XlPivotFieldDataType DataType();
            [id(00000000), propget, helpcontext(0x00010000)]
            BSTR _Default();
            [id(00000000), propput, helpcontext(0x00010000)]
            void _Default([in] BSTR rhs);
            [id(0x00000383), propget, helpcontext(0x00010383)]
            XlConsolidationFunction Function();
            [id(0x00000383), propput, helpcontext(0x00010383)]
            void Function([in] XlConsolidationFunction rhs);
            [id(0x000002d3), propget, helpcontext(0x000102d3)]
            VARIANT GroupLevel();
            [id(0x000002d8), propget, helpcontext(0x000102d8)]
            VARIANT HiddenItems([in, optional] VARIANT Index);
            [id(0x000002cf), propget, helpcontext(0x000102cf)]
            Range* LabelRange();
            [id(0x0000006e), propget, helpcontext(0x0001006e)]
            BSTR Name();
            [id(0x0000006e), propput, helpcontext(0x0001006e)]
            void Name([in] BSTR rhs);
            [id(0x000000c1), propget, helpcontext(0x000100c1)]
            BSTR NumberFormat();
            [id(0x000000c1), propput, helpcontext(0x000100c1)]
            void NumberFormat([in] BSTR rhs);
            [id(0x00000086), propget, helpcontext(0x00010086)]
            XlPivotFieldOrientation Orientation();
            [id(0x00000086), propput, helpcontext(0x00010086)]
            void Orientation([in] XlPivotFieldOrientation rhs);
            [id(0x000001c4), propget, helpcontext(0x000101c4)]
            VARIANT_BOOL ShowAllItems();
            [id(0x000001c4), propput, helpcontext(0x000101c4)]
            void ShowAllItems([in] VARIANT_BOOL rhs);
            [id(0x000002dc), propget, helpcontext(0x000102dc)]
            PivotField* ParentField();
            [id(0x000002d9), propget, helpcontext(0x000102d9)]
            VARIANT ParentItems([in, optional] VARIANT Index);
            [id(0x000002e1), helpcontext(0x000102e1)]
            VARIANT PivotItems([in, optional] VARIANT Index);
            [id(0x00000085), propget, helpcontext(0x00010085)]
            VARIANT Position();
            [id(0x00000085), propput, helpcontext(0x00010085)]
            void Position([in] VARIANT rhs);
            [id(0x000002d1), propget, helpcontext(0x000102d1)]
            BSTR SourceName();
            [id(0x000002dd), helpcontext(0x000102dd)]
            VARIANT Subtotals([in, optional] VARIANT Index);
            [id(0x000002de), propget, helpcontext(0x000102de)]
            VARIANT BaseField();
            [id(0x000002de), propput, helpcontext(0x000102de)]
            void BaseField([in] VARIANT rhs);
            [id(0x000002df), propget, helpcontext(0x000102df)]
            VARIANT BaseItem();
            [id(0x000002df), propput, helpcontext(0x000102df)]
            void BaseItem([in] VARIANT rhs);
            [id(0x000002d4), propget, helpcontext(0x000102d4)]
            VARIANT TotalLevels();
            [id(0x00000006), propget, helpcontext(0x00010006)]
            BSTR Value();
            [id(0x00000006), propput, helpcontext(0x00010006)]
            void Value([in] BSTR rhs);
            [id(0x000002d7), propget, helpcontext(0x000102d7)]
            VARIANT VisibleItems([in, optional] VARIANT Index);
            [id(0x000005e3), helpcontext(0x000105e3)]
            CalculatedItems* CalculatedItems();
            [id(0x00000075), helpcontext(0x00010075)]
            void Delete();
            [id(0x000005e4), propget, helpcontext(0x000105e4)]
            VARIANT_BOOL DragToColumn();
            [id(0x000005e4), propput, helpcontext(0x000105e4)]
            void DragToColumn([in] VARIANT_BOOL rhs);
            [id(0x000005e5), propget, helpcontext(0x000105e5)]
            VARIANT_BOOL DragToHide();
            [id(0x000005e5), propput, helpcontext(0x000105e5)]
            void DragToHide([in] VARIANT_BOOL rhs);
            [id(0x000005e6), propget, helpcontext(0x000105e6)]
            VARIANT_BOOL DragToPage();
            [id(0x000005e6), propput, helpcontext(0x000105e6)]
            void DragToPage([in] VARIANT_BOOL rhs);
            [id(0x000005e7), propget, helpcontext(0x000105e7)]
            VARIANT_BOOL DragToRow();
            [id(0x000005e7), propput, helpcontext(0x000105e7)]
            void DragToRow([in] VARIANT_BOOL rhs);
            [id(0x00000105), propget, helpcontext(0x00010105)]
            BSTR Formula();
            [id(0x00000105), propput, helpcontext(0x00010105)]
            void Formula([in] BSTR rhs);
            [id(0x000005e8), propget, helpcontext(0x000105e8)]
            VARIANT_BOOL IsCalculated();
            [id(0x00000174), propget, helpcontext(0x00010174)]
            long MemoryUsed();
            [id(0x000005e9), propget, helpcontext(0x000105e9)]
            VARIANT_BOOL ServerBased();
            [id(0x000005e9), propput, helpcontext(0x000105e9)]
            void ServerBased([in] VARIANT_BOOL rhs);
            [id(0x000005ea), helpcontext(0x000105ea)]
            void AutoSort(
                            [in] long Order, 
                            [in] BSTR Field);
            [id(0x000005eb), helpcontext(0x000105eb)]
            void AutoShow(
                            [in] long Type, 
                            [in] long Range, 
                            [in] long Count, 
                            [in] BSTR Field);
            [id(0x000005ec), propget, helpcontext(0x000105ec)]
            long AutoSortOrder();
            [id(0x000005ed), propget, helpcontext(0x000105ed)]
            BSTR AutoSortField();
            [id(0x000005ee), propget, helpcontext(0x000105ee)]
            long AutoShowType();
            [id(0x000005ef), propget, helpcontext(0x000105ef)]
            long AutoShowRange();
            [id(0x000005f0), propget, helpcontext(0x000105f0)]
            long AutoShowCount();
            [id(0x000005f1), propget, helpcontext(0x000105f1)]
            BSTR AutoShowField();
    };

    [
      uuid(00020875-0000-0000-C000-000000000046),
      helpcontext(0x00020035)
    ]
    dispinterface PivotFields {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            PivotTable* Parent();
            [id(0x00000076), propget, helpcontext(0x00010076)]
            long Count();
            [id(0x000000aa), helpcontext(0x000100aa)]
            IDispatch* Item([in] VARIANT Index);
            [id(0xfffffffc), helpcontext(0x0000fffc)]
            IUnknown* _NewEnum();
    };

    [
      uuid(00024420-0000-0000-C000-000000000046),
      helpcontext(0x000200b6)
    ]
    dispinterface CalculatedFields {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x00000076), propget, helpcontext(0x00010076)]
            long Count();
            [id(0x000000b5), helpcontext(0x000100b5)]
            PivotField* Add(
                            [in] BSTR Name, 
                            [in] BSTR Formula);
            [id(0x000000aa), helpcontext(0x000100aa)]
            PivotField* Item([in] VARIANT Index);
            [id(00000000), propget, helpcontext(0x00010000)]
            PivotField* _Default([in] VARIANT Field);
            [id(0xfffffffc), helpcontext(0x0000fffc)]
            IUnknown* _NewEnum();
    };

    [
      uuid(00020876-0000-0000-C000-000000000046),
      helpcontext(0x00020036)
    ]
    dispinterface PivotItem {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            PivotField* Parent();
            [id(0x000002da), propget, helpcontext(0x000102da)]
            VARIANT ChildItems([in, optional] VARIANT Index);
            [id(0x000002d0), propget, helpcontext(0x000102d0)]
            Range* DataRange();
            [id(00000000), propget, helpcontext(0x00010000)]
            BSTR _Default();
            [id(00000000), propput, helpcontext(0x00010000)]
            void _Default([in] BSTR rhs);
            [id(0x000002cf), propget, helpcontext(0x000102cf)]
            Range* LabelRange();
            [id(0x0000006e), propget, helpcontext(0x0001006e)]
            BSTR Name();
            [id(0x0000006e), propput, helpcontext(0x0001006e)]
            void Name([in] BSTR rhs);
            [id(0x000002e5), propget, helpcontext(0x000102e5)]
            PivotItem* ParentItem();
            [id(0x000002e3), propget, helpcontext(0x000102e3)]
            VARIANT_BOOL ParentShowDetail();
            [id(0x00000085), propget, helpcontext(0x00010085)]
            long Position();
            [id(0x00000085), propput, helpcontext(0x00010085)]
            void Position([in] long rhs);
            [id(0x00000249), propget, helpcontext(0x00010249)]
            VARIANT_BOOL ShowDetail();
            [id(0x00000249), propput, helpcontext(0x00010249)]
            void ShowDetail([in] VARIANT_BOOL rhs);
            [id(0x000002d1), propget, helpcontext(0x000102d1)]
            VARIANT SourceName();
            [id(0x00000006), propget, helpcontext(0x00010006)]
            BSTR Value();
            [id(0x00000006), propput, helpcontext(0x00010006)]
            void Value([in] BSTR rhs);
            [id(0x0000022e), propget, helpcontext(0x0001022e)]
            VARIANT_BOOL Visible();
            [id(0x0000022e), propput, helpcontext(0x0001022e)]
            void Visible([in] VARIANT_BOOL rhs);
            [id(0x00000075), helpcontext(0x00010075)]
            void Delete();
            [id(0x000005e8), propget, helpcontext(0x000105e8)]
            VARIANT_BOOL IsCalculated();
            [id(0x000005c6), propget, helpcontext(0x000105c6)]
            long RecordCount();
            [id(0x00000105), propget, helpcontext(0x00010105)]
            BSTR Formula();
            [id(0x00000105), propput, helpcontext(0x00010105)]
            void Formula([in] BSTR rhs);
    };

    [
      uuid(00020877-0000-0000-C000-000000000046),
      helpcontext(0x00020037)
    ]
    dispinterface PivotItems {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            PivotField* Parent();
            [id(0x000000b5), helpcontext(0x000100b5)]
            void Add([in] BSTR Name);
            [id(0x00000076), propget, helpcontext(0x00010076)]
            long Count();
            [id(0x000000aa), helpcontext(0x000100aa)]
            IDispatch* Item([in] VARIANT Index);
            [id(0xfffffffc), helpcontext(0x0000fffc)]
            IUnknown* _NewEnum();
    };

    [
      uuid(00024421-0000-0000-C000-000000000046),
      helpcontext(0x000200b7)
    ]
    dispinterface CalculatedItems {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x00000076), propget, helpcontext(0x00010076)]
            long Count();
            [id(0x000000b5), helpcontext(0x000100b5)]
            PivotItem* Add(
                            [in] BSTR Name, 
                            [in] BSTR Formula);
            [id(0x000000aa), helpcontext(0x000100aa)]
            PivotItem* Item([in] VARIANT Index);
            [id(00000000), propget, helpcontext(0x00010000)]
            PivotItem* _Default([in] VARIANT Field);
            [id(0xfffffffc), helpcontext(0x0000fffc)]
            IUnknown* _NewEnum();
    };

    [
      uuid(00020878-0000-0000-C000-000000000046),
      helpcontext(0x00020038)
    ]
    dispinterface Characters {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x0000008b), propget, helpcontext(0x0001008b)]
            BSTR Caption();
            [id(0x0000008b), propput, helpcontext(0x0001008b)]
            void Caption([in] BSTR rhs);
            [id(0x00000076), propget, helpcontext(0x00010076)]
            long Count();
            [id(0x00000075), helpcontext(0x00010075)]
            void Delete();
            [id(0x00000092), propget, helpcontext(0x00010092)]
            Font* Font();
            [id(0x000000fc), helpcontext(0x000100fc)]
            void Insert([in] BSTR String);
            [id(0x0000008a), propget, helpcontext(0x0001008a)]
            BSTR Text();
            [id(0x0000008a), propput, helpcontext(0x0001008a)]
            void Text([in] BSTR rhs);
            [id(0x000005f2), propget, helpcontext(0x000105f2)]
            BSTR PhoneticCharacters();
            [id(0x000005f2), propput, helpcontext(0x000105f2)]
            void PhoneticCharacters([in] BSTR rhs);
    };

    [
      uuid(00020879-0000-0000-C000-000000000046),
      helpcontext(0x00020039)
    ]
    dispinterface Dialogs {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x00000076), propget, helpcontext(0x00010076)]
            long Count();
            [id(0x000000aa), propget, helpcontext(0x000100aa)]
            Dialog* Item([in] XlBuiltInDialog Index);
            [id(00000000), propget, helpcontext(0x00010000)]
            Dialog* _Default([in] XlBuiltInDialog Index);
            [id(0xfffffffc), propget, helpcontext(0x0000fffc)]
            IUnknown* _NewEnum();
    };

    [
      uuid(0002087A-0000-0000-C000-000000000046),
      helpcontext(0x0002003a)
    ]
    dispinterface Dialog {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x000001f0), helpcontext(0x000101f0)]
            VARIANT_BOOL Show(
                            [in, optional] VARIANT Arg1, 
                            [in, optional] VARIANT Arg2, 
                            [in, optional] VARIANT Arg3, 
                            [in, optional] VARIANT Arg4, 
                            [in, optional] VARIANT Arg5, 
                            [in, optional] VARIANT Arg6, 
                            [in, optional] VARIANT Arg7, 
                            [in, optional] VARIANT Arg8, 
                            [in, optional] VARIANT Arg9, 
                            [in, optional] VARIANT Arg10, 
                            [in, optional] VARIANT Arg11, 
                            [in, optional] VARIANT Arg12, 
                            [in, optional] VARIANT Arg13, 
                            [in, optional] VARIANT Arg14, 
                            [in, optional] VARIANT Arg15, 
                            [in, optional] VARIANT Arg16, 
                            [in, optional] VARIANT Arg17, 
                            [in, optional] VARIANT Arg18, 
                            [in, optional] VARIANT Arg19, 
                            [in, optional] VARIANT Arg20, 
                            [in, optional] VARIANT Arg21, 
                            [in, optional] VARIANT Arg22, 
                            [in, optional] VARIANT Arg23, 
                            [in, optional] VARIANT Arg24, 
                            [in, optional] VARIANT Arg25, 
                            [in, optional] VARIANT Arg26, 
                            [in, optional] VARIANT Arg27, 
                            [in, optional] VARIANT Arg28, 
                            [in, optional] VARIANT Arg29, 
                            [in, optional] VARIANT Arg30);
    };

    [
      uuid(0002087B-0000-0000-C000-000000000046),
      helpcontext(0x0002003b)
    ]
    dispinterface SoundNote {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x00000075), helpcontext(0x00010075)]
            void Delete();
            [id(0x00000395), helpcontext(0x00010395)]
            void Import([in] BSTR Filename);
            [id(0x00000396), helpcontext(0x00010396)]
            void Play();
            [id(0x00000397), helpcontext(0x00010397)]
            void Record();
    };

    [
      uuid(0002087D-0000-0000-C000-000000000046),
      helpcontext(0x0002003d),
      hidden
    ]
    dispinterface Button {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x00000267), propget, helpcontext(0x00010267)]
            Range* BottomRightCell();
            [id(0x0000025a), helpcontext(0x0001025a)]
            void BringToFront();
            [id(0x00000227), helpcontext(0x00010227)]
            void Copy();
            [id(0x000000d5), helpcontext(0x000100d5)]
            void CopyPicture(
                            [in, optional, defaultvalue(2)] XlPictureAppearance Appearance, 
                            [in, optional, defaultvalue(-4147)] XlCopyPictureFormat Format);
            [id(0x00000235), helpcontext(0x00010235)]
            void Cut();
            [id(0x00000075), helpcontext(0x00010075)]
            void Delete();
            [id(0x0000040f), helpcontext(0x0001040f)]
            IDispatch* Duplicate();
            [id(0x00000258), propget, helpcontext(0x00010258)]
            VARIANT_BOOL Enabled();
            [id(0x00000258), propput, helpcontext(0x00010258)]
            void Enabled([in] VARIANT_BOOL rhs);
            [id(0x0000007b), propget, helpcontext(0x0001007b)]
            double Height();
            [id(0x0000007b), propput, helpcontext(0x0001007b)]
            void Height([in] double rhs);
            [id(0x000001e6), propget, helpcontext(0x000101e6)]
            long Index();
            [id(0x0000007f), propget, helpcontext(0x0001007f)]
            double Left();
            [id(0x0000007f), propput, helpcontext(0x0001007f)]
            void Left([in] double rhs);
            [id(0x0000010d), propget, helpcontext(0x0001010d)]
            VARIANT_BOOL Locked();
            [id(0x0000010d), propput, helpcontext(0x0001010d)]
            void Locked([in] VARIANT_BOOL rhs);
            [id(0x0000006e), propget, helpcontext(0x0001006e)]
            BSTR Name();
            [id(0x0000006e), propput, helpcontext(0x0001006e)]
            void Name([in] BSTR rhs);
            [id(0x00000254), propget, hidden, helpcontext(0x00010254)]
            BSTR OnAction();
            [id(0x00000254), propput, hidden, helpcontext(0x00010254)]
            void OnAction([in] BSTR rhs);
            [id(0x00000269), propget, helpcontext(0x00010269)]
            VARIANT Placement();
            [id(0x00000269), propput, helpcontext(0x00010269)]
            void Placement([in] VARIANT rhs);
            [id(0x0000026a), propget, helpcontext(0x0001026a)]
            VARIANT_BOOL PrintObject();
            [id(0x0000026a), propput, helpcontext(0x0001026a)]
            void PrintObject([in] VARIANT_BOOL rhs);
            [id(0x000000eb), helpcontext(0x000100eb)]
            void Select([in, optional] VARIANT Replace);
            [id(0x0000025d), helpcontext(0x0001025d)]
            void SendToBack();
            [id(0x0000007e), propget, helpcontext(0x0001007e)]
            double Top();
            [id(0x0000007e), propput, helpcontext(0x0001007e)]
            void Top([in] double rhs);
            [id(0x0000026c), propget, helpcontext(0x0001026c)]
            Range* TopLeftCell();
            [id(0x0000022e), propget, helpcontext(0x0001022e)]
            VARIANT_BOOL Visible();
            [id(0x0000022e), propput, helpcontext(0x0001022e)]
            void Visible([in] VARIANT_BOOL rhs);
            [id(0x0000007a), propget, helpcontext(0x0001007a)]
            double Width();
            [id(0x0000007a), propput, helpcontext(0x0001007a)]
            void Width([in] double rhs);
            [id(0x0000026e), propget, helpcontext(0x0001026e)]
            long ZOrder();
            [id(0x000005f8), propget, helpcontext(0x000105f8)]
            ShapeRange* ShapeRange();
            [id(0x00000427), propget, helpcontext(0x00010427)]
            VARIANT_BOOL AddIndent();
            [id(0x00000427), propput, helpcontext(0x00010427)]
            void AddIndent([in] VARIANT_BOOL rhs);
            [id(0x000005f5), propget, helpcontext(0x000105f5)]
            VARIANT AutoScaleFont();
            [id(0x000005f5), propput, helpcontext(0x000105f5)]
            void AutoScaleFont([in] VARIANT rhs);
            [id(0x00000266), propget, helpcontext(0x00010266)]
            VARIANT_BOOL AutoSize();
            [id(0x00000266), propput, helpcontext(0x00010266)]
            void AutoSize([in] VARIANT_BOOL rhs);
            [id(0x0000008b), propget, helpcontext(0x0001008b)]
            BSTR Caption();
            [id(0x0000008b), propput, helpcontext(0x0001008b)]
            void Caption([in] BSTR rhs);
            [id(0x0000025b), propget, helpcontext(0x0001025b)]
            Characters* Characters(
                            [in, optional] VARIANT Start, 
                            [in, optional] VARIANT Length);
            [id(0x000001f9), helpcontext(0x000101f9)]
            void CheckSpelling(
                            [in, optional] VARIANT CustomDictionary, 
                            [in, optional] VARIANT IgnoreUppercase, 
                            [in, optional] VARIANT AlwaysSuggest, 
                            [in, optional] VARIANT IgnoreInitialAlefHamza, 
                            [in, optional] VARIANT IgnoreFinalYaa, 
                            [in, optional] VARIANT SpellScript);
            [id(0x00000092), propget, helpcontext(0x00010092)]
            Font* Font();
            [id(0x00000105), propget, helpcontext(0x00010105)]
            BSTR Formula();
            [id(0x00000105), propput, helpcontext(0x00010105)]
            void Formula([in] BSTR rhs);
            [id(0x00000088), propget, helpcontext(0x00010088)]
            VARIANT HorizontalAlignment();
            [id(0x00000088), propput, helpcontext(0x00010088)]
            void HorizontalAlignment([in] VARIANT rhs);
            [id(0x00000268), propget, helpcontext(0x00010268)]
            VARIANT_BOOL LockedText();
            [id(0x00000268), propput, helpcontext(0x00010268)]
            void LockedText([in] VARIANT_BOOL rhs);
            [id(0x00000086), propget, helpcontext(0x00010086)]
            VARIANT Orientation();
            [id(0x00000086), propput, helpcontext(0x00010086)]
            void Orientation([in] VARIANT rhs);
            [id(0x0000008a), propget, helpcontext(0x0001008a)]
            BSTR Text();
            [id(0x0000008a), propput, helpcontext(0x0001008a)]
            void Text([in] BSTR rhs);
            [id(0x00000089), propget, helpcontext(0x00010089)]
            VARIANT VerticalAlignment();
            [id(0x00000089), propput, helpcontext(0x00010089)]
            void VerticalAlignment([in] VARIANT rhs);
            [id(0x000003cf), propget, helpcontext(0x000103cf)]
            long ReadingOrder();
            [id(0x000003cf), propput, helpcontext(0x000103cf)]
            void ReadingOrder([in] long rhs);
            [id(0x0000034e), propget, helpcontext(0x0001034e)]
            VARIANT Accelerator();
            [id(0x0000034e), propput, helpcontext(0x0001034e)]
            void Accelerator([in] VARIANT rhs);
            [id(0x0000035a), propget, helpcontext(0x0001035a)]
            VARIANT_BOOL CancelButton();
            [id(0x0000035a), propput, helpcontext(0x0001035a)]
            void CancelButton([in] VARIANT_BOOL rhs);
            [id(0x00000359), propget, helpcontext(0x00010359)]
            VARIANT_BOOL DefaultButton();
            [id(0x00000359), propput, helpcontext(0x00010359)]
            void DefaultButton([in] VARIANT_BOOL rhs);
            [id(0x0000035b), propget, helpcontext(0x0001035b)]
            VARIANT_BOOL DismissButton();
            [id(0x0000035b), propput, helpcontext(0x0001035b)]
            void DismissButton([in] VARIANT_BOOL rhs);
            [id(0x0000035c), propget, helpcontext(0x0001035c)]
            VARIANT_BOOL HelpButton();
            [id(0x0000035c), propput, helpcontext(0x0001035c)]
            void HelpButton([in] VARIANT_BOOL rhs);
            [id(0x00000461), propget, helpcontext(0x00010461)]
            VARIANT PhoneticAccelerator();
            [id(0x00000461), propput, helpcontext(0x00010461)]
            void PhoneticAccelerator([in] VARIANT rhs);
    };
