import "Excel25.Idl";

    [
      uuid(0002442A-0000-0000-C000-000000000046),
      helpcontext(0x000200c0)
    ]
    dispinterface Parameter {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x000002d2), propget, helpcontext(0x000102d2)]
            XlParameterDataType DataType();
            [id(0x000002d2), propput, helpcontext(0x000102d2)]
            void DataType([in] XlParameterDataType rhs);
            [id(0x0000006c), propget, helpcontext(0x0001006c)]
            XlParameterType Type();
            [id(0x0000063f), propget, helpcontext(0x0001063f)]
            BSTR PromptString();
            [id(0x00000006), propget, helpcontext(0x00010006)]
            VARIANT Value();
            [id(0x00000640), propget, helpcontext(0x00010640)]
            Range* SourceRange();
            [id(0x0000006e), propget, helpcontext(0x0001006e)]
            BSTR Name();
            [id(0x0000006e), propput, helpcontext(0x0001006e)]
            void Name([in] BSTR rhs);
            [id(0x00000641), helpcontext(0x00010641)]
            void SetParam(
                            [in] XlParameterType Type, 
                            [in] VARIANT Value);
    };

    [
      uuid(0002442B-0000-0000-C000-000000000046),
      helpcontext(0x000200c1)
    ]
    dispinterface Parameters {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x000000b5), helpcontext(0x000100b5)]
            Parameter* Add(
                            [in] BSTR Name, 
                            [in, optional] VARIANT iDataType);
            [id(0x00000076), propget, helpcontext(0x00010076)]
            long Count();
            [id(0x000000aa), helpcontext(0x000100aa)]
            Parameter* Item([in] VARIANT Index);
            [id(00000000), propget, helpcontext(0x00010000)]
            Parameter* _Default([in] VARIANT Index);
            [id(0x00000075), helpcontext(0x00010075)]
            void Delete();
            [id(0xfffffffc), helpcontext(0x0000fffc)]
            IUnknown* _NewEnum();
    };

    [
      uuid(0002442C-0000-0000-C000-000000000046),
      helpcontext(0x000200c2)
    ]
    dispinterface ODBCError {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x00000643), propget, helpcontext(0x00010643)]
            BSTR SqlState();
            [id(0x000005d2), propget, helpcontext(0x000105d2)]
            BSTR ErrorString();
    };

    [
      uuid(0002442D-0000-0000-C000-000000000046),
      helpcontext(0x000200c3)
    ]
    dispinterface ODBCErrors {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x00000076), propget, helpcontext(0x00010076)]
            long Count();
            [id(0x000000aa), helpcontext(0x000100aa)]
            ODBCError* Item([in] long Index);
            [id(00000000), propget, helpcontext(0x00010000)]
            ODBCError* _Default([in] long Index);
            [id(0xfffffffc), helpcontext(0x0000fffc)]
            IUnknown* _NewEnum();
    };

    [
      uuid(0002442F-0000-0000-C000-000000000046),
      helpcontext(0x000200c5)
    ]
    dispinterface Validation {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x000000b5), helpcontext(0x000100b5)]
            void Add(
                            [in] XlDVType Type, 
                            [in, optional] VARIANT AlertStyle, 
                            [in, optional] VARIANT Operator, 
                            [in, optional] VARIANT Formula1, 
                            [in, optional] VARIANT Formula2);
            [id(0x00000645), propget, helpcontext(0x00010645)]
            long AlertStyle();
            [id(0x00000646), propget, helpcontext(0x00010646)]
            VARIANT_BOOL IgnoreBlank();
            [id(0x00000646), propput, helpcontext(0x00010646)]
            void IgnoreBlank([in] VARIANT_BOOL rhs);
            [id(0x00000647), propget, helpcontext(0x00010647)]
            long IMEMode();
            [id(0x00000647), propput, helpcontext(0x00010647)]
            void IMEMode([in] long rhs);
            [id(0x00000648), propget, helpcontext(0x00010648)]
            VARIANT_BOOL InCellDropdown();
            [id(0x00000648), propput, helpcontext(0x00010648)]
            void InCellDropdown([in] VARIANT_BOOL rhs);
            [id(0x00000075), helpcontext(0x00010075)]
            void Delete();
            [id(0x00000649), propget, helpcontext(0x00010649)]
            BSTR ErrorMessage();
            [id(0x00000649), propput, helpcontext(0x00010649)]
            void ErrorMessage([in] BSTR rhs);
            [id(0x0000064a), propget, helpcontext(0x0001064a)]
            BSTR ErrorTitle();
            [id(0x0000064a), propput, helpcontext(0x0001064a)]
            void ErrorTitle([in] BSTR rhs);
            [id(0x0000064b), propget, helpcontext(0x0001064b)]
            BSTR InputMessage();
            [id(0x0000064b), propput, helpcontext(0x0001064b)]
            void InputMessage([in] BSTR rhs);
            [id(0x0000064c), propget, helpcontext(0x0001064c)]
            BSTR InputTitle();
            [id(0x0000064c), propput, helpcontext(0x0001064c)]
            void InputTitle([in] BSTR rhs);
            [id(0x0000062b), propget, helpcontext(0x0001062b)]
            BSTR Formula1();
            [id(0x0000062c), propget, helpcontext(0x0001062c)]
            BSTR Formula2();
            [id(0x0000062d), helpcontext(0x0001062d)]
            void Modify(
                            [in, optional] VARIANT Type, 
                            [in, optional] VARIANT AlertStyle, 
                            [in, optional] VARIANT Operator, 
                            [in, optional] VARIANT Formula1, 
                            [in, optional] VARIANT Formula2);
            [id(0x0000031d), propget, helpcontext(0x0001031d)]
            long Operator();
            [id(0x0000064d), propget, helpcontext(0x0001064d)]
            VARIANT_BOOL ShowError();
            [id(0x0000064d), propput, helpcontext(0x0001064d)]
            void ShowError([in] VARIANT_BOOL rhs);
            [id(0x0000064e), propget, helpcontext(0x0001064e)]
            VARIANT_BOOL ShowInput();
            [id(0x0000064e), propput, helpcontext(0x0001064e)]
            void ShowInput([in] VARIANT_BOOL rhs);
            [id(0x0000006c), propget, helpcontext(0x0001006c)]
            long Type();
            [id(0x00000006), propget, helpcontext(0x00010006)]
            VARIANT_BOOL Value();
    };

    [
      uuid(00024430-0000-0000-C000-000000000046),
      helpcontext(0x000200c6)
    ]
    dispinterface Hyperlinks {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x000000b5), helpcontext(0x000100b5)]
            IDispatch* Add(
                            [in] IDispatch* Anchor, 
                            [in] BSTR Address, 
                            [in, optional] VARIANT SubAddress);
            [id(0x00000076), propget, helpcontext(0x00010076)]
            long Count();
            [id(0x000000aa), propget, helpcontext(0x000100aa)]
            Hyperlink* Item([in] VARIANT Index);
            [id(00000000), propget, helpcontext(0x00010000)]
            Hyperlink* _Default([in] VARIANT Index);
            [id(0xfffffffc), propget, helpcontext(0x0000fffc)]
            IUnknown* _NewEnum();
            [id(0x00000075), helpcontext(0x00010075)]
            void Delete();
    };

    [
      uuid(00024431-0000-0000-C000-000000000046),
      helpcontext(0x000200c7)
    ]
    dispinterface Hyperlink {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x0000006e), propget, helpcontext(0x0001006e)]
            BSTR Name();
            [id(0x000000c5), propget, helpcontext(0x000100c5)]
            Range* Range();
            [id(0x0000062e), propget, helpcontext(0x0001062e)]
            Shape* Shape();
            [id(0x000005bf), propget, helpcontext(0x000105bf)]
            BSTR SubAddress();
            [id(0x000005bf), propput, helpcontext(0x000105bf)]
            void SubAddress([in] BSTR rhs);
            [id(0x000000ec), propget, helpcontext(0x000100ec)]
            BSTR Address();
            [id(0x000000ec), propput, helpcontext(0x000100ec)]
            void Address([in] BSTR rhs);
            [id(0x0000006c), propget, helpcontext(0x0001006c)]
            long Type();
            [id(0x000005c4), helpcontext(0x000105c4)]
            void AddToFavorites();
            [id(0x00000075), helpcontext(0x00010075)]
            void Delete();
            [id(0x00000650), helpcontext(0x00010650)]
            void Follow(
                            [in, optional] VARIANT NewWindow, 
                            [in, optional] VARIANT AddHistory, 
                            [in, optional] VARIANT ExtraInfo, 
                            [in, optional] VARIANT Method, 
                            [in, optional] VARIANT HeaderInfo);
    };

    [
      uuid(00024432-0000-0000-C000-000000000046),
      helpcontext(0x000200c8)
    ]
    dispinterface AutoFilter {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x000000c5), propget, helpcontext(0x000100c5)]
            Range* Range();
            [id(0x00000651), propget, helpcontext(0x00010651)]
            Filters* Filters();
    };

    [
      uuid(00024433-0000-0000-C000-000000000046),
      helpcontext(0x000200c9)
    ]
    dispinterface Filters {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x00000076), propget, helpcontext(0x00010076)]
            long Count();
            [id(00000000), propget, helpcontext(0x00010000)]
            Filter* _Default([in] long Index);
            [id(0x000000aa), propget, helpcontext(0x000100aa)]
            Filter* Item([in] long Index);
            [id(0xfffffffc), propget, helpcontext(0x0000fffc)]
            IUnknown* _NewEnum();
    };

    [
      uuid(00024434-0000-0000-C000-000000000046),
      helpcontext(0x000200ca)
    ]
    dispinterface Filter {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x00000652), propget, helpcontext(0x00010652)]
            VARIANT_BOOL On();
            [id(0x0000031c), propget, helpcontext(0x0001031c)]
            VARIANT Criteria1();
            [id(0x0000031d), propget, helpcontext(0x0001031d)]
            XlAutoFilterOperator Operator();
            [id(0x0000031e), propget, helpcontext(0x0001031e)]
            VARIANT Criteria2();
    };

    [
      uuid(000208D4-0000-0000-C000-000000000046),
      helpcontext(0x00020093)
    ]
    dispinterface AutoCorrect {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x0000047a), helpcontext(0x0001047a)]
            void AddReplacement(
                            [in] BSTR What, 
                            [in] BSTR Replacement);
            [id(0x0000047e), propget, helpcontext(0x0001047e)]
            VARIANT_BOOL CapitalizeNamesOfDays();
            [id(0x0000047e), propput, helpcontext(0x0001047e)]
            void CapitalizeNamesOfDays([in] VARIANT_BOOL rhs);
            [id(0x0000047b), helpcontext(0x0001047b)]
            void DeleteReplacement([in] BSTR What);
            [id(0x0000047f), helpcontext(0x0001047f)]
            VARIANT ReplacementList([in, optional] VARIANT Index);
            [id(0x0000047c), propget, helpcontext(0x0001047c)]
            VARIANT_BOOL ReplaceText();
            [id(0x0000047c), propput, helpcontext(0x0001047c)]
            void ReplaceText([in] VARIANT_BOOL rhs);
            [id(0x0000047d), propget, helpcontext(0x0001047d)]
            VARIANT_BOOL TwoInitialCapitals();
            [id(0x0000047d), propput, helpcontext(0x0001047d)]
            void TwoInitialCapitals([in] VARIANT_BOOL rhs);
            [id(0x00000653), propget, helpcontext(0x00010653)]
            VARIANT_BOOL CorrectSentenceCap();
            [id(0x00000653), propput, helpcontext(0x00010653)]
            void CorrectSentenceCap([in] VARIANT_BOOL rhs);
            [id(0x00000654), propget, helpcontext(0x00010654)]
            VARIANT_BOOL CorrectCapsLock();
            [id(0x00000654), propput, helpcontext(0x00010654)]
            void CorrectCapsLock([in] VARIANT_BOOL rhs);
    };

    [
      uuid(00020854-0000-0000-C000-000000000046),
      helpcontext(0x00020014)
    ]
    dispinterface Border {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x00000063), propget, helpcontext(0x00010063)]
            VARIANT Color();
            [id(0x00000063), propput, helpcontext(0x00010063)]
            void Color([in] VARIANT rhs);
            [id(0x00000061), propget, helpcontext(0x00010061)]
            VARIANT ColorIndex();
            [id(0x00000061), propput, helpcontext(0x00010061)]
            void ColorIndex([in] VARIANT rhs);
            [id(0x00000077), propget, helpcontext(0x00010077)]
            VARIANT LineStyle();
            [id(0x00000077), propput, helpcontext(0x00010077)]
            void LineStyle([in] VARIANT rhs);
            [id(0x00000078), propget, helpcontext(0x00010078)]
            VARIANT Weight();
            [id(0x00000078), propput, helpcontext(0x00010078)]
            void Weight([in] VARIANT rhs);
    };

    [
      uuid(00020870-0000-0000-C000-000000000046),
      helpcontext(0x00020030)
    ]
    dispinterface Interior {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x00000063), propget, helpcontext(0x00010063)]
            VARIANT Color();
            [id(0x00000063), propput, helpcontext(0x00010063)]
            void Color([in] VARIANT rhs);
            [id(0x00000061), propget, helpcontext(0x00010061)]
            VARIANT ColorIndex();
            [id(0x00000061), propput, helpcontext(0x00010061)]
            void ColorIndex([in] VARIANT rhs);
            [id(0x00000084), propget, helpcontext(0x00010084)]
            VARIANT InvertIfNegative();
            [id(0x00000084), propput, helpcontext(0x00010084)]
            void InvertIfNegative([in] VARIANT rhs);
            [id(0x0000005f), propget, helpcontext(0x0001005f)]
            VARIANT Pattern();
            [id(0x0000005f), propput, helpcontext(0x0001005f)]
            void Pattern([in] VARIANT rhs);
            [id(0x00000064), propget, helpcontext(0x00010064)]
            VARIANT PatternColor();
            [id(0x00000064), propput, helpcontext(0x00010064)]
            void PatternColor([in] VARIANT rhs);
            [id(0x00000062), propget, helpcontext(0x00010062)]
            VARIANT PatternColorIndex();
            [id(0x00000062), propput, helpcontext(0x00010062)]
            void PatternColorIndex([in] VARIANT rhs);
    };

    [
      uuid(00024435-0000-0000-C000-000000000046),
      helpcontext(0x000200cb)
    ]
    dispinterface ChartFillFormat {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x00000655), helpcontext(0x00010655)]
            void OneColorGradient(
                            [in] MsoGradientStyle Style, 
                            [in] long Variant, 
                            [in] single Degree);
            [id(0x00000658), helpcontext(0x00010658)]
            void TwoColorGradient(
                            [in] MsoGradientStyle Style, 
                            [in] long Variant);
            [id(0x00000659), helpcontext(0x00010659)]
            void PresetTextured([in] MsoPresetTexture PresetTexture);
            [id(0x0000065b), helpcontext(0x0001065b)]
            void Solid();
            [id(0x0000065c), helpcontext(0x0001065c)]
            void Patterned([in] MsoPatternType Pattern);
            [id(0x0000065d), helpcontext(0x0001065d)]
            void UserPicture(
                            [in, optional] VARIANT PictureFile, 
                            [in, optional] VARIANT PictureFormat, 
                            [in, optional] VARIANT PictureStackUnit, 
                            [in, optional] VARIANT PicturePlacement);
            [id(0x00000662), helpcontext(0x00010662)]
            void UserTextured([in] BSTR TextureFile);
            [id(0x00000664), helpcontext(0x00010664)]
            void PresetGradient(
                            [in] MsoGradientStyle Style, 
                            [in] long Variant, 
                            [in] MsoPresetGradientType PresetGradientType);
            [id(0x00000666), propget, helpcontext(0x00010666)]
            ChartColorFormat* BackColor();
            [id(0x00000667), propget, helpcontext(0x00010667)]
            ChartColorFormat* ForeColor();
            [id(0x00000668), propget, helpcontext(0x00010668)]
            MsoGradientColorType GradientColorType();
            [id(0x00000669), propget, helpcontext(0x00010669)]
            single GradientDegree();
            [id(0x0000066a), propget, helpcontext(0x0001066a)]
            MsoGradientStyle GradientStyle();
            [id(0x0000066b), propget, helpcontext(0x0001066b)]
            long GradientVariant();
            [id(0x0000005f), propget, helpcontext(0x0001005f)]
            MsoPatternType Pattern();
            [id(0x00000665), propget, helpcontext(0x00010665)]
            MsoPresetGradientType PresetGradientType();
            [id(0x0000065a), propget, helpcontext(0x0001065a)]
            MsoPresetTexture PresetTexture();
            [id(0x0000066c), propget, helpcontext(0x0001066c)]
            BSTR TextureName();
            [id(0x0000066d), propget, helpcontext(0x0001066d)]
            MsoTextureType TextureType();
            [id(0x0000006c), propget, helpcontext(0x0001006c)]
            MsoFillType Type();
            [id(0x0000022e), propget, helpcontext(0x0001022e)]
            MsoTriState Visible();
            [id(0x0000022e), propput, helpcontext(0x0001022e)]
            void Visible([in] MsoTriState rhs);
    };

    [
      uuid(00024436-0000-0000-C000-000000000046),
      helpcontext(0x000200cc)
    ]
    dispinterface ChartColorFormat {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x0000066e), propget, helpcontext(0x0001066e)]
            long SchemeColor();
            [id(0x0000066e), propput, helpcontext(0x0001066e)]
            void SchemeColor([in] long rhs);
            [id(0x0000041f), propget, helpcontext(0x0001041f)]
            long RGB();
            [id(00000000), propget, helpcontext(0x00010000)]
            long _Default();
            [id(0x0000006c), propget, helpcontext(0x0001006c)]
            long Type();
    };

    [
      uuid(00020848-0000-0000-C000-000000000046),
      helpcontext(0x00020008)
    ]
    dispinterface Axis {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x0000002d), propget, helpcontext(0x0001002d)]
            VARIANT_BOOL AxisBetweenCategories();
            [id(0x0000002d), propput, helpcontext(0x0001002d)]
            void AxisBetweenCategories([in] VARIANT_BOOL rhs);
            [id(0x0000002f), propget, helpcontext(0x0001002f)]
            XlAxisGroup AxisGroup();
            [id(0x00000052), propget, helpcontext(0x00010052)]
            AxisTitle* AxisTitle();
            [id(0x00000080), propget, helpcontext(0x00010080)]
            Border* Border();
            [id(0x0000009c), propget, helpcontext(0x0001009c)]
            VARIANT CategoryNames();
            [id(0x0000009c), propput, helpcontext(0x0001009c)]
            void CategoryNames([in] VARIANT rhs);
            [id(0x0000002a), propget, helpcontext(0x0001002a)]
            XlAxisCrosses Crosses();
            [id(0x0000002a), propput, helpcontext(0x0001002a)]
            void Crosses([in] XlAxisCrosses rhs);
            [id(0x0000002b), propget, helpcontext(0x0001002b)]
            double CrossesAt();
            [id(0x0000002b), propput, helpcontext(0x0001002b)]
            void CrossesAt([in] double rhs);
            [id(0x00000075), helpcontext(0x00010075)]
            void Delete();
            [id(0x00000018), propget, helpcontext(0x00010018)]
            VARIANT_BOOL HasMajorGridlines();
            [id(0x00000018), propput, helpcontext(0x00010018)]
            void HasMajorGridlines([in] VARIANT_BOOL rhs);
            [id(0x00000019), propget, helpcontext(0x00010019)]
            VARIANT_BOOL HasMinorGridlines();
            [id(0x00000019), propput, helpcontext(0x00010019)]
            void HasMinorGridlines([in] VARIANT_BOOL rhs);
            [id(0x00000036), propget, helpcontext(0x00010036)]
            VARIANT_BOOL HasTitle();
            [id(0x00000036), propput, helpcontext(0x00010036)]
            void HasTitle([in] VARIANT_BOOL rhs);
            [id(0x00000059), propget, helpcontext(0x00010059)]
            Gridlines* MajorGridlines();
            [id(0x0000001a), propget, helpcontext(0x0001001a)]
            XlTickMark MajorTickMark();
            [id(0x0000001a), propput, helpcontext(0x0001001a)]
            void MajorTickMark([in] XlTickMark rhs);
            [id(0x00000025), propget, helpcontext(0x00010025)]
            double MajorUnit();
            [id(0x00000025), propput, helpcontext(0x00010025)]
            void MajorUnit([in] double rhs);
            [id(0x00000026), propget, helpcontext(0x00010026)]
            VARIANT_BOOL MajorUnitIsAuto();
            [id(0x00000026), propput, helpcontext(0x00010026)]
            void MajorUnitIsAuto([in] VARIANT_BOOL rhs);
            [id(0x00000023), propget, helpcontext(0x00010023)]
            double MaximumScale();
            [id(0x00000023), propput, helpcontext(0x00010023)]
            void MaximumScale([in] double rhs);
            [id(0x00000024), propget, helpcontext(0x00010024)]
            VARIANT_BOOL MaximumScaleIsAuto();
            [id(0x00000024), propput, helpcontext(0x00010024)]
            void MaximumScaleIsAuto([in] VARIANT_BOOL rhs);
            [id(0x00000021), propget, helpcontext(0x00010021)]
            double MinimumScale();
            [id(0x00000021), propput, helpcontext(0x00010021)]
            void MinimumScale([in] double rhs);
            [id(0x00000022), propget, helpcontext(0x00010022)]
            VARIANT_BOOL MinimumScaleIsAuto();
            [id(0x00000022), propput, helpcontext(0x00010022)]
            void MinimumScaleIsAuto([in] VARIANT_BOOL rhs);
            [id(0x0000005a), propget, helpcontext(0x0001005a)]
            Gridlines* MinorGridlines();
            [id(0x0000001b), propget, helpcontext(0x0001001b)]
            XlTickMark MinorTickMark();
            [id(0x0000001b), propput, helpcontext(0x0001001b)]
            void MinorTickMark([in] XlTickMark rhs);
            [id(0x00000027), propget, helpcontext(0x00010027)]
            double MinorUnit();
            [id(0x00000027), propput, helpcontext(0x00010027)]
            void MinorUnit([in] double rhs);
            [id(0x00000028), propget, helpcontext(0x00010028)]
            VARIANT_BOOL MinorUnitIsAuto();
            [id(0x00000028), propput, helpcontext(0x00010028)]
            void MinorUnitIsAuto([in] VARIANT_BOOL rhs);
            [id(0x0000002c), propget, helpcontext(0x0001002c)]
            VARIANT_BOOL ReversePlotOrder();
            [id(0x0000002c), propput, helpcontext(0x0001002c)]
            void ReversePlotOrder([in] VARIANT_BOOL rhs);
            [id(0x00000029), propget, helpcontext(0x00010029)]
            XlScaleType ScaleType();
            [id(0x00000029), propput, helpcontext(0x00010029)]
            void ScaleType([in] XlScaleType rhs);
            [id(0x000000eb), helpcontext(0x000100eb)]
            void Select();
            [id(0x0000001c), propget, helpcontext(0x0001001c)]
            XlTickLabelPosition TickLabelPosition();
            [id(0x0000001c), propput, helpcontext(0x0001001c)]
            void TickLabelPosition([in] XlTickLabelPosition rhs);
            [id(0x0000005b), propget, helpcontext(0x0001005b)]
            TickLabels* TickLabels();
            [id(0x0000001d), propget, helpcontext(0x0001001d)]
            long TickLabelSpacing();
            [id(0x0000001d), propput, helpcontext(0x0001001d)]
            void TickLabelSpacing([in] long rhs);
            [id(0x0000001f), propget, helpcontext(0x0001001f)]
            long TickMarkSpacing();
            [id(0x0000001f), propput, helpcontext(0x0001001f)]
            void TickMarkSpacing([in] long rhs);
            [id(0x0000006c), propget, helpcontext(0x0001006c)]
            XlAxisType Type();
            [id(0x0000006c), propput, helpcontext(0x0001006c)]
            void Type([in] XlAxisType rhs);
            [id(0x0000066f), propget, helpcontext(0x0001066f)]
            XlTimeUnit BaseUnit();
            [id(0x0000066f), propput, helpcontext(0x0001066f)]
            void BaseUnit([in] XlTimeUnit rhs);
            [id(0x00000670), propget, helpcontext(0x00010670)]
            VARIANT_BOOL BaseUnitIsAuto();
            [id(0x00000670), propput, helpcontext(0x00010670)]
            void BaseUnitIsAuto([in] VARIANT_BOOL rhs);
            [id(0x00000671), propget, helpcontext(0x00010671)]
            XlTimeUnit MajorUnitScale();
            [id(0x00000671), propput, helpcontext(0x00010671)]
            void MajorUnitScale([in] XlTimeUnit rhs);
            [id(0x00000672), propget, helpcontext(0x00010672)]
            XlTimeUnit MinorUnitScale();
            [id(0x00000672), propput, helpcontext(0x00010672)]
            void MinorUnitScale([in] XlTimeUnit rhs);
            [id(0x00000673), propget, helpcontext(0x00010673)]
            XlCategoryType CategoryType();
            [id(0x00000673), propput, helpcontext(0x00010673)]
            void CategoryType([in] XlCategoryType rhs);
            [id(0x0000007f), propget, helpcontext(0x0001007f)]
            double Left();
            [id(0x0000007e), propget, helpcontext(0x0001007e)]
            double Top();
            [id(0x0000007a), propget, helpcontext(0x0001007a)]
            double Width();
            [id(0x0000007b), propget, helpcontext(0x0001007b)]
            double Height();
    };

    [
      uuid(00020849-0000-0000-C000-000000000046),
      helpcontext(0x00020009)
    ]
    dispinterface ChartTitle {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x0000006e), propget, helpcontext(0x0001006e)]
            BSTR Name();
            [id(0x000000eb), helpcontext(0x000100eb)]
            void Select();
            [id(0x00000080), propget, helpcontext(0x00010080)]
            Border* Border();
            [id(0x00000075), helpcontext(0x00010075)]
            void Delete();
            [id(0x00000081), propget, helpcontext(0x00010081)]
            Interior* Interior();
            [id(0x0000067f), propget, helpcontext(0x0001067f)]
            ChartFillFormat* Fill();
            [id(0x0000008b), propget, helpcontext(0x0001008b)]
            BSTR Caption();
            [id(0x0000008b), propput, helpcontext(0x0001008b)]
            void Caption([in] BSTR rhs);
            [id(0x0000025b), propget, helpcontext(0x0001025b)]
            Characters* Characters(
                            [in, optional] VARIANT Start, 
                            [in, optional] VARIANT Length);
            [id(0x00000092), propget, helpcontext(0x00010092)]
            Font* Font();
            [id(0x00000088), propget, helpcontext(0x00010088)]
            VARIANT HorizontalAlignment();
            [id(0x00000088), propput, helpcontext(0x00010088)]
            void HorizontalAlignment([in] VARIANT rhs);
            [id(0x0000007f), propget, helpcontext(0x0001007f)]
            double Left();
            [id(0x0000007f), propput, helpcontext(0x0001007f)]
            void Left([in] double rhs);
            [id(0x00000086), propget, helpcontext(0x00010086)]
            VARIANT Orientation();
            [id(0x00000086), propput, helpcontext(0x00010086)]
            void Orientation([in] VARIANT rhs);
            [id(0x00000067), propget, helpcontext(0x00010067)]
            VARIANT_BOOL Shadow();
            [id(0x00000067), propput, helpcontext(0x00010067)]
            void Shadow([in] VARIANT_BOOL rhs);
            [id(0x0000008a), propget, helpcontext(0x0001008a)]
            BSTR Text();
            [id(0x0000008a), propput, helpcontext(0x0001008a)]
            void Text([in] BSTR rhs);
            [id(0x0000007e), propget, helpcontext(0x0001007e)]
            double Top();
            [id(0x0000007e), propput, helpcontext(0x0001007e)]
            void Top([in] double rhs);
            [id(0x00000089), propget, helpcontext(0x00010089)]
            VARIANT VerticalAlignment();
            [id(0x00000089), propput, helpcontext(0x00010089)]
            void VerticalAlignment([in] VARIANT rhs);
            [id(0x000003cf), propget, helpcontext(0x000103cf)]
            long ReadingOrder();
            [id(0x000003cf), propput, helpcontext(0x000103cf)]
            void ReadingOrder([in] long rhs);
            [id(0x000005f5), propget, helpcontext(0x000105f5)]
            VARIANT AutoScaleFont();
            [id(0x000005f5), propput, helpcontext(0x000105f5)]
            void AutoScaleFont([in] VARIANT rhs);
    };

    [
      uuid(0002084A-0000-0000-C000-000000000046),
      helpcontext(0x0002000a)
    ]
    dispinterface AxisTitle {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x0000006e), propget, helpcontext(0x0001006e)]
            BSTR Name();
            [id(0x000000eb), helpcontext(0x000100eb)]
            void Select();
            [id(0x00000080), propget, helpcontext(0x00010080)]
            Border* Border();
            [id(0x00000075), helpcontext(0x00010075)]
            void Delete();
            [id(0x00000081), propget, helpcontext(0x00010081)]
            Interior* Interior();
            [id(0x0000067f), propget, helpcontext(0x0001067f)]
            ChartFillFormat* Fill();
            [id(0x0000008b), propget, helpcontext(0x0001008b)]
            BSTR Caption();
            [id(0x0000008b), propput, helpcontext(0x0001008b)]
            void Caption([in] BSTR rhs);
            [id(0x0000025b), propget, helpcontext(0x0001025b)]
            Characters* Characters(
                            [in, optional] VARIANT Start, 
                            [in, optional] VARIANT Length);
            [id(0x00000092), propget, helpcontext(0x00010092)]
            Font* Font();
            [id(0x00000088), propget, helpcontext(0x00010088)]
            VARIANT HorizontalAlignment();
            [id(0x00000088), propput, helpcontext(0x00010088)]
            void HorizontalAlignment([in] VARIANT rhs);
            [id(0x0000007f), propget, helpcontext(0x0001007f)]
            double Left();
            [id(0x0000007f), propput, helpcontext(0x0001007f)]
            void Left([in] double rhs);
            [id(0x00000086), propget, helpcontext(0x00010086)]
            VARIANT Orientation();
            [id(0x00000086), propput, helpcontext(0x00010086)]
            void Orientation([in] VARIANT rhs);
            [id(0x00000067), propget, helpcontext(0x00010067)]
            VARIANT_BOOL Shadow();
            [id(0x00000067), propput, helpcontext(0x00010067)]
            void Shadow([in] VARIANT_BOOL rhs);
            [id(0x0000008a), propget, helpcontext(0x0001008a)]
            BSTR Text();
            [id(0x0000008a), propput, helpcontext(0x0001008a)]
            void Text([in] BSTR rhs);
            [id(0x0000007e), propget, helpcontext(0x0001007e)]
            double Top();
            [id(0x0000007e), propput, helpcontext(0x0001007e)]
            void Top([in] double rhs);
            [id(0x00000089), propget, helpcontext(0x00010089)]
            VARIANT VerticalAlignment();
            [id(0x00000089), propput, helpcontext(0x00010089)]
            void VerticalAlignment([in] VARIANT rhs);
            [id(0x000003cf), propget, helpcontext(0x000103cf)]
            long ReadingOrder();
            [id(0x000003cf), propput, helpcontext(0x000103cf)]
            void ReadingOrder([in] long rhs);
            [id(0x000005f5), propget, helpcontext(0x000105f5)]
            VARIANT AutoScaleFont();
            [id(0x000005f5), propput, helpcontext(0x000105f5)]
            void AutoScaleFont([in] VARIANT rhs);
    };

