import "Excel28.Idl";


    [
      uuid(0002443A-0000-0000-C000-000000000046),
      helpcontext(0x000200d0)
    ]
    dispinterface Shapes {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x00000076), propget, helpcontext(0x00010076)]
            long Count();
            [id(0x000000aa), helpcontext(0x000100aa)]
            Shape* Item([in] VARIANT Index);
            [id(00000000), helpcontext(0x00010000)]
            Shape* _Default([in] VARIANT Index);
            [id(0xfffffffc), propget, helpcontext(0x0000fffc)]
            IUnknown* _NewEnum();
            [id(0x000006b1), helpcontext(0x000106b1)]
            Shape* AddCallout(
                            [in] MsoCalloutType Type, 
                            [in] single Left, 
                            [in] single Top, 
                            [in] single Width, 
                            [in] single Height);
            [id(0x000006b2), helpcontext(0x000106b2)]
            Shape* AddConnector(
                            [in] MsoConnectorType Type, 
                            [in] single BeginX, 
                            [in] single BeginY, 
                            [in] single EndX, 
                            [in] single EndY);
            [id(0x000006b7), helpcontext(0x000106b7)]
            Shape* AddCurve([in] VARIANT SafeArrayOfPoints);
            [id(0x000006b9), helpcontext(0x000106b9)]
            Shape* AddLabel(
                            [in] MsoTextOrientation Orientation, 
                            [in] single Left, 
                            [in] single Top, 
                            [in] single Width, 
                            [in] single Height);
            [id(0x000006ba), helpcontext(0x000106ba)]
            Shape* AddLine(
                            [in] single BeginX, 
                            [in] single BeginY, 
                            [in] single EndX, 
                            [in] single EndY);
            [id(0x000006bb), helpcontext(0x000106bb)]
            Shape* AddPicture(
                            [in] BSTR Filename, 
                            [in] MsoTriState LinkToFile, 
                            [in] MsoTriState SaveWithDocument, 
                            [in] single Left, 
                            [in] single Top, 
                            [in] single Width, 
                            [in] single Height);
            [id(0x000006be), helpcontext(0x000106be)]
            Shape* AddPolyline([in] VARIANT SafeArrayOfPoints);
            [id(0x000006bf), helpcontext(0x000106bf)]
            Shape* AddShape(
                            [in] MsoAutoShapeType Type, 
                            [in] single Left, 
                            [in] single Top, 
                            [in] single Width, 
                            [in] single Height);
            [id(0x000006c0), helpcontext(0x000106c0)]
            Shape* AddTextEffect(
                            [in] MsoPresetTextEffect PresetTextEffect, 
                            [in] BSTR Text, 
                            [in] BSTR FontName, 
                            [in] single FontSize, 
                            [in] MsoTriState FontBold, 
                            [in] MsoTriState FontItalic, 
                            [in] single Left, 
                            [in] single Top);
            [id(0x000006c6), helpcontext(0x000106c6)]
            Shape* AddTextbox(
                            [in] MsoTextOrientation Orientation, 
                            [in] single Left, 
                            [in] single Top, 
                            [in] single Width, 
                            [in] single Height);
            [id(0x000006c7), helpcontext(0x000106c7)]
            FreeformBuilder* BuildFreeform(
                            [in] MsoEditingType EditingType, 
                            [in] single X1, 
                            [in] single Y1);
            [id(0x000000c5), propget, helpcontext(0x000100c5)]
            ShapeRange* Range([in] VARIANT Index);
            [id(0x000006c9), helpcontext(0x000106c9)]
            void SelectAll();
            [id(0x000006ca), helpcontext(0x000106ca)]
            Shape* AddFormControl(
                            [in] XlFormControl Type, 
                            [in] long Left, 
                            [in] long Top, 
                            [in] long Width, 
                            [in] long Height);
            [id(0x000006cb), helpcontext(0x000106cb)]
            Shape* AddOLEObject(
                            [in, optional] VARIANT ClassType, 
                            [in, optional] VARIANT Filename, 
                            [in, optional] VARIANT Link, 
                            [in, optional] VARIANT DisplayAsIcon, 
                            [in, optional] VARIANT IconFileName, 
                            [in, optional] VARIANT IconIndex, 
                            [in, optional] VARIANT IconLabel, 
                            [in, optional] VARIANT Left, 
                            [in, optional] VARIANT Top, 
                            [in, optional] VARIANT Width, 
                            [in, optional] VARIANT Height);
    };

    [
      uuid(0002443B-0000-0000-C000-000000000046),
      helpcontext(0x000200d1)
    ]
    dispinterface ShapeRange {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x00000076), propget, helpcontext(0x00010076)]
            long Count();
            [id(0x000000aa), helpcontext(0x000100aa)]
            Shape* Item([in] VARIANT Index);
            [id(00000000), helpcontext(0x00010000)]
            Shape* _Default([in] VARIANT Index);
            [id(0xfffffffc), propget, helpcontext(0x0000fffc)]
            IUnknown* _NewEnum();
            [id(0x000006cc), helpcontext(0x000106cc)]
            void Align(
                            [in] MsoAlignCmd AlignCmd, 
                            [in] MsoTriState RelativeTo);
            [id(0x0000068b), helpcontext(0x0001068b)]
            void Apply();
            [id(0x00000075), helpcontext(0x00010075)]
            void Delete();
            [id(0x000006ce), helpcontext(0x000106ce)]
            void Distribute(
                            [in] MsoDistributeCmd DistributeCmd, 
                            [in] MsoTriState RelativeTo);
            [id(0x0000040f), helpcontext(0x0001040f)]
            ShapeRange* Duplicate();
            [id(0x0000068c), helpcontext(0x0001068c)]
            void Flip([in] MsoFlipCmd FlipCmd);
            [id(0x0000068e), helpcontext(0x0001068e)]
            void IncrementLeft([in] single Increment);
            [id(0x00000690), helpcontext(0x00010690)]
            void IncrementRotation([in] single Increment);
            [id(0x00000691), helpcontext(0x00010691)]
            void IncrementTop([in] single Increment);
            [id(0x0000002e), helpcontext(0x0001002e)]
            Shape* Group();
            [id(0x00000692), helpcontext(0x00010692)]
            void PickUp();
            [id(0x00000693), helpcontext(0x00010693)]
            void RerouteConnections();
            [id(0x000006d0), helpcontext(0x000106d0)]
            Shape* Regroup();
            [id(0x00000694), helpcontext(0x00010694)]
            void ScaleHeight(
                            [in] single Factor, 
                            [in] MsoTriState RelativeToOriginalSize, 
                            [in, optional] VARIANT Scale);
            [id(0x00000698), helpcontext(0x00010698)]
            void ScaleWidth(
                            [in] single Factor, 
                            [in] MsoTriState RelativeToOriginalSize, 
                            [in, optional] VARIANT Scale);
            [id(0x000000eb), helpcontext(0x000100eb)]
            void Select([in, optional] VARIANT Replace);
            [id(0x00000699), helpcontext(0x00010699)]
            void SetShapesDefaultProperties();
            [id(0x000000f4), helpcontext(0x000100f4)]
            ShapeRange* Ungroup();
            [id(0x0000026e), helpcontext(0x0001026e)]
            void ZOrder([in] MsoZOrderCmd ZOrderCmd);
            [id(0x0000069b), propget, helpcontext(0x0001069b)]
            Adjustments* Adjustments();
            [id(0x0000069c), propget, helpcontext(0x0001069c)]
            TextFrame* TextFrame();
            [id(0x0000069d), propget, helpcontext(0x0001069d)]
            MsoAutoShapeType AutoShapeType();
            [id(0x0000069d), propput, helpcontext(0x0001069d)]
            void AutoShapeType([in] MsoAutoShapeType rhs);
            [id(0x0000069e), propget, helpcontext(0x0001069e)]
            CalloutFormat* Callout();
            [id(0x0000069f), propget, helpcontext(0x0001069f)]
            long ConnectionSiteCount();
            [id(0x000006a0), propget, helpcontext(0x000106a0)]
            MsoTriState Connector();
            [id(0x000006a1), propget, helpcontext(0x000106a1)]
            ConnectorFormat* ConnectorFormat();
            [id(0x0000067f), propget, helpcontext(0x0001067f)]
            FillFormat* Fill();
            [id(0x000006a2), propget, helpcontext(0x000106a2)]
            GroupShapes* GroupItems();
            [id(0x0000007b), propget, helpcontext(0x0001007b)]
            single Height();
            [id(0x0000007b), propput, helpcontext(0x0001007b)]
            void Height([in] single rhs);
            [id(0x000006a3), propget, helpcontext(0x000106a3)]
            MsoTriState HorizontalFlip();
            [id(0x0000007f), propget, helpcontext(0x0001007f)]
            single Left();
            [id(0x0000007f), propput, helpcontext(0x0001007f)]
            void Left([in] single rhs);
            [id(0x00000331), propget, helpcontext(0x00010331)]
            LineFormat* Line();
            [id(0x000006a4), propget, helpcontext(0x000106a4)]
            MsoTriState LockAspectRatio();
            [id(0x000006a4), propput, helpcontext(0x000106a4)]
            void LockAspectRatio([in] MsoTriState rhs);
            [id(0x0000006e), propget, helpcontext(0x0001006e)]
            BSTR Name();
            [id(0x0000006e), propput, helpcontext(0x0001006e)]
            void Name([in] BSTR rhs);
            [id(0x000006a5), propget, helpcontext(0x000106a5)]
            ShapeNodes* Nodes();
            [id(0x0000003b), propget, helpcontext(0x0001003b)]
            single Rotation();
            [id(0x0000003b), propput, helpcontext(0x0001003b)]
            void Rotation([in] single rhs);
            [id(0x0000065f), propget, helpcontext(0x0001065f)]
            PictureFormat* PictureFormat();
            [id(0x00000067), propget, helpcontext(0x00010067)]
            ShadowFormat* Shadow();
            [id(0x000006a6), propget, helpcontext(0x000106a6)]
            TextEffectFormat* TextEffect();
            [id(0x000006a7), propget, helpcontext(0x000106a7)]
            ThreeDFormat* ThreeD();
            [id(0x0000007e), propget, helpcontext(0x0001007e)]
            single Top();
            [id(0x0000007e), propput, helpcontext(0x0001007e)]
            void Top([in] single rhs);
            [id(0x0000006c), propget, helpcontext(0x0001006c)]
            MsoShapeType Type();
            [id(0x000006a8), propget, helpcontext(0x000106a8)]
            MsoTriState VerticalFlip();
            [id(0x0000026d), propget, helpcontext(0x0001026d)]
            VARIANT Vertices();
            [id(0x0000022e), propget, helpcontext(0x0001022e)]
            MsoTriState Visible();
            [id(0x0000022e), propput, helpcontext(0x0001022e)]
            void Visible([in] MsoTriState rhs);
            [id(0x0000007a), propget, helpcontext(0x0001007a)]
            single Width();
            [id(0x0000007a), propput, helpcontext(0x0001007a)]
            void Width([in] single rhs);
            [id(0x000006a9), propget, helpcontext(0x000106a9)]
            long ZOrderPosition();
            [id(0x000006ab), propget, helpcontext(0x000106ab)]
            MsoBlackWhiteMode BlackWhiteMode();
            [id(0x000006ab), propput, helpcontext(0x000106ab)]
            void BlackWhiteMode([in] MsoBlackWhiteMode rhs);
    };

    [
      uuid(0002443C-0000-0000-C000-000000000046),
      helpcontext(0x000200d2)
    ]
    dispinterface GroupShapes {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x00000076), propget, helpcontext(0x00010076)]
            long Count();
            [id(0x000000aa), helpcontext(0x000100aa)]
            Shape* Item([in] VARIANT Index);
            [id(00000000), helpcontext(0x00010000)]
            Shape* _Default([in] VARIANT Index);
            [id(0xfffffffc), propget, helpcontext(0x0000fffc)]
            IUnknown* _NewEnum();
    };

    [
      uuid(0002443D-0000-0000-C000-000000000046),
      helpcontext(0x000200d3)
    ]
    dispinterface TextFrame {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x000006d1), propget, helpcontext(0x000106d1)]
            single MarginBottom();
            [id(0x000006d1), propput, helpcontext(0x000106d1)]
            void MarginBottom([in] single rhs);
            [id(0x000006d2), propget, helpcontext(0x000106d2)]
            single MarginLeft();
            [id(0x000006d2), propput, helpcontext(0x000106d2)]
            void MarginLeft([in] single rhs);
            [id(0x000006d3), propget, helpcontext(0x000106d3)]
            single MarginRight();
            [id(0x000006d3), propput, helpcontext(0x000106d3)]
            void MarginRight([in] single rhs);
            [id(0x000006d4), propget, helpcontext(0x000106d4)]
            single MarginTop();
            [id(0x000006d4), propput, helpcontext(0x000106d4)]
            void MarginTop([in] single rhs);
            [id(0x00000086), propget, helpcontext(0x00010086)]
            MsoTextOrientation Orientation();
            [id(0x00000086), propput, helpcontext(0x00010086)]
            void Orientation([in] MsoTextOrientation rhs);
            [id(0x0000025b), helpcontext(0x0001025b)]
            Characters* Characters(
                            [in, optional] VARIANT Start, 
                            [in, optional] VARIANT Length);
            [id(0x00000088), propget, helpcontext(0x00010088)]
            XlHAlign HorizontalAlignment();
            [id(0x00000088), propput, helpcontext(0x00010088)]
            void HorizontalAlignment([in] XlHAlign rhs);
            [id(0x00000089), propget, helpcontext(0x00010089)]
            XlVAlign VerticalAlignment();
            [id(0x00000089), propput, helpcontext(0x00010089)]
            void VerticalAlignment([in] XlVAlign rhs);
            [id(0x00000266), propget, helpcontext(0x00010266)]
            VARIANT_BOOL AutoSize();
            [id(0x00000266), propput, helpcontext(0x00010266)]
            void AutoSize([in] VARIANT_BOOL rhs);
            [id(0x000003cf), propget, helpcontext(0x000103cf)]
            long ReadingOrder();
            [id(0x000003cf), propput, helpcontext(0x000103cf)]
            void ReadingOrder([in] long rhs);
            [id(0x000006d5), propget, helpcontext(0x000106d5)]
            VARIANT_BOOL AutoMargins();
            [id(0x000006d5), propput, helpcontext(0x000106d5)]
            void AutoMargins([in] VARIANT_BOOL rhs);
    };

    [
      uuid(0002443E-0000-0000-C000-000000000046),
      helpcontext(0x000200d4)
    ]
    dispinterface ConnectorFormat {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x000006d6), helpcontext(0x000106d6)]
            void BeginConnect(
                            [in] Shape* ConnectedShape, 
                            [in] long ConnectionSite);
            [id(0x000006d9), helpcontext(0x000106d9)]
            void BeginDisconnect();
            [id(0x000006da), helpcontext(0x000106da)]
            void EndConnect(
                            [in] Shape* ConnectedShape, 
                            [in] long ConnectionSite);
            [id(0x000006db), helpcontext(0x000106db)]
            void EndDisconnect();
            [id(0x000006dc), propget, helpcontext(0x000106dc)]
            MsoTriState BeginConnected();
            [id(0x000006dd), propget, helpcontext(0x000106dd)]
            Shape* BeginConnectedShape();
            [id(0x000006de), propget, helpcontext(0x000106de)]
            long BeginConnectionSite();
            [id(0x000006df), propget, helpcontext(0x000106df)]
            MsoTriState EndConnected();
            [id(0x000006e0), propget, helpcontext(0x000106e0)]
            Shape* EndConnectedShape();
            [id(0x000006e1), propget, helpcontext(0x000106e1)]
            long EndConnectionSite();
            [id(0x0000006c), propget, helpcontext(0x0001006c)]
            MsoConnectorType Type();
            [id(0x0000006c), propput, helpcontext(0x0001006c)]
            void Type([in] MsoConnectorType rhs);
    };

    [
      uuid(0002443F-0000-0000-C000-000000000046),
      helpcontext(0x000200d5)
    ]
    dispinterface FreeformBuilder {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x000006e2), helpcontext(0x000106e2)]
            void AddNodes(
                            [in] MsoSegmentType SegmentType, 
                            [in] MsoEditingType EditingType, 
                            [in] single X1, 
                            [in] single Y1, 
                            [in, optional] VARIANT X2, 
                            [in, optional] VARIANT Y2, 
                            [in, optional] VARIANT X3, 
                            [in, optional] VARIANT Y3);
            [id(0x000006e6), helpcontext(0x000106e6)]
            Shape* ConvertToShape();
    };

    [
      uuid(00024440-0000-0000-C000-000000000046),
      helpcontext(0x000200d6)
    ]
    dispinterface ControlFormat {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x00000353), helpcontext(0x00010353)]
            void AddItem(
                            [in] BSTR Text, 
                            [in, optional] VARIANT Index);
            [id(0x00000355), helpcontext(0x00010355)]
            void RemoveAllItems();
            [id(0x00000354), helpcontext(0x00010354)]
            void RemoveItem(
                            [in] long Index, 
                            [in, optional] VARIANT Count);
            [id(0x00000350), propget, helpcontext(0x00010350)]
            long DropDownLines();
            [id(0x00000350), propput, helpcontext(0x00010350)]
            void DropDownLines([in] long rhs);
            [id(0x00000258), propget, helpcontext(0x00010258)]
            VARIANT_BOOL Enabled();
            [id(0x00000258), propput, helpcontext(0x00010258)]
            void Enabled([in] VARIANT_BOOL rhs);
            [id(0x0000034d), propget, helpcontext(0x0001034d)]
            long LargeChange();
            [id(0x0000034d), propput, helpcontext(0x0001034d)]
            void LargeChange([in] long rhs);
            [id(0x00000422), propget, helpcontext(0x00010422)]
            BSTR LinkedCell();
            [id(0x00000422), propput, helpcontext(0x00010422)]
            void LinkedCell([in] BSTR rhs);
            [id(0x0000035d), helpcontext(0x0001035d)]
            VARIANT List([in, optional] VARIANT Index);
            [id(0x00000351), propget, helpcontext(0x00010351)]
            long ListCount();
            [id(0x00000351), propput, helpcontext(0x00010351)]
            void ListCount([in] long rhs);
            [id(0x0000034f), propget, helpcontext(0x0001034f)]
            BSTR ListFillRange();
            [id(0x0000034f), propput, helpcontext(0x0001034f)]
            void ListFillRange([in] BSTR rhs);
            [id(0x00000352), propget, helpcontext(0x00010352)]
            long ListIndex();
            [id(0x00000352), propput, helpcontext(0x00010352)]
            void ListIndex([in] long rhs);
            [id(0x00000268), propget, helpcontext(0x00010268)]
            VARIANT_BOOL LockedText();
            [id(0x00000268), propput, helpcontext(0x00010268)]
            void LockedText([in] VARIANT_BOOL rhs);
            [id(0x0000034a), propget, helpcontext(0x0001034a)]
            long Max();
            [id(0x0000034a), propput, helpcontext(0x0001034a)]
            void Max([in] long rhs);
            [id(0x0000034b), propget, helpcontext(0x0001034b)]
            long Min();
            [id(0x0000034b), propput, helpcontext(0x0001034b)]
            void Min([in] long rhs);
            [id(0x00000020), propget, helpcontext(0x00010020)]
            long MultiSelect();
            [id(0x00000020), propput, helpcontext(0x00010020)]
            void MultiSelect([in] long rhs);
            [id(0x0000026a), propget, helpcontext(0x0001026a)]
            VARIANT_BOOL PrintObject();
            [id(0x0000026a), propput, helpcontext(0x0001026a)]
            void PrintObject([in] VARIANT_BOOL rhs);
            [id(0x0000034c), propget, helpcontext(0x0001034c)]
            long SmallChange();
            [id(0x0000034c), propput, helpcontext(0x0001034c)]
            void SmallChange([in] long rhs);
            [id(00000000), propget, helpcontext(0x00010000)]
            long _Default();
            [id(00000000), propput, helpcontext(0x00010000)]
            void _Default([in] long rhs);
            [id(0x00000006), propget, helpcontext(0x00010006)]
            long Value();
            [id(0x00000006), propput, helpcontext(0x00010006)]
            void Value([in] long rhs);
    };

    [
      uuid(00024441-0000-0000-C000-000000000046),
      helpcontext(0x000200d7)
    ]
    dispinterface OLEFormat {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x00000130), helpcontext(0x00010130)]
            void Activate();
            [id(0x00000419), propget, helpcontext(0x00010419)]
            IDispatch* Object();
            [id(0x000005f3), propget, helpcontext(0x000105f3)]
            BSTR ProgId();
            [id(0x0000025e), helpcontext(0x0001025e)]
            void Verb([in, optional] VARIANT Verb);
    };

    [
      uuid(00024442-0000-0000-C000-000000000046),
      helpcontext(0x000200d8)
    ]
    dispinterface LinkFormat {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x00000418), propget, helpcontext(0x00010418)]
            VARIANT_BOOL AutoUpdate();
            [id(0x00000418), propput, helpcontext(0x00010418)]
            void AutoUpdate([in] VARIANT_BOOL rhs);
            [id(0x0000010d), propget, helpcontext(0x0001010d)]
            VARIANT_BOOL Locked();
            [id(0x0000010d), propput, helpcontext(0x0001010d)]
            void Locked([in] VARIANT_BOOL rhs);
            [id(0x000002a8), helpcontext(0x000102a8)]
            void Update();
    };

    [
      odl,
      uuid(0002442E-0001-0000-C000-000000000046),
      helpcontext(0x000200c4),
      hidden
    ]
    interface IDummy : IDispatch {
        [helpcontext(0x00010644)]
        HRESULT _stdcall _ActiveSheetOrChart();
        [helpcontext(0x0001041f)]
        HRESULT _stdcall RGB();
        [helpcontext(0x00010420)]
        HRESULT _stdcall ChDir();
        [helpcontext(0x00010475)]
        HRESULT _stdcall DoScript();
        [helpcontext(0x00010473)]
        HRESULT _stdcall DirectObject();
    };

    [
      uuid(59191DA1-EA47-11CE-A51F-00AA0061507F),
      helpcontext(0x000200be)
    ]
    coclass QueryTable {
        [default] dispinterface _QueryTable;
        [default, source] dispinterface RefreshEvents;
    };

    [
      uuid(00024500-0000-0000-C000-000000000046),
      helpcontext(0x00020001)
    ]
    coclass Application {
        [default] interface _Application;
        [default, source] dispinterface AppEvents;
    };

    [
      uuid(00020821-0000-0000-C000-000000000046),
      helpcontext(0x00020007)
    ]
    coclass Chart {
        [default] interface _Chart;
        [default, source] dispinterface ChartEvents;
    };

    [
      uuid(00020820-0000-0000-C000-000000000046),
      helpcontext(0x00020010)
    ]
    coclass Worksheet {
        [default] interface _Worksheet;
        [default, source] dispinterface DocEvents;
    };

    [
      uuid(00020812-0000-0000-C000-000000000046),
      helpcontext(0x00020016),
      appobject,
      hidden
    ]
    coclass Global {
        [default] interface _Global;
    };

    [
      uuid(00020819-0000-0000-C000-000000000046),
      helpcontext(0x00020021)
    ]
    coclass Workbook {
        [default] interface _Workbook;
        [default, source] dispinterface WorkbookEvents;
    };

    [
      uuid(00020818-0000-0000-C000-000000000046),
      helpcontext(0x00020062)
    ]
    coclass OLEObject {
        [default] dispinterface _OLEObject;
        [default, source] dispinterface OLEObjectEvents;
    };
