import "Excel19.Idl";


    [
      uuid(0002087E-0000-0000-C000-000000000046),
      helpcontext(0x0002003e),
      hidden
    ]
    dispinterface Buttons {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x00010003), restricted, hidden]
            void _Dummy3();
            [id(0x0000025a), helpcontext(0x0001025a)]
            void BringToFront();
            [id(0x00000227), helpcontext(0x00010227)]
            void Copy();
            [id(0x000000d5), helpcontext(0x000100d5)]
            void CopyPicture(
                            [in, optional, defaultvalue(2)] XlPictureAppearance Appearance, 
                            [in, optional, defaultvalue(-4147)] XlCopyPictureFormat Format);
            [id(0x00000235), helpcontext(0x00010235)]
            void Cut();
            [id(0x00000075), helpcontext(0x00010075)]
            void Delete();
            [id(0x0000040f), helpcontext(0x0001040f)]
            IDispatch* Duplicate();
            [id(0x00000258), propget, helpcontext(0x00010258)]
            VARIANT_BOOL Enabled();
            [id(0x00000258), propput, helpcontext(0x00010258)]
            void Enabled([in] VARIANT_BOOL rhs);
            [id(0x0000007b), propget, helpcontext(0x0001007b)]
            double Height();
            [id(0x0000007b), propput, helpcontext(0x0001007b)]
            void Height([in] double rhs);
            [id(0x0001000c), restricted, hidden]
            void _Dummy12();
            [id(0x0000007f), propget, helpcontext(0x0001007f)]
            double Left();
            [id(0x0000007f), propput, helpcontext(0x0001007f)]
            void Left([in] double rhs);
            [id(0x0000010d), propget, helpcontext(0x0001010d)]
            VARIANT_BOOL Locked();
            [id(0x0000010d), propput, helpcontext(0x0001010d)]
            void Locked([in] VARIANT_BOOL rhs);
            [id(0x0001000f), restricted, hidden]
            void _Dummy15();
            [id(0x00000254), propget, hidden, helpcontext(0x00010254)]
            BSTR OnAction();
            [id(0x00000254), propput, hidden, helpcontext(0x00010254)]
            void OnAction([in] BSTR rhs);
            [id(0x00000269), propget, helpcontext(0x00010269)]
            VARIANT Placement();
            [id(0x00000269), propput, helpcontext(0x00010269)]
            void Placement([in] VARIANT rhs);
            [id(0x0000026a), propget, helpcontext(0x0001026a)]
            VARIANT_BOOL PrintObject();
            [id(0x0000026a), propput, helpcontext(0x0001026a)]
            void PrintObject([in] VARIANT_BOOL rhs);
            [id(0x000000eb), helpcontext(0x000100eb)]
            void Select([in, optional] VARIANT Replace);
            [id(0x0000025d), helpcontext(0x0001025d)]
            void SendToBack();
            [id(0x0000007e), propget, helpcontext(0x0001007e)]
            double Top();
            [id(0x0000007e), propput, helpcontext(0x0001007e)]
            void Top([in] double rhs);
            [id(0x00010016), restricted, hidden]
            void _Dummy22();
            [id(0x0000022e), propget, helpcontext(0x0001022e)]
            VARIANT_BOOL Visible();
            [id(0x0000022e), propput, helpcontext(0x0001022e)]
            void Visible([in] VARIANT_BOOL rhs);
            [id(0x0000007a), propget, helpcontext(0x0001007a)]
            double Width();
            [id(0x0000007a), propput, helpcontext(0x0001007a)]
            void Width([in] double rhs);
            [id(0x0000026e), propget, helpcontext(0x0001026e)]
            long ZOrder();
            [id(0x000005f8), propget, helpcontext(0x000105f8)]
            ShapeRange* ShapeRange();
            [id(0x00000427), propget, helpcontext(0x00010427)]
            VARIANT_BOOL AddIndent();
            [id(0x00000427), propput, helpcontext(0x00010427)]
            void AddIndent([in] VARIANT_BOOL rhs);
            [id(0x000005f5), propget, helpcontext(0x000105f5)]
            VARIANT AutoScaleFont();
            [id(0x000005f5), propput, helpcontext(0x000105f5)]
            void AutoScaleFont([in] VARIANT rhs);
            [id(0x00000266), propget, helpcontext(0x00010266)]
            VARIANT_BOOL AutoSize();
            [id(0x00000266), propput, helpcontext(0x00010266)]
            void AutoSize([in] VARIANT_BOOL rhs);
            [id(0x0000008b), propget, helpcontext(0x0001008b)]
            BSTR Caption();
            [id(0x0000008b), propput, helpcontext(0x0001008b)]
            void Caption([in] BSTR rhs);
            [id(0x0000025b), propget, helpcontext(0x0001025b)]
            Characters* Characters(
                            [in, optional] VARIANT Start, 
                            [in, optional] VARIANT Length);
            [id(0x000001f9), helpcontext(0x000101f9)]
            void CheckSpelling(
                            [in, optional] VARIANT CustomDictionary, 
                            [in, optional] VARIANT IgnoreUppercase, 
                            [in, optional] VARIANT AlwaysSuggest, 
                            [in, optional] VARIANT IgnoreInitialAlefHamza, 
                            [in, optional] VARIANT IgnoreFinalYaa, 
                            [in, optional] VARIANT SpellScript);
            [id(0x00000092), propget, helpcontext(0x00010092)]
            Font* Font();
            [id(0x00000105), propget, helpcontext(0x00010105)]
            BSTR Formula();
            [id(0x00000105), propput, helpcontext(0x00010105)]
            void Formula([in] BSTR rhs);
            [id(0x00000088), propget, helpcontext(0x00010088)]
            VARIANT HorizontalAlignment();
            [id(0x00000088), propput, helpcontext(0x00010088)]
            void HorizontalAlignment([in] VARIANT rhs);
            [id(0x00000268), propget, helpcontext(0x00010268)]
            VARIANT_BOOL LockedText();
            [id(0x00000268), propput, helpcontext(0x00010268)]
            void LockedText([in] VARIANT_BOOL rhs);
            [id(0x00000086), propget, helpcontext(0x00010086)]
            VARIANT Orientation();
            [id(0x00000086), propput, helpcontext(0x00010086)]
            void Orientation([in] VARIANT rhs);
            [id(0x0000008a), propget, helpcontext(0x0001008a)]
            BSTR Text();
            [id(0x0000008a), propput, helpcontext(0x0001008a)]
            void Text([in] BSTR rhs);
            [id(0x00000089), propget, helpcontext(0x00010089)]
            VARIANT VerticalAlignment();
            [id(0x00000089), propput, helpcontext(0x00010089)]
            void VerticalAlignment([in] VARIANT rhs);
            [id(0x000003cf), propget, helpcontext(0x000103cf)]
            long ReadingOrder();
            [id(0x000003cf), propput, helpcontext(0x000103cf)]
            void ReadingOrder([in] long rhs);
            [id(0x0000034e), propget, helpcontext(0x0001034e)]
            VARIANT Accelerator();
            [id(0x0000034e), propput, helpcontext(0x0001034e)]
            void Accelerator([in] VARIANT rhs);
            [id(0x0000035a), propget, helpcontext(0x0001035a)]
            VARIANT_BOOL CancelButton();
            [id(0x0000035a), propput, helpcontext(0x0001035a)]
            void CancelButton([in] VARIANT_BOOL rhs);
            [id(0x00000359), propget, helpcontext(0x00010359)]
            VARIANT_BOOL DefaultButton();
            [id(0x00000359), propput, helpcontext(0x00010359)]
            void DefaultButton([in] VARIANT_BOOL rhs);
            [id(0x0000035b), propget, helpcontext(0x0001035b)]
            VARIANT_BOOL DismissButton();
            [id(0x0000035b), propput, helpcontext(0x0001035b)]
            void DismissButton([in] VARIANT_BOOL rhs);
            [id(0x0000035c), propget, helpcontext(0x0001035c)]
            VARIANT_BOOL HelpButton();
            [id(0x0000035c), propput, helpcontext(0x0001035c)]
            void HelpButton([in] VARIANT_BOOL rhs);
            [id(0x00000461), propget, helpcontext(0x00010461)]
            VARIANT PhoneticAccelerator();
            [id(0x00000461), propput, helpcontext(0x00010461)]
            void PhoneticAccelerator([in] VARIANT rhs);
            [id(0x000000b5), helpcontext(0x000100b5)]
            Button* Add(
                            [in] double Left, 
                            [in] double Top, 
                            [in] double Width, 
                            [in] double Height);
            [id(0x00000076), propget, helpcontext(0x00010076)]
            long Count();
            [id(0x0000002e), helpcontext(0x0001002e)]
            GroupObject* Group();
            [id(0x000000aa), helpcontext(0x000100aa)]
            IDispatch* Item([in] VARIANT Index);
            [id(0xfffffffc), helpcontext(0x0000fffc)]
            IUnknown* _NewEnum();
    };

    [
      uuid(0002087F-0000-0000-C000-000000000046),
      helpcontext(0x0002003f),
      hidden
    ]
    dispinterface CheckBox {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x00000267), propget, helpcontext(0x00010267)]
            Range* BottomRightCell();
            [id(0x0000025a), helpcontext(0x0001025a)]
            void BringToFront();
            [id(0x00000227), helpcontext(0x00010227)]
            void Copy();
            [id(0x000000d5), helpcontext(0x000100d5)]
            void CopyPicture(
                            [in, optional, defaultvalue(2)] XlPictureAppearance Appearance, 
                            [in, optional, defaultvalue(-4147)] XlCopyPictureFormat Format);
            [id(0x00000235), helpcontext(0x00010235)]
            void Cut();
            [id(0x00000075), helpcontext(0x00010075)]
            void Delete();
            [id(0x0000040f), helpcontext(0x0001040f)]
            IDispatch* Duplicate();
            [id(0x00000258), propget, helpcontext(0x00010258)]
            VARIANT_BOOL Enabled();
            [id(0x00000258), propput, helpcontext(0x00010258)]
            void Enabled([in] VARIANT_BOOL rhs);
            [id(0x0000007b), propget, helpcontext(0x0001007b)]
            double Height();
            [id(0x0000007b), propput, helpcontext(0x0001007b)]
            void Height([in] double rhs);
            [id(0x000001e6), propget, helpcontext(0x000101e6)]
            long Index();
            [id(0x0000007f), propget, helpcontext(0x0001007f)]
            double Left();
            [id(0x0000007f), propput, helpcontext(0x0001007f)]
            void Left([in] double rhs);
            [id(0x0000010d), propget, helpcontext(0x0001010d)]
            VARIANT_BOOL Locked();
            [id(0x0000010d), propput, helpcontext(0x0001010d)]
            void Locked([in] VARIANT_BOOL rhs);
            [id(0x0000006e), propget, helpcontext(0x0001006e)]
            BSTR Name();
            [id(0x0000006e), propput, helpcontext(0x0001006e)]
            void Name([in] BSTR rhs);
            [id(0x00000254), propget, hidden, helpcontext(0x00010254)]
            BSTR OnAction();
            [id(0x00000254), propput, hidden, helpcontext(0x00010254)]
            void OnAction([in] BSTR rhs);
            [id(0x00000269), propget, helpcontext(0x00010269)]
            VARIANT Placement();
            [id(0x00000269), propput, helpcontext(0x00010269)]
            void Placement([in] VARIANT rhs);
            [id(0x0000026a), propget, helpcontext(0x0001026a)]
            VARIANT_BOOL PrintObject();
            [id(0x0000026a), propput, helpcontext(0x0001026a)]
            void PrintObject([in] VARIANT_BOOL rhs);
            [id(0x000000eb), helpcontext(0x000100eb)]
            void Select([in, optional] VARIANT Replace);
            [id(0x0000025d), helpcontext(0x0001025d)]
            void SendToBack();
            [id(0x0000007e), propget, helpcontext(0x0001007e)]
            double Top();
            [id(0x0000007e), propput, helpcontext(0x0001007e)]
            void Top([in] double rhs);
            [id(0x0000026c), propget, helpcontext(0x0001026c)]
            Range* TopLeftCell();
            [id(0x0000022e), propget, helpcontext(0x0001022e)]
            VARIANT_BOOL Visible();
            [id(0x0000022e), propput, helpcontext(0x0001022e)]
            void Visible([in] VARIANT_BOOL rhs);
            [id(0x0000007a), propget, helpcontext(0x0001007a)]
            double Width();
            [id(0x0000007a), propput, helpcontext(0x0001007a)]
            void Width([in] double rhs);
            [id(0x0000026e), propget, helpcontext(0x0001026e)]
            long ZOrder();
            [id(0x000005f8), propget, helpcontext(0x000105f8)]
            ShapeRange* ShapeRange();
            [id(0x0000008b), propget, helpcontext(0x0001008b)]
            BSTR Caption();
            [id(0x0000008b), propput, helpcontext(0x0001008b)]
            void Caption([in] BSTR rhs);
            [id(0x0000025b), propget, helpcontext(0x0001025b)]
            Characters* Characters(
                            [in, optional] VARIANT Start, 
                            [in, optional] VARIANT Length);
            [id(0x000001f9), helpcontext(0x000101f9)]
            void CheckSpelling(
                            [in, optional] VARIANT CustomDictionary, 
                            [in, optional] VARIANT IgnoreUppercase, 
                            [in, optional] VARIANT AlwaysSuggest, 
                            [in, optional] VARIANT IgnoreInitialAlefHamza, 
                            [in, optional] VARIANT IgnoreFinalYaa, 
                            [in, optional] VARIANT SpellScript);
            [id(0x00000268), propget, helpcontext(0x00010268)]
            VARIANT_BOOL LockedText();
            [id(0x00000268), propput, helpcontext(0x00010268)]
            void LockedText([in] VARIANT_BOOL rhs);
            [id(0x0000008a), propget, helpcontext(0x0001008a)]
            BSTR Text();
            [id(0x0000008a), propput, helpcontext(0x0001008a)]
            void Text([in] BSTR rhs);
            [id(0x0000034e), propget, helpcontext(0x0001034e)]
            VARIANT Accelerator();
            [id(0x0000034e), propput, helpcontext(0x0001034e)]
            void Accelerator([in] VARIANT rhs);
            [id(0x00000080), propget, helpcontext(0x00010080)]
            Border* Border();
            [id(00000000), propget, helpcontext(0x00010000)]
            long _Default();
            [id(00000000), propput, helpcontext(0x00010000)]
            void _Default([in] long rhs);
            [id(0x00000462), propget, helpcontext(0x00010462)]
            VARIANT_BOOL Display3DShading();
            [id(0x00000462), propput, helpcontext(0x00010462)]
            void Display3DShading([in] VARIANT_BOOL rhs);
            [id(0x00000081), propget, helpcontext(0x00010081)]
            Interior* Interior();
            [id(0x00000422), propget, helpcontext(0x00010422)]
            BSTR LinkedCell();
            [id(0x00000422), propput, helpcontext(0x00010422)]
            void LinkedCell([in] BSTR rhs);
            [id(0x00000461), propget, helpcontext(0x00010461)]
            VARIANT PhoneticAccelerator();
            [id(0x00000461), propput, helpcontext(0x00010461)]
            void PhoneticAccelerator([in] VARIANT rhs);
            [id(0x00000006), propget, helpcontext(0x00010006)]
            VARIANT Value();
            [id(0x00000006), propput, helpcontext(0x00010006)]
            void Value([in] VARIANT rhs);
    };

    [
      uuid(00020880-0000-0000-C000-000000000046),
      helpcontext(0x00020040),
      hidden
    ]
    dispinterface CheckBoxes {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x00010003), restricted, hidden]
            void _Dummy3();
            [id(0x0000025a), helpcontext(0x0001025a)]
            void BringToFront();
            [id(0x00000227), helpcontext(0x00010227)]
            void Copy();
            [id(0x000000d5), helpcontext(0x000100d5)]
            void CopyPicture(
                            [in, optional, defaultvalue(2)] XlPictureAppearance Appearance, 
                            [in, optional, defaultvalue(-4147)] XlCopyPictureFormat Format);
            [id(0x00000235), helpcontext(0x00010235)]
            void Cut();
            [id(0x00000075), helpcontext(0x00010075)]
            void Delete();
            [id(0x0000040f), helpcontext(0x0001040f)]
            IDispatch* Duplicate();
            [id(0x00000258), propget, helpcontext(0x00010258)]
            VARIANT_BOOL Enabled();
            [id(0x00000258), propput, helpcontext(0x00010258)]
            void Enabled([in] VARIANT_BOOL rhs);
            [id(0x0000007b), propget, helpcontext(0x0001007b)]
            double Height();
            [id(0x0000007b), propput, helpcontext(0x0001007b)]
            void Height([in] double rhs);
            [id(0x0001000c), restricted, hidden]
            void _Dummy12();
            [id(0x0000007f), propget, helpcontext(0x0001007f)]
            double Left();
            [id(0x0000007f), propput, helpcontext(0x0001007f)]
            void Left([in] double rhs);
            [id(0x0000010d), propget, helpcontext(0x0001010d)]
            VARIANT_BOOL Locked();
            [id(0x0000010d), propput, helpcontext(0x0001010d)]
            void Locked([in] VARIANT_BOOL rhs);
            [id(0x0001000f), restricted, hidden]
            void _Dummy15();
            [id(0x00000254), propget, hidden, helpcontext(0x00010254)]
            BSTR OnAction();
            [id(0x00000254), propput, hidden, helpcontext(0x00010254)]
            void OnAction([in] BSTR rhs);
            [id(0x00000269), propget, helpcontext(0x00010269)]
            VARIANT Placement();
            [id(0x00000269), propput, helpcontext(0x00010269)]
            void Placement([in] VARIANT rhs);
            [id(0x0000026a), propget, helpcontext(0x0001026a)]
            VARIANT_BOOL PrintObject();
            [id(0x0000026a), propput, helpcontext(0x0001026a)]
            void PrintObject([in] VARIANT_BOOL rhs);
            [id(0x000000eb), helpcontext(0x000100eb)]
            void Select([in, optional] VARIANT Replace);
            [id(0x0000025d), helpcontext(0x0001025d)]
            void SendToBack();
            [id(0x0000007e), propget, helpcontext(0x0001007e)]
            double Top();
            [id(0x0000007e), propput, helpcontext(0x0001007e)]
            void Top([in] double rhs);
            [id(0x00010016), restricted, hidden]
            void _Dummy22();
            [id(0x0000022e), propget, helpcontext(0x0001022e)]
            VARIANT_BOOL Visible();
            [id(0x0000022e), propput, helpcontext(0x0001022e)]
            void Visible([in] VARIANT_BOOL rhs);
            [id(0x0000007a), propget, helpcontext(0x0001007a)]
            double Width();
            [id(0x0000007a), propput, helpcontext(0x0001007a)]
            void Width([in] double rhs);
            [id(0x0000026e), propget, helpcontext(0x0001026e)]
            long ZOrder();
            [id(0x000005f8), propget, helpcontext(0x000105f8)]
            ShapeRange* ShapeRange();
            [id(0x0000008b), propget, helpcontext(0x0001008b)]
            BSTR Caption();
            [id(0x0000008b), propput, helpcontext(0x0001008b)]
            void Caption([in] BSTR rhs);
            [id(0x0000025b), propget, helpcontext(0x0001025b)]
            Characters* Characters(
                            [in, optional] VARIANT Start, 
                            [in, optional] VARIANT Length);
            [id(0x000001f9), helpcontext(0x000101f9)]
            void CheckSpelling(
                            [in, optional] VARIANT CustomDictionary, 
                            [in, optional] VARIANT IgnoreUppercase, 
                            [in, optional] VARIANT AlwaysSuggest, 
                            [in, optional] VARIANT IgnoreInitialAlefHamza, 
                            [in, optional] VARIANT IgnoreFinalYaa, 
                            [in, optional] VARIANT SpellScript);
            [id(0x00000268), propget, helpcontext(0x00010268)]
            VARIANT_BOOL LockedText();
            [id(0x00000268), propput, helpcontext(0x00010268)]
            void LockedText([in] VARIANT_BOOL rhs);
            [id(0x0000008a), propget, helpcontext(0x0001008a)]
            BSTR Text();
            [id(0x0000008a), propput, helpcontext(0x0001008a)]
            void Text([in] BSTR rhs);
            [id(0x0000034e), propget, helpcontext(0x0001034e)]
            VARIANT Accelerator();
            [id(0x0000034e), propput, helpcontext(0x0001034e)]
            void Accelerator([in] VARIANT rhs);
            [id(0x00000080), propget, helpcontext(0x00010080)]
            Border* Border();
            [id(00000000), propget, helpcontext(0x00010000)]
            long _Default();
            [id(00000000), propput, helpcontext(0x00010000)]
            void _Default([in] long rhs);
            [id(0x00000462), propget, helpcontext(0x00010462)]
            VARIANT_BOOL Display3DShading();
            [id(0x00000462), propput, helpcontext(0x00010462)]
            void Display3DShading([in] VARIANT_BOOL rhs);
            [id(0x00000081), propget, helpcontext(0x00010081)]
            Interior* Interior();
            [id(0x00000422), propget, helpcontext(0x00010422)]
            BSTR LinkedCell();
            [id(0x00000422), propput, helpcontext(0x00010422)]
            void LinkedCell([in] BSTR rhs);
            [id(0x00000461), propget, helpcontext(0x00010461)]
            VARIANT PhoneticAccelerator();
            [id(0x00000461), propput, helpcontext(0x00010461)]
            void PhoneticAccelerator([in] VARIANT rhs);
            [id(0x00000006), propget, helpcontext(0x00010006)]
            VARIANT Value();
            [id(0x00000006), propput, helpcontext(0x00010006)]
            void Value([in] VARIANT rhs);
            [id(0x000000b5), helpcontext(0x000100b5)]
            CheckBox* Add(
                            [in] double Left, 
                            [in] double Top, 
                            [in] double Width, 
                            [in] double Height);
            [id(0x00000076), propget, helpcontext(0x00010076)]
            long Count();
            [id(0x0000002e), helpcontext(0x0001002e)]
            GroupObject* Group();
            [id(0x000000aa), helpcontext(0x000100aa)]
            IDispatch* Item([in] VARIANT Index);
            [id(0xfffffffc), helpcontext(0x0000fffc)]
            IUnknown* _NewEnum();
    };

    [
      uuid(00020881-0000-0000-C000-000000000046),
      helpcontext(0x00020041),
      hidden
    ]
    dispinterface OptionButton {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x00000267), propget, helpcontext(0x00010267)]
            Range* BottomRightCell();
            [id(0x0000025a), helpcontext(0x0001025a)]
            void BringToFront();
            [id(0x00000227), helpcontext(0x00010227)]
            void Copy();
            [id(0x000000d5), helpcontext(0x000100d5)]
            void CopyPicture(
                            [in, optional, defaultvalue(2)] XlPictureAppearance Appearance, 
                            [in, optional, defaultvalue(-4147)] XlCopyPictureFormat Format);
            [id(0x00000235), helpcontext(0x00010235)]
            void Cut();
            [id(0x00000075), helpcontext(0x00010075)]
            void Delete();
            [id(0x0000040f), helpcontext(0x0001040f)]
            IDispatch* Duplicate();
            [id(0x00000258), propget, helpcontext(0x00010258)]
            VARIANT_BOOL Enabled();
            [id(0x00000258), propput, helpcontext(0x00010258)]
            void Enabled([in] VARIANT_BOOL rhs);
            [id(0x0000007b), propget, helpcontext(0x0001007b)]
            double Height();
            [id(0x0000007b), propput, helpcontext(0x0001007b)]
            void Height([in] double rhs);
            [id(0x000001e6), propget, helpcontext(0x000101e6)]
            long Index();
            [id(0x0000007f), propget, helpcontext(0x0001007f)]
            double Left();
            [id(0x0000007f), propput, helpcontext(0x0001007f)]
            void Left([in] double rhs);
            [id(0x0000010d), propget, helpcontext(0x0001010d)]
            VARIANT_BOOL Locked();
            [id(0x0000010d), propput, helpcontext(0x0001010d)]
            void Locked([in] VARIANT_BOOL rhs);
            [id(0x0000006e), propget, helpcontext(0x0001006e)]
            BSTR Name();
            [id(0x0000006e), propput, helpcontext(0x0001006e)]
            void Name([in] BSTR rhs);
            [id(0x00000254), propget, hidden, helpcontext(0x00010254)]
            BSTR OnAction();
            [id(0x00000254), propput, hidden, helpcontext(0x00010254)]
            void OnAction([in] BSTR rhs);
            [id(0x00000269), propget, helpcontext(0x00010269)]
            VARIANT Placement();
            [id(0x00000269), propput, helpcontext(0x00010269)]
            void Placement([in] VARIANT rhs);
            [id(0x0000026a), propget, helpcontext(0x0001026a)]
            VARIANT_BOOL PrintObject();
            [id(0x0000026a), propput, helpcontext(0x0001026a)]
            void PrintObject([in] VARIANT_BOOL rhs);
            [id(0x000000eb), helpcontext(0x000100eb)]
            void Select([in, optional] VARIANT Replace);
            [id(0x0000025d), helpcontext(0x0001025d)]
            void SendToBack();
            [id(0x0000007e), propget, helpcontext(0x0001007e)]
            double Top();
            [id(0x0000007e), propput, helpcontext(0x0001007e)]
            void Top([in] double rhs);
            [id(0x0000026c), propget, helpcontext(0x0001026c)]
            Range* TopLeftCell();
            [id(0x0000022e), propget, helpcontext(0x0001022e)]
            VARIANT_BOOL Visible();
            [id(0x0000022e), propput, helpcontext(0x0001022e)]
            void Visible([in] VARIANT_BOOL rhs);
            [id(0x0000007a), propget, helpcontext(0x0001007a)]
            double Width();
            [id(0x0000007a), propput, helpcontext(0x0001007a)]
            void Width([in] double rhs);
            [id(0x0000026e), propget, helpcontext(0x0001026e)]
            long ZOrder();
            [id(0x000005f8), propget, helpcontext(0x000105f8)]
            ShapeRange* ShapeRange();
            [id(0x0000008b), propget, helpcontext(0x0001008b)]
            BSTR Caption();
            [id(0x0000008b), propput, helpcontext(0x0001008b)]
            void Caption([in] BSTR rhs);
            [id(0x0000025b), propget, helpcontext(0x0001025b)]
            Characters* Characters(
                            [in, optional] VARIANT Start, 
                            [in, optional] VARIANT Length);
            [id(0x000001f9), helpcontext(0x000101f9)]
            void CheckSpelling(
                            [in, optional] VARIANT CustomDictionary, 
                            [in, optional] VARIANT IgnoreUppercase, 
                            [in, optional] VARIANT AlwaysSuggest, 
                            [in, optional] VARIANT IgnoreInitialAlefHamza, 
                            [in, optional] VARIANT IgnoreFinalYaa, 
                            [in, optional] VARIANT SpellScript);
            [id(0x00000268), propget, helpcontext(0x00010268)]
            VARIANT_BOOL LockedText();
            [id(0x00000268), propput, helpcontext(0x00010268)]
            void LockedText([in] VARIANT_BOOL rhs);
            [id(0x0000008a), propget, helpcontext(0x0001008a)]
            BSTR Text();
            [id(0x0000008a), propput, helpcontext(0x0001008a)]
            void Text([in] BSTR rhs);
            [id(0x0000034e), propget, helpcontext(0x0001034e)]
            VARIANT Accelerator();
            [id(0x0000034e), propput, helpcontext(0x0001034e)]
            void Accelerator([in] VARIANT rhs);
            [id(0x00000080), propget, helpcontext(0x00010080)]
            Border* Border();
            [id(00000000), propget, helpcontext(0x00010000)]
            long _Default();
            [id(00000000), propput, helpcontext(0x00010000)]
            void _Default([in] long rhs);
            [id(0x00000462), propget, helpcontext(0x00010462)]
            VARIANT_BOOL Display3DShading();
            [id(0x00000462), propput, helpcontext(0x00010462)]
            void Display3DShading([in] VARIANT_BOOL rhs);
            [id(0x00000081), propget, helpcontext(0x00010081)]
            Interior* Interior();
            [id(0x00000422), propget, helpcontext(0x00010422)]
            BSTR LinkedCell();
            [id(0x00000422), propput, helpcontext(0x00010422)]
            void LinkedCell([in] BSTR rhs);
            [id(0x00000461), propget, helpcontext(0x00010461)]
            VARIANT PhoneticAccelerator();
            [id(0x00000461), propput, helpcontext(0x00010461)]
            void PhoneticAccelerator([in] VARIANT rhs);
            [id(0x00000006), propget, helpcontext(0x00010006)]
            VARIANT Value();
            [id(0x00000006), propput, helpcontext(0x00010006)]
            void Value([in] VARIANT rhs);
            [id(0x00000341), propget, helpcontext(0x00010341)]
            GroupBox* GroupBox();
    };

    [
      uuid(00020882-0000-0000-C000-000000000046),
      helpcontext(0x00020042),
      hidden
    ]
    dispinterface OptionButtons {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x00010003), restricted, hidden]
            void _Dummy3();
            [id(0x0000025a), helpcontext(0x0001025a)]
            void BringToFront();
            [id(0x00000227), helpcontext(0x00010227)]
            void Copy();
            [id(0x000000d5), helpcontext(0x000100d5)]
            void CopyPicture(
                            [in, optional, defaultvalue(2)] XlPictureAppearance Appearance, 
                            [in, optional, defaultvalue(-4147)] XlCopyPictureFormat Format);
            [id(0x00000235), helpcontext(0x00010235)]
            void Cut();
            [id(0x00000075), helpcontext(0x00010075)]
            void Delete();
            [id(0x0000040f), helpcontext(0x0001040f)]
            IDispatch* Duplicate();
            [id(0x00000258), propget, helpcontext(0x00010258)]
            VARIANT_BOOL Enabled();
            [id(0x00000258), propput, helpcontext(0x00010258)]
            void Enabled([in] VARIANT_BOOL rhs);
            [id(0x0000007b), propget, helpcontext(0x0001007b)]
            double Height();
            [id(0x0000007b), propput, helpcontext(0x0001007b)]
            void Height([in] double rhs);
            [id(0x0001000c), restricted, hidden]
            void _Dummy12();
            [id(0x0000007f), propget, helpcontext(0x0001007f)]
            double Left();
            [id(0x0000007f), propput, helpcontext(0x0001007f)]
            void Left([in] double rhs);
            [id(0x0000010d), propget, helpcontext(0x0001010d)]
            VARIANT_BOOL Locked();
            [id(0x0000010d), propput, helpcontext(0x0001010d)]
            void Locked([in] VARIANT_BOOL rhs);
            [id(0x0001000f), restricted, hidden]
            void _Dummy15();
            [id(0x00000254), propget, hidden, helpcontext(0x00010254)]
            BSTR OnAction();
            [id(0x00000254), propput, hidden, helpcontext(0x00010254)]
            void OnAction([in] BSTR rhs);
            [id(0x00000269), propget, helpcontext(0x00010269)]
            VARIANT Placement();
            [id(0x00000269), propput, helpcontext(0x00010269)]
            void Placement([in] VARIANT rhs);
            [id(0x0000026a), propget, helpcontext(0x0001026a)]
            VARIANT_BOOL PrintObject();
            [id(0x0000026a), propput, helpcontext(0x0001026a)]
            void PrintObject([in] VARIANT_BOOL rhs);
            [id(0x000000eb), helpcontext(0x000100eb)]
            void Select([in, optional] VARIANT Replace);
            [id(0x0000025d), helpcontext(0x0001025d)]
            void SendToBack();
            [id(0x0000007e), propget, helpcontext(0x0001007e)]
            double Top();
            [id(0x0000007e), propput, helpcontext(0x0001007e)]
            void Top([in] double rhs);
            [id(0x00010016), restricted, hidden]
            void _Dummy22();
            [id(0x0000022e), propget, helpcontext(0x0001022e)]
            VARIANT_BOOL Visible();
            [id(0x0000022e), propput, helpcontext(0x0001022e)]
            void Visible([in] VARIANT_BOOL rhs);
            [id(0x0000007a), propget, helpcontext(0x0001007a)]
            double Width();
            [id(0x0000007a), propput, helpcontext(0x0001007a)]
            void Width([in] double rhs);
            [id(0x0000026e), propget, helpcontext(0x0001026e)]
            long ZOrder();
            [id(0x000005f8), propget, helpcontext(0x000105f8)]
            ShapeRange* ShapeRange();
            [id(0x0000008b), propget, helpcontext(0x0001008b)]
            BSTR Caption();
            [id(0x0000008b), propput, helpcontext(0x0001008b)]
            void Caption([in] BSTR rhs);
            [id(0x0000025b), propget, helpcontext(0x0001025b)]
            Characters* Characters(
                            [in, optional] VARIANT Start, 
                            [in, optional] VARIANT Length);
            [id(0x000001f9), helpcontext(0x000101f9)]
            void CheckSpelling(
                            [in, optional] VARIANT CustomDictionary, 
                            [in, optional] VARIANT IgnoreUppercase, 
                            [in, optional] VARIANT AlwaysSuggest, 
                            [in, optional] VARIANT IgnoreInitialAlefHamza, 
                            [in, optional] VARIANT IgnoreFinalYaa, 
                            [in, optional] VARIANT SpellScript);
            [id(0x00000268), propget, helpcontext(0x00010268)]
            VARIANT_BOOL LockedText();
            [id(0x00000268), propput, helpcontext(0x00010268)]
            void LockedText([in] VARIANT_BOOL rhs);
            [id(0x0000008a), propget, helpcontext(0x0001008a)]
            BSTR Text();
            [id(0x0000008a), propput, helpcontext(0x0001008a)]
            void Text([in] BSTR rhs);
            [id(0x0000034e), propget, helpcontext(0x0001034e)]
            VARIANT Accelerator();
            [id(0x0000034e), propput, helpcontext(0x0001034e)]
            void Accelerator([in] VARIANT rhs);
            [id(0x00000080), propget, helpcontext(0x00010080)]
            Border* Border();
            [id(00000000), propget, helpcontext(0x00010000)]
            long _Default();
            [id(00000000), propput, helpcontext(0x00010000)]
            void _Default([in] long rhs);
            [id(0x00000462), propget, helpcontext(0x00010462)]
            VARIANT_BOOL Display3DShading();
            [id(0x00000462), propput, helpcontext(0x00010462)]
            void Display3DShading([in] VARIANT_BOOL rhs);
            [id(0x00000081), propget, helpcontext(0x00010081)]
            Interior* Interior();
            [id(0x00000422), propget, helpcontext(0x00010422)]
            BSTR LinkedCell();
            [id(0x00000422), propput, helpcontext(0x00010422)]
            void LinkedCell([in] BSTR rhs);
            [id(0x00000461), propget, helpcontext(0x00010461)]
            VARIANT PhoneticAccelerator();
            [id(0x00000461), propput, helpcontext(0x00010461)]
            void PhoneticAccelerator([in] VARIANT rhs);
            [id(0x00000006), propget, helpcontext(0x00010006)]
            VARIANT Value();
            [id(0x00000006), propput, helpcontext(0x00010006)]
            void Value([in] VARIANT rhs);
            [id(0x00000341), propget, helpcontext(0x00010341)]
            GroupBox* GroupBox();
            [id(0x000000b5), helpcontext(0x000100b5)]
            OptionButton* Add(
                            [in] double Left, 
                            [in] double Top, 
                            [in] double Width, 
                            [in] double Height);
            [id(0x00000076), propget, helpcontext(0x00010076)]
            long Count();
            [id(0x0000002e), helpcontext(0x0001002e)]
            GroupObject* Group();
            [id(0x000000aa), helpcontext(0x000100aa)]
            IDispatch* Item([in] VARIANT Index);
            [id(0xfffffffc), helpcontext(0x0000fffc)]
            IUnknown* _NewEnum();
    };

    [
      uuid(00020883-0000-0000-C000-000000000046),
      helpcontext(0x00020043),
      hidden
    ]
    dispinterface EditBox {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x00000267), propget, helpcontext(0x00010267)]
            Range* BottomRightCell();
            [id(0x0000025a), helpcontext(0x0001025a)]
            void BringToFront();
            [id(0x00000227), helpcontext(0x00010227)]
            void Copy();
            [id(0x000000d5), helpcontext(0x000100d5)]
            void CopyPicture(
                            [in, optional, defaultvalue(2)] XlPictureAppearance Appearance, 
                            [in, optional, defaultvalue(-4147)] XlCopyPictureFormat Format);
            [id(0x00000235), helpcontext(0x00010235)]
            void Cut();
            [id(0x00000075), helpcontext(0x00010075)]
            void Delete();
            [id(0x0000040f), helpcontext(0x0001040f)]
            IDispatch* Duplicate();
            [id(0x00000258), propget, helpcontext(0x00010258)]
            VARIANT_BOOL Enabled();
            [id(0x00000258), propput, helpcontext(0x00010258)]
            void Enabled([in] VARIANT_BOOL rhs);
            [id(0x0000007b), propget, helpcontext(0x0001007b)]
            double Height();
            [id(0x0000007b), propput, helpcontext(0x0001007b)]
            void Height([in] double rhs);
            [id(0x000001e6), propget, helpcontext(0x000101e6)]
            long Index();
            [id(0x0000007f), propget, helpcontext(0x0001007f)]
            double Left();
            [id(0x0000007f), propput, helpcontext(0x0001007f)]
            void Left([in] double rhs);
            [id(0x0000010d), propget, helpcontext(0x0001010d)]
            VARIANT_BOOL Locked();
            [id(0x0000010d), propput, helpcontext(0x0001010d)]
            void Locked([in] VARIANT_BOOL rhs);
            [id(0x0000006e), propget, helpcontext(0x0001006e)]
            BSTR Name();
            [id(0x0000006e), propput, helpcontext(0x0001006e)]
            void Name([in] BSTR rhs);
            [id(0x00000254), propget, hidden, helpcontext(0x00010254)]
            BSTR OnAction();
            [id(0x00000254), propput, hidden, helpcontext(0x00010254)]
            void OnAction([in] BSTR rhs);
            [id(0x00000269), propget, helpcontext(0x00010269)]
            VARIANT Placement();
            [id(0x00000269), propput, helpcontext(0x00010269)]
            void Placement([in] VARIANT rhs);
            [id(0x0000026a), propget, helpcontext(0x0001026a)]
            VARIANT_BOOL PrintObject();
            [id(0x0000026a), propput, helpcontext(0x0001026a)]
            void PrintObject([in] VARIANT_BOOL rhs);
            [id(0x000000eb), helpcontext(0x000100eb)]
            void Select([in, optional] VARIANT Replace);
            [id(0x0000025d), helpcontext(0x0001025d)]
            void SendToBack();
            [id(0x0000007e), propget, helpcontext(0x0001007e)]
            double Top();
            [id(0x0000007e), propput, helpcontext(0x0001007e)]
            void Top([in] double rhs);
            [id(0x0000026c), propget, helpcontext(0x0001026c)]
            Range* TopLeftCell();
            [id(0x0000022e), propget, helpcontext(0x0001022e)]
            VARIANT_BOOL Visible();
            [id(0x0000022e), propput, helpcontext(0x0001022e)]
            void Visible([in] VARIANT_BOOL rhs);
            [id(0x0000007a), propget, helpcontext(0x0001007a)]
            double Width();
            [id(0x0000007a), propput, helpcontext(0x0001007a)]
            void Width([in] double rhs);
            [id(0x0000026e), propget, helpcontext(0x0001026e)]
            long ZOrder();
            [id(0x000005f8), propget, helpcontext(0x000105f8)]
            ShapeRange* ShapeRange();
            [id(0x0000008b), propget, helpcontext(0x0001008b)]
            BSTR Caption();
            [id(0x0000008b), propput, helpcontext(0x0001008b)]
            void Caption([in] BSTR rhs);
            [id(0x0000025b), propget, helpcontext(0x0001025b)]
            Characters* Characters(
                            [in, optional] VARIANT Start, 
                            [in, optional] VARIANT Length);
            [id(0x000001f9), helpcontext(0x000101f9)]
            void CheckSpelling(
                            [in, optional] VARIANT CustomDictionary, 
                            [in, optional] VARIANT IgnoreUppercase, 
                            [in, optional] VARIANT AlwaysSuggest, 
                            [in, optional] VARIANT IgnoreInitialAlefHamza, 
                            [in, optional] VARIANT IgnoreFinalYaa, 
                            [in, optional] VARIANT SpellScript);
            [id(0x00000268), propget, helpcontext(0x00010268)]
            VARIANT_BOOL LockedText();
            [id(0x00000268), propput, helpcontext(0x00010268)]
            void LockedText([in] VARIANT_BOOL rhs);
            [id(0x0000008a), propget, helpcontext(0x0001008a)]
            BSTR Text();
            [id(0x0000008a), propput, helpcontext(0x0001008a)]
            void Text([in] BSTR rhs);
            [id(0x0000039a), propget, helpcontext(0x0001039a)]
            VARIANT_BOOL DisplayVerticalScrollBar();
            [id(0x0000039a), propput, helpcontext(0x0001039a)]
            void DisplayVerticalScrollBar([in] VARIANT_BOOL rhs);
            [id(0x00000356), propget, helpcontext(0x00010356)]
            long InputType();
            [id(0x00000356), propput, helpcontext(0x00010356)]
            void InputType([in] long rhs);
            [id(0x0000035e), propget, helpcontext(0x0001035e)]
            BSTR LinkedObject();
            [id(0x00000357), propget, helpcontext(0x00010357)]
            VARIANT_BOOL MultiLine();
            [id(0x00000357), propput, helpcontext(0x00010357)]
            void MultiLine([in] VARIANT_BOOL rhs);
            [id(0x0000048a), propget, helpcontext(0x0001048a)]
            VARIANT_BOOL PasswordEdit();
            [id(0x0000048a), propput, helpcontext(0x0001048a)]
            void PasswordEdit([in] VARIANT_BOOL rhs);
    };

    [
      uuid(00020884-0000-0000-C000-000000000046),
      helpcontext(0x00020044),
      hidden
    ]
    dispinterface EditBoxes {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x00010003), restricted, hidden]
            void _Dummy3();
            [id(0x0000025a), helpcontext(0x0001025a)]
            void BringToFront();
            [id(0x00000227), helpcontext(0x00010227)]
            void Copy();
            [id(0x000000d5), helpcontext(0x000100d5)]
            void CopyPicture(
                            [in, optional, defaultvalue(2)] XlPictureAppearance Appearance, 
                            [in, optional, defaultvalue(-4147)] XlCopyPictureFormat Format);
            [id(0x00000235), helpcontext(0x00010235)]
            void Cut();
            [id(0x00000075), helpcontext(0x00010075)]
            void Delete();
            [id(0x0000040f), helpcontext(0x0001040f)]
            IDispatch* Duplicate();
            [id(0x00000258), propget, helpcontext(0x00010258)]
            VARIANT_BOOL Enabled();
            [id(0x00000258), propput, helpcontext(0x00010258)]
            void Enabled([in] VARIANT_BOOL rhs);
            [id(0x0000007b), propget, helpcontext(0x0001007b)]
            double Height();
            [id(0x0000007b), propput, helpcontext(0x0001007b)]
            void Height([in] double rhs);
            [id(0x0001000c), restricted, hidden]
            void _Dummy12();
            [id(0x0000007f), propget, helpcontext(0x0001007f)]
            double Left();
            [id(0x0000007f), propput, helpcontext(0x0001007f)]
            void Left([in] double rhs);
            [id(0x0000010d), propget, helpcontext(0x0001010d)]
            VARIANT_BOOL Locked();
            [id(0x0000010d), propput, helpcontext(0x0001010d)]
            void Locked([in] VARIANT_BOOL rhs);
            [id(0x0001000f), restricted, hidden]
            void _Dummy15();
            [id(0x00000254), propget, hidden, helpcontext(0x00010254)]
            BSTR OnAction();
            [id(0x00000254), propput, hidden, helpcontext(0x00010254)]
            void OnAction([in] BSTR rhs);
            [id(0x00000269), propget, helpcontext(0x00010269)]
            VARIANT Placement();
            [id(0x00000269), propput, helpcontext(0x00010269)]
            void Placement([in] VARIANT rhs);
            [id(0x0000026a), propget, helpcontext(0x0001026a)]
            VARIANT_BOOL PrintObject();
            [id(0x0000026a), propput, helpcontext(0x0001026a)]
            void PrintObject([in] VARIANT_BOOL rhs);
            [id(0x000000eb), helpcontext(0x000100eb)]
            void Select([in, optional] VARIANT Replace);
            [id(0x0000025d), helpcontext(0x0001025d)]
            void SendToBack();
            [id(0x0000007e), propget, helpcontext(0x0001007e)]
            double Top();
            [id(0x0000007e), propput, helpcontext(0x0001007e)]
            void Top([in] double rhs);
            [id(0x00010016), restricted, hidden]
            void _Dummy22();
            [id(0x0000022e), propget, helpcontext(0x0001022e)]
            VARIANT_BOOL Visible();
            [id(0x0000022e), propput, helpcontext(0x0001022e)]
            void Visible([in] VARIANT_BOOL rhs);
            [id(0x0000007a), propget, helpcontext(0x0001007a)]
            double Width();
            [id(0x0000007a), propput, helpcontext(0x0001007a)]
            void Width([in] double rhs);
            [id(0x0000026e), propget, helpcontext(0x0001026e)]
            long ZOrder();
            [id(0x000005f8), propget, helpcontext(0x000105f8)]
            ShapeRange* ShapeRange();
            [id(0x0000008b), propget, helpcontext(0x0001008b)]
            BSTR Caption();
            [id(0x0000008b), propput, helpcontext(0x0001008b)]
            void Caption([in] BSTR rhs);
            [id(0x0000025b), propget, helpcontext(0x0001025b)]
            Characters* Characters(
                            [in, optional] VARIANT Start, 
                            [in, optional] VARIANT Length);
            [id(0x000001f9), helpcontext(0x000101f9)]
            void CheckSpelling(
                            [in, optional] VARIANT CustomDictionary, 
                            [in, optional] VARIANT IgnoreUppercase, 
                            [in, optional] VARIANT AlwaysSuggest, 
                            [in, optional] VARIANT IgnoreInitialAlefHamza, 
                            [in, optional] VARIANT IgnoreFinalYaa, 
                            [in, optional] VARIANT SpellScript);
            [id(0x00000268), propget, helpcontext(0x00010268)]
            VARIANT_BOOL LockedText();
            [id(0x00000268), propput, helpcontext(0x00010268)]
            void LockedText([in] VARIANT_BOOL rhs);
            [id(0x0000008a), propget, helpcontext(0x0001008a)]
            BSTR Text();
            [id(0x0000008a), propput, helpcontext(0x0001008a)]
            void Text([in] BSTR rhs);
            [id(0x0000039a), propget, helpcontext(0x0001039a)]
            VARIANT_BOOL DisplayVerticalScrollBar();
            [id(0x0000039a), propput, helpcontext(0x0001039a)]
            void DisplayVerticalScrollBar([in] VARIANT_BOOL rhs);
            [id(0x00000356), propget, helpcontext(0x00010356)]
            long InputType();
            [id(0x00000356), propput, helpcontext(0x00010356)]
            void InputType([in] long rhs);
            [id(0x00010022), restricted, hidden]
            void _Dummy34();
            [id(0x00000357), propget, helpcontext(0x00010357)]
            VARIANT_BOOL MultiLine();
            [id(0x00000357), propput, helpcontext(0x00010357)]
            void MultiLine([in] VARIANT_BOOL rhs);
            [id(0x0000048a), propget, helpcontext(0x0001048a)]
            VARIANT_BOOL PasswordEdit();
            [id(0x0000048a), propput, helpcontext(0x0001048a)]
            void PasswordEdit([in] VARIANT_BOOL rhs);
            [id(0x000000b5), helpcontext(0x000100b5)]
            EditBox* Add(
                            [in] double Left, 
                            [in] double Top, 
                            [in] double Width, 
                            [in] double Height);
            [id(0x00000076), propget, helpcontext(0x00010076)]
            long Count();
            [id(0x0000002e), helpcontext(0x0001002e)]
            GroupObject* Group();
            [id(0x000000aa), helpcontext(0x000100aa)]
            VARIANT Item([in] VARIANT Index);
            [id(0xfffffffc), helpcontext(0x0000fffc)]
            IUnknown* _NewEnum();
    };

    [
      uuid(00020885-0000-0000-C000-000000000046),
      helpcontext(0x00020045),
      hidden
    ]
    dispinterface ScrollBar {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x00000267), propget, helpcontext(0x00010267)]
            Range* BottomRightCell();
            [id(0x0000025a), helpcontext(0x0001025a)]
            void BringToFront();
            [id(0x00000227), helpcontext(0x00010227)]
            void Copy();
            [id(0x000000d5), helpcontext(0x000100d5)]
            void CopyPicture(
                            [in, optional, defaultvalue(2)] XlPictureAppearance Appearance, 
                            [in, optional, defaultvalue(-4147)] XlCopyPictureFormat Format);
            [id(0x00000235), helpcontext(0x00010235)]
            void Cut();
            [id(0x00000075), helpcontext(0x00010075)]
            void Delete();
            [id(0x0000040f), helpcontext(0x0001040f)]
            IDispatch* Duplicate();
            [id(0x00000258), propget, helpcontext(0x00010258)]
            VARIANT_BOOL Enabled();
            [id(0x00000258), propput, helpcontext(0x00010258)]
            void Enabled([in] VARIANT_BOOL rhs);
            [id(0x0000007b), propget, helpcontext(0x0001007b)]
            double Height();
            [id(0x0000007b), propput, helpcontext(0x0001007b)]
            void Height([in] double rhs);
            [id(0x000001e6), propget, helpcontext(0x000101e6)]
            long Index();
            [id(0x0000007f), propget, helpcontext(0x0001007f)]
            double Left();
            [id(0x0000007f), propput, helpcontext(0x0001007f)]
            void Left([in] double rhs);
            [id(0x0000010d), propget, helpcontext(0x0001010d)]
            VARIANT_BOOL Locked();
            [id(0x0000010d), propput, helpcontext(0x0001010d)]
            void Locked([in] VARIANT_BOOL rhs);
            [id(0x0000006e), propget, helpcontext(0x0001006e)]
            BSTR Name();
            [id(0x0000006e), propput, helpcontext(0x0001006e)]
            void Name([in] BSTR rhs);
            [id(0x00000254), propget, hidden, helpcontext(0x00010254)]
            BSTR OnAction();
            [id(0x00000254), propput, hidden, helpcontext(0x00010254)]
            void OnAction([in] BSTR rhs);
            [id(0x00000269), propget, helpcontext(0x00010269)]
            VARIANT Placement();
            [id(0x00000269), propput, helpcontext(0x00010269)]
            void Placement([in] VARIANT rhs);
            [id(0x0000026a), propget, helpcontext(0x0001026a)]
            VARIANT_BOOL PrintObject();
            [id(0x0000026a), propput, helpcontext(0x0001026a)]
            void PrintObject([in] VARIANT_BOOL rhs);
            [id(0x000000eb), helpcontext(0x000100eb)]
            void Select([in, optional] VARIANT Replace);
            [id(0x0000025d), helpcontext(0x0001025d)]
            void SendToBack();
            [id(0x0000007e), propget, helpcontext(0x0001007e)]
            double Top();
            [id(0x0000007e), propput, helpcontext(0x0001007e)]
            void Top([in] double rhs);
            [id(0x0000026c), propget, helpcontext(0x0001026c)]
            Range* TopLeftCell();
            [id(0x0000022e), propget, helpcontext(0x0001022e)]
            VARIANT_BOOL Visible();
            [id(0x0000022e), propput, helpcontext(0x0001022e)]
            void Visible([in] VARIANT_BOOL rhs);
            [id(0x0000007a), propget, helpcontext(0x0001007a)]
            double Width();
            [id(0x0000007a), propput, helpcontext(0x0001007a)]
            void Width([in] double rhs);
            [id(0x0000026e), propget, helpcontext(0x0001026e)]
            long ZOrder();
            [id(0x000005f8), propget, helpcontext(0x000105f8)]
            ShapeRange* ShapeRange();
            [id(00000000), propget, helpcontext(0x00010000)]
            long _Default();
            [id(00000000), propput, helpcontext(0x00010000)]
            void _Default([in] long rhs);
            [id(0x00000462), propget, helpcontext(0x00010462)]
            VARIANT_BOOL Display3DShading();
            [id(0x00000462), propput, helpcontext(0x00010462)]
            void Display3DShading([in] VARIANT_BOOL rhs);
            [id(0x00000422), propget, helpcontext(0x00010422)]
            BSTR LinkedCell();
            [id(0x00000422), propput, helpcontext(0x00010422)]
            void LinkedCell([in] BSTR rhs);
            [id(0x0000034a), propget, helpcontext(0x0001034a)]
            long Max();
            [id(0x0000034a), propput, helpcontext(0x0001034a)]
            void Max([in] long rhs);
            [id(0x0000034b), propget, helpcontext(0x0001034b)]
            long Min();
            [id(0x0000034b), propput, helpcontext(0x0001034b)]
            void Min([in] long rhs);
            [id(0x0000034c), propget, helpcontext(0x0001034c)]
            long SmallChange();
            [id(0x0000034c), propput, helpcontext(0x0001034c)]
            void SmallChange([in] long rhs);
            [id(0x00000006), propget, helpcontext(0x00010006)]
            long Value();
            [id(0x00000006), propput, helpcontext(0x00010006)]
            void Value([in] long rhs);
            [id(0x0000034d), propget, helpcontext(0x0001034d)]
            long LargeChange();
            [id(0x0000034d), propput, helpcontext(0x0001034d)]
            void LargeChange([in] long rhs);
    };
