import "Excel09.Idl";


    [
      odl,
      uuid(00020899-0001-0000-C000-000000000046),
      helpcontext(0x00020059),
      hidden
    ]
    interface IGroupObjects : IDispatch {
        [propget, helpcontext(0x00010094)]
        HRESULT _stdcall Application([out, retval] Application** RHS);
        [propget, helpcontext(0x00010095)]
        HRESULT _stdcall Creator([out, retval] XlCreator* RHS);
        [propget, helpcontext(0x00010096)]
        HRESULT _stdcall Parent([out, retval] IDispatch** RHS);
        [restricted, hidden]
        void _stdcall _Dummy3();
        [helpcontext(0x0001025a)]
        HRESULT _stdcall BringToFront();
        [helpcontext(0x00010227)]
        HRESULT _stdcall Copy();
        [helpcontext(0x000100d5)]
        HRESULT _stdcall CopyPicture(
                        [in, optional, defaultvalue(2)] XlPictureAppearance Appearance, 
                        [in, optional, defaultvalue(-4147)] XlCopyPictureFormat Format);
        [helpcontext(0x00010235)]
        HRESULT _stdcall Cut();
        [helpcontext(0x00010075)]
        HRESULT _stdcall Delete();
        [helpcontext(0x0001040f)]
        HRESULT _stdcall Duplicate([out, retval] IDispatch** RHS);
        [propget, helpcontext(0x00010258)]
        HRESULT _stdcall Enabled([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010258)]
        HRESULT _stdcall Enabled([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x0001007b)]
        HRESULT _stdcall Height([out, retval] double* RHS);
        [propput, helpcontext(0x0001007b)]
        HRESULT _stdcall Height([in] double RHS);
        [restricted, hidden]
        void _stdcall _Dummy12();
        [propget, helpcontext(0x0001007f)]
        HRESULT _stdcall Left([out, retval] double* RHS);
        [propput, helpcontext(0x0001007f)]
        HRESULT _stdcall Left([in] double RHS);
        [propget, helpcontext(0x0001010d)]
        HRESULT _stdcall Locked([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x0001010d)]
        HRESULT _stdcall Locked([in] VARIANT_BOOL RHS);
        [restricted, hidden]
        void _stdcall _Dummy15();
        [propget, hidden, helpcontext(0x00010254)]
        HRESULT _stdcall OnAction([out, retval] BSTR* RHS);
        [propput, hidden, helpcontext(0x00010254)]
        HRESULT _stdcall OnAction([in] BSTR RHS);
        [propget, helpcontext(0x00010269)]
        HRESULT _stdcall Placement([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010269)]
        HRESULT _stdcall Placement([in] VARIANT RHS);
        [propget, helpcontext(0x0001026a)]
        HRESULT _stdcall PrintObject([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x0001026a)]
        HRESULT _stdcall PrintObject([in] VARIANT_BOOL RHS);
        [helpcontext(0x000100eb)]
        HRESULT _stdcall Select([in, optional] VARIANT Replace);
        [helpcontext(0x0001025d)]
        HRESULT _stdcall SendToBack();
        [propget, helpcontext(0x0001007e)]
        HRESULT _stdcall Top([out, retval] double* RHS);
        [propput, helpcontext(0x0001007e)]
        HRESULT _stdcall Top([in] double RHS);
        [restricted, hidden]
        void _stdcall _Dummy22();
        [propget, helpcontext(0x0001022e)]
        HRESULT _stdcall Visible([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x0001022e)]
        HRESULT _stdcall Visible([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x0001007a)]
        HRESULT _stdcall Width([out, retval] double* RHS);
        [propput, helpcontext(0x0001007a)]
        HRESULT _stdcall Width([in] double RHS);
        [propget, helpcontext(0x0001026e)]
        HRESULT _stdcall ZOrder([out, retval] long* RHS);
        [propget, helpcontext(0x000105f8)]
        HRESULT _stdcall ShapeRange([out, retval] ShapeRange** RHS);
        [restricted, hidden]
        void _stdcall _Dummy27();
        [restricted, hidden]
        void _stdcall _Dummy28();
        [propget, helpcontext(0x00010427)]
        HRESULT _stdcall AddIndent([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010427)]
        HRESULT _stdcall AddIndent([in] VARIANT_BOOL RHS);
        [restricted, hidden]
        void _stdcall _Dummy30();
        [propget, helpcontext(0x00010263)]
        HRESULT _stdcall ArrowHeadLength([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010263)]
        HRESULT _stdcall ArrowHeadLength([in] VARIANT RHS);
        [propget, helpcontext(0x00010264)]
        HRESULT _stdcall ArrowHeadStyle([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010264)]
        HRESULT _stdcall ArrowHeadStyle([in] VARIANT RHS);
        [propget, helpcontext(0x00010265)]
        HRESULT _stdcall ArrowHeadWidth([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010265)]
        HRESULT _stdcall ArrowHeadWidth([in] VARIANT RHS);
        [propget, helpcontext(0x00010266)]
        HRESULT _stdcall AutoSize([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010266)]
        HRESULT _stdcall AutoSize([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x00010080)]
        HRESULT _stdcall Border([out, retval] Border** RHS);
        [restricted, hidden]
        void _stdcall _Dummy36();
        [restricted, hidden]
        void _stdcall _Dummy37();
        [restricted, hidden]
        void _stdcall _Dummy38();
        [helpcontext(0x000101f9)]
        HRESULT _stdcall CheckSpelling(
                        [in, optional] VARIANT CustomDictionary, 
                        [in, optional] VARIANT IgnoreUppercase, 
                        [in, optional] VARIANT AlwaysSuggest, 
                        [in, optional] VARIANT IgnoreInitialAlefHamza, 
                        [in, optional] VARIANT IgnoreFinalYaa, 
                        [in, optional] VARIANT SpellScript);
        [propget, helpcontext(0x00010000)]
        HRESULT _stdcall _Default([out, retval] long* RHS);
        [propput, helpcontext(0x00010000)]
        HRESULT _stdcall _Default([in] long RHS);
        [restricted, hidden]
        void _stdcall _Dummy41();
        [restricted, hidden]
        void _stdcall _Dummy42();
        [restricted, hidden]
        void _stdcall _Dummy43();
        [restricted, hidden]
        void _stdcall _Dummy44();
        [restricted, hidden]
        void _stdcall _Dummy45();
        [propget, helpcontext(0x00010092)]
        HRESULT _stdcall Font([out, retval] Font** RHS);
        [restricted, hidden]
        void _stdcall _Dummy47();
        [restricted, hidden]
        void _stdcall _Dummy48();
        [propget, helpcontext(0x00010088)]
        HRESULT _stdcall HorizontalAlignment([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010088)]
        HRESULT _stdcall HorizontalAlignment([in] VARIANT RHS);
        [restricted, hidden]
        void _stdcall _Dummy50();
        [propget, helpcontext(0x00010081)]
        HRESULT _stdcall Interior([out, retval] Interior** RHS);
        [restricted, hidden]
        void _stdcall _Dummy52();
        [restricted, hidden]
        void _stdcall _Dummy53();
        [restricted, hidden]
        void _stdcall _Dummy54();
        [restricted, hidden]
        void _stdcall _Dummy55();
        [restricted, hidden]
        void _stdcall _Dummy56();
        [restricted, hidden]
        void _stdcall _Dummy57();
        [restricted, hidden]
        void _stdcall _Dummy58();
        [restricted, hidden]
        void _stdcall _Dummy59();
        [restricted, hidden]
        void _stdcall _Dummy60();
        [restricted, hidden]
        void _stdcall _Dummy61();
        [restricted, hidden]
        void _stdcall _Dummy62();
        [restricted, hidden]
        void _stdcall _Dummy63();
        [propget, helpcontext(0x00010086)]
        HRESULT _stdcall Orientation([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010086)]
        HRESULT _stdcall Orientation([in] VARIANT RHS);
        [restricted, hidden]
        void _stdcall _Dummy65();
        [restricted, hidden]
        void _stdcall _Dummy66();
        [restricted, hidden]
        void _stdcall _Dummy67();
        [restricted, hidden]
        void _stdcall _Dummy68();
        [propget, helpcontext(0x0001026b)]
        HRESULT _stdcall RoundedCorners([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x0001026b)]
        HRESULT _stdcall RoundedCorners([in] VARIANT_BOOL RHS);
        [restricted, hidden]
        void _stdcall _Dummy70();
        [propget, helpcontext(0x00010067)]
        HRESULT _stdcall Shadow([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010067)]
        HRESULT _stdcall Shadow([in] VARIANT_BOOL RHS);
        [restricted, hidden]
        void _stdcall _Dummy72();
        [restricted, hidden]
        void _stdcall _Dummy73();
        [helpcontext(0x000100f4)]
        HRESULT _stdcall Ungroup([out, retval] IDispatch** RHS);
        [restricted, hidden]
        void _stdcall _Dummy75();
        [propget, helpcontext(0x00010089)]
        HRESULT _stdcall VerticalAlignment([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010089)]
        HRESULT _stdcall VerticalAlignment([in] VARIANT RHS);
        [restricted, hidden]
        void _stdcall _Dummy77();
        [propget, helpcontext(0x000103cf)]
        HRESULT _stdcall ReadingOrder([out, retval] long* RHS);
        [propput, helpcontext(0x000103cf)]
        HRESULT _stdcall ReadingOrder([in] long RHS);
        [propget, helpcontext(0x00010076)]
        HRESULT _stdcall Count([out, retval] long* RHS);
        [helpcontext(0x0001002e)]
        HRESULT _stdcall Group([out, retval] GroupObject** RHS);
        [helpcontext(0x000100aa)]
        HRESULT _stdcall Item(
                        [in] VARIANT Index, 
                        [out, retval] IDispatch** RHS);
        [helpcontext(0x0000fffc)]
        HRESULT _stdcall _NewEnum([out, retval] IUnknown** RHS);
    };

    [
      odl,
      uuid(0002089A-0001-0000-C000-000000000046),
      helpcontext(0x0002005a),
      hidden
    ]
    interface ILine : IDispatch {
        [propget, helpcontext(0x00010094)]
        HRESULT _stdcall Application([out, retval] Application** RHS);
        [propget, helpcontext(0x00010095)]
        HRESULT _stdcall Creator([out, retval] XlCreator* RHS);
        [propget, helpcontext(0x00010096)]
        HRESULT _stdcall Parent([out, retval] IDispatch** RHS);
        [propget, helpcontext(0x00010267)]
        HRESULT _stdcall BottomRightCell([out, retval] Range** RHS);
        [helpcontext(0x0001025a)]
        HRESULT _stdcall BringToFront();
        [helpcontext(0x00010227)]
        HRESULT _stdcall Copy();
        [helpcontext(0x000100d5)]
        HRESULT _stdcall CopyPicture(
                        [in, optional, defaultvalue(2)] XlPictureAppearance Appearance, 
                        [in, optional, defaultvalue(-4147)] XlCopyPictureFormat Format);
        [helpcontext(0x00010235)]
        HRESULT _stdcall Cut();
        [helpcontext(0x00010075)]
        HRESULT _stdcall Delete();
        [helpcontext(0x0001040f)]
        HRESULT _stdcall Duplicate([out, retval] IDispatch** RHS);
        [propget, helpcontext(0x00010258)]
        HRESULT _stdcall Enabled([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010258)]
        HRESULT _stdcall Enabled([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x0001007b)]
        HRESULT _stdcall Height([out, retval] double* RHS);
        [propput, helpcontext(0x0001007b)]
        HRESULT _stdcall Height([in] double RHS);
        [propget, helpcontext(0x000101e6)]
        HRESULT _stdcall Index([out, retval] long* RHS);
        [propget, helpcontext(0x0001007f)]
        HRESULT _stdcall Left([out, retval] double* RHS);
        [propput, helpcontext(0x0001007f)]
        HRESULT _stdcall Left([in] double RHS);
        [propget, helpcontext(0x0001010d)]
        HRESULT _stdcall Locked([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x0001010d)]
        HRESULT _stdcall Locked([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x0001006e)]
        HRESULT _stdcall Name([out, retval] BSTR* RHS);
        [propput, helpcontext(0x0001006e)]
        HRESULT _stdcall Name([in] BSTR RHS);
        [propget, hidden, helpcontext(0x00010254)]
        HRESULT _stdcall OnAction([out, retval] BSTR* RHS);
        [propput, hidden, helpcontext(0x00010254)]
        HRESULT _stdcall OnAction([in] BSTR RHS);
        [propget, helpcontext(0x00010269)]
        HRESULT _stdcall Placement([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010269)]
        HRESULT _stdcall Placement([in] VARIANT RHS);
        [propget, helpcontext(0x0001026a)]
        HRESULT _stdcall PrintObject([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x0001026a)]
        HRESULT _stdcall PrintObject([in] VARIANT_BOOL RHS);
        [helpcontext(0x000100eb)]
        HRESULT _stdcall Select([in, optional] VARIANT Replace);
        [helpcontext(0x0001025d)]
        HRESULT _stdcall SendToBack();
        [propget, helpcontext(0x0001007e)]
        HRESULT _stdcall Top([out, retval] double* RHS);
        [propput, helpcontext(0x0001007e)]
        HRESULT _stdcall Top([in] double RHS);
        [propget, helpcontext(0x0001026c)]
        HRESULT _stdcall TopLeftCell([out, retval] Range** RHS);
        [propget, helpcontext(0x0001022e)]
        HRESULT _stdcall Visible([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x0001022e)]
        HRESULT _stdcall Visible([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x0001007a)]
        HRESULT _stdcall Width([out, retval] double* RHS);
        [propput, helpcontext(0x0001007a)]
        HRESULT _stdcall Width([in] double RHS);
        [propget, helpcontext(0x0001026e)]
        HRESULT _stdcall ZOrder([out, retval] long* RHS);
        [propget, helpcontext(0x000105f8)]
        HRESULT _stdcall ShapeRange([out, retval] ShapeRange** RHS);
        [propget, helpcontext(0x00010263)]
        HRESULT _stdcall ArrowHeadLength([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010263)]
        HRESULT _stdcall ArrowHeadLength([in] VARIANT RHS);
        [propget, helpcontext(0x00010264)]
        HRESULT _stdcall ArrowHeadStyle([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010264)]
        HRESULT _stdcall ArrowHeadStyle([in] VARIANT RHS);
        [propget, helpcontext(0x00010265)]
        HRESULT _stdcall ArrowHeadWidth([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010265)]
        HRESULT _stdcall ArrowHeadWidth([in] VARIANT RHS);
        [propget, helpcontext(0x00010080)]
        HRESULT _stdcall Border([out, retval] Border** RHS);
    };

    [
      odl,
      uuid(0002089B-0001-0000-C000-000000000046),
      helpcontext(0x0002005b),
      hidden
    ]
    interface ILines : IDispatch {
        [propget, helpcontext(0x00010094)]
        HRESULT _stdcall Application([out, retval] Application** RHS);
        [propget, helpcontext(0x00010095)]
        HRESULT _stdcall Creator([out, retval] XlCreator* RHS);
        [propget, helpcontext(0x00010096)]
        HRESULT _stdcall Parent([out, retval] IDispatch** RHS);
        [restricted, hidden]
        void _stdcall _Dummy3();
        [helpcontext(0x0001025a)]
        HRESULT _stdcall BringToFront();
        [helpcontext(0x00010227)]
        HRESULT _stdcall Copy();
        [helpcontext(0x000100d5)]
        HRESULT _stdcall CopyPicture(
                        [in, optional, defaultvalue(2)] XlPictureAppearance Appearance, 
                        [in, optional, defaultvalue(-4147)] XlCopyPictureFormat Format);
        [helpcontext(0x00010235)]
        HRESULT _stdcall Cut();
        [helpcontext(0x00010075)]
        HRESULT _stdcall Delete();
        [helpcontext(0x0001040f)]
        HRESULT _stdcall Duplicate([out, retval] IDispatch** RHS);
        [propget, helpcontext(0x00010258)]
        HRESULT _stdcall Enabled([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010258)]
        HRESULT _stdcall Enabled([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x0001007b)]
        HRESULT _stdcall Height([out, retval] double* RHS);
        [propput, helpcontext(0x0001007b)]
        HRESULT _stdcall Height([in] double RHS);
        [restricted, hidden]
        void _stdcall _Dummy12();
        [propget, helpcontext(0x0001007f)]
        HRESULT _stdcall Left([out, retval] double* RHS);
        [propput, helpcontext(0x0001007f)]
        HRESULT _stdcall Left([in] double RHS);
        [propget, helpcontext(0x0001010d)]
        HRESULT _stdcall Locked([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x0001010d)]
        HRESULT _stdcall Locked([in] VARIANT_BOOL RHS);
        [restricted, hidden]
        void _stdcall _Dummy15();
        [propget, hidden, helpcontext(0x00010254)]
        HRESULT _stdcall OnAction([out, retval] BSTR* RHS);
        [propput, hidden, helpcontext(0x00010254)]
        HRESULT _stdcall OnAction([in] BSTR RHS);
        [propget, helpcontext(0x00010269)]
        HRESULT _stdcall Placement([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010269)]
        HRESULT _stdcall Placement([in] VARIANT RHS);
        [propget, helpcontext(0x0001026a)]
        HRESULT _stdcall PrintObject([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x0001026a)]
        HRESULT _stdcall PrintObject([in] VARIANT_BOOL RHS);
        [helpcontext(0x000100eb)]
        HRESULT _stdcall Select([in, optional] VARIANT Replace);
        [helpcontext(0x0001025d)]
        HRESULT _stdcall SendToBack();
        [propget, helpcontext(0x0001007e)]
        HRESULT _stdcall Top([out, retval] double* RHS);
        [propput, helpcontext(0x0001007e)]
        HRESULT _stdcall Top([in] double RHS);
        [restricted, hidden]
        void _stdcall _Dummy22();
        [propget, helpcontext(0x0001022e)]
        HRESULT _stdcall Visible([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x0001022e)]
        HRESULT _stdcall Visible([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x0001007a)]
        HRESULT _stdcall Width([out, retval] double* RHS);
        [propput, helpcontext(0x0001007a)]
        HRESULT _stdcall Width([in] double RHS);
        [propget, helpcontext(0x0001026e)]
        HRESULT _stdcall ZOrder([out, retval] long* RHS);
        [propget, helpcontext(0x000105f8)]
        HRESULT _stdcall ShapeRange([out, retval] ShapeRange** RHS);
        [propget, helpcontext(0x00010263)]
        HRESULT _stdcall ArrowHeadLength([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010263)]
        HRESULT _stdcall ArrowHeadLength([in] VARIANT RHS);
        [propget, helpcontext(0x00010264)]
        HRESULT _stdcall ArrowHeadStyle([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010264)]
        HRESULT _stdcall ArrowHeadStyle([in] VARIANT RHS);
        [propget, helpcontext(0x00010265)]
        HRESULT _stdcall ArrowHeadWidth([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010265)]
        HRESULT _stdcall ArrowHeadWidth([in] VARIANT RHS);
        [propget, helpcontext(0x00010080)]
        HRESULT _stdcall Border([out, retval] Border** RHS);
        [helpcontext(0x000100b5)]
        HRESULT _stdcall Add(
                        [in] double X1, 
                        [in] double Y1, 
                        [in] double X2, 
                        [in] double Y2, 
                        [out, retval] Line** RHS);
        [propget, helpcontext(0x00010076)]
        HRESULT _stdcall Count([out, retval] long* RHS);
        [helpcontext(0x0001002e)]
        HRESULT _stdcall Group([out, retval] GroupObject** RHS);
        [helpcontext(0x000100aa)]
        HRESULT _stdcall Item(
                        [in] VARIANT Index, 
                        [out, retval] IDispatch** RHS);
        [helpcontext(0x0000fffc)]
        HRESULT _stdcall _NewEnum([out, retval] IUnknown** RHS);
    };

    [
      odl,
      uuid(0002089C-0001-0000-C000-000000000046),
      helpcontext(0x0002005c),
      hidden
    ]
    interface IRectangle : IDispatch {
        [propget, helpcontext(0x00010094)]
        HRESULT _stdcall Application([out, retval] Application** RHS);
        [propget, helpcontext(0x00010095)]
        HRESULT _stdcall Creator([out, retval] XlCreator* RHS);
        [propget, helpcontext(0x00010096)]
        HRESULT _stdcall Parent([out, retval] IDispatch** RHS);
        [propget, helpcontext(0x00010267)]
        HRESULT _stdcall BottomRightCell([out, retval] Range** RHS);
        [helpcontext(0x0001025a)]
        HRESULT _stdcall BringToFront();
        [helpcontext(0x00010227)]
        HRESULT _stdcall Copy();
        [helpcontext(0x000100d5)]
        HRESULT _stdcall CopyPicture(
                        [in, optional, defaultvalue(2)] XlPictureAppearance Appearance, 
                        [in, optional, defaultvalue(-4147)] XlCopyPictureFormat Format);
        [helpcontext(0x00010235)]
        HRESULT _stdcall Cut();
        [helpcontext(0x00010075)]
        HRESULT _stdcall Delete();
        [helpcontext(0x0001040f)]
        HRESULT _stdcall Duplicate([out, retval] IDispatch** RHS);
        [propget, helpcontext(0x00010258)]
        HRESULT _stdcall Enabled([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010258)]
        HRESULT _stdcall Enabled([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x0001007b)]
        HRESULT _stdcall Height([out, retval] double* RHS);
        [propput, helpcontext(0x0001007b)]
        HRESULT _stdcall Height([in] double RHS);
        [propget, helpcontext(0x000101e6)]
        HRESULT _stdcall Index([out, retval] long* RHS);
        [propget, helpcontext(0x0001007f)]
        HRESULT _stdcall Left([out, retval] double* RHS);
        [propput, helpcontext(0x0001007f)]
        HRESULT _stdcall Left([in] double RHS);
        [propget, helpcontext(0x0001010d)]
        HRESULT _stdcall Locked([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x0001010d)]
        HRESULT _stdcall Locked([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x0001006e)]
        HRESULT _stdcall Name([out, retval] BSTR* RHS);
        [propput, helpcontext(0x0001006e)]
        HRESULT _stdcall Name([in] BSTR RHS);
        [propget, hidden, helpcontext(0x00010254)]
        HRESULT _stdcall OnAction([out, retval] BSTR* RHS);
        [propput, hidden, helpcontext(0x00010254)]
        HRESULT _stdcall OnAction([in] BSTR RHS);
        [propget, helpcontext(0x00010269)]
        HRESULT _stdcall Placement([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010269)]
        HRESULT _stdcall Placement([in] VARIANT RHS);
        [propget, helpcontext(0x0001026a)]
        HRESULT _stdcall PrintObject([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x0001026a)]
        HRESULT _stdcall PrintObject([in] VARIANT_BOOL RHS);
        [helpcontext(0x000100eb)]
        HRESULT _stdcall Select([in, optional] VARIANT Replace);
        [helpcontext(0x0001025d)]
        HRESULT _stdcall SendToBack();
        [propget, helpcontext(0x0001007e)]
        HRESULT _stdcall Top([out, retval] double* RHS);
        [propput, helpcontext(0x0001007e)]
        HRESULT _stdcall Top([in] double RHS);
        [propget, helpcontext(0x0001026c)]
        HRESULT _stdcall TopLeftCell([out, retval] Range** RHS);
        [propget, helpcontext(0x0001022e)]
        HRESULT _stdcall Visible([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x0001022e)]
        HRESULT _stdcall Visible([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x0001007a)]
        HRESULT _stdcall Width([out, retval] double* RHS);
        [propput, helpcontext(0x0001007a)]
        HRESULT _stdcall Width([in] double RHS);
        [propget, helpcontext(0x0001026e)]
        HRESULT _stdcall ZOrder([out, retval] long* RHS);
        [propget, helpcontext(0x000105f8)]
        HRESULT _stdcall ShapeRange([out, retval] ShapeRange** RHS);
        [propget, helpcontext(0x00010427)]
        HRESULT _stdcall AddIndent([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010427)]
        HRESULT _stdcall AddIndent([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x000105f5)]
        HRESULT _stdcall AutoScaleFont([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x000105f5)]
        HRESULT _stdcall AutoScaleFont([in] VARIANT RHS);
        [propget, helpcontext(0x00010266)]
        HRESULT _stdcall AutoSize([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010266)]
        HRESULT _stdcall AutoSize([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x0001008b)]
        HRESULT _stdcall Caption([out, retval] BSTR* RHS);
        [propput, helpcontext(0x0001008b)]
        HRESULT _stdcall Caption([in] BSTR RHS);
        [propget, helpcontext(0x0001025b)]
        HRESULT _stdcall Characters(
                        [in, optional] VARIANT Start, 
                        [in, optional] VARIANT Length, 
                        [out, retval] Characters** RHS);
        [helpcontext(0x000101f9)]
        HRESULT _stdcall CheckSpelling(
                        [in, optional] VARIANT CustomDictionary, 
                        [in, optional] VARIANT IgnoreUppercase, 
                        [in, optional] VARIANT AlwaysSuggest, 
                        [in, optional] VARIANT IgnoreInitialAlefHamza, 
                        [in, optional] VARIANT IgnoreFinalYaa, 
                        [in, optional] VARIANT SpellScript);
        [propget, helpcontext(0x00010092)]
        HRESULT _stdcall Font([out, retval] Font** RHS);
        [propget, helpcontext(0x00010105)]
        HRESULT _stdcall Formula([out, retval] BSTR* RHS);
        [propput, helpcontext(0x00010105)]
        HRESULT _stdcall Formula([in] BSTR RHS);
        [propget, helpcontext(0x00010088)]
        HRESULT _stdcall HorizontalAlignment([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010088)]
        HRESULT _stdcall HorizontalAlignment([in] VARIANT RHS);
        [propget, helpcontext(0x00010268)]
        HRESULT _stdcall LockedText([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010268)]
        HRESULT _stdcall LockedText([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x00010086)]
        HRESULT _stdcall Orientation([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010086)]
        HRESULT _stdcall Orientation([in] VARIANT RHS);
        [propget, helpcontext(0x0001008a)]
        HRESULT _stdcall Text([out, retval] BSTR* RHS);
        [propput, helpcontext(0x0001008a)]
        HRESULT _stdcall Text([in] BSTR RHS);
        [propget, helpcontext(0x00010089)]
        HRESULT _stdcall VerticalAlignment([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010089)]
        HRESULT _stdcall VerticalAlignment([in] VARIANT RHS);
        [propget, helpcontext(0x000103cf)]
        HRESULT _stdcall ReadingOrder([out, retval] long* RHS);
        [propput, helpcontext(0x000103cf)]
        HRESULT _stdcall ReadingOrder([in] long RHS);
        [propget, helpcontext(0x00010080)]
        HRESULT _stdcall Border([out, retval] Border** RHS);
        [propget, helpcontext(0x00010081)]
        HRESULT _stdcall Interior([out, retval] Interior** RHS);
        [propget, helpcontext(0x00010067)]
        HRESULT _stdcall Shadow([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010067)]
        HRESULT _stdcall Shadow([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x0001026b)]
        HRESULT _stdcall RoundedCorners([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x0001026b)]
        HRESULT _stdcall RoundedCorners([in] VARIANT_BOOL RHS);
    };

    [
      odl,
      uuid(0002089D-0001-0000-C000-000000000046),
      helpcontext(0x0002005d),
      hidden
    ]
    interface IRectangles : IDispatch {
        [propget, helpcontext(0x00010094)]
        HRESULT _stdcall Application([out, retval] Application** RHS);
        [propget, helpcontext(0x00010095)]
        HRESULT _stdcall Creator([out, retval] XlCreator* RHS);
        [propget, helpcontext(0x00010096)]
        HRESULT _stdcall Parent([out, retval] IDispatch** RHS);
        [restricted, hidden]
        void _stdcall _Dummy3();
        [helpcontext(0x0001025a)]
        HRESULT _stdcall BringToFront();
        [helpcontext(0x00010227)]
        HRESULT _stdcall Copy();
        [helpcontext(0x000100d5)]
        HRESULT _stdcall CopyPicture(
                        [in, optional, defaultvalue(2)] XlPictureAppearance Appearance, 
                        [in, optional, defaultvalue(-4147)] XlCopyPictureFormat Format);
        [helpcontext(0x00010235)]
        HRESULT _stdcall Cut();
        [helpcontext(0x00010075)]
        HRESULT _stdcall Delete();
        [helpcontext(0x0001040f)]
        HRESULT _stdcall Duplicate([out, retval] IDispatch** RHS);
        [propget, helpcontext(0x00010258)]
        HRESULT _stdcall Enabled([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010258)]
        HRESULT _stdcall Enabled([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x0001007b)]
        HRESULT _stdcall Height([out, retval] double* RHS);
        [propput, helpcontext(0x0001007b)]
        HRESULT _stdcall Height([in] double RHS);
        [restricted, hidden]
        void _stdcall _Dummy12();
        [propget, helpcontext(0x0001007f)]
        HRESULT _stdcall Left([out, retval] double* RHS);
        [propput, helpcontext(0x0001007f)]
        HRESULT _stdcall Left([in] double RHS);
        [propget, helpcontext(0x0001010d)]
        HRESULT _stdcall Locked([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x0001010d)]
        HRESULT _stdcall Locked([in] VARIANT_BOOL RHS);
        [restricted, hidden]
        void _stdcall _Dummy15();
        [propget, hidden, helpcontext(0x00010254)]
        HRESULT _stdcall OnAction([out, retval] BSTR* RHS);
        [propput, hidden, helpcontext(0x00010254)]
        HRESULT _stdcall OnAction([in] BSTR RHS);
        [propget, helpcontext(0x00010269)]
        HRESULT _stdcall Placement([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010269)]
        HRESULT _stdcall Placement([in] VARIANT RHS);
        [propget, helpcontext(0x0001026a)]
        HRESULT _stdcall PrintObject([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x0001026a)]
        HRESULT _stdcall PrintObject([in] VARIANT_BOOL RHS);
        [helpcontext(0x000100eb)]
        HRESULT _stdcall Select([in, optional] VARIANT Replace);
        [helpcontext(0x0001025d)]
        HRESULT _stdcall SendToBack();
        [propget, helpcontext(0x0001007e)]
        HRESULT _stdcall Top([out, retval] double* RHS);
        [propput, helpcontext(0x0001007e)]
        HRESULT _stdcall Top([in] double RHS);
        [restricted, hidden]
        void _stdcall _Dummy22();
        [propget, helpcontext(0x0001022e)]
        HRESULT _stdcall Visible([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x0001022e)]
        HRESULT _stdcall Visible([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x0001007a)]
        HRESULT _stdcall Width([out, retval] double* RHS);
        [propput, helpcontext(0x0001007a)]
        HRESULT _stdcall Width([in] double RHS);
        [propget, helpcontext(0x0001026e)]
        HRESULT _stdcall ZOrder([out, retval] long* RHS);
        [propget, helpcontext(0x000105f8)]
        HRESULT _stdcall ShapeRange([out, retval] ShapeRange** RHS);
        [propget, helpcontext(0x00010427)]
        HRESULT _stdcall AddIndent([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010427)]
        HRESULT _stdcall AddIndent([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x000105f5)]
        HRESULT _stdcall AutoScaleFont([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x000105f5)]
        HRESULT _stdcall AutoScaleFont([in] VARIANT RHS);
        [propget, helpcontext(0x00010266)]
        HRESULT _stdcall AutoSize([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010266)]
        HRESULT _stdcall AutoSize([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x0001008b)]
        HRESULT _stdcall Caption([out, retval] BSTR* RHS);
        [propput, helpcontext(0x0001008b)]
        HRESULT _stdcall Caption([in] BSTR RHS);
        [propget, helpcontext(0x0001025b)]
        HRESULT _stdcall Characters(
                        [in, optional] VARIANT Start, 
                        [in, optional] VARIANT Length, 
                        [out, retval] Characters** RHS);
        [helpcontext(0x000101f9)]
        HRESULT _stdcall CheckSpelling(
                        [in, optional] VARIANT CustomDictionary, 
                        [in, optional] VARIANT IgnoreUppercase, 
                        [in, optional] VARIANT AlwaysSuggest, 
                        [in, optional] VARIANT IgnoreInitialAlefHamza, 
                        [in, optional] VARIANT IgnoreFinalYaa, 
                        [in, optional] VARIANT SpellScript);
        [propget, helpcontext(0x00010092)]
        HRESULT _stdcall Font([out, retval] Font** RHS);
        [propget, helpcontext(0x00010105)]
        HRESULT _stdcall Formula([out, retval] BSTR* RHS);
        [propput, helpcontext(0x00010105)]
        HRESULT _stdcall Formula([in] BSTR RHS);
        [propget, helpcontext(0x00010088)]
        HRESULT _stdcall HorizontalAlignment([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010088)]
        HRESULT _stdcall HorizontalAlignment([in] VARIANT RHS);
        [propget, helpcontext(0x00010268)]
        HRESULT _stdcall LockedText([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010268)]
        HRESULT _stdcall LockedText([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x00010086)]
        HRESULT _stdcall Orientation([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010086)]
        HRESULT _stdcall Orientation([in] VARIANT RHS);
        [propget, helpcontext(0x0001008a)]
        HRESULT _stdcall Text([out, retval] BSTR* RHS);
        [propput, helpcontext(0x0001008a)]
        HRESULT _stdcall Text([in] BSTR RHS);
        [propget, helpcontext(0x00010089)]
        HRESULT _stdcall VerticalAlignment([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010089)]
        HRESULT _stdcall VerticalAlignment([in] VARIANT RHS);
        [propget, helpcontext(0x000103cf)]
        HRESULT _stdcall ReadingOrder([out, retval] long* RHS);
        [propput, helpcontext(0x000103cf)]
        HRESULT _stdcall ReadingOrder([in] long RHS);
        [propget, helpcontext(0x00010080)]
        HRESULT _stdcall Border([out, retval] Border** RHS);
        [propget, helpcontext(0x00010081)]
        HRESULT _stdcall Interior([out, retval] Interior** RHS);
        [propget, helpcontext(0x00010067)]
        HRESULT _stdcall Shadow([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010067)]
        HRESULT _stdcall Shadow([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x0001026b)]
        HRESULT _stdcall RoundedCorners([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x0001026b)]
        HRESULT _stdcall RoundedCorners([in] VARIANT_BOOL RHS);
        [helpcontext(0x000100b5)]
        HRESULT _stdcall Add(
                        [in] double Left, 
                        [in] double Top, 
                        [in] double Width, 
                        [in] double Height, 
                        [out, retval] Rectangle** RHS);
        [propget, helpcontext(0x00010076)]
        HRESULT _stdcall Count([out, retval] long* RHS);
        [helpcontext(0x0001002e)]
        HRESULT _stdcall Group([out, retval] GroupObject** RHS);
        [helpcontext(0x000100aa)]
        HRESULT _stdcall Item(
                        [in] VARIANT Index, 
                        [out, retval] IDispatch** RHS);
        [helpcontext(0x0000fffc)]
        HRESULT _stdcall _NewEnum([out, retval] IUnknown** RHS);
    };

    [
      odl,
      uuid(0002089E-0001-0000-C000-000000000046),
      helpcontext(0x0002005e),
      hidden
    ]
    interface IOval : IDispatch {
        [propget, helpcontext(0x00010094)]
        HRESULT _stdcall Application([out, retval] Application** RHS);
        [propget, helpcontext(0x00010095)]
        HRESULT _stdcall Creator([out, retval] XlCreator* RHS);
        [propget, helpcontext(0x00010096)]
        HRESULT _stdcall Parent([out, retval] IDispatch** RHS);
        [propget, helpcontext(0x00010267)]
        HRESULT _stdcall BottomRightCell([out, retval] Range** RHS);
        [helpcontext(0x0001025a)]
        HRESULT _stdcall BringToFront();
        [helpcontext(0x00010227)]
        HRESULT _stdcall Copy();
        [helpcontext(0x000100d5)]
        HRESULT _stdcall CopyPicture(
                        [in, optional, defaultvalue(2)] XlPictureAppearance Appearance, 
                        [in, optional, defaultvalue(-4147)] XlCopyPictureFormat Format);
        [helpcontext(0x00010235)]
        HRESULT _stdcall Cut();
        [helpcontext(0x00010075)]
        HRESULT _stdcall Delete();
        [helpcontext(0x0001040f)]
        HRESULT _stdcall Duplicate([out, retval] IDispatch** RHS);
        [propget, helpcontext(0x00010258)]
        HRESULT _stdcall Enabled([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010258)]
        HRESULT _stdcall Enabled([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x0001007b)]
        HRESULT _stdcall Height([out, retval] double* RHS);
        [propput, helpcontext(0x0001007b)]
        HRESULT _stdcall Height([in] double RHS);
        [propget, helpcontext(0x000101e6)]
        HRESULT _stdcall Index([out, retval] long* RHS);
        [propget, helpcontext(0x0001007f)]
        HRESULT _stdcall Left([out, retval] double* RHS);
        [propput, helpcontext(0x0001007f)]
        HRESULT _stdcall Left([in] double RHS);
        [propget, helpcontext(0x0001010d)]
        HRESULT _stdcall Locked([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x0001010d)]
        HRESULT _stdcall Locked([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x0001006e)]
        HRESULT _stdcall Name([out, retval] BSTR* RHS);
        [propput, helpcontext(0x0001006e)]
        HRESULT _stdcall Name([in] BSTR RHS);
        [propget, hidden, helpcontext(0x00010254)]
        HRESULT _stdcall OnAction([out, retval] BSTR* RHS);
        [propput, hidden, helpcontext(0x00010254)]
        HRESULT _stdcall OnAction([in] BSTR RHS);
        [propget, helpcontext(0x00010269)]
        HRESULT _stdcall Placement([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010269)]
        HRESULT _stdcall Placement([in] VARIANT RHS);
        [propget, helpcontext(0x0001026a)]
        HRESULT _stdcall PrintObject([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x0001026a)]
        HRESULT _stdcall PrintObject([in] VARIANT_BOOL RHS);
        [helpcontext(0x000100eb)]
        HRESULT _stdcall Select([in, optional] VARIANT Replace);
        [helpcontext(0x0001025d)]
        HRESULT _stdcall SendToBack();
        [propget, helpcontext(0x0001007e)]
        HRESULT _stdcall Top([out, retval] double* RHS);
        [propput, helpcontext(0x0001007e)]
        HRESULT _stdcall Top([in] double RHS);
        [propget, helpcontext(0x0001026c)]
        HRESULT _stdcall TopLeftCell([out, retval] Range** RHS);
        [propget, helpcontext(0x0001022e)]
        HRESULT _stdcall Visible([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x0001022e)]
        HRESULT _stdcall Visible([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x0001007a)]
        HRESULT _stdcall Width([out, retval] double* RHS);
        [propput, helpcontext(0x0001007a)]
        HRESULT _stdcall Width([in] double RHS);
        [propget, helpcontext(0x0001026e)]
        HRESULT _stdcall ZOrder([out, retval] long* RHS);
        [propget, helpcontext(0x000105f8)]
        HRESULT _stdcall ShapeRange([out, retval] ShapeRange** RHS);
        [propget, helpcontext(0x00010427)]
        HRESULT _stdcall AddIndent([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010427)]
        HRESULT _stdcall AddIndent([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x000105f5)]
        HRESULT _stdcall AutoScaleFont([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x000105f5)]
        HRESULT _stdcall AutoScaleFont([in] VARIANT RHS);
        [propget, helpcontext(0x00010266)]
        HRESULT _stdcall AutoSize([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010266)]
        HRESULT _stdcall AutoSize([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x0001008b)]
        HRESULT _stdcall Caption([out, retval] BSTR* RHS);
        [propput, helpcontext(0x0001008b)]
        HRESULT _stdcall Caption([in] BSTR RHS);
        [propget, helpcontext(0x0001025b)]
        HRESULT _stdcall Characters(
                        [in, optional] VARIANT Start, 
                        [in, optional] VARIANT Length, 
                        [out, retval] Characters** RHS);
        [helpcontext(0x000101f9)]
        HRESULT _stdcall CheckSpelling(
                        [in, optional] VARIANT CustomDictionary, 
                        [in, optional] VARIANT IgnoreUppercase, 
                        [in, optional] VARIANT AlwaysSuggest, 
                        [in, optional] VARIANT IgnoreInitialAlefHamza, 
                        [in, optional] VARIANT IgnoreFinalYaa, 
                        [in, optional] VARIANT SpellScript);
        [propget, helpcontext(0x00010092)]
        HRESULT _stdcall Font([out, retval] Font** RHS);
        [propget, helpcontext(0x00010105)]
        HRESULT _stdcall Formula([out, retval] BSTR* RHS);
        [propput, helpcontext(0x00010105)]
        HRESULT _stdcall Formula([in] BSTR RHS);
        [propget, helpcontext(0x00010088)]
        HRESULT _stdcall HorizontalAlignment([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010088)]
        HRESULT _stdcall HorizontalAlignment([in] VARIANT RHS);
        [propget, helpcontext(0x00010268)]
        HRESULT _stdcall LockedText([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010268)]
        HRESULT _stdcall LockedText([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x00010086)]
        HRESULT _stdcall Orientation([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010086)]
        HRESULT _stdcall Orientation([in] VARIANT RHS);
        [propget, helpcontext(0x0001008a)]
        HRESULT _stdcall Text([out, retval] BSTR* RHS);
        [propput, helpcontext(0x0001008a)]
        HRESULT _stdcall Text([in] BSTR RHS);
        [propget, helpcontext(0x00010089)]
        HRESULT _stdcall VerticalAlignment([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010089)]
        HRESULT _stdcall VerticalAlignment([in] VARIANT RHS);
        [propget, helpcontext(0x000103cf)]
        HRESULT _stdcall ReadingOrder([out, retval] long* RHS);
        [propput, helpcontext(0x000103cf)]
        HRESULT _stdcall ReadingOrder([in] long RHS);
        [propget, helpcontext(0x00010080)]
        HRESULT _stdcall Border([out, retval] Border** RHS);
        [propget, helpcontext(0x00010081)]
        HRESULT _stdcall Interior([out, retval] Interior** RHS);
        [propget, helpcontext(0x00010067)]
        HRESULT _stdcall Shadow([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010067)]
        HRESULT _stdcall Shadow([in] VARIANT_BOOL RHS);
    };

    [
      odl,
      uuid(0002089F-0001-0000-C000-000000000046),
      helpcontext(0x0002005f),
      hidden
    ]
    interface IOvals : IDispatch {
        [propget, helpcontext(0x00010094)]
        HRESULT _stdcall Application([out, retval] Application** RHS);
        [propget, helpcontext(0x00010095)]
        HRESULT _stdcall Creator([out, retval] XlCreator* RHS);
        [propget, helpcontext(0x00010096)]
        HRESULT _stdcall Parent([out, retval] IDispatch** RHS);
        [restricted, hidden]
        void _stdcall _Dummy3();
        [helpcontext(0x0001025a)]
        HRESULT _stdcall BringToFront();
        [helpcontext(0x00010227)]
        HRESULT _stdcall Copy();
        [helpcontext(0x000100d5)]
        HRESULT _stdcall CopyPicture(
                        [in, optional, defaultvalue(2)] XlPictureAppearance Appearance, 
                        [in, optional, defaultvalue(-4147)] XlCopyPictureFormat Format);
        [helpcontext(0x00010235)]
        HRESULT _stdcall Cut();
        [helpcontext(0x00010075)]
        HRESULT _stdcall Delete();
        [helpcontext(0x0001040f)]
        HRESULT _stdcall Duplicate([out, retval] IDispatch** RHS);
        [propget, helpcontext(0x00010258)]
        HRESULT _stdcall Enabled([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010258)]
        HRESULT _stdcall Enabled([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x0001007b)]
        HRESULT _stdcall Height([out, retval] double* RHS);
        [propput, helpcontext(0x0001007b)]
        HRESULT _stdcall Height([in] double RHS);
        [restricted, hidden]
        void _stdcall _Dummy12();
        [propget, helpcontext(0x0001007f)]
        HRESULT _stdcall Left([out, retval] double* RHS);
        [propput, helpcontext(0x0001007f)]
        HRESULT _stdcall Left([in] double RHS);
        [propget, helpcontext(0x0001010d)]
        HRESULT _stdcall Locked([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x0001010d)]
        HRESULT _stdcall Locked([in] VARIANT_BOOL RHS);
        [restricted, hidden]
        void _stdcall _Dummy15();
        [propget, hidden, helpcontext(0x00010254)]
        HRESULT _stdcall OnAction([out, retval] BSTR* RHS);
        [propput, hidden, helpcontext(0x00010254)]
        HRESULT _stdcall OnAction([in] BSTR RHS);
        [propget, helpcontext(0x00010269)]
        HRESULT _stdcall Placement([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010269)]
        HRESULT _stdcall Placement([in] VARIANT RHS);
        [propget, helpcontext(0x0001026a)]
        HRESULT _stdcall PrintObject([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x0001026a)]
        HRESULT _stdcall PrintObject([in] VARIANT_BOOL RHS);
        [helpcontext(0x000100eb)]
        HRESULT _stdcall Select([in, optional] VARIANT Replace);
        [helpcontext(0x0001025d)]
        HRESULT _stdcall SendToBack();
        [propget, helpcontext(0x0001007e)]
        HRESULT _stdcall Top([out, retval] double* RHS);
        [propput, helpcontext(0x0001007e)]
        HRESULT _stdcall Top([in] double RHS);
        [restricted, hidden]
        void _stdcall _Dummy22();
        [propget, helpcontext(0x0001022e)]
        HRESULT _stdcall Visible([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x0001022e)]
        HRESULT _stdcall Visible([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x0001007a)]
        HRESULT _stdcall Width([out, retval] double* RHS);
        [propput, helpcontext(0x0001007a)]
        HRESULT _stdcall Width([in] double RHS);
        [propget, helpcontext(0x0001026e)]
        HRESULT _stdcall ZOrder([out, retval] long* RHS);
        [propget, helpcontext(0x000105f8)]
        HRESULT _stdcall ShapeRange([out, retval] ShapeRange** RHS);
        [propget, helpcontext(0x00010427)]
        HRESULT _stdcall AddIndent([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010427)]
        HRESULT _stdcall AddIndent([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x000105f5)]
        HRESULT _stdcall AutoScaleFont([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x000105f5)]
        HRESULT _stdcall AutoScaleFont([in] VARIANT RHS);
        [propget, helpcontext(0x00010266)]
        HRESULT _stdcall AutoSize([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010266)]
        HRESULT _stdcall AutoSize([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x0001008b)]
        HRESULT _stdcall Caption([out, retval] BSTR* RHS);
        [propput, helpcontext(0x0001008b)]
        HRESULT _stdcall Caption([in] BSTR RHS);
        [propget, helpcontext(0x0001025b)]
        HRESULT _stdcall Characters(
                        [in, optional] VARIANT Start, 
                        [in, optional] VARIANT Length, 
                        [out, retval] Characters** RHS);
        [helpcontext(0x000101f9)]
        HRESULT _stdcall CheckSpelling(
                        [in, optional] VARIANT CustomDictionary, 
                        [in, optional] VARIANT IgnoreUppercase, 
                        [in, optional] VARIANT AlwaysSuggest, 
                        [in, optional] VARIANT IgnoreInitialAlefHamza, 
                        [in, optional] VARIANT IgnoreFinalYaa, 
                        [in, optional] VARIANT SpellScript);
        [propget, helpcontext(0x00010092)]
        HRESULT _stdcall Font([out, retval] Font** RHS);
        [propget, helpcontext(0x00010105)]
        HRESULT _stdcall Formula([out, retval] BSTR* RHS);
        [propput, helpcontext(0x00010105)]
        HRESULT _stdcall Formula([in] BSTR RHS);
        [propget, helpcontext(0x00010088)]
        HRESULT _stdcall HorizontalAlignment([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010088)]
        HRESULT _stdcall HorizontalAlignment([in] VARIANT RHS);
        [propget, helpcontext(0x00010268)]
        HRESULT _stdcall LockedText([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010268)]
        HRESULT _stdcall LockedText([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x00010086)]
        HRESULT _stdcall Orientation([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010086)]
        HRESULT _stdcall Orientation([in] VARIANT RHS);
        [propget, helpcontext(0x0001008a)]
        HRESULT _stdcall Text([out, retval] BSTR* RHS);
        [propput, helpcontext(0x0001008a)]
        HRESULT _stdcall Text([in] BSTR RHS);
        [propget, helpcontext(0x00010089)]
        HRESULT _stdcall VerticalAlignment([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010089)]
        HRESULT _stdcall VerticalAlignment([in] VARIANT RHS);
        [propget, helpcontext(0x000103cf)]
        HRESULT _stdcall ReadingOrder([out, retval] long* RHS);
        [propput, helpcontext(0x000103cf)]
        HRESULT _stdcall ReadingOrder([in] long RHS);
        [propget, helpcontext(0x00010080)]
        HRESULT _stdcall Border([out, retval] Border** RHS);
        [propget, helpcontext(0x00010081)]
        HRESULT _stdcall Interior([out, retval] Interior** RHS);
        [propget, helpcontext(0x00010067)]
        HRESULT _stdcall Shadow([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010067)]
        HRESULT _stdcall Shadow([in] VARIANT_BOOL RHS);
        [helpcontext(0x000100b5)]
        HRESULT _stdcall Add(
                        [in] double Left, 
                        [in] double Top, 
                        [in] double Width, 
                        [in] double Height, 
                        [out, retval] Oval** RHS);
        [propget, helpcontext(0x00010076)]
        HRESULT _stdcall Count([out, retval] long* RHS);
        [helpcontext(0x0001002e)]
        HRESULT _stdcall Group([out, retval] GroupObject** RHS);
        [helpcontext(0x000100aa)]
        HRESULT _stdcall Item(
                        [in] VARIANT Index, 
                        [out, retval] IDispatch** RHS);
        [helpcontext(0x0000fffc)]
        HRESULT _stdcall _NewEnum([out, retval] IUnknown** RHS);
    };

    [
      odl,
      uuid(000208A0-0001-0000-C000-000000000046),
      helpcontext(0x00020060),
      hidden
    ]
    interface IArc : IDispatch {
        [propget, helpcontext(0x00010094)]
        HRESULT _stdcall Application([out, retval] Application** RHS);
        [propget, helpcontext(0x00010095)]
        HRESULT _stdcall Creator([out, retval] XlCreator* RHS);
        [propget, helpcontext(0x00010096)]
        HRESULT _stdcall Parent([out, retval] IDispatch** RHS);
        [propget, helpcontext(0x00010267)]
        HRESULT _stdcall BottomRightCell([out, retval] Range** RHS);
        [helpcontext(0x0001025a)]
        HRESULT _stdcall BringToFront();
        [helpcontext(0x00010227)]
        HRESULT _stdcall Copy();
        [helpcontext(0x000100d5)]
        HRESULT _stdcall CopyPicture(
                        [in, optional, defaultvalue(2)] XlPictureAppearance Appearance, 
                        [in, optional, defaultvalue(-4147)] XlCopyPictureFormat Format);
        [helpcontext(0x00010235)]
        HRESULT _stdcall Cut();
        [helpcontext(0x00010075)]
        HRESULT _stdcall Delete();
        [helpcontext(0x0001040f)]
        HRESULT _stdcall Duplicate([out, retval] IDispatch** RHS);
        [propget, helpcontext(0x00010258)]
        HRESULT _stdcall Enabled([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010258)]
        HRESULT _stdcall Enabled([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x0001007b)]
        HRESULT _stdcall Height([out, retval] double* RHS);
        [propput, helpcontext(0x0001007b)]
        HRESULT _stdcall Height([in] double RHS);
        [propget, helpcontext(0x000101e6)]
        HRESULT _stdcall Index([out, retval] long* RHS);
        [propget, helpcontext(0x0001007f)]
        HRESULT _stdcall Left([out, retval] double* RHS);
        [propput, helpcontext(0x0001007f)]
        HRESULT _stdcall Left([in] double RHS);
        [propget, helpcontext(0x0001010d)]
        HRESULT _stdcall Locked([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x0001010d)]
        HRESULT _stdcall Locked([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x0001006e)]
        HRESULT _stdcall Name([out, retval] BSTR* RHS);
        [propput, helpcontext(0x0001006e)]
        HRESULT _stdcall Name([in] BSTR RHS);
        [propget, hidden, helpcontext(0x00010254)]
        HRESULT _stdcall OnAction([out, retval] BSTR* RHS);
        [propput, hidden, helpcontext(0x00010254)]
        HRESULT _stdcall OnAction([in] BSTR RHS);
        [propget, helpcontext(0x00010269)]
        HRESULT _stdcall Placement([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010269)]
        HRESULT _stdcall Placement([in] VARIANT RHS);
        [propget, helpcontext(0x0001026a)]
        HRESULT _stdcall PrintObject([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x0001026a)]
        HRESULT _stdcall PrintObject([in] VARIANT_BOOL RHS);
        [helpcontext(0x000100eb)]
        HRESULT _stdcall Select([in, optional] VARIANT Replace);
        [helpcontext(0x0001025d)]
        HRESULT _stdcall SendToBack();
        [propget, helpcontext(0x0001007e)]
        HRESULT _stdcall Top([out, retval] double* RHS);
        [propput, helpcontext(0x0001007e)]
        HRESULT _stdcall Top([in] double RHS);
        [propget, helpcontext(0x0001026c)]
        HRESULT _stdcall TopLeftCell([out, retval] Range** RHS);
        [propget, helpcontext(0x0001022e)]
        HRESULT _stdcall Visible([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x0001022e)]
        HRESULT _stdcall Visible([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x0001007a)]
        HRESULT _stdcall Width([out, retval] double* RHS);
        [propput, helpcontext(0x0001007a)]
        HRESULT _stdcall Width([in] double RHS);
        [propget, helpcontext(0x0001026e)]
        HRESULT _stdcall ZOrder([out, retval] long* RHS);
        [propget, helpcontext(0x000105f8)]
        HRESULT _stdcall ShapeRange([out, retval] ShapeRange** RHS);
        [propget, helpcontext(0x00010427)]
        HRESULT _stdcall AddIndent([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010427)]
        HRESULT _stdcall AddIndent([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x000105f5)]
        HRESULT _stdcall AutoScaleFont([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x000105f5)]
        HRESULT _stdcall AutoScaleFont([in] VARIANT RHS);
        [propget, helpcontext(0x00010266)]
        HRESULT _stdcall AutoSize([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010266)]
        HRESULT _stdcall AutoSize([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x0001008b)]
        HRESULT _stdcall Caption([out, retval] BSTR* RHS);
        [propput, helpcontext(0x0001008b)]
        HRESULT _stdcall Caption([in] BSTR RHS);
        [propget, helpcontext(0x0001025b)]
        HRESULT _stdcall Characters(
                        [in, optional] VARIANT Start, 
                        [in, optional] VARIANT Length, 
                        [out, retval] Characters** RHS);
        [helpcontext(0x000101f9)]
        HRESULT _stdcall CheckSpelling(
                        [in, optional] VARIANT CustomDictionary, 
                        [in, optional] VARIANT IgnoreUppercase, 
                        [in, optional] VARIANT AlwaysSuggest, 
                        [in, optional] VARIANT IgnoreInitialAlefHamza, 
                        [in, optional] VARIANT IgnoreFinalYaa, 
                        [in, optional] VARIANT SpellScript);
        [propget, helpcontext(0x00010092)]
        HRESULT _stdcall Font([out, retval] Font** RHS);
        [propget, helpcontext(0x00010105)]
        HRESULT _stdcall Formula([out, retval] BSTR* RHS);
        [propput, helpcontext(0x00010105)]
        HRESULT _stdcall Formula([in] BSTR RHS);
        [propget, helpcontext(0x00010088)]
        HRESULT _stdcall HorizontalAlignment([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010088)]
        HRESULT _stdcall HorizontalAlignment([in] VARIANT RHS);
        [propget, helpcontext(0x00010268)]
        HRESULT _stdcall LockedText([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010268)]
        HRESULT _stdcall LockedText([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x00010086)]
        HRESULT _stdcall Orientation([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010086)]
        HRESULT _stdcall Orientation([in] VARIANT RHS);
        [propget, helpcontext(0x0001008a)]
        HRESULT _stdcall Text([out, retval] BSTR* RHS);
        [propput, helpcontext(0x0001008a)]
        HRESULT _stdcall Text([in] BSTR RHS);
        [propget, helpcontext(0x00010089)]
        HRESULT _stdcall VerticalAlignment([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010089)]
        HRESULT _stdcall VerticalAlignment([in] VARIANT RHS);
        [propget, helpcontext(0x000103cf)]
        HRESULT _stdcall ReadingOrder([out, retval] long* RHS);
        [propput, helpcontext(0x000103cf)]
        HRESULT _stdcall ReadingOrder([in] long RHS);
        [propget, helpcontext(0x00010080)]
        HRESULT _stdcall Border([out, retval] Border** RHS);
        [propget, helpcontext(0x00010081)]
        HRESULT _stdcall Interior([out, retval] Interior** RHS);
        [restricted, hidden]
        void _stdcall _Dummy43();
    };
