import "Excel08.Idl";


    [
      odl,
      uuid(0002088B-0001-0000-C000-000000000046),
      helpcontext(0x0002004b),
      hidden
    ]
    interface IDropDown : IDispatch {
        [propget, helpcontext(0x00010094)]
        HRESULT _stdcall Application([out, retval] Application** RHS);
        [propget, helpcontext(0x00010095)]
        HRESULT _stdcall Creator([out, retval] XlCreator* RHS);
        [propget, helpcontext(0x00010096)]
        HRESULT _stdcall Parent([out, retval] IDispatch** RHS);
        [propget, helpcontext(0x00010267)]
        HRESULT _stdcall BottomRightCell([out, retval] Range** RHS);
        [helpcontext(0x0001025a)]
        HRESULT _stdcall BringToFront();
        [helpcontext(0x00010227)]
        HRESULT _stdcall Copy();
        [helpcontext(0x000100d5)]
        HRESULT _stdcall CopyPicture(
                        [in, optional, defaultvalue(2)] XlPictureAppearance Appearance, 
                        [in, optional, defaultvalue(-4147)] XlCopyPictureFormat Format);
        [helpcontext(0x00010235)]
        HRESULT _stdcall Cut();
        [helpcontext(0x00010075)]
        HRESULT _stdcall Delete();
        [helpcontext(0x0001040f)]
        HRESULT _stdcall Duplicate([out, retval] IDispatch** RHS);
        [propget, helpcontext(0x00010258)]
        HRESULT _stdcall Enabled([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010258)]
        HRESULT _stdcall Enabled([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x0001007b)]
        HRESULT _stdcall Height([out, retval] double* RHS);
        [propput, helpcontext(0x0001007b)]
        HRESULT _stdcall Height([in] double RHS);
        [propget, helpcontext(0x000101e6)]
        HRESULT _stdcall Index([out, retval] long* RHS);
        [propget, helpcontext(0x0001007f)]
        HRESULT _stdcall Left([out, retval] double* RHS);
        [propput, helpcontext(0x0001007f)]
        HRESULT _stdcall Left([in] double RHS);
        [propget, helpcontext(0x0001010d)]
        HRESULT _stdcall Locked([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x0001010d)]
        HRESULT _stdcall Locked([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x0001006e)]
        HRESULT _stdcall Name([out, retval] BSTR* RHS);
        [propput, helpcontext(0x0001006e)]
        HRESULT _stdcall Name([in] BSTR RHS);
        [propget, hidden, helpcontext(0x00010254)]
        HRESULT _stdcall OnAction([out, retval] BSTR* RHS);
        [propput, hidden, helpcontext(0x00010254)]
        HRESULT _stdcall OnAction([in] BSTR RHS);
        [propget, helpcontext(0x00010269)]
        HRESULT _stdcall Placement([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010269)]
        HRESULT _stdcall Placement([in] VARIANT RHS);
        [propget, helpcontext(0x0001026a)]
        HRESULT _stdcall PrintObject([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x0001026a)]
        HRESULT _stdcall PrintObject([in] VARIANT_BOOL RHS);
        [helpcontext(0x000100eb)]
        HRESULT _stdcall Select([in, optional] VARIANT Replace);
        [helpcontext(0x0001025d)]
        HRESULT _stdcall SendToBack();
        [propget, helpcontext(0x0001007e)]
        HRESULT _stdcall Top([out, retval] double* RHS);
        [propput, helpcontext(0x0001007e)]
        HRESULT _stdcall Top([in] double RHS);
        [propget, helpcontext(0x0001026c)]
        HRESULT _stdcall TopLeftCell([out, retval] Range** RHS);
        [propget, helpcontext(0x0001022e)]
        HRESULT _stdcall Visible([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x0001022e)]
        HRESULT _stdcall Visible([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x0001007a)]
        HRESULT _stdcall Width([out, retval] double* RHS);
        [propput, helpcontext(0x0001007a)]
        HRESULT _stdcall Width([in] double RHS);
        [propget, helpcontext(0x0001026e)]
        HRESULT _stdcall ZOrder([out, retval] long* RHS);
        [propget, helpcontext(0x000105f8)]
        HRESULT _stdcall ShapeRange([out, retval] ShapeRange** RHS);
        [helpcontext(0x00010353)]
        HRESULT _stdcall AddItem(
                        [in] VARIANT Text, 
                        [in, optional] VARIANT Index);
        [propget, helpcontext(0x00010462)]
        HRESULT _stdcall Display3DShading([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010462)]
        HRESULT _stdcall Display3DShading([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x00010000)]
        HRESULT _stdcall _Default([out, retval] long* RHS);
        [propput, helpcontext(0x00010000)]
        HRESULT _stdcall _Default([in] long RHS);
        [propget, helpcontext(0x00010422)]
        HRESULT _stdcall LinkedCell([out, retval] BSTR* RHS);
        [propput, helpcontext(0x00010422)]
        HRESULT _stdcall LinkedCell([in] BSTR RHS);
        [propget, helpcontext(0x0001035e)]
        HRESULT _stdcall LinkedObject([out, retval] VARIANT* RHS);
        [helpcontext(0x0001035d)]
        HRESULT _stdcall List(
                        [in, optional] VARIANT Index, 
                        [out, retval] VARIANT* RHS);
        [propget, helpcontext(0x00010351)]
        HRESULT _stdcall ListCount([out, retval] long* RHS);
        [propget, helpcontext(0x0001034f)]
        HRESULT _stdcall ListFillRange([out, retval] BSTR* RHS);
        [propput, helpcontext(0x0001034f)]
        HRESULT _stdcall ListFillRange([in] BSTR RHS);
        [propget, helpcontext(0x00010352)]
        HRESULT _stdcall ListIndex([out, retval] long* RHS);
        [propput, helpcontext(0x00010352)]
        HRESULT _stdcall ListIndex([in] long RHS);
        [restricted, hidden]
        void _stdcall _Dummy36();
        [helpcontext(0x00010355)]
        HRESULT _stdcall RemoveAllItems();
        [helpcontext(0x00010354)]
        HRESULT _stdcall RemoveItem(
                        [in] long Index, 
                        [in, optional] VARIANT Count);
        [helpcontext(0x00010463)]
        HRESULT _stdcall Selected(
                        [in, optional] VARIANT Index, 
                        [out, retval] VARIANT* RHS);
        [propget, helpcontext(0x00010006)]
        HRESULT _stdcall Value([out, retval] long* RHS);
        [propput, helpcontext(0x00010006)]
        HRESULT _stdcall Value([in] long RHS);
        [propget, helpcontext(0x0001008b)]
        HRESULT _stdcall Caption([out, retval] BSTR* RHS);
        [propput, helpcontext(0x0001008b)]
        HRESULT _stdcall Caption([in] BSTR RHS);
        [propget, helpcontext(0x0001025b)]
        HRESULT _stdcall Characters(
                        [in, optional] VARIANT Start, 
                        [in, optional] VARIANT Length, 
                        [out, retval] Characters** RHS);
        [propget, helpcontext(0x00010350)]
        HRESULT _stdcall DropDownLines([out, retval] long* RHS);
        [propput, helpcontext(0x00010350)]
        HRESULT _stdcall DropDownLines([in] long RHS);
        [propget, helpcontext(0x0001008a)]
        HRESULT _stdcall Text([out, retval] BSTR* RHS);
        [propput, helpcontext(0x0001008a)]
        HRESULT _stdcall Text([in] BSTR RHS);
    };

    [
      odl,
      uuid(0002088C-0001-0000-C000-000000000046),
      helpcontext(0x0002004c),
      hidden
    ]
    interface IDropDowns : IDispatch {
        [propget, helpcontext(0x00010094)]
        HRESULT _stdcall Application([out, retval] Application** RHS);
        [propget, helpcontext(0x00010095)]
        HRESULT _stdcall Creator([out, retval] XlCreator* RHS);
        [propget, helpcontext(0x00010096)]
        HRESULT _stdcall Parent([out, retval] IDispatch** RHS);
        [restricted, hidden]
        void _stdcall _Dummy3();
        [helpcontext(0x0001025a)]
        HRESULT _stdcall BringToFront();
        [helpcontext(0x00010227)]
        HRESULT _stdcall Copy();
        [helpcontext(0x000100d5)]
        HRESULT _stdcall CopyPicture(
                        [in, optional, defaultvalue(2)] XlPictureAppearance Appearance, 
                        [in, optional, defaultvalue(-4147)] XlCopyPictureFormat Format);
        [helpcontext(0x00010235)]
        HRESULT _stdcall Cut();
        [helpcontext(0x00010075)]
        HRESULT _stdcall Delete();
        [helpcontext(0x0001040f)]
        HRESULT _stdcall Duplicate([out, retval] IDispatch** RHS);
        [propget, helpcontext(0x00010258)]
        HRESULT _stdcall Enabled([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010258)]
        HRESULT _stdcall Enabled([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x0001007b)]
        HRESULT _stdcall Height([out, retval] double* RHS);
        [propput, helpcontext(0x0001007b)]
        HRESULT _stdcall Height([in] double RHS);
        [restricted, hidden]
        void _stdcall _Dummy12();
        [propget, helpcontext(0x0001007f)]
        HRESULT _stdcall Left([out, retval] double* RHS);
        [propput, helpcontext(0x0001007f)]
        HRESULT _stdcall Left([in] double RHS);
        [propget, helpcontext(0x0001010d)]
        HRESULT _stdcall Locked([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x0001010d)]
        HRESULT _stdcall Locked([in] VARIANT_BOOL RHS);
        [restricted, hidden]
        void _stdcall _Dummy15();
        [propget, hidden, helpcontext(0x00010254)]
        HRESULT _stdcall OnAction([out, retval] BSTR* RHS);
        [propput, hidden, helpcontext(0x00010254)]
        HRESULT _stdcall OnAction([in] BSTR RHS);
        [propget, helpcontext(0x00010269)]
        HRESULT _stdcall Placement([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010269)]
        HRESULT _stdcall Placement([in] VARIANT RHS);
        [propget, helpcontext(0x0001026a)]
        HRESULT _stdcall PrintObject([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x0001026a)]
        HRESULT _stdcall PrintObject([in] VARIANT_BOOL RHS);
        [helpcontext(0x000100eb)]
        HRESULT _stdcall Select([in, optional] VARIANT Replace);
        [helpcontext(0x0001025d)]
        HRESULT _stdcall SendToBack();
        [propget, helpcontext(0x0001007e)]
        HRESULT _stdcall Top([out, retval] double* RHS);
        [propput, helpcontext(0x0001007e)]
        HRESULT _stdcall Top([in] double RHS);
        [restricted, hidden]
        void _stdcall _Dummy22();
        [propget, helpcontext(0x0001022e)]
        HRESULT _stdcall Visible([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x0001022e)]
        HRESULT _stdcall Visible([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x0001007a)]
        HRESULT _stdcall Width([out, retval] double* RHS);
        [propput, helpcontext(0x0001007a)]
        HRESULT _stdcall Width([in] double RHS);
        [propget, helpcontext(0x0001026e)]
        HRESULT _stdcall ZOrder([out, retval] long* RHS);
        [propget, helpcontext(0x000105f8)]
        HRESULT _stdcall ShapeRange([out, retval] ShapeRange** RHS);
        [helpcontext(0x00010353)]
        HRESULT _stdcall AddItem(
                        [in] VARIANT Text, 
                        [in, optional] VARIANT Index);
        [propget, helpcontext(0x00010462)]
        HRESULT _stdcall Display3DShading([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010462)]
        HRESULT _stdcall Display3DShading([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x00010000)]
        HRESULT _stdcall _Default([out, retval] long* RHS);
        [propput, helpcontext(0x00010000)]
        HRESULT _stdcall _Default([in] long RHS);
        [propget, helpcontext(0x00010422)]
        HRESULT _stdcall LinkedCell([out, retval] BSTR* RHS);
        [propput, helpcontext(0x00010422)]
        HRESULT _stdcall LinkedCell([in] BSTR RHS);
        [restricted, hidden]
        void _stdcall _Dummy31();
        [helpcontext(0x0001035d)]
        HRESULT _stdcall List(
                        [in, optional] VARIANT Index, 
                        [out, retval] VARIANT* RHS);
        [restricted, hidden]
        void _stdcall _Dummy33();
        [propget, helpcontext(0x0001034f)]
        HRESULT _stdcall ListFillRange([out, retval] BSTR* RHS);
        [propput, helpcontext(0x0001034f)]
        HRESULT _stdcall ListFillRange([in] BSTR RHS);
        [propget, helpcontext(0x00010352)]
        HRESULT _stdcall ListIndex([out, retval] long* RHS);
        [propput, helpcontext(0x00010352)]
        HRESULT _stdcall ListIndex([in] long RHS);
        [restricted, hidden]
        void _stdcall _Dummy36();
        [helpcontext(0x00010355)]
        HRESULT _stdcall RemoveAllItems();
        [helpcontext(0x00010354)]
        HRESULT _stdcall RemoveItem(
                        [in] long Index, 
                        [in, optional] VARIANT Count);
        [helpcontext(0x00010463)]
        HRESULT _stdcall Selected(
                        [in, optional] VARIANT Index, 
                        [out, retval] VARIANT* RHS);
        [propget, helpcontext(0x00010006)]
        HRESULT _stdcall Value([out, retval] long* RHS);
        [propput, helpcontext(0x00010006)]
        HRESULT _stdcall Value([in] long RHS);
        [propget, helpcontext(0x0001008b)]
        HRESULT _stdcall Caption([out, retval] BSTR* RHS);
        [propput, helpcontext(0x0001008b)]
        HRESULT _stdcall Caption([in] BSTR RHS);
        [propget, helpcontext(0x0001025b)]
        HRESULT _stdcall Characters(
                        [in, optional] VARIANT Start, 
                        [in, optional] VARIANT Length, 
                        [out, retval] Characters** RHS);
        [propget, helpcontext(0x00010350)]
        HRESULT _stdcall DropDownLines([out, retval] long* RHS);
        [propput, helpcontext(0x00010350)]
        HRESULT _stdcall DropDownLines([in] long RHS);
        [propget, helpcontext(0x0001008a)]
        HRESULT _stdcall Text([out, retval] BSTR* RHS);
        [propput, helpcontext(0x0001008a)]
        HRESULT _stdcall Text([in] BSTR RHS);
        [helpcontext(0x000100b5)]
        HRESULT _stdcall Add(
                        [in] double Left, 
                        [in] double Top, 
                        [in] double Width, 
                        [in] double Height, 
                        [in, optional] VARIANT Editable, 
                        [out, retval] DropDown** RHS);
        [propget, helpcontext(0x00010076)]
        HRESULT _stdcall Count([out, retval] long* RHS);
        [helpcontext(0x0001002e)]
        HRESULT _stdcall Group([out, retval] GroupObject** RHS);
        [helpcontext(0x000100aa)]
        HRESULT _stdcall Item(
                        [in] VARIANT Index, 
                        [out, retval] IDispatch** RHS);
        [helpcontext(0x0000fffc)]
        HRESULT _stdcall _NewEnum([out, retval] IUnknown** RHS);
    };

    [
      odl,
      uuid(0002088D-0001-0000-C000-000000000046),
      helpcontext(0x0002004d),
      hidden
    ]
    interface ISpinner : IDispatch {
        [propget, helpcontext(0x00010094)]
        HRESULT _stdcall Application([out, retval] Application** RHS);
        [propget, helpcontext(0x00010095)]
        HRESULT _stdcall Creator([out, retval] XlCreator* RHS);
        [propget, helpcontext(0x00010096)]
        HRESULT _stdcall Parent([out, retval] IDispatch** RHS);
        [propget, helpcontext(0x00010267)]
        HRESULT _stdcall BottomRightCell([out, retval] Range** RHS);
        [helpcontext(0x0001025a)]
        HRESULT _stdcall BringToFront();
        [helpcontext(0x00010227)]
        HRESULT _stdcall Copy();
        [helpcontext(0x000100d5)]
        HRESULT _stdcall CopyPicture(
                        [in, optional, defaultvalue(2)] XlPictureAppearance Appearance, 
                        [in, optional, defaultvalue(-4147)] XlCopyPictureFormat Format);
        [helpcontext(0x00010235)]
        HRESULT _stdcall Cut();
        [helpcontext(0x00010075)]
        HRESULT _stdcall Delete();
        [helpcontext(0x0001040f)]
        HRESULT _stdcall Duplicate([out, retval] IDispatch** RHS);
        [propget, helpcontext(0x00010258)]
        HRESULT _stdcall Enabled([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010258)]
        HRESULT _stdcall Enabled([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x0001007b)]
        HRESULT _stdcall Height([out, retval] double* RHS);
        [propput, helpcontext(0x0001007b)]
        HRESULT _stdcall Height([in] double RHS);
        [propget, helpcontext(0x000101e6)]
        HRESULT _stdcall Index([out, retval] long* RHS);
        [propget, helpcontext(0x0001007f)]
        HRESULT _stdcall Left([out, retval] double* RHS);
        [propput, helpcontext(0x0001007f)]
        HRESULT _stdcall Left([in] double RHS);
        [propget, helpcontext(0x0001010d)]
        HRESULT _stdcall Locked([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x0001010d)]
        HRESULT _stdcall Locked([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x0001006e)]
        HRESULT _stdcall Name([out, retval] BSTR* RHS);
        [propput, helpcontext(0x0001006e)]
        HRESULT _stdcall Name([in] BSTR RHS);
        [propget, hidden, helpcontext(0x00010254)]
        HRESULT _stdcall OnAction([out, retval] BSTR* RHS);
        [propput, hidden, helpcontext(0x00010254)]
        HRESULT _stdcall OnAction([in] BSTR RHS);
        [propget, helpcontext(0x00010269)]
        HRESULT _stdcall Placement([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010269)]
        HRESULT _stdcall Placement([in] VARIANT RHS);
        [propget, helpcontext(0x0001026a)]
        HRESULT _stdcall PrintObject([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x0001026a)]
        HRESULT _stdcall PrintObject([in] VARIANT_BOOL RHS);
        [helpcontext(0x000100eb)]
        HRESULT _stdcall Select([in, optional] VARIANT Replace);
        [helpcontext(0x0001025d)]
        HRESULT _stdcall SendToBack();
        [propget, helpcontext(0x0001007e)]
        HRESULT _stdcall Top([out, retval] double* RHS);
        [propput, helpcontext(0x0001007e)]
        HRESULT _stdcall Top([in] double RHS);
        [propget, helpcontext(0x0001026c)]
        HRESULT _stdcall TopLeftCell([out, retval] Range** RHS);
        [propget, helpcontext(0x0001022e)]
        HRESULT _stdcall Visible([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x0001022e)]
        HRESULT _stdcall Visible([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x0001007a)]
        HRESULT _stdcall Width([out, retval] double* RHS);
        [propput, helpcontext(0x0001007a)]
        HRESULT _stdcall Width([in] double RHS);
        [propget, helpcontext(0x0001026e)]
        HRESULT _stdcall ZOrder([out, retval] long* RHS);
        [propget, helpcontext(0x000105f8)]
        HRESULT _stdcall ShapeRange([out, retval] ShapeRange** RHS);
        [propget, helpcontext(0x00010000)]
        HRESULT _stdcall _Default([out, retval] long* RHS);
        [propput, helpcontext(0x00010000)]
        HRESULT _stdcall _Default([in] long RHS);
        [propget, helpcontext(0x00010462)]
        HRESULT _stdcall Display3DShading([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010462)]
        HRESULT _stdcall Display3DShading([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x00010422)]
        HRESULT _stdcall LinkedCell([out, retval] BSTR* RHS);
        [propput, helpcontext(0x00010422)]
        HRESULT _stdcall LinkedCell([in] BSTR RHS);
        [propget, helpcontext(0x0001034a)]
        HRESULT _stdcall Max([out, retval] long* RHS);
        [propput, helpcontext(0x0001034a)]
        HRESULT _stdcall Max([in] long RHS);
        [propget, helpcontext(0x0001034b)]
        HRESULT _stdcall Min([out, retval] long* RHS);
        [propput, helpcontext(0x0001034b)]
        HRESULT _stdcall Min([in] long RHS);
        [propget, helpcontext(0x0001034c)]
        HRESULT _stdcall SmallChange([out, retval] long* RHS);
        [propput, helpcontext(0x0001034c)]
        HRESULT _stdcall SmallChange([in] long RHS);
        [propget, helpcontext(0x00010006)]
        HRESULT _stdcall Value([out, retval] long* RHS);
        [propput, helpcontext(0x00010006)]
        HRESULT _stdcall Value([in] long RHS);
    };

    [
      odl,
      uuid(0002088E-0001-0000-C000-000000000046),
      helpcontext(0x0002004e),
      hidden
    ]
    interface ISpinners : IDispatch {
        [propget, helpcontext(0x00010094)]
        HRESULT _stdcall Application([out, retval] Application** RHS);
        [propget, helpcontext(0x00010095)]
        HRESULT _stdcall Creator([out, retval] XlCreator* RHS);
        [propget, helpcontext(0x00010096)]
        HRESULT _stdcall Parent([out, retval] IDispatch** RHS);
        [restricted, hidden]
        void _stdcall _Dummy3();
        [helpcontext(0x0001025a)]
        HRESULT _stdcall BringToFront();
        [helpcontext(0x00010227)]
        HRESULT _stdcall Copy();
        [helpcontext(0x000100d5)]
        HRESULT _stdcall CopyPicture(
                        [in, optional, defaultvalue(2)] XlPictureAppearance Appearance, 
                        [in, optional, defaultvalue(-4147)] XlCopyPictureFormat Format);
        [helpcontext(0x00010235)]
        HRESULT _stdcall Cut();
        [helpcontext(0x00010075)]
        HRESULT _stdcall Delete();
        [helpcontext(0x0001040f)]
        HRESULT _stdcall Duplicate([out, retval] IDispatch** RHS);
        [propget, helpcontext(0x00010258)]
        HRESULT _stdcall Enabled([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010258)]
        HRESULT _stdcall Enabled([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x0001007b)]
        HRESULT _stdcall Height([out, retval] double* RHS);
        [propput, helpcontext(0x0001007b)]
        HRESULT _stdcall Height([in] double RHS);
        [restricted, hidden]
        void _stdcall _Dummy12();
        [propget, helpcontext(0x0001007f)]
        HRESULT _stdcall Left([out, retval] double* RHS);
        [propput, helpcontext(0x0001007f)]
        HRESULT _stdcall Left([in] double RHS);
        [propget, helpcontext(0x0001010d)]
        HRESULT _stdcall Locked([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x0001010d)]
        HRESULT _stdcall Locked([in] VARIANT_BOOL RHS);
        [restricted, hidden]
        void _stdcall _Dummy15();
        [propget, hidden, helpcontext(0x00010254)]
        HRESULT _stdcall OnAction([out, retval] BSTR* RHS);
        [propput, hidden, helpcontext(0x00010254)]
        HRESULT _stdcall OnAction([in] BSTR RHS);
        [propget, helpcontext(0x00010269)]
        HRESULT _stdcall Placement([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010269)]
        HRESULT _stdcall Placement([in] VARIANT RHS);
        [propget, helpcontext(0x0001026a)]
        HRESULT _stdcall PrintObject([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x0001026a)]
        HRESULT _stdcall PrintObject([in] VARIANT_BOOL RHS);
        [helpcontext(0x000100eb)]
        HRESULT _stdcall Select([in, optional] VARIANT Replace);
        [helpcontext(0x0001025d)]
        HRESULT _stdcall SendToBack();
        [propget, helpcontext(0x0001007e)]
        HRESULT _stdcall Top([out, retval] double* RHS);
        [propput, helpcontext(0x0001007e)]
        HRESULT _stdcall Top([in] double RHS);
        [restricted, hidden]
        void _stdcall _Dummy22();
        [propget, helpcontext(0x0001022e)]
        HRESULT _stdcall Visible([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x0001022e)]
        HRESULT _stdcall Visible([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x0001007a)]
        HRESULT _stdcall Width([out, retval] double* RHS);
        [propput, helpcontext(0x0001007a)]
        HRESULT _stdcall Width([in] double RHS);
        [propget, helpcontext(0x0001026e)]
        HRESULT _stdcall ZOrder([out, retval] long* RHS);
        [propget, helpcontext(0x000105f8)]
        HRESULT _stdcall ShapeRange([out, retval] ShapeRange** RHS);
        [propget, helpcontext(0x00010000)]
        HRESULT _stdcall _Default([out, retval] long* RHS);
        [propput, helpcontext(0x00010000)]
        HRESULT _stdcall _Default([in] long RHS);
        [propget, helpcontext(0x00010462)]
        HRESULT _stdcall Display3DShading([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010462)]
        HRESULT _stdcall Display3DShading([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x00010422)]
        HRESULT _stdcall LinkedCell([out, retval] BSTR* RHS);
        [propput, helpcontext(0x00010422)]
        HRESULT _stdcall LinkedCell([in] BSTR RHS);
        [propget, helpcontext(0x0001034a)]
        HRESULT _stdcall Max([out, retval] long* RHS);
        [propput, helpcontext(0x0001034a)]
        HRESULT _stdcall Max([in] long RHS);
        [propget, helpcontext(0x0001034b)]
        HRESULT _stdcall Min([out, retval] long* RHS);
        [propput, helpcontext(0x0001034b)]
        HRESULT _stdcall Min([in] long RHS);
        [propget, helpcontext(0x0001034c)]
        HRESULT _stdcall SmallChange([out, retval] long* RHS);
        [propput, helpcontext(0x0001034c)]
        HRESULT _stdcall SmallChange([in] long RHS);
        [propget, helpcontext(0x00010006)]
        HRESULT _stdcall Value([out, retval] long* RHS);
        [propput, helpcontext(0x00010006)]
        HRESULT _stdcall Value([in] long RHS);
        [helpcontext(0x000100b5)]
        HRESULT _stdcall Add(
                        [in] double Left, 
                        [in] double Top, 
                        [in] double Width, 
                        [in] double Height, 
                        [out, retval] Spinner** RHS);
        [propget, helpcontext(0x00010076)]
        HRESULT _stdcall Count([out, retval] long* RHS);
        [helpcontext(0x0001002e)]
        HRESULT _stdcall Group([out, retval] GroupObject** RHS);
        [helpcontext(0x000100aa)]
        HRESULT _stdcall Item(
                        [in] VARIANT Index, 
                        [out, retval] IDispatch** RHS);
        [helpcontext(0x0000fffc)]
        HRESULT _stdcall _NewEnum([out, retval] IUnknown** RHS);
    };

    [
      odl,
      uuid(0002088F-0001-0000-C000-000000000046),
      helpcontext(0x0002004f),
      hidden
    ]
    interface IDialogFrame : IDispatch {
        [propget, helpcontext(0x00010094)]
        HRESULT _stdcall Application([out, retval] Application** RHS);
        [propget, helpcontext(0x00010095)]
        HRESULT _stdcall Creator([out, retval] XlCreator* RHS);
        [propget, helpcontext(0x00010096)]
        HRESULT _stdcall Parent([out, retval] IDispatch** RHS);
        [restricted, hidden]
        void _stdcall _Dummy3();
        [restricted, hidden]
        void _stdcall _Dummy4();
        [restricted, hidden]
        void _stdcall _Dummy5();
        [helpcontext(0x000100d5)]
        HRESULT _stdcall CopyPicture(
                        [in, optional, defaultvalue(2)] XlPictureAppearance Appearance, 
                        [in, optional, defaultvalue(-4147)] XlCopyPictureFormat Format);
        [restricted, hidden]
        void _stdcall _Dummy7();
        [restricted, hidden]
        void _stdcall _Dummy8();
        [restricted, hidden]
        void _stdcall _Dummy9();
        [restricted, hidden]
        void _stdcall _Dummy10();
        [propget, helpcontext(0x0001007b)]
        HRESULT _stdcall Height([out, retval] double* RHS);
        [propput, helpcontext(0x0001007b)]
        HRESULT _stdcall Height([in] double RHS);
        [restricted, hidden]
        void _stdcall _Dummy12();
        [propget, helpcontext(0x0001007f)]
        HRESULT _stdcall Left([out, retval] double* RHS);
        [propput, helpcontext(0x0001007f)]
        HRESULT _stdcall Left([in] double RHS);
        [propget, helpcontext(0x0001010d)]
        HRESULT _stdcall Locked([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x0001010d)]
        HRESULT _stdcall Locked([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x0001006e)]
        HRESULT _stdcall Name([out, retval] BSTR* RHS);
        [propput, helpcontext(0x0001006e)]
        HRESULT _stdcall Name([in] BSTR RHS);
        [propget, hidden, helpcontext(0x00010254)]
        HRESULT _stdcall OnAction([out, retval] BSTR* RHS);
        [propput, hidden, helpcontext(0x00010254)]
        HRESULT _stdcall OnAction([in] BSTR RHS);
        [restricted, hidden]
        void _stdcall _Dummy17();
        [restricted, hidden]
        void _stdcall _Dummy18();
        [helpcontext(0x000100eb)]
        HRESULT _stdcall Select([in, optional] VARIANT Replace);
        [restricted, hidden]
        void _stdcall _Dummy20();
        [propget, helpcontext(0x0001007e)]
        HRESULT _stdcall Top([out, retval] double* RHS);
        [propput, helpcontext(0x0001007e)]
        HRESULT _stdcall Top([in] double RHS);
        [restricted, hidden]
        void _stdcall _Dummy22();
        [restricted, hidden]
        void _stdcall _Dummy23();
        [propget, helpcontext(0x0001007a)]
        HRESULT _stdcall Width([out, retval] double* RHS);
        [propput, helpcontext(0x0001007a)]
        HRESULT _stdcall Width([in] double RHS);
        [restricted, hidden]
        void _stdcall _Dummy25();
        [propget, helpcontext(0x000105f8)]
        HRESULT _stdcall ShapeRange([out, retval] ShapeRange** RHS);
        [propget, helpcontext(0x0001008b)]
        HRESULT _stdcall Caption([out, retval] BSTR* RHS);
        [propput, helpcontext(0x0001008b)]
        HRESULT _stdcall Caption([in] BSTR RHS);
        [propget, helpcontext(0x0001025b)]
        HRESULT _stdcall Characters(
                        [in, optional] VARIANT Start, 
                        [in, optional] VARIANT Length, 
                        [out, retval] Characters** RHS);
        [helpcontext(0x000101f9)]
        HRESULT _stdcall CheckSpelling(
                        [in, optional] VARIANT CustomDictionary, 
                        [in, optional] VARIANT IgnoreUppercase, 
                        [in, optional] VARIANT AlwaysSuggest, 
                        [in, optional] VARIANT IgnoreInitialAlefHamza, 
                        [in, optional] VARIANT IgnoreFinalYaa, 
                        [in, optional] VARIANT SpellScript);
        [propget, helpcontext(0x00010268)]
        HRESULT _stdcall LockedText([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010268)]
        HRESULT _stdcall LockedText([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x0001008a)]
        HRESULT _stdcall Text([out, retval] BSTR* RHS);
        [propput, helpcontext(0x0001008a)]
        HRESULT _stdcall Text([in] BSTR RHS);
    };

    [
      odl,
      uuid(00020890-0001-0000-C000-000000000046),
      helpcontext(0x00020050),
      hidden
    ]
    interface ILabel : IDispatch {
        [propget, helpcontext(0x00010094)]
        HRESULT _stdcall Application([out, retval] Application** RHS);
        [propget, helpcontext(0x00010095)]
        HRESULT _stdcall Creator([out, retval] XlCreator* RHS);
        [propget, helpcontext(0x00010096)]
        HRESULT _stdcall Parent([out, retval] IDispatch** RHS);
        [propget, helpcontext(0x00010267)]
        HRESULT _stdcall BottomRightCell([out, retval] Range** RHS);
        [helpcontext(0x0001025a)]
        HRESULT _stdcall BringToFront();
        [helpcontext(0x00010227)]
        HRESULT _stdcall Copy();
        [helpcontext(0x000100d5)]
        HRESULT _stdcall CopyPicture(
                        [in, optional, defaultvalue(2)] XlPictureAppearance Appearance, 
                        [in, optional, defaultvalue(-4147)] XlCopyPictureFormat Format);
        [helpcontext(0x00010235)]
        HRESULT _stdcall Cut();
        [helpcontext(0x00010075)]
        HRESULT _stdcall Delete();
        [helpcontext(0x0001040f)]
        HRESULT _stdcall Duplicate([out, retval] IDispatch** RHS);
        [propget, helpcontext(0x00010258)]
        HRESULT _stdcall Enabled([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010258)]
        HRESULT _stdcall Enabled([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x0001007b)]
        HRESULT _stdcall Height([out, retval] double* RHS);
        [propput, helpcontext(0x0001007b)]
        HRESULT _stdcall Height([in] double RHS);
        [propget, helpcontext(0x000101e6)]
        HRESULT _stdcall Index([out, retval] long* RHS);
        [propget, helpcontext(0x0001007f)]
        HRESULT _stdcall Left([out, retval] double* RHS);
        [propput, helpcontext(0x0001007f)]
        HRESULT _stdcall Left([in] double RHS);
        [propget, helpcontext(0x0001010d)]
        HRESULT _stdcall Locked([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x0001010d)]
        HRESULT _stdcall Locked([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x0001006e)]
        HRESULT _stdcall Name([out, retval] BSTR* RHS);
        [propput, helpcontext(0x0001006e)]
        HRESULT _stdcall Name([in] BSTR RHS);
        [propget, hidden, helpcontext(0x00010254)]
        HRESULT _stdcall OnAction([out, retval] BSTR* RHS);
        [propput, hidden, helpcontext(0x00010254)]
        HRESULT _stdcall OnAction([in] BSTR RHS);
        [propget, helpcontext(0x00010269)]
        HRESULT _stdcall Placement([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010269)]
        HRESULT _stdcall Placement([in] VARIANT RHS);
        [propget, helpcontext(0x0001026a)]
        HRESULT _stdcall PrintObject([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x0001026a)]
        HRESULT _stdcall PrintObject([in] VARIANT_BOOL RHS);
        [helpcontext(0x000100eb)]
        HRESULT _stdcall Select([in, optional] VARIANT Replace);
        [helpcontext(0x0001025d)]
        HRESULT _stdcall SendToBack();
        [propget, helpcontext(0x0001007e)]
        HRESULT _stdcall Top([out, retval] double* RHS);
        [propput, helpcontext(0x0001007e)]
        HRESULT _stdcall Top([in] double RHS);
        [propget, helpcontext(0x0001026c)]
        HRESULT _stdcall TopLeftCell([out, retval] Range** RHS);
        [propget, helpcontext(0x0001022e)]
        HRESULT _stdcall Visible([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x0001022e)]
        HRESULT _stdcall Visible([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x0001007a)]
        HRESULT _stdcall Width([out, retval] double* RHS);
        [propput, helpcontext(0x0001007a)]
        HRESULT _stdcall Width([in] double RHS);
        [propget, helpcontext(0x0001026e)]
        HRESULT _stdcall ZOrder([out, retval] long* RHS);
        [propget, helpcontext(0x000105f8)]
        HRESULT _stdcall ShapeRange([out, retval] ShapeRange** RHS);
        [propget, helpcontext(0x0001008b)]
        HRESULT _stdcall Caption([out, retval] BSTR* RHS);
        [propput, helpcontext(0x0001008b)]
        HRESULT _stdcall Caption([in] BSTR RHS);
        [propget, helpcontext(0x0001025b)]
        HRESULT _stdcall Characters(
                        [in, optional] VARIANT Start, 
                        [in, optional] VARIANT Length, 
                        [out, retval] Characters** RHS);
        [helpcontext(0x000101f9)]
        HRESULT _stdcall CheckSpelling(
                        [in, optional] VARIANT CustomDictionary, 
                        [in, optional] VARIANT IgnoreUppercase, 
                        [in, optional] VARIANT AlwaysSuggest, 
                        [in, optional] VARIANT IgnoreInitialAlefHamza, 
                        [in, optional] VARIANT IgnoreFinalYaa, 
                        [in, optional] VARIANT SpellScript);
        [propget, helpcontext(0x00010268)]
        HRESULT _stdcall LockedText([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010268)]
        HRESULT _stdcall LockedText([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x0001008a)]
        HRESULT _stdcall Text([out, retval] BSTR* RHS);
        [propput, helpcontext(0x0001008a)]
        HRESULT _stdcall Text([in] BSTR RHS);
        [propget, helpcontext(0x0001034e)]
        HRESULT _stdcall Accelerator([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x0001034e)]
        HRESULT _stdcall Accelerator([in] VARIANT RHS);
        [restricted, hidden]
        void _stdcall _Dummy33();
        [propget, helpcontext(0x00010461)]
        HRESULT _stdcall PhoneticAccelerator([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010461)]
        HRESULT _stdcall PhoneticAccelerator([in] VARIANT RHS);
    };

    [
      odl,
      uuid(00020891-0001-0000-C000-000000000046),
      helpcontext(0x00020051),
      hidden
    ]
    interface ILabels : IDispatch {
        [propget, helpcontext(0x00010094)]
        HRESULT _stdcall Application([out, retval] Application** RHS);
        [propget, helpcontext(0x00010095)]
        HRESULT _stdcall Creator([out, retval] XlCreator* RHS);
        [propget, helpcontext(0x00010096)]
        HRESULT _stdcall Parent([out, retval] IDispatch** RHS);
        [restricted, hidden]
        void _stdcall _Dummy3();
        [helpcontext(0x0001025a)]
        HRESULT _stdcall BringToFront();
        [helpcontext(0x00010227)]
        HRESULT _stdcall Copy();
        [helpcontext(0x000100d5)]
        HRESULT _stdcall CopyPicture(
                        [in, optional, defaultvalue(2)] XlPictureAppearance Appearance, 
                        [in, optional, defaultvalue(-4147)] XlCopyPictureFormat Format);
        [helpcontext(0x00010235)]
        HRESULT _stdcall Cut();
        [helpcontext(0x00010075)]
        HRESULT _stdcall Delete();
        [helpcontext(0x0001040f)]
        HRESULT _stdcall Duplicate([out, retval] IDispatch** RHS);
        [propget, helpcontext(0x00010258)]
        HRESULT _stdcall Enabled([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010258)]
        HRESULT _stdcall Enabled([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x0001007b)]
        HRESULT _stdcall Height([out, retval] double* RHS);
        [propput, helpcontext(0x0001007b)]
        HRESULT _stdcall Height([in] double RHS);
        [restricted, hidden]
        void _stdcall _Dummy12();
        [propget, helpcontext(0x0001007f)]
        HRESULT _stdcall Left([out, retval] double* RHS);
        [propput, helpcontext(0x0001007f)]
        HRESULT _stdcall Left([in] double RHS);
        [propget, helpcontext(0x0001010d)]
        HRESULT _stdcall Locked([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x0001010d)]
        HRESULT _stdcall Locked([in] VARIANT_BOOL RHS);
        [restricted, hidden]
        void _stdcall _Dummy15();
        [propget, hidden, helpcontext(0x00010254)]
        HRESULT _stdcall OnAction([out, retval] BSTR* RHS);
        [propput, hidden, helpcontext(0x00010254)]
        HRESULT _stdcall OnAction([in] BSTR RHS);
        [propget, helpcontext(0x00010269)]
        HRESULT _stdcall Placement([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010269)]
        HRESULT _stdcall Placement([in] VARIANT RHS);
        [propget, helpcontext(0x0001026a)]
        HRESULT _stdcall PrintObject([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x0001026a)]
        HRESULT _stdcall PrintObject([in] VARIANT_BOOL RHS);
        [helpcontext(0x000100eb)]
        HRESULT _stdcall Select([in, optional] VARIANT Replace);
        [helpcontext(0x0001025d)]
        HRESULT _stdcall SendToBack();
        [propget, helpcontext(0x0001007e)]
        HRESULT _stdcall Top([out, retval] double* RHS);
        [propput, helpcontext(0x0001007e)]
        HRESULT _stdcall Top([in] double RHS);
        [restricted, hidden]
        void _stdcall _Dummy22();
        [propget, helpcontext(0x0001022e)]
        HRESULT _stdcall Visible([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x0001022e)]
        HRESULT _stdcall Visible([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x0001007a)]
        HRESULT _stdcall Width([out, retval] double* RHS);
        [propput, helpcontext(0x0001007a)]
        HRESULT _stdcall Width([in] double RHS);
        [propget, helpcontext(0x0001026e)]
        HRESULT _stdcall ZOrder([out, retval] long* RHS);
        [propget, helpcontext(0x000105f8)]
        HRESULT _stdcall ShapeRange([out, retval] ShapeRange** RHS);
        [propget, helpcontext(0x0001008b)]
        HRESULT _stdcall Caption([out, retval] BSTR* RHS);
        [propput, helpcontext(0x0001008b)]
        HRESULT _stdcall Caption([in] BSTR RHS);
        [propget, helpcontext(0x0001025b)]
        HRESULT _stdcall Characters(
                        [in, optional] VARIANT Start, 
                        [in, optional] VARIANT Length, 
                        [out, retval] Characters** RHS);
        [helpcontext(0x000101f9)]
        HRESULT _stdcall CheckSpelling(
                        [in, optional] VARIANT CustomDictionary, 
                        [in, optional] VARIANT IgnoreUppercase, 
                        [in, optional] VARIANT AlwaysSuggest, 
                        [in, optional] VARIANT IgnoreInitialAlefHamza, 
                        [in, optional] VARIANT IgnoreFinalYaa, 
                        [in, optional] VARIANT SpellScript);
        [propget, helpcontext(0x00010268)]
        HRESULT _stdcall LockedText([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010268)]
        HRESULT _stdcall LockedText([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x0001008a)]
        HRESULT _stdcall Text([out, retval] BSTR* RHS);
        [propput, helpcontext(0x0001008a)]
        HRESULT _stdcall Text([in] BSTR RHS);
        [propget, helpcontext(0x0001034e)]
        HRESULT _stdcall Accelerator([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x0001034e)]
        HRESULT _stdcall Accelerator([in] VARIANT RHS);
        [restricted, hidden]
        void _stdcall _Dummy33();
        [propget, helpcontext(0x00010461)]
        HRESULT _stdcall PhoneticAccelerator([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010461)]
        HRESULT _stdcall PhoneticAccelerator([in] VARIANT RHS);
        [helpcontext(0x000100b5)]
        HRESULT _stdcall Add(
                        [in] double Left, 
                        [in] double Top, 
                        [in] double Width, 
                        [in] double Height, 
                        [out, retval] Label** RHS);
        [propget, helpcontext(0x00010076)]
        HRESULT _stdcall Count([out, retval] long* RHS);
        [helpcontext(0x0001002e)]
        HRESULT _stdcall Group([out, retval] GroupObject** RHS);
        [helpcontext(0x000100aa)]
        HRESULT _stdcall Item(
                        [in] VARIANT Index, 
                        [out, retval] IDispatch** RHS);
        [helpcontext(0x0000fffc)]
        HRESULT _stdcall _NewEnum([out, retval] IUnknown** RHS);
    };

    [
      odl,
      uuid(00020894-0001-0000-C000-000000000046),
      helpcontext(0x00020054),
      hidden
    ]
    interface IPanes : IDispatch {
        [propget, helpcontext(0x00010094)]
        HRESULT _stdcall Application([out, retval] Application** RHS);
        [propget, helpcontext(0x00010095)]
        HRESULT _stdcall Creator([out, retval] XlCreator* RHS);
        [propget, helpcontext(0x00010096)]
        HRESULT _stdcall Parent([out, retval] IDispatch** RHS);
        [propget, helpcontext(0x00010076)]
        HRESULT _stdcall Count([out, retval] long* RHS);
        [propget, helpcontext(0x000100aa)]
        HRESULT _stdcall Item(
                        [in] long Index, 
                        [out, retval] Pane** RHS);
        [propget, helpcontext(0x00010000)]
        HRESULT _stdcall _Default(
                        [in] long Index, 
                        [out, retval] Pane** RHS);
    };

    [
      odl,
      uuid(00020895-0001-0000-C000-000000000046),
      helpcontext(0x00020055),
      hidden
    ]
    interface IPane : IDispatch {
        [propget, helpcontext(0x00010094)]
        HRESULT _stdcall Application([out, retval] Application** RHS);
        [propget, helpcontext(0x00010095)]
        HRESULT _stdcall Creator([out, retval] XlCreator* RHS);
        [propget, helpcontext(0x00010096)]
        HRESULT _stdcall Parent([out, retval] IDispatch** RHS);
        [helpcontext(0x00010130)]
        HRESULT _stdcall Activate();
        [propget, helpcontext(0x000101e6)]
        HRESULT _stdcall Index([out, retval] long* RHS);
        [helpcontext(0x00010223)]
        HRESULT _stdcall LargeScroll(
                        [in, optional] VARIANT Down, 
                        [in, optional] VARIANT Up, 
                        [in, optional] VARIANT ToRight, 
                        [in, optional] VARIANT ToLeft);
        [propget, helpcontext(0x0001028e)]
        HRESULT _stdcall ScrollColumn([out, retval] long* RHS);
        [propput, helpcontext(0x0001028e)]
        HRESULT _stdcall ScrollColumn([in] long RHS);
        [propget, helpcontext(0x0001028f)]
        HRESULT _stdcall ScrollRow([out, retval] long* RHS);
        [propput, helpcontext(0x0001028f)]
        HRESULT _stdcall ScrollRow([in] long RHS);
        [helpcontext(0x00010224)]
        HRESULT _stdcall SmallScroll(
                        [in, optional] VARIANT Down, 
                        [in, optional] VARIANT Up, 
                        [in, optional] VARIANT ToRight, 
                        [in, optional] VARIANT ToLeft);
        [propget, helpcontext(0x0001045e)]
        HRESULT _stdcall VisibleRange([out, retval] Range** RHS);
    };

    [
      odl,
      uuid(00020896-0001-0000-C000-000000000046),
      helpcontext(0x00020056),
      hidden
    ]
    interface IScenarios : IDispatch {
        [propget, helpcontext(0x00010094)]
        HRESULT _stdcall Application([out, retval] Application** RHS);
        [propget, helpcontext(0x00010095)]
        HRESULT _stdcall Creator([out, retval] XlCreator* RHS);
        [propget, helpcontext(0x00010096)]
        HRESULT _stdcall Parent([out, retval] IDispatch** RHS);
        [helpcontext(0x000100b5)]
        HRESULT _stdcall Add(
                        [in] BSTR Name, 
                        [in] VARIANT ChangingCells, 
                        [in, optional] VARIANT Values, 
                        [in, optional] VARIANT Comment, 
                        [in, optional] VARIANT Locked, 
                        [in, optional] VARIANT Hidden, 
                        [out, retval] Scenario** RHS);
        [propget, helpcontext(0x00010076)]
        HRESULT _stdcall Count([out, retval] long* RHS);
        [helpcontext(0x00010391)]
        HRESULT _stdcall CreateSummary(
                        [in, optional, defaultvalue(1)] XlSummaryReportType ReportType, 
                        [in, optional] VARIANT ResultCells);
        [helpcontext(0x000100aa)]
        HRESULT _stdcall Item(
                        [in] VARIANT Index, 
                        [out, retval] Scenario** RHS);
        [helpcontext(0x00010234)]
        HRESULT _stdcall Merge([in] VARIANT Source);
        [helpcontext(0x0000fffc)]
        HRESULT _stdcall _NewEnum([out, retval] IUnknown** RHS);
    };

    [
      odl,
      uuid(00020897-0001-0000-C000-000000000046),
      helpcontext(0x00020057),
      hidden
    ]
    interface IScenario : IDispatch {
        [propget, helpcontext(0x00010094)]
        HRESULT _stdcall Application([out, retval] Application** RHS);
        [propget, helpcontext(0x00010095)]
        HRESULT _stdcall Creator([out, retval] XlCreator* RHS);
        [propget, helpcontext(0x00010096)]
        HRESULT _stdcall Parent([out, retval] IDispatch** RHS);
        [helpcontext(0x00010390)]
        HRESULT _stdcall ChangeScenario(
                        [in] VARIANT ChangingCells, 
                        [in, optional] VARIANT Values);
        [propget, helpcontext(0x0001038f)]
        HRESULT _stdcall ChangingCells([out, retval] Range** RHS);
        [propget, helpcontext(0x0001038e)]
        HRESULT _stdcall Comment([out, retval] BSTR* RHS);
        [propput, helpcontext(0x0001038e)]
        HRESULT _stdcall Comment([in] BSTR RHS);
        [helpcontext(0x00010075)]
        HRESULT _stdcall Delete();
        [propget, helpcontext(0x0001010c)]
        HRESULT _stdcall Hidden([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x0001010c)]
        HRESULT _stdcall Hidden([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x000101e6)]
        HRESULT _stdcall Index([out, retval] long* RHS);
        [propget, helpcontext(0x0001010d)]
        HRESULT _stdcall Locked([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x0001010d)]
        HRESULT _stdcall Locked([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x0001006e)]
        HRESULT _stdcall Name([out, retval] BSTR* RHS);
        [propput, helpcontext(0x0001006e)]
        HRESULT _stdcall Name([in] BSTR RHS);
        [helpcontext(0x000101f0)]
        HRESULT _stdcall Show();
        [propget, helpcontext(0x000100a4)]
        HRESULT _stdcall Values(
                        [in, optional] VARIANT Index, 
                        [out, retval] VARIANT* RHS);
    };

    [
      odl,
      uuid(00020898-0001-0000-C000-000000000046),
      helpcontext(0x00020058),
      hidden
    ]
    interface IGroupObject : IDispatch {
        [propget, helpcontext(0x00010094)]
        HRESULT _stdcall Application([out, retval] Application** RHS);
        [propget, helpcontext(0x00010095)]
        HRESULT _stdcall Creator([out, retval] XlCreator* RHS);
        [propget, helpcontext(0x00010096)]
        HRESULT _stdcall Parent([out, retval] IDispatch** RHS);
        [propget, helpcontext(0x00010267)]
        HRESULT _stdcall BottomRightCell([out, retval] Range** RHS);
        [helpcontext(0x0001025a)]
        HRESULT _stdcall BringToFront();
        [helpcontext(0x00010227)]
        HRESULT _stdcall Copy();
        [helpcontext(0x000100d5)]
        HRESULT _stdcall CopyPicture(
                        [in, optional, defaultvalue(2)] XlPictureAppearance Appearance, 
                        [in, optional, defaultvalue(-4147)] XlCopyPictureFormat Format);
        [helpcontext(0x00010235)]
        HRESULT _stdcall Cut();
        [helpcontext(0x00010075)]
        HRESULT _stdcall Delete();
        [helpcontext(0x0001040f)]
        HRESULT _stdcall Duplicate([out, retval] IDispatch** RHS);
        [propget, helpcontext(0x00010258)]
        HRESULT _stdcall Enabled([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010258)]
        HRESULT _stdcall Enabled([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x0001007b)]
        HRESULT _stdcall Height([out, retval] double* RHS);
        [propput, helpcontext(0x0001007b)]
        HRESULT _stdcall Height([in] double RHS);
        [propget, helpcontext(0x000101e6)]
        HRESULT _stdcall Index([out, retval] long* RHS);
        [propget, helpcontext(0x0001007f)]
        HRESULT _stdcall Left([out, retval] double* RHS);
        [propput, helpcontext(0x0001007f)]
        HRESULT _stdcall Left([in] double RHS);
        [propget, helpcontext(0x0001010d)]
        HRESULT _stdcall Locked([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x0001010d)]
        HRESULT _stdcall Locked([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x0001006e)]
        HRESULT _stdcall Name([out, retval] BSTR* RHS);
        [propput, helpcontext(0x0001006e)]
        HRESULT _stdcall Name([in] BSTR RHS);
        [propget, hidden, helpcontext(0x00010254)]
        HRESULT _stdcall OnAction([out, retval] BSTR* RHS);
        [propput, hidden, helpcontext(0x00010254)]
        HRESULT _stdcall OnAction([in] BSTR RHS);
        [propget, helpcontext(0x00010269)]
        HRESULT _stdcall Placement([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010269)]
        HRESULT _stdcall Placement([in] VARIANT RHS);
        [propget, helpcontext(0x0001026a)]
        HRESULT _stdcall PrintObject([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x0001026a)]
        HRESULT _stdcall PrintObject([in] VARIANT_BOOL RHS);
        [helpcontext(0x000100eb)]
        HRESULT _stdcall Select([in, optional] VARIANT Replace);
        [helpcontext(0x0001025d)]
        HRESULT _stdcall SendToBack();
        [propget, helpcontext(0x0001007e)]
        HRESULT _stdcall Top([out, retval] double* RHS);
        [propput, helpcontext(0x0001007e)]
        HRESULT _stdcall Top([in] double RHS);
        [propget, helpcontext(0x0001026c)]
        HRESULT _stdcall TopLeftCell([out, retval] Range** RHS);
        [propget, helpcontext(0x0001022e)]
        HRESULT _stdcall Visible([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x0001022e)]
        HRESULT _stdcall Visible([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x0001007a)]
        HRESULT _stdcall Width([out, retval] double* RHS);
        [propput, helpcontext(0x0001007a)]
        HRESULT _stdcall Width([in] double RHS);
        [propget, helpcontext(0x0001026e)]
        HRESULT _stdcall ZOrder([out, retval] long* RHS);
        [propget, helpcontext(0x000105f8)]
        HRESULT _stdcall ShapeRange([out, retval] ShapeRange** RHS);
        [restricted, hidden]
        void _stdcall _Dummy27();
        [restricted, hidden]
        void _stdcall _Dummy28();
        [propget, helpcontext(0x00010427)]
        HRESULT _stdcall AddIndent([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010427)]
        HRESULT _stdcall AddIndent([in] VARIANT_BOOL RHS);
        [restricted, hidden]
        void _stdcall _Dummy30();
        [propget, helpcontext(0x00010263)]
        HRESULT _stdcall ArrowHeadLength([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010263)]
        HRESULT _stdcall ArrowHeadLength([in] VARIANT RHS);
        [propget, helpcontext(0x00010264)]
        HRESULT _stdcall ArrowHeadStyle([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010264)]
        HRESULT _stdcall ArrowHeadStyle([in] VARIANT RHS);
        [propget, helpcontext(0x00010265)]
        HRESULT _stdcall ArrowHeadWidth([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010265)]
        HRESULT _stdcall ArrowHeadWidth([in] VARIANT RHS);
        [propget, helpcontext(0x00010266)]
        HRESULT _stdcall AutoSize([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010266)]
        HRESULT _stdcall AutoSize([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x00010080)]
        HRESULT _stdcall Border([out, retval] Border** RHS);
        [restricted, hidden]
        void _stdcall _Dummy36();
        [restricted, hidden]
        void _stdcall _Dummy37();
        [restricted, hidden]
        void _stdcall _Dummy38();
        [helpcontext(0x000101f9)]
        HRESULT _stdcall CheckSpelling(
                        [in, optional] VARIANT CustomDictionary, 
                        [in, optional] VARIANT IgnoreUppercase, 
                        [in, optional] VARIANT AlwaysSuggest, 
                        [in, optional] VARIANT IgnoreInitialAlefHamza, 
                        [in, optional] VARIANT IgnoreFinalYaa, 
                        [in, optional] VARIANT SpellScript);
        [propget, helpcontext(0x00010000)]
        HRESULT _stdcall _Default([out, retval] long* RHS);
        [propput, helpcontext(0x00010000)]
        HRESULT _stdcall _Default([in] long RHS);
        [restricted, hidden]
        void _stdcall _Dummy41();
        [restricted, hidden]
        void _stdcall _Dummy42();
        [restricted, hidden]
        void _stdcall _Dummy43();
        [restricted, hidden]
        void _stdcall _Dummy44();
        [restricted, hidden]
        void _stdcall _Dummy45();
        [propget, helpcontext(0x00010092)]
        HRESULT _stdcall Font([out, retval] Font** RHS);
        [restricted, hidden]
        void _stdcall _Dummy47();
        [restricted, hidden]
        void _stdcall _Dummy48();
        [propget, helpcontext(0x00010088)]
        HRESULT _stdcall HorizontalAlignment([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010088)]
        HRESULT _stdcall HorizontalAlignment([in] VARIANT RHS);
        [restricted, hidden]
        void _stdcall _Dummy50();
        [propget, helpcontext(0x00010081)]
        HRESULT _stdcall Interior([out, retval] Interior** RHS);
        [restricted, hidden]
        void _stdcall _Dummy52();
        [restricted, hidden]
        void _stdcall _Dummy53();
        [restricted, hidden]
        void _stdcall _Dummy54();
        [restricted, hidden]
        void _stdcall _Dummy55();
        [restricted, hidden]
        void _stdcall _Dummy56();
        [restricted, hidden]
        void _stdcall _Dummy57();
        [restricted, hidden]
        void _stdcall _Dummy58();
        [restricted, hidden]
        void _stdcall _Dummy59();
        [restricted, hidden]
        void _stdcall _Dummy60();
        [restricted, hidden]
        void _stdcall _Dummy61();
        [restricted, hidden]
        void _stdcall _Dummy62();
        [restricted, hidden]
        void _stdcall _Dummy63();
        [propget, helpcontext(0x00010086)]
        HRESULT _stdcall Orientation([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010086)]
        HRESULT _stdcall Orientation([in] VARIANT RHS);
        [restricted, hidden]
        void _stdcall _Dummy65();
        [restricted, hidden]
        void _stdcall _Dummy66();
        [restricted, hidden]
        void _stdcall _Dummy67();
        [restricted, hidden]
        void _stdcall _Dummy68();
        [propget, helpcontext(0x0001026b)]
        HRESULT _stdcall RoundedCorners([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x0001026b)]
        HRESULT _stdcall RoundedCorners([in] VARIANT_BOOL RHS);
        [restricted, hidden]
        void _stdcall _Dummy70();
        [propget, helpcontext(0x00010067)]
        HRESULT _stdcall Shadow([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010067)]
        HRESULT _stdcall Shadow([in] VARIANT_BOOL RHS);
        [restricted, hidden]
        void _stdcall _Dummy72();
        [restricted, hidden]
        void _stdcall _Dummy73();
        [helpcontext(0x000100f4)]
        HRESULT _stdcall Ungroup([out, retval] IDispatch** RHS);
        [restricted, hidden]
        void _stdcall _Dummy75();
        [propget, helpcontext(0x00010089)]
        HRESULT _stdcall VerticalAlignment([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010089)]
        HRESULT _stdcall VerticalAlignment([in] VARIANT RHS);
        [restricted, hidden]
        void _stdcall _Dummy77();
        [propget, helpcontext(0x000103cf)]
        HRESULT _stdcall ReadingOrder([out, retval] long* RHS);
        [propput, helpcontext(0x000103cf)]
        HRESULT _stdcall ReadingOrder([in] long RHS);
    };
