import "Excel26.Idl";

    [
      uuid(00020859-0000-0000-C000-000000000046),
      helpcontext(0x00020019)
    ]
    dispinterface ChartGroup {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x0000002f), propget, helpcontext(0x0001002f)]
            XlAxisGroup AxisGroup();
            [id(0x0000002f), propput, helpcontext(0x0001002f)]
            void AxisGroup([in] XlAxisGroup rhs);
            [id(0x00000466), propget, helpcontext(0x00010466)]
            long DoughnutHoleSize();
            [id(0x00000466), propput, helpcontext(0x00010466)]
            void DoughnutHoleSize([in] long rhs);
            [id(0x0000008d), propget, helpcontext(0x0001008d)]
            DownBars* DownBars();
            [id(0x0000008e), propget, helpcontext(0x0001008e)]
            DropLines* DropLines();
            [id(0x0000003f), propget, helpcontext(0x0001003f)]
            long FirstSliceAngle();
            [id(0x0000003f), propput, helpcontext(0x0001003f)]
            void FirstSliceAngle([in] long rhs);
            [id(0x00000033), propget, helpcontext(0x00010033)]
            long GapWidth();
            [id(0x00000033), propput, helpcontext(0x00010033)]
            void GapWidth([in] long rhs);
            [id(0x0000003d), propget, helpcontext(0x0001003d)]
            VARIANT_BOOL HasDropLines();
            [id(0x0000003d), propput, helpcontext(0x0001003d)]
            void HasDropLines([in] VARIANT_BOOL rhs);
            [id(0x0000003e), propget, helpcontext(0x0001003e)]
            VARIANT_BOOL HasHiLoLines();
            [id(0x0000003e), propput, helpcontext(0x0001003e)]
            void HasHiLoLines([in] VARIANT_BOOL rhs);
            [id(0x00000040), propget, helpcontext(0x00010040)]
            VARIANT_BOOL HasRadarAxisLabels();
            [id(0x00000040), propput, helpcontext(0x00010040)]
            void HasRadarAxisLabels([in] VARIANT_BOOL rhs);
            [id(0x00000041), propget, helpcontext(0x00010041)]
            VARIANT_BOOL HasSeriesLines();
            [id(0x00000041), propput, helpcontext(0x00010041)]
            void HasSeriesLines([in] VARIANT_BOOL rhs);
            [id(0x00000042), propget, helpcontext(0x00010042)]
            VARIANT_BOOL HasUpDownBars();
            [id(0x00000042), propput, helpcontext(0x00010042)]
            void HasUpDownBars([in] VARIANT_BOOL rhs);
            [id(0x0000008f), propget, helpcontext(0x0001008f)]
            HiLoLines* HiLoLines();
            [id(0x000001e6), propget, helpcontext(0x000101e6)]
            long Index();
            [id(0x00000038), propget, helpcontext(0x00010038)]
            long Overlap();
            [id(0x00000038), propput, helpcontext(0x00010038)]
            void Overlap([in] long rhs);
            [id(0x00000090), propget, helpcontext(0x00010090)]
            TickLabels* RadarAxisLabels();
            [id(0x00000044), helpcontext(0x00010044)]
            IDispatch* SeriesCollection([in, optional] VARIANT Index);
            [id(0x00000091), propget, helpcontext(0x00010091)]
            SeriesLines* SeriesLines();
            [id(0x0000006d), propget, hidden, helpcontext(0x0001006d)]
            long SubType();
            [id(0x0000006d), propput, hidden, helpcontext(0x0001006d)]
            void SubType([in] long rhs);
            [id(0x0000006c), propget, hidden, helpcontext(0x0001006c)]
            long Type();
            [id(0x0000006c), propput, hidden, helpcontext(0x0001006c)]
            void Type([in] long rhs);
            [id(0x0000008c), propget, helpcontext(0x0001008c)]
            UpBars* UpBars();
            [id(0x0000003c), propget, helpcontext(0x0001003c)]
            VARIANT_BOOL VaryByCategories();
            [id(0x0000003c), propput, helpcontext(0x0001003c)]
            void VaryByCategories([in] VARIANT_BOOL rhs);
            [id(0x00000674), propget, helpcontext(0x00010674)]
            XlSizeRepresents SizeRepresents();
            [id(0x00000674), propput, helpcontext(0x00010674)]
            void SizeRepresents([in] XlSizeRepresents rhs);
            [id(0x00000675), propget, helpcontext(0x00010675)]
            long BubbleScale();
            [id(0x00000675), propput, helpcontext(0x00010675)]
            void BubbleScale([in] long rhs);
            [id(0x00000676), propget, helpcontext(0x00010676)]
            VARIANT_BOOL ShowNegativeBubbles();
            [id(0x00000676), propput, helpcontext(0x00010676)]
            void ShowNegativeBubbles([in] VARIANT_BOOL rhs);
            [id(0x00000677), propget, helpcontext(0x00010677)]
            XlChartSplitType SplitType();
            [id(0x00000677), propput, helpcontext(0x00010677)]
            void SplitType([in] XlChartSplitType rhs);
            [id(0x00000678), propget, helpcontext(0x00010678)]
            VARIANT SplitValue();
            [id(0x00000678), propput, helpcontext(0x00010678)]
            void SplitValue([in] VARIANT rhs);
            [id(0x00000679), propget, helpcontext(0x00010679)]
            long SecondPlotSize();
            [id(0x00000679), propput, helpcontext(0x00010679)]
            void SecondPlotSize([in] long rhs);
            [id(0x0000067a), propget, helpcontext(0x0001067a)]
            VARIANT_BOOL Has3DShading();
            [id(0x0000067a), propput, helpcontext(0x0001067a)]
            void Has3DShading([in] VARIANT_BOOL rhs);
    };

    [
      uuid(0002085A-0000-0000-C000-000000000046),
      helpcontext(0x0002001a)
    ]
    dispinterface ChartGroups {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x00000076), propget, helpcontext(0x00010076)]
            long Count();
            [id(0x000000aa), helpcontext(0x000100aa)]
            ChartGroup* Item([in] VARIANT Index);
            [id(0xfffffffc), helpcontext(0x0000fffc)]
            IUnknown* _NewEnum();
    };

    [
      uuid(0002085B-0000-0000-C000-000000000046),
      helpcontext(0x0002001b)
    ]
    dispinterface Axes {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x00000076), propget, helpcontext(0x00010076)]
            long Count();
            [id(0x000000aa), helpcontext(0x000100aa)]
            Axis* Item(
                            [in] XlAxisType Type, 
                            [in, optional, defaultvalue(1)] XlAxisGroup AxisGroup);
            [id(0xfffffffc), helpcontext(0x0000fffc)]
            IUnknown* _NewEnum();
    };

    [
      uuid(00020869-0000-0000-C000-000000000046),
      helpcontext(0x00020029)
    ]
    dispinterface Points {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x00000076), propget, helpcontext(0x00010076)]
            long Count();
            [id(0x000000aa), helpcontext(0x000100aa)]
            Point* Item([in] long Index);
            [id(0xfffffffc), helpcontext(0x0000fffc)]
            IUnknown* _NewEnum();
    };

    [
      uuid(0002086A-0000-0000-C000-000000000046),
      helpcontext(0x0002002a)
    ]
    dispinterface Point {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x00000097), helpcontext(0x00010097)]
            void ApplyDataLabels(
                            [in, optional, defaultvalue(2)] XlDataLabelsType Type, 
                            [in, optional] VARIANT LegendKey, 
                            [in, optional] VARIANT AutoText);
            [id(0x00000080), propget, helpcontext(0x00010080)]
            Border* Border();
            [id(0x00000070), helpcontext(0x00010070)]
            void ClearFormats();
            [id(0x00000227), helpcontext(0x00010227)]
            void Copy();
            [id(0x0000009e), propget, helpcontext(0x0001009e)]
            DataLabel* DataLabel();
            [id(0x00000075), helpcontext(0x00010075)]
            void Delete();
            [id(0x000000b6), propget, helpcontext(0x000100b6)]
            long Explosion();
            [id(0x000000b6), propput, helpcontext(0x000100b6)]
            void Explosion([in] long rhs);
            [id(0x0000004d), propget, helpcontext(0x0001004d)]
            VARIANT_BOOL HasDataLabel();
            [id(0x0000004d), propput, helpcontext(0x0001004d)]
            void HasDataLabel([in] VARIANT_BOOL rhs);
            [id(0x00000081), propget, helpcontext(0x00010081)]
            Interior* Interior();
            [id(0x00000084), propget, helpcontext(0x00010084)]
            VARIANT_BOOL InvertIfNegative();
            [id(0x00000084), propput, helpcontext(0x00010084)]
            void InvertIfNegative([in] VARIANT_BOOL rhs);
            [id(0x00000049), propget, helpcontext(0x00010049)]
            long MarkerBackgroundColor();
            [id(0x00000049), propput, helpcontext(0x00010049)]
            void MarkerBackgroundColor([in] long rhs);
            [id(0x0000004a), propget, helpcontext(0x0001004a)]
            XlColorIndex MarkerBackgroundColorIndex();
            [id(0x0000004a), propput, helpcontext(0x0001004a)]
            void MarkerBackgroundColorIndex([in] XlColorIndex rhs);
            [id(0x0000004b), propget, helpcontext(0x0001004b)]
            long MarkerForegroundColor();
            [id(0x0000004b), propput, helpcontext(0x0001004b)]
            void MarkerForegroundColor([in] long rhs);
            [id(0x0000004c), propget, helpcontext(0x0001004c)]
            XlColorIndex MarkerForegroundColorIndex();
            [id(0x0000004c), propput, helpcontext(0x0001004c)]
            void MarkerForegroundColorIndex([in] XlColorIndex rhs);
            [id(0x000000e7), propget, helpcontext(0x000100e7)]
            long MarkerSize();
            [id(0x000000e7), propput, helpcontext(0x000100e7)]
            void MarkerSize([in] long rhs);
            [id(0x00000048), propget, helpcontext(0x00010048)]
            XlMarkerStyle MarkerStyle();
            [id(0x00000048), propput, helpcontext(0x00010048)]
            void MarkerStyle([in] XlMarkerStyle rhs);
            [id(0x000000d3), helpcontext(0x000100d3)]
            void Paste();
            [id(0x000000a1), propget, helpcontext(0x000100a1)]
            XlChartPictureType PictureType();
            [id(0x000000a1), propput, helpcontext(0x000100a1)]
            void PictureType([in] XlChartPictureType rhs);
            [id(0x000000a2), propget, helpcontext(0x000100a2)]
            long PictureUnit();
            [id(0x000000a2), propput, helpcontext(0x000100a2)]
            void PictureUnit([in] long rhs);
            [id(0x000000eb), helpcontext(0x000100eb)]
            void Select();
            [id(0x0000067b), propget, helpcontext(0x0001067b)]
            VARIANT_BOOL ApplyPictToSides();
            [id(0x0000067b), propput, helpcontext(0x0001067b)]
            void ApplyPictToSides([in] VARIANT_BOOL rhs);
            [id(0x0000067c), propget, helpcontext(0x0001067c)]
            VARIANT_BOOL ApplyPictToFront();
            [id(0x0000067c), propput, helpcontext(0x0001067c)]
            void ApplyPictToFront([in] VARIANT_BOOL rhs);
            [id(0x0000067d), propget, helpcontext(0x0001067d)]
            VARIANT_BOOL ApplyPictToEnd();
            [id(0x0000067d), propput, helpcontext(0x0001067d)]
            void ApplyPictToEnd([in] VARIANT_BOOL rhs);
            [id(0x00000067), propget, helpcontext(0x00010067)]
            VARIANT_BOOL Shadow();
            [id(0x00000067), propput, helpcontext(0x00010067)]
            void Shadow([in] VARIANT_BOOL rhs);
            [id(0x0000067e), propget, helpcontext(0x0001067e)]
            VARIANT_BOOL SecondaryPlot();
            [id(0x0000067e), propput, helpcontext(0x0001067e)]
            void SecondaryPlot([in] VARIANT_BOOL rhs);
            [id(0x0000067f), propget, helpcontext(0x0001067f)]
            ChartFillFormat* Fill();
    };

    [
      uuid(0002086B-0000-0000-C000-000000000046),
      helpcontext(0x0002002b)
    ]
    dispinterface Series {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x00000097), helpcontext(0x00010097)]
            void ApplyDataLabels(
                            [in, optional, defaultvalue(2)] XlDataLabelsType Type, 
                            [in, optional] VARIANT LegendKey, 
                            [in, optional] VARIANT AutoText, 
                            [in, optional] VARIANT HasLeaderLines);
            [id(0x0000002f), propget, helpcontext(0x0001002f)]
            XlAxisGroup AxisGroup();
            [id(0x0000002f), propput, helpcontext(0x0001002f)]
            void AxisGroup([in] XlAxisGroup rhs);
            [id(0x00000080), propget, helpcontext(0x00010080)]
            Border* Border();
            [id(0x00000070), helpcontext(0x00010070)]
            void ClearFormats();
            [id(0x00000227), helpcontext(0x00010227)]
            void Copy();
            [id(0x0000009d), helpcontext(0x0001009d)]
            IDispatch* DataLabels([in, optional] VARIANT Index);
            [id(0x00000075), helpcontext(0x00010075)]
            void Delete();
            [id(0x00000098), helpcontext(0x00010098)]
            void ErrorBar(
                            [in] XlErrorBarDirection Direction, 
                            [in] XlErrorBarInclude Include, 
                            [in] XlErrorBarType Type, 
                            [in, optional] VARIANT Amount, 
                            [in, optional] VARIANT MinusValues);
            [id(0x0000009f), propget, helpcontext(0x0001009f)]
            ErrorBars* ErrorBars();
            [id(0x000000b6), propget, helpcontext(0x000100b6)]
            long Explosion();
            [id(0x000000b6), propput, helpcontext(0x000100b6)]
            void Explosion([in] long rhs);
            [id(0x00000105), propget, helpcontext(0x00010105)]
            BSTR Formula();
            [id(0x00000105), propput, helpcontext(0x00010105)]
            void Formula([in] BSTR rhs);
            [id(0x00000107), propget, helpcontext(0x00010107)]
            BSTR FormulaLocal();
            [id(0x00000107), propput, helpcontext(0x00010107)]
            void FormulaLocal([in] BSTR rhs);
            [id(0x00000108), propget, helpcontext(0x00010108)]
            BSTR FormulaR1C1();
            [id(0x00000108), propput, helpcontext(0x00010108)]
            void FormulaR1C1([in] BSTR rhs);
            [id(0x00000109), propget, helpcontext(0x00010109)]
            BSTR FormulaR1C1Local();
            [id(0x00000109), propput, helpcontext(0x00010109)]
            void FormulaR1C1Local([in] BSTR rhs);
            [id(0x0000004e), propget, helpcontext(0x0001004e)]
            VARIANT_BOOL HasDataLabels();
            [id(0x0000004e), propput, helpcontext(0x0001004e)]
            void HasDataLabels([in] VARIANT_BOOL rhs);
            [id(0x000000a0), propget, helpcontext(0x000100a0)]
            VARIANT_BOOL HasErrorBars();
            [id(0x000000a0), propput, helpcontext(0x000100a0)]
            void HasErrorBars([in] VARIANT_BOOL rhs);
            [id(0x00000081), propget, helpcontext(0x00010081)]
            Interior* Interior();
            [id(0x0000067f), propget, helpcontext(0x0001067f)]
            ChartFillFormat* Fill();
            [id(0x00000084), propget, helpcontext(0x00010084)]
            VARIANT_BOOL InvertIfNegative();
            [id(0x00000084), propput, helpcontext(0x00010084)]
            void InvertIfNegative([in] VARIANT_BOOL rhs);
            [id(0x00000049), propget, helpcontext(0x00010049)]
            long MarkerBackgroundColor();
            [id(0x00000049), propput, helpcontext(0x00010049)]
            void MarkerBackgroundColor([in] long rhs);
            [id(0x0000004a), propget, helpcontext(0x0001004a)]
            XlColorIndex MarkerBackgroundColorIndex();
            [id(0x0000004a), propput, helpcontext(0x0001004a)]
            void MarkerBackgroundColorIndex([in] XlColorIndex rhs);
            [id(0x0000004b), propget, helpcontext(0x0001004b)]
            long MarkerForegroundColor();
            [id(0x0000004b), propput, helpcontext(0x0001004b)]
            void MarkerForegroundColor([in] long rhs);
            [id(0x0000004c), propget, helpcontext(0x0001004c)]
            XlColorIndex MarkerForegroundColorIndex();
            [id(0x0000004c), propput, helpcontext(0x0001004c)]
            void MarkerForegroundColorIndex([in] XlColorIndex rhs);
            [id(0x000000e7), propget, helpcontext(0x000100e7)]
            long MarkerSize();
            [id(0x000000e7), propput, helpcontext(0x000100e7)]
            void MarkerSize([in] long rhs);
            [id(0x00000048), propget, helpcontext(0x00010048)]
            XlMarkerStyle MarkerStyle();
            [id(0x00000048), propput, helpcontext(0x00010048)]
            void MarkerStyle([in] XlMarkerStyle rhs);
            [id(0x0000006e), propget, helpcontext(0x0001006e)]
            BSTR Name();
            [id(0x0000006e), propput, helpcontext(0x0001006e)]
            void Name([in] BSTR rhs);
            [id(0x000000d3), helpcontext(0x000100d3)]
            void Paste();
            [id(0x000000a1), propget, helpcontext(0x000100a1)]
            XlChartPictureType PictureType();
            [id(0x000000a1), propput, helpcontext(0x000100a1)]
            void PictureType([in] XlChartPictureType rhs);
            [id(0x000000a2), propget, helpcontext(0x000100a2)]
            long PictureUnit();
            [id(0x000000a2), propput, helpcontext(0x000100a2)]
            void PictureUnit([in] long rhs);
            [id(0x000000e4), propget, helpcontext(0x000100e4)]
            long PlotOrder();
            [id(0x000000e4), propput, helpcontext(0x000100e4)]
            void PlotOrder([in] long rhs);
            [id(0x00000046), helpcontext(0x00010046)]
            IDispatch* Points([in, optional] VARIANT Index);
            [id(0x000000eb), helpcontext(0x000100eb)]
            void Select();
            [id(0x000000a3), propget, helpcontext(0x000100a3)]
            VARIANT_BOOL Smooth();
            [id(0x000000a3), propput, helpcontext(0x000100a3)]
            void Smooth([in] VARIANT_BOOL rhs);
            [id(0x0000009a), helpcontext(0x0001009a)]
            IDispatch* Trendlines([in, optional] VARIANT Index);
            [id(0x0000006c), propget, helpcontext(0x0001006c)]
            long Type();
            [id(0x0000006c), propput, helpcontext(0x0001006c)]
            void Type([in] long rhs);
            [id(0x00000578), propget, helpcontext(0x00010578)]
            XlChartType ChartType();
            [id(0x00000578), propput, helpcontext(0x00010578)]
            void ChartType([in] XlChartType rhs);
            [id(0x00000579), helpcontext(0x00010579)]
            void ApplyCustomType([in] XlChartType ChartType);
            [id(0x000000a4), propget, helpcontext(0x000100a4)]
            VARIANT Values();
            [id(0x000000a4), propput, helpcontext(0x000100a4)]
            void Values([in] VARIANT rhs);
            [id(0x00000457), propget, helpcontext(0x00010457)]
            VARIANT XValues();
            [id(0x00000457), propput, helpcontext(0x00010457)]
            void XValues([in] VARIANT rhs);
            [id(0x00000680), propget, helpcontext(0x00010680)]
            VARIANT BubbleSizes();
            [id(0x00000680), propput, helpcontext(0x00010680)]
            void BubbleSizes([in] VARIANT rhs);
            [id(0x0000057b), propget, helpcontext(0x0001057b)]
            XlBarShape BarShape();
            [id(0x0000057b), propput, helpcontext(0x0001057b)]
            void BarShape([in] XlBarShape rhs);
            [id(0x0000067b), propget, helpcontext(0x0001067b)]
            VARIANT_BOOL ApplyPictToSides();
            [id(0x0000067b), propput, helpcontext(0x0001067b)]
            void ApplyPictToSides([in] VARIANT_BOOL rhs);
            [id(0x0000067c), propget, helpcontext(0x0001067c)]
            VARIANT_BOOL ApplyPictToFront();
            [id(0x0000067c), propput, helpcontext(0x0001067c)]
            void ApplyPictToFront([in] VARIANT_BOOL rhs);
            [id(0x0000067d), propget, helpcontext(0x0001067d)]
            VARIANT_BOOL ApplyPictToEnd();
            [id(0x0000067d), propput, helpcontext(0x0001067d)]
            void ApplyPictToEnd([in] VARIANT_BOOL rhs);
            [id(0x00000681), propget, helpcontext(0x00010681)]
            VARIANT_BOOL Has3DEffect();
            [id(0x00000681), propput, helpcontext(0x00010681)]
            void Has3DEffect([in] VARIANT_BOOL rhs);
            [id(0x00000067), propget, helpcontext(0x00010067)]
            VARIANT_BOOL Shadow();
            [id(0x00000067), propput, helpcontext(0x00010067)]
            void Shadow([in] VARIANT_BOOL rhs);
            [id(0x00000572), propget, helpcontext(0x00010572)]
            VARIANT_BOOL HasLeaderLines();
            [id(0x00000572), propput, helpcontext(0x00010572)]
            void HasLeaderLines([in] VARIANT_BOOL rhs);
            [id(0x00000682), propget, helpcontext(0x00010682)]
            LeaderLines* LeaderLines();
    };

    [
      uuid(0002086C-0000-0000-C000-000000000046),
      helpcontext(0x0002002c)
    ]
    dispinterface SeriesCollection {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x000000b5), helpcontext(0x000100b5)]
            Series* Add(
                            [in] VARIANT Source, 
                            [in, optional, defaultvalue(2)] XlRowCol Rowcol, 
                            [in, optional] VARIANT SeriesLabels, 
                            [in, optional] VARIANT CategoryLabels, 
                            [in, optional] VARIANT Replace);
            [id(0x00000076), propget, helpcontext(0x00010076)]
            long Count();
            [id(0x000000e3), helpcontext(0x000100e3)]
            void Extend(
                            [in] VARIANT Source, 
                            [in, optional] VARIANT Rowcol, 
                            [in, optional] VARIANT CategoryLabels);
            [id(0x000000aa), helpcontext(0x000100aa)]
            Series* Item([in] VARIANT Index);
            [id(0xfffffffc), helpcontext(0x0000fffc)]
            IUnknown* _NewEnum();
            [id(0x000000d3), helpcontext(0x000100d3)]
            void Paste(
                            [in, optional, defaultvalue(2)] XlRowCol Rowcol, 
                            [in, optional] VARIANT SeriesLabels, 
                            [in, optional] VARIANT CategoryLabels, 
                            [in, optional] VARIANT Replace, 
                            [in, optional] VARIANT NewSeries);
            [id(0x0000045d), helpcontext(0x0001045d)]
            Series* NewSeries();
    };

    [
      uuid(000208B2-0000-0000-C000-000000000046),
      helpcontext(0x00020072)
    ]
    dispinterface DataLabel {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x0000006e), propget, helpcontext(0x0001006e)]
            BSTR Name();
            [id(0x000000eb), helpcontext(0x000100eb)]
            void Select();
            [id(0x00000080), propget, helpcontext(0x00010080)]
            Border* Border();
            [id(0x00000075), helpcontext(0x00010075)]
            void Delete();
            [id(0x00000081), propget, helpcontext(0x00010081)]
            Interior* Interior();
            [id(0x0000067f), propget, helpcontext(0x0001067f)]
            ChartFillFormat* Fill();
            [id(0x0000008b), propget, helpcontext(0x0001008b)]
            BSTR Caption();
            [id(0x0000008b), propput, helpcontext(0x0001008b)]
            void Caption([in] BSTR rhs);
            [id(0x0000025b), propget, helpcontext(0x0001025b)]
            Characters* Characters(
                            [in, optional] VARIANT Start, 
                            [in, optional] VARIANT Length);
            [id(0x00000092), propget, helpcontext(0x00010092)]
            Font* Font();
            [id(0x00000088), propget, helpcontext(0x00010088)]
            VARIANT HorizontalAlignment();
            [id(0x00000088), propput, helpcontext(0x00010088)]
            void HorizontalAlignment([in] VARIANT rhs);
            [id(0x0000007f), propget, helpcontext(0x0001007f)]
            double Left();
            [id(0x0000007f), propput, helpcontext(0x0001007f)]
            void Left([in] double rhs);
            [id(0x00000086), propget, helpcontext(0x00010086)]
            VARIANT Orientation();
            [id(0x00000086), propput, helpcontext(0x00010086)]
            void Orientation([in] VARIANT rhs);
            [id(0x00000067), propget, helpcontext(0x00010067)]
            VARIANT_BOOL Shadow();
            [id(0x00000067), propput, helpcontext(0x00010067)]
            void Shadow([in] VARIANT_BOOL rhs);
            [id(0x0000008a), propget, helpcontext(0x0001008a)]
            BSTR Text();
            [id(0x0000008a), propput, helpcontext(0x0001008a)]
            void Text([in] BSTR rhs);
            [id(0x0000007e), propget, helpcontext(0x0001007e)]
            double Top();
            [id(0x0000007e), propput, helpcontext(0x0001007e)]
            void Top([in] double rhs);
            [id(0x00000089), propget, helpcontext(0x00010089)]
            VARIANT VerticalAlignment();
            [id(0x00000089), propput, helpcontext(0x00010089)]
            void VerticalAlignment([in] VARIANT rhs);
            [id(0x000003cf), propget, helpcontext(0x000103cf)]
            long ReadingOrder();
            [id(0x000003cf), propput, helpcontext(0x000103cf)]
            void ReadingOrder([in] long rhs);
            [id(0x000005f5), propget, helpcontext(0x000105f5)]
            VARIANT AutoScaleFont();
            [id(0x000005f5), propput, helpcontext(0x000105f5)]
            void AutoScaleFont([in] VARIANT rhs);
            [id(0x00000087), propget, helpcontext(0x00010087)]
            VARIANT_BOOL AutoText();
            [id(0x00000087), propput, helpcontext(0x00010087)]
            void AutoText([in] VARIANT_BOOL rhs);
            [id(0x000000c1), propget, helpcontext(0x000100c1)]
            BSTR NumberFormat();
            [id(0x000000c1), propput, helpcontext(0x000100c1)]
            void NumberFormat([in] BSTR rhs);
            [id(0x000000c2), propget, helpcontext(0x000100c2)]
            VARIANT_BOOL NumberFormatLinked();
            [id(0x000000c2), propput, helpcontext(0x000100c2)]
            void NumberFormatLinked([in] VARIANT_BOOL rhs);
            [id(0x000000ab), propget, helpcontext(0x000100ab)]
            VARIANT_BOOL ShowLegendKey();
            [id(0x000000ab), propput, helpcontext(0x000100ab)]
            void ShowLegendKey([in] VARIANT_BOOL rhs);
            [id(0x0000006c), propget, helpcontext(0x0001006c)]
            VARIANT Type();
            [id(0x0000006c), propput, helpcontext(0x0001006c)]
            void Type([in] VARIANT rhs);
            [id(0x00000085), propget, helpcontext(0x00010085)]
            XlDataLabelPosition Position();
            [id(0x00000085), propput, helpcontext(0x00010085)]
            void Position([in] XlDataLabelPosition rhs);
    };

    [
      uuid(000208B3-0000-0000-C000-000000000046),
      helpcontext(0x00020073)
    ]
    dispinterface DataLabels {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x0000006e), propget, helpcontext(0x0001006e)]
            BSTR Name();
            [id(0x000000eb), helpcontext(0x000100eb)]
            void Select();
            [id(0x00000080), propget, helpcontext(0x00010080)]
            Border* Border();
            [id(0x00000075), helpcontext(0x00010075)]
            void Delete();
            [id(0x00000081), propget, helpcontext(0x00010081)]
            Interior* Interior();
            [id(0x0000067f), propget, helpcontext(0x0001067f)]
            ChartFillFormat* Fill();
            [id(0x00010009), restricted, hidden]
            void _Dummy9();
            [id(0x0001000a), restricted, hidden]
            void _Dummy10();
            [id(0x00000092), propget, helpcontext(0x00010092)]
            Font* Font();
            [id(0x00000088), propget, helpcontext(0x00010088)]
            VARIANT HorizontalAlignment();
            [id(0x00000088), propput, helpcontext(0x00010088)]
            void HorizontalAlignment([in] VARIANT rhs);
            [id(0x0001000d), restricted, hidden]
            void _Dummy13();
            [id(0x00000086), propget, helpcontext(0x00010086)]
            VARIANT Orientation();
            [id(0x00000086), propput, helpcontext(0x00010086)]
            void Orientation([in] VARIANT rhs);
            [id(0x00000067), propget, helpcontext(0x00010067)]
            VARIANT_BOOL Shadow();
            [id(0x00000067), propput, helpcontext(0x00010067)]
            void Shadow([in] VARIANT_BOOL rhs);
            [id(0x00010010), restricted, hidden]
            void _Dummy16();
            [id(0x00010011), restricted, hidden]
            void _Dummy17();
            [id(0x00000089), propget, helpcontext(0x00010089)]
            VARIANT VerticalAlignment();
            [id(0x00000089), propput, helpcontext(0x00010089)]
            void VerticalAlignment([in] VARIANT rhs);
            [id(0x000003cf), propget, helpcontext(0x000103cf)]
            long ReadingOrder();
            [id(0x000003cf), propput, helpcontext(0x000103cf)]
            void ReadingOrder([in] long rhs);
            [id(0x000005f5), propget, helpcontext(0x000105f5)]
            VARIANT AutoScaleFont();
            [id(0x000005f5), propput, helpcontext(0x000105f5)]
            void AutoScaleFont([in] VARIANT rhs);
            [id(0x00000087), propget, helpcontext(0x00010087)]
            VARIANT_BOOL AutoText();
            [id(0x00000087), propput, helpcontext(0x00010087)]
            void AutoText([in] VARIANT_BOOL rhs);
            [id(0x000000c1), propget, helpcontext(0x000100c1)]
            BSTR NumberFormat();
            [id(0x000000c1), propput, helpcontext(0x000100c1)]
            void NumberFormat([in] BSTR rhs);
            [id(0x000000c2), propget, helpcontext(0x000100c2)]
            VARIANT_BOOL NumberFormatLinked();
            [id(0x000000c2), propput, helpcontext(0x000100c2)]
            void NumberFormatLinked([in] VARIANT_BOOL rhs);
            [id(0x000000ab), propget, helpcontext(0x000100ab)]
            VARIANT_BOOL ShowLegendKey();
            [id(0x000000ab), propput, helpcontext(0x000100ab)]
            void ShowLegendKey([in] VARIANT_BOOL rhs);
            [id(0x0000006c), propget, helpcontext(0x0001006c)]
            VARIANT Type();
            [id(0x0000006c), propput, helpcontext(0x0001006c)]
            void Type([in] VARIANT rhs);
            [id(0x00000085), propget, helpcontext(0x00010085)]
            XlDataLabelPosition Position();
            [id(0x00000085), propput, helpcontext(0x00010085)]
            void Position([in] XlDataLabelPosition rhs);
            [id(0x00000076), propget, helpcontext(0x00010076)]
            long Count();
            [id(0x000000aa), helpcontext(0x000100aa)]
            DataLabel* Item([in] VARIANT Index);
            [id(0xfffffffc), helpcontext(0x0000fffc)]
            IUnknown* _NewEnum();
    };

    [
      uuid(000208BA-0000-0000-C000-000000000046),
      helpcontext(0x0002007a)
    ]
    dispinterface LegendEntry {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x00000075), helpcontext(0x00010075)]
            void Delete();
            [id(0x00000092), propget, helpcontext(0x00010092)]
            Font* Font();
            [id(0x000001e6), propget, helpcontext(0x000101e6)]
            long Index();
            [id(0x000000ae), propget, helpcontext(0x000100ae)]
            LegendKey* LegendKey();
            [id(0x000000eb), helpcontext(0x000100eb)]
            void Select();
            [id(0x000005f5), propget, helpcontext(0x000105f5)]
            VARIANT AutoScaleFont();
            [id(0x000005f5), propput, helpcontext(0x000105f5)]
            void AutoScaleFont([in] VARIANT rhs);
            [id(0x0000007f), propget, helpcontext(0x0001007f)]
            double Left();
            [id(0x0000007e), propget, helpcontext(0x0001007e)]
            double Top();
            [id(0x0000007a), propget, helpcontext(0x0001007a)]
            double Width();
            [id(0x0000007b), propget, helpcontext(0x0001007b)]
            double Height();
    };

    [
      uuid(000208BB-0000-0000-C000-000000000046),
      helpcontext(0x0002007b)
    ]
    dispinterface LegendEntries {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x00000076), propget, helpcontext(0x00010076)]
            long Count();
            [id(0x000000aa), helpcontext(0x000100aa)]
            LegendEntry* Item([in] VARIANT Index);
            [id(0xfffffffc), helpcontext(0x0000fffc)]
            IUnknown* _NewEnum();
    };

    [
      uuid(000208BC-0000-0000-C000-000000000046),
      helpcontext(0x0002007c)
    ]
    dispinterface LegendKey {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x00000080), propget, helpcontext(0x00010080)]
            Border* Border();
            [id(0x00000070), helpcontext(0x00010070)]
            void ClearFormats();
            [id(0x00000075), helpcontext(0x00010075)]
            void Delete();
            [id(0x00000081), propget, helpcontext(0x00010081)]
            Interior* Interior();
            [id(0x0000067f), propget, helpcontext(0x0001067f)]
            ChartFillFormat* Fill();
            [id(0x00000084), propget, helpcontext(0x00010084)]
            VARIANT_BOOL InvertIfNegative();
            [id(0x00000084), propput, helpcontext(0x00010084)]
            void InvertIfNegative([in] VARIANT_BOOL rhs);
            [id(0x00000049), propget, helpcontext(0x00010049)]
            long MarkerBackgroundColor();
            [id(0x00000049), propput, helpcontext(0x00010049)]
            void MarkerBackgroundColor([in] long rhs);
            [id(0x0000004a), propget, helpcontext(0x0001004a)]
            XlColorIndex MarkerBackgroundColorIndex();
            [id(0x0000004a), propput, helpcontext(0x0001004a)]
            void MarkerBackgroundColorIndex([in] XlColorIndex rhs);
            [id(0x0000004b), propget, helpcontext(0x0001004b)]
            long MarkerForegroundColor();
            [id(0x0000004b), propput, helpcontext(0x0001004b)]
            void MarkerForegroundColor([in] long rhs);
            [id(0x0000004c), propget, helpcontext(0x0001004c)]
            XlColorIndex MarkerForegroundColorIndex();
            [id(0x0000004c), propput, helpcontext(0x0001004c)]
            void MarkerForegroundColorIndex([in] XlColorIndex rhs);
            [id(0x000000e7), propget, helpcontext(0x000100e7)]
            long MarkerSize();
            [id(0x000000e7), propput, helpcontext(0x000100e7)]
            void MarkerSize([in] long rhs);
            [id(0x00000048), propget, helpcontext(0x00010048)]
            XlMarkerStyle MarkerStyle();
            [id(0x00000048), propput, helpcontext(0x00010048)]
            void MarkerStyle([in] XlMarkerStyle rhs);
            [id(0x000000a1), propget, helpcontext(0x000100a1)]
            long PictureType();
            [id(0x000000a1), propput, helpcontext(0x000100a1)]
            void PictureType([in] long rhs);
            [id(0x000000a2), propget, helpcontext(0x000100a2)]
            long PictureUnit();
            [id(0x000000a2), propput, helpcontext(0x000100a2)]
            void PictureUnit([in] long rhs);
            [id(0x000000eb), helpcontext(0x000100eb)]
            void Select();
            [id(0x000000a3), propget, helpcontext(0x000100a3)]
            VARIANT_BOOL Smooth();
            [id(0x000000a3), propput, helpcontext(0x000100a3)]
            void Smooth([in] VARIANT_BOOL rhs);
            [id(0x0000007f), propget, helpcontext(0x0001007f)]
            double Left();
            [id(0x0000007e), propget, helpcontext(0x0001007e)]
            double Top();
            [id(0x0000007a), propget, helpcontext(0x0001007a)]
            double Width();
            [id(0x0000007b), propget, helpcontext(0x0001007b)]
            double Height();
            [id(0x00000067), propget, helpcontext(0x00010067)]
            VARIANT_BOOL Shadow();
            [id(0x00000067), propput, helpcontext(0x00010067)]
            void Shadow([in] VARIANT_BOOL rhs);
    };

    [
      uuid(000208BD-0000-0000-C000-000000000046),
      helpcontext(0x0002007d)
    ]
    dispinterface Trendlines {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x000000b5), helpcontext(0x000100b5)]
            Trendline* Add(
                            [in, optional, defaultvalue(-4132)] XlTrendlineType Type, 
                            [in, optional] VARIANT Order, 
                            [in, optional] VARIANT Period, 
                            [in, optional] VARIANT Forward, 
                            [in, optional] VARIANT Backward, 
                            [in, optional] VARIANT Intercept, 
                            [in, optional] VARIANT DisplayEquation, 
                            [in, optional] VARIANT DisplayRSquared, 
                            [in, optional] VARIANT Name);
            [id(0x00000076), propget, helpcontext(0x00010076)]
            long Count();
            [id(0x000000aa), helpcontext(0x000100aa)]
            Trendline* Item([in, optional] VARIANT Index);
            [id(0xfffffffc), helpcontext(0x0000fffc)]
            IUnknown* _NewEnum();
    };

    [
      uuid(000208BE-0000-0000-C000-000000000046),
      helpcontext(0x0002007e)
    ]
    dispinterface Trendline {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x000000b9), propget, helpcontext(0x000100b9)]
            long Backward();
            [id(0x000000b9), propput, helpcontext(0x000100b9)]
            void Backward([in] long rhs);
            [id(0x00000080), propget, helpcontext(0x00010080)]
            Border* Border();
            [id(0x00000070), helpcontext(0x00010070)]
            void ClearFormats();
            [id(0x0000009e), propget, helpcontext(0x0001009e)]
            DataLabel* DataLabel();
            [id(0x00000075), helpcontext(0x00010075)]
            void Delete();
            [id(0x000000be), propget, helpcontext(0x000100be)]
            VARIANT_BOOL DisplayEquation();
            [id(0x000000be), propput, helpcontext(0x000100be)]
            void DisplayEquation([in] VARIANT_BOOL rhs);
            [id(0x000000bd), propget, helpcontext(0x000100bd)]
            VARIANT_BOOL DisplayRSquared();
            [id(0x000000bd), propput, helpcontext(0x000100bd)]
            void DisplayRSquared([in] VARIANT_BOOL rhs);
            [id(0x000000bf), propget, helpcontext(0x000100bf)]
            long Forward();
            [id(0x000000bf), propput, helpcontext(0x000100bf)]
            void Forward([in] long rhs);
            [id(0x000001e6), propget, helpcontext(0x000101e6)]
            long Index();
            [id(0x000000ba), propget, helpcontext(0x000100ba)]
            double Intercept();
            [id(0x000000ba), propput, helpcontext(0x000100ba)]
            void Intercept([in] double rhs);
            [id(0x000000bb), propget, helpcontext(0x000100bb)]
            VARIANT_BOOL InterceptIsAuto();
            [id(0x000000bb), propput, helpcontext(0x000100bb)]
            void InterceptIsAuto([in] VARIANT_BOOL rhs);
            [id(0x0000006e), propget, helpcontext(0x0001006e)]
            BSTR Name();
            [id(0x0000006e), propput, helpcontext(0x0001006e)]
            void Name([in] BSTR rhs);
            [id(0x000000bc), propget, helpcontext(0x000100bc)]
            VARIANT_BOOL NameIsAuto();
            [id(0x000000bc), propput, helpcontext(0x000100bc)]
            void NameIsAuto([in] VARIANT_BOOL rhs);
            [id(0x000000c0), propget, helpcontext(0x000100c0)]
            long Order();
            [id(0x000000c0), propput, helpcontext(0x000100c0)]
            void Order([in] long rhs);
            [id(0x000000b8), propget, helpcontext(0x000100b8)]
            long Period();
            [id(0x000000b8), propput, helpcontext(0x000100b8)]
            void Period([in] long rhs);
            [id(0x000000eb), helpcontext(0x000100eb)]
            void Select();
            [id(0x0000006c), propget, helpcontext(0x0001006c)]
            XlTrendlineType Type();
            [id(0x0000006c), propput, helpcontext(0x0001006c)]
            void Type([in] XlTrendlineType rhs);
    };

    [
      uuid(000208C0-0000-0000-C000-000000000046),
      helpcontext(0x00020080)
    ]
    dispinterface Corners {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x0000006e), propget, helpcontext(0x0001006e)]
            BSTR Name();
            [id(0x000000eb), helpcontext(0x000100eb)]
            void Select();
    };

    [
      uuid(000208C1-0000-0000-C000-000000000046),
      helpcontext(0x00020081)
    ]
    dispinterface SeriesLines {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x0000006e), propget, helpcontext(0x0001006e)]
            BSTR Name();
            [id(0x000000eb), helpcontext(0x000100eb)]
            void Select();
            [id(0x00000080), propget, helpcontext(0x00010080)]
            Border* Border();
            [id(0x00000075), helpcontext(0x00010075)]
            void Delete();
    };
