import "Excel03.Idl";

    [
      odl,
      uuid(00020846-0001-0000-C000-000000000046),
      helpcontext(0x00020006),
      hidden
    ]
    interface IRange : IDispatch {
        [propget, helpcontext(0x00010094)]
        HRESULT _stdcall Application([out, retval] Application** RHS);
        [propget, helpcontext(0x00010095)]
        HRESULT _stdcall Creator([out, retval] XlCreator* RHS);
        [propget, helpcontext(0x00010096)]
        HRESULT _stdcall Parent([out, retval] IDispatch** RHS);
        [helpcontext(0x00010130)]
        HRESULT _stdcall Activate();
        [propget, helpcontext(0x00010427)]
        HRESULT _stdcall AddIndent([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010427)]
        HRESULT _stdcall AddIndent([in] VARIANT RHS);
        [propget, helpcontext(0x000100ec)]
        HRESULT _stdcall Address(
                        [in, optional] VARIANT RowAbsolute, 
                        [in, optional] VARIANT ColumnAbsolute, 
                        [in, optional, defaultvalue(1)] XlReferenceStyle ReferenceStyle, 
                        [in, optional] VARIANT External, 
                        [in, optional] VARIANT RelativeTo, 
                        [in, lcid] long lcid, 
                        [out, retval] BSTR* RHS);
        [propget, helpcontext(0x000101b5)]
        HRESULT _stdcall AddressLocal(
                        [in, optional] VARIANT RowAbsolute, 
                        [in, optional] VARIANT ColumnAbsolute, 
                        [in, optional, defaultvalue(1)] XlReferenceStyle ReferenceStyle, 
                        [in, optional] VARIANT External, 
                        [in, optional] VARIANT RelativeTo, 
                        [out, retval] BSTR* RHS);
        [helpcontext(0x0001036c)]
        HRESULT _stdcall AdvancedFilter(
                        [in] XlFilterAction Action, 
                        [in, optional] VARIANT CriteriaRange, 
                        [in, optional] VARIANT CopyToRange, 
                        [in, optional] VARIANT Unique);
        [helpcontext(0x000101b9)]
        HRESULT _stdcall ApplyNames(
                        [in, optional] VARIANT Names, 
                        [in, optional] VARIANT IgnoreRelativeAbsolute, 
                        [in, optional] VARIANT UseRowColumnNames, 
                        [in, optional] VARIANT OmitColumn, 
                        [in, optional] VARIANT OmitRow, 
                        [in, optional, defaultvalue(1)] XlApplyNamesOrder Order, 
                        [in, optional] VARIANT AppendLast);
        [helpcontext(0x000101c0)]
        HRESULT _stdcall ApplyOutlineStyles();
        [propget, helpcontext(0x00010238)]
        HRESULT _stdcall Areas([out, retval] Areas** RHS);
        [helpcontext(0x000104a1)]
        HRESULT _stdcall AutoComplete(
                        [in] BSTR String, 
                        [out, retval] BSTR* RHS);
        [helpcontext(0x000101c1)]
        HRESULT _stdcall AutoFill(
                        [in] Range* Destination, 
                        [in, optional, defaultvalue(0)] XlAutoFillType Type);
        [helpcontext(0x00010319)]
        HRESULT _stdcall AutoFilter(
                        [in, optional] VARIANT Field, 
                        [in, optional] VARIANT Criteria1, 
                        [in, optional, defaultvalue(1)] XlAutoFilterOperator Operator, 
                        [in, optional] VARIANT Criteria2, 
                        [in, optional] VARIANT VisibleDropDown);
        [helpcontext(0x000100ed)]
        HRESULT _stdcall AutoFit();
        [helpcontext(0x00010072)]
        HRESULT _stdcall AutoFormat(
                        [in, optional, defaultvalue(1)] XlRangeAutoFormat Format, 
                        [in, optional] VARIANT Number, 
                        [in, optional] VARIANT Font, 
                        [in, optional] VARIANT Alignment, 
                        [in, optional] VARIANT Border, 
                        [in, optional] VARIANT Pattern, 
                        [in, optional] VARIANT Width);
        [helpcontext(0x0001040c)]
        HRESULT _stdcall AutoOutline();
        [helpcontext(0x0001042b)]
        HRESULT _stdcall BorderAround(
                        [in, optional] VARIANT LineStyle, 
                        [in, optional, defaultvalue(2)] XlBorderWeight Weight, 
                        [in, optional, defaultvalue(-4105)] XlColorIndex ColorIndex, 
                        [in, optional] VARIANT Color);
        [propget, helpcontext(0x000101b3)]
        HRESULT _stdcall Borders([out, retval] Borders** RHS);
        [helpcontext(0x00010117)]
        HRESULT _stdcall Calculate();
        [propget, helpcontext(0x000100ee)]
        HRESULT _stdcall Cells([out, retval] Range** RHS);
        [propget, helpcontext(0x0001025b)]
        HRESULT _stdcall Characters(
                        [in, optional] VARIANT Start, 
                        [in, optional] VARIANT Length, 
                        [out, retval] Characters** RHS);
        [helpcontext(0x000101f9)]
        HRESULT _stdcall CheckSpelling(
                        [in, optional] VARIANT CustomDictionary, 
                        [in, optional] VARIANT IgnoreUppercase, 
                        [in, optional] VARIANT AlwaysSuggest, 
                        [in, optional] VARIANT IgnoreInitialAlefHamza, 
                        [in, optional] VARIANT IgnoreFinalYaa, 
                        [in, optional] VARIANT SpellScript);
        [helpcontext(0x0001006f)]
        HRESULT _stdcall Clear();
        [helpcontext(0x00010071)]
        HRESULT _stdcall ClearContents();
        [helpcontext(0x00010070)]
        HRESULT _stdcall ClearFormats();
        [helpcontext(0x000100ef)]
        HRESULT _stdcall ClearNotes();
        [helpcontext(0x0001040d)]
        HRESULT _stdcall ClearOutline();
        [propget, helpcontext(0x000100f0)]
        HRESULT _stdcall Column([out, retval] long* RHS);
        [helpcontext(0x000101fe)]
        HRESULT _stdcall ColumnDifferences(
                        [in] VARIANT Comparison, 
                        [out, retval] Range** RHS);
        [propget, helpcontext(0x000100f1)]
        HRESULT _stdcall Columns([out, retval] Range** RHS);
        [propget, helpcontext(0x000100f2)]
        HRESULT _stdcall ColumnWidth([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x000100f2)]
        HRESULT _stdcall ColumnWidth([in] VARIANT RHS);
        [helpcontext(0x000101e2)]
        HRESULT _stdcall Consolidate(
                        [in, optional] VARIANT Sources, 
                        [in, optional] VARIANT Function, 
                        [in, optional] VARIANT TopRow, 
                        [in, optional] VARIANT LeftColumn, 
                        [in, optional] VARIANT CreateLinks);
        [helpcontext(0x00010227)]
        HRESULT _stdcall Copy([in, optional] VARIANT Destination);
        [helpcontext(0x00010480)]
        HRESULT _stdcall CopyFromRecordset(
                        [in] IUnknown* Data, 
                        [in, optional] VARIANT MaxRows, 
                        [in, optional] VARIANT MaxColumns, 
                        [out, retval] long* RHS);
        [helpcontext(0x000100d5)]
        HRESULT _stdcall CopyPicture(
                        [in, optional, defaultvalue(1)] XlPictureAppearance Appearance, 
                        [in, optional, defaultvalue(-4147)] XlCopyPictureFormat Format);
        [propget, helpcontext(0x00010076)]
        HRESULT _stdcall Count([out, retval] long* RHS);
        [helpcontext(0x000101c9)]
        HRESULT _stdcall CreateNames(
                        [in, optional] VARIANT Top, 
                        [in, optional] VARIANT Left, 
                        [in, optional] VARIANT Bottom, 
                        [in, optional] VARIANT Right);
        [helpcontext(0x000101ca)]
        HRESULT _stdcall CreatePublisher(
                        [in, optional] VARIANT Edition, 
                        [in, optional, defaultvalue(1)] XlPictureAppearance Appearance, 
                        [in, optional] VARIANT ContainsPICT, 
                        [in, optional] VARIANT ContainsBIFF, 
                        [in, optional] VARIANT ContainsRTF, 
                        [in, optional] VARIANT ContainsVALU);
        [propget, helpcontext(0x000101f5)]
        HRESULT _stdcall CurrentArray([out, retval] Range** RHS);
        [propget, helpcontext(0x000100f3)]
        HRESULT _stdcall CurrentRegion([out, retval] Range** RHS);
        [helpcontext(0x00010235)]
        HRESULT _stdcall Cut([in, optional] VARIANT Destination);
        [helpcontext(0x000101d0)]
        HRESULT _stdcall DataSeries(
                        [in, optional] VARIANT Rowcol, 
                        [in, optional, defaultvalue(-4132)] XlDataSeriesType Type, 
                        [in, optional, defaultvalue(1)] XlDataSeriesDate Date, 
                        [in, optional] VARIANT Step, 
                        [in, optional] VARIANT Stop, 
                        [in, optional] VARIANT Trend);
        [propget, helpcontext(0x00010000)]
        HRESULT _stdcall _Default(
                        [in, optional] VARIANT RowIndex, 
                        [in, optional] VARIANT ColumnIndex, 
                        [in, lcid] long lcid, 
                        [out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010000)]
        HRESULT _stdcall _Default(
                        [in, optional] VARIANT RowIndex, 
                        [in, optional] VARIANT ColumnIndex, 
                        [in, lcid] long lcid, 
                        [in] VARIANT RHS);
        [helpcontext(0x00010075)]
        HRESULT _stdcall Delete([in, optional] VARIANT Shift);
        [propget, helpcontext(0x0001021f)]
        HRESULT _stdcall Dependents([out, retval] Range** RHS);
        [helpcontext(0x000100f5)]
        HRESULT _stdcall DialogBox([out, retval] VARIANT* RHS);
        [propget, helpcontext(0x00010221)]
        HRESULT _stdcall DirectDependents([out, retval] Range** RHS);
        [propget, helpcontext(0x00010222)]
        HRESULT _stdcall DirectPrecedents([out, retval] Range** RHS);
        [helpcontext(0x0001046b)]
        HRESULT _stdcall EditionOptions(
                        [in] XlEditionType Type, 
                        [in] XlEditionOptionsOption Option, 
                        [in, optional] VARIANT Name, 
                        [in, optional] VARIANT Reference, 
                        [in, optional, defaultvalue(1)] XlPictureAppearance Appearance, 
                        [in, optional, defaultvalue(1)] XlPictureAppearance ChartSize, 
                        [in, optional] VARIANT Format, 
                        [out, retval] VARIANT* RHS);
        [propget, helpcontext(0x000101f4)]
        HRESULT _stdcall End(
                        [in] XlDirection Direction, 
                        [out, retval] Range** RHS);
        [propget, helpcontext(0x000100f6)]
        HRESULT _stdcall EntireColumn([out, retval] Range** RHS);
        [propget, helpcontext(0x000100f7)]
        HRESULT _stdcall EntireRow([out, retval] Range** RHS);
        [helpcontext(0x000100f8)]
        HRESULT _stdcall FillDown();
        [helpcontext(0x000100f9)]
        HRESULT _stdcall FillLeft();
        [helpcontext(0x000100fa)]
        HRESULT _stdcall FillRight();
        [helpcontext(0x000100fb)]
        HRESULT _stdcall FillUp();
        [helpcontext(0x0001018e)]
        HRESULT _stdcall Find(
                        [in] VARIANT What, 
                        [in, optional] VARIANT After, 
                        [in, optional] VARIANT LookIn, 
                        [in, optional] VARIANT LookAt, 
                        [in, optional] VARIANT SearchOrder, 
                        [in, optional, defaultvalue(1)] XlSearchDirection SearchDirection, 
                        [in, optional] VARIANT MatchCase, 
                        [in, optional] VARIANT MatchByte, 
                        [in, optional] VARIANT MatchControlCharacters, 
                        [in, optional] VARIANT MatchDiacritics, 
                        [in, optional] VARIANT MatchKashida, 
                        [in, optional] VARIANT MatchAlefHamza, 
                        [out, retval] Range** RHS);
        [helpcontext(0x0001018f)]
        HRESULT _stdcall FindNext(
                        [in, optional] VARIANT After, 
                        [out, retval] Range** RHS);
        [helpcontext(0x00010190)]
        HRESULT _stdcall FindPrevious(
                        [in, optional] VARIANT After, 
                        [out, retval] Range** RHS);
        [propget, helpcontext(0x00010092)]
        HRESULT _stdcall Font([out, retval] Font** RHS);
        [propget, helpcontext(0x00010105)]
        HRESULT _stdcall Formula(
                        [in, lcid] long lcid, 
                        [out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010105)]
        HRESULT _stdcall Formula(
                        [in, lcid] long lcid, 
                        [in] VARIANT RHS);
        [propget, helpcontext(0x0001024a)]
        HRESULT _stdcall FormulaArray([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x0001024a)]
        HRESULT _stdcall FormulaArray([in] VARIANT RHS);
        [propget, helpcontext(0x00010564)]
        HRESULT _stdcall FormulaLabel([out, retval] XlFormulaLabel* RHS);
        [propput, helpcontext(0x00010564)]
        HRESULT _stdcall FormulaLabel([in] XlFormulaLabel RHS);
        [propget, helpcontext(0x00010106)]
        HRESULT _stdcall FormulaHidden([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010106)]
        HRESULT _stdcall FormulaHidden([in] VARIANT RHS);
        [propget, helpcontext(0x00010107)]
        HRESULT _stdcall FormulaLocal([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010107)]
        HRESULT _stdcall FormulaLocal([in] VARIANT RHS);
        [propget, helpcontext(0x00010108)]
        HRESULT _stdcall FormulaR1C1(
                        [in, lcid] long lcid, 
                        [out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010108)]
        HRESULT _stdcall FormulaR1C1(
                        [in, lcid] long lcid, 
                        [in] VARIANT RHS);
        [propget, helpcontext(0x00010109)]
        HRESULT _stdcall FormulaR1C1Local([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010109)]
        HRESULT _stdcall FormulaR1C1Local([in] VARIANT RHS);
        [helpcontext(0x0001023b)]
        HRESULT _stdcall FunctionWizard();
        [helpcontext(0x000101d8)]
        HRESULT _stdcall GoalSeek(
                        [in] VARIANT Goal, 
                        [in] Range* ChangingCell, 
                        [out, retval] VARIANT_BOOL* RHS);
        [helpcontext(0x0001002e)]
        HRESULT _stdcall Group(
                        [in, optional] VARIANT Start, 
                        [in, optional] VARIANT End, 
                        [in, optional] VARIANT By, 
                        [in, optional] VARIANT Periods, 
                        [out, retval] VARIANT* RHS);
        [propget, helpcontext(0x0001010a)]
        HRESULT _stdcall HasArray([out, retval] VARIANT* RHS);
        [propget, helpcontext(0x0001010b)]
        HRESULT _stdcall HasFormula([out, retval] VARIANT* RHS);
        [propget, helpcontext(0x0001007b)]
        HRESULT _stdcall Height([out, retval] VARIANT* RHS);
        [propget, helpcontext(0x0001010c)]
        HRESULT _stdcall Hidden([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x0001010c)]
        HRESULT _stdcall Hidden([in] VARIANT RHS);
        [propget, helpcontext(0x00010088)]
        HRESULT _stdcall HorizontalAlignment([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010088)]
        HRESULT _stdcall HorizontalAlignment([in] VARIANT RHS);
        [propget, helpcontext(0x000100c9)]
        HRESULT _stdcall IndentLevel([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x000100c9)]
        HRESULT _stdcall IndentLevel([in] VARIANT RHS);
        [helpcontext(0x00010565)]
        HRESULT _stdcall InsertIndent([in] long InsertAmount);
        [helpcontext(0x000100fc)]
        HRESULT _stdcall Insert([in, optional] VARIANT Shift);
        [propget, helpcontext(0x00010081)]
        HRESULT _stdcall Interior([out, retval] Interior** RHS);
        [propget, helpcontext(0x000100aa)]
        HRESULT _stdcall Item(
                        [in] VARIANT RowIndex, 
                        [in, optional] VARIANT ColumnIndex, 
                        [in, lcid] long lcid, 
                        [out, retval] VARIANT* RHS);
        [propput, helpcontext(0x000100aa)]
        HRESULT _stdcall Item(
                        [in] VARIANT RowIndex, 
                        [in, optional] VARIANT ColumnIndex, 
                        [in, lcid] long lcid, 
                        [in] VARIANT RHS);
        [helpcontext(0x000101ef)]
        HRESULT _stdcall Justify();
        [propget, helpcontext(0x0001007f)]
        HRESULT _stdcall Left([out, retval] VARIANT* RHS);
        [propget, helpcontext(0x000104a3)]
        HRESULT _stdcall ListHeaderRows([out, retval] long* RHS);
        [helpcontext(0x000100fd)]
        HRESULT _stdcall ListNames();
        [propget, helpcontext(0x000102b3)]
        HRESULT _stdcall LocationInTable([out, retval] XlLocationInTable* RHS);
        [propget, helpcontext(0x0001010d)]
        HRESULT _stdcall Locked([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x0001010d)]
        HRESULT _stdcall Locked([in] VARIANT RHS);
        [helpcontext(0x00010234)]
        HRESULT _stdcall Merge([in, optional] VARIANT Across);
        [helpcontext(0x00010568)]
        HRESULT _stdcall UnMerge();
        [propget, helpcontext(0x00010569)]
        HRESULT _stdcall MergeArea([out, retval] Range** RHS);
        [propget, helpcontext(0x000100d0)]
        HRESULT _stdcall MergeCells([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x000100d0)]
        HRESULT _stdcall MergeCells([in] VARIANT RHS);
        [propget, helpcontext(0x0001006e)]
        HRESULT _stdcall Name([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x0001006e)]
        HRESULT _stdcall Name([in] VARIANT RHS);
        [helpcontext(0x00010408)]
        HRESULT _stdcall NavigateArrow(
                        [in, optional] VARIANT TowardPrecedent, 
                        [in, optional] VARIANT ArrowNumber, 
                        [in, optional] VARIANT LinkNumber);
        [propget, helpcontext(0x0000fffc)]
        HRESULT _stdcall _NewEnum([out, retval] IUnknown** RHS);
        [propget, helpcontext(0x000101f6)]
        HRESULT _stdcall Next([out, retval] Range** RHS);
        [helpcontext(0x00010467)]
        HRESULT _stdcall NoteText(
                        [in, optional] VARIANT Text, 
                        [in, optional] VARIANT Start, 
                        [in, optional] VARIANT Length, 
                        [out, retval] BSTR* RHS);
        [propget, helpcontext(0x000100c1)]
        HRESULT _stdcall NumberFormat([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x000100c1)]
        HRESULT _stdcall NumberFormat([in] VARIANT RHS);
        [propget, helpcontext(0x00010449)]
        HRESULT _stdcall NumberFormatLocal([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010449)]
        HRESULT _stdcall NumberFormatLocal([in] VARIANT RHS);
        [propget, helpcontext(0x000100fe)]
        HRESULT _stdcall Offset(
                        [in, optional] VARIANT RowOffset, 
                        [in, optional] VARIANT ColumnOffset, 
                        [out, retval] Range** RHS);
        [propget, helpcontext(0x00010086)]
        HRESULT _stdcall Orientation([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010086)]
        HRESULT _stdcall Orientation([in] VARIANT RHS);
        [propget, helpcontext(0x0001010f)]
        HRESULT _stdcall OutlineLevel([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x0001010f)]
        HRESULT _stdcall OutlineLevel([in] VARIANT RHS);
        [propget, helpcontext(0x000100ff)]
        HRESULT _stdcall PageBreak([out, retval] long* RHS);
        [propput, helpcontext(0x000100ff)]
        HRESULT _stdcall PageBreak([in] long RHS);
        [helpcontext(0x000101dd)]
        HRESULT _stdcall Parse(
                        [in, optional] VARIANT ParseLine, 
                        [in, optional] VARIANT Destination);
        [helpcontext(0x00010403)]
        HRESULT _stdcall PasteSpecial(
                        [in, optional, defaultvalue(-4104)] XlPasteType Paste, 
                        [in, optional, defaultvalue(-4142)] XlPasteSpecialOperation Operation, 
                        [in, optional] VARIANT SkipBlanks, 
                        [in, optional] VARIANT Transpose);
        [propget, helpcontext(0x000102db)]
        HRESULT _stdcall PivotField([out, retval] PivotField** RHS);
        [propget, helpcontext(0x000102e4)]
        HRESULT _stdcall PivotItem([out, retval] PivotItem** RHS);
        [propget, helpcontext(0x000102cc)]
        HRESULT _stdcall PivotTable([out, retval] PivotTable** RHS);
        [propget, helpcontext(0x00010220)]
        HRESULT _stdcall Precedents([out, retval] Range** RHS);
        [propget, helpcontext(0x000101f8)]
        HRESULT _stdcall PrefixCharacter([out, retval] VARIANT* RHS);
        [propget, helpcontext(0x000101f7)]
        HRESULT _stdcall Previous([out, retval] Range** RHS);
        [helpcontext(0x00010389)]
        HRESULT _stdcall PrintOut(
                        [in, optional] VARIANT From, 
                        [in, optional] VARIANT To, 
                        [in, optional] VARIANT Copies, 
                        [in, optional] VARIANT Preview, 
                        [in, optional] VARIANT ActivePrinter, 
                        [in, optional] VARIANT PrintToFile, 
                        [in, optional] VARIANT Collate);
        [helpcontext(0x00010119)]
        HRESULT _stdcall PrintPreview([in, optional] VARIANT EnableChanges);
        [propget, helpcontext(0x0001056a)]
        HRESULT _stdcall QueryTable([out, retval] QueryTable** RHS);
        [propget, helpcontext(0x000100c5)]
        HRESULT _stdcall Range(
                        [in] VARIANT Cell1, 
                        [in, optional] VARIANT Cell2, 
                        [out, retval] Range** RHS);
        [helpcontext(0x00010373)]
        HRESULT _stdcall RemoveSubtotal();
        [helpcontext(0x000100e2)]
        HRESULT _stdcall Replace(
                        [in] VARIANT What, 
                        [in] VARIANT Replacement, 
                        [in, optional] VARIANT LookAt, 
                        [in, optional] VARIANT SearchOrder, 
                        [in, optional] VARIANT MatchCase, 
                        [in, optional] VARIANT MatchByte, 
                        [in, optional] VARIANT MatchControlCharacters, 
                        [in, optional] VARIANT MatchDiacritics, 
                        [in, optional] VARIANT MatchKashida, 
                        [in, optional] VARIANT MatchAlefHamza, 
                        [out, retval] VARIANT_BOOL* RHS);
        [propget, helpcontext(0x00010100)]
        HRESULT _stdcall Resize(
                        [in, optional] VARIANT RowSize, 
                        [in, optional] VARIANT ColumnSize, 
                        [out, retval] Range** RHS);
        [propget, helpcontext(0x00010101)]
        HRESULT _stdcall Row([out, retval] long* RHS);
        [helpcontext(0x000101ff)]
        HRESULT _stdcall RowDifferences(
                        [in] VARIANT Comparison, 
                        [out, retval] Range** RHS);
        [propget, helpcontext(0x00010110)]
        HRESULT _stdcall RowHeight([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010110)]
        HRESULT _stdcall RowHeight([in] VARIANT RHS);
        [propget, helpcontext(0x00010102)]
        HRESULT _stdcall Rows([out, retval] Range** RHS);
        [helpcontext(0x00010103)]
        HRESULT _stdcall Run(
                        [in, optional] VARIANT Arg1, 
                        [in, optional] VARIANT Arg2, 
                        [in, optional] VARIANT Arg3, 
                        [in, optional] VARIANT Arg4, 
                        [in, optional] VARIANT Arg5, 
                        [in, optional] VARIANT Arg6, 
                        [in, optional] VARIANT Arg7, 
                        [in, optional] VARIANT Arg8, 
                        [in, optional] VARIANT Arg9, 
                        [in, optional] VARIANT Arg10, 
                        [in, optional] VARIANT Arg11, 
                        [in, optional] VARIANT Arg12, 
                        [in, optional] VARIANT Arg13, 
                        [in, optional] VARIANT Arg14, 
                        [in, optional] VARIANT Arg15, 
                        [in, optional] VARIANT Arg16, 
                        [in, optional] VARIANT Arg17, 
                        [in, optional] VARIANT Arg18, 
                        [in, optional] VARIANT Arg19, 
                        [in, optional] VARIANT Arg20, 
                        [in, optional] VARIANT Arg21, 
                        [in, optional] VARIANT Arg22, 
                        [in, optional] VARIANT Arg23, 
                        [in, optional] VARIANT Arg24, 
                        [in, optional] VARIANT Arg25, 
                        [in, optional] VARIANT Arg26, 
                        [in, optional] VARIANT Arg27, 
                        [in, optional] VARIANT Arg28, 
                        [in, optional] VARIANT Arg29, 
                        [in, optional] VARIANT Arg30, 
                        [out, retval] VARIANT* RHS);
        [helpcontext(0x000100eb)]
        HRESULT _stdcall Select();
        [helpcontext(0x000101f0)]
        HRESULT _stdcall Show();
        [helpcontext(0x0001036d)]
        HRESULT _stdcall ShowDependents([in, optional] VARIANT Remove);
        [propget, helpcontext(0x00010249)]
        HRESULT _stdcall ShowDetail([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010249)]
        HRESULT _stdcall ShowDetail([in] VARIANT RHS);
        [helpcontext(0x0001036e)]
        HRESULT _stdcall ShowErrors();
        [helpcontext(0x0001036f)]
        HRESULT _stdcall ShowPrecedents([in, optional] VARIANT Remove);
        [propget, helpcontext(0x000100d1)]
        HRESULT _stdcall ShrinkToFit([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x000100d1)]
        HRESULT _stdcall ShrinkToFit([in] VARIANT RHS);
        [helpcontext(0x00010370)]
        HRESULT _stdcall Sort(
                        [in, optional] VARIANT Key1, 
                        [in, optional, defaultvalue(1)] XlSortOrder Order1, 
                        [in, optional] VARIANT Key2, 
                        [in, optional] VARIANT Type, 
                        [in, optional, defaultvalue(1)] XlSortOrder Order2, 
                        [in, optional] VARIANT Key3, 
                        [in, optional, defaultvalue(1)] XlSortOrder Order3, 
                        [in, optional, defaultvalue(2)] XlYesNoGuess Header, 
                        [in, optional] VARIANT OrderCustom, 
                        [in, optional] VARIANT MatchCase, 
                        [in, optional, defaultvalue(2)] XlSortOrientation Orientation, 
                        [in, optional, defaultvalue(1)] XlSortMethod SortMethod, 
                        [in, optional] VARIANT IgnoreControlCharacters, 
                        [in, optional] VARIANT IgnoreDiacritics, 
                        [in, optional] VARIANT IgnoreKashida);
        [helpcontext(0x00010371)]
        HRESULT _stdcall SortSpecial(
                        [in, optional, defaultvalue(1)] XlSortMethod SortMethod, 
                        [in, optional] VARIANT Key1, 
                        [in, optional, defaultvalue(1)] XlSortOrder Order1, 
                        [in, optional] VARIANT Type, 
                        [in, optional] VARIANT Key2, 
                        [in, optional, defaultvalue(1)] XlSortOrder Order2, 
                        [in, optional] VARIANT Key3, 
                        [in, optional, defaultvalue(1)] XlSortOrder Order3, 
                        [in, optional, defaultvalue(2)] XlYesNoGuess Header, 
                        [in, optional] VARIANT OrderCustom, 
                        [in, optional] VARIANT MatchCase, 
                        [in, optional, defaultvalue(2)] XlSortOrientation Orientation);
        [propget, helpcontext(0x00010394)]
        HRESULT _stdcall SoundNote([out, retval] SoundNote** RHS);
        [helpcontext(0x0001019a)]
        HRESULT _stdcall SpecialCells(
                        [in] XlCellType Type, 
                        [in, optional] VARIANT Value, 
                        [out, retval] Range** RHS);
        [propget, helpcontext(0x00010104)]
        HRESULT _stdcall Style([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010104)]
        HRESULT _stdcall Style([in] VARIANT RHS);
        [helpcontext(0x000101e1)]
        HRESULT _stdcall SubscribeTo(
                        [in] BSTR Edition, 
                        [in, optional, defaultvalue(-4158)] XlSubscribeToFormat Format);
        [helpcontext(0x00010372)]
        HRESULT _stdcall Subtotal(
                        [in] long GroupBy, 
                        [in] XlConsolidationFunction Function, 
                        [in] VARIANT TotalList, 
                        [in, optional] VARIANT Replace, 
                        [in, optional] VARIANT PageBreaks, 
                        [in, optional, defaultvalue(1)] XlSummaryRow SummaryBelowData);
        [propget, helpcontext(0x00010111)]
        HRESULT _stdcall Summary([out, retval] VARIANT* RHS);
        [helpcontext(0x000101f1)]
        HRESULT _stdcall Table(
                        [in, optional] VARIANT RowInput, 
                        [in, optional] VARIANT ColumnInput);
        [propget, helpcontext(0x0001008a)]
        HRESULT _stdcall Text([out, retval] VARIANT* RHS);
        [helpcontext(0x00010410)]
        HRESULT _stdcall TextToColumns(
                        [in, optional] VARIANT Destination, 
                        [in, optional, defaultvalue(1)] XlTextParsingType DataType, 
                        [in, optional, defaultvalue(1)] XlTextQualifier TextQualifier, 
                        [in, optional] VARIANT ConsecutiveDelimiter, 
                        [in, optional] VARIANT Tab, 
                        [in, optional] VARIANT Semicolon, 
                        [in, optional] VARIANT Comma, 
                        [in, optional] VARIANT Space, 
                        [in, optional] VARIANT Other, 
                        [in, optional] VARIANT OtherChar, 
                        [in, optional] VARIANT FieldInfo);
        [propget, helpcontext(0x0001007e)]
        HRESULT _stdcall Top([out, retval] VARIANT* RHS);
        [helpcontext(0x000100f4)]
        HRESULT _stdcall Ungroup();
        [propget, helpcontext(0x00010112)]
        HRESULT _stdcall UseStandardHeight([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010112)]
        HRESULT _stdcall UseStandardHeight([in] VARIANT RHS);
        [propget, helpcontext(0x00010113)]
        HRESULT _stdcall UseStandardWidth([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010113)]
        HRESULT _stdcall UseStandardWidth([in] VARIANT RHS);
        [propget, helpcontext(0x0001056b)]
        HRESULT _stdcall Validation([out, retval] Validation** RHS);
        [propget, helpcontext(0x00010006)]
        HRESULT _stdcall Value(
                        [in, lcid] long lcid, 
                        [out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010006)]
        HRESULT _stdcall Value(
                        [in, lcid] long lcid, 
                        [in] VARIANT RHS);
        [propget, helpcontext(0x0001056c)]
        HRESULT _stdcall Value2(
                        [in, lcid] long lcid, 
                        [out, retval] VARIANT* RHS);
        [propput, helpcontext(0x0001056c)]
        HRESULT _stdcall Value2(
                        [in, lcid] long lcid, 
                        [in] VARIANT RHS);
        [propget, helpcontext(0x00010089)]
        HRESULT _stdcall VerticalAlignment([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010089)]
        HRESULT _stdcall VerticalAlignment([in] VARIANT RHS);
        [propget, helpcontext(0x0001007a)]
        HRESULT _stdcall Width([out, retval] VARIANT* RHS);
        [propget, helpcontext(0x0001015c)]
        HRESULT _stdcall Worksheet([out, retval] Worksheet** RHS);
        [propget, helpcontext(0x00010114)]
        HRESULT _stdcall WrapText([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010114)]
        HRESULT _stdcall WrapText([in] VARIANT RHS);
        [helpcontext(0x0001056d)]
        HRESULT _stdcall AddComment(
                        [in, optional] VARIANT Text, 
                        [out, retval] Comment** RHS);
        [propget, helpcontext(0x0001038e)]
        HRESULT _stdcall Comment([out, retval] Comment** RHS);
        [helpcontext(0x0001056e)]
        HRESULT _stdcall ClearComments();
        [propget, helpcontext(0x0001056f)]
        HRESULT _stdcall Phonetic([out, retval] Phonetic** RHS);
        [propget, helpcontext(0x00010570)]
        HRESULT _stdcall FormatConditions([out, retval] FormatConditions** RHS);
        [propget, helpcontext(0x000103cf)]
        HRESULT _stdcall ReadingOrder([out, retval] long* RHS);
        [propput, helpcontext(0x000103cf)]
        HRESULT _stdcall ReadingOrder([in] long RHS);
        [propget, helpcontext(0x00010571)]
        HRESULT _stdcall Hyperlinks([out, retval] Hyperlinks** RHS);
    };

    [
      odl,
      uuid(0002440F-0001-0000-C000-000000000046),
      helpcontext(0x000200a5),
      hidden
    ]
    interface IChartEvents : IDispatch {
        [helpcontext(0x00010130)]
        HRESULT _stdcall Activate();
        [helpcontext(0x000105fa)]
        HRESULT _stdcall Deactivate();
        [helpcontext(0x00010100)]
        HRESULT _stdcall Resize();
        [helpcontext(0x000105fb)]
        HRESULT _stdcall MouseDown(
                        [in] XlMouseButton Button, 
                        [in] long Shift, 
                        [in] long X, 
                        [in] long Y);
        [helpcontext(0x000105fc)]
        HRESULT _stdcall MouseUp(
                        [in] XlMouseButton Button, 
                        [in] long Shift, 
                        [in] long X, 
                        [in] long Y);
        [helpcontext(0x000105fd)]
        HRESULT _stdcall MouseMove(
                        [in] XlMouseButton Button, 
                        [in] long Shift, 
                        [in] long X, 
                        [in] long Y);
        [helpcontext(0x000105fe)]
        HRESULT _stdcall BeforeRightClick([in] VARIANT_BOOL* Cancel);
        [helpcontext(0x000105ff)]
        HRESULT _stdcall DragPlot();
        [helpcontext(0x00010600)]
        HRESULT _stdcall DragOver();
        [helpcontext(0x00010601)]
        HRESULT _stdcall BeforeDoubleClick(
                        [in] XlChartItem ElementID, 
                        [in] long Arg1, 
                        [in] long Arg2, 
                        [in] VARIANT_BOOL* Cancel);
        [helpcontext(0x000100eb)]
        HRESULT _stdcall Select(
                        [in] XlChartItem ElementID, 
                        [in] long Arg1, 
                        [in] long Arg2);
        [helpcontext(0x00010602)]
        HRESULT _stdcall SeriesChange(
                        [in] long SeriesIndex, 
                        [in] long PointIndex);
        [helpcontext(0x00010117)]
        HRESULT _stdcall Calculate();
    };

    [
      odl,
      uuid(000208D6-0000-0000-C000-000000000046),
      helpcontext(0x00020007),
      dual,
      nonextensible,
      oleautomation
    ]
    interface _Chart : IDispatch {
        [id(0x00000094), propget, helpcontext(0x00010094)]
        HRESULT Application([out, retval] Application** RHS);
        [id(0x00000095), propget, helpcontext(0x00010095)]
        HRESULT Creator([out, retval] XlCreator* RHS);
        [id(0x00000096), propget, helpcontext(0x00010096)]
        HRESULT Parent([out, retval] IDispatch** RHS);
        [id(0x00000130), helpcontext(0x00010130)]
        HRESULT Activate([in, lcid] long lcid);
        [id(0x00000227), helpcontext(0x00010227)]
        HRESULT Copy(
                        [in, optional] VARIANT Before, 
                        [in, optional] VARIANT After, 
                        [in, lcid] long lcid);
        [id(0x00000075), helpcontext(0x00010075)]
        HRESULT Delete([in, lcid] long lcid);
        [id(0x0000055d), propget, helpcontext(0x0001055d)]
        HRESULT CodeName([out, retval] BSTR* RHS);
        [id(0x80010000), propget, helpcontext(0x80020000)]
        HRESULT _CodeName([out, retval] BSTR* RHS);
        [id(0x80010000), propput, helpcontext(0x80020000)]
        HRESULT _CodeName([in] BSTR RHS);
        [id(0x000001e6), propget, helpcontext(0x000101e6)]
        HRESULT Index(
                        [in, lcid] long lcid, 
                        [out, retval] long* RHS);
        [id(0x0000027d), helpcontext(0x0001027d)]
        HRESULT Move(
                        [in, optional] VARIANT Before, 
                        [in, optional] VARIANT After, 
                        [in, lcid] long lcid);
        [id(0x0000006e), propget, helpcontext(0x0001006e)]
        HRESULT Name([out, retval] BSTR* RHS);
        [id(0x0000006e), propput, helpcontext(0x0001006e)]
        HRESULT Name([in] BSTR RHS);
        [id(0x000001f6), propget, helpcontext(0x000101f6)]
        HRESULT Next([out, retval] IDispatch** RHS);
        [id(0x00000274), propget, hidden, helpcontext(0x00010274)]
        HRESULT OnDoubleClick(
                        [in, lcid] long lcid, 
                        [out, retval] BSTR* RHS);
        [id(0x00000274), propput, hidden, helpcontext(0x00010274)]
        HRESULT OnDoubleClick(
                        [in, lcid] long lcid, 
                        [in] BSTR RHS);
        [id(0x00000407), propget, hidden, helpcontext(0x00010407)]
        HRESULT OnSheetActivate(
                        [in, lcid] long lcid, 
                        [out, retval] BSTR* RHS);
        [id(0x00000407), propput, hidden, helpcontext(0x00010407)]
        HRESULT OnSheetActivate(
                        [in, lcid] long lcid, 
                        [in] BSTR RHS);
        [id(0x00000439), propget, hidden, helpcontext(0x00010439)]
        HRESULT OnSheetDeactivate(
                        [in, lcid] long lcid, 
                        [out, retval] BSTR* RHS);
        [id(0x00000439), propput, hidden, helpcontext(0x00010439)]
        HRESULT OnSheetDeactivate(
                        [in, lcid] long lcid, 
                        [in] BSTR RHS);
        [id(0x000003e6), propget, helpcontext(0x000103e6)]
        HRESULT PageSetup([out, retval] PageSetup** RHS);
        [id(0x000001f7), propget, helpcontext(0x000101f7)]
        HRESULT Previous([out, retval] IDispatch** RHS);
        [id(0x00000389), helpcontext(0x00010389)]
        HRESULT PrintOut(
                        [in, optional] VARIANT From, 
                        [in, optional] VARIANT To, 
                        [in, optional] VARIANT Copies, 
                        [in, optional] VARIANT Preview, 
                        [in, optional] VARIANT ActivePrinter, 
                        [in, optional] VARIANT PrintToFile, 
                        [in, optional] VARIANT Collate, 
                        [in, lcid] long lcid);
        [id(0x00000119), helpcontext(0x00010119)]
        HRESULT PrintPreview(
                        [in, optional] VARIANT EnableChanges, 
                        [in, lcid] long lcid);
        [id(0x0000011a), helpcontext(0x0001011a)]
        HRESULT Protect(
                        [in, optional] VARIANT Password, 
                        [in, optional] VARIANT DrawingObjects, 
                        [in, optional] VARIANT Contents, 
                        [in, optional] VARIANT Scenarios, 
                        [in, optional] VARIANT UserInterfaceOnly, 
                        [in, lcid] long lcid);
        [id(0x00000124), propget, helpcontext(0x00010124)]
        HRESULT ProtectContents(
                        [in, lcid] long lcid, 
                        [out, retval] VARIANT_BOOL* RHS);
        [id(0x00000125), propget, helpcontext(0x00010125)]
        HRESULT ProtectDrawingObjects(
                        [in, lcid] long lcid, 
                        [out, retval] VARIANT_BOOL* RHS);
        [id(0x00000487), propget, helpcontext(0x00010487)]
        HRESULT ProtectionMode(
                        [in, lcid] long lcid, 
                        [out, retval] VARIANT_BOOL* RHS);
        [id(0x00010017), restricted, hidden]
        void _Dummy23();
        [id(0x0000011c), helpcontext(0x0001011c)]
        HRESULT SaveAs(
                        [in] BSTR Filename, 
                        [in, optional] VARIANT FileFormat, 
                        [in, optional] VARIANT Password, 
                        [in, optional] VARIANT WriteResPassword, 
                        [in, optional] VARIANT ReadOnlyRecommended, 
                        [in, optional] VARIANT CreateBackup, 
                        [in, optional] VARIANT AddToMru, 
                        [in, optional] VARIANT TextCodepage, 
                        [in, optional] VARIANT TextVisualLayout, 
                        [in, lcid] long lcid);
        [id(0x000000eb), helpcontext(0x000100eb)]
        HRESULT Select(
                        [in, optional] VARIANT Replace, 
                        [in, lcid] long lcid);
        [id(0x0000011d), helpcontext(0x0001011d)]
        HRESULT Unprotect(
                        [in, optional] VARIANT Password, 
                        [in, lcid] long lcid);
        [id(0x0000022e), propget, helpcontext(0x0001022e)]
        HRESULT Visible(
                        [in, lcid] long lcid, 
                        [out, retval] XlSheetVisibility* RHS);
        [id(0x0000022e), propput, helpcontext(0x0001022e)]
        HRESULT Visible(
                        [in, lcid] long lcid, 
                        [in] XlSheetVisibility RHS);
        [id(0x00000561), propget, helpcontext(0x00010561)]
        HRESULT Shapes([out, retval] Shapes** RHS);
        [id(0x00000097), helpcontext(0x00010097)]
        HRESULT ApplyDataLabels(
                        [in, optional, defaultvalue(2)] XlDataLabelsType Type, 
                        [in, optional] VARIANT LegendKey, 
                        [in, optional] VARIANT AutoText, 
                        [in, optional] VARIANT HasLeaderLines, 
                        [in, lcid] long lcid);
        [id(0x000002f8), hidden, helpcontext(0x000102f8)]
        HRESULT Arcs(
                        [in, optional] VARIANT Index, 
                        [in, lcid] long lcid, 
                        [out, retval] IDispatch** RHS);
        [id(0x00000011), propget, helpcontext(0x00010011)]
        HRESULT Area3DGroup(
                        [in, lcid] long lcid, 
                        [out, retval] ChartGroup** RHS);
        [id(0x00000009), helpcontext(0x00010009)]
        HRESULT AreaGroups(
                        [in, optional] VARIANT Index, 
                        [in, lcid] long lcid, 
                        [out, retval] IDispatch** RHS);
        [id(0x00000072), hidden, helpcontext(0x00010072)]
        HRESULT AutoFormat(
                        [in] long Gallery, 
                        [in, optional] VARIANT Format);
        [id(0x0000006b), propget, helpcontext(0x0001006b)]
        HRESULT AutoScaling(
                        [in, lcid] long lcid, 
                        [out, retval] VARIANT_BOOL* RHS);
        [id(0x0000006b), propput, helpcontext(0x0001006b)]
        HRESULT AutoScaling(
                        [in, lcid] long lcid, 
                        [in] VARIANT_BOOL RHS);
        [id(0x00000017), helpcontext(0x00010017)]
        HRESULT Axes(
                        [in, optional] VARIANT Type, 
                        [in, optional, defaultvalue(1)] XlAxisGroup AxisGroup, 
                        [in, lcid] long lcid, 
                        [out, retval] IDispatch** RHS);
        [id(0x000004a4), helpcontext(0x000104a4)]
        HRESULT SetBackgroundPicture([in] BSTR Filename);
        [id(0x00000012), propget, helpcontext(0x00010012)]
        HRESULT Bar3DGroup(
                        [in, lcid] long lcid, 
                        [out, retval] ChartGroup** RHS);
        [id(0x0000000a), helpcontext(0x0001000a)]
        HRESULT BarGroups(
                        [in, optional] VARIANT Index, 
                        [in, lcid] long lcid, 
                        [out, retval] IDispatch** RHS);
        [id(0x0000022d), hidden, helpcontext(0x0001022d)]
        HRESULT Buttons(
                        [in, optional] VARIANT Index, 
                        [in, lcid] long lcid, 
                        [out, retval] IDispatch** RHS);
        [id(0x00000050), propget, helpcontext(0x00010050)]
        HRESULT ChartArea(
                        [in, lcid] long lcid, 
                        [out, retval] ChartArea** RHS);
        [id(0x00000008), helpcontext(0x00010008)]
        HRESULT ChartGroups(
                        [in, optional] VARIANT Index, 
                        [in, lcid] long lcid, 
                        [out, retval] IDispatch** RHS);
        [id(0x00000424), helpcontext(0x00010424)]
        HRESULT ChartObjects(
                        [in, optional] VARIANT Index, 
                        [in, lcid] long lcid, 
                        [out, retval] IDispatch** RHS);
        [id(0x00000051), propget, helpcontext(0x00010051)]
        HRESULT ChartTitle(
                        [in, lcid] long lcid, 
                        [out, retval] ChartTitle** RHS);
        [id(0x000000c4), helpcontext(0x000100c4)]
        HRESULT ChartWizard(
                        [in, optional] VARIANT Source, 
                        [in, optional] VARIANT Gallery, 
                        [in, optional] VARIANT Format, 
                        [in, optional] VARIANT PlotBy, 
                        [in, optional] VARIANT CategoryLabels, 
                        [in, optional] VARIANT SeriesLabels, 
                        [in, optional] VARIANT HasLegend, 
                        [in, optional] VARIANT Title, 
                        [in, optional] VARIANT CategoryTitle, 
                        [in, optional] VARIANT ValueTitle, 
                        [in, optional] VARIANT ExtraTitle, 
                        [in, lcid] long lcid);
        [id(0x00000338), hidden, helpcontext(0x00010338)]
        HRESULT CheckBoxes(
                        [in, optional] VARIANT Index, 
                        [in, lcid] long lcid, 
                        [out, retval] IDispatch** RHS);
        [id(0x000001f9), helpcontext(0x000101f9)]
        HRESULT CheckSpelling(
                        [in, optional] VARIANT CustomDictionary, 
                        [in, optional] VARIANT IgnoreUppercase, 
                        [in, optional] VARIANT AlwaysSuggest, 
                        [in, optional] VARIANT IgnoreInitialAlefHamza, 
                        [in, optional] VARIANT IgnoreFinalYaa, 
                        [in, optional] VARIANT SpellScript, 
                        [in, lcid] long lcid);
        [id(0x00000013), propget, helpcontext(0x00010013)]
        HRESULT Column3DGroup(
                        [in, lcid] long lcid, 
                        [out, retval] ChartGroup** RHS);
        [id(0x0000000b), helpcontext(0x0001000b)]
        HRESULT ColumnGroups(
                        [in, optional] VARIANT Index, 
                        [in, lcid] long lcid, 
                        [out, retval] IDispatch** RHS);
        [id(0x000000d5), helpcontext(0x000100d5)]
        HRESULT CopyPicture(
                        [in, optional, defaultvalue(1)] XlPictureAppearance Appearance, 
                        [in, optional, defaultvalue(-4147)] XlCopyPictureFormat Format, 
                        [in, optional, defaultvalue(2)] XlPictureAppearance Size, 
                        [in, lcid] long lcid);
        [id(0x0000004f), propget, helpcontext(0x0001004f)]
        HRESULT Corners(
                        [in, lcid] long lcid, 
                        [out, retval] Corners** RHS);
        [id(0x000001ca), helpcontext(0x000101ca)]
        HRESULT CreatePublisher(
                        [in, optional] VARIANT Edition, 
                        [in, optional, defaultvalue(1)] XlPictureAppearance Appearance, 
                        [in, optional, defaultvalue(1)] XlPictureAppearance Size, 
                        [in, optional] VARIANT ContainsPICT, 
                        [in, optional] VARIANT ContainsBIFF, 
                        [in, optional] VARIANT ContainsRTF, 
                        [in, optional] VARIANT ContainsVALU, 
                        [in, lcid] long lcid);
        [id(0x00000573), propget, helpcontext(0x00010573)]
        HRESULT DataTable([out, retval] DataTable** RHS);
        [id(0x00000030), propget, helpcontext(0x00010030)]
        HRESULT DepthPercent(
                        [in, lcid] long lcid, 
                        [out, retval] long* RHS);
        [id(0x00000030), propput, helpcontext(0x00010030)]
        HRESULT DepthPercent(
                        [in, lcid] long lcid, 
                        [in] long RHS);
        [id(0x00000460), helpcontext(0x00010460)]
        HRESULT Deselect([in, lcid] long lcid);
        [id(0x0000005d), propget, helpcontext(0x0001005d)]
        HRESULT DisplayBlanksAs(
                        [in, lcid] long lcid, 
                        [out, retval] XlDisplayBlanksAs* RHS);
        [id(0x0000005d), propput, helpcontext(0x0001005d)]
        HRESULT DisplayBlanksAs(
                        [in, lcid] long lcid, 
                        [in] XlDisplayBlanksAs RHS);
        [id(0x0000000e), helpcontext(0x0001000e)]
        HRESULT DoughnutGroups(
                        [in, optional] VARIANT Index, 
                        [in, lcid] long lcid, 
                        [out, retval] IDispatch** RHS);
        [id(0x00000304), hidden, helpcontext(0x00010304)]
        HRESULT Drawings(
                        [in, optional] VARIANT Index, 
                        [in, lcid] long lcid, 
                        [out, retval] IDispatch** RHS);
        [id(0x00000058), hidden, helpcontext(0x00010058)]
        HRESULT DrawingObjects(
                        [in, optional] VARIANT Index, 
                        [in, lcid] long lcid, 
                        [out, retval] IDispatch** RHS);
        [id(0x00000344), hidden, helpcontext(0x00010344)]
        HRESULT DropDowns(
                        [in, optional] VARIANT Index, 
                        [in, lcid] long lcid, 
                        [out, retval] IDispatch** RHS);
        [id(0x00000031), propget, helpcontext(0x00010031)]
        HRESULT Elevation(
                        [in, lcid] long lcid, 
                        [out, retval] long* RHS);
        [id(0x00000031), propput, helpcontext(0x00010031)]
        HRESULT Elevation(
                        [in, lcid] long lcid, 
                        [in] long RHS);
        [id(0x00000001), helpcontext(0x00010001)]
        HRESULT Evaluate(
                        [in] VARIANT Name, 
                        [in, lcid] long lcid, 
                        [out, retval] VARIANT* RHS);
        [id(0xfffffffb), helpcontext(0x0000fffb)]
        HRESULT _Evaluate(
                        [in] VARIANT Name, 
                        [in, lcid] long lcid, 
                        [out, retval] VARIANT* RHS);
        [id(0x00000053), propget, helpcontext(0x00010053)]
        HRESULT Floor(
                        [in, lcid] long lcid, 
                        [out, retval] Floor** RHS);
        [id(0x00000032), propget, helpcontext(0x00010032)]
        HRESULT GapDepth(
                        [in, lcid] long lcid, 
                        [out, retval] long* RHS);
        [id(0x00000032), propput, helpcontext(0x00010032)]
        HRESULT GapDepth(
                        [in, lcid] long lcid, 
                        [in] long RHS);
        [id(0x00000342), hidden, helpcontext(0x00010342)]
        HRESULT GroupBoxes(
                        [in, optional] VARIANT Index, 
                        [in, lcid] long lcid, 
                        [out, retval] IDispatch** RHS);
        [id(0x00000459), hidden, helpcontext(0x00010459)]
        HRESULT GroupObjects(
                        [in, optional] VARIANT Index, 
                        [in, lcid] long lcid, 
                        [out, retval] IDispatch** RHS);
        [id(0x00000034), propget, helpcontext(0x00010034)]
        HRESULT HasAxis(
                        [in, optional] VARIANT Index1, 
                        [in, optional] VARIANT Index2, 
                        [in, lcid] long lcid, 
                        [out, retval] VARIANT* RHS);
        [id(0x00000034), propput, helpcontext(0x00010034)]
        HRESULT HasAxis(
                        [in, optional] VARIANT Index1, 
                        [in, optional] VARIANT Index2, 
                        [in, lcid] long lcid, 
                        [in] VARIANT RHS);
        [id(0x00000574), propget, helpcontext(0x00010574)]
        HRESULT HasDataTable([out, retval] VARIANT_BOOL* RHS);
        [id(0x00000574), propput, helpcontext(0x00010574)]
        HRESULT HasDataTable([in] VARIANT_BOOL RHS);
        [id(0x00000035), propget, helpcontext(0x00010035)]
        HRESULT HasLegend(
                        [in, lcid] long lcid, 
                        [out, retval] VARIANT_BOOL* RHS);
        [id(0x00000035), propput, helpcontext(0x00010035)]
        HRESULT HasLegend(
                        [in, lcid] long lcid, 
                        [in] VARIANT_BOOL RHS);
        [id(0x00000036), propget, helpcontext(0x00010036)]
        HRESULT HasTitle(
                        [in, lcid] long lcid, 
                        [out, retval] VARIANT_BOOL* RHS);
        [id(0x00000036), propput, helpcontext(0x00010036)]
        HRESULT HasTitle(
                        [in, lcid] long lcid, 
                        [in] VARIANT_BOOL RHS);
        [id(0x00000037), propget, helpcontext(0x00010037)]
        HRESULT HeightPercent(
                        [in, lcid] long lcid, 
                        [out, retval] long* RHS);
        [id(0x00000037), propput, helpcontext(0x00010037)]
        HRESULT HeightPercent(
                        [in, lcid] long lcid, 
                        [in] long RHS);
        [id(0x00000571), propget, helpcontext(0x00010571)]
        HRESULT Hyperlinks([out, retval] Hyperlinks** RHS);
        [id(0x00000349), hidden, helpcontext(0x00010349)]
        HRESULT Labels(
                        [in, optional] VARIANT Index, 
                        [in, lcid] long lcid, 
                        [out, retval] IDispatch** RHS);
        [id(0x00000054), propget, helpcontext(0x00010054)]
        HRESULT Legend(
                        [in, lcid] long lcid, 
                        [out, retval] Legend** RHS);
        [id(0x00000014), propget, helpcontext(0x00010014)]
        HRESULT Line3DGroup(
                        [in, lcid] long lcid, 
                        [out, retval] ChartGroup** RHS);
        [id(0x0000000c), helpcontext(0x0001000c)]
        HRESULT LineGroups(
                        [in, optional] VARIANT Index, 
                        [in, lcid] long lcid, 
                        [out, retval] IDispatch** RHS);
        [id(0x000002ff), hidden, helpcontext(0x000102ff)]
        HRESULT Lines(
                        [in, optional] VARIANT Index, 
                        [in, lcid] long lcid, 
                        [out, retval] IDispatch** RHS);
        [id(0x00000340), hidden, helpcontext(0x00010340)]
        HRESULT ListBoxes(
                        [in, optional] VARIANT Index, 
                        [in, lcid] long lcid, 
                        [out, retval] IDispatch** RHS);
        [id(0x00000575), helpcontext(0x00010575)]
        HRESULT Location(
                        [in] XlChartLocation Where, 
                        [in, optional] VARIANT Name, 
                        [out, retval] Chart** RHS);
        [id(0x0000031f), helpcontext(0x0001031f)]
        HRESULT OLEObjects(
                        [in, optional] VARIANT Index, 
                        [in, lcid] long lcid, 
                        [out, retval] IDispatch** RHS);
        [id(0x0000033a), hidden, helpcontext(0x0001033a)]
        HRESULT OptionButtons(
                        [in, optional] VARIANT Index, 
                        [in, lcid] long lcid, 
                        [out, retval] IDispatch** RHS);
        [id(0x00000321), hidden, helpcontext(0x00010321)]
        HRESULT Ovals(
                        [in, optional] VARIANT Index, 
                        [in, lcid] long lcid, 
                        [out, retval] IDispatch** RHS);
        [id(0x000000d3), helpcontext(0x000100d3)]
        HRESULT Paste(
                        [in, optional] VARIANT Type, 
                        [in, lcid] long lcid);
        [id(0x00000039), propget, helpcontext(0x00010039)]
        HRESULT Perspective(
                        [in, lcid] long lcid, 
                        [out, retval] long* RHS);
        [id(0x00000039), propput, helpcontext(0x00010039)]
        HRESULT Perspective(
                        [in, lcid] long lcid, 
                        [in] long RHS);
        [id(0x00000303), hidden, helpcontext(0x00010303)]
        HRESULT Pictures(
                        [in, optional] VARIANT Index, 
                        [in, lcid] long lcid, 
                        [out, retval] IDispatch** RHS);
        [id(0x00000015), propget, helpcontext(0x00010015)]
        HRESULT Pie3DGroup(
                        [in, lcid] long lcid, 
                        [out, retval] ChartGroup** RHS);
        [id(0x0000000d), helpcontext(0x0001000d)]
        HRESULT PieGroups(
                        [in, optional] VARIANT Index, 
                        [in, lcid] long lcid, 
                        [out, retval] IDispatch** RHS);
        [id(0x00000055), propget, helpcontext(0x00010055)]
        HRESULT PlotArea(
                        [in, lcid] long lcid, 
                        [out, retval] PlotArea** RHS);
        [id(0x0000005c), propget, helpcontext(0x0001005c)]
        HRESULT PlotVisibleOnly(
                        [in, lcid] long lcid, 
                        [out, retval] VARIANT_BOOL* RHS);
        [id(0x0000005c), propput, helpcontext(0x0001005c)]
        HRESULT PlotVisibleOnly(
                        [in, lcid] long lcid, 
                        [in] VARIANT_BOOL RHS);
        [id(0x0000000f), helpcontext(0x0001000f)]
        HRESULT RadarGroups(
                        [in, optional] VARIANT Index, 
                        [in, lcid] long lcid, 
                        [out, retval] IDispatch** RHS);
        [id(0x00000306), hidden, helpcontext(0x00010306)]
        HRESULT Rectangles(
                        [in, optional] VARIANT Index, 
                        [in, lcid] long lcid, 
                        [out, retval] IDispatch** RHS);
        [id(0x0000003a), propget, helpcontext(0x0001003a)]
        HRESULT RightAngleAxes(
                        [in, lcid] long lcid, 
                        [out, retval] VARIANT* RHS);
        [id(0x0000003a), propput, helpcontext(0x0001003a)]
        HRESULT RightAngleAxes(
                        [in, lcid] long lcid, 
                        [in] VARIANT RHS);
        [id(0x0000003b), propget, helpcontext(0x0001003b)]
        HRESULT Rotation(
                        [in, lcid] long lcid, 
                        [out, retval] VARIANT* RHS);
        [id(0x0000003b), propput, helpcontext(0x0001003b)]
        HRESULT Rotation(
                        [in, lcid] long lcid, 
                        [in] VARIANT RHS);
        [id(0x0000033e), hidden, helpcontext(0x0001033e)]
        HRESULT ScrollBars(
                        [in, optional] VARIANT Index, 
                        [in, lcid] long lcid, 
                        [out, retval] IDispatch** RHS);
        [id(0x00000044), helpcontext(0x00010044)]
        HRESULT SeriesCollection(
                        [in, optional] VARIANT Index, 
                        [in, lcid] long lcid, 
                        [out, retval] IDispatch** RHS);
        [id(0x0000005e), propget, helpcontext(0x0001005e)]
        HRESULT SizeWithWindow(
                        [in, lcid] long lcid, 
                        [out, retval] VARIANT_BOOL* RHS);
        [id(0x0000005e), propput, helpcontext(0x0001005e)]
        HRESULT SizeWithWindow(
                        [in, lcid] long lcid, 
                        [in] VARIANT_BOOL RHS);
        [id(0x00000577), propget, helpcontext(0x00010577)]
        HRESULT ShowWindow([out, retval] VARIANT_BOOL* RHS);
        [id(0x00000577), propput, helpcontext(0x00010577)]
        HRESULT ShowWindow([in] VARIANT_BOOL RHS);
        [id(0x00000346), hidden, helpcontext(0x00010346)]
        HRESULT Spinners(
                        [in, optional] VARIANT Index, 
                        [in, lcid] long lcid, 
                        [out, retval] IDispatch** RHS);
        [id(0x0000006d), propget, hidden, helpcontext(0x0001006d)]
        HRESULT SubType(
                        [in, lcid] long lcid, 
                        [out, retval] long* RHS);
        [id(0x0000006d), propput, hidden, helpcontext(0x0001006d)]
        HRESULT SubType(
                        [in, lcid] long lcid, 
                        [in] long RHS);
        [id(0x00000016), propget, helpcontext(0x00010016)]
        HRESULT SurfaceGroup(
                        [in, lcid] long lcid, 
                        [out, retval] ChartGroup** RHS);
        [id(0x00000309), hidden, helpcontext(0x00010309)]
        HRESULT TextBoxes(
                        [in, optional] VARIANT Index, 
                        [in, lcid] long lcid, 
                        [out, retval] IDispatch** RHS);
        [id(0x0000006c), propget, hidden, helpcontext(0x0001006c)]
        HRESULT Type(
                        [in, lcid] long lcid, 
                        [out, retval] long* RHS);
        [id(0x0000006c), propput, hidden, helpcontext(0x0001006c)]
        HRESULT Type(
                        [in, lcid] long lcid, 
                        [in] long RHS);
        [id(0x00000578), propget, helpcontext(0x00010578)]
        HRESULT ChartType([out, retval] XlChartType* RHS);
        [id(0x00000578), propput, helpcontext(0x00010578)]
        HRESULT ChartType([in] XlChartType RHS);
        [id(0x00000579), helpcontext(0x00010579)]
        HRESULT ApplyCustomType(
                        [in] XlChartType ChartType, 
                        [in, optional] VARIANT TypeName);
        [id(0x00000056), propget, helpcontext(0x00010056)]
        HRESULT Walls(
                        [in, lcid] long lcid, 
                        [out, retval] Walls** RHS);
        [id(0x000000d2), propget, helpcontext(0x000100d2)]
        HRESULT WallsAndGridlines2D(
                        [in, lcid] long lcid, 
                        [out, retval] VARIANT_BOOL* RHS);
        [id(0x000000d2), propput, helpcontext(0x000100d2)]
        HRESULT WallsAndGridlines2D(
                        [in, lcid] long lcid, 
                        [in] VARIANT_BOOL RHS);
        [id(0x00000010), helpcontext(0x00010010)]
        HRESULT XYGroups(
                        [in, optional] VARIANT Index, 
                        [in, lcid] long lcid, 
                        [out, retval] IDispatch** RHS);
        [id(0x0000057b), propget, helpcontext(0x0001057b)]
        HRESULT BarShape([out, retval] XlBarShape* RHS);
        [id(0x0000057b), propput, helpcontext(0x0001057b)]
        HRESULT BarShape([in] XlBarShape RHS);
        [id(0x000000ca), propget, helpcontext(0x000100ca)]
        HRESULT PlotBy([out, retval] XlRowCol* RHS);
        [id(0x000000ca), propput, helpcontext(0x000100ca)]
        HRESULT PlotBy([in] XlRowCol RHS);
        [id(0x0000057c), hidden, helpcontext(0x0001057c)]
        HRESULT CopyChartBuild();
        [id(0x0000057d), propget, helpcontext(0x0001057d)]
        HRESULT ProtectFormatting([out, retval] VARIANT_BOOL* RHS);
        [id(0x0000057d), propput, helpcontext(0x0001057d)]
        HRESULT ProtectFormatting([in] VARIANT_BOOL RHS);
        [id(0x0000057e), propget, helpcontext(0x0001057e)]
        HRESULT ProtectData([out, retval] VARIANT_BOOL* RHS);
        [id(0x0000057e), propput, helpcontext(0x0001057e)]
        HRESULT ProtectData([in] VARIANT_BOOL RHS);
        [id(0x0000057f), propget, helpcontext(0x0001057f)]
        HRESULT ProtectGoalSeek([out, retval] VARIANT_BOOL* RHS);
        [id(0x0000057f), propput, helpcontext(0x0001057f)]
        HRESULT ProtectGoalSeek([in] VARIANT_BOOL RHS);
        [id(0x00000580), propget, helpcontext(0x00010580)]
        HRESULT ProtectSelection([out, retval] VARIANT_BOOL* RHS);
        [id(0x00000580), propput, helpcontext(0x00010580)]
        HRESULT ProtectSelection([in] VARIANT_BOOL RHS);
        [id(0x00000581), helpcontext(0x00010581)]
        HRESULT GetChartElement(
                        [in] long X, 
                        [in] long Y, 
                        [in] long* ElementID, 
                        [in] long* Arg1, 
                        [in] long* Arg2);
        [id(0x00000585), helpcontext(0x00010585)]
        HRESULT SetSourceData(
                        [in] Range* Source, 
                        [in, optional] VARIANT PlotBy);
        [id(0x00000586), helpcontext(0x00010586)]
        HRESULT Export(
                        [in] BSTR Filename, 
                        [in, optional] VARIANT FilterName, 
                        [in, optional] VARIANT Interactive, 
                        [out, retval] VARIANT_BOOL* RHS);
        [id(0x00000589), helpcontext(0x00010589)]
        HRESULT Refresh();
    };

    [
      odl,
      uuid(000208D7-0000-0000-C000-000000000046),
      helpcontext(0x0002000c),
      dual,
      nonextensible,
      oleautomation
    ]
    interface Sheets : IDispatch {
        [id(0x00000094), propget, helpcontext(0x00010094)]
        HRESULT Application([out, retval] Application** RHS);
        [id(0x00000095), propget, helpcontext(0x00010095)]
        HRESULT Creator([out, retval] XlCreator* RHS);
        [id(0x00000096), propget, helpcontext(0x00010096)]
        HRESULT Parent([out, retval] IDispatch** RHS);
        [id(0x000000b5), helpcontext(0x000100b5)]
        HRESULT Add(
                        [in, optional] VARIANT Before, 
                        [in, optional] VARIANT After, 
                        [in, optional] VARIANT Count, 
                        [in, optional] VARIANT Type, 
                        [in, lcid] long lcid, 
                        [out, retval] IDispatch** RHS);
        [id(0x00000227), helpcontext(0x00010227)]
        HRESULT Copy(
                        [in, optional] VARIANT Before, 
                        [in, optional] VARIANT After, 
                        [in, lcid] long lcid);
        [id(0x00000076), propget, helpcontext(0x00010076)]
        HRESULT Count([out, retval] long* RHS);
        [id(0x00000075), helpcontext(0x00010075)]
        HRESULT Delete([in, lcid] long lcid);
        [id(0x000001d5), helpcontext(0x000101d5)]
        HRESULT FillAcrossSheets(
                        [in] Range* Range, 
                        [in, optional, defaultvalue(-4104)] XlFillWith Type, 
                        [in, lcid] long lcid);
        [id(0x000000aa), propget, helpcontext(0x000100aa)]
        HRESULT Item(
                        [in] VARIANT Index, 
                        [out, retval] IDispatch** RHS);
        [id(0x0000027d), helpcontext(0x0001027d)]
        HRESULT Move(
                        [in, optional] VARIANT Before, 
                        [in, optional] VARIANT After, 
                        [in, lcid] long lcid);
        [id(0xfffffffc), propget, helpcontext(0x0000fffc)]
        HRESULT _NewEnum([out, retval] IUnknown** RHS);
        [id(0x00000389), helpcontext(0x00010389)]
        HRESULT PrintOut(
                        [in, optional] VARIANT From, 
                        [in, optional] VARIANT To, 
                        [in, optional] VARIANT Copies, 
                        [in, optional] VARIANT Preview, 
                        [in, optional] VARIANT ActivePrinter, 
                        [in, optional] VARIANT PrintToFile, 
                        [in, optional] VARIANT Collate, 
                        [in, lcid] long lcid);
        [id(0x00000119), helpcontext(0x00010119)]
        HRESULT PrintPreview(
                        [in, optional] VARIANT EnableChanges, 
                        [in, lcid] long lcid);
        [id(0x000000eb), helpcontext(0x000100eb)]
        HRESULT Select(
                        [in, optional] VARIANT Replace, 
                        [in, lcid] long lcid);
        [id(0x0000058a), propget, helpcontext(0x0001058a)]
        HRESULT HPageBreaks([out, retval] HPageBreaks** RHS);
        [id(0x0000058b), propget, helpcontext(0x0001058b)]
        HRESULT VPageBreaks([out, retval] VPageBreaks** RHS);
        [id(0x0000022e), propget, helpcontext(0x0001022e)]
        HRESULT Visible(
                        [in, lcid] long lcid, 
                        [out, retval] VARIANT* RHS);
        [id(0x0000022e), propput, helpcontext(0x0001022e)]
        HRESULT Visible(
                        [in, lcid] long lcid, 
                        [in] VARIANT RHS);
        [id(00000000), propget, helpcontext(0x00010000)]
        HRESULT _Default(
                        [in] VARIANT Index, 
                        [out, retval] IDispatch** RHS);
    };

