import "Excel10.Idl";


    [
      odl,
      uuid(000208A1-0001-0000-C000-000000000046),
      helpcontext(0x00020061),
      hidden
    ]
    interface IArcs : IDispatch {
        [propget, helpcontext(0x00010094)]
        HRESULT _stdcall Application([out, retval] Application** RHS);
        [propget, helpcontext(0x00010095)]
        HRESULT _stdcall Creator([out, retval] XlCreator* RHS);
        [propget, helpcontext(0x00010096)]
        HRESULT _stdcall Parent([out, retval] IDispatch** RHS);
        [restricted, hidden]
        void _stdcall _Dummy3();
        [helpcontext(0x0001025a)]
        HRESULT _stdcall BringToFront();
        [helpcontext(0x00010227)]
        HRESULT _stdcall Copy();
        [helpcontext(0x000100d5)]
        HRESULT _stdcall CopyPicture(
                        [in, optional, defaultvalue(2)] XlPictureAppearance Appearance, 
                        [in, optional, defaultvalue(-4147)] XlCopyPictureFormat Format);
        [helpcontext(0x00010235)]
        HRESULT _stdcall Cut();
        [helpcontext(0x00010075)]
        HRESULT _stdcall Delete();
        [helpcontext(0x0001040f)]
        HRESULT _stdcall Duplicate([out, retval] IDispatch** RHS);
        [propget, helpcontext(0x00010258)]
        HRESULT _stdcall Enabled([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010258)]
        HRESULT _stdcall Enabled([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x0001007b)]
        HRESULT _stdcall Height([out, retval] double* RHS);
        [propput, helpcontext(0x0001007b)]
        HRESULT _stdcall Height([in] double RHS);
        [restricted, hidden]
        void _stdcall _Dummy12();
        [propget, helpcontext(0x0001007f)]
        HRESULT _stdcall Left([out, retval] double* RHS);
        [propput, helpcontext(0x0001007f)]
        HRESULT _stdcall Left([in] double RHS);
        [propget, helpcontext(0x0001010d)]
        HRESULT _stdcall Locked([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x0001010d)]
        HRESULT _stdcall Locked([in] VARIANT_BOOL RHS);
        [restricted, hidden]
        void _stdcall _Dummy15();
        [propget, hidden, helpcontext(0x00010254)]
        HRESULT _stdcall OnAction([out, retval] BSTR* RHS);
        [propput, hidden, helpcontext(0x00010254)]
        HRESULT _stdcall OnAction([in] BSTR RHS);
        [propget, helpcontext(0x00010269)]
        HRESULT _stdcall Placement([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010269)]
        HRESULT _stdcall Placement([in] VARIANT RHS);
        [propget, helpcontext(0x0001026a)]
        HRESULT _stdcall PrintObject([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x0001026a)]
        HRESULT _stdcall PrintObject([in] VARIANT_BOOL RHS);
        [helpcontext(0x000100eb)]
        HRESULT _stdcall Select([in, optional] VARIANT Replace);
        [helpcontext(0x0001025d)]
        HRESULT _stdcall SendToBack();
        [propget, helpcontext(0x0001007e)]
        HRESULT _stdcall Top([out, retval] double* RHS);
        [propput, helpcontext(0x0001007e)]
        HRESULT _stdcall Top([in] double RHS);
        [restricted, hidden]
        void _stdcall _Dummy22();
        [propget, helpcontext(0x0001022e)]
        HRESULT _stdcall Visible([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x0001022e)]
        HRESULT _stdcall Visible([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x0001007a)]
        HRESULT _stdcall Width([out, retval] double* RHS);
        [propput, helpcontext(0x0001007a)]
        HRESULT _stdcall Width([in] double RHS);
        [propget, helpcontext(0x0001026e)]
        HRESULT _stdcall ZOrder([out, retval] long* RHS);
        [propget, helpcontext(0x000105f8)]
        HRESULT _stdcall ShapeRange([out, retval] ShapeRange** RHS);
        [propget, helpcontext(0x00010427)]
        HRESULT _stdcall AddIndent([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010427)]
        HRESULT _stdcall AddIndent([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x000105f5)]
        HRESULT _stdcall AutoScaleFont([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x000105f5)]
        HRESULT _stdcall AutoScaleFont([in] VARIANT RHS);
        [propget, helpcontext(0x00010266)]
        HRESULT _stdcall AutoSize([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010266)]
        HRESULT _stdcall AutoSize([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x0001008b)]
        HRESULT _stdcall Caption([out, retval] BSTR* RHS);
        [propput, helpcontext(0x0001008b)]
        HRESULT _stdcall Caption([in] BSTR RHS);
        [propget, helpcontext(0x0001025b)]
        HRESULT _stdcall Characters(
                        [in, optional] VARIANT Start, 
                        [in, optional] VARIANT Length, 
                        [out, retval] Characters** RHS);
        [helpcontext(0x000101f9)]
        HRESULT _stdcall CheckSpelling(
                        [in, optional] VARIANT CustomDictionary, 
                        [in, optional] VARIANT IgnoreUppercase, 
                        [in, optional] VARIANT AlwaysSuggest, 
                        [in, optional] VARIANT IgnoreInitialAlefHamza, 
                        [in, optional] VARIANT IgnoreFinalYaa, 
                        [in, optional] VARIANT SpellScript);
        [propget, helpcontext(0x00010092)]
        HRESULT _stdcall Font([out, retval] Font** RHS);
        [propget, helpcontext(0x00010105)]
        HRESULT _stdcall Formula([out, retval] BSTR* RHS);
        [propput, helpcontext(0x00010105)]
        HRESULT _stdcall Formula([in] BSTR RHS);
        [propget, helpcontext(0x00010088)]
        HRESULT _stdcall HorizontalAlignment([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010088)]
        HRESULT _stdcall HorizontalAlignment([in] VARIANT RHS);
        [propget, helpcontext(0x00010268)]
        HRESULT _stdcall LockedText([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010268)]
        HRESULT _stdcall LockedText([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x00010086)]
        HRESULT _stdcall Orientation([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010086)]
        HRESULT _stdcall Orientation([in] VARIANT RHS);
        [propget, helpcontext(0x0001008a)]
        HRESULT _stdcall Text([out, retval] BSTR* RHS);
        [propput, helpcontext(0x0001008a)]
        HRESULT _stdcall Text([in] BSTR RHS);
        [propget, helpcontext(0x00010089)]
        HRESULT _stdcall VerticalAlignment([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010089)]
        HRESULT _stdcall VerticalAlignment([in] VARIANT RHS);
        [propget, helpcontext(0x000103cf)]
        HRESULT _stdcall ReadingOrder([out, retval] long* RHS);
        [propput, helpcontext(0x000103cf)]
        HRESULT _stdcall ReadingOrder([in] long RHS);
        [propget, helpcontext(0x00010080)]
        HRESULT _stdcall Border([out, retval] Border** RHS);
        [propget, helpcontext(0x00010081)]
        HRESULT _stdcall Interior([out, retval] Interior** RHS);
        [restricted, hidden]
        void _stdcall _Dummy43();
        [helpcontext(0x000100b5)]
        HRESULT _stdcall Add(
                        [in] double X1, 
                        [in] double Y1, 
                        [in] double X2, 
                        [in] double Y2, 
                        [out, retval] Arc** RHS);
        [propget, helpcontext(0x00010076)]
        HRESULT _stdcall Count([out, retval] long* RHS);
        [helpcontext(0x0001002e)]
        HRESULT _stdcall Group([out, retval] GroupObject** RHS);
        [helpcontext(0x000100aa)]
        HRESULT _stdcall Item(
                        [in] VARIANT Index, 
                        [out, retval] IDispatch** RHS);
        [helpcontext(0x0000fffc)]
        HRESULT _stdcall _NewEnum([out, retval] IUnknown** RHS);
    };

    [
      odl,
      uuid(00024410-0001-0000-C000-000000000046),
      helpcontext(0x000200a6),
      hidden
    ]
    interface IOLEObjectEvents : IDispatch {
        [helpcontext(0x00010605)]
        HRESULT _stdcall GotFocus();
        [helpcontext(0x00010606)]
        HRESULT _stdcall LostFocus();
    };

    [
      odl,
      uuid(000208A2-0001-0000-C000-000000000046),
      helpcontext(0x00020062),
      hidden
    ]
    interface _IOLEObject : IDispatch {
        [propget, helpcontext(0x00010094)]
        HRESULT _stdcall Application([out, retval] Application** RHS);
        [propget, helpcontext(0x00010095)]
        HRESULT _stdcall Creator([out, retval] XlCreator* RHS);
        [propget, helpcontext(0x00010096)]
        HRESULT _stdcall Parent([out, retval] IDispatch** RHS);
        [propget, helpcontext(0x00010267)]
        HRESULT _stdcall BottomRightCell([out, retval] Range** RHS);
        [helpcontext(0x0001025a)]
        HRESULT _stdcall BringToFront();
        [helpcontext(0x00010227)]
        HRESULT _stdcall Copy();
        [helpcontext(0x000100d5)]
        HRESULT _stdcall CopyPicture(
                        [in, optional, defaultvalue(2)] XlPictureAppearance Appearance, 
                        [in, optional, defaultvalue(-4147)] XlCopyPictureFormat Format);
        [helpcontext(0x00010235)]
        HRESULT _stdcall Cut();
        [helpcontext(0x00010075)]
        HRESULT _stdcall Delete();
        [helpcontext(0x0001040f)]
        HRESULT _stdcall Duplicate([out, retval] IDispatch** RHS);
        [propget, helpcontext(0x00010258)]
        HRESULT _stdcall Enabled([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010258)]
        HRESULT _stdcall Enabled([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x0001007b)]
        HRESULT _stdcall Height([out, retval] double* RHS);
        [propput, helpcontext(0x0001007b)]
        HRESULT _stdcall Height([in] double RHS);
        [propget, helpcontext(0x000101e6)]
        HRESULT _stdcall Index([out, retval] long* RHS);
        [propget, helpcontext(0x0001007f)]
        HRESULT _stdcall Left([out, retval] double* RHS);
        [propput, helpcontext(0x0001007f)]
        HRESULT _stdcall Left([in] double RHS);
        [propget, helpcontext(0x0001010d)]
        HRESULT _stdcall Locked([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x0001010d)]
        HRESULT _stdcall Locked([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x0001006e)]
        HRESULT _stdcall Name([out, retval] BSTR* RHS);
        [propput, helpcontext(0x0001006e)]
        HRESULT _stdcall Name([in] BSTR RHS);
        [propget, hidden, helpcontext(0x00010254)]
        HRESULT _stdcall OnAction([out, retval] BSTR* RHS);
        [propput, hidden, helpcontext(0x00010254)]
        HRESULT _stdcall OnAction([in] BSTR RHS);
        [propget, helpcontext(0x00010269)]
        HRESULT _stdcall Placement([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010269)]
        HRESULT _stdcall Placement([in] VARIANT RHS);
        [propget, helpcontext(0x0001026a)]
        HRESULT _stdcall PrintObject([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x0001026a)]
        HRESULT _stdcall PrintObject([in] VARIANT_BOOL RHS);
        [helpcontext(0x000100eb)]
        HRESULT _stdcall Select([in, optional] VARIANT Replace);
        [helpcontext(0x0001025d)]
        HRESULT _stdcall SendToBack();
        [propget, helpcontext(0x0001007e)]
        HRESULT _stdcall Top([out, retval] double* RHS);
        [propput, helpcontext(0x0001007e)]
        HRESULT _stdcall Top([in] double RHS);
        [propget, helpcontext(0x0001026c)]
        HRESULT _stdcall TopLeftCell([out, retval] Range** RHS);
        [propget, helpcontext(0x0001022e)]
        HRESULT _stdcall Visible([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x0001022e)]
        HRESULT _stdcall Visible([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x0001007a)]
        HRESULT _stdcall Width([out, retval] double* RHS);
        [propput, helpcontext(0x0001007a)]
        HRESULT _stdcall Width([in] double RHS);
        [propget, helpcontext(0x0001026e)]
        HRESULT _stdcall ZOrder([out, retval] long* RHS);
        [propget, helpcontext(0x000105f8)]
        HRESULT _stdcall ShapeRange([out, retval] ShapeRange** RHS);
        [propget, helpcontext(0x00010080)]
        HRESULT _stdcall Border([out, retval] Border** RHS);
        [propget, helpcontext(0x00010081)]
        HRESULT _stdcall Interior([out, retval] Interior** RHS);
        [propget, helpcontext(0x00010067)]
        HRESULT _stdcall Shadow([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010067)]
        HRESULT _stdcall Shadow([in] VARIANT_BOOL RHS);
        [helpcontext(0x00010130)]
        HRESULT _stdcall Activate();
        [propget, helpcontext(0x000104a2)]
        HRESULT _stdcall AutoLoad([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x000104a2)]
        HRESULT _stdcall AutoLoad([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x00010418)]
        HRESULT _stdcall AutoUpdate([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010418)]
        HRESULT _stdcall AutoUpdate([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x00010419)]
        HRESULT _stdcall Object([out, retval] IDispatch** RHS);
        [propget, helpcontext(0x0001041e)]
        HRESULT _stdcall OLEType([out, retval] VARIANT* RHS);
        [propget, helpcontext(0x000102d1)]
        HRESULT _stdcall SourceName([out, retval] BSTR* RHS);
        [propput, helpcontext(0x000102d1)]
        HRESULT _stdcall SourceName([in] BSTR RHS);
        [helpcontext(0x000102a8)]
        HRESULT _stdcall Update();
        [helpcontext(0x0001025e)]
        HRESULT _stdcall Verb([in, optional, defaultvalue(1)] XlOLEVerb Verb);
        [propget, helpcontext(0x00010422)]
        HRESULT _stdcall LinkedCell([out, retval] BSTR* RHS);
        [propput, helpcontext(0x00010422)]
        HRESULT _stdcall LinkedCell([in] BSTR RHS);
        [propget, helpcontext(0x0001034f)]
        HRESULT _stdcall ListFillRange([out, retval] BSTR* RHS);
        [propput, helpcontext(0x0001034f)]
        HRESULT _stdcall ListFillRange([in] BSTR RHS);
        [propget, helpcontext(0x000105f3)]
        HRESULT _stdcall ProgId([out, retval] BSTR* RHS);
    };

    [
      odl,
      uuid(000208A3-0001-0000-C000-000000000046),
      helpcontext(0x00020063),
      hidden
    ]
    interface IOLEObjects : IDispatch {
        [propget, helpcontext(0x00010094)]
        HRESULT _stdcall Application([out, retval] Application** RHS);
        [propget, helpcontext(0x00010095)]
        HRESULT _stdcall Creator([out, retval] XlCreator* RHS);
        [propget, helpcontext(0x00010096)]
        HRESULT _stdcall Parent([out, retval] IDispatch** RHS);
        [restricted, hidden]
        void _stdcall _Dummy3();
        [helpcontext(0x0001025a)]
        HRESULT _stdcall BringToFront();
        [helpcontext(0x00010227)]
        HRESULT _stdcall Copy();
        [helpcontext(0x000100d5)]
        HRESULT _stdcall CopyPicture(
                        [in, optional, defaultvalue(2)] XlPictureAppearance Appearance, 
                        [in, optional, defaultvalue(-4147)] XlCopyPictureFormat Format);
        [helpcontext(0x00010235)]
        HRESULT _stdcall Cut();
        [helpcontext(0x00010075)]
        HRESULT _stdcall Delete();
        [helpcontext(0x0001040f)]
        HRESULT _stdcall Duplicate([out, retval] IDispatch** RHS);
        [propget, helpcontext(0x00010258)]
        HRESULT _stdcall Enabled([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010258)]
        HRESULT _stdcall Enabled([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x0001007b)]
        HRESULT _stdcall Height([out, retval] double* RHS);
        [propput, helpcontext(0x0001007b)]
        HRESULT _stdcall Height([in] double RHS);
        [restricted, hidden]
        void _stdcall _Dummy12();
        [propget, helpcontext(0x0001007f)]
        HRESULT _stdcall Left([out, retval] double* RHS);
        [propput, helpcontext(0x0001007f)]
        HRESULT _stdcall Left([in] double RHS);
        [propget, helpcontext(0x0001010d)]
        HRESULT _stdcall Locked([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x0001010d)]
        HRESULT _stdcall Locked([in] VARIANT_BOOL RHS);
        [restricted, hidden]
        void _stdcall _Dummy15();
        [propget, hidden, helpcontext(0x00010254)]
        HRESULT _stdcall OnAction([out, retval] BSTR* RHS);
        [propput, hidden, helpcontext(0x00010254)]
        HRESULT _stdcall OnAction([in] BSTR RHS);
        [propget, helpcontext(0x00010269)]
        HRESULT _stdcall Placement([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010269)]
        HRESULT _stdcall Placement([in] VARIANT RHS);
        [propget, helpcontext(0x0001026a)]
        HRESULT _stdcall PrintObject([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x0001026a)]
        HRESULT _stdcall PrintObject([in] VARIANT_BOOL RHS);
        [helpcontext(0x000100eb)]
        HRESULT _stdcall Select([in, optional] VARIANT Replace);
        [helpcontext(0x0001025d)]
        HRESULT _stdcall SendToBack();
        [propget, helpcontext(0x0001007e)]
        HRESULT _stdcall Top([out, retval] double* RHS);
        [propput, helpcontext(0x0001007e)]
        HRESULT _stdcall Top([in] double RHS);
        [restricted, hidden]
        void _stdcall _Dummy22();
        [propget, helpcontext(0x0001022e)]
        HRESULT _stdcall Visible([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x0001022e)]
        HRESULT _stdcall Visible([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x0001007a)]
        HRESULT _stdcall Width([out, retval] double* RHS);
        [propput, helpcontext(0x0001007a)]
        HRESULT _stdcall Width([in] double RHS);
        [propget, helpcontext(0x0001026e)]
        HRESULT _stdcall ZOrder([out, retval] long* RHS);
        [propget, helpcontext(0x000105f8)]
        HRESULT _stdcall ShapeRange([out, retval] ShapeRange** RHS);
        [propget, helpcontext(0x00010080)]
        HRESULT _stdcall Border([out, retval] Border** RHS);
        [propget, helpcontext(0x00010081)]
        HRESULT _stdcall Interior([out, retval] Interior** RHS);
        [propget, helpcontext(0x00010067)]
        HRESULT _stdcall Shadow([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010067)]
        HRESULT _stdcall Shadow([in] VARIANT_BOOL RHS);
        [restricted, hidden]
        void _stdcall _Dummy30();
        [propget, helpcontext(0x000104a2)]
        HRESULT _stdcall AutoLoad([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x000104a2)]
        HRESULT _stdcall AutoLoad([in] VARIANT_BOOL RHS);
        [restricted, hidden]
        void _stdcall _Dummy32();
        [restricted, hidden]
        void _stdcall _Dummy33();
        [restricted, hidden]
        void _stdcall _Dummy34();
        [propget, helpcontext(0x000102d1)]
        HRESULT _stdcall SourceName([out, retval] BSTR* RHS);
        [propput, helpcontext(0x000102d1)]
        HRESULT _stdcall SourceName([in] BSTR RHS);
        [restricted, hidden]
        void _stdcall _Dummy36();
        [restricted, hidden]
        void _stdcall _Dummy37();
        [restricted, hidden]
        void _stdcall _Dummy38();
        [restricted, hidden]
        void _stdcall _Dummy39();
        [restricted, hidden]
        void _stdcall _Dummy40();
        [helpcontext(0x000100b5)]
        HRESULT _stdcall Add(
                        [in, optional] VARIANT ClassType, 
                        [in, optional] VARIANT Filename, 
                        [in, optional] VARIANT Link, 
                        [in, optional] VARIANT DisplayAsIcon, 
                        [in, optional] VARIANT IconFileName, 
                        [in, optional] VARIANT IconIndex, 
                        [in, optional] VARIANT IconLabel, 
                        [in, optional] VARIANT Left, 
                        [in, optional] VARIANT Top, 
                        [in, optional] VARIANT Width, 
                        [in, optional] VARIANT Height, 
                        [out, retval] OLEObject** RHS);
        [propget, helpcontext(0x00010076)]
        HRESULT _stdcall Count([out, retval] long* RHS);
        [hidden, helpcontext(0x0001002e)]
        HRESULT _stdcall Group([out, retval] GroupObject** RHS);
        [helpcontext(0x000100aa)]
        HRESULT _stdcall Item(
                        [in] VARIANT Index, 
                        [out, retval] IDispatch** RHS);
        [helpcontext(0x0000fffc)]
        HRESULT _stdcall _NewEnum([out, retval] IUnknown** RHS);
    };

    [
      odl,
      uuid(000208A4-0001-0000-C000-000000000046),
      helpcontext(0x00020064),
      hidden
    ]
    interface ITextBox : IDispatch {
        [propget, helpcontext(0x00010094)]
        HRESULT _stdcall Application([out, retval] Application** RHS);
        [propget, helpcontext(0x00010095)]
        HRESULT _stdcall Creator([out, retval] XlCreator* RHS);
        [propget, helpcontext(0x00010096)]
        HRESULT _stdcall Parent([out, retval] IDispatch** RHS);
        [propget, helpcontext(0x00010267)]
        HRESULT _stdcall BottomRightCell([out, retval] Range** RHS);
        [helpcontext(0x0001025a)]
        HRESULT _stdcall BringToFront();
        [helpcontext(0x00010227)]
        HRESULT _stdcall Copy();
        [helpcontext(0x000100d5)]
        HRESULT _stdcall CopyPicture(
                        [in, optional, defaultvalue(2)] XlPictureAppearance Appearance, 
                        [in, optional, defaultvalue(-4147)] XlCopyPictureFormat Format);
        [helpcontext(0x00010235)]
        HRESULT _stdcall Cut();
        [helpcontext(0x00010075)]
        HRESULT _stdcall Delete();
        [helpcontext(0x0001040f)]
        HRESULT _stdcall Duplicate([out, retval] IDispatch** RHS);
        [propget, helpcontext(0x00010258)]
        HRESULT _stdcall Enabled([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010258)]
        HRESULT _stdcall Enabled([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x0001007b)]
        HRESULT _stdcall Height([out, retval] double* RHS);
        [propput, helpcontext(0x0001007b)]
        HRESULT _stdcall Height([in] double RHS);
        [propget, helpcontext(0x000101e6)]
        HRESULT _stdcall Index([out, retval] long* RHS);
        [propget, helpcontext(0x0001007f)]
        HRESULT _stdcall Left([out, retval] double* RHS);
        [propput, helpcontext(0x0001007f)]
        HRESULT _stdcall Left([in] double RHS);
        [propget, helpcontext(0x0001010d)]
        HRESULT _stdcall Locked([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x0001010d)]
        HRESULT _stdcall Locked([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x0001006e)]
        HRESULT _stdcall Name([out, retval] BSTR* RHS);
        [propput, helpcontext(0x0001006e)]
        HRESULT _stdcall Name([in] BSTR RHS);
        [propget, hidden, helpcontext(0x00010254)]
        HRESULT _stdcall OnAction([out, retval] BSTR* RHS);
        [propput, hidden, helpcontext(0x00010254)]
        HRESULT _stdcall OnAction([in] BSTR RHS);
        [propget, helpcontext(0x00010269)]
        HRESULT _stdcall Placement([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010269)]
        HRESULT _stdcall Placement([in] VARIANT RHS);
        [propget, helpcontext(0x0001026a)]
        HRESULT _stdcall PrintObject([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x0001026a)]
        HRESULT _stdcall PrintObject([in] VARIANT_BOOL RHS);
        [helpcontext(0x000100eb)]
        HRESULT _stdcall Select([in, optional] VARIANT Replace);
        [helpcontext(0x0001025d)]
        HRESULT _stdcall SendToBack();
        [propget, helpcontext(0x0001007e)]
        HRESULT _stdcall Top([out, retval] double* RHS);
        [propput, helpcontext(0x0001007e)]
        HRESULT _stdcall Top([in] double RHS);
        [propget, helpcontext(0x0001026c)]
        HRESULT _stdcall TopLeftCell([out, retval] Range** RHS);
        [propget, helpcontext(0x0001022e)]
        HRESULT _stdcall Visible([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x0001022e)]
        HRESULT _stdcall Visible([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x0001007a)]
        HRESULT _stdcall Width([out, retval] double* RHS);
        [propput, helpcontext(0x0001007a)]
        HRESULT _stdcall Width([in] double RHS);
        [propget, helpcontext(0x0001026e)]
        HRESULT _stdcall ZOrder([out, retval] long* RHS);
        [propget, helpcontext(0x000105f8)]
        HRESULT _stdcall ShapeRange([out, retval] ShapeRange** RHS);
        [propget, helpcontext(0x00010427)]
        HRESULT _stdcall AddIndent([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010427)]
        HRESULT _stdcall AddIndent([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x000105f5)]
        HRESULT _stdcall AutoScaleFont([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x000105f5)]
        HRESULT _stdcall AutoScaleFont([in] VARIANT RHS);
        [propget, helpcontext(0x00010266)]
        HRESULT _stdcall AutoSize([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010266)]
        HRESULT _stdcall AutoSize([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x0001008b)]
        HRESULT _stdcall Caption([out, retval] BSTR* RHS);
        [propput, helpcontext(0x0001008b)]
        HRESULT _stdcall Caption([in] BSTR RHS);
        [propget, helpcontext(0x0001025b)]
        HRESULT _stdcall Characters(
                        [in, optional] VARIANT Start, 
                        [in, optional] VARIANT Length, 
                        [out, retval] Characters** RHS);
        [helpcontext(0x000101f9)]
        HRESULT _stdcall CheckSpelling(
                        [in, optional] VARIANT CustomDictionary, 
                        [in, optional] VARIANT IgnoreUppercase, 
                        [in, optional] VARIANT AlwaysSuggest, 
                        [in, optional] VARIANT IgnoreInitialAlefHamza, 
                        [in, optional] VARIANT IgnoreFinalYaa, 
                        [in, optional] VARIANT SpellScript);
        [propget, helpcontext(0x00010092)]
        HRESULT _stdcall Font([out, retval] Font** RHS);
        [propget, helpcontext(0x00010105)]
        HRESULT _stdcall Formula([out, retval] BSTR* RHS);
        [propput, helpcontext(0x00010105)]
        HRESULT _stdcall Formula([in] BSTR RHS);
        [propget, helpcontext(0x00010088)]
        HRESULT _stdcall HorizontalAlignment([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010088)]
        HRESULT _stdcall HorizontalAlignment([in] VARIANT RHS);
        [propget, helpcontext(0x00010268)]
        HRESULT _stdcall LockedText([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010268)]
        HRESULT _stdcall LockedText([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x00010086)]
        HRESULT _stdcall Orientation([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010086)]
        HRESULT _stdcall Orientation([in] VARIANT RHS);
        [propget, helpcontext(0x0001008a)]
        HRESULT _stdcall Text([out, retval] BSTR* RHS);
        [propput, helpcontext(0x0001008a)]
        HRESULT _stdcall Text([in] BSTR RHS);
        [propget, helpcontext(0x00010089)]
        HRESULT _stdcall VerticalAlignment([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010089)]
        HRESULT _stdcall VerticalAlignment([in] VARIANT RHS);
        [propget, helpcontext(0x000103cf)]
        HRESULT _stdcall ReadingOrder([out, retval] long* RHS);
        [propput, helpcontext(0x000103cf)]
        HRESULT _stdcall ReadingOrder([in] long RHS);
        [propget, helpcontext(0x00010080)]
        HRESULT _stdcall Border([out, retval] Border** RHS);
        [propget, helpcontext(0x00010081)]
        HRESULT _stdcall Interior([out, retval] Interior** RHS);
        [propget, helpcontext(0x0001026b)]
        HRESULT _stdcall RoundedCorners([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x0001026b)]
        HRESULT _stdcall RoundedCorners([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x00010067)]
        HRESULT _stdcall Shadow([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010067)]
        HRESULT _stdcall Shadow([in] VARIANT_BOOL RHS);
    };

    [
      odl,
      uuid(000208A5-0001-0000-C000-000000000046),
      helpcontext(0x00020065),
      hidden
    ]
    interface ITextBoxes : IDispatch {
        [propget, helpcontext(0x00010094)]
        HRESULT _stdcall Application([out, retval] Application** RHS);
        [propget, helpcontext(0x00010095)]
        HRESULT _stdcall Creator([out, retval] XlCreator* RHS);
        [propget, helpcontext(0x00010096)]
        HRESULT _stdcall Parent([out, retval] IDispatch** RHS);
        [restricted, hidden]
        void _stdcall _Dummy3();
        [helpcontext(0x0001025a)]
        HRESULT _stdcall BringToFront();
        [helpcontext(0x00010227)]
        HRESULT _stdcall Copy();
        [helpcontext(0x000100d5)]
        HRESULT _stdcall CopyPicture(
                        [in, optional, defaultvalue(2)] XlPictureAppearance Appearance, 
                        [in, optional, defaultvalue(-4147)] XlCopyPictureFormat Format);
        [helpcontext(0x00010235)]
        HRESULT _stdcall Cut();
        [helpcontext(0x00010075)]
        HRESULT _stdcall Delete();
        [helpcontext(0x0001040f)]
        HRESULT _stdcall Duplicate([out, retval] IDispatch** RHS);
        [propget, helpcontext(0x00010258)]
        HRESULT _stdcall Enabled([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010258)]
        HRESULT _stdcall Enabled([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x0001007b)]
        HRESULT _stdcall Height([out, retval] double* RHS);
        [propput, helpcontext(0x0001007b)]
        HRESULT _stdcall Height([in] double RHS);
        [restricted, hidden]
        void _stdcall _Dummy12();
        [propget, helpcontext(0x0001007f)]
        HRESULT _stdcall Left([out, retval] double* RHS);
        [propput, helpcontext(0x0001007f)]
        HRESULT _stdcall Left([in] double RHS);
        [propget, helpcontext(0x0001010d)]
        HRESULT _stdcall Locked([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x0001010d)]
        HRESULT _stdcall Locked([in] VARIANT_BOOL RHS);
        [restricted, hidden]
        void _stdcall _Dummy15();
        [propget, hidden, helpcontext(0x00010254)]
        HRESULT _stdcall OnAction([out, retval] BSTR* RHS);
        [propput, hidden, helpcontext(0x00010254)]
        HRESULT _stdcall OnAction([in] BSTR RHS);
        [propget, helpcontext(0x00010269)]
        HRESULT _stdcall Placement([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010269)]
        HRESULT _stdcall Placement([in] VARIANT RHS);
        [propget, helpcontext(0x0001026a)]
        HRESULT _stdcall PrintObject([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x0001026a)]
        HRESULT _stdcall PrintObject([in] VARIANT_BOOL RHS);
        [helpcontext(0x000100eb)]
        HRESULT _stdcall Select([in, optional] VARIANT Replace);
        [helpcontext(0x0001025d)]
        HRESULT _stdcall SendToBack();
        [propget, helpcontext(0x0001007e)]
        HRESULT _stdcall Top([out, retval] double* RHS);
        [propput, helpcontext(0x0001007e)]
        HRESULT _stdcall Top([in] double RHS);
        [restricted, hidden]
        void _stdcall _Dummy22();
        [propget, helpcontext(0x0001022e)]
        HRESULT _stdcall Visible([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x0001022e)]
        HRESULT _stdcall Visible([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x0001007a)]
        HRESULT _stdcall Width([out, retval] double* RHS);
        [propput, helpcontext(0x0001007a)]
        HRESULT _stdcall Width([in] double RHS);
        [propget, helpcontext(0x0001026e)]
        HRESULT _stdcall ZOrder([out, retval] long* RHS);
        [propget, helpcontext(0x000105f8)]
        HRESULT _stdcall ShapeRange([out, retval] ShapeRange** RHS);
        [propget, helpcontext(0x00010427)]
        HRESULT _stdcall AddIndent([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010427)]
        HRESULT _stdcall AddIndent([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x000105f5)]
        HRESULT _stdcall AutoScaleFont([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x000105f5)]
        HRESULT _stdcall AutoScaleFont([in] VARIANT RHS);
        [propget, helpcontext(0x00010266)]
        HRESULT _stdcall AutoSize([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010266)]
        HRESULT _stdcall AutoSize([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x0001008b)]
        HRESULT _stdcall Caption([out, retval] BSTR* RHS);
        [propput, helpcontext(0x0001008b)]
        HRESULT _stdcall Caption([in] BSTR RHS);
        [propget, helpcontext(0x0001025b)]
        HRESULT _stdcall Characters(
                        [in, optional] VARIANT Start, 
                        [in, optional] VARIANT Length, 
                        [out, retval] Characters** RHS);
        [helpcontext(0x000101f9)]
        HRESULT _stdcall CheckSpelling(
                        [in, optional] VARIANT CustomDictionary, 
                        [in, optional] VARIANT IgnoreUppercase, 
                        [in, optional] VARIANT AlwaysSuggest, 
                        [in, optional] VARIANT IgnoreInitialAlefHamza, 
                        [in, optional] VARIANT IgnoreFinalYaa, 
                        [in, optional] VARIANT SpellScript);
        [propget, helpcontext(0x00010092)]
        HRESULT _stdcall Font([out, retval] Font** RHS);
        [propget, helpcontext(0x00010105)]
        HRESULT _stdcall Formula([out, retval] BSTR* RHS);
        [propput, helpcontext(0x00010105)]
        HRESULT _stdcall Formula([in] BSTR RHS);
        [propget, helpcontext(0x00010088)]
        HRESULT _stdcall HorizontalAlignment([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010088)]
        HRESULT _stdcall HorizontalAlignment([in] VARIANT RHS);
        [propget, helpcontext(0x00010268)]
        HRESULT _stdcall LockedText([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010268)]
        HRESULT _stdcall LockedText([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x00010086)]
        HRESULT _stdcall Orientation([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010086)]
        HRESULT _stdcall Orientation([in] VARIANT RHS);
        [propget, helpcontext(0x0001008a)]
        HRESULT _stdcall Text([out, retval] BSTR* RHS);
        [propput, helpcontext(0x0001008a)]
        HRESULT _stdcall Text([in] BSTR RHS);
        [propget, helpcontext(0x00010089)]
        HRESULT _stdcall VerticalAlignment([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010089)]
        HRESULT _stdcall VerticalAlignment([in] VARIANT RHS);
        [propget, helpcontext(0x000103cf)]
        HRESULT _stdcall ReadingOrder([out, retval] long* RHS);
        [propput, helpcontext(0x000103cf)]
        HRESULT _stdcall ReadingOrder([in] long RHS);
        [propget, helpcontext(0x00010080)]
        HRESULT _stdcall Border([out, retval] Border** RHS);
        [propget, helpcontext(0x00010081)]
        HRESULT _stdcall Interior([out, retval] Interior** RHS);
        [propget, helpcontext(0x0001026b)]
        HRESULT _stdcall RoundedCorners([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x0001026b)]
        HRESULT _stdcall RoundedCorners([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x00010067)]
        HRESULT _stdcall Shadow([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010067)]
        HRESULT _stdcall Shadow([in] VARIANT_BOOL RHS);
        [helpcontext(0x000100b5)]
        HRESULT _stdcall Add(
                        [in] double Left, 
                        [in] double Top, 
                        [in] double Width, 
                        [in] double Height, 
                        [out, retval] TextBox** RHS);
        [propget, helpcontext(0x00010076)]
        HRESULT _stdcall Count([out, retval] long* RHS);
        [helpcontext(0x0001002e)]
        HRESULT _stdcall Group([out, retval] GroupObject** RHS);
        [helpcontext(0x000100aa)]
        HRESULT _stdcall Item(
                        [in] VARIANT Index, 
                        [out, retval] IDispatch** RHS);
        [helpcontext(0x0000fffc)]
        HRESULT _stdcall _NewEnum([out, retval] IUnknown** RHS);
    };

    [
      odl,
      uuid(000208A6-0001-0000-C000-000000000046),
      helpcontext(0x00020066),
      hidden
    ]
    interface IPicture : IDispatch {
        [propget, helpcontext(0x00010094)]
        HRESULT _stdcall Application([out, retval] Application** RHS);
        [propget, helpcontext(0x00010095)]
        HRESULT _stdcall Creator([out, retval] XlCreator* RHS);
        [propget, helpcontext(0x00010096)]
        HRESULT _stdcall Parent([out, retval] IDispatch** RHS);
        [propget, helpcontext(0x00010267)]
        HRESULT _stdcall BottomRightCell([out, retval] Range** RHS);
        [helpcontext(0x0001025a)]
        HRESULT _stdcall BringToFront();
        [helpcontext(0x00010227)]
        HRESULT _stdcall Copy();
        [helpcontext(0x000100d5)]
        HRESULT _stdcall CopyPicture(
                        [in, optional, defaultvalue(2)] XlPictureAppearance Appearance, 
                        [in, optional, defaultvalue(-4147)] XlCopyPictureFormat Format);
        [helpcontext(0x00010235)]
        HRESULT _stdcall Cut();
        [helpcontext(0x00010075)]
        HRESULT _stdcall Delete();
        [helpcontext(0x0001040f)]
        HRESULT _stdcall Duplicate([out, retval] IDispatch** RHS);
        [propget, helpcontext(0x00010258)]
        HRESULT _stdcall Enabled([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010258)]
        HRESULT _stdcall Enabled([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x0001007b)]
        HRESULT _stdcall Height([out, retval] double* RHS);
        [propput, helpcontext(0x0001007b)]
        HRESULT _stdcall Height([in] double RHS);
        [propget, helpcontext(0x000101e6)]
        HRESULT _stdcall Index([out, retval] long* RHS);
        [propget, helpcontext(0x0001007f)]
        HRESULT _stdcall Left([out, retval] double* RHS);
        [propput, helpcontext(0x0001007f)]
        HRESULT _stdcall Left([in] double RHS);
        [propget, helpcontext(0x0001010d)]
        HRESULT _stdcall Locked([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x0001010d)]
        HRESULT _stdcall Locked([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x0001006e)]
        HRESULT _stdcall Name([out, retval] BSTR* RHS);
        [propput, helpcontext(0x0001006e)]
        HRESULT _stdcall Name([in] BSTR RHS);
        [propget, hidden, helpcontext(0x00010254)]
        HRESULT _stdcall OnAction([out, retval] BSTR* RHS);
        [propput, hidden, helpcontext(0x00010254)]
        HRESULT _stdcall OnAction([in] BSTR RHS);
        [propget, helpcontext(0x00010269)]
        HRESULT _stdcall Placement([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010269)]
        HRESULT _stdcall Placement([in] VARIANT RHS);
        [propget, helpcontext(0x0001026a)]
        HRESULT _stdcall PrintObject([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x0001026a)]
        HRESULT _stdcall PrintObject([in] VARIANT_BOOL RHS);
        [helpcontext(0x000100eb)]
        HRESULT _stdcall Select([in, optional] VARIANT Replace);
        [helpcontext(0x0001025d)]
        HRESULT _stdcall SendToBack();
        [propget, helpcontext(0x0001007e)]
        HRESULT _stdcall Top([out, retval] double* RHS);
        [propput, helpcontext(0x0001007e)]
        HRESULT _stdcall Top([in] double RHS);
        [propget, helpcontext(0x0001026c)]
        HRESULT _stdcall TopLeftCell([out, retval] Range** RHS);
        [propget, helpcontext(0x0001022e)]
        HRESULT _stdcall Visible([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x0001022e)]
        HRESULT _stdcall Visible([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x0001007a)]
        HRESULT _stdcall Width([out, retval] double* RHS);
        [propput, helpcontext(0x0001007a)]
        HRESULT _stdcall Width([in] double RHS);
        [propget, helpcontext(0x0001026e)]
        HRESULT _stdcall ZOrder([out, retval] long* RHS);
        [propget, helpcontext(0x000105f8)]
        HRESULT _stdcall ShapeRange([out, retval] ShapeRange** RHS);
        [propget, helpcontext(0x00010080)]
        HRESULT _stdcall Border([out, retval] Border** RHS);
        [propget, helpcontext(0x00010081)]
        HRESULT _stdcall Interior([out, retval] Interior** RHS);
        [propget, helpcontext(0x00010067)]
        HRESULT _stdcall Shadow([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010067)]
        HRESULT _stdcall Shadow([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x00010105)]
        HRESULT _stdcall Formula([out, retval] BSTR* RHS);
        [propput, helpcontext(0x00010105)]
        HRESULT _stdcall Formula([in] BSTR RHS);
    };

    [
      odl,
      uuid(000208A7-0001-0000-C000-000000000046),
      helpcontext(0x00020067),
      hidden
    ]
    interface IPictures : IDispatch {
        [propget, helpcontext(0x00010094)]
        HRESULT _stdcall Application([out, retval] Application** RHS);
        [propget, helpcontext(0x00010095)]
        HRESULT _stdcall Creator([out, retval] XlCreator* RHS);
        [propget, helpcontext(0x00010096)]
        HRESULT _stdcall Parent([out, retval] IDispatch** RHS);
        [restricted, hidden]
        void _stdcall _Dummy3();
        [helpcontext(0x0001025a)]
        HRESULT _stdcall BringToFront();
        [helpcontext(0x00010227)]
        HRESULT _stdcall Copy();
        [helpcontext(0x000100d5)]
        HRESULT _stdcall CopyPicture(
                        [in, optional, defaultvalue(2)] XlPictureAppearance Appearance, 
                        [in, optional, defaultvalue(-4147)] XlCopyPictureFormat Format);
        [helpcontext(0x00010235)]
        HRESULT _stdcall Cut();
        [helpcontext(0x00010075)]
        HRESULT _stdcall Delete();
        [helpcontext(0x0001040f)]
        HRESULT _stdcall Duplicate([out, retval] IDispatch** RHS);
        [propget, helpcontext(0x00010258)]
        HRESULT _stdcall Enabled([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010258)]
        HRESULT _stdcall Enabled([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x0001007b)]
        HRESULT _stdcall Height([out, retval] double* RHS);
        [propput, helpcontext(0x0001007b)]
        HRESULT _stdcall Height([in] double RHS);
        [restricted, hidden]
        void _stdcall _Dummy12();
        [propget, helpcontext(0x0001007f)]
        HRESULT _stdcall Left([out, retval] double* RHS);
        [propput, helpcontext(0x0001007f)]
        HRESULT _stdcall Left([in] double RHS);
        [propget, helpcontext(0x0001010d)]
        HRESULT _stdcall Locked([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x0001010d)]
        HRESULT _stdcall Locked([in] VARIANT_BOOL RHS);
        [restricted, hidden]
        void _stdcall _Dummy15();
        [propget, hidden, helpcontext(0x00010254)]
        HRESULT _stdcall OnAction([out, retval] BSTR* RHS);
        [propput, hidden, helpcontext(0x00010254)]
        HRESULT _stdcall OnAction([in] BSTR RHS);
        [propget, helpcontext(0x00010269)]
        HRESULT _stdcall Placement([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010269)]
        HRESULT _stdcall Placement([in] VARIANT RHS);
        [propget, helpcontext(0x0001026a)]
        HRESULT _stdcall PrintObject([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x0001026a)]
        HRESULT _stdcall PrintObject([in] VARIANT_BOOL RHS);
        [helpcontext(0x000100eb)]
        HRESULT _stdcall Select([in, optional] VARIANT Replace);
        [helpcontext(0x0001025d)]
        HRESULT _stdcall SendToBack();
        [propget, helpcontext(0x0001007e)]
        HRESULT _stdcall Top([out, retval] double* RHS);
        [propput, helpcontext(0x0001007e)]
        HRESULT _stdcall Top([in] double RHS);
        [restricted, hidden]
        void _stdcall _Dummy22();
        [propget, helpcontext(0x0001022e)]
        HRESULT _stdcall Visible([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x0001022e)]
        HRESULT _stdcall Visible([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x0001007a)]
        HRESULT _stdcall Width([out, retval] double* RHS);
        [propput, helpcontext(0x0001007a)]
        HRESULT _stdcall Width([in] double RHS);
        [propget, helpcontext(0x0001026e)]
        HRESULT _stdcall ZOrder([out, retval] long* RHS);
        [propget, helpcontext(0x000105f8)]
        HRESULT _stdcall ShapeRange([out, retval] ShapeRange** RHS);
        [propget, helpcontext(0x00010080)]
        HRESULT _stdcall Border([out, retval] Border** RHS);
        [propget, helpcontext(0x00010081)]
        HRESULT _stdcall Interior([out, retval] Interior** RHS);
        [propget, helpcontext(0x00010067)]
        HRESULT _stdcall Shadow([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010067)]
        HRESULT _stdcall Shadow([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x00010105)]
        HRESULT _stdcall Formula([out, retval] BSTR* RHS);
        [propput, helpcontext(0x00010105)]
        HRESULT _stdcall Formula([in] BSTR RHS);
        [helpcontext(0x000100b5)]
        HRESULT _stdcall Add(
                        [in] double Left, 
                        [in] double Top, 
                        [in] double Width, 
                        [in] double Height, 
                        [out, retval] Picture** RHS);
        [propget, helpcontext(0x00010076)]
        HRESULT _stdcall Count([out, retval] long* RHS);
        [helpcontext(0x0001002e)]
        HRESULT _stdcall Group([out, retval] GroupObject** RHS);
        [helpcontext(0x000100fc)]
        HRESULT _stdcall Insert(
                        [in] BSTR Filename, 
                        [in, optional] VARIANT Converter, 
                        [out, retval] Picture** RHS);
        [helpcontext(0x000100aa)]
        HRESULT _stdcall Item(
                        [in] VARIANT Index, 
                        [out, retval] IDispatch** RHS);
        [helpcontext(0x0000fffc)]
        HRESULT _stdcall _NewEnum([out, retval] IUnknown** RHS);
        [helpcontext(0x000100d3)]
        HRESULT _stdcall Paste(
                        [in, optional] VARIANT Link, 
                        [out, retval] Picture** RHS);
    };

    [
      odl,
      uuid(000208A8-0001-0000-C000-000000000046),
      helpcontext(0x00020068),
      hidden
    ]
    interface IDrawing : IDispatch {
        [propget, helpcontext(0x00010094)]
        HRESULT _stdcall Application([out, retval] Application** RHS);
        [propget, helpcontext(0x00010095)]
        HRESULT _stdcall Creator([out, retval] XlCreator* RHS);
        [propget, helpcontext(0x00010096)]
        HRESULT _stdcall Parent([out, retval] IDispatch** RHS);
        [propget, helpcontext(0x00010267)]
        HRESULT _stdcall BottomRightCell([out, retval] Range** RHS);
        [helpcontext(0x0001025a)]
        HRESULT _stdcall BringToFront();
        [helpcontext(0x00010227)]
        HRESULT _stdcall Copy();
        [helpcontext(0x000100d5)]
        HRESULT _stdcall CopyPicture(
                        [in, optional, defaultvalue(2)] XlPictureAppearance Appearance, 
                        [in, optional, defaultvalue(-4147)] XlCopyPictureFormat Format);
        [helpcontext(0x00010235)]
        HRESULT _stdcall Cut();
        [helpcontext(0x00010075)]
        HRESULT _stdcall Delete();
        [helpcontext(0x0001040f)]
        HRESULT _stdcall Duplicate([out, retval] IDispatch** RHS);
        [propget, helpcontext(0x00010258)]
        HRESULT _stdcall Enabled([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010258)]
        HRESULT _stdcall Enabled([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x0001007b)]
        HRESULT _stdcall Height([out, retval] double* RHS);
        [propput, helpcontext(0x0001007b)]
        HRESULT _stdcall Height([in] double RHS);
        [propget, helpcontext(0x000101e6)]
        HRESULT _stdcall Index([out, retval] long* RHS);
        [propget, helpcontext(0x0001007f)]
        HRESULT _stdcall Left([out, retval] double* RHS);
        [propput, helpcontext(0x0001007f)]
        HRESULT _stdcall Left([in] double RHS);
        [propget, helpcontext(0x0001010d)]
        HRESULT _stdcall Locked([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x0001010d)]
        HRESULT _stdcall Locked([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x0001006e)]
        HRESULT _stdcall Name([out, retval] BSTR* RHS);
        [propput, helpcontext(0x0001006e)]
        HRESULT _stdcall Name([in] BSTR RHS);
        [propget, hidden, helpcontext(0x00010254)]
        HRESULT _stdcall OnAction([out, retval] BSTR* RHS);
        [propput, hidden, helpcontext(0x00010254)]
        HRESULT _stdcall OnAction([in] BSTR RHS);
        [propget, helpcontext(0x00010269)]
        HRESULT _stdcall Placement([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010269)]
        HRESULT _stdcall Placement([in] VARIANT RHS);
        [propget, helpcontext(0x0001026a)]
        HRESULT _stdcall PrintObject([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x0001026a)]
        HRESULT _stdcall PrintObject([in] VARIANT_BOOL RHS);
        [helpcontext(0x000100eb)]
        HRESULT _stdcall Select([in, optional] VARIANT Replace);
        [helpcontext(0x0001025d)]
        HRESULT _stdcall SendToBack();
        [propget, helpcontext(0x0001007e)]
        HRESULT _stdcall Top([out, retval] double* RHS);
        [propput, helpcontext(0x0001007e)]
        HRESULT _stdcall Top([in] double RHS);
        [propget, helpcontext(0x0001026c)]
        HRESULT _stdcall TopLeftCell([out, retval] Range** RHS);
        [propget, helpcontext(0x0001022e)]
        HRESULT _stdcall Visible([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x0001022e)]
        HRESULT _stdcall Visible([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x0001007a)]
        HRESULT _stdcall Width([out, retval] double* RHS);
        [propput, helpcontext(0x0001007a)]
        HRESULT _stdcall Width([in] double RHS);
        [propget, helpcontext(0x0001026e)]
        HRESULT _stdcall ZOrder([out, retval] long* RHS);
        [propget, helpcontext(0x000105f8)]
        HRESULT _stdcall ShapeRange([out, retval] ShapeRange** RHS);
        [propget, helpcontext(0x00010427)]
        HRESULT _stdcall AddIndent([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010427)]
        HRESULT _stdcall AddIndent([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x000105f5)]
        HRESULT _stdcall AutoScaleFont([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x000105f5)]
        HRESULT _stdcall AutoScaleFont([in] VARIANT RHS);
        [propget, helpcontext(0x00010266)]
        HRESULT _stdcall AutoSize([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010266)]
        HRESULT _stdcall AutoSize([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x0001008b)]
        HRESULT _stdcall Caption([out, retval] BSTR* RHS);
        [propput, helpcontext(0x0001008b)]
        HRESULT _stdcall Caption([in] BSTR RHS);
        [propget, helpcontext(0x0001025b)]
        HRESULT _stdcall Characters(
                        [in, optional] VARIANT Start, 
                        [in, optional] VARIANT Length, 
                        [out, retval] Characters** RHS);
        [helpcontext(0x000101f9)]
        HRESULT _stdcall CheckSpelling(
                        [in, optional] VARIANT CustomDictionary, 
                        [in, optional] VARIANT IgnoreUppercase, 
                        [in, optional] VARIANT AlwaysSuggest, 
                        [in, optional] VARIANT IgnoreInitialAlefHamza, 
                        [in, optional] VARIANT IgnoreFinalYaa, 
                        [in, optional] VARIANT SpellScript);
        [propget, helpcontext(0x00010092)]
        HRESULT _stdcall Font([out, retval] Font** RHS);
        [propget, helpcontext(0x00010105)]
        HRESULT _stdcall Formula([out, retval] BSTR* RHS);
        [propput, helpcontext(0x00010105)]
        HRESULT _stdcall Formula([in] BSTR RHS);
        [propget, helpcontext(0x00010088)]
        HRESULT _stdcall HorizontalAlignment([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010088)]
        HRESULT _stdcall HorizontalAlignment([in] VARIANT RHS);
        [propget, helpcontext(0x00010268)]
        HRESULT _stdcall LockedText([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010268)]
        HRESULT _stdcall LockedText([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x00010086)]
        HRESULT _stdcall Orientation([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010086)]
        HRESULT _stdcall Orientation([in] VARIANT RHS);
        [propget, helpcontext(0x0001008a)]
        HRESULT _stdcall Text([out, retval] BSTR* RHS);
        [propput, helpcontext(0x0001008a)]
        HRESULT _stdcall Text([in] BSTR RHS);
        [propget, helpcontext(0x00010089)]
        HRESULT _stdcall VerticalAlignment([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010089)]
        HRESULT _stdcall VerticalAlignment([in] VARIANT RHS);
        [propget, helpcontext(0x000103cf)]
        HRESULT _stdcall ReadingOrder([out, retval] long* RHS);
        [propput, helpcontext(0x000103cf)]
        HRESULT _stdcall ReadingOrder([in] long RHS);
        [propget, helpcontext(0x00010080)]
        HRESULT _stdcall Border([out, retval] Border** RHS);
        [propget, helpcontext(0x00010081)]
        HRESULT _stdcall Interior([out, retval] Interior** RHS);
        [propget, helpcontext(0x00010067)]
        HRESULT _stdcall Shadow([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010067)]
        HRESULT _stdcall Shadow([in] VARIANT_BOOL RHS);
        [helpcontext(0x00010259)]
        HRESULT _stdcall AddVertex(
                        [in] double Left, 
                        [in] double Top);
        [helpcontext(0x0001025c)]
        HRESULT _stdcall Reshape(
                        [in] long Vertex, 
                        [in] VARIANT_BOOL Insert, 
                        [in, optional] VARIANT Left, 
                        [in, optional] VARIANT Top);
        [propget, helpcontext(0x0001026d)]
        HRESULT _stdcall Vertices(
                        [in, optional] VARIANT Index1, 
                        [in, optional] VARIANT Index2, 
                        [out, retval] VARIANT* RHS);
    };

    [
      odl,
      uuid(000208A9-0001-0000-C000-000000000046),
      helpcontext(0x00020069),
      hidden
    ]
    interface IDrawings : IDispatch {
        [propget, helpcontext(0x00010094)]
        HRESULT _stdcall Application([out, retval] Application** RHS);
        [propget, helpcontext(0x00010095)]
        HRESULT _stdcall Creator([out, retval] XlCreator* RHS);
        [propget, helpcontext(0x00010096)]
        HRESULT _stdcall Parent([out, retval] IDispatch** RHS);
        [restricted, hidden]
        void _stdcall _Dummy3();
        [helpcontext(0x0001025a)]
        HRESULT _stdcall BringToFront();
        [helpcontext(0x00010227)]
        HRESULT _stdcall Copy();
        [helpcontext(0x000100d5)]
        HRESULT _stdcall CopyPicture(
                        [in, optional, defaultvalue(2)] XlPictureAppearance Appearance, 
                        [in, optional, defaultvalue(-4147)] XlCopyPictureFormat Format);
        [helpcontext(0x00010235)]
        HRESULT _stdcall Cut();
        [helpcontext(0x00010075)]
        HRESULT _stdcall Delete();
        [helpcontext(0x0001040f)]
        HRESULT _stdcall Duplicate([out, retval] IDispatch** RHS);
        [propget, helpcontext(0x00010258)]
        HRESULT _stdcall Enabled([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010258)]
        HRESULT _stdcall Enabled([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x0001007b)]
        HRESULT _stdcall Height([out, retval] double* RHS);
        [propput, helpcontext(0x0001007b)]
        HRESULT _stdcall Height([in] double RHS);
        [restricted, hidden]
        void _stdcall _Dummy12();
        [propget, helpcontext(0x0001007f)]
        HRESULT _stdcall Left([out, retval] double* RHS);
        [propput, helpcontext(0x0001007f)]
        HRESULT _stdcall Left([in] double RHS);
        [propget, helpcontext(0x0001010d)]
        HRESULT _stdcall Locked([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x0001010d)]
        HRESULT _stdcall Locked([in] VARIANT_BOOL RHS);
        [restricted, hidden]
        void _stdcall _Dummy15();
        [propget, hidden, helpcontext(0x00010254)]
        HRESULT _stdcall OnAction([out, retval] BSTR* RHS);
        [propput, hidden, helpcontext(0x00010254)]
        HRESULT _stdcall OnAction([in] BSTR RHS);
        [propget, helpcontext(0x00010269)]
        HRESULT _stdcall Placement([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010269)]
        HRESULT _stdcall Placement([in] VARIANT RHS);
        [propget, helpcontext(0x0001026a)]
        HRESULT _stdcall PrintObject([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x0001026a)]
        HRESULT _stdcall PrintObject([in] VARIANT_BOOL RHS);
        [helpcontext(0x000100eb)]
        HRESULT _stdcall Select([in, optional] VARIANT Replace);
        [helpcontext(0x0001025d)]
        HRESULT _stdcall SendToBack();
        [propget, helpcontext(0x0001007e)]
        HRESULT _stdcall Top([out, retval] double* RHS);
        [propput, helpcontext(0x0001007e)]
        HRESULT _stdcall Top([in] double RHS);
        [restricted, hidden]
        void _stdcall _Dummy22();
        [propget, helpcontext(0x0001022e)]
        HRESULT _stdcall Visible([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x0001022e)]
        HRESULT _stdcall Visible([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x0001007a)]
        HRESULT _stdcall Width([out, retval] double* RHS);
        [propput, helpcontext(0x0001007a)]
        HRESULT _stdcall Width([in] double RHS);
        [propget, helpcontext(0x0001026e)]
        HRESULT _stdcall ZOrder([out, retval] long* RHS);
        [propget, helpcontext(0x000105f8)]
        HRESULT _stdcall ShapeRange([out, retval] ShapeRange** RHS);
        [propget, helpcontext(0x00010427)]
        HRESULT _stdcall AddIndent([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010427)]
        HRESULT _stdcall AddIndent([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x000105f5)]
        HRESULT _stdcall AutoScaleFont([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x000105f5)]
        HRESULT _stdcall AutoScaleFont([in] VARIANT RHS);
        [propget, helpcontext(0x00010266)]
        HRESULT _stdcall AutoSize([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010266)]
        HRESULT _stdcall AutoSize([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x0001008b)]
        HRESULT _stdcall Caption([out, retval] BSTR* RHS);
        [propput, helpcontext(0x0001008b)]
        HRESULT _stdcall Caption([in] BSTR RHS);
        [propget, helpcontext(0x0001025b)]
        HRESULT _stdcall Characters(
                        [in, optional] VARIANT Start, 
                        [in, optional] VARIANT Length, 
                        [out, retval] Characters** RHS);
        [helpcontext(0x000101f9)]
        HRESULT _stdcall CheckSpelling(
                        [in, optional] VARIANT CustomDictionary, 
                        [in, optional] VARIANT IgnoreUppercase, 
                        [in, optional] VARIANT AlwaysSuggest, 
                        [in, optional] VARIANT IgnoreInitialAlefHamza, 
                        [in, optional] VARIANT IgnoreFinalYaa, 
                        [in, optional] VARIANT SpellScript);
        [propget, helpcontext(0x00010092)]
        HRESULT _stdcall Font([out, retval] Font** RHS);
        [propget, helpcontext(0x00010105)]
        HRESULT _stdcall Formula([out, retval] BSTR* RHS);
        [propput, helpcontext(0x00010105)]
        HRESULT _stdcall Formula([in] BSTR RHS);
        [propget, helpcontext(0x00010088)]
        HRESULT _stdcall HorizontalAlignment([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010088)]
        HRESULT _stdcall HorizontalAlignment([in] VARIANT RHS);
        [propget, helpcontext(0x00010268)]
        HRESULT _stdcall LockedText([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010268)]
        HRESULT _stdcall LockedText([in] VARIANT_BOOL RHS);
        [propget, helpcontext(0x00010086)]
        HRESULT _stdcall Orientation([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010086)]
        HRESULT _stdcall Orientation([in] VARIANT RHS);
        [propget, helpcontext(0x0001008a)]
        HRESULT _stdcall Text([out, retval] BSTR* RHS);
        [propput, helpcontext(0x0001008a)]
        HRESULT _stdcall Text([in] BSTR RHS);
        [propget, helpcontext(0x00010089)]
        HRESULT _stdcall VerticalAlignment([out, retval] VARIANT* RHS);
        [propput, helpcontext(0x00010089)]
        HRESULT _stdcall VerticalAlignment([in] VARIANT RHS);
        [propget, helpcontext(0x000103cf)]
        HRESULT _stdcall ReadingOrder([out, retval] long* RHS);
        [propput, helpcontext(0x000103cf)]
        HRESULT _stdcall ReadingOrder([in] long RHS);
        [propget, helpcontext(0x00010080)]
        HRESULT _stdcall Border([out, retval] Border** RHS);
        [propget, helpcontext(0x00010081)]
        HRESULT _stdcall Interior([out, retval] Interior** RHS);
        [propget, helpcontext(0x00010067)]
        HRESULT _stdcall Shadow([out, retval] VARIANT_BOOL* RHS);
        [propput, helpcontext(0x00010067)]
        HRESULT _stdcall Shadow([in] VARIANT_BOOL RHS);
        [restricted, hidden]
        void _stdcall _Dummy44();
        [helpcontext(0x0001025c)]
        HRESULT _stdcall Reshape(
                        [in] long Vertex, 
                        [in] VARIANT_BOOL Insert, 
                        [in, optional] VARIANT Left, 
                        [in, optional] VARIANT Top);
        [restricted, hidden]
        void _stdcall _Dummy46();
        [helpcontext(0x000100b5)]
        HRESULT _stdcall Add(
                        [in] double X1, 
                        [in] double Y1, 
                        [in] double X2, 
                        [in] double Y2, 
                        [in] VARIANT_BOOL Closed, 
                        [out, retval] Drawing** RHS);
        [propget, helpcontext(0x00010076)]
        HRESULT _stdcall Count([out, retval] long* RHS);
        [helpcontext(0x0001002e)]
        HRESULT _stdcall Group([out, retval] GroupObject** RHS);
        [helpcontext(0x000100aa)]
        HRESULT _stdcall Item(
                        [in] VARIANT Index, 
                        [out, retval] IDispatch** RHS);
        [helpcontext(0x0000fffc)]
        HRESULT _stdcall _NewEnum([out, retval] IUnknown** RHS);
    };

