import "Excel23.Idl";


    [
      uuid(000208A4-0000-0000-C000-000000000046),
      helpcontext(0x00020064),
      hidden
    ]
    dispinterface TextBox {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x00000267), propget, helpcontext(0x00010267)]
            Range* BottomRightCell();
            [id(0x0000025a), helpcontext(0x0001025a)]
            void BringToFront();
            [id(0x00000227), helpcontext(0x00010227)]
            void Copy();
            [id(0x000000d5), helpcontext(0x000100d5)]
            void CopyPicture(
                            [in, optional, defaultvalue(2)] XlPictureAppearance Appearance, 
                            [in, optional, defaultvalue(-4147)] XlCopyPictureFormat Format);
            [id(0x00000235), helpcontext(0x00010235)]
            void Cut();
            [id(0x00000075), helpcontext(0x00010075)]
            void Delete();
            [id(0x0000040f), helpcontext(0x0001040f)]
            IDispatch* Duplicate();
            [id(0x00000258), propget, helpcontext(0x00010258)]
            VARIANT_BOOL Enabled();
            [id(0x00000258), propput, helpcontext(0x00010258)]
            void Enabled([in] VARIANT_BOOL rhs);
            [id(0x0000007b), propget, helpcontext(0x0001007b)]
            double Height();
            [id(0x0000007b), propput, helpcontext(0x0001007b)]
            void Height([in] double rhs);
            [id(0x000001e6), propget, helpcontext(0x000101e6)]
            long Index();
            [id(0x0000007f), propget, helpcontext(0x0001007f)]
            double Left();
            [id(0x0000007f), propput, helpcontext(0x0001007f)]
            void Left([in] double rhs);
            [id(0x0000010d), propget, helpcontext(0x0001010d)]
            VARIANT_BOOL Locked();
            [id(0x0000010d), propput, helpcontext(0x0001010d)]
            void Locked([in] VARIANT_BOOL rhs);
            [id(0x0000006e), propget, helpcontext(0x0001006e)]
            BSTR Name();
            [id(0x0000006e), propput, helpcontext(0x0001006e)]
            void Name([in] BSTR rhs);
            [id(0x00000254), propget, hidden, helpcontext(0x00010254)]
            BSTR OnAction();
            [id(0x00000254), propput, hidden, helpcontext(0x00010254)]
            void OnAction([in] BSTR rhs);
            [id(0x00000269), propget, helpcontext(0x00010269)]
            VARIANT Placement();
            [id(0x00000269), propput, helpcontext(0x00010269)]
            void Placement([in] VARIANT rhs);
            [id(0x0000026a), propget, helpcontext(0x0001026a)]
            VARIANT_BOOL PrintObject();
            [id(0x0000026a), propput, helpcontext(0x0001026a)]
            void PrintObject([in] VARIANT_BOOL rhs);
            [id(0x000000eb), helpcontext(0x000100eb)]
            void Select([in, optional] VARIANT Replace);
            [id(0x0000025d), helpcontext(0x0001025d)]
            void SendToBack();
            [id(0x0000007e), propget, helpcontext(0x0001007e)]
            double Top();
            [id(0x0000007e), propput, helpcontext(0x0001007e)]
            void Top([in] double rhs);
            [id(0x0000026c), propget, helpcontext(0x0001026c)]
            Range* TopLeftCell();
            [id(0x0000022e), propget, helpcontext(0x0001022e)]
            VARIANT_BOOL Visible();
            [id(0x0000022e), propput, helpcontext(0x0001022e)]
            void Visible([in] VARIANT_BOOL rhs);
            [id(0x0000007a), propget, helpcontext(0x0001007a)]
            double Width();
            [id(0x0000007a), propput, helpcontext(0x0001007a)]
            void Width([in] double rhs);
            [id(0x0000026e), propget, helpcontext(0x0001026e)]
            long ZOrder();
            [id(0x000005f8), propget, helpcontext(0x000105f8)]
            ShapeRange* ShapeRange();
            [id(0x00000427), propget, helpcontext(0x00010427)]
            VARIANT_BOOL AddIndent();
            [id(0x00000427), propput, helpcontext(0x00010427)]
            void AddIndent([in] VARIANT_BOOL rhs);
            [id(0x000005f5), propget, helpcontext(0x000105f5)]
            VARIANT AutoScaleFont();
            [id(0x000005f5), propput, helpcontext(0x000105f5)]
            void AutoScaleFont([in] VARIANT rhs);
            [id(0x00000266), propget, helpcontext(0x00010266)]
            VARIANT_BOOL AutoSize();
            [id(0x00000266), propput, helpcontext(0x00010266)]
            void AutoSize([in] VARIANT_BOOL rhs);
            [id(0x0000008b), propget, helpcontext(0x0001008b)]
            BSTR Caption();
            [id(0x0000008b), propput, helpcontext(0x0001008b)]
            void Caption([in] BSTR rhs);
            [id(0x0000025b), propget, helpcontext(0x0001025b)]
            Characters* Characters(
                            [in, optional] VARIANT Start, 
                            [in, optional] VARIANT Length);
            [id(0x000001f9), helpcontext(0x000101f9)]
            void CheckSpelling(
                            [in, optional] VARIANT CustomDictionary, 
                            [in, optional] VARIANT IgnoreUppercase, 
                            [in, optional] VARIANT AlwaysSuggest, 
                            [in, optional] VARIANT IgnoreInitialAlefHamza, 
                            [in, optional] VARIANT IgnoreFinalYaa, 
                            [in, optional] VARIANT SpellScript);
            [id(0x00000092), propget, helpcontext(0x00010092)]
            Font* Font();
            [id(0x00000105), propget, helpcontext(0x00010105)]
            BSTR Formula();
            [id(0x00000105), propput, helpcontext(0x00010105)]
            void Formula([in] BSTR rhs);
            [id(0x00000088), propget, helpcontext(0x00010088)]
            VARIANT HorizontalAlignment();
            [id(0x00000088), propput, helpcontext(0x00010088)]
            void HorizontalAlignment([in] VARIANT rhs);
            [id(0x00000268), propget, helpcontext(0x00010268)]
            VARIANT_BOOL LockedText();
            [id(0x00000268), propput, helpcontext(0x00010268)]
            void LockedText([in] VARIANT_BOOL rhs);
            [id(0x00000086), propget, helpcontext(0x00010086)]
            VARIANT Orientation();
            [id(0x00000086), propput, helpcontext(0x00010086)]
            void Orientation([in] VARIANT rhs);
            [id(0x0000008a), propget, helpcontext(0x0001008a)]
            BSTR Text();
            [id(0x0000008a), propput, helpcontext(0x0001008a)]
            void Text([in] BSTR rhs);
            [id(0x00000089), propget, helpcontext(0x00010089)]
            VARIANT VerticalAlignment();
            [id(0x00000089), propput, helpcontext(0x00010089)]
            void VerticalAlignment([in] VARIANT rhs);
            [id(0x000003cf), propget, helpcontext(0x000103cf)]
            long ReadingOrder();
            [id(0x000003cf), propput, helpcontext(0x000103cf)]
            void ReadingOrder([in] long rhs);
            [id(0x00000080), propget, helpcontext(0x00010080)]
            Border* Border();
            [id(0x00000081), propget, helpcontext(0x00010081)]
            Interior* Interior();
            [id(0x0000026b), propget, helpcontext(0x0001026b)]
            VARIANT_BOOL RoundedCorners();
            [id(0x0000026b), propput, helpcontext(0x0001026b)]
            void RoundedCorners([in] VARIANT_BOOL rhs);
            [id(0x00000067), propget, helpcontext(0x00010067)]
            VARIANT_BOOL Shadow();
            [id(0x00000067), propput, helpcontext(0x00010067)]
            void Shadow([in] VARIANT_BOOL rhs);
    };

    [
      uuid(000208A5-0000-0000-C000-000000000046),
      helpcontext(0x00020065),
      hidden
    ]
    dispinterface TextBoxes {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x00010003), restricted, hidden]
            void _Dummy3();
            [id(0x0000025a), helpcontext(0x0001025a)]
            void BringToFront();
            [id(0x00000227), helpcontext(0x00010227)]
            void Copy();
            [id(0x000000d5), helpcontext(0x000100d5)]
            void CopyPicture(
                            [in, optional, defaultvalue(2)] XlPictureAppearance Appearance, 
                            [in, optional, defaultvalue(-4147)] XlCopyPictureFormat Format);
            [id(0x00000235), helpcontext(0x00010235)]
            void Cut();
            [id(0x00000075), helpcontext(0x00010075)]
            void Delete();
            [id(0x0000040f), helpcontext(0x0001040f)]
            IDispatch* Duplicate();
            [id(0x00000258), propget, helpcontext(0x00010258)]
            VARIANT_BOOL Enabled();
            [id(0x00000258), propput, helpcontext(0x00010258)]
            void Enabled([in] VARIANT_BOOL rhs);
            [id(0x0000007b), propget, helpcontext(0x0001007b)]
            double Height();
            [id(0x0000007b), propput, helpcontext(0x0001007b)]
            void Height([in] double rhs);
            [id(0x0001000c), restricted, hidden]
            void _Dummy12();
            [id(0x0000007f), propget, helpcontext(0x0001007f)]
            double Left();
            [id(0x0000007f), propput, helpcontext(0x0001007f)]
            void Left([in] double rhs);
            [id(0x0000010d), propget, helpcontext(0x0001010d)]
            VARIANT_BOOL Locked();
            [id(0x0000010d), propput, helpcontext(0x0001010d)]
            void Locked([in] VARIANT_BOOL rhs);
            [id(0x0001000f), restricted, hidden]
            void _Dummy15();
            [id(0x00000254), propget, hidden, helpcontext(0x00010254)]
            BSTR OnAction();
            [id(0x00000254), propput, hidden, helpcontext(0x00010254)]
            void OnAction([in] BSTR rhs);
            [id(0x00000269), propget, helpcontext(0x00010269)]
            VARIANT Placement();
            [id(0x00000269), propput, helpcontext(0x00010269)]
            void Placement([in] VARIANT rhs);
            [id(0x0000026a), propget, helpcontext(0x0001026a)]
            VARIANT_BOOL PrintObject();
            [id(0x0000026a), propput, helpcontext(0x0001026a)]
            void PrintObject([in] VARIANT_BOOL rhs);
            [id(0x000000eb), helpcontext(0x000100eb)]
            void Select([in, optional] VARIANT Replace);
            [id(0x0000025d), helpcontext(0x0001025d)]
            void SendToBack();
            [id(0x0000007e), propget, helpcontext(0x0001007e)]
            double Top();
            [id(0x0000007e), propput, helpcontext(0x0001007e)]
            void Top([in] double rhs);
            [id(0x00010016), restricted, hidden]
            void _Dummy22();
            [id(0x0000022e), propget, helpcontext(0x0001022e)]
            VARIANT_BOOL Visible();
            [id(0x0000022e), propput, helpcontext(0x0001022e)]
            void Visible([in] VARIANT_BOOL rhs);
            [id(0x0000007a), propget, helpcontext(0x0001007a)]
            double Width();
            [id(0x0000007a), propput, helpcontext(0x0001007a)]
            void Width([in] double rhs);
            [id(0x0000026e), propget, helpcontext(0x0001026e)]
            long ZOrder();
            [id(0x000005f8), propget, helpcontext(0x000105f8)]
            ShapeRange* ShapeRange();
            [id(0x00000427), propget, helpcontext(0x00010427)]
            VARIANT_BOOL AddIndent();
            [id(0x00000427), propput, helpcontext(0x00010427)]
            void AddIndent([in] VARIANT_BOOL rhs);
            [id(0x000005f5), propget, helpcontext(0x000105f5)]
            VARIANT AutoScaleFont();
            [id(0x000005f5), propput, helpcontext(0x000105f5)]
            void AutoScaleFont([in] VARIANT rhs);
            [id(0x00000266), propget, helpcontext(0x00010266)]
            VARIANT_BOOL AutoSize();
            [id(0x00000266), propput, helpcontext(0x00010266)]
            void AutoSize([in] VARIANT_BOOL rhs);
            [id(0x0000008b), propget, helpcontext(0x0001008b)]
            BSTR Caption();
            [id(0x0000008b), propput, helpcontext(0x0001008b)]
            void Caption([in] BSTR rhs);
            [id(0x0000025b), propget, helpcontext(0x0001025b)]
            Characters* Characters(
                            [in, optional] VARIANT Start, 
                            [in, optional] VARIANT Length);
            [id(0x000001f9), helpcontext(0x000101f9)]
            void CheckSpelling(
                            [in, optional] VARIANT CustomDictionary, 
                            [in, optional] VARIANT IgnoreUppercase, 
                            [in, optional] VARIANT AlwaysSuggest, 
                            [in, optional] VARIANT IgnoreInitialAlefHamza, 
                            [in, optional] VARIANT IgnoreFinalYaa, 
                            [in, optional] VARIANT SpellScript);
            [id(0x00000092), propget, helpcontext(0x00010092)]
            Font* Font();
            [id(0x00000105), propget, helpcontext(0x00010105)]
            BSTR Formula();
            [id(0x00000105), propput, helpcontext(0x00010105)]
            void Formula([in] BSTR rhs);
            [id(0x00000088), propget, helpcontext(0x00010088)]
            VARIANT HorizontalAlignment();
            [id(0x00000088), propput, helpcontext(0x00010088)]
            void HorizontalAlignment([in] VARIANT rhs);
            [id(0x00000268), propget, helpcontext(0x00010268)]
            VARIANT_BOOL LockedText();
            [id(0x00000268), propput, helpcontext(0x00010268)]
            void LockedText([in] VARIANT_BOOL rhs);
            [id(0x00000086), propget, helpcontext(0x00010086)]
            VARIANT Orientation();
            [id(0x00000086), propput, helpcontext(0x00010086)]
            void Orientation([in] VARIANT rhs);
            [id(0x0000008a), propget, helpcontext(0x0001008a)]
            BSTR Text();
            [id(0x0000008a), propput, helpcontext(0x0001008a)]
            void Text([in] BSTR rhs);
            [id(0x00000089), propget, helpcontext(0x00010089)]
            VARIANT VerticalAlignment();
            [id(0x00000089), propput, helpcontext(0x00010089)]
            void VerticalAlignment([in] VARIANT rhs);
            [id(0x000003cf), propget, helpcontext(0x000103cf)]
            long ReadingOrder();
            [id(0x000003cf), propput, helpcontext(0x000103cf)]
            void ReadingOrder([in] long rhs);
            [id(0x00000080), propget, helpcontext(0x00010080)]
            Border* Border();
            [id(0x00000081), propget, helpcontext(0x00010081)]
            Interior* Interior();
            [id(0x0000026b), propget, helpcontext(0x0001026b)]
            VARIANT_BOOL RoundedCorners();
            [id(0x0000026b), propput, helpcontext(0x0001026b)]
            void RoundedCorners([in] VARIANT_BOOL rhs);
            [id(0x00000067), propget, helpcontext(0x00010067)]
            VARIANT_BOOL Shadow();
            [id(0x00000067), propput, helpcontext(0x00010067)]
            void Shadow([in] VARIANT_BOOL rhs);
            [id(0x000000b5), helpcontext(0x000100b5)]
            TextBox* Add(
                            [in] double Left, 
                            [in] double Top, 
                            [in] double Width, 
                            [in] double Height);
            [id(0x00000076), propget, helpcontext(0x00010076)]
            long Count();
            [id(0x0000002e), helpcontext(0x0001002e)]
            GroupObject* Group();
            [id(0x000000aa), helpcontext(0x000100aa)]
            IDispatch* Item([in] VARIANT Index);
            [id(0xfffffffc), helpcontext(0x0000fffc)]
            IUnknown* _NewEnum();
    };

    [
      uuid(000208A6-0000-0000-C000-000000000046),
      helpcontext(0x00020066),
      hidden
    ]
    dispinterface Picture {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x00000267), propget, helpcontext(0x00010267)]
            Range* BottomRightCell();
            [id(0x0000025a), helpcontext(0x0001025a)]
            void BringToFront();
            [id(0x00000227), helpcontext(0x00010227)]
            void Copy();
            [id(0x000000d5), helpcontext(0x000100d5)]
            void CopyPicture(
                            [in, optional, defaultvalue(2)] XlPictureAppearance Appearance, 
                            [in, optional, defaultvalue(-4147)] XlCopyPictureFormat Format);
            [id(0x00000235), helpcontext(0x00010235)]
            void Cut();
            [id(0x00000075), helpcontext(0x00010075)]
            void Delete();
            [id(0x0000040f), helpcontext(0x0001040f)]
            IDispatch* Duplicate();
            [id(0x00000258), propget, helpcontext(0x00010258)]
            VARIANT_BOOL Enabled();
            [id(0x00000258), propput, helpcontext(0x00010258)]
            void Enabled([in] VARIANT_BOOL rhs);
            [id(0x0000007b), propget, helpcontext(0x0001007b)]
            double Height();
            [id(0x0000007b), propput, helpcontext(0x0001007b)]
            void Height([in] double rhs);
            [id(0x000001e6), propget, helpcontext(0x000101e6)]
            long Index();
            [id(0x0000007f), propget, helpcontext(0x0001007f)]
            double Left();
            [id(0x0000007f), propput, helpcontext(0x0001007f)]
            void Left([in] double rhs);
            [id(0x0000010d), propget, helpcontext(0x0001010d)]
            VARIANT_BOOL Locked();
            [id(0x0000010d), propput, helpcontext(0x0001010d)]
            void Locked([in] VARIANT_BOOL rhs);
            [id(0x0000006e), propget, helpcontext(0x0001006e)]
            BSTR Name();
            [id(0x0000006e), propput, helpcontext(0x0001006e)]
            void Name([in] BSTR rhs);
            [id(0x00000254), propget, hidden, helpcontext(0x00010254)]
            BSTR OnAction();
            [id(0x00000254), propput, hidden, helpcontext(0x00010254)]
            void OnAction([in] BSTR rhs);
            [id(0x00000269), propget, helpcontext(0x00010269)]
            VARIANT Placement();
            [id(0x00000269), propput, helpcontext(0x00010269)]
            void Placement([in] VARIANT rhs);
            [id(0x0000026a), propget, helpcontext(0x0001026a)]
            VARIANT_BOOL PrintObject();
            [id(0x0000026a), propput, helpcontext(0x0001026a)]
            void PrintObject([in] VARIANT_BOOL rhs);
            [id(0x000000eb), helpcontext(0x000100eb)]
            void Select([in, optional] VARIANT Replace);
            [id(0x0000025d), helpcontext(0x0001025d)]
            void SendToBack();
            [id(0x0000007e), propget, helpcontext(0x0001007e)]
            double Top();
            [id(0x0000007e), propput, helpcontext(0x0001007e)]
            void Top([in] double rhs);
            [id(0x0000026c), propget, helpcontext(0x0001026c)]
            Range* TopLeftCell();
            [id(0x0000022e), propget, helpcontext(0x0001022e)]
            VARIANT_BOOL Visible();
            [id(0x0000022e), propput, helpcontext(0x0001022e)]
            void Visible([in] VARIANT_BOOL rhs);
            [id(0x0000007a), propget, helpcontext(0x0001007a)]
            double Width();
            [id(0x0000007a), propput, helpcontext(0x0001007a)]
            void Width([in] double rhs);
            [id(0x0000026e), propget, helpcontext(0x0001026e)]
            long ZOrder();
            [id(0x000005f8), propget, helpcontext(0x000105f8)]
            ShapeRange* ShapeRange();
            [id(0x00000080), propget, helpcontext(0x00010080)]
            Border* Border();
            [id(0x00000081), propget, helpcontext(0x00010081)]
            Interior* Interior();
            [id(0x00000067), propget, helpcontext(0x00010067)]
            VARIANT_BOOL Shadow();
            [id(0x00000067), propput, helpcontext(0x00010067)]
            void Shadow([in] VARIANT_BOOL rhs);
            [id(0x00000105), propget, helpcontext(0x00010105)]
            BSTR Formula();
            [id(0x00000105), propput, helpcontext(0x00010105)]
            void Formula([in] BSTR rhs);
    };

    [
      uuid(000208A7-0000-0000-C000-000000000046),
      helpcontext(0x00020067),
      hidden
    ]
    dispinterface Pictures {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x00010003), restricted, hidden]
            void _Dummy3();
            [id(0x0000025a), helpcontext(0x0001025a)]
            void BringToFront();
            [id(0x00000227), helpcontext(0x00010227)]
            void Copy();
            [id(0x000000d5), helpcontext(0x000100d5)]
            void CopyPicture(
                            [in, optional, defaultvalue(2)] XlPictureAppearance Appearance, 
                            [in, optional, defaultvalue(-4147)] XlCopyPictureFormat Format);
            [id(0x00000235), helpcontext(0x00010235)]
            void Cut();
            [id(0x00000075), helpcontext(0x00010075)]
            void Delete();
            [id(0x0000040f), helpcontext(0x0001040f)]
            IDispatch* Duplicate();
            [id(0x00000258), propget, helpcontext(0x00010258)]
            VARIANT_BOOL Enabled();
            [id(0x00000258), propput, helpcontext(0x00010258)]
            void Enabled([in] VARIANT_BOOL rhs);
            [id(0x0000007b), propget, helpcontext(0x0001007b)]
            double Height();
            [id(0x0000007b), propput, helpcontext(0x0001007b)]
            void Height([in] double rhs);
            [id(0x0001000c), restricted, hidden]
            void _Dummy12();
            [id(0x0000007f), propget, helpcontext(0x0001007f)]
            double Left();
            [id(0x0000007f), propput, helpcontext(0x0001007f)]
            void Left([in] double rhs);
            [id(0x0000010d), propget, helpcontext(0x0001010d)]
            VARIANT_BOOL Locked();
            [id(0x0000010d), propput, helpcontext(0x0001010d)]
            void Locked([in] VARIANT_BOOL rhs);
            [id(0x0001000f), restricted, hidden]
            void _Dummy15();
            [id(0x00000254), propget, hidden, helpcontext(0x00010254)]
            BSTR OnAction();
            [id(0x00000254), propput, hidden, helpcontext(0x00010254)]
            void OnAction([in] BSTR rhs);
            [id(0x00000269), propget, helpcontext(0x00010269)]
            VARIANT Placement();
            [id(0x00000269), propput, helpcontext(0x00010269)]
            void Placement([in] VARIANT rhs);
            [id(0x0000026a), propget, helpcontext(0x0001026a)]
            VARIANT_BOOL PrintObject();
            [id(0x0000026a), propput, helpcontext(0x0001026a)]
            void PrintObject([in] VARIANT_BOOL rhs);
            [id(0x000000eb), helpcontext(0x000100eb)]
            void Select([in, optional] VARIANT Replace);
            [id(0x0000025d), helpcontext(0x0001025d)]
            void SendToBack();
            [id(0x0000007e), propget, helpcontext(0x0001007e)]
            double Top();
            [id(0x0000007e), propput, helpcontext(0x0001007e)]
            void Top([in] double rhs);
            [id(0x00010016), restricted, hidden]
            void _Dummy22();
            [id(0x0000022e), propget, helpcontext(0x0001022e)]
            VARIANT_BOOL Visible();
            [id(0x0000022e), propput, helpcontext(0x0001022e)]
            void Visible([in] VARIANT_BOOL rhs);
            [id(0x0000007a), propget, helpcontext(0x0001007a)]
            double Width();
            [id(0x0000007a), propput, helpcontext(0x0001007a)]
            void Width([in] double rhs);
            [id(0x0000026e), propget, helpcontext(0x0001026e)]
            long ZOrder();
            [id(0x000005f8), propget, helpcontext(0x000105f8)]
            ShapeRange* ShapeRange();
            [id(0x00000080), propget, helpcontext(0x00010080)]
            Border* Border();
            [id(0x00000081), propget, helpcontext(0x00010081)]
            Interior* Interior();
            [id(0x00000067), propget, helpcontext(0x00010067)]
            VARIANT_BOOL Shadow();
            [id(0x00000067), propput, helpcontext(0x00010067)]
            void Shadow([in] VARIANT_BOOL rhs);
            [id(0x00000105), propget, helpcontext(0x00010105)]
            BSTR Formula();
            [id(0x00000105), propput, helpcontext(0x00010105)]
            void Formula([in] BSTR rhs);
            [id(0x000000b5), helpcontext(0x000100b5)]
            Picture* Add(
                            [in] double Left, 
                            [in] double Top, 
                            [in] double Width, 
                            [in] double Height);
            [id(0x00000076), propget, helpcontext(0x00010076)]
            long Count();
            [id(0x0000002e), helpcontext(0x0001002e)]
            GroupObject* Group();
            [id(0x000000fc), helpcontext(0x000100fc)]
            Picture* Insert(
                            [in] BSTR Filename, 
                            [in, optional] VARIANT Converter);
            [id(0x000000aa), helpcontext(0x000100aa)]
            IDispatch* Item([in] VARIANT Index);
            [id(0xfffffffc), helpcontext(0x0000fffc)]
            IUnknown* _NewEnum();
            [id(0x000000d3), helpcontext(0x000100d3)]
            Picture* Paste([in, optional] VARIANT Link);
    };

    [
      uuid(000208A8-0000-0000-C000-000000000046),
      helpcontext(0x00020068),
      hidden
    ]
    dispinterface Drawing {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x00000267), propget, helpcontext(0x00010267)]
            Range* BottomRightCell();
            [id(0x0000025a), helpcontext(0x0001025a)]
            void BringToFront();
            [id(0x00000227), helpcontext(0x00010227)]
            void Copy();
            [id(0x000000d5), helpcontext(0x000100d5)]
            void CopyPicture(
                            [in, optional, defaultvalue(2)] XlPictureAppearance Appearance, 
                            [in, optional, defaultvalue(-4147)] XlCopyPictureFormat Format);
            [id(0x00000235), helpcontext(0x00010235)]
            void Cut();
            [id(0x00000075), helpcontext(0x00010075)]
            void Delete();
            [id(0x0000040f), helpcontext(0x0001040f)]
            IDispatch* Duplicate();
            [id(0x00000258), propget, helpcontext(0x00010258)]
            VARIANT_BOOL Enabled();
            [id(0x00000258), propput, helpcontext(0x00010258)]
            void Enabled([in] VARIANT_BOOL rhs);
            [id(0x0000007b), propget, helpcontext(0x0001007b)]
            double Height();
            [id(0x0000007b), propput, helpcontext(0x0001007b)]
            void Height([in] double rhs);
            [id(0x000001e6), propget, helpcontext(0x000101e6)]
            long Index();
            [id(0x0000007f), propget, helpcontext(0x0001007f)]
            double Left();
            [id(0x0000007f), propput, helpcontext(0x0001007f)]
            void Left([in] double rhs);
            [id(0x0000010d), propget, helpcontext(0x0001010d)]
            VARIANT_BOOL Locked();
            [id(0x0000010d), propput, helpcontext(0x0001010d)]
            void Locked([in] VARIANT_BOOL rhs);
            [id(0x0000006e), propget, helpcontext(0x0001006e)]
            BSTR Name();
            [id(0x0000006e), propput, helpcontext(0x0001006e)]
            void Name([in] BSTR rhs);
            [id(0x00000254), propget, hidden, helpcontext(0x00010254)]
            BSTR OnAction();
            [id(0x00000254), propput, hidden, helpcontext(0x00010254)]
            void OnAction([in] BSTR rhs);
            [id(0x00000269), propget, helpcontext(0x00010269)]
            VARIANT Placement();
            [id(0x00000269), propput, helpcontext(0x00010269)]
            void Placement([in] VARIANT rhs);
            [id(0x0000026a), propget, helpcontext(0x0001026a)]
            VARIANT_BOOL PrintObject();
            [id(0x0000026a), propput, helpcontext(0x0001026a)]
            void PrintObject([in] VARIANT_BOOL rhs);
            [id(0x000000eb), helpcontext(0x000100eb)]
            void Select([in, optional] VARIANT Replace);
            [id(0x0000025d), helpcontext(0x0001025d)]
            void SendToBack();
            [id(0x0000007e), propget, helpcontext(0x0001007e)]
            double Top();
            [id(0x0000007e), propput, helpcontext(0x0001007e)]
            void Top([in] double rhs);
            [id(0x0000026c), propget, helpcontext(0x0001026c)]
            Range* TopLeftCell();
            [id(0x0000022e), propget, helpcontext(0x0001022e)]
            VARIANT_BOOL Visible();
            [id(0x0000022e), propput, helpcontext(0x0001022e)]
            void Visible([in] VARIANT_BOOL rhs);
            [id(0x0000007a), propget, helpcontext(0x0001007a)]
            double Width();
            [id(0x0000007a), propput, helpcontext(0x0001007a)]
            void Width([in] double rhs);
            [id(0x0000026e), propget, helpcontext(0x0001026e)]
            long ZOrder();
            [id(0x000005f8), propget, helpcontext(0x000105f8)]
            ShapeRange* ShapeRange();
            [id(0x00000427), propget, helpcontext(0x00010427)]
            VARIANT_BOOL AddIndent();
            [id(0x00000427), propput, helpcontext(0x00010427)]
            void AddIndent([in] VARIANT_BOOL rhs);
            [id(0x000005f5), propget, helpcontext(0x000105f5)]
            VARIANT AutoScaleFont();
            [id(0x000005f5), propput, helpcontext(0x000105f5)]
            void AutoScaleFont([in] VARIANT rhs);
            [id(0x00000266), propget, helpcontext(0x00010266)]
            VARIANT_BOOL AutoSize();
            [id(0x00000266), propput, helpcontext(0x00010266)]
            void AutoSize([in] VARIANT_BOOL rhs);
            [id(0x0000008b), propget, helpcontext(0x0001008b)]
            BSTR Caption();
            [id(0x0000008b), propput, helpcontext(0x0001008b)]
            void Caption([in] BSTR rhs);
            [id(0x0000025b), propget, helpcontext(0x0001025b)]
            Characters* Characters(
                            [in, optional] VARIANT Start, 
                            [in, optional] VARIANT Length);
            [id(0x000001f9), helpcontext(0x000101f9)]
            void CheckSpelling(
                            [in, optional] VARIANT CustomDictionary, 
                            [in, optional] VARIANT IgnoreUppercase, 
                            [in, optional] VARIANT AlwaysSuggest, 
                            [in, optional] VARIANT IgnoreInitialAlefHamza, 
                            [in, optional] VARIANT IgnoreFinalYaa, 
                            [in, optional] VARIANT SpellScript);
            [id(0x00000092), propget, helpcontext(0x00010092)]
            Font* Font();
            [id(0x00000105), propget, helpcontext(0x00010105)]
            BSTR Formula();
            [id(0x00000105), propput, helpcontext(0x00010105)]
            void Formula([in] BSTR rhs);
            [id(0x00000088), propget, helpcontext(0x00010088)]
            VARIANT HorizontalAlignment();
            [id(0x00000088), propput, helpcontext(0x00010088)]
            void HorizontalAlignment([in] VARIANT rhs);
            [id(0x00000268), propget, helpcontext(0x00010268)]
            VARIANT_BOOL LockedText();
            [id(0x00000268), propput, helpcontext(0x00010268)]
            void LockedText([in] VARIANT_BOOL rhs);
            [id(0x00000086), propget, helpcontext(0x00010086)]
            VARIANT Orientation();
            [id(0x00000086), propput, helpcontext(0x00010086)]
            void Orientation([in] VARIANT rhs);
            [id(0x0000008a), propget, helpcontext(0x0001008a)]
            BSTR Text();
            [id(0x0000008a), propput, helpcontext(0x0001008a)]
            void Text([in] BSTR rhs);
            [id(0x00000089), propget, helpcontext(0x00010089)]
            VARIANT VerticalAlignment();
            [id(0x00000089), propput, helpcontext(0x00010089)]
            void VerticalAlignment([in] VARIANT rhs);
            [id(0x000003cf), propget, helpcontext(0x000103cf)]
            long ReadingOrder();
            [id(0x000003cf), propput, helpcontext(0x000103cf)]
            void ReadingOrder([in] long rhs);
            [id(0x00000080), propget, helpcontext(0x00010080)]
            Border* Border();
            [id(0x00000081), propget, helpcontext(0x00010081)]
            Interior* Interior();
            [id(0x00000067), propget, helpcontext(0x00010067)]
            VARIANT_BOOL Shadow();
            [id(0x00000067), propput, helpcontext(0x00010067)]
            void Shadow([in] VARIANT_BOOL rhs);
            [id(0x00000259), helpcontext(0x00010259)]
            void AddVertex(
                            [in] double Left, 
                            [in] double Top);
            [id(0x0000025c), helpcontext(0x0001025c)]
            void Reshape(
                            [in] long Vertex, 
                            [in] VARIANT_BOOL Insert, 
                            [in, optional] VARIANT Left, 
                            [in, optional] VARIANT Top);
            [id(0x0000026d), propget, helpcontext(0x0001026d)]
            VARIANT Vertices(
                            [in, optional] VARIANT Index1, 
                            [in, optional] VARIANT Index2);
    };

    [
      uuid(000208A9-0000-0000-C000-000000000046),
      helpcontext(0x00020069),
      hidden
    ]
    dispinterface Drawings {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x00010003), restricted, hidden]
            void _Dummy3();
            [id(0x0000025a), helpcontext(0x0001025a)]
            void BringToFront();
            [id(0x00000227), helpcontext(0x00010227)]
            void Copy();
            [id(0x000000d5), helpcontext(0x000100d5)]
            void CopyPicture(
                            [in, optional, defaultvalue(2)] XlPictureAppearance Appearance, 
                            [in, optional, defaultvalue(-4147)] XlCopyPictureFormat Format);
            [id(0x00000235), helpcontext(0x00010235)]
            void Cut();
            [id(0x00000075), helpcontext(0x00010075)]
            void Delete();
            [id(0x0000040f), helpcontext(0x0001040f)]
            IDispatch* Duplicate();
            [id(0x00000258), propget, helpcontext(0x00010258)]
            VARIANT_BOOL Enabled();
            [id(0x00000258), propput, helpcontext(0x00010258)]
            void Enabled([in] VARIANT_BOOL rhs);
            [id(0x0000007b), propget, helpcontext(0x0001007b)]
            double Height();
            [id(0x0000007b), propput, helpcontext(0x0001007b)]
            void Height([in] double rhs);
            [id(0x0001000c), restricted, hidden]
            void _Dummy12();
            [id(0x0000007f), propget, helpcontext(0x0001007f)]
            double Left();
            [id(0x0000007f), propput, helpcontext(0x0001007f)]
            void Left([in] double rhs);
            [id(0x0000010d), propget, helpcontext(0x0001010d)]
            VARIANT_BOOL Locked();
            [id(0x0000010d), propput, helpcontext(0x0001010d)]
            void Locked([in] VARIANT_BOOL rhs);
            [id(0x0001000f), restricted, hidden]
            void _Dummy15();
            [id(0x00000254), propget, hidden, helpcontext(0x00010254)]
            BSTR OnAction();
            [id(0x00000254), propput, hidden, helpcontext(0x00010254)]
            void OnAction([in] BSTR rhs);
            [id(0x00000269), propget, helpcontext(0x00010269)]
            VARIANT Placement();
            [id(0x00000269), propput, helpcontext(0x00010269)]
            void Placement([in] VARIANT rhs);
            [id(0x0000026a), propget, helpcontext(0x0001026a)]
            VARIANT_BOOL PrintObject();
            [id(0x0000026a), propput, helpcontext(0x0001026a)]
            void PrintObject([in] VARIANT_BOOL rhs);
            [id(0x000000eb), helpcontext(0x000100eb)]
            void Select([in, optional] VARIANT Replace);
            [id(0x0000025d), helpcontext(0x0001025d)]
            void SendToBack();
            [id(0x0000007e), propget, helpcontext(0x0001007e)]
            double Top();
            [id(0x0000007e), propput, helpcontext(0x0001007e)]
            void Top([in] double rhs);
            [id(0x00010016), restricted, hidden]
            void _Dummy22();
            [id(0x0000022e), propget, helpcontext(0x0001022e)]
            VARIANT_BOOL Visible();
            [id(0x0000022e), propput, helpcontext(0x0001022e)]
            void Visible([in] VARIANT_BOOL rhs);
            [id(0x0000007a), propget, helpcontext(0x0001007a)]
            double Width();
            [id(0x0000007a), propput, helpcontext(0x0001007a)]
            void Width([in] double rhs);
            [id(0x0000026e), propget, helpcontext(0x0001026e)]
            long ZOrder();
            [id(0x000005f8), propget, helpcontext(0x000105f8)]
            ShapeRange* ShapeRange();
            [id(0x00000427), propget, helpcontext(0x00010427)]
            VARIANT_BOOL AddIndent();
            [id(0x00000427), propput, helpcontext(0x00010427)]
            void AddIndent([in] VARIANT_BOOL rhs);
            [id(0x000005f5), propget, helpcontext(0x000105f5)]
            VARIANT AutoScaleFont();
            [id(0x000005f5), propput, helpcontext(0x000105f5)]
            void AutoScaleFont([in] VARIANT rhs);
            [id(0x00000266), propget, helpcontext(0x00010266)]
            VARIANT_BOOL AutoSize();
            [id(0x00000266), propput, helpcontext(0x00010266)]
            void AutoSize([in] VARIANT_BOOL rhs);
            [id(0x0000008b), propget, helpcontext(0x0001008b)]
            BSTR Caption();
            [id(0x0000008b), propput, helpcontext(0x0001008b)]
            void Caption([in] BSTR rhs);
            [id(0x0000025b), propget, helpcontext(0x0001025b)]
            Characters* Characters(
                            [in, optional] VARIANT Start, 
                            [in, optional] VARIANT Length);
            [id(0x000001f9), helpcontext(0x000101f9)]
            void CheckSpelling(
                            [in, optional] VARIANT CustomDictionary, 
                            [in, optional] VARIANT IgnoreUppercase, 
                            [in, optional] VARIANT AlwaysSuggest, 
                            [in, optional] VARIANT IgnoreInitialAlefHamza, 
                            [in, optional] VARIANT IgnoreFinalYaa, 
                            [in, optional] VARIANT SpellScript);
            [id(0x00000092), propget, helpcontext(0x00010092)]
            Font* Font();
            [id(0x00000105), propget, helpcontext(0x00010105)]
            BSTR Formula();
            [id(0x00000105), propput, helpcontext(0x00010105)]
            void Formula([in] BSTR rhs);
            [id(0x00000088), propget, helpcontext(0x00010088)]
            VARIANT HorizontalAlignment();
            [id(0x00000088), propput, helpcontext(0x00010088)]
            void HorizontalAlignment([in] VARIANT rhs);
            [id(0x00000268), propget, helpcontext(0x00010268)]
            VARIANT_BOOL LockedText();
            [id(0x00000268), propput, helpcontext(0x00010268)]
            void LockedText([in] VARIANT_BOOL rhs);
            [id(0x00000086), propget, helpcontext(0x00010086)]
            VARIANT Orientation();
            [id(0x00000086), propput, helpcontext(0x00010086)]
            void Orientation([in] VARIANT rhs);
            [id(0x0000008a), propget, helpcontext(0x0001008a)]
            BSTR Text();
            [id(0x0000008a), propput, helpcontext(0x0001008a)]
            void Text([in] BSTR rhs);
            [id(0x00000089), propget, helpcontext(0x00010089)]
            VARIANT VerticalAlignment();
            [id(0x00000089), propput, helpcontext(0x00010089)]
            void VerticalAlignment([in] VARIANT rhs);
            [id(0x000003cf), propget, helpcontext(0x000103cf)]
            long ReadingOrder();
            [id(0x000003cf), propput, helpcontext(0x000103cf)]
            void ReadingOrder([in] long rhs);
            [id(0x00000080), propget, helpcontext(0x00010080)]
            Border* Border();
            [id(0x00000081), propget, helpcontext(0x00010081)]
            Interior* Interior();
            [id(0x00000067), propget, helpcontext(0x00010067)]
            VARIANT_BOOL Shadow();
            [id(0x00000067), propput, helpcontext(0x00010067)]
            void Shadow([in] VARIANT_BOOL rhs);
            [id(0x0001002c), restricted, hidden]
            void _Dummy44();
            [id(0x0000025c), helpcontext(0x0001025c)]
            void Reshape(
                            [in] long Vertex, 
                            [in] VARIANT_BOOL Insert, 
                            [in, optional] VARIANT Left, 
                            [in, optional] VARIANT Top);
            [id(0x0001002e), restricted, hidden]
            void _Dummy46();
            [id(0x000000b5), helpcontext(0x000100b5)]
            Drawing* Add(
                            [in] double X1, 
                            [in] double Y1, 
                            [in] double X2, 
                            [in] double Y2, 
                            [in] VARIANT_BOOL Closed);
            [id(0x00000076), propget, helpcontext(0x00010076)]
            long Count();
            [id(0x0000002e), helpcontext(0x0001002e)]
            GroupObject* Group();
            [id(0x000000aa), helpcontext(0x000100aa)]
            IDispatch* Item([in] VARIANT Index);
            [id(0xfffffffc), helpcontext(0x0000fffc)]
            IUnknown* _NewEnum();
    };

    [
      uuid(000208AA-0000-0000-C000-000000000046),
      helpcontext(0x0002006a)
    ]
    dispinterface RoutingSlip {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x000003bb), propget, helpcontext(0x000103bb)]
            XlRoutingSlipDelivery Delivery();
            [id(0x000003bb), propput, helpcontext(0x000103bb)]
            void Delivery([in] XlRoutingSlipDelivery rhs);
            [id(0x000003ba), propget, helpcontext(0x000103ba)]
            VARIANT Message();
            [id(0x000003ba), propput, helpcontext(0x000103ba)]
            void Message([in] VARIANT rhs);
            [id(0x000003b8), helpcontext(0x000103b8)]
            VARIANT Recipients([in, optional] VARIANT Index);
            [id(0x0000022b), helpcontext(0x0001022b)]
            void Reset();
            [id(0x000003bc), propget, helpcontext(0x000103bc)]
            VARIANT_BOOL ReturnWhenDone();
            [id(0x000003bc), propput, helpcontext(0x000103bc)]
            void ReturnWhenDone([in] VARIANT_BOOL rhs);
            [id(0x000003be), propget, helpcontext(0x000103be)]
            XlRoutingSlipStatus Status();
            [id(0x000003b9), propget, helpcontext(0x000103b9)]
            VARIANT Subject();
            [id(0x000003b9), propput, helpcontext(0x000103b9)]
            void Subject([in] VARIANT rhs);
            [id(0x000003bd), propget, helpcontext(0x000103bd)]
            VARIANT_BOOL TrackStatus();
            [id(0x000003bd), propput, helpcontext(0x000103bd)]
            void TrackStatus([in] VARIANT_BOOL rhs);
    };

    [
      uuid(000208AB-0000-0000-C000-000000000046),
      helpcontext(0x0002006b)
    ]
    dispinterface Outline {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x000003bf), propget, helpcontext(0x000103bf)]
            VARIANT_BOOL AutomaticStyles();
            [id(0x000003bf), propput, helpcontext(0x000103bf)]
            void AutomaticStyles([in] VARIANT_BOOL rhs);
            [id(0x000003c0), helpcontext(0x000103c0)]
            void ShowLevels(
                            [in, optional] VARIANT RowLevels, 
                            [in, optional] VARIANT ColumnLevels);
            [id(0x000003c1), propget, helpcontext(0x000103c1)]
            XlSummaryColumn SummaryColumn();
            [id(0x000003c1), propput, helpcontext(0x000103c1)]
            void SummaryColumn([in] XlSummaryColumn rhs);
            [id(0x00000386), propget, helpcontext(0x00010386)]
            XlSummaryRow SummaryRow();
            [id(0x00000386), propput, helpcontext(0x00010386)]
            void SummaryRow([in] XlSummaryRow rhs);
    };

    [
      uuid(000208AD-0000-0000-C000-000000000046),
      helpcontext(0x0002006d),
      hidden
    ]
    dispinterface Module {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x00000130), helpcontext(0x00010130)]
            void Activate();
            [id(0x00000227), helpcontext(0x00010227)]
            void Copy(
                            [in, optional] VARIANT Before, 
                            [in, optional] VARIANT After);
            [id(0x00000075), helpcontext(0x00010075)]
            void Delete();
            [id(0x0000055d), propget, helpcontext(0x0001055d)]
            BSTR CodeName();
            [id(0x80010000), propget, helpcontext(0x80020000)]
            BSTR _CodeName();
            [id(0x80010000), propput, helpcontext(0x80020000)]
            void _CodeName([in] BSTR rhs);
            [id(0x000001e6), propget, helpcontext(0x000101e6)]
            long Index();
            [id(0x0000027d), helpcontext(0x0001027d)]
            void Move(
                            [in, optional] VARIANT Before, 
                            [in, optional] VARIANT After);
            [id(0x0000006e), propget, helpcontext(0x0001006e)]
            BSTR Name();
            [id(0x0000006e), propput, helpcontext(0x0001006e)]
            void Name([in] BSTR rhs);
            [id(0x000001f6), propget, helpcontext(0x000101f6)]
            IDispatch* Next();
            [id(0x00000274), propget, hidden, helpcontext(0x00010274)]
            BSTR OnDoubleClick();
            [id(0x00000274), propput, hidden, helpcontext(0x00010274)]
            void OnDoubleClick([in] BSTR rhs);
            [id(0x00000407), propget, hidden, helpcontext(0x00010407)]
            BSTR OnSheetActivate();
            [id(0x00000407), propput, hidden, helpcontext(0x00010407)]
            void OnSheetActivate([in] BSTR rhs);
            [id(0x00000439), propget, hidden, helpcontext(0x00010439)]
            BSTR OnSheetDeactivate();
            [id(0x00000439), propput, hidden, helpcontext(0x00010439)]
            void OnSheetDeactivate([in] BSTR rhs);
            [id(0x000003e6), propget, helpcontext(0x000103e6)]
            PageSetup* PageSetup();
            [id(0x000001f7), propget, helpcontext(0x000101f7)]
            IDispatch* Previous();
            [id(0x00000389), helpcontext(0x00010389)]
            void PrintOut(
                            [in, optional] VARIANT From, 
                            [in, optional] VARIANT To, 
                            [in, optional] VARIANT Copies, 
                            [in, optional] VARIANT Preview, 
                            [in, optional] VARIANT ActivePrinter, 
                            [in, optional] VARIANT PrintToFile, 
                            [in, optional] VARIANT Collate);
            [id(0x00010012), restricted, hidden]
            void _Dummy18();
            [id(0x0000011a), helpcontext(0x0001011a)]
            void Protect(
                            [in, optional] VARIANT Password, 
                            [in, optional] VARIANT DrawingObjects, 
                            [in, optional] VARIANT Contents, 
                            [in, optional] VARIANT Scenarios, 
                            [in, optional] VARIANT UserInterfaceOnly);
            [id(0x00000124), propget, helpcontext(0x00010124)]
            VARIANT_BOOL ProtectContents();
            [id(0x00010015), restricted, hidden]
            void _Dummy21();
            [id(0x00000487), propget, helpcontext(0x00010487)]
            VARIANT_BOOL ProtectionMode();
            [id(0x00010017), restricted, hidden]
            void _Dummy23();
            [id(0x0000011c), helpcontext(0x0001011c)]
            void SaveAs(
                            [in] BSTR Filename, 
                            [in, optional] VARIANT FileFormat, 
                            [in, optional] VARIANT Password, 
                            [in, optional] VARIANT WriteResPassword, 
                            [in, optional] VARIANT ReadOnlyRecommended, 
                            [in, optional] VARIANT CreateBackup, 
                            [in, optional] VARIANT AddToMru, 
                            [in, optional] VARIANT TextCodepage, 
                            [in, optional] VARIANT TextVisualLayout);
            [id(0x000000eb), helpcontext(0x000100eb)]
            void Select([in, optional] VARIANT Replace);
            [id(0x0000011d), helpcontext(0x0001011d)]
            void Unprotect([in, optional] VARIANT Password);
            [id(0x0000022e), propget, helpcontext(0x0001022e)]
            XlSheetVisibility Visible();
            [id(0x0000022e), propput, helpcontext(0x0001022e)]
            void Visible([in] XlSheetVisibility rhs);
            [id(0x00000561), propget, helpcontext(0x00010561)]
            Shapes* Shapes();
            [id(0x00000248), helpcontext(0x00010248)]
            void InsertFile(
                            [in] VARIANT Filename, 
                            [in, optional] VARIANT Merge);
    };

    [
      uuid(000208AE-0000-0000-C000-000000000046),
      helpcontext(0x0002006e),
      hidden
    ]
    dispinterface Modules {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x000000b5), helpcontext(0x000100b5)]
            Module* Add(
                            [in, optional] VARIANT Before, 
                            [in, optional] VARIANT After, 
                            [in, optional] VARIANT Count);
            [id(0x00000227), helpcontext(0x00010227)]
            void Copy(
                            [in, optional] VARIANT Before, 
                            [in, optional] VARIANT After);
            [id(0x00000076), propget, helpcontext(0x00010076)]
            long Count();
            [id(0x00000075), helpcontext(0x00010075)]
            void Delete();
            [id(0x00010007), restricted, hidden]
            void _Dummy7();
            [id(0x000000aa), propget, helpcontext(0x000100aa)]
            IDispatch* Item([in] VARIANT Index);
            [id(0x0000027d), helpcontext(0x0001027d)]
            void Move(
                            [in, optional] VARIANT Before, 
                            [in, optional] VARIANT After);
            [id(0xfffffffc), propget, helpcontext(0x0000fffc)]
            IUnknown* _NewEnum();
            [id(0x00000389), helpcontext(0x00010389)]
            void PrintOut(
                            [in, optional] VARIANT From, 
                            [in, optional] VARIANT To, 
                            [in, optional] VARIANT Copies, 
                            [in, optional] VARIANT Preview, 
                            [in, optional] VARIANT ActivePrinter, 
                            [in, optional] VARIANT PrintToFile, 
                            [in, optional] VARIANT Collate);
            [id(0x0001000c), restricted, hidden]
            void _Dummy12();
            [id(0x000000eb), helpcontext(0x000100eb)]
            void Select([in, optional] VARIANT Replace);
            [id(0x0000058a), propget, helpcontext(0x0001058a)]
            HPageBreaks* HPageBreaks();
            [id(0x0000058b), propget, helpcontext(0x0001058b)]
            VPageBreaks* VPageBreaks();
            [id(0x0000022e), propget, helpcontext(0x0001022e)]
            VARIANT Visible();
            [id(0x0000022e), propput, helpcontext(0x0001022e)]
            void Visible([in] VARIANT rhs);
            [id(00000000), propget, helpcontext(0x00010000)]
            IDispatch* _Default([in] VARIANT Index);
    };

    [
      uuid(000208AF-0000-0000-C000-000000000046),
      helpcontext(0x0002006f),
      hidden
    ]
    dispinterface DialogSheet {
        properties:
        methods:
            [id(0x60000000), restricted]
            void QueryInterface(
                            [in] GUID* riid, 
                            [out] void** ppvObj);
            [id(0x60000001), restricted]
            unsigned long AddRef();
            [id(0x60000002), restricted]
            unsigned long Release();
            [id(0x60010000), restricted]
            void GetTypeInfoCount([out] unsigned int* pctinfo);
            [id(0x60010001), restricted]
            void GetTypeInfo(
                            [in] unsigned int itinfo, 
                            [in] unsigned long lcid, 
                            [out] void** pptinfo);
            [id(0x60010002), restricted]
            void GetIDsOfNames(
                            [in] GUID* riid, 
                            [in] char** rgszNames, 
                            [in] unsigned int cNames, 
                            [in] unsigned long lcid, 
                            [out] long* rgdispid);
            [id(0x60010003), restricted]
            void Invoke(
                            [in] long dispidMember, 
                            [in] GUID* riid, 
                            [in] unsigned long lcid, 
                            [in] unsigned short wFlags, 
                            [in] DISPPARAMS* pdispparams, 
                            [out] VARIANT* pvarResult, 
                            [out] EXCEPINFO* pexcepinfo, 
                            [out] unsigned int* puArgErr);
            [id(0x00000094), propget, helpcontext(0x00010094)]
            Application* Application();
            [id(0x00000095), propget, helpcontext(0x00010095)]
            XlCreator Creator();
            [id(0x00000096), propget, helpcontext(0x00010096)]
            IDispatch* Parent();
            [id(0x00000130), helpcontext(0x00010130)]
            void Activate();
            [id(0x00000227), helpcontext(0x00010227)]
            void Copy(
                            [in, optional] VARIANT Before, 
                            [in, optional] VARIANT After);
            [id(0x00000075), helpcontext(0x00010075)]
            void Delete();
            [id(0x0000055d), propget, helpcontext(0x0001055d)]
            BSTR CodeName();
            [id(0x80010000), propget, helpcontext(0x80020000)]
            BSTR _CodeName();
            [id(0x80010000), propput, helpcontext(0x80020000)]
            void _CodeName([in] BSTR rhs);
            [id(0x000001e6), propget, helpcontext(0x000101e6)]
            long Index();
            [id(0x0000027d), helpcontext(0x0001027d)]
            void Move(
                            [in, optional] VARIANT Before, 
                            [in, optional] VARIANT After);
            [id(0x0000006e), propget, helpcontext(0x0001006e)]
            BSTR Name();
            [id(0x0000006e), propput, helpcontext(0x0001006e)]
            void Name([in] BSTR rhs);
            [id(0x000001f6), propget, helpcontext(0x000101f6)]
            IDispatch* Next();
            [id(0x00000274), propget, hidden, helpcontext(0x00010274)]
            BSTR OnDoubleClick();
            [id(0x00000274), propput, hidden, helpcontext(0x00010274)]
            void OnDoubleClick([in] BSTR rhs);
            [id(0x00000407), propget, hidden, helpcontext(0x00010407)]
            BSTR OnSheetActivate();
            [id(0x00000407), propput, hidden, helpcontext(0x00010407)]
            void OnSheetActivate([in] BSTR rhs);
            [id(0x00000439), propget, hidden, helpcontext(0x00010439)]
            BSTR OnSheetDeactivate();
            [id(0x00000439), propput, hidden, helpcontext(0x00010439)]
            void OnSheetDeactivate([in] BSTR rhs);
            [id(0x000003e6), propget, helpcontext(0x000103e6)]
            PageSetup* PageSetup();
            [id(0x000001f7), propget, helpcontext(0x000101f7)]
            IDispatch* Previous();
            [id(0x00000389), helpcontext(0x00010389)]
            void PrintOut(
                            [in, optional] VARIANT From, 
                            [in, optional] VARIANT To, 
                            [in, optional] VARIANT Copies, 
                            [in, optional] VARIANT Preview, 
                            [in, optional] VARIANT ActivePrinter, 
                            [in, optional] VARIANT PrintToFile, 
                            [in, optional] VARIANT Collate);
            [id(0x00000119), helpcontext(0x00010119)]
            void PrintPreview([in, optional] VARIANT EnableChanges);
            [id(0x0000011a), helpcontext(0x0001011a)]
            void Protect(
                            [in, optional] VARIANT Password, 
                            [in, optional] VARIANT DrawingObjects, 
                            [in, optional] VARIANT Contents, 
                            [in, optional] VARIANT Scenarios, 
                            [in, optional] VARIANT UserInterfaceOnly);
            [id(0x00000124), propget, helpcontext(0x00010124)]
            VARIANT_BOOL ProtectContents();
            [id(0x00000125), propget, helpcontext(0x00010125)]
            VARIANT_BOOL ProtectDrawingObjects();
            [id(0x00000487), propget, helpcontext(0x00010487)]
            VARIANT_BOOL ProtectionMode();
            [id(0x00000126), propget, helpcontext(0x00010126)]
            VARIANT_BOOL ProtectScenarios();
            [id(0x0000011c), helpcontext(0x0001011c)]
            void SaveAs(
                            [in] BSTR Filename, 
                            [in, optional] VARIANT FileFormat, 
                            [in, optional] VARIANT Password, 
                            [in, optional] VARIANT WriteResPassword, 
                            [in, optional] VARIANT ReadOnlyRecommended, 
                            [in, optional] VARIANT CreateBackup, 
                            [in, optional] VARIANT AddToMru, 
                            [in, optional] VARIANT TextCodepage, 
                            [in, optional] VARIANT TextVisualLayout);
            [id(0x000000eb), helpcontext(0x000100eb)]
            void Select([in, optional] VARIANT Replace);
            [id(0x0000011d), helpcontext(0x0001011d)]
            void Unprotect([in, optional] VARIANT Password);
            [id(0x0000022e), propget, helpcontext(0x0001022e)]
            XlSheetVisibility Visible();
            [id(0x0000022e), propput, helpcontext(0x0001022e)]
            void Visible([in] XlSheetVisibility rhs);
            [id(0x00000561), propget, helpcontext(0x00010561)]
            Shapes* Shapes();
            [id(0x0001001d), restricted, hidden]
            void _Dummy29();
            [id(0x000002f8), hidden, helpcontext(0x000102f8)]
            IDispatch* Arcs([in, optional] VARIANT Index);
            [id(0x0001001f), restricted, hidden]
            void _Dummy31();
            [id(0x00010020), restricted, hidden]
            void _Dummy32();
            [id(0x0000022d), hidden, helpcontext(0x0001022d)]
            IDispatch* Buttons([in, optional] VARIANT Index);
            [id(0x00010022), restricted, hidden]
            void _Dummy34();
            [id(0x00000590), propget, helpcontext(0x00010590)]
            VARIANT_BOOL EnableCalculation();
            [id(0x00000590), propput, helpcontext(0x00010590)]
            void EnableCalculation([in] VARIANT_BOOL rhs);
            [id(0x00010024), restricted, hidden]
            void _Dummy36();
            [id(0x00000424), helpcontext(0x00010424)]
            IDispatch* ChartObjects([in, optional] VARIANT Index);
            [id(0x00000338), hidden, helpcontext(0x00010338)]
            IDispatch* CheckBoxes([in, optional] VARIANT Index);
            [id(0x000001f9), helpcontext(0x000101f9)]
            void CheckSpelling(
                            [in, optional] VARIANT CustomDictionary, 
                            [in, optional] VARIANT IgnoreUppercase, 
                            [in, optional] VARIANT AlwaysSuggest, 
                            [in, optional] VARIANT IgnoreInitialAlefHamza, 
                            [in, optional] VARIANT IgnoreFinalYaa, 
                            [in, optional] VARIANT SpellScript);
            [id(0x00010028), restricted, hidden]
            void _Dummy40();
            [id(0x00010029), restricted, hidden]
            void _Dummy41();
            [id(0x0001002a), restricted, hidden]
            void _Dummy42();
            [id(0x0001002b), restricted, hidden]
            void _Dummy43();
            [id(0x0001002c), restricted, hidden]
            void _Dummy44();
            [id(0x0001002d), restricted, hidden]
            void _Dummy45();
            [id(0x00000283), propget, hidden, helpcontext(0x00010283)]
            VARIANT_BOOL DisplayAutomaticPageBreaks();
            [id(0x00000283), propput, hidden, helpcontext(0x00010283)]
            void DisplayAutomaticPageBreaks([in] VARIANT_BOOL rhs);
            [id(0x00000304), hidden, helpcontext(0x00010304)]
            IDispatch* Drawings([in, optional] VARIANT Index);
            [id(0x00000058), hidden, helpcontext(0x00010058)]
            IDispatch* DrawingObjects([in, optional] VARIANT Index);
            [id(0x00000344), hidden, helpcontext(0x00010344)]
            IDispatch* DropDowns([in, optional] VARIANT Index);
            [id(0x00000484), propget, helpcontext(0x00010484)]
            VARIANT_BOOL EnableAutoFilter();
            [id(0x00000484), propput, helpcontext(0x00010484)]
            void EnableAutoFilter([in] VARIANT_BOOL rhs);
            [id(0x00000591), propget, helpcontext(0x00010591)]
            XlEnableSelection EnableSelection();
            [id(0x00000591), propput, helpcontext(0x00010591)]
            void EnableSelection([in] XlEnableSelection rhs);
            [id(0x00000485), propget, helpcontext(0x00010485)]
            VARIANT_BOOL EnableOutlining();
            [id(0x00000485), propput, helpcontext(0x00010485)]
            void EnableOutlining([in] VARIANT_BOOL rhs);
            [id(0x00000486), propget, helpcontext(0x00010486)]
            VARIANT_BOOL EnablePivotTable();
            [id(0x00000486), propput, helpcontext(0x00010486)]
            void EnablePivotTable([in] VARIANT_BOOL rhs);
            [id(0x00000001), helpcontext(0x00010001)]
            VARIANT Evaluate([in] VARIANT Name);
            [id(0xfffffffb), helpcontext(0x0000fffb)]
            VARIANT _Evaluate([in] VARIANT Name);
            [id(0x00010038), restricted, hidden]
            void _Dummy56();
            [id(0x00000592), helpcontext(0x00010592)]
            void ResetAllPageBreaks();
            [id(0x00000342), hidden, helpcontext(0x00010342)]
            IDispatch* GroupBoxes([in, optional] VARIANT Index);
            [id(0x00000459), hidden, helpcontext(0x00010459)]
            IDispatch* GroupObjects([in, optional] VARIANT Index);
            [id(0x00000349), hidden, helpcontext(0x00010349)]
            IDispatch* Labels([in, optional] VARIANT Index);
            [id(0x000002ff), hidden, helpcontext(0x000102ff)]
            IDispatch* Lines([in, optional] VARIANT Index);
            [id(0x00000340), hidden, helpcontext(0x00010340)]
            IDispatch* ListBoxes([in, optional] VARIANT Index);
            [id(0x000001ba), propget, helpcontext(0x000101ba)]
            Names* Names();
            [id(0x0000031f), helpcontext(0x0001031f)]
            IDispatch* OLEObjects([in, optional] VARIANT Index);
            [id(0x00010041), restricted, hidden]
            void _Dummy65();
            [id(0x00010042), restricted, hidden]
            void _Dummy66();
            [id(0x00010043), restricted, hidden]
            void _Dummy67();
            [id(0x0000033a), hidden, helpcontext(0x0001033a)]
            IDispatch* OptionButtons([in, optional] VARIANT Index);
            [id(0x00010045), restricted, hidden]
            void _Dummy69();
            [id(0x00000321), hidden, helpcontext(0x00010321)]
            IDispatch* Ovals([in, optional] VARIANT Index);
            [id(0x000000d3), helpcontext(0x000100d3)]
            void Paste(
                            [in, optional] VARIANT Destination, 
                            [in, optional] VARIANT Link);
            [id(0x00000403), helpcontext(0x00010403)]
            void PasteSpecial(
                            [in, optional] VARIANT Format, 
                            [in, optional] VARIANT Link, 
                            [in, optional] VARIANT DisplayAsIcon, 
                            [in, optional] VARIANT IconFileName, 
                            [in, optional] VARIANT IconIndex, 
                            [in, optional] VARIANT IconLabel);
            [id(0x00000303), hidden, helpcontext(0x00010303)]
            IDispatch* Pictures([in, optional] VARIANT Index);
            [id(0x0001004a), restricted, hidden]
            void _Dummy74();
            [id(0x0001004b), restricted, hidden]
            void _Dummy75();
            [id(0x0001004c), restricted, hidden]
            void _Dummy76();
            [id(0x00000306), hidden, helpcontext(0x00010306)]
            IDispatch* Rectangles([in, optional] VARIANT Index);
            [id(0x0001004e), restricted, hidden]
            void _Dummy78();
            [id(0x0001004f), restricted, hidden]
            void _Dummy79();
            [id(0x00000599), propget, helpcontext(0x00010599)]
            BSTR ScrollArea();
            [id(0x00000599), propput, helpcontext(0x00010599)]
            void ScrollArea([in] BSTR rhs);
            [id(0x0000033e), hidden, helpcontext(0x0001033e)]
            IDispatch* ScrollBars([in, optional] VARIANT Index);
            [id(0x00010052), restricted, hidden]
            void _Dummy82();
            [id(0x00010053), restricted, hidden]
            void _Dummy83();
            [id(0x00000346), hidden, helpcontext(0x00010346)]
            IDispatch* Spinners([in, optional] VARIANT Index);
            [id(0x00010055), restricted, hidden]
            void _Dummy85();
            [id(0x00010056), restricted, hidden]
            void _Dummy86();
            [id(0x00000309), hidden, helpcontext(0x00010309)]
            IDispatch* TextBoxes([in, optional] VARIANT Index);
            [id(0x00010058), restricted, hidden]
            void _Dummy88();
            [id(0x00010059), restricted, hidden]
            void _Dummy89();
            [id(0x0001005a), restricted, hidden]
            void _Dummy90();
            [id(0x0000058a), propget, helpcontext(0x0001058a)]
            HPageBreaks* HPageBreaks();
            [id(0x0000058b), propget, helpcontext(0x0001058b)]
            VPageBreaks* VPageBreaks();
            [id(0x0000059a), propget, helpcontext(0x0001059a)]
            QueryTables* QueryTables();
            [id(0x0000059b), propget, helpcontext(0x0001059b)]
            VARIANT_BOOL DisplayPageBreaks();
            [id(0x0000059b), propput, helpcontext(0x0001059b)]
            void DisplayPageBreaks([in] VARIANT_BOOL rhs);
            [id(0x0000023f), propget, helpcontext(0x0001023f)]
            Comments* Comments();
            [id(0x00000571), propget, helpcontext(0x00010571)]
            Hyperlinks* Hyperlinks();
            [id(0x0000059c), helpcontext(0x0001059c)]
            void ClearCircles();
            [id(0x0000059d), helpcontext(0x0001059d)]
            void CircleInvalid();
            [id(0x00000288), propget, hidden, helpcontext(0x00010288)]
            long DisplayRightToLeft();
            [id(0x00000288), propput, hidden, helpcontext(0x00010288)]
            void DisplayRightToLeft([in] long rhs);
            [id(0x00000319), propget, helpcontext(0x00010319)]
            AutoFilter* AutoFilter();
            [id(0x00000359), propget, helpcontext(0x00010359)]
            VARIANT DefaultButton();
            [id(0x00000359), propput, helpcontext(0x00010359)]
            void DefaultButton([in] VARIANT rhs);
            [id(0x00000347), propget, hidden, helpcontext(0x00010347)]
            DialogFrame* DialogFrame();
            [id(0x0000033c), hidden, helpcontext(0x0001033c)]
            IDispatch* EditBoxes([in, optional] VARIANT Index);
            [id(0x0000032e), propget, helpcontext(0x0001032e)]
            VARIANT Focus();
            [id(0x0000032e), propput, helpcontext(0x0001032e)]
            void Focus([in] VARIANT rhs);
            [id(0x0000032d), helpcontext(0x0001032d)]
            VARIANT_BOOL Hide([in, optional] VARIANT Cancel);
            [id(0x000001f0), helpcontext(0x000101f0)]
            VARIANT_BOOL Show();
    };
