.TH betawc 1 "Feb-20-1996" "MBS r3.1" "Mjolner Informatics" 
.\"  Copyright (c) 1995-96 Mjolner Informatics
.de BP
.sp
.ti \-.2i
\(**
..

.SH NAME
betawc \- BETA fragment analyser
.SH SYNOPSIS
.hy 0
.na
.B betawc
.RB "[\|" options "\|]"
.IR file ...
.ad b
.hy 1
.PP
.SH AVAILABILITY
The Mjolner BETA fragment analyzer is available as part of the Mjolner
BETA System from Mjolner Informatics.
.PP
.SH DESCRIPTION
.I betawc
is a BETA fragment analyzer.
.I betawc
is used to find out how many fragment groups, how many fragment forms,
how many lines of code, how many words, and how many characters are in
the dependency graph of the specified fragment.

Furthermore, 
.I betawc
tries to evaluate which libraries are used in the specified fragment
(either directly or indirectly throughout the entire dependency
graph), and gives a listing of all fragment groups found during the
analysis of the dependency graph of the specified fragment.

During the analysis of the dependency, 
.I betawc
will give proper warnings of suspicious library versions, in the sense
that there seems to be two versions of the same library in use in the
same dependency graph.

.I betawc
works by traversing the dependency graph of the fragment graph,
following ORIGIN, INCLUDE, BODY and MDBODY fragment links, starting
at the fragment specified in the file given as argument to 
.I betawc.
During this traversal (identical to the dependency analysis conducted
by the BETA compiler), 
.I betawc
selects the fragments to be included in the further analysis (count of
fragment forms, etc.).

The different 
.I betawc
options may be used to control the part of the
dependency graph that are analysed, and the types of analysis
conducted (see below).
.PP
.SH OPTIONS

.TP
\--all
same as --conflict --full --list
.TP
\--conflict
check for conflicts
.TP
\--full
include standard files (files located in /users/beta)
.TP
\--exclude str
exclude all files containing str. Note, that str may be any egrep pattern
.TP
\--include str
include all files containing str. Note, that str may be any egrep pattern
.TP
\--list
list the fragment groups in the dependency graph.
.TP
\--help
Print this help info
.PP
.SH ENVIRONMENT
The
.I betawc
recognizes the environment variable $BETALIB. Please note
that this variable is given default value in the Bourne Shell
script 
.I $BETALIB/configuration/r3.0/env.sh
.TP
.B BETALIB
Specifies where 
.I ~beta
is located.  If not set,
.I beta
is assumed to be a username, and 
.I ~beta
being the home directory of that user.  Is used by many tools in the Mjolner
BETA System.

.PP
.SH SEE ALSO
.I beta(1)
- BETA Compiler
.br
.sp
.I valhalla(1)
- Mjolner BETA Source-Level Debugger
.br
.sp
.I betatar(1)
- BETA tar(1) front-end
.br
.sp
.I sif(1)
- Hyper-Structure Editor - to appear
.PP
.SH AUTHORS
The BETA fragment analyzer is developed by Mjolner Informatics as part
of the Mjolner BETA System.

Questions, bug-reports, etc. may be directed to support@mjolner.dk if the
local support organization cannot find solutions to the problems.

For more information of the Mjolner BETA System, please contact
Mjolner Informatics, Science Park Aarhus, Gustav Wieds Vej 10, DK-8000
Aarhus C, Denmark, phone: +45 86 20 20 00, fax: +45 86 20 12 22,
e-mail: info@mjolner.dk.
