.TH valhalla 1 "Sept-15-1995" "MBS r3.1" "Mjolner Informatics" 

.SH NAME
valhalla \- Mjolner BETA Source-Level Debugger (version 1.3)
.SH SYNOPSIS
.B valhalla 
[
.I executable
]
.PP
The 
.I executable 
parameter is optional, and should only be used if the program to debug does
not take command line parameters. Otherwise, start valhalla without parameters,
and enter program name and parameters when prompted.
.PP
.SH AVAILABILITY
The Mjolner BETA Debugger is available as part of the Mjolner BETA System from
Mjolner Informatics. 
.PP
.SH DESCRIPTION
.I valhalla
is the source level debugger for the Mjolner BETA System. Valhalla includes
the following functionality:
.TP
.B Program control
by setting breakpoints and single stepping on BETA source level.
.TP 
.B Static browsing 
of program text by following semantic links. Semantic links include super 
pattern relationships, SLOT bindings, and links from name applications to 
the corresponding declarations.
.TP
.B Dynamic browsing
of call chains and object states of the stopped BETA 
program execution.
.PP
.SH OPTIONS
No command line options are supported.
.SH ENVIRONMENT
.TP
.B BETARS
Corresponds to
.B BETART
(see beta(1)). The contents of the 
.B BETARS
environment variable is passed in 
.B BETART
to the debugged program. 
.B BETARS
is needed since the contents of
.B BETART
affects the behaviour of valhalla itself.
.PP
.SH SEE ALSO
.I beta(1)
- BETA Compiler
.br
.sp
.I betawc(1)
- BETA fragment analyzer
.br
.sp
.I betatar(1)
- BETA tar(1) front-end
.br
.sp
.I sif(1)
- Hyper-Structure Editor - to appear
.I "The Mjolner BETA System - Valhalla: The BETA Source-level Debugger - User's Guide,"
Mjolner Informatics Report: MIA 92-12.
.PP
.SH BUGS
A number of new features of the beta compiler version 5.0 are not supported 
by the current valhalla version. Most notably this includes dopart slots
and inserted items. For details, see [MIA 92-12].
.PP
.SH AUTHORS
Valhalla is developed by Mjolner Informatics as part of the Mjolner
BETA System.  
.PP
Questions, bug-reports, etc. may be directed to support@mjolner.dk if the
local support organization cannot find solutions to the problems.

For more information of the Mjolner BETA System, please contact
Mjolner Informatics, Science Park Aarhus, Gustav Wieds Vej 10, DK-8000 Aarhus C,
Denmark, phone: +45 86 20 20 00, fax: +45 86 20 12 22, e-mail:
info@mjolner.dk.
