
The content of '.' is: 
Directory: .
Directory: ..
Directory: CVS
File:      diradm
File:      diradm.a2s
File:      diradm.ast
File:      diradm.bet
File:      findentry
File:      findentry.a2s
File:      findentry.ast
File:      findentry.bet
File:      foo
Directory: foodir
File:      listdir
File:      listdir.a2s
File:      listdir.ast
File:      listdir.bet
File:      scandir
File:      scandir.a2s
File:      scandir.ast
File:      scandir.bet
Directory: ${objdir}
