'^([a-zA-Z])[a-zA-Z_0-9]+$' is matched by 'p9'
'^([a-zA-Z])[a-zA-Z_0-9]+$' is matched by 'This_is_a_variable_name_2'
'^([a-zA-Z])[a-zA-Z_0-9]+$' is not matched by '9p'
'^([a-zA-Z])[a-zA-Z_0-9]+$' is not matched by 'p 9'
***Test text: 
Wer der Philosophie Wissenschaftlichkeit im Sinne rationeller
und argumentativ geschlossener Diskursivität abverlangt,
wird die Frage, ob denn nun Dichter Philosophen seien, in
letzter Instanz verneinen müssen.
**First capital letter
Match 'W' (position 1-1)
**First capital letter after position 10 in text
Match 'W' (position 21-21)
**First capital letter after position 9 in text
Match 'P' (position 9-9)
**All the capital letters in text
WPWSDFDPI
**First set of consecutive vowels
Match 'ie' (position 18-19)
**Job change
Wer der Philosophie Wissenschaftlichkeit im Sinne rationeller
und argumentativ geschlossener Diskursivität abverlangt,
wird die Frage, ob denn nun Informatiker Philosophen seien, in
letzter Instanz verneinen müssen.
**Childrens song version
Wir dir Philisiphii Wissinschiftlichkiit im Sinni ritiinillir
ind irgimintitiv gischlissinir Diskirsivitit ibvirlingt,
wird dii Frigi, ib dinn nin Dichtir Philisiphin siiin, in
litztir Instinz virniinin missin.
**Case insensitive and case preserving childrens song version
War dar Phalasaphaa Wassanschaftlachkaat am Sanna rataanallar
and argamantatav gaschlassanar Daskarsavatat abvarlangt,
ward daa Fraga, ab dann nan Dachtar Phalasaphan saaan, an
latztar Anstanz varnaanan massan.
**Words
Wer
der
Philosophie
Wissenschaftlichkeit
im
Sinne
rationeller
und
argumentativ
geschlossener
Diskursivität
abverlangt
wird
die
Frage
ob
denn
nun
Dichter
Philosophen
seien
in
letzter
Instanz
verneinen
müssen
***Test text: 
> Kan du spesifisere hva du mener med "naturtalent"/egnet?

Thore kan sikkert det på egenhånd, men jeg pleier å si at
bugs er hint fra maskinen til mennesket om at mennesket ikke
har skjønt maskinen.  Et naturtalent av en programmerer
skjønner maskinen.  En programmerer som sliter med bugs i
månedsvis, burde ta et hint.
**HTMLise
&gt; Kan du spesifisere hva du mener med "naturtalent"/egnet?<br>
<br>
Thore kan sikkert det p&#229; egenh&#229;nd, men jeg pleier &#229; si at<br>
bugs er hint fra maskinen til mennesket om at mennesket ikke<br>
har skj&#248;nt maskinen.  Et naturtalent av en programmerer<br>
skj&#248;nner maskinen.  En programmerer som sliter med bugs i<br>
m&#229;nedsvis, burde ta et hint.
***Test text: 
root:x:0:0:Da Boss:/root:/bin/bash
**Split /etc/passwd entry into fields, put in a list, dump list
root
x
0
0
Da Boss
/root
/bin/bash
**Split /etc/passwd entry into named fields
User name is root, hashed password is x, uid/gid is 0/0
Real name is 'Da Boss', home directory is /root, shell is "/bin/bash"
***Test text: 
Lars  Balker Rasmussen
Erik Haldane  Corry
Flemming Gram  Christensen
Mick Jagger
Peter da Silva
Lars von Trier
Georg Jensen
Jeeves
William Jefferson Clinton
**Recognise given and surnames
"Balker Rasmussen, Lars"
"Corry, Erik Haldane"
"Gram Christensen, Flemming"
"Jagger, Mick"
"da Silva, Peter"
"von Trier, Lars"
"Jensen, Georg"
"Jeeves"
"Clinton, William Jefferson"
