Replace: Replace: 78 in: Replace: 78 in: dhjdhj305j78dhjdj87jjd788nds with: Replace: 78 in: dhjdhj305j78dhjdj87jjd788nds with: !!!! gives: dhjdhj305j!!!!dhjdj87jjd788nds
Replace: 78 in: dhjdhj305j78dhjdj87jjd788nds with: !!!! gives: dhjdhj305j!!!!dhjdj87jjd!!!!8nds
	No match
Replace: 78 in: dhjdhj305j78dhjdj87jjd788nds with: Replace: 78 in: dhjdhj305j78dhjdj87jjd788nds with: HUGO gives: dhjdhj305jHUGOdhjdj87jjd788nds
Replace: 78 in: dhjdhj305j78dhjdj87jjd788nds with: HUGO gives: dhjdhj305jHUGOdhjdj87jjdHUGO8nds
	No match
Replace: 78 in: dhjdhj305j78dhjdj87jjd788nds with: Replace: 78 in: Replace: 