#!/bin/sh -f
if test -f /usr/bin/sun
then MACHINE=SUN3 objdir=sun3
	echo generator sab
	generator sab
	echo bobsit sab-parser 
	bobsit sab-parser 
	echo makepretty++ sab
	makepretty++ sab
	echo morepretty++ sab
	morepretty++ sab
else
  	echo BOBS must be run on a SUN3
fi
