#!/usr/local/bin/perl -s

use File::Find;

$betalib = $ENV{'BETALIB'};

sub rebuild()
{
    $f = $File::Find::name;
    next unless $f =~ m%\.bet$%;
    $f =~ s%\.bet$%%; # strip suffix
    $f =~ s%^\./%%; # strip ./ prefix
    next if ($f =~ m%/_[^/]+$%); # skip wrapper classes
    next if ($f =~ m%betahelpers$%); # skip helpers
    print "************ $f ************\n";
    system "cd $betalib/compiler/GENERATOR/JAVA; java2beta -F $f";
}

find(\&rebuild, ".");
