#!/usr/local/bin/perl -s

my @files;

use File::Find;

$betalib = $ENV{'BETALIB'};

sub check()
{
    $f = $File::Find::name;
    next unless $f =~ m%\.bet$%;
    $f =~ s%\.bet$%%; # strip suffix
    $f =~ s%^\./%%; # strip ./ prefix
    next if ($f =~ m%/_[^/]+$%); # skip wrapper classes
    next if ($f =~ m%betahelpers$%); # skip helpers
    push @files, $f;
}

find(\&check, ".");

foreach $f (@files){
    print "************ $f ************\n";
    if (-M "$f.bet" <= 0){
	print "*** Skipped $f.bet: already modified by this rebuild\n";
    } else {
	system "cd $betalib/compiler/GENERATOR/JAVA; java2beta -F $f";
    }
}
