#!/bin/sh

#--------- Configuration: ------

# Directories containing source files:
SRC="${BETALIB}/guienv"

# Files to include in interface. The order given here will
# be the order they appear in in the generated interface.
FILES="\
multimedia/cdplayer.bet \
multimedia/movieplayer.bet \
"

MAKEINT=../../bin/beta2int.perl
MAKEHTML=../../bin/int2html.perl

. ../../bin/makeHTML.sh
