#!/bin/sh
#
#
# recompile all.bet on all supported platforms

BETA="beta -nolink"			# what compiler to use
SYSTEM=/users/beta/betaast/v5.0		# where to find source

# machines to use
sun4s=fraxinus
sun4=chrysler
hpux8=blanche
hpux9mc=thelma
hpux9pa=angers
linux=ceres

platforms="$sun4s $sun4 $hpux9pa $hpux8 $hpux9mc $linux"

compile()
{
  if [ $5 = "check" ]
  then
	(rsh $1 "setenv BETALIB /users/beta; \
		cd $2; \
		/users/beta/bin/${BETA} $3 $4\
		" 2>&1) | tee all.$5.lst
  else
	(rsh $1 "setenv BETALIB /users/beta; \
		cd $2; \
		/users/beta/bin/${BETA} $3 $4\
		" 2>&1) >all.$5.lst &
  fi
}

echo ""
echo "--- Checking all.bet on $sun4s:"

compile $sun4s ${SYSTEM} " -nocode" all "check"

echo ""
echo "--- Compiling all.bet (in batch) on all UNIX platforms: "
echo "--- $platforms"

if [ `whoami` != "beta" ]
then
	echo ""
	echo $0: MUST BE RUN AS USER BETA.
	exit 1
fi

for p in $platforms
do
	case $p in
	$sun4s)   target=SUN4S
		  ;;
	$sun4)    target=SUN4
		  ;;
	$hpux9pa) target=HPUX9PA
		  ;;
	$hpux9mc) target=HPUX9MC
		  ;;
	$hpux8)   target=HPUX8
		  ;;
	$linux)   target=LINUX
		  ;;
	esac

	echo $target: rsh $p
	compile $p ${SYSTEM} "" all $p

done

echo "--- Consult the files: all.*.lst for the results"
echo "--- Notice that mac and nti are not made by this script."