BETA=beta
VERSION=v5.0

all:
	$(BETA) -q -w all.bet

tags:
	etags --output=ALLTAGS \
/users/beta/betaast/$(VERSION)/*.bet \
/users/beta/betaast/$(VERSION)/private/*.bet \
/users/beta/pretty/$(VERSION)/*.bet \
/users/beta/pretty/$(VERSION)/private/*.bet \
/users/beta/mps/$(VERSION)/*.bet \
/users/beta/mps/$(VERSION)/demo/beta/*.bet \
/users/beta/mps/$(VERSION)/demo/expr/*.bet \
/users/beta/mps/$(VERSION)/demo/general/*.bet \
/users/beta/mps/$(VERSION)/private/*.bet
