#!/bin/sh
echo Recompiling all tests...

beta testcursor.bet

beta testpatternparser.bet

beta testsensitivity.bet

beta testsimplestatementset.bet

beta teststatementset.bet

beta testtransact.bet

./testall $1 $2 $3
