#!/bin/sh

echo testcursor
testcursor $1 $2 $3

echo testpatternparser
testpatternparser $1 $2 $3

echo testsensitivity $1 $2 $3
testsensitivity $1 $2 $3

echo testsimplestatementset $1 $2 $3
testsimplestatementset $1 $2 $3

echo teststatementset $1 $2 $3
teststatementset $1 $2 $3

echo testtransact $1 $2 $3
testtransact $1 $2 $3


